### ISSUE TITLE
IE11 https - "Access is denied" on graph

### ISSUE THREAD

**Issue by albertdabrowski** [grafana/grafana#10357]
Hi,
I've read that You really do not support IE. Anyway I need to use it and found a real blocker for me.
When I open graph it responds with "Access is denied". 
Important to mention:
* if this is http then it works if I enable https then such issue occurs (for testing just used self-signed)
* checked on localhost as well as different ip binded (the same issue occurs) 
* later also set-up haproxy in front to have just http for grafana and https in haproxy, but did not change, so really seems like an UI issue?

This is not network issue (all Get's are 200 (ok)), in Inspector and also grafana show me this stacktrace

"Error: Access is denied.

   at Anonymous function (https://localhost/public/build/vendor.2305a8e1d478628b1297.js:43:54273)
   at g (https://localhost/public/build/vendor.2305a8e1d478628b1297.js:43:51743)
   at u (https://localhost/public/build/vendor.2305a8e1d478628b1297.js:43:49825)
   at u (https://localhost/public/build/vendor.2305a8e1d478628b1297.js:43:68718)
   at Anonymous function (https://localhost/public/build/vendor.2305a8e1d478628b1297.js:43:69127)
   at f.prototype.$digest (https://localhost/public/build/vendor.2305a8e1d478628b1297.js:43:74824)
   at f.prototype.$apply (https://localhost/public/build/vendor.2305a8e1d478628b1297.js:43:76636)
   at Anonymous function (https://localhost/public/build/0.be20b78823b4c9d93a84.js:7:171041)
   at Anonymous function (https://localhost/public/build/vendor.2305a8e1d478628b1297.js:15:579177)
   at Anonymous function (https://localhost/public/build/vendor.2305a8e1d478628b1297.js:15:579049)
"
I checked this on Chrome, Firefox and there are no problems. Also checked few options in IE11 but did not help.

- What Grafana version are you using? `v4.6.3`
- What datasource are you using?`Prometheus`
- What OS are you running grafana on?`Win 8.1`
- What did you do?`Run dashboard on IE11`
- What was the expected result?`Should see a correct graph`
- What happened instead?`No graph displayed`

**Comment by torkelo** [comment]
could be caused by your self signed cert, try adding your custom cert as a trusted cert.

What's your data source options? direct access or proxy access? Try proxy access (then the call to prometheus will be proxied by Grafana)

**Comment by albertdabrowski** [comment]
Bingo!!! Changed to proxy and it works.
So understand that it could be caused by the fact that on UI we call from secure to direct non-secure prometheus backend, right?

Thanks so much
