### ISSUE TITLE
Bug (v5-beta1) TypeError: e.match is not a function when adding a chart

### ISSUE THREAD

**Issue by jeromepin** [grafana/grafana#10858]
**- What Grafana version are you using?**
5.0.0-beta1 but master has it too

**- What datasource are you using?**
Prometheus 2.1.0

**- What OS are you running grafana on?**
The official container, on a Debian 9 host

**- What did you do?**
I added my Prometheus datasource using `provisioning/datasources` : 

```dockerfile
FROM grafana/grafana:5.0.0-beta1

COPY datasources /etc/grafana/provisioning/datasources
```
```yaml
datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  org_id: 1
  url: http://172.17.0.1:9090
  is_default: true
  json_data:
    timeInterval: 10
  editable: true
```
The datasource is properly added and the connection between Grafana and Prometheus works well.
Then I tried to add a Graph Panel in a new dashboard. 

**- What was the expected result?**

A chart should be displayed. 

**- What happened instead?**

The following error is shown in Chrome Dev Tools :

```javascript
Panel data error: TypeError: e.match is not a function                      metrics_panel_ctrl.ts:156
    at Object.s.describe_interval (kbn.ts:183)
    at Object.s.interval_to_ms (kbn.ts:196)
    at Object.s.calculateInterval (kbn.ts:168)
    at e.calculateInterval (metrics_panel_ctrl.ts:191)
    at e.updateTimeRange (metrics_panel_ctrl.ts:178)
    at u (angular.js:17145)
    at angular.js:17193
    at d.$digest (angular.js:18331)
    at d.$apply (angular.js:18628)
    at angular.js:18931
```

And the same one in Grafana (in the graph inspector) :

```javascript
TypeError: e.match is not a function
    at Object.s.describe_interval (http://localhost:3000/public/build/app.09ca0886c7c907fe8d09.js:1:20998)
    at Object.s.interval_to_ms (http://localhost:3000/public/build/app.09ca0886c7c907fe8d09.js:1:21270)
    at Object.s.calculateInterval (http://localhost:3000/public/build/app.09ca0886c7c907fe8d09.js:1:20825)
    at e.calculateInterval (http://localhost:3000/public/build/0.7fcd053fbf0c943e1675.js:7:16302)
    at e.updateTimeRange (http://localhost:3000/public/build/0.7fcd053fbf0c943e1675.js:7:16062)
    at u (http://localhost:3000/public/build/vendor.d55cccadcb21996d6baf.js:87:69119)
    at http://localhost:3000/public/build/vendor.d55cccadcb21996d6baf.js:87:69565
    at d.$digest (http://localhost:3000/public/build/vendor.d55cccadcb21996d6baf.js:87:75262)
    at http://localhost:3000/public/build/vendor.d55cccadcb21996d6baf.js:87:76888
    at i (http://localhost:3000/public/build/vendor.d55cccadcb21996d6baf.js:87:21978)
```

There is no network request involved.

**Comment by torkelo** [comment]
timeInterval should be a string time interval, example "10s"
