### ISSUE TITLE
errors running npm run watch on mac osx

### ISSUE THREAD

**Issue by paixaop** [grafana/grafana#11172]
Read before posting: 

Please include this information:
- What Grafana version are you using?
5.0.1-pre1

- What datasource are you using?
Prometheus
- What OS are you running grafana on?
Mac osx

- What did you do?
npm run watch

- What was the expected result?

- What happened instead?
```
  [22] ./public/app/core/config.ts 665 bytes {2} [built]
  [29] (webpack)/buildin/global.js 509 bytes {1} [built]
 [148] (webpack)/buildin/module.js 517 bytes {1} [built]
 [178] (webpack)/buildin/amd-define.js 88 bytes {1} [built]
 [228] ./public/app/core/core.ts 3.38 kB {2} [built]
 [539] ./public/app/index.ts 39 bytes {2} [built]
 [540] ./public/app/app.ts 4.71 kB {2} [built]
 [742] (webpack)/buildin/amd-options.js 82 bytes {1} [built]
 [763] ./public/vendor/bootstrap/bootstrap.js 41 kB {2} [built]
 [764] ./public/vendor/angular-ui/ui-bootstrap-tpls.js 45.8 kB {2} [built]
 [765] ./public/vendor/angular-other/angular-strap.js 6.53 kB {2} [built]
 [766] ./node_modules/moment/locale ^\.\/.*$ 2.95 kB {1} [optional] [built]
[1457] ./public/sass/grafana.dark.scss 41 bytes {4} [built]
[1458] ./public/sass/grafana.light.scss 41 bytes {3} [built]
[1459] multi jquery angular angular-bindonce angular-native-dragdrop angular-routeangular-sanitize babel-polyfill brace classnames clipboard d3 d3-scale-chromatic eventemitter3 file-saver lodash mobx mobx-react mobx-state-tree moment mousetrap mousetrap-global-bind perfect-scrollbar prop-types react react-dom react-grid-layout-grafana react-highlight-words react-popper react-select react-sizeme react-transition-group remarkable rst2html tether tether-drop tinycolor2 448 bytes {1} [built]
    + 1719 hidden modules

ERROR in multi jquery angular angular-bindonce angular-native-dragdrop angular-route angular-sanitize babel-polyfill brace classnames clipboard d3 d3-scale-chromaticeventemitter3 file-saver lodash mobx mobx-react mobx-state-tree moment mousetrap mousetrap-global-bind perfect-scrollbar prop-types react react-dom react-grid-layout-grafana react-highlight-words react-popper react-select react-sizeme react-transition-group remarkable rst2html tether tether-drop tinycolor2
Module not found: Error: Can't resolve 'rst2html' in '/Users/pedro/IDrive-Sync/work/go/src/github.com/grafana/grafana'
 @ multi jquery angular angular-bindonce angular-native-dragdrop angular-route angular-sanitize babel-polyfill brace classnames clipboard d3 d3-scale-chromatic eventemitter3 file-saver lodash mobx mobx-react mobx-state-tree moment mousetrap mousetrap-global-bind perfect-scrollbar prop-types react react-dom react-grid-layout-grafana react-highlight-words react-popper react-select react-sizeme react-transition-group remarkable rst2html tether tether-drop tinycolor2

ERROR in ./public/app/plugins/datasource/graphite/add_graphite_func.js
Module not found: Error: Can't resolve 'rst2html' in '/Users/pedro/IDrive-Sync/work/go/src/github.com/grafana/grafana/public/app/plugins/datasource/graphite'
 @ ./public/app/plugins/datasource/graphite/add_graphite_func.js 1:0-155:2
 @ ./public/app/plugins/datasource/graphite/query_ctrl.ts
 @ ./public/app/plugins/datasource/graphite/module.ts
 @ ./public/app/features/plugins/built_in_plugins.ts
 @ ./public/app/features/plugins/plugin_loader.ts
 @ ./public/app/features/plugins/plugin_component.ts
 @ ./public/app/features/plugins/all.ts
 @ ./public/app/features/all.js
 @ ./public/app/app.ts
 @ ./public/app/index.ts

ERROR in ./public/app/plugins/datasource/graphite/func_editor.js
Module not found: Error: Can't resolve 'rst2html' in '/Users/pedro/IDrive-Sync/work/go/src/github.com/grafana/grafana/public/app/plugins/datasource/graphite'
 @ ./public/app/plugins/datasource/graphite/func_editor.js 1:0-309:2
 @ ./public/app/plugins/datasource/graphite/query_ctrl.ts
 @ ./public/app/plugins/datasource/graphite/module.ts
 @ ./public/app/features/plugins/built_in_plugins.ts
 @ ./public/app/features/plugins/plugin_loader.ts
 @ ./public/app/features/plugins/plugin_component.ts
 @ ./public/app/features/plugins/all.ts
 @ ./public/app/features/all.js
 @ ./public/app/app.ts
 @ ./public/app/index.ts

[at-loader] Checking finished with 1 errors
[at-loader] ./node_modules/mobx-state-tree/dist/types/complex-types/model.d.ts:29:5
    TS2416: Property 'props' in type 'ModelType<S, T>' is not assignable to the same property in base type 'IModelType<S, T>'.
  Type '<SP, TP>(properties: { [K in keyof TP]: IType<any, TP[K]>; } & { [K in keyof SP]: IType<SP[K], an...' is not assignable to type '<SP, TP>(props: { [K in keyof TP]: TP[K] | IType<any, TP[K]>; } & { [K in keyof SP]: SP[K] | ITyp...'.
    Types of parameters 'properties' and 'props' are incompatible.
      Type '{ [K in keyof TP]: TP[K] | IType<any, TP[K]>; } & { [K in keyof SP]: SP[K] | IType<SP[K], any>; }' is not assignable to type '{ [K in keyof TP]: IType<any, TP[K]>; } & { [K in keyof SP]: IType<Snapshot<SP>[K], any>; }'.
        Type '{ [K in keyof TP]: TP[K] | IType<any, TP[K]>; } & { [K in keyof SP]:SP[K] | IType<SP[K], any>; }' is not assignable to type '{ [K in keyof TP]: IType<any, TP[K]>; }'.
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 ```

Grafana still works but it don't know if there are any side effects. What should I do to resolve this?
I double checked and rst2html module is installed and I added docutils with 

    brew install docutils

THANKS!

**Comment by bergquist** [comment]
Could you try.
```
rm -rf node_modules/
yarn install
npm run build
npm run watch
```

**Comment by paixaop** [comment]
Thanks. I ran

    rm -rf node_modules/
    yarn install
    npm run build

```
> grafana@5.0.1-pre1 build /Users/pedro/IDrive-Sync/work/go/src/github.com/grafana/grafana
> grunt build

grunt-cli: The grunt command line interface (v1.2.0)

Fatal error: Unable to find local grunt.

If you're seeing this message, grunt hasn't been installed locally to
your project. For more information about installing and configuring grunt,
please see the Getting Started guide:

http://gruntjs.com/getting-started
npm ERR! code ELIFECYCLE
npm ERR! errno 99
npm ERR! grafana@5.0.1-pre1 build: `grunt build`
npm ERR! Exit status 99
npm ERR! 
npm ERR! Failed at the grafana@5.0.1-pre1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

Then I ran 

    npm install --only=dev

and got:

```

> fsevents@1.1.3 install /Users/pedro/IDrive-Sync/work/go/src/github.com/grafana/grafana/node_modules/fsevents
> node install

[fsevents] Success: "/Users/pedro/IDrive-Sync/work/go/src/github.com/grafana/grafana/node_modules/fsevents/lib/binding/Release/node-v59-darwin-x64/fse.node" is installed via remote

> iltorb@1.3.10 install /Users/pedro/IDrive-Sync/work/go/src/github.com/grafana/grafana/node_modules/iltorb
> detect-libc prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info looking for local prebuild @ prebuilds/iltorb-v1.3.10-node-v59-darwin-x64.tar.gz
prebuild-install info looking for cached prebuild @ /Users/pedro/.npm/_prebuilds/https-github.com-MayhemYDG-iltorb-releases-download-v1.3.10-iltorb-v1.3.10-node-v59-darwin-x64.tar.gz
prebuild-install http request GET https://github.com/MayhemYDG/iltorb/releases/download/v1.3.10/iltorb-v1.3.10-node-v59-darwin-x64.tar.gz
prebuild-install http 404 https://github.com/MayhemYDG/iltorb/releases/download/v1.3.10/iltorb-v1.3.10-node-v59-darwin-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=9.3.0 runtime=node arch=x64 platform=darwin)
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/usr/local/bin/python" is v3.6.4, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:474:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:264:7)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:943:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:363:11)
gyp ERR! stack     at Socket.emit (events.js:159:13)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:568:12)
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/pedro/IDrive-Sync/work/go/src/github.com/grafana/grafana/node_modules/iltorb
gyp ERR! node -v v9.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
```

To solve the Python issue I ran virtualenv

    virtualenv -p /usr/bin/python2.7 pygrafana
    source ./pygrafana/bin/activate

reran 

    npm install --only=dev

and this time it ran with no errors, just some warnings when compiling 

```
CXX(target) Release/obj.target/iltorb/src/dec/stream_decode_worker.o
../src/dec/stream_decode_worker.cc:46:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    callback->Call(1, argv);
              ^
../../nan/nan.h:1567:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/dec/stream_decode_worker.cc:52:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    callback->Call(2, argv);
              ^
../../nan/nan.h:1567:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
2 warnings generated.
  CXX(target) Release/obj.target/iltorb/src/enc/stream_encode.o
  CXX(target) Release/obj.target/iltorb/src/enc/stream_encode_worker.o
../src/enc/stream_encode_worker.cc:47:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    callback->Call(1, argv);
              ^
../../nan/nan.h:1567:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/enc/stream_encode_worker.cc:53:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    callback->Call(2, argv);
              ^
../../nan/nan.h:1567:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
2 warnings generated.
```
Running `npm run build` I got:

```
npm run build

> grafana@5.0.1-pre1 build /Users/pedro/IDrive-Sync/work/go/src/github.com/grafana/grafana
> grunt build

Version 5.0.1-pre1
Running "clean:release" (clean) task
>> 0 paths cleaned.

Running "clean:build" (clean) task
>> 1 path cleaned.

Running "phantomjs" task

Running "copy:phantom_bin" (copy) task
Copied 1 file

Running "exec:webpack" (exec) task

[at-loader] Using typescript@2.7.2 from typescript and "tsconfig.json" from /Users/Pedro/IDrive-Sync/work/go/src/github.com/grafana/grafana/tsconfig.json.



[at-loader] Checking started in a separate process...
>> [at-loader] Checking finished with 1 errors
[ Error: [at-loader] ./node_modules/mobx-state-tree/dist/types/complex-types/model.d.ts:29:5 
    TS2416: Property 'props' in type 'ModelType<S, T>' is not assignable to the same property in base type 'IModelType<S, T>'.
  Type '<SP, TP>(properties: { [K in keyof TP]: IType<any, TP[K]>; } & { [K in keyof SP]: IType<SP[K], an...' is not assignable to type '<SP, TP>(props: { [K in keyof TP]: TP[K] | IType<any, TP[K]>; } & { [K in keyof SP]: SP[K] | ITyp...'.
    Types of parameters 'properties' and 'props' are incompatible.
      Type '{ [K in keyof TP]: TP[K] | IType<any, TP[K]>; } & { [K in keyof SP]: SP[K] | IType<SP[K], any>; }' is not assignable to type '{ [K in keyof TP]: IType<any, TP[K]>; } & { [K in keyof SP]: IType<Snapshot<SP>[K], any>; }'.
        Type '{ [K in keyof TP]: TP[K] | IType<any, TP[K]>; } & { [K in keyof SP]: SP[K] | IType<SP[K], any>; }' is not assignable to type '{ [K in keyof TP]: IType<any, TP[K]>; }'.
    at emitError (/Users/pedro/IDrive-Sync/work/go/src/github.com/grafana/grafana/node_modules/awesome-typescript-loader/src/instance.ts:457:45)
    at /Users/pedro/IDrive-Sync/work/go/src/github.com/grafana/grafana/node_modules/awesome-typescript-loader/src/instance.ts:490:43
    at Array.forEach (<anonymous>)
    at /Users/pedro/IDrive-Sync/work/go/src/github.com/grafana/grafana/node_modules/awesome-typescript-loader/src/instance.ts:490:27
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7) ]
>> Exited with code: 1.
>> Error executing child process: Error: Command failed: node ./node_modules/webpack/bin/webpack.js --config scripts/webpack/webpack.prod.js
>> 
>> [at-loader] Checking finished with 1 errors
Warning: Task "exec:webpack" failed. Use --force to continue.

Aborted due to warnings.
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! grafana@5.0.1-pre1 build: `grunt build`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the grafana@5.0.1-pre1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pedro/.npm/_logs/2018-03-09T20_39_24_237Z-debug.log
```

which hung for 5 minutes and sent my CPU to nearly 100% on all cores, and finally gave the error above.

**Comment by marefr** [comment]
Regarding grunt you need to do a `npm install -g grunt`.

Suggest you to do (again)
```
rm -rf node_modules/
yarn install --pure-lockfile
npm install -g grunt
npm run build
```

**Comment by daniellee** [comment]
Closing this - if you are still having problems then I can reopen it.
