### ISSUE TITLE
Failing silently when setting a future date range

### ISSUE THREAD

**Issue by clementgarnier** [grafana/grafana#1161]
Hi there – I'm surprised that this bug hasn't been reported yet, but I couldn't find any occurrences of this error in the issues.

Here are the reproduction steps:
1. Click on the date in the top right corner
2. Select "Custom"
3. Choose a future date using the `From` date picker
4. Click "apply"

The dashboard does not refresh and the console shows the following error:

```
TypeError: Cannot read property 'getHours' of undefined
    at k (http://example.com/app/app.fea68443.js:24:28485)
    at j (http://example.com/app/app.fea68443.js:24:28045)
    at l.a.setAbsoluteTimeFilter (http://example.com/app/app.fea68443.js:24:27634)
    at Array.<anonymous> (http://example.com/app/app.fea68443.js:11:11572)
    at http://example.com/app/app.fea68443.js:11:8760
    at e (http://example.com/app/app.fea68443.js:11:24272)
    at l.$eval (http://example.com/app/app.fea68443.js:10:3986)
    at l.$apply (http://example.com/app/app.fea68443.js:10:4264)
    at HTMLButtonElement.<anonymous> (http://example.com/app/app.fea68443.js:11:24324)
    at HTMLButtonElement._.event.dispatch (http://example.com/app/app.fea68443.js:6:1092) 
```

Currently running Grafana 1.9.0 RC1 and Google Chrome 39.0.2171.71 (64-bit) on Mac OS 10.9.5.

**Comment by torkelo** [comment]
this looks to be fixed, no more silent error.
