### ISSUE TITLE
Pie Chart v1.3.0 give JS ERROR "Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by EXANIX** [grafana/grafana#11916]
Grafana version - 4.6 (RPM grafana-5.0.4-1.x86_64)
datasource - Mysql (mariadb-5.5.50)
Grafana running on CentOS Linux release 7.4.1708 (kernel 3.10.0-693.21.1.el7.x86_64)
I try show me a simple "Pie Chart" version 1.3.0 in my web browser Google Chrome Version 58.0.3029.110 (64-bit) on CentOS 7.3.1611(kernel 3.10.0-514.21.1.el7.x86_64).
I expected to vision some "Pie". But I see a red triangle with a message
Message:
Cannot read property 'length' of undefined
Stack trace:
TypeError: Cannot read property 'length' of undefined
    at e.isMsResolutionNeeded (http://192.168.14.6:3000/public/build/app.a4b7f5a163ea89ff6420.js:1:17555)
    at new e (http://192.168.14.6:3000/public/build/app.a4b7f5a163ea89ff6420.js:1:14461)
    at PieChartCtrl.seriesHandler (http://192.168.14.6:3000/public/plugins/grafana-piechart-panel/piechart_ctrl.js:171:26)
    at Array.map (native)
    at PieChartCtrl.onDataReceived (http://192.168.14.6:3000/public/plugins/grafana-piechart-panel/piechart_ctrl.js:164:36)
    at o.emit (http://192.168.14.6:3000/public/build/vendor.2c3c591224fb193f7fd3.js:44:25754)
    at e.emit (http://192.168.14.6:3000/public/build/app.a4b7f5a163ea89ff6420.js:1:13162)
    at PieChartCtrl.e.handleQueryResult (http://192.168.14.6:3000/public/build/0.2ba40e7163b7f9a6ed4b.js:7:18131)
    at u (http://192.168.14.6:3000/public/build/vendor.2c3c591224fb193f7fd3.js:92:69119)
    at http://192.168.14.6:3000/public/build/vendor.2c3c591224fb193f7fd3.js:92:69565

On FireFox ESR 52.1.0 (64-bit) I got other JS Error
Message:
this.datapoints is undefined
Stack trace:
u</e.prototype.isMsResolutionNeeded@http://192.168.14.6:3000/public/build/app.a4b7f5a163ea89ff6420.js:1:17538
e@http://192.168.14.6:3000/public/build/app.a4b7f5a163ea89ff6420.js:1:14456
seriesHandler@http://192.168.14.6:3000/public/plugins/grafana-piechart-panel/piechart_ctrl.js:171:26
onDataReceived@http://192.168.14.6:3000/public/plugins/grafana-piechart-panel/piechart_ctrl.js:164:27
o.prototype.emit@http://192.168.14.6:3000/public/build/vendor.2c3c591224fb193f7fd3.js:44:25316
a</e.prototype.emit@http://192.168.14.6:3000/public/build/app.a4b7f5a163ea89ff6420.js:1:13149
[1523]/f</e.prototype.handleQueryResult@http://192.168.14.6:3000/public/build/0.2ba40e7163b7f9a6ed4b.js:7:18119
u@http://192.168.14.6:3000/public/build/vendor.2c3c591224fb193f7fd3.js:92:69119
l/<@http://192.168.14.6:3000/public/build/vendor.2c3c591224fb193f7fd3.js:92:69565
On/this.$get</d.prototype.$digest@http://192.168.14.6:3000/public/build/vendor.2c3c591224fb193f7fd3.js:92:75262
On/this.$get</d.prototype.$apply@http://192.168.14.6:3000/public/build/vendor.2c3c591224fb193f7fd3.js:92:77074
A/s<@http://192.168.14.6:3000/public/build/vendor.2c3c591224fb193f7fd3.js:92:73133
i@http://192.168.14.6:3000/public/build/vendor.2c3c591224fb193f7fd3.js:92:21976
me/l.defer/n<@http://192.168.14.6:3000/public/build/vendor.2c3c591224fb193f7fd3.js:92:23440

My metric query is 
SELECT event, count(event) as metric 
FROM queue_log_for_excel where  $__timeFilter(time) and (event = 'ANSWER' or event = 'NOANSWER')  group by 1
it is 
SELECT event, count(event) as metric FROM queue_log_for_excel where time >= FROM_UNIXTIME(1526016023) AND time <= FROM_UNIXTIME(1526019623) and (event = 'ANSWER' or event = 'NOANSWER') group by 1;
My Test give it
+----------+--------+
| event    | metric |
+----------+--------+
| ANSWER   |     71 |
| NOANSWER |      3 |
+----------+--------+
2 rows in set (0.15 sec)

Chrome + F12:

perfect-scrollbar.esm.js:6 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive.
angular-strap.js:8 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive.
perfect-scrollbar.esm.js:6 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive.
vendor.2c3c591….js:112090 [Violation] 'setTimeout' handler took 100ms
index.js:9 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive.
vendor.2c3c591….js:112090 [Violation] 'setTimeout' handler took 80ms
perfect-scrollbar.min.js:6 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive.
metrics_panel_ctrl.ts:159 Panel data error: TypeError: Cannot read property 'length' of undefined
    at e.isMsResolutionNeeded (http://192.168.14.6:3000/public/build/app.a4b7f5a163ea89ff6420.js:1:17555)
    at new e (http://192.168.14.6:3000/public/build/app.a4b7f5a163ea89ff6420.js:1:14461)
    at PieChartCtrl.seriesHandler (http://192.168.14.6:3000/public/plugins/grafana-piechart-panel/piechart_ctrl.js:171:26)
    at Array.map (native)
    at PieChartCtrl.onDataReceived (http://192.168.14.6:3000/public/plugins/grafana-piechart-panel/piechart_ctrl.js:164:36)
    at o.emit (http://192.168.14.6:3000/public/build/vendor.2c3c591224fb193f7fd3.js:44:25754)
    at e.emit (http://192.168.14.6:3000/public/build/app.a4b7f5a163ea89ff6420.js:1:13162)
    at PieChartCtrl.e.handleQueryResult (http://192.168.14.6:3000/public/build/0.2ba40e7163b7f9a6ed4b.js:7:18131)
    at u (http://192.168.14.6:3000/public/build/vendor.2c3c591224fb193f7fd3.js:92:69119)
    at http://192.168.14.6:3000/public/build/vendor.2c3c591224fb193f7fd3.js:92:69565

**Comment by marefr** [comment]
Glad you worked it out. In the future, we would appreciate if pie chart related issues are open in pie chart repository, https://github.com/grafana/piechart-panel.
