### ISSUE TITLE
"Time mode requires the flot.time plugin." Error

### ISSUE THREAD

**Issue by hbh7** [grafana/grafana#12171]
**What Grafana version are you using?** 5.1.3
**What datasource are you using?** InfluxDB
**What OS are you running grafana on?** Ubuntu Server 18.04
**What did you do?** View a dashboard with graphs
**What was the expected result?** See the graphs
**What happened instead?** Error was given: 
```
Error: Time mode requires the flot.time plugin.
    at setupTickGeneration (https://grafana.hbh7.com/public/plugins/blackmirror1-singlestat-math-panel/lib/flot/jquery.flot.js:1773:23)
    at Object.eval (https://grafana.hbh7.com/public/plugins/blackmirror1-singlestat-math-panel/lib/flot/jquery.flot.js:1629:25)
    at Function.each (https://grafana.hbh7.com/public/build/vendor.0cea50118711e7e6c839.js:72:14819)
    at setupGrid (https://grafana.hbh7.com/public/plugins/blackmirror1-singlestat-math-panel/lib/flot/jquery.flot.js:1627:23)
    at new Plot (https://grafana.hbh7.com/public/plugins/blackmirror1-singlestat-math-panel/lib/flot/jquery.flot.js:716:9)
    at Function.$.plot (https://grafana.hbh7.com/public/plugins/blackmirror1-singlestat-math-panel/lib/flot/jquery.flot.js:3196:20)
    at p (https://grafana.hbh7.com/public/build/0.5c89ac3fc7a3e78b3629.js:7:219619)
    at l (https://grafana.hbh7.com/public/build/0.5c89ac3fc7a3e78b3629.js:7:218811)
    at o.<anonymous> (https://grafana.hbh7.com/public/build/0.5c89ac3fc7a3e78b3629.js:7:224696)
    at o.emit (https://grafana.hbh7.com/public/build/vendor.0cea50118711e7e6c839.js:44:25321)
```

On page load/reload, the graphs look and work normal (most of the time), but after the graph refreshes automatically, the graphs will go blank with the red ! and look like [this.](https://i.imgur.com/cHFQctl.png)

Not certain if it affects all dashboards, but if I switch between them and it's broken already, then it will continue to not work until reloading the page. Also happens across different browsers and PCs

Happy to provide more info if needed. I'll continue looking around for clues and add more info if I find anything. Thanks

**Comment by hbh7** [comment]
Nevermind found the issue. This plugin causes it. 
https://grafana.com/plugins/blackmirror1-singlestat-math-panel
My recommendation is to avoid this plugin until the author fixes it.
