### ISSUE TITLE
npm build fails in v5.2.0-beta1

### ISSUE THREAD

**Issue by calebtote** [grafana/grafana#12246]
Please include this information:
### What Grafana version are you using?
v5.2.0-beta1

### What OS are you running grafana on?
MacOS

### What did you do?
Merged branch `v5.2.x` with local master
`npm install`
`sudo npm build`

### What was the expected result?
Success

### What happened instead?
```
Running "exec:webpack" (exec) task

[at-loader] Using typescript@2.6.2 from typescript and "tsconfig.json" from /Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/tsconfig.json.

>> [at-loader]: Child process failed to process the request:  TypeError: compiler.createWatchProgram is not a function
>>     at createWatch (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/awesome-typescript-loader/src/checker/runtime.ts:144:19)
>>     at processInit (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/awesome-typescript-loader/src/checker/runtime.ts:312:11)
>>     at /Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/awesome-typescript-loader/src/checker/runtime.ts:593:6
>>     at Object.send (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/awesome-typescript-loader/src/checker/runtime.ts:48:6)
>>     at Checker.req (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/awesome-typescript-loader/src/checker/checker.ts:100:15)
>>     at new Checker (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/awesome-typescript-loader/src/checker/checker.ts:78:8)
>>     at Object.ensureInstance (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/awesome-typescript-loader/src/instance.ts:139:18)
>>     at compiler (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/awesome-typescript-loader/src/index.ts:47:19)
>>     at Object.loader (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/awesome-typescript-loader/src/index.ts:16:12)
>>     at LOADER_EXECUTION (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
>>     at runSyncOrAsync (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
>>     at iterateNormalLoaders (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
>>     at iterateNormalLoaders (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/loader-runner/lib/LoaderRunner.js:218:10)
>>     at /Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/loader-runner/lib/LoaderRunner.js:233:3
>>     at context.callback (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
>>     at Object.module.exports (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/tslint-loader/index.js:141:3)
>>     at LOADER_EXECUTION (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
>>     at runSyncOrAsync (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
>>     at iterateNormalLoaders (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
>>     at Array.<anonymous> (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
>>     at Storage.finished (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:40:15)
>>     at /Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:77:9
>>     at /Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/graceful-fs/graceful-fs.js:78:16
>>     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
>> [at-loader]: Child process failed to process the request:  TypeError: Cannot read property 'updateRootFileNames' of undefined
>>     at getProgram (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/awesome-typescript-loader/src/checker/runtime.ts:150:9)
>>     at getEmitOutput (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/awesome-typescript-loader/src/checker/runtime.ts:394:19)
>>     at emit (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/awesome-typescript-loader/src/checker/runtime.ts:413:24)
>>     at processEmit (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/awesome-typescript-loader/src/checker/runtime.ts:448:22)
>>     at /Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/awesome-typescript-loader/src/checker/runtime.ts:602:6
>>     at Object.send (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/awesome-typescript-loader/src/checker/runtime.ts:48:6)
>>     at Checker.req (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/awesome-typescript-loader/src/checker/checker.ts:100:15)
>>     at Checker.emitFile (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/awesome-typescript-loader/src/checker/checker.ts:105:15)
>>     at transform (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/awesome-typescript-loader/src/index.ts:132:26)
>>     at transformationFunction (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/awesome-typescript-loader/src/index.ts:74:40)
>>     at compiler (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/awesome-typescript-loader/src/index.ts:85:21)
>>     at Object.loader (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/awesome-typescript-loader/src/index.ts:16:12)
>>     at LOADER_EXECUTION (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
>>     at runSyncOrAsync (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
>>     at iterateNormalLoaders (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
>>     at iterateNormalLoaders (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/loader-runner/lib/LoaderRunner.js:218:10)
>>     at /Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/loader-runner/lib/LoaderRunner.js:233:3
>>     at context.callback (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
>>     at Object.module.exports (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/tslint-loader/index.js:141:3)
>>     at LOADER_EXECUTION (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
>>     at runSyncOrAsync (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
>>     at iterateNormalLoaders (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
>>     at Array.<anonymous> (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
>>     at Storage.finished (/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:40:15)
>>     at /Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:77:9
>>     at /Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/node_modules/graceful-fs/graceful-fs.js:78:16
>>     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
>> (node:85814) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): null
```

**Comment by calebtote** [comment]
Think I resolved this with a `npm update` instead of `npm install`

**Comment by daniellee** [comment]
Hmm, there are several strange things here. 

- Why are you building with sudo?

- You should run  `yarn install --pure-lockfile` and not npm install as per instructions:

    https://github.com/grafana/grafana#building-frontend-assets

 I would recommend removing your node_modules if you have run a `sudo npm install` previously and then running `yarn install --pure-lockfile` and finally running `yarn build` (or `npm build` - it doesn't matter).

(Don't think this is a problem in the Grafana build so closing but can reopen if it turns out to be a bug).

**Comment by calebtote** [comment]
Hey @daniellee  -- thanks for the note, I tried what you said but now when I navigate to my application (`npm run watch` and `./bin/grafana-server`) I get the following permission error:

```Uncaught Error: Module build failed: Error: EACCES: permission denied, open '/Users/ctote/Documents/dev/grafana/src/github.com/grafana/grafana/.awcache/e92c6824c466bfe3edbed52e46b32a502b3aca13e8c380b356d34d6548650e6b8d6d9f84a6837cb716f7c2f20a79832b8c6731b493bf581adabcc1b08271469c.json.gzip'```

This happens whether I use `npm run watch` or `sudo npm run watch` -- I've tried `sudo rm -rf .awcache` so that it's recreated as the correct user, but it still fails. Kind of stuck at this point

**Comment by daniellee** [comment]
You should not be using sudo at all - that's just introducing permission problems. You have messed something up by using sudo - maybe it would be easiest to do a git clean or just remove the whole repo and start again.
