### ISSUE TITLE
Building on arm64 platform has phantomjs issue

### ISSUE THREAD

**Issue by lukaszgryglicki** [grafana/grafana#12618]
Please include this information:
### What Grafana version are you using? 
- master (build current master 0b210a6f5d1d6b3e967854607444e852fc33fef1)
### What datasource are you using? 
- none
### What OS are you running grafana on?
- `Ubuntu 18.04` `Linux devstats.team.io 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:20 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux` 
### What did you do?
- `yarn install --pure-lockfile`
### What was the expected result? 
- full output pasted at the bottom
### What happened instead? 
- build error

```
root@devstats:/data/dev/src/github.com/grafana/grafana# yarn install --pure-lockfile
yarn install v1.7.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/4] ⠐ iltorb
[2/4] ⠐ node-sass
[-/4] ⠐ waiting...
error /data/dev/src/github.com/grafana/grafana/node_modules/phantomjs-prebuilt: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /data/dev/src/github.com/grafana/grafana/node_modules/phantomjs-prebuilt
Output:
Considering PhantomJS found at /usr/bin/phantomjs
Found PhantomJS at /usr/bin/phantomjs ...verifying
Error verifying phantomjs, continuing { Error: Command failed: /usr/bin/phantomjs --version
qt.qpa.screen: QXcbConnection: Could not connect to display 
Could not connect to any X display.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/usr/bin/phantomjs --version' }
Unexpected platform or architecture: linux/arm64
```

**Comment by torkelo** [comment]
we have an arm64 package, 
![image](https://user-images.githubusercontent.com/10999/42758038-5c95bf1a-8902-11e8-9d18-b29794866739.png)
 
To build on an arm platform you will have to remove phantomjs-prebuilt from yarn/package.json , instead of phantomjs we have a renderer backend plugin (that we will migrate to), and remove phantomjs in a future release.

https://github.com/grafana/grafana-image-renderer

Actually if you want to you can submit a PR and remove this phantomjs-prebuilt package as it's only used for local dev builds, we do not use when we build packages. For packages we use this script https://github.com/grafana/grafana/blob/master/scripts/build/download-phantomjs.sh

**Comment by lukaszgryglicki** [comment]
Ok, so when I remove `phantomjs-prebuilt` from `package.json`:
```
root@devstats:/data/dev/src/github.com/grafana/grafana# yarn install --pure-lockfile
yarn install v1.7.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/4] ⠐ iltorb
[2/4] ⠐ node-sass
[-/4] ⠐ waiting...
error /data/dev/src/github.com/grafana/grafana/node_modules/phantomjs-prebuilt: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /data/dev/src/github.com/grafana/grafana/node_modules/phantomjs-prebuilt
Output:
Considering PhantomJS found at /usr/bin/phantomjs
Found PhantomJS at /usr/bin/phantomjs ...verifying
Error verifying phantomjs, continuing { Error: Command failed: /usr/bin/phantomjs --version
qt.qpa.screen: QXcbConnection: Could not connect to display 
Could not connect to any X display.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/usr/bin/phantomjs --version' }
Unexpected platform or architecture: linux/arm64
```
So it attempts to use installed PhantomJS.

When I `apt remove phantomjs`:
```
root@devstats:/data/dev/src/github.com/grafana/grafana# yarn install --pure-lockfile
yarn install v1.7.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/4] ⠠ iltorb
[2/4] ⠠ node-sass
[-/4] ⠐ waiting...
error /data/dev/src/github.com/grafana/grafana/node_modules/phantomjs-prebuilt: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /data/dev/src/github.com/grafana/grafana/node_modules/phantomjs-prebuilt
Output:
PhantomJS not found on PATH
Unexpected platform or architecture: linux/arm64
```

**Comment by torkelo** [comment]
You need to remove it from yarn lock file as well

**Comment by yuvadm** [comment]
@torkelo Trying to build this on arm64/aarch64 as well and getting the same error, even after removing from the lock file. Any suggestions?

**Comment by yuvadm** [comment]
The steps that seem to be working are:

1. Remove both `phantomjs` and `karma-phantomjs` in `package.json`
2. Remove those same entries in `yarn.lock`
3. Change the `build` task to run `grunt build --force` due to the missing parts

**Comment by marefr** [comment]
Closing this since PhantomJS is now removed in master, ref #13802
