### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by ervikrant06** [grafana/grafana#12822]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
grafana-5.1.4-1.x86_64
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
```
 cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
### What did you do?
Imported the prometheus  node exporter dashboard from https://grafana.com/dashboards/1860
### What was the expected result?
Import should be successful without any issue. 
### What happened instead?
Getting the following error in all panels. 
~~~
TypeError: Cannot read property 'replace' of undefined
    at r (http://127.0.0.1:9000/public/build/0.5c89ac3fc7a3e78b3629.js:7:167630)
    at t.interpolateQueryExpr (http://127.0.0.1:9000/public/build/0.5c89ac3fc7a3e78b3629.js:7:169318)
    at t.formatValue (http://127.0.0.1:9000/public/build/0.5c89ac3fc7a3e78b3629.js:1:58018)
    at http://127.0.0.1:9000/public/build/0.5c89ac3fc7a3e78b3629.js:1:59523
    at String.replace (<anonymous>)
    at t.replace (http://127.0.0.1:9000/public/build/0.5c89ac3fc7a3e78b3629.js:1:59266)
    at t.createQuery (http://127.0.0.1:9000/public/build/0.5c89ac3fc7a3e78b3629.js:7:170580)
    at t.query (http://127.0.0.1:9000/public/build/0.5c89ac3fc7a3e78b3629.js:7:169675)
    at e.issueQueries (http://127.0.0.1:9000/public/build/0.5c89ac3fc7a3e78b3629.js:7:17849)
    at e.issueQueries (http://127.0.0.1:9000/public/build/0.5c89ac3fc7a3e78b3629.js:7:214528)
~~~
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
I found another issue #10499 opened for this issue and it was closed stating that it's fixed but issue still persist.

**Comment by torkelo** [comment]
That issue states it was fixed in v5.2 , your using v5.1, can you upgrade?
