### ISSUE TITLE
init panic

### ISSUE THREAD

**Issue by hellojukay** [grafana/grafana#13021]
i run grafana in docker container, my image version is 
```shell
 grafana/grafana:5.2.1
```
docker version
```shell
[infra@dev snc]$ docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:20:16 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:23:58 2018
  OS/Arch:      linux/amd64
  Experimental: false
[infra@dev snc]$
```
my docker-compose config
```shell
  grafana:
    image: grafana/grafana:5.2.1
    container_name: grafana
    restart: always
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks:
      - snc_network
```
this is my container log
```shell
t=2018-08-24T01:48:29+0000 lvl=info msg="Initializing NotificationService" logger=server
t=2018-08-24T01:48:29+0000 lvl=info msg="Initializing ProvisioningService" logger=server
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xfa79dd]

goroutine 1 [running]:
github.com/grafana/grafana/pkg/services/sqlstore.DeleteDataSourceByName.func1(0xc420676e00, 0x0, 0x0)
	/go/src/github.com/grafana/grafana/pkg/services/sqlstore/datasource.go:82 +0x12d
github.com/grafana/grafana/pkg/services/sqlstore.inTransactionWithRetry(0xc4202b9410, 0x0, 0x0, 0x0)
	/go/src/github.com/grafana/grafana/pkg/services/sqlstore/shared.go:42 +0xaa
```

**Comment by xlson** [comment]
@hellojukay It sounds like you booted Grafana mapping in an old version of the database that had the wrong file permissions. Grafana runs as user `472` now. 777 works but will make it readable by anyone, you could set stricter permissions and change the owner to `472`.
