### ISSUE TITLE
Blank Black Page after Install 1.9.1

### ISSUE THREAD

**Issue by gchristiansen** [grafana/grafana#1342]
I've just finished initial installation on a nginx host.  I get a blank black page when accessing the app.  When I open Chrome javascript console, I get the following error stacktrace:

app.496fdc2e.js:9 TypeError: Cannot set property 'default' of undefined
    at init (http://app1.lab.vx/app/app.496fdc2e.js:18:22496)
    at new <anonymous> (http://app1.lab.vx/app/app.496fdc2e.js:18:23197)
    at e (http://app1.lab.vx/app/app.496fdc2e.js:8:23327)
    at Object.f [as instantiate] (http://app1.lab.vx/app/app.496fdc2e.js:8:23413)
    at Object.<anonymous> (http://app1.lab.vx/app/app.496fdc2e.js:8:22011)
    at Object.e [as invoke] (http://app1.lab.vx/app/app.496fdc2e.js:8:23327)
    at Object.$get (http://app1.lab.vx/app/app.496fdc2e.js:8:21777)
    at Object.e [as invoke] (http://app1.lab.vx/app/app.496fdc2e.js:8:23327)
    at http://app1.lab.vx/app/app.496fdc2e.js:8:23854
    at d (http://app1.lab.vx/app/app.496fdc2e.js:8:22972) <div ng-include="'app/partials/dashboard_topnav.html'" class="ng-scope">
app.496fdc2e.js:9 TypeError: Cannot set property 'default' of undefined
    at init (http://app1.lab.vx/app/app.496fdc2e.js:18:22496)
    at new <anonymous> (http://app1.lab.vx/app/app.496fdc2e.js:18:23197)
    at e (http://app1.lab.vx/app/app.496fdc2e.js:8:23327)
    at Object.f [as instantiate] (http://app1.lab.vx/app/app.496fdc2e.js:8:23413)
    at Object.<anonymous> (http://app1.lab.vx/app/app.496fdc2e.js:8:22011)
    at Object.e [as invoke] (http://app1.lab.vx/app/app.496fdc2e.js:8:23327)
    at Object.$get (http://app1.lab.vx/app/app.496fdc2e.js:8:21777)
    at Object.e [as invoke] (http://app1.lab.vx/app/app.496fdc2e.js:8:23327)
    at http://app1.lab.vx/app/app.496fdc2e.js:8:23854
    at d (http://app1.lab.vx/app/app.496fdc2e.js:8:22972)

**Comment by torkelo** [comment]
Have you added your data sources  to config.js ?

**Comment by gchristiansen** [comment]
Yes, I'm using influxdb that is up and running on the same host:

// InfluxDB example setup (the InfluxDB databases specified need to exist)
      /*
      datasources: {
        javis: {
          type: 'influxdb',
          url: "http://app1.lab.vx:8086/db/javis",
          username: 'gc',
          password: 'gcgc',
        },
        grafana: {
          type: 'influxdb',
          url: "http://app1.lab.vx:8086/db/grafana",
          username: 'grafadmin',
          password: 'grafadmin',
          grafanaDB: true
        },
      },
      */

**Comment by gchristiansen** [comment]
Looks like I missed that the datasources where commented out.  It's now working.
