### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by WPH95** [grafana/grafana#1353]
i can't solved this problem....     

TypeError: Cannot read property 'length' of undefined
    at h.convertDataPointsToMs (http://xxx.com/app/app.496fdc2e.js:18:4047)
    at i (http://xxx.com/app/app.496fdc2e.js:9:30874)
    at http://xxx.com/app/app.496fdc2e.js:9:31046
    at l.$eval (http://xxx.com/app/app.496fdc2e.js:10:6196)
    at l.$digest (http://xxx.com/app/app.496fdc2e.js:10:4714)
    at l.$apply (http://xxx.com/app/app.496fdc2e.js:10:6452)
    at h (http://xxx.com/app/app.496fdc2e.js:9:14682)
    at q (http://xxx.com/app/app.496fdc2e.js:9:16489)
    at XMLHttpRequest.u.onload (http://xxx.com/app/app.496fdc2e.js:9:17029)

**Comment by torkelo** [comment]
I have seen this as well but very rarely, usually happens when graphite returns strange things, but should be fixed in graphite 0.9.13 (https://github.com/graphite-project/graphite-web/issues/576)
