### ISSUE TITLE
session/redis: unsupported option 'grafana'

### ISSUE THREAD

**Issue by thomasriley** [grafana/grafana#13593]
When using Redis for sessions, Grafana crashes on startup with the error below:

```
session/redis: unsupported option 'grafana'
```

My session config looks like this in Grafana.ini:
```
    [session]
    provider = redis
    provider_config = network=tcp,addr=k8-service-name-for-redis:6379,db=0,pool_size=100,idle_timeout=180,prefix=session
```

Seems like the option `grafana` is being passed into this Hash in the Session Package:
https://github.com/go-macaron/session/blob/b8e286a0dba8f4999042d6b258daf51b31d08938/redis/redis.go#L124

I've searched across GitHub & Grafana community for anyone seeing the same issue, but I've not seen anything.

Cheers,
Tom

Grafana Log:
```
t=2018-10-10T10:28:54+0000 lvl=info msg="Starting Grafana" logger=server version=5.2.4 commit=0bbac5c compiled=2018-09-07T14:35:16+0000
t=2018-10-10T10:28:54+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2018-10-10T10:28:54+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2018-10-10T10:28:54+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2018-10-10T10:28:54+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2018-10-10T10:28:54+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2018-10-10T10:28:54+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
t=2018-10-10T10:28:54+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.log.mode=console"
t=2018-10-10T10:28:54+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_DATA=/var/lib/grafana"
t=2018-10-10T10:28:54+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_LOGS=/var/log/grafana"
t=2018-10-10T10:28:54+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PLUGINS=/var/lib/grafana/plugins"
t=2018-10-10T10:28:54+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PROVISIONING=/etc/grafana/provisioning"
t=2018-10-10T10:28:54+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_DATABASE_PASSWORD=*********"
t=2018-10-10T10:28:54+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_SESSION_PROVIDER_CONFIG=*********"
t=2018-10-10T10:28:54+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_SECURITY_ADMIN_USER=admin"
t=2018-10-10T10:28:54+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_SECURITY_ADMIN_PASSWORD=*********"
t=2018-10-10T10:28:54+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2018-10-10T10:28:54+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2018-10-10T10:28:54+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2018-10-10T10:28:54+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2018-10-10T10:28:54+0000 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
t=2018-10-10T10:28:54+0000 lvl=info msg="App mode production" logger=settings
t=2018-10-10T10:28:54+0000 lvl=info msg="Initializing SqlStore" logger=server
t=2018-10-10T10:28:54+0000 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=mysql
t=2018-10-10T10:28:54+0000 lvl=info msg="Starting DB migration" logger=migrator
t=2018-10-10T10:28:54+0000 lvl=info msg="Initializing SearchService" logger=server
t=2018-10-10T10:28:54+0000 lvl=info msg="Initializing PluginManager" logger=server
t=2018-10-10T10:28:54+0000 lvl=info msg="Starting plugin search" logger=plugins
t=2018-10-10T10:28:54+0000 lvl=info msg="Initializing InternalMetricsService" logger=server
t=2018-10-10T10:28:54+0000 lvl=info msg="Initializing AlertingService" logger=server
t=2018-10-10T10:28:54+0000 lvl=info msg="Initializing HTTPServer" logger=server
t=2018-10-10T10:28:54+0000 lvl=info msg="Initializing CleanUpService" logger=server
t=2018-10-10T10:28:54+0000 lvl=info msg="Initializing NotificationService" logger=server
t=2018-10-10T10:28:54+0000 lvl=info msg="Initializing ProvisioningService" logger=server
t=2018-10-10T10:28:54+0000 lvl=info msg="Initializing RenderingService" logger=server
t=2018-10-10T10:28:54+0000 lvl=info msg="Initializing TracingService" logger=server
panic: session/redis: unsupported option 'grafana'

goroutine 87 [running]:
github.com/grafana/grafana/pkg/services/session.Init(0x2101680, 0x3840)
	/go/src/github.com/grafana/grafana/pkg/services/session/session.go:46 +0x28b
github.com/grafana/grafana/pkg/middleware.Sessioner(0x2101680, 0x3840, 0x14ef810, 0x11a4c20)
	/go/src/github.com/grafana/grafana/pkg/middleware/session.go:12 +0x35
github.com/grafana/grafana/pkg/api.(*HTTPServer).newMacaron(0xc42032c780, 0x0)
	/go/src/github.com/grafana/grafana/pkg/api/http_server.go:197 +0x6e7
github.com/grafana/grafana/pkg/api.(*HTTPServer).Run(0xc42032c780, 0x15cdc80, 0xc42032a540, 0x45f5e0, 0x8)
	/go/src/github.com/grafana/grafana/pkg/api/http_server.go:64 +0x91
main.(*GrafanaServerImpl).Run.func1(0x8, 0x14f2360)
	/go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/server.go:128 +0x66
github.com/grafana/grafana/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc42032a580, 0xc42016bb60)
	/go/src/github.com/grafana/grafana/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
created by github.com/grafana/grafana/vendor/golang.org/x/sync/errgroup.(*Group).Go
	/go/src/github.com/grafana/grafana/vendor/golang.org/x/sync/errgroup/errgroup.go:55 +0x66
```

Please include this information:
### What Grafana version are you using?
5.2.4
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
GKE
### What did you do?
Start Grafana with a configuration for sessions on Redis
### What was the expected result?
Grafana starts
### What happened instead?
Grafana crashes

**Comment by marefr** [comment]
This sounds weird. Been looking at the code and cannot understand how this could happen. Could you include your full grafana config (stripping out any sensitive information). Thanks

**Comment by thomasriley** [comment]
Hey @marefr, thanks for looking into this for me.

My Grafana.ini is below:

```
[analytics]
check_for_updates = false
[auth.ldap]
enabled = false
[database]
ca_cert_path = /etc/secrets/server-ca.pem
client_cert_path = /etc/secrets/client-cert.pem
client_key_path = /etc/secrets/client-key.pem
host = redacted_ip_address:3306
name = grafana
ssl_mode = skip-verify
type = mysql
user = grafana
[grafana_net]
url = https://grafana.net
[log]
mode = console
[paths]
data = /var/lib/grafana/data
logs = /var/log/grafana
plugins = /var/lib/grafana/plugins
provisioning = /etc/grafana/provisioning
[session]
provider = redis
provider_config = "addr=grafana-redis-master:6379,pool_size=100,prefix=session"
```

On the `provider_config` the grafana-redis-master bit is a K8 service name, I've tried removing Grafana from that service name in case something funky was going on there, but no difference. 

Cheers, Tom.

**Comment by marefr** [comment]
I noticed that you have a section called `grafana_net` - that shouldn't be there. Format is [TOML](https://github.com/toml-lang/toml) and all examples I've seen uses newlines between sections. Please try this (grafana_net section removed):

```toml
[analytics]
check_for_updates = false

[auth.ldap]
enabled = false

[database]
ca_cert_path = /etc/secrets/server-ca.pem
client_cert_path = /etc/secrets/client-cert.pem
client_key_path = /etc/secrets/client-key.pem
host = redacted_ip_address:3306
name = grafana
ssl_mode = skip-verify
type = mysql
user = grafana

[log]
mode = console

[paths]
data = /var/lib/grafana/data
logs = /var/log/grafana
plugins = /var/lib/grafana/plugins
provisioning = /etc/grafana/provisioning

[session]
provider = redis
provider_config = "addr=grafana-redis-master:6379,pool_size=100,prefix=session"
```

**Comment by thomasriley** [comment]
I've tried using the above (by manually editing it in the ConfigMap) but I'm still getting the same error.

Interestingly, the format of the grafana.ini file is out of my control as I'm using the [Grafana Helm Chart ](https://hub.kubeapps.com/charts/stable/grafana) which generates the file based on Helm values set for it.

Just removing the `grafana_net` bit, deployed via Helm with the odd formatting, still also has the error.

Thanks again.

Cheers,
Tom

**Comment by marefr** [comment]
This is probably related to some configuration error with the helm chart so closing this. We haven't created the helm chart nor used it so hard for us to investigate. Could you try and use [environment variables](http://docs.grafana.org/installation/docker/#configuration) instead? 

`GF_SESSION_PROVIDER` and `GF_SESSION_PROVIDER_CONFIG` should work for a normal Grafana docker image. Don't know if there are anything special with the helm chart needed.
