### ISSUE TITLE
exec:tslint fails

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#13905]
Getting this output when running `yarn run precommit`

```
Running "exec:tslint" (exec) task
>> internal/modules/cjs/loader.js:583
>>     throw err;
>>     ^
>> 
>> Error: Cannot find module 'go/src/github.com/grafana/grafana/node_modules/tslint/lib/tslint-cli.js'
>>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
>>     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
>>     at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
>>     at startup (internal/bootstrap/node.js:279:19)
>>     at bootstrapNodeJSCore (internal/bootstrap/node.js:752:3)
>> Exited with code: 1.
>> Error executing child process: Error: Command failed: node ./node_modules/tslint/lib/tslint-cli.js -c tslint.json --project ./tsconfig.json
>> internal/modules/cjs/loader.js:583
>>     throw err;
>>     ^
>> 
>> Error: Cannot find module 'go/src/github.com/grafana/grafana/node_modules/tslint/lib/tslint-cli.js'
>>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
>>     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
>>     at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
>>     at startup (internal/bootstrap/node.js:279:19)
>>     at bootstrapNodeJSCore (internal/bootstrap/node.js:752:3)
Warning: Task "exec:tslint" failed. Use --force to continue.
```

```
$ ls ./node_modules/tslint/lib/
configs                 enableDisableRules.js   formatterLoader.js      index.d.ts              linter.js               rules.d.ts              test.d.ts               utils.d.ts
configuration.d.ts      error.d.ts              formatters              index.js                ruleLoader.d.ts         rules.js                test.js                 utils.js
configuration.js        error.js                formatters.d.ts         language                ruleLoader.js           runner.d.ts             tslintCli.d.ts          verify
enableDisableRules.d.ts formatterLoader.d.ts    formatters.js           linter.d.ts             rules                   runner.js               tslintCli.js
```
Is it wrong in my machine or tslint changed caps?

**Comment by torkelo** [comment]
Are you on latest master? And have you run yarn install?

**Comment by simPod** [comment]
Yup, happening to me on https://github.com/grafana/grafana/commit/3d452e5a46a4115dc9ef585eaa43f7c254c3d77d

Running `yarn install --pure-lock`

(macos latest)

**Comment by torkelo** [comment]
the error makes zero sense, we do not try to execute tslint-cli but tslintCli 
https://github.com/grafana/grafana/blob/master/scripts/grunt/options/exec.js#L6 

same in commit your referring to. something has gotten mixed up in your devenv?

**Comment by simPod** [comment]
Indeed, you're correct. I tried to rm and reclone the whole directory, works now. Consider it invalid then. Thanks!
