### ISSUE TITLE
Can't save dashboard

### ISSUE THREAD

**Issue by liorsav** [grafana/grafana#1401]
Hi,
I installed grafana 1.9.1. Working with OpenTSDB as default DB. I don't have elasticsearch or other storage engine for metadata and I want to use the plain json (on disk) storage.
config.js 
datasources: {
        opentsdb: {
          default: true,
          type: 'opentsdb',
          url: "http://lab-mon001:80",
        }
      },

when saving in the browser I get this error:
TypeError: undefined is not a function
    at l.a.searchDashboards (http://lab-mon001/grafana-1.9.1/app/app.496fdc2e.js:21:28259)
    at l.a.search (http://lab-mon001/grafana-1.9.1/app/app.496fdc2e.js:21:28826)
    at http://lab-mon001/grafana-1.9.1/app/app.496fdc2e.js:21:27383
    at http://lab-mon001/grafana-1.9.1/app/app.496fdc2e.js:10:13641
    at g (http://lab-mon001/grafana-1.9.1/app/app.496fdc2e.js:8:24897)
    at http://lab-mon001/grafana-1.9.1/app/app.496fdc2e.js:8:26897app.496fdc2e.js:9 (anonymous function)app.496fdc2e.js:9 (anonymous function)app.496fdc2e.js:10 (anonymous function)app.496fdc2e.js:8 gapp.496fdc2e.js:8 (anonymous function)

Please advise,
Lior

**Comment by torkelo** [comment]
Sorry :(  Since you have no Elasticsearch or InfluxDB datasource (the only ones that support dashboard storage at the moment) the save and search features will not work.

To save to json file on disk you need to export the dashboard to json (available in the save menu). Then upload that json file to a folder on the web server that hosts grafana (app/dashboards folder). Since grafana is a frontend app only without a backend like Elasticsearch or InfluxDB that can handle the saving of dashboards the json file solution is very cumbersome.
