### ISSUE TITLE
Select user/team drop downs doesn't work

### ISSUE THREAD

**Issue by MachEleven** [grafana/grafana#14935]
Please include this information:
### What Grafana version are you using?
5.5.0 nightly builds

### What OS are you running grafana on?
Ubuntu 16.04

### What did you do?
I created a team. Then tried to add the initial team member.
I clicked "Select user" from Add Team Member.
![image](https://user-images.githubusercontent.com/28393146/51327458-69867180-1a82-11e9-8d65-93cf4c787115.png)

### What was the expected result?
A list of users for this organization.

### What happened instead?
An empty page

**Comment by marefr** [comment]
Seems like select team in folder/dashboard permissions is broken as well.

Using yarn watch:
```
⚛️🔥😭: hot update was not successful collapse
TypeError: Failed to construct 'Option': Please use the 'new' operator, this DOM object constructor cannot be called as a function.

Stack trace:
at ProxyFacade (http://localhost:3000/public/build/app.2e96337131504da53393.js:231972:20)
in Option (created by Select)
in div (created by MenuList)
in MenuList (created by MenuPlacer)
in ScrollBlock (created by MenuPlacer)
in NodeResolver (created by ScrollCaptor)
in ScrollCaptor (created by ScrollCaptorSwitch)
in ScrollCaptorSwitch (created by MenuPlacer)
in div (created by Menu)
in Menu (created by MenuPlacer)
in MenuPlacer (created by Select)
in div (created by SelectContainer)
in SelectContainer (created by Select)
in Select (created by StateManager)
in StateManager (created by Async)
in Async (created by AsyncSelect)
in AsyncSelect (created by UserPicker)
in div (created by UserPicker)
in UserPicker (created by AddPermissions)
in div (created by AddPermissions)
in div (created by AddPermissions)
in form (created by AddPermissions)
in div (created by AddPermissions)
in AddPermissions (created by FolderPermissions)
in div (created by Transition)
in Transition (created by Component)
in Component (created by FolderPermissions)
in div (created by FolderPermissions)
in div (created by FolderPermissions)
in FolderPermissions (created by Connect(FolderPermissions))
in Connect(FolderPermissions) (created by HotExportedConnect(FolderPermissions))
in AppContainer (created by HotExportedConnect(FolderPermissions))
in HotExportedConnect(FolderPermissions)
in Provider
TypeError: Failed to construct 'Option': Please use the 'new' operator, this DOM object constructor cannot be called as a function.

Stack trace:
at ProxyFacade (http://localhost:3000/public/build/app.2e96337131504da53393.js:231972:20)
in Option (created by Select)
in div (created by MenuList)
in MenuList (created by MenuPlacer)
in ScrollBlock (created by MenuPlacer)
in NodeResolver (created by ScrollCaptor)
in ScrollCaptor (created by ScrollCaptorSwitch)
in ScrollCaptorSwitch (created by MenuPlacer)
in div (created by Menu)
in Menu (created by MenuPlacer)
in MenuPlacer (created by Select)
in div (created by SelectContainer)
in SelectContainer (created by Select)
in Select (created by StateManager)
in StateManager (created by Async)
in Async (created by AsyncSelect)
in AsyncSelect (created by UserPicker)
in div (created by UserPicker)
in UserPicker (created by AddPermissions)
in div (created by AddPermissions)
in div (created by AddPermissions)
in form (created by AddPermissions)
in div (created by AddPermissions)
in AddPermissions (created by FolderPermissions)
in div (created by Transition)
in Transition (created by Component)
in Component (created by FolderPermissions)
in div (created by FolderPermissions)
in div (created by FolderPermissions)
in FolderPermissions (created by Connect(FolderPermissions))
in Connect(FolderPermissions) (created by HotExportedConnect(FolderPermissions))
in AppContainer (created by HotExportedConnect(FolderPermissions))
in HotExportedConnect(FolderPermissions)
in Provider
TypeError: Failed to construct 'Option': Please use the 'new' operator, this DOM object constructor cannot be called as a function.

Stack trace:
at ProxyFacade (http://localhost:3000/public/build/app.2e96337131504da53393.js:231972:20)
in Option (created by Select)
in div (created by MenuList)
in MenuList (created by MenuPlacer)
in ScrollBlock (created by MenuPlacer)
in NodeResolver (created by ScrollCaptor)
in ScrollCaptor (created by ScrollCaptorSwitch)
in ScrollCaptorSwitch (created by MenuPlacer)
in div (created by Menu)
in Menu (created by MenuPlacer)
in MenuPlacer (created by Select)
in div (created by SelectContainer)
in SelectContainer (created by Select)
in Select (created by StateManager)
in StateManager (created by Async)
in Async (created by AsyncSelect)
in AsyncSelect (created by UserPicker)
in div (created by UserPicker)
in UserPicker (created by AddPermissions)
in div (created by AddPermissions)
in div (created by AddPermissions)
in form (created by AddPermissions)
in div (created by AddPermissions)
in AddPermissions (created by FolderPermissions)
in div (created by Transition)
in Transition (created by Component)
in Component (created by FolderPermissions)
in div (created by FolderPermissions)
in div (created by FolderPermissions)
in FolderPermissions (created by Connect(FolderPermissions))
in Connect(FolderPermissions) (created by HotExportedConnect(FolderPermissions))
in AppContainer (created by HotExportedConnect(FolderPermissions))
in HotExportedConnect(FolderPermissions)
in Provider
TypeError: Failed to construct 'Option': Please use the 'new' operator, this DOM object constructor cannot be called as a function.

Stack trace:
at ProxyFacade (http://localhost:3000/public/build/app.2e96337131504da53393.js:231972:20)
in Option (created by Select)
in div (created by MenuList)
in MenuList (created by MenuPlacer)
in ScrollBlock (created by MenuPlacer)
in NodeResolver (created by ScrollCaptor)
in ScrollCaptor (created by ScrollCaptorSwitch)
in ScrollCaptorSwitch (created by MenuPlacer)
in div (created by Menu)
in Menu (created by MenuPlacer)
in MenuPlacer (created by Select)
in div (created by SelectContainer)
in SelectContainer (created by Select)
in Select (created by StateManager)
in StateManager (created by Async)
in Async (created by AsyncSelect)
in AsyncSelect (created by UserPicker)
in div (created by UserPicker)
in UserPicker (created by AddPermissions)
in div (created by AddPermissions)
in div (created by AddPermissions)
in form (created by AddPermissions)
in div (created by AddPermissions)
in AddPermissions (created by FolderPermissions)
in div (created by Transition)
in Transition (created by Component)
in Component (created by FolderPermissions)
in div (created by FolderPermissions)
in div (created by FolderPermissions)
in FolderPermissions (created by Connect(FolderPermissions))
in Connect(FolderPermissions) (created by HotExportedConnect(FolderPermissions))
in AppContainer (created by HotExportedConnect(FolderPermissions))
in HotExportedConnect(FolderPermissions)
in Provider
TypeError: Failed to construct 'Option': Please use the 'new' operator, this DOM object constructor cannot be called as a function.

Stack trace:
at ProxyFacade (http://localhost:3000/public/build/app.2e96337131504da53393.js:231972:20)
in Option (created by Select)
in div (created by MenuList)
in MenuList (created by MenuPlacer)
in ScrollBlock (created by MenuPlacer)
in NodeResolver (created by ScrollCaptor)
in ScrollCaptor (created by ScrollCaptorSwitch)
in ScrollCaptorSwitch (created by MenuPlacer)
in div (created by Menu)
in Menu (created by MenuPlacer)
in MenuPlacer (created by Select)
in div (created by SelectContainer)
in SelectContainer (created by Select)
in Select (created by StateManager)
in StateManager (created by Async)
in Async (created by AsyncSelect)
in AsyncSelect (created by UserPicker)
in div (created by UserPicker)
in UserPicker (created by AddPermissions)
in div (created by AddPermissions)
in div (created by AddPermissions)
in form (created by AddPermissions)
in div (created by AddPermissions)
in AddPermissions (created by FolderPermissions)
in div (created by Transition)
in Transition (created by Component)
in Component (created by FolderPermissions)
in div (created by FolderPermissions)
in div (created by FolderPermissions)
in FolderPermissions (created by Connect(FolderPermissions))
in Connect(FolderPermissions) (created by HotExportedConnect(FolderPermissions))
in AppContainer (created by HotExportedConnect(FolderPermissions))
in HotExportedConnect(FolderPermissions)
in Provider
TypeError: Failed to construct 'Option': Please use the 'new' operator, this DOM object constructor cannot be called as a function.

Stack trace:
at ProxyFacade (http://localhost:3000/public/build/app.2e96337131504da53393.js:231972:20)
in Option (created by Select)
in div (created by MenuList)
in MenuList (created by MenuPlacer)
in ScrollBlock (created by MenuPlacer)
in NodeResolver (created by ScrollCaptor)
in ScrollCaptor (created by ScrollCaptorSwitch)
in ScrollCaptorSwitch (created by MenuPlacer)
in div (created by Menu)
in Menu (created by MenuPlacer)
in MenuPlacer (created by Select)
in div (created by SelectContainer)
in SelectContainer (created by Select)
in Select (created by StateManager)
in StateManager (created by Async)
in Async (created by AsyncSelect)
in AsyncSelect (created by UserPicker)
in div (created by UserPicker)
in UserPicker (created by AddPermissions)
in div (created by AddPermissions)
in div (created by AddPermissions)
in form (created by AddPermissions)
in div (created by AddPermissions)
in AddPermissions (created by FolderPermissions)
in div (created by Transition)
in Transition (created by Component)
in Component (created by FolderPermissions)
in div (created by FolderPermissions)
in div (created by FolderPermissions)
in FolderPermissions (created by Connect(FolderPermissions))
in Connect(FolderPermissions) (created by HotExportedConnect(FolderPermissions))
in AppContainer (created by HotExportedConnect(FolderPermissions))
in HotExportedConnect(FolderPermissions)
in Provider
TypeError: Failed to construct 'Option': Please use the 'new' operator, this DOM object constructor cannot be called as a function.

Stack trace:
at ProxyFacade (http://localhost:3000/public/build/app.2e96337131504da53393.js:231972:20)
in Option (created by Select)
in div (created by MenuList)
in MenuList (created by MenuPlacer)
in ScrollBlock (created by MenuPlacer)
in NodeResolver (created by ScrollCaptor)
in ScrollCaptor (created by ScrollCaptorSwitch)
in ScrollCaptorSwitch (created by MenuPlacer)
in div (created by Menu)
in Menu (created by MenuPlacer)
in MenuPlacer (created by Select)
in div (created by SelectContainer)
in SelectContainer (created by Select)
in Select (created by StateManager)
in StateManager (created by Async)
in Async (created by AsyncSelect)
in AsyncSelect (created by UserPicker)
in div (created by UserPicker)
in UserPicker (created by AddPermissions)
in div (created by AddPermissions)
in div (created by AddPermissions)
in form (created by AddPermissions)
in div (created by AddPermissions)
in AddPermissions (created by FolderPermissions)
in div (created by Transition)
in Transition (created by Component)
in Component (created by FolderPermissions)
in div (created by FolderPermissions)
in div (created by FolderPermissions)
in FolderPermissions (created by Connect(FolderPermissions))
in Connect(FolderPermissions) (created by HotExportedConnect(FolderPermissions))
in AppContainer (created by HotExportedConnect(FolderPermissions))
in HotExportedConnect(FolderPermissions)
in Provider
TypeError: Failed to construct 'Option': Please use the 'new' operator, this DOM object constructor cannot be called as a function.

Stack trace:
at ProxyFacade (http://localhost:3000/public/build/app.2e96337131504da53393.js:231972:20)
in Option (created by Select)
in div (created by MenuList)
in MenuList (created by MenuPlacer)
in ScrollBlock (created by MenuPlacer)
in NodeResolver (created by ScrollCaptor)
in ScrollCaptor (created by ScrollCaptorSwitch)
in ScrollCaptorSwitch (created by MenuPlacer)
in div (created by Menu)
in Menu (created by MenuPlacer)
in MenuPlacer (created by Select)
in div (created by SelectContainer)
in SelectContainer (created by Select)
in Select (created by StateManager)
in StateManager (created by Async)
in Async (created by AsyncSelect)
in AsyncSelect (created by UserPicker)
in div (created by UserPicker)
in UserPicker (created by AddPermissions)
in div (created by AddPermissions)
in div (created by AddPermissions)
in form (created by AddPermissions)
in div (created by AddPermissions)
in AddPermissions (created by FolderPermissions)
in div (created by Transition)
in Transition (created by Component)
in Component (created by FolderPermissions)
in div (created by FolderPermissions)
in div (created by FolderPermissions)
in FolderPermissions (created by Connect(FolderPermissions))
in Connect(FolderPermissions) (created by HotExportedConnect(FolderPermissions))
in AppContainer (created by HotExportedConnect(FolderPermissions))
in HotExportedConnect(FolderPermissions)
in Provider
TypeError: Failed to construct 'Option': Please use the 'new' operator, this DOM object constructor cannot be called as a function.

Stack trace:
at ProxyFacade (http://localhost:3000/public/build/app.2e96337131504da53393.js:231972:20)
in Option (created by Select)
in div (created by MenuList)
in MenuList (created by MenuPlacer)
in ScrollBlock (created by MenuPlacer)
in NodeResolver (created by ScrollCaptor)
in ScrollCaptor (created by ScrollCaptorSwitch)
in ScrollCaptorSwitch (created by MenuPlacer)
in div (created by Menu)
in Menu (created by MenuPlacer)
in MenuPlacer (created by Select)
in div (created by SelectContainer)
in SelectContainer (created by Select)
in Select (created by StateManager)
in StateManager (created by Async)
in Async (created by AsyncSelect)
in AsyncSelect (created by UserPicker)
in div (created by UserPicker)
in UserPicker (created by AddPermissions)
in div (created by AddPermissions)
in div (created by AddPermissions)
in form (created by AddPermissions)
in div (created by AddPermissions)
in AddPermissions (created by FolderPermissions)
in div (created by Transition)
in Transition (created by Component)
in Component (created by FolderPermissions)
in div (created by FolderPermissions)
in div (created by FolderPermissions)
in FolderPermissions (created by Connect(FolderPermissions))
in Connect(FolderPermissions) (created by HotExportedConnect(FolderPermissions))
in AppContainer (created by HotExportedConnect(FolderPermissions))
in HotExportedConnect(FolderPermissions)
in Provider
TypeError: Failed to construct 'Option': Please use the 'new' operator, this DOM object constructor cannot be called as a function.

Stack trace:
at ProxyFacade (http://localhost:3000/public/build/app.2e96337131504da53393.js:231972:20)
in Option (created by Select)
in div (created by MenuList)
in MenuList (created by MenuPlacer)
in ScrollBlock (created by MenuPlacer)
in NodeResolver (created by ScrollCaptor)
in ScrollCaptor (created by ScrollCaptorSwitch)
in ScrollCaptorSwitch (created by MenuPlacer)
in div (created by Menu)
in Menu (created by MenuPlacer)
in MenuPlacer (created by Select)
in div (created by SelectContainer)
in SelectContainer (created by Select)
in Select (created by StateManager)
in StateManager (created by Async)
in Async (created by AsyncSelect)
in AsyncSelect (created by UserPicker)
in div (created by UserPicker)
in UserPicker (created by AddPermissions)
in div (created by AddPermissions)
in div (created by AddPermissions)
in form (created by AddPermissions)
in div (created by AddPermissions)
in AddPermissions (created by FolderPermissions)
in div (created by Transition)
in Transition (created by Component)
in Component (created by FolderPermissions)
in div (created by FolderPermissions)
in div (created by FolderPermissions)
in FolderPermissions (created by Connect(FolderPermissions))
in Connect(FolderPermissions) (created by HotExportedConnect(FolderPermissions))
in AppContainer (created by HotExportedConnect(FolderPermissions))
in HotExportedConnect(FolderPermissions)
in Provider
```

**Comment by marefr** [comment]
Have only confirmed a problem in development build but I'm guessing it's sort of the same problem in production build?
