### ISSUE TITLE
Grafana 2.0b Javascript Error on Import -> "List dashboards"

### ISSUE THREAD

**Issue by kylelanser** [grafana/grafana#1743]
Scenario:
- Operating System: CentOS 6
- Grafana 2.0.0-Beta1 installed via the latest RPM.
- On the page: Dashboards -> Import
- In the section: "Load dashboard from Graphite-Web
- Select a graphite datasource (previously created).
- Click "List dashboards"

Outcome:
No network request is sent, no dashboards are listed, and I get a javascript error.

In Chrome:
TypeError: undefined is not a function
    at l.b.listAll (app.8ae07506.js:24)
    at app.8ae07506.js:13
    at e (app.8ae07506.js:13)
    at l.$eval (app.8ae07506.js:12)
    at l.$apply (app.8ae07506.js:12)
    at HTMLButtonElement.<anonymous> (app.8ae07506.js:13)
    at HTMLButtonElement._.event.dispatch (app.8ae07506.js:6)
    at HTMLButtonElement.q.handle (app.8ae07506.js:5)

In IE 11:
TypeError: Object doesn't support property or method 'listDashboards'
   at b.listAll (http://10.10.10.25:3000/app/app.8ae07506.js:24:18770)
   at Anonymous function (http://10.10.10.25:3000/app/app.8ae07506.js:13:14385)
   at e (http://10.10.10.25:3000/app/app.8ae07506.js:13:27608)
   at l.prototype.$eval (http://10.10.10.25:3000/app/app.8ae07506.js:12:5057)
   at l.prototype.$apply (http://10.10.10.25:3000/app/app.8ae07506.js:12:5259)
   at Anonymous function (http://10.10.10.25:3000/app/app.8ae07506.js:13:27658)
   at _.event.dispatch (http://10.10.10.25:3000/app/app.8ae07506.js:6:1531)
   at q.handle (http://10.10.10.25:3000/app/app.8ae07506.js:5:30358)

I can with confidence say that my graphite installation is running correctly.

**Comment by torkelo** [comment]
Fixed in latest beta2 build, http://grafana.org/download/builds 
Please change the data source access mode to direct before importing, I could not get the "list dashboards" graphite api to work via the grafana data source proxy, and could not figure out why. After the import you can switch back to "Proxy" access mode for the data source.
