### ISSUE TITLE
IE 11 : Preferences dropboxes give React error

### ISSUE THREAD

**Issue by slangloisde** [grafana/grafana#17761]
**What happened**:  With IE 11, when choosing an option in the preferences page dropboxes, the whole section disapears and we get a JS error in console.

![image](https://user-images.githubusercontent.com/43825188/60106136-a9890900-9732-11e9-8bf2-17057c4eafe7.png)

![image](https://user-images.githubusercontent.com/43825188/60106176-bc9bd900-9732-11e9-8b81-0e2d258ff409.png)

**Anything else we need to know?**:
Here's the error : 
```
Error: Unspecified error.
   {
      [functions]: ,
      __proto__: { },
      description: "Unspecified error.",
      message: "Unspecified error.",
      name: "Error",
      number: -2147467259,
      stack: "Error: Unspecified error.
   at lr (https://local-dns.ent/public/build/vendor.f1b90925e974a5a6c44d.js:182:37963)
   at Ua (https://local-dns.ent/public/build/vendor.f1b90925e974a5a6c44d.js:182:88409)
   at Va (https://local-dns.ent/public/build/vendor.f1b90925e974a5a6c44d.js:182:90695)
   at qa (https://local-dns.ent/public/build/vendor.f1b90925e974a5a6c44d.js:182:91055)
   at Ls (https://local-dns.ent/public/build/vendor.f1b90925e974a5a6c44d.js:182:97945)
   at As (https://local-dns.ent/public/build/vendor.f1b90925e974a5a6c44d.js:182:97325)
   at Ps (https://local-dns.ent/public/build/vendor.f1b90925e974a5a6c44d.js:182:98700)
   at Cn (https://local-dns.ent/public/build/vendor.f1b90925e974a5a6c44d.js:182:30568)",
      Symbol()_10.zbt1oq5miu: undefined,
      Symbol()_11.zbt1oq5miu: undefined,
      Symbol()_12.zbt1oq5miu: undefined,
      Symbol()_13.zbt1oq5miu: undefined,
      Symbol()_14.zbt1oq5miu: undefined,
      Symbol()_15.zbt1oq5miu: undefined,
      Symbol()_16.zbt1oq5miu: undefined,
      Symbol()_17.zbt1oq5miu: undefined,
      Symbol()_x.zbt1oq5miuf: undefined,
      Symbol()_z.zbt1oq5miuf: undefined,
      Symbol(__immutablehash__)_1b.zbt1oq5miu: undefined,
      Symbol(observable)_1a.zbt1oq5miu: undefined,
      Symbol(react.async_mode)_19.zbt1oq5miu: undefined,
      Symbol(react.concurrent_mode)_s.zbt1oq5miuf: undefined,
      Symbol(react.context)_r.zbt1oq5miuf: undefined,
      Symbol(react.element)_l.zbt1oq5miuf: undefined,
      Symbol(react.forward_ref)_t.zbt1oq5miuf: undefined,
      Symbol(react.fragment)_n.zbt1oq5miuf: undefined,
      Symbol(react.lazy)_w.zbt1oq5miuf: undefined,
      Symbol(react.memo)_v.zbt1oq5miuf: undefined,
      Symbol(react.portal)_m.zbt1oq5miuf: undefined,
      Symbol(react.profiler)_p.zbt1oq5miuf: undefined,
      Symbol(react.provider)_q.zbt1oq5miuf: undefined,
      Symbol(react.strict_mode)_o.zbt1oq5miuf: undefined,
      Symbol(react.suspense)_u.zbt1oq5miuf: undefined,
      Symbol(rxSubscriber)_18.zbt1oq5miu: undefined,
      Symbol(Symbol.observable)_y.zbt1oq5miuf: undefined,
      Symbol(util.promisify.custom)_1c.zbt1oq5miu: undefined
   }

SCRIPT16389: Unspecified error.
react-dom.production.min.js (248,316)

```

**Environment**:
- Grafana version: 6.2
- OS Grafana is installed on: RHEL and CENTOS
- User OS & Browser: Win 10 with IE 11

**Comment by torkelo** [comment]
currently we do not fully support IE11, here is the main issue to vote for IE11 support https://github.com/grafana/grafana/issues/15754

**Comment by torkelo** [comment]
closking and linking to https://github.com/grafana/grafana/issues/15754   (IE11 support issue)
