### ISSUE TITLE
Usage of _ numerical separator breaks build

### ISSUE THREAD

**Issue by dlespiau** [grafana/grafana#18015]
**What happened**:

From a fresh checkout, I ran:

```
env GRAFANA_THEME=light yarn start:hot
```

The build errors out with:

```
Dev server] ERROR in ./public/app/plugins/datasource/loki/language_provider.ts
[Dev server] Module build failed (from ./node_modules/babel-loader/lib/index.js):
[Dev server] SyntaxError: /home/damien/go/src/github.com/grafana/grafana/public/app/plugins/datasource/loki/language_provider.ts: Identifier directly after number (25:18)
[Dev server] 
[Dev server]   23 | const HISTORY_ITEM_COUNT = 10;
[Dev server]   24 | const HISTORY_COUNT_CUTOFF = 1000 * 60 * 60 * 24; // 24h
[Dev server] > 25 | const NS_IN_MS = 1_000_000;
[Dev server]      |                   ^
[Dev server]   26 | export const LABEL_REFRESH_INTERVAL = 1000 * 30; // 30sec
[Dev server]   27 | 
[Dev server]   28 | const wrapLabel = (label: string) => ({ label });
[Dev server]     at Object.raise (/home/damien/go/src/github.com/grafana/grafana/node_modules/@babel/parser/lib/index.js:6322:17)
[Dev server]     at Object.readNumber (/home/damien/go/src/github.com/grafana/grafana/node_modules/@babel/parser/lib/index.js:7211:12)
[Dev server]     at Object.getTokenFromCode (/home/damien/go/src/github.com/grafana/grafana/node_modules/@babel/parser/lib/index.js:6945:14)
[Dev server]     at Object.getTokenFromCode (/home/damien/go/src/github.com/grafana/grafana/node_modules/@babel/parser/lib/index.js:5789:20)
[Dev server]     at Object.nextToken (/home/damien/go/src/github.com/grafana/grafana/node_modules/@babel/parser/lib/index.js:6520:12)
[Dev server]     at Object.next (/home/damien/go/src/github.com/grafana/grafana/node_modules/@babel/parser/lib/index.js:6460:10)
[Dev server]     at Object.eat (/home/damien/go/src/github.com/grafana/grafana/node_modules/@babel/parser/lib/index.js:6465:12)
[Dev server]     at Object.parseVar (/home/damien/go/src/github.com/grafana/grafana/node_modules/@babel/parser/lib/index.js:10414:16)
[Dev server]     at Object.parseVarStatement (/home/damien/go/src/github.com/grafana/grafana/node_modules/@babel/parser/lib/index.js:10234:10)
[Dev server]     at Object.parseStatementContent (/home/damien/go/src/github.com/grafana/grafana/node_modules/@babel/parser/lib/index.js:9830:21)
[Dev server]  @ ./public/app/plugins/datasource/loki/datasource.ts 40:0-51 425:33-49
[Dev server]  @ ./public/app/plugins/datasource/loki/module.ts
[Dev server]  @ ./public/app/features/plugins/built_in_plugins.ts
[Dev server]  @ ./public/app/features/plugins/plugin_loader.ts
[Dev server]  @ ./public/app/app.ts
[Dev server]  @ ./public/app/dev.ts
[Dev server]  @ multi (webpack)-dev-server/client?http://localhost:3333 (webpack)/hot/dev-server.js webpack-dev-server/client?http://localhost:3333 ./public/app/dev.ts
```

**What you expected to happen**:

Build finishes successfully!

**How to reproduce it (as minimally and precisely as possible)**:

```
env GRAFANA_THEME=light yarn start:hot
```

**Environment**:
- Grafana version: latest master (648aa62264758dad815e1b47a7356b42e7841717)

**Comment by dprokop** [comment]
@dlespiau thanks for reporting this. It seems like our webpack configs for start and start:hot task are slightly different and yield different results. I've created #18025 to investigate
