### ISSUE TITLE
Tests in packages/* should not get compiled

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#18047]
In a development environment, I am sometimes getting the false error:

```
>> FAIL packages/grafana-data/compiled/utils/string.test.js
>>   ● Test suite failed to run
>>
>>     Jest encountered an unexpected token
>>
>>     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
>>
>>     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
>>
>>     Here's what you can do:
>>      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
>>      • If you need a custom transformation specify a "transform" option in your config.
>>      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
>>
>>     You'll find more details and examples of these config options in the docs:
>>     https://jestjs.io/docs/en/configuration.html
>>
>>     Details:
>>
>>     /Users/ryan/gocode/src/github.com/grafana/grafana/packages/grafana-data/compiled/utils/string.test.js:1
>>     ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { stringToJsRegex, stringToMs } from './string';
>>                                                                                                     ^
>>
>>     SyntaxError: Unexpected token {
>>
>>       at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
>>       at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)
```

We can avoid this by not putting compiled tests into the `compiled` folder

**Comment by dehrax** [comment]
What are the steps to reproduce this issue?

**Comment by dehrax** [comment]
I'm running `npx tsc -p ./tsconfig.build,json` in the grafana-data dir, but no tests in the compiled folder. The config also says to exclude tests, so I wonder what's happening here.

**Comment by dprokop** [comment]
I've tried with `yarn packages:build`, no tests in `compiled` neither.

**Comment by dprokop** [comment]
`./node_modules/.bin/.tsc -p ./tsconfig.build.json` - no tests in `compiled` neither

**Comment by ryantxu** [comment]
I'm not really sure the steps to reproduce -- but I get it frequently in my dev environment.  Just got it again :(

The build commands in my history recent are:
```
yarn watch
yarn test
git checkout (other branches)
```

**Comment by torkelo** [comment]
Is this stll an issue? I think its just a problem after you build the npm packages (test publish) you need to remove the fist folder?
