### ISSUE TITLE
Document how to setup the debian repo for arm

### ISSUE THREAD

**Issue by daviehh** [grafana/grafana#18326]
According to the documentation [here](https://grafana.com/docs/installation/debian/#apt-repository), one can add the grafana repo, but `sudo add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"` fails with
```
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/buster
```

additionally, `https://packages.grafana.com/oss/deb` returns
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>No such object: grafana-repo/oss/deb</Details>
</Error>
```

**Comment by torkelo** [comment]
@xlson any ideas?

**Comment by Azrael-Masters** [comment]
Same issue here

**Comment by xlson** [comment]
@daviehh What raspberry pi board are you running?

Could you try doing a manual setup of the repository?

```bash
# create /etc/apt/sources.list/grafana.list with:
deb https://packages.grafana.com/oss/deb stable main

# run
apt update
apt install grafana
```
And report any errors.

**Comment by daviehh** [comment]
@xlson I changed your `/etc/apt/sources.list/grafana.list` to `/etc/apt/sources.list.d/grafana.list`since `sources.list` is the default apt list file whereas `sources.list.d` is the directory for custom lists. Uninstalling and reinstalling works fine. 
Thanks! Attached result:

```
~ sudo dpkg -r grafana                
(Reading database ... 54812 files and directories currently installed.)
Removing grafana (6.3.2) ...
~ sudo apt install grafana
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  grafana
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 31.1 MB of archives.
After this operation, 95.5 MB of additional disk space will be used.
Get:1 https://packages.grafana.com/oss/deb stable/main armhf grafana armhf 6.3.2 [31.1 MB]
Fetched 31.1 MB in 3s (10.5 MB/s)   
Selecting previously unselected package grafana.
(Reading database ... 52721 files and directories currently installed.)
Preparing to unpack .../grafana_6.3.2_armhf.deb ...
Unpacking grafana (6.3.2) ...
Setting up grafana (6.3.2) ...
Restarting grafana-server service... OK
Processing triggers for systemd (241-5+rpi1) ...
```

**Comment by xlson** [comment]
I'm glad to hear it worked. I will update our documentation. Would you be willing to help me test the new docs after I've made the changes?

**Comment by daviehh** [comment]
sure, thanks a lot!

**Comment by oddlittlebird** [comment]
@xlson , can we close this or do we still need to update something?

**Comment by xlson** [comment]
We need to add a little bit of docs, thanks for reminding me of this. I'll take care of it today.
