### ISSUE TITLE
Unable to view snapshot shared

### ISSUE THREAD

**Issue by costimuraru** [grafana/grafana#1846]
When trying to access a snapshot (either on http://snapshot.raintank.io/dashboard/snapshot/46q6lbxH0Rb36eio1WLAOPW4TeWDXtJ1 or on-premise) a js error is thrown:

```
Error in event handler for extension.onRequest: TypeError: Cannot read property 'toLowerCase' of null
    at createMicroInfoBoxes (chrome-extension://agnoocojkneiphkobpcfoaenhpjnmifb/Resources/JavaScript/Content.js:336:66)
    at chrome-extension://agnoocojkneiphkobpcfoaenhpjnmifb/Resources/JavaScript/Content.js:381:42handler @ extensions::uncaught_exception_handler:8exports.handle @ extensions::uncaught_exception_handler:100EventImpl.dispatch_ @ extensions::event_bindings:384EventImpl.dispatch @ extensions::event_bindings:401target.(anonymous function) @ extensions::SafeBuiltins:19$Array.forEach.publicClass.(anonymous function) @ extensions::utils:94messageListener @ extensions::messaging:188target.(anonymous function) @ extensions::SafeBuiltins:19EventImpl.dispatchToListener @ extensions::event_bindings:395target.(anonymous function) @ extensions::SafeBuiltins:19$Array.forEach.publicClass.(anonymous function) @ extensions::utils:94EventImpl.dispatch_ @ extensions::event_bindings:379EventImpl.dispatch @ extensions::event_bindings:401target.(anonymous function) @ extensions::SafeBuiltins:19$Array.forEach.publicClass.(anonymous function) @ extensions::utils:94dispatchOnMessage @ extensions::messaging:316
app.abcadd80.js:10 TypeError: Cannot read property 'text' of undefined
    at d.service.updateAutoInterval (app.abcadd80.js:21)
    at d.service.init (app.abcadd80.js:21)
    at l.d.controller.b.setupDashboard (app.abcadd80.js:21)
    at d.controller.init (app.abcadd80.js:21)
    at l.f.controller.f.initDashboard (app.abcadd80.js:26)
    at f.controller.c.get.then.a.initDashboard.meta.isSnapshot (app.abcadd80.js:27)
    at i (app.abcadd80.js:10)
    at app.abcadd80.js:10
    at l.$get.l.$eval (app.abcadd80.js:12)
    at l.$get.l.$digest (app.abcadd80.js:12)
```

![sgf](https://cloud.githubusercontent.com/assets/952836/7271561/e50fc03e-e8ec-11e4-90db-e326662662e7.jpg)

Snapshot created using: Grafana version: 2.0.1, commit: 9540e12, build date: 2015-04-20 14:21:42

**Comment by torkelo** [comment]
looks like you have a chrome extensions that is causing some problem

**Comment by torkelo** [comment]
looks like it is caused by an auto interval variable.
