### ISSUE TITLE
OpenTSDB auto-downsample query problem

### ISSUE THREAD

**Issue by ebereketoglu** [grafana/grafana#1850]
I am trying to visulize the data of the multiple OpenTSDB metrics in the same Grafana dashboard. When I set the time period as 7days ago to a few seconds ago, it brings 5m-avg downsampled data and works properly. But when  I set the time period as a month ago to a few seconds ago, it tries to bring 30m-avg downsampled data but it can't bring the data for some metrics. After this query, the Grafana dashboard, OpenTSDB and HBase services crashes,  I need to refresh the Grafana dashboard and restart the HBase and OpenTSDB services. When I checked the OpenTSDB logs, I get the below error. I am not sure the problem occurs because of the Grafana or OpenTSDB. Do you have any idea?

java.net.ConnectException: Connection refused
at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.7.0_76]
at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739) ~[na:1.7.0_76]
at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1143) ~[zookeeper-3.3.6.jar:3.3.6-1366786]
14:49:33.863 INFO [ClientCnxn.startConnect] - Opening socket connection to server localhost/127.0.0.1:2181
14:49:33.864 WARN [ClientCnxn.run] - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.7.0_76]
at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739) ~[na:1.7.0_76]
at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1143) ~[zookeeper-3.3.6.jar:3.3.6-1366786]

**Comment by torkelo** [comment]
I do not know, maybe report the issue to the OpenTSDB project, they might have more experiance with issues like this

**Comment by ebereketoglu** [comment]
I have reported the issue to the OpenTSDB project too, I have just wanted to be sure the issue is an OpenTSDB issue.
