### ISSUE TITLE
OpenTSDB : templating variable and values of tagk failed

### ISSUE THREAD

**Issue by handfreezer** [grafana/grafana#19112]
**What happened**: templating variable of values from a key in opentsdb failed

**What you expected to happen**: get the list a value available in DB for a specific tagkey

**How to reproduce it (as minimally and precisely as possible)**: declare a datasource of opentsdb (grafana server is proxying request to opentsdb), fill metric, open a dashboard, create a template, choose type=query, select your datasource opentsdb, set query to tag_values(icinga.host.rta,host) (base on fact that your are using Icinga2 and default OpenTSDB feature for perf_data), you'll get this error : 
![image](https://user-images.githubusercontent.com/2912752/64924556-50d38480-d7e6-11e9-9643-bdecaf9ce98c.png)

**Anything else we need to know?**: metrics are present and tag key host is available, if creating a template with the query "metrics(icinga.host.rta)" I got available values: "icinga.host.rta icinga.host.rta_crit icinga.host.rta_warn"

**Environment**:
- Grafana version: 6.3.5
- Data source type & version: opentsdb 2.4.0 deb package
- OS Grafana is installed on:debian_version 10.1
- User OS & Browser: win10 / Chrome 77.0.3865.75
- Grafana plugins: NA
- Others: NA

**Comment by papagian** [comment]
Thank you for reporting this. Could you please provide the response from the opentsdb using chrome/firefox developer tools network tab?

**Comment by handfreezer** [comment]
Two thinks:
First, : when I save my template and go back to dash board, I have this error message:
![image](https://user-images.githubusercontent.com/2912752/64927582-ff8abb80-d80c-11e9-8625-e9d25d77e774.png)

Second, screen shot of developper tools network tab:
![image](https://user-images.githubusercontent.com/2912752/64927619-6e681480-d80d-11e9-9003-1a7308e2c328.png)

**Comment by papagian** [comment]
In your [datasource setup](https://grafana.com/docs/features/datasources/opentsdb/#using-opentsdb-in-grafana) the `Access` is set to `Server` or `Browser`? Can you try to change it?

**Comment by handfreezer** [comment]
It is set to "Server" , setting "Browser" is not really an option as the client won't have access to opentsdb server  for security purposes (opentsdb API do not have authenticationmecanism and OpenTSDB recommend to not give public access, normal).

But, I test it  without changing security of the platform and I got this message:
![image](https://user-images.githubusercontent.com/2912752/64951610-8d52bf00-d87e-11e9-8e29-392b5b10576d.png)

If I remove the security of the platform, I got this:
![image](https://user-images.githubusercontent.com/2912752/64951810-094d0700-d87f-11e9-90c2-9d8c4ecbb3f3.png)

I think that setting "Server" is really the best choice : for security reasons and simplicity of deployment.

**Comment by hugohaggmark** [comment]
@papagian can you have a look what todo with this issue?

**Comment by papagian** [comment]
@hugohaggmark sure

**Comment by papagian** [comment]
@handfreezer sorry for the late reply.
According to [this](http://opentsdb.net/docs/build/html/api_http/index.html#cors) you should be able to bypass the CORS errors your are experiencing by setting appropriately the `tsd.http.request.cors_domains` in your OpenTSDB configuration.
 Would you like to try this?

**Comment by handfreezer** [comment]
Don't worry,you're not so late, as I'm reading now only.
I'm happy to get some help and give it a try before end of Sunday, and keep you up-to-date.

**Comment by handfreezer** [comment]
hello, it does not have change the result, BUT, I discovered an error in the web console and reproduce it in commande line. It seems that the key work tag_names generate a bad request.
I tried this (request metrics(icin) ):
curl -kvL "http://localhost:4242/api/suggest?max=1000&q=icinga.host.pl&type=metrics"

And result was:
["icinga.host.pl","icinga.host.pl_crit","icinga.host.pl_warn"]

Then I try the request tag_names(icinga.host.pl):
curl -kvL "http://localhost:4242/api/search/lookup?limit=1000&m=icinga.host.pl"

and the result was:
Empty reply from server

AND, on the second cul request, I got this in opentsdb log:
00:24:17.061 INFO  [ConnectionManager.handleUpstream] - [id: 0x875689f5, /127.0.0.1:58640 => /127.0.0.1:4242] OPEN
00:24:17.062 INFO  [ConnectionManager.handleUpstream] - [id: 0x875689f5, /127.0.0.1:58640 => /127.0.0.1:4242] BOUND: /127.0.0.1:4242
00:24:17.062 INFO  [ConnectionManager.handleUpstream] - [id: 0x875689f5, /127.0.0.1:58640 => /127.0.0.1:4242] CONNECTED: /127.0.0.1:58640
00:24:17.066 INFO  [HttpQuery.logInfo] - [id: 0x875689f5, /127.0.0.1:58640 => /127.0.0.1:4242] HTTP /api/suggest?max=1000&q=icinga.host.pl&type=metrics done in 2ms
00:24:17.067 INFO  [ConnectionManager.handleUpstream] - [id: 0x875689f5, /127.0.0.1:58640 :> /127.0.0.1:4242] DISCONNECTED
00:24:17.067 INFO  [ConnectionManager.handleUpstream] - [id: 0x875689f5, /127.0.0.1:58640 :> /127.0.0.1:4242] UNBOUND
00:24:17.067 INFO  [ConnectionManager.handleUpstream] - [id: 0x875689f5, /127.0.0.1:58640 :> /127.0.0.1:4242] CLOSED







00:24:23.074 INFO  [ConnectionManager.handleUpstream] - [id: 0x6b7cae2f, /127.0.0.1:58644 => /127.0.0.1:4242] OPEN
00:24:23.075 INFO  [ConnectionManager.handleUpstream] - [id: 0x6b7cae2f, /127.0.0.1:58644 => /127.0.0.1:4242] BOUND: /127.0.0.1:4242
00:24:23.076 INFO  [ConnectionManager.handleUpstream] - [id: 0x6b7cae2f, /127.0.0.1:58644 => /127.0.0.1:4242] CONNECTED: /127.0.0.1:58644
00:24:23.080 ERROR [ConnectionManager.exceptionCaught] - Unexpected exception from downstream for [id: 0x6b7cae2f, /127.0.0.1:58644 => /127.0.0.1:4242]
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
        at net.opentsdb.uid.UniqueId.uidToString(UniqueId.java:1412) ~[tsdb-2.4.0.jar:14ab3ef]
        at net.opentsdb.search.TimeSeriesLookup$1MetricCB.call(TimeSeriesLookup.java:370) ~[tsdb-2.4.0.jar:14ab3ef]
        at net.opentsdb.search.TimeSeriesLookup$1MetricCB.call(TimeSeriesLookup.java:366) ~[tsdb-2.4.0.jar:14ab3ef]
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) ~[async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.addCallbacks(Deferred.java:688) ~[async-1.4.0.jar:na]
        at com.stumbleupon.async.Deferred.addCallbackDeferring(Deferred.java:738) ~[async-1.4.0.jar:na]
        at net.opentsdb.search.TimeSeriesLookup.resolveUIDs(TimeSeriesLookup.java:378) ~[tsdb-2.4.0.jar:14ab3ef]
        at net.opentsdb.search.TimeSeriesLookup.lookupAsync(TimeSeriesLookup.java:305) ~[tsdb-2.4.0.jar:14ab3ef]
        at net.opentsdb.tsd.SearchRpc.processLookup(SearchRpc.java:294) ~[tsdb-2.4.0.jar:14ab3ef]
        at net.opentsdb.tsd.SearchRpc.execute(SearchRpc.java:85) ~[tsdb-2.4.0.jar:14ab3ef]
        at net.opentsdb.tsd.RpcHandler.handleHttpQuery(RpcHandler.java:282) ~[tsdb-2.4.0.jar:14ab3ef]
        at net.opentsdb.tsd.RpcHandler.messageReceived(RpcHandler.java:133) ~[tsdb-2.4.0.jar:14ab3ef]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.handler.timeout.IdleStateAwareChannelUpstreamHandler.handleUpstream(IdleStateAwareChannelUpstreamHandler.java:36) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:294) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.handler.codec.http.HttpContentEncoder.messageReceived(HttpContentEncoder.java:82) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) ~[netty-3.10.6.Final.jar:na]
        at net.opentsdb.tsd.ConnectionManager.handleUpstream(ConnectionManager.java:128) ~[tsdb-2.4.0.jar:14ab3ef]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[netty-3.10.6.Final.jar:na]
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) ~[netty-3.10.6.Final.jar:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:835) ~[na:na]
00:24:23.085 INFO  [ConnectionManager.handleUpstream] - [id: 0x6b7cae2f, /127.0.0.1:58644 :> /127.0.0.1:4242] DISCONNECTED
00:24:23.085 INFO  [ConnectionManager.handleUpstream] - [id: 0x6b7cae2f, /127.0.0.1:58644 :> /127.0.0.1:4242] UNBOUND
00:24:23.086 INFO  [ConnectionManager.handleUpstream] - [id: 0x6b7cae2f, /127.0.0.1:58644 :> /127.0.0.1:4242] CLOSED
00:24:35.634 INFO  [ConnectionManager.handleUpstream] - [id: 0xc80128d1, /127.0.0.1:58568 :> /127.0.0.1:4242] DISCONNECTED
00:24:35.636 INFO  [ConnectionManager.handleUpstream] - [id: 0xc80128d1, /127.0.0.1:58568 :> /127.0.0.1:4242] UNBOUND
00:24:35.637 INFO  [ConnectionManager.handleUpstream] - [id: 0xc80128d1, /127.0.0.1:58568 :> /127.0.0.1:4242] CLOSED


So, I guess that my opentsdb is not well installed/configured, OR the generated request is not good.

Any idea?

**Comment by torkelo** [comment]
no ideas :( 

Looks like a OpenTSDB backend issue and not a problem with Grafana
