### ISSUE TITLE
Unable to get plugin template from @grafana/toolkit

### ISSUE THREAD

**Issue by krishna217** [grafana/grafana#19617]
**What happened**: Ran npx grafana-toolkit plugin:create my-grafana-plugin command with toolkit

**What you expected to happen**: Clone the react plugin template

**Error**: 
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

**Anything else we need to know?**:  Running @grafana/toolkit@6.4.0-beta.2

**Environment**: Windows 10
- Grafana version: 6.4
- OS Grafana is installed on: Windows
- User Browser: Chrome
- Others: Node @ 10.14.1

**Comment by hugohaggmark** [comment]
Thanks for reporting this @krishna217, I can definitely repro this. Have you tried our recent 6.4.0 release as well? 
![image](https://user-images.githubusercontent.com/562238/66192172-2f044980-e690-11e9-86d2-d01b971efe1d.png)

**Comment by krishna217** [comment]
I found a issue with my ssh key. Hence i am getting above error. Now it's working fine.

Also i updated toolkit to 6.4.0 and ran the same command and getting the following error:

$ npx grafana-toolkit plugin:create my-grafana-plugin
? Select plugin type (Use arrow keys)
? Select plugin type React panel
- Fetching plugin template...
√ Fetching plugin template...
  Trace: TypeError: Cannot read property 'trim' of null
      at Object.<anonymous> (C:\Users\kmannam\node_modules\@grafana\toolkit\src\cli\tasks\plugin\create.js:71:40)
      at step (C:\Users\kmannam\node_modules\tslib\tslib.js:136:27)
      at Object.next (C:\Users\kmannam\node_modules\tslib\tslib.js:117:57)
      at fulfilled (C:\Users\kmannam\node_modules\tslib\tslib.js:107:62)
      at process._tickCallback (internal/process/next_tick.js:68:7)
      at Object.<anonymous> (C:\Users\kmannam\node_modules\@grafana\toolkit\src\cli\utils\execTask.js:26:25)
      at step (C:\Users\kmannam\node_modules\tslib\tslib.js:136:27)
      at Object.throw (C:\Users\kmannam\node_modules\tslib\tslib.js:117:57)
      at rejected (C:\Users\kmannam\node_modules\tslib\tslib.js:108:69)
      at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by dprokop** [comment]
@krishna217 the problem you have encountered is related to the fact that you don't have git config's user.name set. I have fixed that in https://github.com/grafana/grafana/pull/19821
