### ISSUE TITLE
ModuleNotFoundError: Module not found: Error: Can't resolve 'rxjs' in

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#19613]
I tried to build latest master frontend using

```
yarn install --pure-lock
yarn run build
```

The module is there

```
[00:56:40]W:			 [Build] + ls -la node_modules/rxjs
[00:56:40] :			 [Build] total 0
[00:56:40] :			 [Build] drwxr-xr-x    7 1001 1001   140 Oct  3 22:56 .
[00:56:40] :			 [Build] drwxr-xr-x 1844 1001 1001 36900 Oct  3 22:56 ..
[00:56:40] :			 [Build] drwxr-xr-x    3 1001 1001    60 Oct  3 22:56 node_modules
[00:56:40] :			 [Build] drwxr-xr-x    2 1001 1001   220 Oct  3 22:56 symbol
[00:56:40] :			 [Build] drwxr-xr-x    2 1001 1001   120 Oct  3 22:56 testing
[00:56:40] :			 [Build] drwxr-xr-x    2 1001 1001  1960 Oct  3 22:56 util
[00:56:40] :			 [Build] drwxr-xr-x    2 1001 1001   120 Oct  3 22:56 webSocket
```

however getting many errors like this. Any idea how to resolve it?

```[00:03:23]	[Build]   ModuleNotFoundError: Module not found: Error: Can't resolve 'rxjs' in '/go/src/github.com/grafana/grafana/public/app/plugins/datasource/prometheus'
[00:03:23]	[Build]       at /go/src/github.com/grafana/grafana/node_modules/webpack/lib/Compilation.js:823:10
[00:03:23]	[Build]       at /go/src/github.com/grafana/grafana/node_modules/webpack/lib/NormalModuleFactory.js:397:22
[00:03:23]	[Build]       at /go/src/github.com/grafana/grafana/node_modules/webpack/lib/NormalModuleFactory.js:130:21
[00:03:23]	[Build]       at /go/src/github.com/grafana/grafana/node_modules/webpack/lib/NormalModuleFactory.js:224:22
[00:03:23]	[Build]       at /go/src/github.com/grafana/grafana/node_modules/neo-async/async.js:2825:7
[00:03:23]	[Build]       at /go/src/github.com/grafana/grafana/node_modules/neo-async/async.js:6886:13
[00:03:23]	[Build]       at /go/src/github.com/grafana/grafana/node_modules/webpack/lib/NormalModuleFactory.js:214:25
[00:03:23]	[Build]       at /go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/Resolver.js:184:12
[00:03:23]	[Build]       at /go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/Resolver.js:238:5
[00:03:23]	[Build]       at eval (eval at create (/go/src/github.com/grafana/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
[00:03:23]	[Build]       at /go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5
[00:03:23]	[Build]       at /go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/Resolver.js:238:5
[00:03:23]	[Build]       at eval (eval at create (/go/src/github.com/grafana/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
[00:03:23]	[Build]       at /go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/Resolver.js:238:5
[00:03:23]	[Build]       at eval (eval at create (/go/src/github.com/grafana/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
[00:03:23]	[Build]       at /go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38
[00:03:23]	[Build]       at /go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/Resolver.js:238:5
[00:03:23]	[Build]       at eval (eval at create (/go/src/github.com/grafana/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
[00:03:23]	[Build]       at /go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:23:37
[00:03:23]	[Build]       at /go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/Resolver.js:238:5
[00:03:23]	[Build]       at eval (eval at create (/go/src/github.com/grafana/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
[00:03:23]	[Build]       at /go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/Resolver.js:238:5
[00:03:23]	[Build]       at eval (eval at create (/go/src/github.com/grafana/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
[00:03:23]	[Build]       at /go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/Resolver.js:238:5
[00:03:23]	[Build]       at eval (eval at create (/go/src/github.com/grafana/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
[00:03:23]	[Build]       at /go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5
[00:03:23]	[Build]       at /go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/Resolver.js:238:5
[00:03:23]	[Build]       at eval (eval at create (/go/src/github.com/grafana/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
[00:03:23]	[Build]       at /go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/Resolver.js:238:5
[00:03:23]	[Build]       at eval (eval at create (/go/src/github.com/grafana/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
[00:03:23]	[Build]       at /go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38
[00:03:23]	[Build]       at /go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/Resolver.js:238:5
[00:03:23]	[Build]       at eval (eval at create (/go/src/github.com/grafana/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
[00:03:23]	[Build]       at /go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/Resolver.js:238:5
[00:03:23]	[Build]       at eval (eval at create (/go/src/github.com/grafana/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
[00:03:23]	[Build]       at /go/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38
[00:03:23]	[Build]   resolve 'rxjs' in '/go/src/github.com/grafana/grafana/public/app/plugins/datasource/prometheus'
[00:03:23]	[Build]     Parsed request is a module
[00:03:23]	[Build]     using description file: /go/src/github.com/grafana/grafana/package.json (relative path: ./public/app/plugins/datasource/prometheus)
[00:03:23]	[Build]       Field 'browser' doesn't contain a valid alias configuration
[00:03:23]	[Build]       resolve as module
[00:03:23]	[Build]         looking for modules in /go/src/github.com/grafana/grafana/public
[00:03:23]	[Build]           using description file: /go/src/github.com/grafana/grafana/package.json (relative path: ./public)
[00:03:23]	[Build]             Field 'browser' doesn't contain a valid alias configuration
[00:03:23]	[Build]             using description file: /go/src/github.com/grafana/grafana/package.json (relative path: ./public/rxjs)
[00:03:23]	[Build]               no extension
[00:03:23]	[Build]                 Field 'browser' doesn't contain a valid alias configuration
[00:03:23]	[Build]                 /go/src/github.com/grafana/grafana/public/rxjs doesn't exist
[00:03:23]	[Build]               .ts
[00:03:23]	[Build]                 Field 'browser' doesn't contain a valid alias configuration
[00:03:23]	[Build]                 /go/src/github.com/grafana/grafana/public/rxjs.ts doesn't exist
[00:03:23]	[Build]               .tsx
[00:03:23]	[Build]                 Field 'browser' doesn't contain a valid alias configuration
[00:03:23]	[Build]                 /go/src/github.com/grafana/grafana/public/rxjs.tsx doesn't exist
[00:03:23]	[Build]               .es6
[00:03:23]	[Build]                 Field 'browser' doesn't contain a valid alias configuration
[00:03:23]	[Build]                 /go/src/github.com/grafana/grafana/public/rxjs.es6 doesn't exist
[00:03:23]	[Build]               .js
[00:03:23]	[Build]                 Field 'browser' doesn't contain a valid alias configuration
[00:03:23]	[Build]                 /go/src/github.com/grafana/grafana/public/rxjs.js doesn't exist
[00:03:23]	[Build]               .json
[00:03:23]	[Build]                 Field 'browser' doesn't contain a valid alias configuration
[00:03:23]	[Build]                 /go/src/github.com/grafana/grafana/public/rxjs.json doesn't exist
[00:03:23]	[Build]               .svg
[00:03:23]	[Build]                 Field 'browser' doesn't contain a valid alias configuration
[00:03:23]	[Build]                 /go/src/github.com/grafana/grafana/public/rxjs.svg doesn't exist
[00:03:23]	[Build]               as directory
[00:03:23]	[Build]                 /go/src/github.com/grafana/grafana/public/rxjs doesn't exist
[00:03:23]	[Build]         looking for modules in /go/src/github.com/grafana/grafana/node_modules
[00:03:23]	[Build]           using description file: /go/src/github.com/grafana/grafana/package.json (relative path: ./node_modules)
[00:03:23]	[Build]             Field 'browser' doesn't contain a valid alias configuration
[00:03:23]	[Build]             using description file: /go/src/github.com/grafana/grafana/package.json (relative path: ./node_modules/rxjs)
[00:03:23]	[Build]               no extension
[00:03:23]	[Build]                 Field 'browser' doesn't contain a valid alias configuration
[00:03:23]	[Build]                 /go/src/github.com/grafana/grafana/node_modules/rxjs is not a file
[00:03:23]	[Build]               .ts
[00:03:23]	[Build]                 Field 'browser' doesn't contain a valid alias configuration
[00:03:23]	[Build]                 /go/src/github.com/grafana/grafana/node_modules/rxjs.ts doesn't exist
[00:03:23]	[Build]               .tsx
[00:03:23]	[Build]                 Field 'browser' doesn't contain a valid alias configuration
[00:03:23]	[Build]                 /go/src/github.com/grafana/grafana/node_modules/rxjs.tsx doesn't exist
[00:03:23]	[Build]               .es6
[00:03:23]	[Build]                 Field 'browser' doesn't contain a valid alias configuration
[00:03:23]	[Build]                 /go/src/github.com/grafana/grafana/node_modules/rxjs.es6 doesn't exist
[00:03:23]	[Build]               .js
[00:03:23]	[Build]                 Field 'browser' doesn't contain a valid alias configuration
[00:03:23]	[Build]                 /go/src/github.com/grafana/grafana/node_modules/rxjs.js doesn't exist
[00:03:23]	[Build]               .json
[00:03:23]	[Build]                 Field 'browser' doesn't contain a valid alias configuration
[00:03:23]	[Build]                 /go/src/github.com/grafana/grafana/node_modules/rxjs.json doesn't exist
[00:03:23]	[Build]               .svg
[00:03:23]	[Build]                 Field 'browser' doesn't contain a valid alias configuration
[00:03:23]	[Build]                 /go/src/github.com/grafana/grafana/node_modules/rxjs.svg doesn't exist
[00:03:23]	[Build]               as directory
[00:03:23]	[Build]                 existing directory
[00:03:23]	[Build]                   using path: /go/src/github.com/grafana/grafana/node_modules/rxjs/index
[00:03:23]	[Build]                     using description file: /go/src/github.com/grafana/grafana/package.json (relative path: ./node_modules/rxjs/index)
[00:03:23]	[Build]                       no extension
[00:03:23]	[Build]                         Field 'browser' doesn't contain a valid alias configuration
[00:03:23]	[Build]                         /go/src/github.com/grafana/grafana/node_modules/rxjs/index doesn't exist
[00:03:23]	[Build]                       .ts
[00:03:23]	[Build]                         Field 'browser' doesn't contain a valid alias configuration
[00:03:23]	[Build]                         /go/src/github.com/grafana/grafana/node_modules/rxjs/index.ts doesn't exist
[00:03:23]	[Build]                       .tsx
[00:03:23]	[Build]                         Field 'browser' doesn't contain a valid alias configuration
[00:03:23]	[Build]                         /go/src/github.com/grafana/grafana/node_modules/rxjs/index.tsx doesn't exist
[00:03:23]	[Build]                       .es6
[00:03:23]	[Build]                         Field 'browser' doesn't contain a valid alias configuration
[00:03:23]	[Build]                         /go/src/github.com/grafana/grafana/node_modules/rxjs/index.es6 doesn't exist
[00:03:23]	[Build]                       .js
[00:03:23]	[Build]                         Field 'browser' doesn't contain a valid alias configuration
[00:03:23]	[Build]                         /go/src/github.com/grafana/grafana/node_modules/rxjs/index.js doesn't exist
[00:03:23]	[Build]                       .json
[00:03:23]	[Build]                         Field 'browser' doesn't contain a valid alias configuration
[00:03:23]	[Build]                         /go/src/github.com/grafana/grafana/node_modules/rxjs/index.json doesn't exist
[00:03:23]	[Build]                       .svg
[00:03:23]	[Build]                         Field 'browser' doesn't contain a valid alias configuration
[00:03:23]	[Build]                         /go/src/github.com/grafana/grafana/node_modules/rxjs/index.svg doesn't exist```

**Comment by hugohaggmark** [comment]
@simPod could you try to remove all the `node_modules` under the grafana dir and under all the `grafana/packages/grafana-*/node_modules` and run `yarn install --pure-lockfile` and `yarn run build`. Did that help?

**Comment by simPod** [comment]
@hugohaggmark thanks for response! I initially thought it's rxjs related but it was not. There were probably some corrupted packages in cache. Had to clear yarn cache and install all again.
