### ISSUE TITLE
Unable to upload alert images to s3 + grafana-image-renderer incompatible with grafana/grafana:6.4.1

### ISSUE THREAD

**Issue by markuman** [grafana/grafana#19695]
This is my bucket policy

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowUserToReadWriteObjectData",
            "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:PutObjectAcl",
                "s3:DeleteObject",
                "s3:Put*",
                "s3:Get*",
                "s3:List*",
                "s3:DeleteObject"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::grafana.some.bucket/*",
                "arn:aws:s3:::grafana.some.buclet"
            ]
        }
    ]
}
```

And I tried every grafana config I could find here in the buck tracker, but nothing worked

nor `bucket_url`
```
[external_image_storage]
provider = s3

[external_image_storage.s3]
bucket_url = https://grafana.some.bucket.s3-eu-central-1.amazonaws.com
access_key = GRAFANA_ACCESS_KEY
secret_key = GRAFANA_SECRET_KEY
```

nor `bucket`
```
[external_image_storage]
provider = s3

[external_image_storage.s3]
bucket = grafana.some.bucket
region = eu-central-1
access_key = GRAFANA_ACCESS_KEY
secret_key = GRAFANA_SECRET_KEY
```

and I also tried with ecs task role. but no chance, everything results in

```
DBUG[10-08|09:05:31] Phantomjs output                         logger=rendering out="Loading a web page: http://localhost:3000/d-solo/Q3wlPS6iz/db-div?orgId=1&panelId=6&render=1 status: fail 30000\n"
DBUG[10-08|09:05:31] Phantomjs error                          logger=rendering error="signal: killed"
INFO[10-08|09:05:31] Rendering timed out                      logger=rendering
EROR[10-08|09:05:31] Failed to upload alert panel image.      logger=alerting.notifier error="Timeout error. You can set timeout in seconds with &timeout url parameter"
```

instead of phantomjs, I also tried to use `grafana-cli plugins install grafana-image-renderer`.  
However, the official docker image `grafana/grafana:6.4.1` is not compatible with this plugin.

```dockerfile
FROM grafana/grafana:6.4.1

RUN grafana-cli plugins install jasonlashua-prtg-datasource
RUN grafana-cli plugins install grafana-piechart-panel
RUN grafana-cli plugins install jdbranham-diagram-panel
RUN grafana-cli plugins install grafana-image-renderer

COPY --chown=grafana grafana.ini /etc/grafana/grafana.ini

USER root
RUN apk update && apk add libx11 libxcomposite libxcursor libxdamage \
    libxscrnsaver libxext libxi libxtst glib nss cups-libs libxrandr \
    alsa-lib chromium zlib

```

next to dozen new dependencies for this fancy new plugin, there is something wrong with libz.so.1 on alpine linux

```
EROR[10-08|09:02:11] Failed to upload alert panel image.      logger=alerting.notifier error="Rendering failed: Error: Failed to launch chrome!\n/var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome: /usr/lib/libasound.so.2: no version information available (required by /var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome)\n/var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib/libpng16.so.16)\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n"
```

So everything seems to be broken atm. Or am I just to stupid? Any ideas?

**Comment by markuman** [comment]
@xlson nothing happen

```
INFO[10-09|05:08:40] Rendering                                logger=rendering path="d-solo/23q88TAmk/aws?orgId=1&from=1570511317438&to=1570597717438&panelId=20&width=1000&height=500&tz=Europe%2FBerlin"
DBUG[10-09|05:08:40] executing Phantomjs                      logger=rendering binPath=/usr/share/grafana/tools/phantomjs/phantomjs cmdArgs="[--ignore-ssl-errors=true --web-security=true --local-url-access=false --debug=true /usr/share/grafana/tools/phantomjs/render.js url=http://localhost:3000/d-solo/23q88TAmk/aws?orgId=1&from=1570511317438&to=1570597717438&panelId=20&width=1000&height=500&tz=Europe%2FBerlin&render=1 width=1000 height=500 png=/var/lib/grafana/png/xQNF8jpPUwA24DFxNs4P.png domain=localhost timeout=60 renderKey=5mWIzZ5ved1riwqMAZZtwA1zzWcHOApk]" timezone=Europe/Berlin
DBUG[10-09|05:09:42] Phantomjs output                         logger=rendering out="Loading a web page: http://localhost:3000/d-solo/23q88TAmk/aws?orgId=1&from=1570511317438&to=1570597717438&panelId=20&width=1000&height=500&tz=Europe%2FBerlin&render=1 status: fail 60000\n"
DBUG[10-09|05:09:42] Phantomjs error                          logger=rendering error="signal: killed"
INFO[10-09|05:09:42] Rendering timed out                      logger=rendering
EROR[10-09|05:09:42] Timeout error. You can set timeout in seconds with &timeout url parameter logger=context userId=2 orgId=1 uname=bergholm error="Timeout error. You can set timeout in seconds with &timeout url parameter"
EROR[10-09|05:09:42] Request Completed                        logger=context userId=2 orgId=1 uname=bergholm method=GET path=/render/d-solo/23q88TAmk/aws status=500 remote_addr=172.17.0.1 time_ms=62090 size=1782 referer="http://localhost:3000/d/23q88TAmk/aws?orgId=1"
```

this is what ff looks like

![grafanaerror](https://user-images.githubusercontent.com/3920157/66453231-f71c4e00-ea63-11e9-93ee-69c4f400ac9f.png)

**Comment by xlson** [comment]
Looks like PhantomJS is timing out on your panel. I would suggest trying to install the rendering plugin as its own docker container and use remote rendering. Unfortunately installing the renderig plugin within the main grafana container doesnt work very well, but running it separately should hopefully solve your issue.

The Grafana image renderer docker image is: `grafana/grafana-image-renderer:latest`, you need to expose port 8081 to Grafana and link Grafana to it using the configuration file.

Config:
```ini
[rendering]
# Options to configure external image rendering server like https://github.com/grafana/grafana-image-renderer
server_url = http://<server>:8081/render
;callback_url =
```

**Comment by markuman** [comment]
That results also in an error.

Grafana log

```
  t=2019-10-09T06:18:21+0000 lvl=eror msg="Failed to send request to remote rendering service." logger=rendering error="Get https://grafana-image-renderer.....de/render?domain=grafana.....de&encoding=&height=500&renderKey=7pPRWQhrdNTBrGOo2jkrO7A1I6Jx9DjD&timeout=60&timezone=Europe%2FBerlin&url=https%3A%2F%2Fgrafana.....de%2Fd-solo%2F23q88TAmk%2Faws%3ForgId%3D1%26from%3D1570515456063%26to%3D1570601856063%26panelId%3D20%26width%3D1000%26height%3D500%26tz%3DEurope%252FBerlin%26render%3D1&width=1000: context canceled"
  t=2019-10-09T06:18:21+0000 lvl=eror msg="Rendering failed." logger=context userId=0 orgId=1 uname= error="Failed to send request to remote rendering service. Get https://grafana-image-renderer.....de/render?domain=grafana.....de&encoding=&height=500&renderKey=7pPRWQhrdNTBrGOo2jkrO7A1I6Jx9DjD&timeout=60&timezone=Europe%2FBerlin&url=https%3A%2F%2Fgrafana.....de%2Fd-solo%2F23q88TAmk%2Faws%3ForgId%3D1%26from%3D1570515456063%26to%3D1570601856063%26panelId%3D20%26width%3D1000%26height%3D500%26tz%3DEurope%252FBerlin%26render%3D1&width=1000: context canceled"
  t=2019-10-09T06:18:21+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/render/d-solo/23q88TAmk/aws status=500 remote_addr=10.98.5.75 time_ms=60000 size=1722 referer="https://grafana.....de/d/23q88TAmk/aws?orgId=1"
```

Grafana Image Renderer Log

```
  render request recieved for https://grafana.....de/d-solo/23q88TAmk/aws?orgId=1&from=1570515456063&to=1570601856063&panelId=20&width=1000&height=500&tz=Europe%2FBerlin&render=1
  ::ffff:10.112.60.222 - - [09/Oct/2019:06:18:21 +0000] "GET /render?domain=grafana.....de&encoding=&height=500&renderKey=7pPRWQhrdNTBrGOo2jkrO7A1I6Jx9DjD&timeout=60&timezone=Europe%2FBerlin&url=https%3A%2F%2Fgrafana.....de%2Fd-solo%2F23q88TAmk%2Faws%3ForgId%3D1%26from%3D1570515456063%26to%3D1570601856063%26panelId%3D20%26width%3D1000%26height%3D500%26tz%3DEurope%252FBerlin%26render%3D1&width=1000 HTTP/1.1" - - "-" "Go-http-client/1.1"
  { TimeoutError: waiting for function failed: timeout 60000ms exceeded
  at new WaitTask (/usr/src/app/node_modules/puppeteer/lib/FrameManager.js:864:28)
  at Frame.waitForFunction (/usr/src/app/node_modules/puppeteer/lib/FrameManager.js:733:12)
  at Page.waitForFunction (/usr/src/app/node_modules/puppeteer/lib/Page.js:1036:29)
  at Browser.<anonymous> (/usr/src/app/build/browser.js:80:28)
  at Generator.next (<anonymous>)
  at fulfilled (/usr/src/app/build/browser.js:4:58)
  at process._tickCallback (internal/process/next_tick.js:68:7)
  stack:
  'TimeoutError: waiting for function failed: timeout 60000ms exceeded\n at new WaitTask (/usr/src/app/node_modules/puppeteer/lib/FrameManager.js:864:28)\n at Frame.waitForFunction (/usr/src/app/node_modules/puppeteer/lib/FrameManager.js:733:12)\n at Page.waitForFunction (/usr/src/app/node_modules/puppeteer/lib/Page.js:1036:29)\n at Browser.<anonymous> (/usr/src/app/build/browser.js:80:28)\n at Generator.next (<anonymous>)\n at fulfilled (/usr/src/app/build/browser.js:4:58)\n at process._tickCallback (internal/process/next_tick.js:68:7)',
  message: 'waiting for function failed: timeout 60000ms exceeded',
  name: 'TimeoutError',
  isBoom: true,
  isServer: true,
  data: null,
  output:
  { statusCode: 500,
  payload:
  { statusCode: 500,
  error: 'Internal Server Error',
  message: 'An internal server error occurred' },
  headers: {} },
  reformat: [Function],
  isDeveloperError: true }
```

It is all deployed on aws ecs behind application loadbalancer.  
They can reach each other. I can make a curl from grafana to grafana-image-renderer and vise versa.

**Comment by marefr** [comment]
@markuman please include your grafana configuration in regards to [server](https://grafana.com/docs/installation/configuration/#server) and [rendering](https://grafana.com/docs/installation/configuration/#rendering) sections. 

Also what's the public url you're using for Grafana and what's the internal addresses of grafana and grafana-image-renderer? Please strip out any sensitive information.

**Comment by xlson** [comment]
Have you set the callback_url to the url of your grafana instance? That might be able to cause the timeout.

Example of what it looks like for me in docker-compose local test case:
```yaml
  remote-renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_RENDERING_SERVER_URL: http://remote-renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
```

**Comment by torkelo** [comment]
think there is a problem accessing the server from the local instance, I see it's using https.  Please include your server settings. 

Closing due to lack of updates
