### ISSUE TITLE
Grafana Toolkit: stats undefined

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#20560]
I followed this guide https://github.com/grafana/grafana/blob/master/packages/grafana-toolkit/README.md, using latest versions of those dependencies.

Running `grafana-toolkit plugin:build` gives me

```
✔ Running tests
⠴ Compiling.../mydir/node_modules/@grafana/toolkit/src/cli/tasks/plugin/bundle.js:53
if (stats.hasErrors()) {
^

TypeError: Cannot read property 'hasErrors' of undefined
at /mydir/node_modules/@grafana/src/cli/tasks/plugin/bundle.ts:60:19
at finalCallback (/mydir/node_modules/webpack/lib/Compiler.js:220:39)
at /mydir/node_modules/webpack/lib/Compiler.js:268:23
at AsyncSeriesHook.eval [as callAsync] (eval at create (/mydir/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
at AsyncSeriesHook.lazyCompileHook (/mydir/node_modules/tapable/lib/Hook.js:154:20)
at /mydir/node_modules/webpack/lib/Compiler.js:267:22
at Compiler.emitRecords (/mydir/node_modules/webpack/lib/Compiler.js:449:39)
at /mydir/node_modules/webpack/lib/Compiler.js:261:10
at /mydir/node_modules/webpack/lib/Compiler.js:435:14
at _next0 (eval at create (/mydir/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
at eval (eval at create (/mydir/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
at /mydir/node_modules/copy-webpack-plugin/dist/index.js:116:7
at AsyncSeriesHook.eval [as callAsync] (eval at create (/mydir/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
at AsyncSeriesHook.lazyCompileHook (/mydir/node_modules/tapable/lib/Hook.js:154:20)
at /mydir/node_modules/webpack/lib/Compiler.js:432:27
at /mydir/node_modules/neo-async/async.js:2818:7
```

Any idea what's wrong? Thanks!

**Comment by hugohaggmark** [comment]
Thanks for reporting this @simPod but could you give us more details about  your environment and the specific version of grafana toolkit you're using?

**Comment by ryantxu** [comment]
Did your build fail before the error?  The code looks like:
```
        if (err) {
          reject(err.message);
        }
        if (stats.hasErrors()) {
          ...
```
There should likely be a `return` after the reject

**Comment by simPod** [comment]
@ryantxu ah, definitely something about that. Will investigate. Thanks.

**Comment by simPod** [comment]
Ok, so the actual issue was that I had no `version` property in package.json and replace-in-file webpack plugin could not replace `%VERSION%` in plugin.json as it was `undefined`. However, `return` is indeed missing. Sending a patch.

Thanks!
