### ISSUE TITLE
systemctl start grafana-server fails on armv7l (raspberry)

### ISSUE THREAD

**Issue by dpsenner** [grafana/grafana#21448]
**What happened**:

I restarted the raspberry. This resulted in the grafana-server systemd service to no longer start with the inconclusive error 2/invalid argument. journalctl reports the following:

```text
$ sudo journalctl -u grafana-server
[...]
Jan 11 13:09:19 hades systemd[1]: Started Grafana instance.
Jan 11 13:09:19 hades grafana-server[1917]: runtime: nameOff 0xffffffffbd074000 out of range 0xe0da10 - 0x14ec82c
Jan 11 13:09:19 hades grafana-server[1917]: fatal error: runtime: name offset out of range
Jan 11 13:09:19 hades grafana-server[1917]: goroutine 1 [running, locked to thread]:
Jan 11 13:09:19 hades grafana-server[1917]: runtime.throw(0x11ae68d, 0x21)
Jan 11 13:09:19 hades grafana-server[1917]:         /usr/local/go/src/runtime/panic.go:774 +0x5c fp=0x317787c sp=0x3177868 pc=0x4555c
Jan 11 13:09:19 hades grafana-server[1917]: runtime.resolveNameOff(0x100dd58, 0xbd074000, 0xe232a8)
Jan 11 13:09:19 hades systemd[1]: grafana-server.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 11 13:09:19 hades systemd[1]: grafana-server.service: Unit entered failed state.
Jan 11 13:09:19 hades systemd[1]: grafana-server.service: Failed with result 'exit-code'.
Jan 11 13:09:19 hades systemd[1]: grafana-server.service: Service hold-off time over, scheduling restart.
Jan 11 13:09:19 hades systemd[1]: Stopped Grafana instance.
Jan 11 13:09:19 hades systemd[1]: Started Grafana instance.
Jan 11 13:09:19 hades grafana-server[1962]: runtime: nameOff 0xffffffffbd074000 out of range 0xe0da10 - 0x14ec82c
Jan 11 13:09:19 hades grafana-server[1962]: fatal error: runtime: name offset out of range
Jan 11 13:09:19 hades grafana-server[1962]: goroutine 1 [running, locked to thread]:
Jan 11 13:09:19 hades grafana-server[1962]: runtime.throw(0x11ae68d, 0x21)
Jan 11 13:09:19 hades grafana-server[1962]:         /usr/local/go/src/runtime/panic.go:774 +0x5c fp=0x3d2987c sp=0x3d29868 pc=0x4555c
Jan 11 13:09:19 hades systemd[1]: grafana-server.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 11 13:09:19 hades systemd[1]: grafana-server.service: Unit entered failed state.
Jan 11 13:09:19 hades systemd[1]: grafana-server.service: Failed with result 'exit-code'.
Jan 11 13:09:19 hades systemd[1]: grafana-server.service: Service hold-off time over, scheduling restart.
Jan 11 13:09:19 hades systemd[1]: Stopped Grafana instance.
Jan 11 13:09:19 hades systemd[1]: Started Grafana instance.
Jan 11 13:09:19 hades grafana-server[1988]: runtime: nameOff 0xffffffffbd074000 out of range 0xe0da10 - 0x14ec82c
Jan 11 13:09:19 hades grafana-server[1988]: fatal error: runtime: name offset out of range
Jan 11 13:09:19 hades grafana-server[1988]: goroutine 1 [running, locked to thread]:
Jan 11 13:09:19 hades grafana-server[1988]: runtime.throw(0x11ae68d, 0x21)
Jan 11 13:09:19 hades grafana-server[1988]:         /usr/local/go/src/runtime/panic.go:774 +0x5c fp=0x295187c sp=0x2951868 pc=0x4555c
Jan 11 13:09:19 hades systemd[1]: grafana-server.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 11 13:09:19 hades systemd[1]: grafana-server.service: Unit entered failed state.
Jan 11 13:09:19 hades systemd[1]: grafana-server.service: Failed with result 'exit-code'.
Jan 11 13:09:19 hades systemd[1]: grafana-server.service: Service hold-off time over, scheduling restart.
Jan 11 13:09:19 hades systemd[1]: Stopped Grafana instance.
Jan 11 13:09:19 hades systemd[1]: Started Grafana instance.
Jan 11 13:09:19 hades grafana-server[1996]: runtime: nameOff 0xffffffffbd074000 out of range 0xe0da10 - 0x14ec82c
Jan 11 13:09:19 hades grafana-server[1996]: fatal error: runtime: name offset out of range
Jan 11 13:09:19 hades grafana-server[1996]: goroutine 1 [running, locked to thread]:
Jan 11 13:09:19 hades grafana-server[1996]: runtime.throw(0x11ae68d, 0x21)
Jan 11 13:09:19 hades systemd[1]: grafana-server.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 11 13:09:19 hades systemd[1]: grafana-server.service: Unit entered failed state.
Jan 11 13:09:19 hades systemd[1]: grafana-server.service: Failed with result 'exit-code'.
Jan 11 13:09:20 hades systemd[1]: grafana-server.service: Service hold-off time over, scheduling restart.
Jan 11 13:09:20 hades systemd[1]: Stopped Grafana instance.
Jan 11 13:09:20 hades systemd[1]: Started Grafana instance.
Jan 11 13:09:20 hades grafana-server[2004]: runtime: nameOff 0xffffffffbd074000 out of range 0xe0da10 - 0x14ec82c
Jan 11 13:09:20 hades grafana-server[2004]: fatal error: runtime: name offset out of range
Jan 11 13:09:20 hades grafana-server[2004]: goroutine 1 [running, locked to thread]:
Jan 11 13:09:20 hades grafana-server[2004]: runtime.throw(0x11ae68d, 0x21)
Jan 11 13:09:20 hades grafana-server[2004]:         /usr/local/go/src/runtime/panic.go:774 +0x5c fp=0x351387c sp=0x3513868 pc=0x4555c
Jan 11 13:09:20 hades systemd[1]: grafana-server.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

`/var/log/grafana/grafana.log` is not updated on start, probably meaning that it does not even get as far as opening the logfile. The last message in `grafana.log` is `lvl=error msg="Server shutdown" logger=server reason=nil`.

**What you expected to happen**:

Raspberry starts fine along with all its services. It used to work ten minutes ago. No changes were made to the grafana-server plugins or anything related.

**How to reproduce it (as minimally and precisely as possible)**:

`systemctl start grafana-server` continuously results in the same error.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5.2
- Data source type & version: default
- OS Grafana is installed on: raspberrypi armv7l
- User OS & Browser: raspbian stretch (9.11)
- Grafana plugins:
  - agenty-flowcharting-panel @ 0.6.0 
  - farski-blendstat-panel @ 1.0.2 
  - grafana-piechart-panel @ 1.3.9 
  - grafana-polystat-panel @ 1.0.16 
  - michaeldmoore-multistat-panel @ 1.2.5
- Others:

**Comment by dpsenner** [comment]
The following appears to have solved the symptom:

`apt install --reinstall grafana`

It is however totally unclear to me what caused the problem.
