### ISSUE TITLE
Unable to build custom plugin on ubuntu

### ISSUE THREAD

**Issue by WaleedNaveed** [grafana/grafana#21846]
I am developing a grafana plugin using react. I have used syncfusion library in my plugin. The plugin works fine on windows, but when i build it on ubuntu, i get the following error.

grafana-toolkit plugin:build

✔ Cleaning
✔ Preparing
✔ Prettier check
⠋ Linting

  Trace: TypeError: f.getRuleSeverity is not a function
      at /aedata/ae/grafana/plugins/simple-react-panel/node_modules/@grafana/toolkit/src/cli/tasks/plugin.build.js:179:44
      at Array.forEach (<anonymous>)
      at /aedata/ae/grafana/plugins/simple-react-panel/node_modules/@grafana/toolkit/src/cli/tasks/plugin.build.js:177:34
      at step (/aedata/ae/grafana/plugins/simple-react-panel/node_modules/tslib/tslib.js:136:27)
      at Object.next (/aedata/ae/grafana/plugins/simple-react-panel/node_modules/tslib/tslib.js:117:57)
      at fulfilled (/aedata/ae/grafana/plugins/simple-react-panel/node_modules/tslib/tslib.js:107:62)
      at /aedata/ae/grafana/plugins/simple-react-panel/node_modules/@grafana/toolkit/src/cli/utils/useSpinner.js:24:29
      at step (/aedata/ae/grafana/plugins/simple-react-panel/node_modules/tslib/tslib.js:136:27)
      at Object.throw (/aedata/ae/grafana/plugins/simple-react-panel/node_modules/tslib/tslib.js:117:57)
      at rejected (/aedata/ae/grafana/plugins/simple-react-panel/node_modules/tslib/tslib.js:108:69)
✖ f.getRuleSeverity is not a function
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! simple-react-panel@1.0.0 build: `grafana-toolkit plugin:build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the simple-react-panel@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-30T11_22_15_197Z-debug.log

**Comment by dprokop** [comment]
@WaleedNaveed thanks for reporting this. Actually, this issue was fixed yesterday with this PR https://github.com/grafana/grafana/pull/21849

We are about to release Grafana 6.6.1 next week. Until then, please use `canary` version of @grafana/toolkit. Sorry for troubles!
