### ISSUE TITLE
toFixed() digits argument must be between 0 and 20

### ISSUE THREAD

**Issue by ccutrer** [grafana/grafana#2189]
I have a single stat panel against influxdb 0.9.0. I'm getting a JS error:

RangeError: toFixed() digits argument must be between 0 and 20
    at Number.toFixed (native)
    at Object.d.roundValue (https://grafana/app/app.db6d039e.js:19:10613)
    at l.g.controller.a.setValues (https://grafana/app/app.db6d039e.js:38:998)
    at l.g.controller.a.render (https://grafana/app/app.db6d039e.js:38:550)
    at g.controller.a.dataHandler (https://grafana/app/app.db6d039e.js:37:31579)
    at i (https://grafana/app/app.db6d039e.js:11:29915)
    at https://grafana/app/app.db6d039e.js:11:30087
    at l.$eval (https://grafana/app/app.db6d039e.js:12:5255)
    at l.$digest (https://grafana/app/app.db6d039e.js:12:3773)
    at l.$apply (https://grafana/app/app.db6d039e.js:12:5511)

the metric is `SELECT sum(value) FROM "energy" WHERE circuit='solar' AND $timeFilter`. the unit is set to Wh (influx is returning a one point per hour). I get the error whenever my time filter is less than the last 24 hours.

I'm running 2.1.0-pre1, at commit a815511aef7768b0f0a22a9c27588f9fb9a70b45

**Comment by torkelo** [comment]
Is your influxdb data a number? can you print the response from InfluxDB?

**Comment by ccutrer** [comment]
```
{"results":[{"series":[{"name":"energy","columns":["time","sum"],"values":[["2015-06-18T17:00:22.080011278Z",null]]}]}]}
```

yes, it's null. what's weird is I can only reproduce for a last hour query now. must be something odd with lag on population of influx from my energy monitor. even given the query is returning null, I would expect the UI to show "NaN" or something, rather than give a javascript error

**Comment by ccutrer** [comment]
yes, confirmed that I had a few of the hour points missing (it populates every five minutes, with a 15 minute lookback; it must have missed the on-the-hour points; I adjusted those to have a 24 hour lookback). I still see the query error around-the-hour on a last-hour query when the last point has slipped out of the window, but the latest data isn't in yet.

**Comment by torkelo** [comment]
thanks for reporting this, the bug in singlestat panel (null value handling) is fixed
