### ISSUE TITLE
Error: Cannot find module 'rxjs-compat/Subject'

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#22241]
I'm trying to build latest master https://github.com/grafana/grafana/commit/a743a1cc129d2cd1756500b5931ea214ec2991b3 in docker container by running `make all`. However I'm getting 

```
01:54:28]	error /go/src/github.com/grafana/grafana/node_modules/cypress: Command failed.
[01:54:28]	Exit code: 1
[01:54:28]	Command: node index.js --exec install
[01:54:28]	Arguments: 
[01:54:28]	Directory: /go/src/github.com/grafana/grafana/node_modules/cypress
[01:54:28]	Output:
[01:54:28]	internal/modules/cjs/loader.js:983
[01:54:28]	  throw err;
[01:54:28]	  ^
[01:54:28]	
[01:54:28]	Error: Cannot find module 'rxjs-compat/Subject'
[01:54:28]	Require stack:
[01:54:28]	- /go/src/github.com/grafana/grafana/node_modules/rxjs/Subject.js
[01:54:28]	info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[01:54:28]	- /go/src/github.com/grafana/grafana/node_modules/cypress/node_modules/listr/lib/task.js
[01:54:28]	- /go/src/github.com/grafana/grafana/node_modules/cypress/node_modules/listr/index.js
[01:54:28]	- /go/src/github.com/grafana/grafana/node_modules/cypress/lib/tasks/install.js
[01:54:28]	- /go/src/github.com/grafana/grafana/node_modules/cypress/index.js
[01:54:28]	    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
[01:54:28]	    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
[01:54:28]	    at Module.require (internal/modules/cjs/loader.js:1040:19)
[01:54:28]	    at require (internal/modules/cjs/helpers.js:72:18)
[01:54:28]	    at Object.<anonymous> (/go/src/github.com/grafana/grafana/node_modules/rxjs/Subject.js:6:10)
[01:54:28]	    at Module._compile (internal/modules/cjs/loader.js:1151:30)
[01:54:28]	    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
[01:54:28]	    at Module.load (internal/modules/cjs/loader.js:1000:32)
[01:54:28]	    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
[01:54:28]	    at Module.require (internal/modules/cjs/loader.js:1040:19)
[01:54:28]	    at require (internal/modules/cjs/helpers.js:72:18)
[01:54:28]	    at Object.<anonymous> (/go/src/github.com/grafana/grafana/node_modules/cypress/node_modules/listr/lib/task.js:5:17)
[01:54:28]	    at Module._compile (internal/modules/cjs/loader.js:1151:30)
[01:54:28]	    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
[01:54:28]	    at Module.load (internal/modules/cjs/loader.js:1000:32)
[01:54:28]	    at Function.Module._load (internal/modules/cjs/loader.js:899:14) {
[01:54:28]	  code: 'MODULE_NOT_FOUND',
[01:54:28]	  requireStack: [
[01:54:28]	    '/go/src/github.com/grafana/grafana/node_modules/rxjs/Subject.js',
[01:54:28]	    '/go/src/github.com/grafana/grafana/node_modules/cypress/node_modules/listr/lib/task.js',
[01:54:28]	    '/go/src/github.com/grafana/grafana/node_modules/cypress/node_modules/listr/index.js',
[01:54:28]	    '/go/src/github.com/grafana/grafana/node_modules/cypress/lib/tasks/install.js',
[01:54:28]	    '/go/src/github.com/grafana/grafana/node_modules/cypress/index.js'
[01:54:28]	  ]
[01:54:28]	}
[01:56:15]	Makefile:25: recipe for target 'node_modules' failed
[01:56:15]	make: *** [node_modules] Error 1
```

any ideas? It comes from `listr` which is `cypress` dep but don't see why build passes on my macos and not debian then 🤔.

```sh
FROM golang:1.13-stretch

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        apt-transport-https \
        bzip2 \
        git \
        && \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    curl -sL https://deb.nodesource.com/setup_12.x | bash - && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        nodejs \
        yarn \
        && \
    rm -rf /var/lib/apt/lists/*
```

**Comment by papagian** [comment]
There is a Grafana build [container](https://github.com/grafana/grafana/blob/master/scripts/build/ci-build/Dockerfile).
Also you could find helpful [these](https://github.com/grafana/grafana/tree/master/scripts/build/ci-build#makefile-targets) Makefile targets.

**Comment by papagian** [comment]
I'm closing this since it's more a question rather than a bug. If you have additional questions or trouble building grafana, feel free to ask in the community [site](https://community.grafana.com/).
