### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by rohilbh** [grafana/grafana#2231]
Suddenly got this error. Goes away if I restrict the time period in the query.

Message:
			Cannot read property 'length' of undefined
		
Stack trace:
			TypeError: Cannot read property 'length' of undefined
    at http://metric0.dev.quantifind.com:3000/public/app/plugins/datasource/influxdb/influxSeries.js?bust=1435250607757:4:403
    at Function.Ya (http://metric0.dev.quantifind.com:3000/app/app.6e379bdb.js:8:18233)
    at b.c.getTimeSeries (http://metric0.dev.quantifind.com:3000/public/app/plugins/datasource/influxdb/influxSeries.js?bust=1435250607757:4:346)
    at i (http://metric0.dev.quantifind.com:3000/public/app/plugins/datasource/influxdb/datasource.js?bust=1435250607757:4:911)
    at b (http://metric0.dev.quantifind.com:3000/app/app.6e379bdb.js:8:10634)
    at i (http://metric0.dev.quantifind.com:3000/app/app.6e379bdb.js:10:29774)
    at http://metric0.dev.quantifind.com:3000/app/app.6e379bdb.js:10:29946
    at l.$eval (http://metric0.dev.quantifind.com:3000/app/app.6e379bdb.js:12:5068)
    at l.$digest (http://metric0.dev.quantifind.com:3000/app/app.6e379bdb.js:12:3586)
    at l.$apply (http://metric0.dev.quantifind.com:3000/app/app.6e379bdb.js:12:5324)

**Comment by torkelo** [comment]
what is the response from influxdb? Looks like InfluxDB is returning something unexpected in this case

**Comment by rohilbh** [comment]
Not sure how to view the response from influxdb but usually if I refresh the page a couple times, the error goes away but comes back after some time. If I restrict the query to data from the last few minutes for example, the error doesn't show up.

**Comment by torkelo** [comment]
Maybe, as I said check what response Influxdb is sending to grafana. You can do this in chrome dev tools network tab

**Comment by rohilbh** [comment]
Ah, my mistake. It was querying for data just before that data was put into the db, which caused an empty response from influx
