### ISSUE TITLE
Grafana 2.0.0 -> 2.1.0 panic during "DB Migration"

### ISSUE THREAD

**Issue by ecables** [grafana/grafana#2256]
Grafana 2.0.0 -> 2.1.0 upgrade attempt results in panic when attempting "DB Migration" with PG backend for dashboards & session state.

```
# ./grafana
2015/06/26 11:12:14 [I] Starting Grafana
2015/06/26 11:12:14 [I] Version: master, Commit: NA, Build date: 1969-12-31 16:00:00 -0800 PST
2015/06/26 11:12:14 [I] Configuration Info
Config files:
  [0]: /opt/go/src/github.com/grafana/grafana/conf/defaults.ini
Paths:
  home: /opt/go/src/github.com/grafana/grafana
  data: /opt/go/src/github.com/grafana/grafana
  logs: /opt/go/src/github.com/grafana/grafana

2015/06/26 11:12:14 [I] Database: postgres, ConnectionString: user=grafana password=pass123 host=dbserver1 port=5432 dbname=grafana_dashboards sslmode=disable
2015/06/26 11:12:14 [I] Migrator: Starting DB migration
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x7ea4ee]

goroutine 1 [running]:
gopkg.in/ini%2ev1.(*Section).GetKey(0x0, 0xbf07d0, 0x7, 0x0, 0x0, 0x0)
    /opt/twitch/go/src/gopkg.in/ini.v1/ini.go:484 +0x4e
gopkg.in/ini%2ev1.(*Section).Key(0x0, 0xbf07d0, 0x7, 0x0)
    /opt/twitch/go/src/gopkg.in/ini.v1/ini.go:502 +0x3c
github.com/grafana/grafana/pkg/services/search.Init()
    /opt/twitch/go/src/github.com/grafana/grafana/pkg/services/search/handlers.go:18 +0xad
main.main()
    /opt/twitch/go/src/github.com/grafana/grafana/main.go:56 +0xdb

goroutine 5 [select]:
github.com/grafana/grafana/pkg/log.(*Logger).StartLogger(0xc20802d740)
    /opt/twitch/go/src/github.com/grafana/grafana/pkg/log/log.go:223 +0x369
created by github.com/grafana/grafana/pkg/log.newLogger
    /opt/twitch/go/src/github.com/grafana/grafana/pkg/log/log.go:153 +0x13a

goroutine 6 [syscall]:
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
    /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 7 [chan receive]:
main.func·001()
    /opt/twitch/go/src/github.com/grafana/grafana/main.go:47 +0xed
created by main.main
    /opt/twitch/go/src/github.com/grafana/grafana/main.go:49 +0xc5

goroutine 8 [select]:
github.com/grafana/grafana/pkg/log.(*Logger).StartLogger(0xc20812ce00)
    /opt/twitch/go/src/github.com/grafana/grafana/pkg/log/log.go:223 +0x369
created by github.com/grafana/grafana/pkg/log.newLogger
    /opt/twitch/go/src/github.com/grafana/grafana/pkg/log/log.go:153 +0x13a

goroutine 9 [select]:
github.com/grafana/grafana/pkg/log.(*Logger).StartLogger(0xc20809a080)
    /opt/twitch/go/src/github.com/grafana/grafana/pkg/log/log.go:223 +0x369
created by github.com/grafana/grafana/pkg/log.newLogger
    /opt/twitch/go/src/github.com/grafana/grafana/pkg/log/log.go:153 +0x13a

goroutine 17 [chan receive]:
database/sql.(*DB).connectionOpener(0xc2080fe1e0)
    /usr/local/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
    /usr/local/go/src/database/sql/sql.go:452 +0x31c

goroutine 33 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
```

**Comment by torkelo** [comment]
The error did not have anything to do with postgres, 

you must have modified defaults.ini and removed section dashboards.json section. You should not modify this file, create a custom.ini instead and override the defaults. 

```
#################################### Dashboard JSON files ##########################
[dashboards.json]
enabled = false
path = /var/lib/grafana/dashboards
```
