### ISSUE TITLE
grafana-toolkit: yarn dev command fails with TypeError

### ISSUE THREAD

**Issue by xinau** [grafana/grafana#23084]
**What happened**:
after performing the mentioned steps in the documentation for creating a grafana panel plugin. I got repeatedly stuck at performing the `yarn dev` command.
```
yarn run v1.22.4
$ grafana-toolkit plugin:dev
⠋ Prettier check  Trace: TypeError: results.flat is not a function
      at /home/xinau/Projects/github.com/xinau/grafana-plugins/horizon-charts/node_modules/@grafana/toolkit/src/cli/tasks/plugin.build.js:76:124
      at process._tickCallback (internal/process/next_tick.js:68:7)
      at /home/xinau/Projects/github.com/xinau/grafana-plugins/horizon-charts/node_modules/@grafana/toolkit/src/cli/utils/useSpinner.js:24:29
      at step (/home/xinau/Projects/github.com/xinau/grafana-plugins/horizon-charts/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:136:27)
      at Object.throw (/home/xinau/Projects/github.com/xinau/grafana-plugins/horizon-charts/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:117:57)
      at rejected (/home/xinau/Projects/github.com/xinau/grafana-plugins/horizon-charts/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:108:69)
      at process._tickCallback (internal/process/next_tick.js:68:7)
✖ results.flat is not a function
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**What you expected to happen**:

It to work as described in the documentation.

**How to reproduce it (as minimally and precisely as possible)**:

```
npx @grafana/toolkit plugin:create my-grafana-plugin
cd my-grafana-plugin
yarn install
yarn dev
```
**Environment**:
- Others:
  - yarn  = 1.22.4
  - npm = 6.14.2
  - grafana/toolkit =  6.6.2

**Comment by ryantxu** [comment]
try with node 12 -- if that does not work... post again

**Comment by xinau** [comment]
@ryantxu thanks.
