### ISSUE TITLE
grafana-toolkit: Plugins need eslint-plugin-prettier

### ISSUE THREAD

**Issue by peterholmberg** [grafana/grafana#23137]
**What happened**:
Implementing grafana/toolkit in an existing plugin. Followed the guide [here](https://github.com/grafana/grafana/tree/master/packages/grafana-toolkit). When I ran `yarn dev` I got an error: 

```
$ grafana-toolkit plugin:dev
⠋ Linting  Trace: Error: Failed to load plugin 'prettier' declared in '--config » @grafana/eslint-config#overrides[0] » ./config-js.js': Cannot find module 'eslint-plugin-prettier'
  Require stack:
  - /home/pete/dev/git/grafana-plugins/strava-datasource/__placeholder__.js
  Referenced from: /home/pete/dev/git/grafana-plugins/strava-datasource/node_modules/@grafana/eslint-config/config-js.js
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
      at Function.resolve (internal/modules/cjs/helpers.js:80:19)
      at Object.resolve (/home/pete/dev/git/grafana-plugins/strava-datasource/node_modules/eslint/lib/shared/relative-module-resolver.js:44:50)
      at ConfigArrayFactory._loadPlugin (/home/pete/dev/git/grafana-plugins/strava-datasource/node_modules/eslint/lib/cli-engine/config-array-factory.js:957:39)
      at ConfigArrayFactory._loadExtendedPluginConfig (/home/pete/dev/git/grafana-plugins/strava-datasource/node_modules/eslint/lib/cli-engine/config-array-factory.js:777:29)
      at ConfigArrayFactory._loadExtends (/home/pete/dev/git/grafana-plugins/strava-datasource/node_modules/eslint/lib/cli-engine/config-array-factory.js:723:29)
      at ConfigArrayFactory._normalizeObjectConfigDataBody (/home/pete/dev/git/grafana-plugins/strava-datasource/node_modules/eslint/lib/cli-engine/config-array-factory.js:658:25)
      at _normalizeObjectConfigDataBody.next (<anonymous>)
      at ConfigArrayFactory._normalizeObjectConfigData (/home/pete/dev/git/grafana-plugins/strava-datasource/node_modules/eslint/lib/cli-engine/config-array-factory.js:594:20)
      at _normalizeObjectConfigData.next (<anonymous>)
      at ConfigArrayFactory._normalizeObjectConfigDataBody (/home/pete/dev/git/grafana-plugins/strava-datasource/node_modules/eslint/lib/cli-engine/config-array-factory.js:658:25)
      at _normalizeObjectConfigDataBody.next (<anonymous>)
      at ConfigArrayFactory._normalizeObjectConfigData (/home/pete/dev/git/grafana-plugins/strava-datasource/node_modules/eslint/lib/cli-engine/config-array-factory.js:594:20)
      at _normalizeObjectConfigData.next (<anonymous>)
      at ConfigArrayFactory._normalizeObjectConfigDataBody (/home/pete/dev/git/grafana-plugins/strava-datasource/node_modules/eslint/lib/cli-engine/config-array-factory.js:697:25)
      at _normalizeObjectConfigDataBody.next (<anonymous>) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      '/home/pete/dev/git/grafana-plugins/strava-datasource/__placeholder__.js'
    ],
    messageTemplate: 'plugin-missing',
    messageData: {
      pluginName: 'eslint-plugin-prettier',
      resolvePluginsRelativeTo: '/home/pete/dev/git/grafana-plugins/strava-datasource',
      importerName: '--config » @grafana/eslint-config#overrides[0] » ./config-js.js'
    }
  }
      at /home/pete/dev/git/grafana-plugins/strava-datasource/node_modules/@grafana/toolkit/src/cli/utils/useSpinner.js:24:29
      at step (/home/pete/dev/git/grafana-plugins/strava-datasource/node_modules/tslib/tslib.js:136:27)
      at Object.throw (/home/pete/dev/git/grafana-plugins/strava-datasource/node_modules/tslib/tslib.js:117:57)
      at rejected (/home/pete/dev/git/grafana-plugins/strava-datasource/node_modules/tslib/tslib.js:108:69)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
✖ Failed to load plugin 'prettier' declared in '--config » @grafana/eslint-config#overrides[0] » ./config-js.js': Cannot find module 'eslint-plugin-prettier'
Require stack:
- /home/pete/dev/git/grafana-plugins/strava-datasource/__placeholder__.js
Referenced from: /home/pete/dev/git/grafana-plugins/strava-datasource/node_modules/@grafana/eslint-config/config-js.js
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**What you expected to happen**:
Expected the plugin to build, the docs did not mention a requirement for the plugin stated above. I guess the easy solution here is to add a step to the installation docs.

**Comment by gupta-tarun** [comment]
Facing the same issue, any workaround ??

**Comment by oddlittlebird** [comment]
@marcusolsson, pertinent to your interests.

**Comment by ryantxu** [comment]
This was fixed before 7x -- if it is still a problem, can you open a new issue?
