### ISSUE TITLE
Regression: OpenTSDB tag globbing broken

### ISSUE THREAD

**Issue by pdf** [grafana/grafana#2315]
The latest nightly (06/07/2015, 23:09:37) appears to have broken OpenTSDB tag globbing, ie - tag values like `host1|host2` or `host*` now result in the UI throwing:

```
TypeError: Cannot read property 'alias' of undefined
    at i (https://grafana.0xc0dedbad.com/public/app/plugins/datasource/opentsdb/datasource.js?bust=1436414943375:4:502)
    at h (https://grafana.0xc0dedbad.com/public/app/plugins/datasource/opentsdb/datasource.js?bust=1436414943375:4:384)
    at https://grafana.0xc0dedbad.com/public/app/plugins/datasource/opentsdb/datasource.js?bust=1436414943375:4:2177
    at Function._a (https://grafana.0xc0dedbad.com/app/app.fa0bedbb.js:9:19182)
    at https://grafana.0xc0dedbad.com/public/app/plugins/datasource/opentsdb/datasource.js?bust=1436414943375:4:2138
    at i (https://grafana.0xc0dedbad.com/app/app.fa0bedbb.js:12:3146)
    at https://grafana.0xc0dedbad.com/app/app.fa0bedbb.js:12:3318
    at n.$eval (https://grafana.0xc0dedbad.com/app/app.fa0bedbb.js:12:10922)
    at n.$digest (https://grafana.0xc0dedbad.com/app/app.fa0bedbb.js:12:9353)
    at n.$apply (https://grafana.0xc0dedbad.com/app/app.fa0bedbb.js:12:11189)
```

**Comment by pdf** [comment]
Awesome turn-around, thanks.
