### ISSUE TITLE
DataSource typing regression with Observables

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#23377]
Something changed between 6.7.1 and 6.7.2 (and continues on master) that is breaking plugin imports.  When compiling against 6.7.2+ all DataSource implementations fail because of a mismatch in the Observable interface:

The main difference is:
```
    Type 'import("/home/ryan/workspace/grafana/plugins/google-sheets-datasource/node_modules/rxjs/internal/Observable")                           .Observable<import("/home/ryan/workspace/grafana/plugins/google-sheets-datasource/node_modules/@grafana/data/types/datasource").DataQueryResponse>'
 to type 'import("/home/ryan/workspace/grafana/plugins/google-sheets-datasource/node_modules/@grafana/data/node_modules/rxjs/internal/Observable").Observable<import("/home/ryan/workspace/grafana/plugins/google-sheets-datasource/node_modules/@grafana/data/types/datasource").DataQueryResponse>'.
```

See https://github.com/grafana/google-sheets-datasource/issues/73

The full errors look like:
```
[@grafana/ui] external "@grafana/ui" 42 bytes {module} [built]
  [lodash] external "lodash" 42 bytes {module} [built]
      + 13 hidden modules

  ERROR in /home/ryan/workspace/grafana/plugins/google-sheets-datasource/src/module.ts
  ./module.ts
  [tsl] ERROR in /home/ryan/workspace/grafana/plugins/google-sheets-datasource/src/module.ts(6,44)
        TS2344: Type 'DataSource' does not satisfy the constraint 'DataSourceApi<SheetsQuery, SheetsSourceOptions>'.
    The types returned by 'query(...)' are incompatible between these types.
      Type 'Observable<DataQueryResponse>' is not assignable to type 'Promise<DataQueryResponse> | Observable<DataQueryResponse>'.
        Type 'import("/home/ryan/workspace/grafana/plugins/google-sheets-datasource/node_modules/rxjs/internal/Observable").Observable<import("/home/ryan/workspace/grafana/plugins/google-sheets-datasource/node_modules/@grafana/data/types/datasource").DataQueryResponse>' is not assignable to type 'import("/home/ryan/workspace/grafana/plugins/google-sheets-datasource/node_modules/@grafana/data/node_modules/rxjs/internal/Observable").Observable<import("/home/ryan/workspace/grafana/plugins/google-sheets-datasource/node_modules/@grafana/data/types/datasource").DataQueryResponse>'.

  ERROR in /home/ryan/workspace/grafana/plugins/google-sheets-datasource/src/components/QueryEditor.tsx
  ./components/QueryEditor.tsx
  [tsl] ERROR in /home/ryan/workspace/grafana/plugins/google-sheets-datasource/src/components/QueryEditor.tsx(7,31)
        TS2344: Type 'DataSource' does not satisfy the constraint 'DataSourceApi<SheetsQuery, SheetsSourceOptions>'.
    The types returned by 'query(...)' are incompatible between these types.
      Type 'Observable<DataQueryResponse>' is not assignable to type 'Promise<DataQueryResponse> | Observable<DataQueryResponse>'.
        Type 'import("/home/ryan/workspace/grafana/plugins/google-sheets-datasource/node_modules/rxjs/internal/Observable").Observable<import("/home/ryan/workspace/grafana/plugins/google-sheets-datasource/node_modules/@grafana/data/types/datasource").DataQueryResponse>' is not assignable to type 'import("/home/ryan/workspace/grafana/plugins/google-sheets-datasource/node_modules/@grafana/data/node_modules/rxjs/internal/Observable").Observable<import("/home/ryan/workspace/grafana/plugins/google-sheets-datasource/node_modules/@grafana/data/types/datasource").DataQueryResponse>'.
          The types of 'source.operator.call' are incompatible between these types.
            Type '(subscriber: import("/home/ryan/workspace/grafana/plugins/google-sheets-datasource/node_modules/rxjs/internal/Subscriber").Subscriber<any>, source: any) => import("/home/ryan/workspace/grafana/plugins/google-sheets-datasource/node_modules/rxjs/internal/types").TeardownLogic' is not assignable to type '(subscriber: import("/home/ryan/workspace/grafana/plugins/google-sheets-datasource/node_modules/@grafana/data/node_modules/rxjs/internal/Subscriber").Subscriber<any>, source: any) => import("/home/ryan/workspace/grafana/plugins/google-sheets-datasource/node_modules/@grafana/data/node_modules/rxjs/internal/types").Te...'.
              Types of parameters 'subscriber' and 'subscriber' are incompatible.
                Type 'import("/home/ryan/workspace/grafana/plugins/google-sheets-datasource/node_modules/@grafana/data/node_modules/rxjs/internal/Subscriber").Subscriber<any>' is not assignable to type 'import("/home/ryan/workspace/grafana/plugins/google-sheets-datasource/node_modules/rxjs/internal/Subscriber").Subscriber<any>'.
                  Property 'isStopped' is protected but type 'Subscriber<T>' is not a class derived from 'Subscriber<T>'.

  ERROR in /home/ryan/workspace/grafana/plugins/google-sheets-datasource/src/components/QueryEditor.tsx
  ./components/QueryEditor.tsx
  [tsl] ERROR in /home/ryan/workspace/grafana/plugins/google-sheets-datasource/src/components/QueryEditor.tsx(116,13)
        TS2322: Type '{ style: { marginTop: number; }; disabled: boolean; variant: "link"; icon: string; href: string; target: string; }' is not assignable to type 'IntrinsicAttributes & CommonProps & AnchorHTMLAttributes<HTMLAnchorElement> & RefAttributes<HTMLAnchorElement>'.
    Property 'disabled' does not exist on type 'IntrinsicAttributes & CommonProps & AnchorHTMLAttributes<HTMLAnchorElement> & RefAttributes<HTMLAnchorElement>'.

  ERROR in /home/ryan/workspace/grafana/plugins/google-sheets-datasource/src/components/MetaInspector.tsx
  ./components/MetaInspector.tsx
  [tsl] ERROR in /home/ryan/workspace/grafana/plugins/google-sheets-datasource/src/components/MetaInspector.tsx(6,44)
        TS2344: Type 'DataSource' does not satisfy the constraint 'DataSourceApi<SheetsQuery, SheetsSourceOptions>'.

  Trace: Build failed
      at /home/ryan/workspace/grafana/plugins/google-sheets-datasource/node_modules/@grafana/toolkit/src/cli/utils/useSpinner.js:24:29
      at step (/home/ryan/workspace/grafana/plugins/google-sheets-datasource/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:136:27)
      at Object.throw (/home/ryan/workspace/grafana/plugins/google-sheets-datasource/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:117:57)
      at rejected (/home/ryan/workspace/grafana/plugins/google-sheets-datasource/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:108:69)
      at processTicksAndRejections (internal/process/task_queues.js:94:5)
✖ Build failed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by ryantxu** [comment]
I think this is an issue with rxjs 6.5.5 -- if I manually change the `yarn.lock` to avoid the 6.5.5 file it work.  When the following changes happen everything breaks:

![image](https://user-images.githubusercontent.com/705951/78619188-6ddaae00-7831-11ea-938a-9e500e84ce33.png)

**Comment by torkelo** [comment]
Is there anything we can do here? Is there a mismatch between toolkit & data package with verison in lock file?
