### ISSUE TITLE
重新编译时出现错误yarn start

### ISSUE THREAD

**Issue by hl0709** [grafana/grafana#23725]
yarn run v1.22.4
$ webpack --mode production --config scripts/webpack/webpack.prod.js --profile --json > compilation-stats.json
D:\go\grafana-master\node_modules\terser-webpack-plugin\dist\index.js:375
    const optimizeFn = async (compilation, chunks) => {
                             ^

SyntaxError: Unexpected token (
    at NativeCompileCache._moduleCompile (D:\go\grafana-master\node_modules\v8-compile-cache\v8-compile-cache.js:240:18)
    at Module._compile (D:\go\grafana-master\node_modules\v8-compile-cache\v8-compile-cache.js:186:36)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (D:\go\grafana-master\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (D:\go\grafana-master\node_modules\terser-webpack-plugin\dist\cjs.js:3:16)
    at Module._compile (D:\go\grafana-master\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (D:\go\grafana-master\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (D:\go\grafana-master\scripts\webpack\webpack.prod.js:4:22)
    at Module._compile (D:\go\grafana-master\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (D:\go\grafana-master\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (D:\go\grafana-master\node_modules\webpack-cli\bin\utils\convert-argv.js:114:13)
    at requireConfig (D:\go\grafana-master\node_modules\webpack-cli\bin\utils\convert-argv.js:116:6)
    at D:\go\grafana-master\node_modules\webpack-cli\bin\utils\convert-argv.js:123:17
    at Array.forEach (native)
    at module.exports (D:\go\grafana-master\node_modules\webpack-cli\bin\utils\convert-argv.js:121:15)
    at yargs.parse.err (D:\go\grafana-master\node_modules\webpack-cli\bin\cli.js:71:45)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
Please fill in Grafana version and/or branch you're using together with Node version and what command you're trying to run.
