### ISSUE TITLE
panic: Invalid DSN: Missing the slash separating the database name

### ISSUE THREAD

**Issue by Janhouse** [grafana/grafana#2400]
This happens after installing Grafana from provided Debian/Ubuntu repository.
It shows the same message also when using MySQL even if DSN is correct. (And it (or init script?) actually created tables in that database.)

I tried installing Grafana from stable and test repos. Same problem.

```
2015/07/26 18:38:36 [I] Starting Grafana
2015/07/26 18:38:36 [I] Version: 2.0.2, Commit: v2.0.2, Build date: 2015-04-22 17:51:50 +0200 CEST
2015/07/26 18:38:36 [I] Configuration Info
Config files:
  [0]: /usr/share/grafana/conf/defaults.ini
  [1]: /etc/grafana/grafana.ini
Command lines overrides:
  [0]: default.paths.data=/var/lib/grafana
  [1]: default.paths.logs=/var/log/grafana
Paths:
  home: /usr/share/grafana
  data: /var/lib/grafana
  logs: /var/log/grafana

2015/07/26 18:38:36 [I] Database: sqlite3, ConnectionString: file:/var/lib/grafana/grafana.db?cache=shared&mode=rwc&_loc=Local
2015/07/26 18:38:36 [I] Migrator: Starting DB migration
panic: Invalid DSN: Missing the slash separating the database name

goroutine 1 [running]:
github.com/grafana/grafana/pkg/middleware.Sessioner(0xc20812ae50, 0x5, 0xc20812ae98, 0x8, 0xc20812aef0, 0xc, 0xbb11b0, 0x1, 0x15180, 0x15180, ...)
	/go/src/github.com/grafana/grafana/pkg/middleware/session.go:31 +0x16f
github.com/grafana/grafana/pkg/cmd.newMacaron(0x0)
	/go/src/github.com/grafana/grafana/pkg/cmd/web.go:44 +0x4ab
github.com/grafana/grafana/pkg/cmd.StartServer()
	/go/src/github.com/grafana/grafana/pkg/cmd/web.go:73 +0x3c
main.main()
	/go/src/github.com/grafana/grafana/main.go:62 +0xfc

goroutine 5 [select]:
github.com/grafana/grafana/pkg/log.(*Logger).StartLogger(0xc20802d5c0)
	/go/src/github.com/grafana/grafana/pkg/log/log.go:223 +0x369
created by github.com/grafana/grafana/pkg/log.newLogger
	/go/src/github.com/grafana/grafana/pkg/log/log.go:153 +0x13a

goroutine 6 [syscall]:
os/signal.loop()
	/usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/src/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 7 [chan receive]:
main.func·001()
	/go/src/github.com/grafana/grafana/main.go:45 +0xed
created by main.main
	/go/src/github.com/grafana/grafana/main.go:47 +0xbd

goroutine 8 [select]:
github.com/grafana/grafana/pkg/log.(*Logger).StartLogger(0xc20808a000)
	/go/src/github.com/grafana/grafana/pkg/log/log.go:223 +0x369
created by github.com/grafana/grafana/pkg/log.newLogger
	/go/src/github.com/grafana/grafana/pkg/log/log.go:153 +0x13a

goroutine 9 [select]:
github.com/grafana/grafana/pkg/log.(*Logger).StartLogger(0xc20808a140)
	/go/src/github.com/grafana/grafana/pkg/log/log.go:223 +0x369
created by github.com/grafana/grafana/pkg/log.newLogger
	/go/src/github.com/grafana/grafana/pkg/log/log.go:153 +0x13a

goroutine 17 [chan receive]:
database/sql.(*DB).connectionOpener(0xc20808c320)
	/usr/src/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
	/usr/src/go/src/database/sql/sql.go:452 +0x31c

goroutine 33 [syscall, locked to thread]:
runtime.goexit()
	/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 10 [chan receive]:
github.com/grafana/grafana/pkg/metrics.StartUsageReportLoop(0x1198b90)
	/go/src/github.com/grafana/grafana/pkg/metrics/report_usage.go:22 +0x8c
created by main.main
	/go/src/github.com/grafana/grafana/main.go:59 +0xf5

goroutine 34 [chan receive]:
database/sql.(*DB).connectionOpener(0xc2080f4000)
	/usr/src/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
	/usr/src/go/src/database/sql/sql.go:452 +0x31c
```

**Comment by torkelo** [comment]
is this with default config what does your config look like? No one has reported this for Grafana 2.0.2 so it is most likely a config issue :)

**Comment by Janhouse** [comment]
I made new LXC container, installed Grafana and started it without messing with the config (but the init script did display that it failed to start).
Then I changed only database config to use mysql. It did show that it failed to start but it did start and create all the necessary tables in the database.

Then I started tweaking other config values and now after restarting it it launches just fine and the init script doesn't show failure message.

So I'll go enjoying the new Grafana version but there certainly seems to be something weird going on with the init script. :)

**Comment by torkelo** [comment]
The init script reporting failed on first start when using mysql is due to it takes time the first time to run the mysql db migration, this is fixed in the init script in master and the coming release

**Comment by szibis** [comment]
Same issue on latest build Version: 2.2.0-pre1, Commit: v2.1.2+183-gd56e778, Build date: 2015-09-02 09:32:49 +0000 UTC

is this fixed in latest builds ?

**Comment by szibis** [comment]
```bash
2015/09/03 08:29:53 [I] Starting Grafana
2015/09/03 08:29:53 [I] Version: 2.2.0-pre1, Commit: v2.1.2+183-gd56e778, Build date: 2015-09-02 09:32:49 +0000 UTC
2015/09/03 08:29:53 [I] Configuration Info
Config files:
  [0]: /usr/share/grafana/conf/defaults.ini
  [1]: /etc/grafana/grafana.ini
Paths:
  home: /usr/share/grafana
  data: /usr/share/grafana/data
  logs: /var/log/grafana

2015/09/03 08:29:53 [I] Database: mysql
2015/09/03 08:29:53 [I] Migrator: Starting DB migration
2015/09/03 08:29:53 [I] Migrator: exec migration id: create migration_log table
2015/09/03 08:29:53 [I] Migrator: exec migration id: create user table
2015/09/03 08:29:53 [I] Migrator: exec migration id: add unique index user.login
2015/09/03 08:29:53 [I] Migrator: exec migration id: add unique index user.email
2015/09/03 08:29:53 [I] Migrator: exec migration id: drop index UQE_user_login - v1
2015/09/03 08:29:53 [I] Migrator: exec migration id: drop index UQE_user_email - v1
2015/09/03 08:29:53 [I] Migrator: exec migration id: Rename table user to user_v1 - v1
2015/09/03 08:29:53 [I] Migrator: exec migration id: create user table v2
2015/09/03 08:29:54 [I] Migrator: exec migration id: create index UQE_user_login - v2
2015/09/03 08:29:54 [I] Migrator: exec migration id: create index UQE_user_email - v2
2015/09/03 08:29:54 [I] Migrator: exec migration id: copy data_source v1 to v2
2015/09/03 08:29:54 [I] Migrator: exec migration id: Drop old table user_v1
2015/09/03 08:29:54 [I] Migrator: exec migration id: create temp user table v1-7
2015/09/03 08:29:54 [I] Migrator: exec migration id: create index IDX_temp_user_email - v1-7
2015/09/03 08:29:54 [I] Migrator: exec migration id: create index IDX_temp_user_org_id - v1-7
2015/09/03 08:29:54 [I] Migrator: exec migration id: create index IDX_temp_user_code - v1-7
2015/09/03 08:29:54 [I] Migrator: exec migration id: create index IDX_temp_user_status - v1-7
2015/09/03 08:29:54 [I] Migrator: exec migration id: create star table
2015/09/03 08:29:54 [I] Migrator: exec migration id: add unique index star.user_id_dashboard_id
2015/09/03 08:29:54 [I] Migrator: exec migration id: create org table v1
2015/09/03 08:29:54 [I] Migrator: exec migration id: create index UQE_org_name - v1
2015/09/03 08:29:54 [I] Migrator: exec migration id: create org_user table v1
2015/09/03 08:29:54 [I] Migrator: exec migration id: create index IDX_org_user_org_id - v1
2015/09/03 08:29:54 [I] Migrator: exec migration id: create index UQE_org_user_org_id_user_id - v1
2015/09/03 08:29:55 [I] Migrator: exec migration id: copy data account to org
2015/09/03 08:29:55 [I] Migrator: skipping migration id: copy data account to org, condition not fulfilled
2015/09/03 08:29:55 [I] Migrator: exec migration id: copy data account_user to org_user
2015/09/03 08:29:55 [I] Migrator: skipping migration id: copy data account_user to org_user, condition not fulfilled
2015/09/03 08:29:55 [I] Migrator: exec migration id: Drop old table account
2015/09/03 08:29:55 [I] Migrator: exec migration id: Drop old table account_user
2015/09/03 08:29:55 [I] Migrator: exec migration id: create dashboard table
2015/09/03 08:29:55 [I] Migrator: exec migration id: add index dashboard.account_id
2015/09/03 08:29:55 [I] Migrator: exec migration id: add unique index dashboard_account_id_slug
2015/09/03 08:29:55 [I] Migrator: exec migration id: create dashboard_tag table
2015/09/03 08:29:55 [I] Migrator: exec migration id: add unique index dashboard_tag.dasboard_id_term
2015/09/03 08:29:55 [I] Migrator: exec migration id: drop index UQE_dashboard_tag_dashboard_id_term - v1
2015/09/03 08:29:55 [I] Migrator: exec migration id: Rename table dashboard to dashboard_v1 - v1
2015/09/03 08:29:55 [I] Migrator: exec migration id: create dashboard v2
2015/09/03 08:29:55 [I] Migrator: exec migration id: create index IDX_dashboard_org_id - v2
2015/09/03 08:29:55 [I] Migrator: exec migration id: create index UQE_dashboard_org_id_slug - v2
2015/09/03 08:29:55 [I] Migrator: exec migration id: copy dashboard v1 to v2
2015/09/03 08:29:55 [I] Migrator: exec migration id: drop table dashboard_v1
2015/09/03 08:29:55 [I] Migrator: exec migration id: alter dashboard.data to mediumtext v1
2015/09/03 08:29:56 [I] Migrator: exec migration id: create data_source table
2015/09/03 08:29:56 [I] Migrator: exec migration id: add index data_source.account_id
2015/09/03 08:29:56 [I] Migrator: exec migration id: add unique index data_source.account_id_name
2015/09/03 08:29:56 [I] Migrator: exec migration id: drop index IDX_data_source_account_id - v1
2015/09/03 08:29:56 [I] Migrator: exec migration id: drop index UQE_data_source_account_id_name - v1
2015/09/03 08:29:56 [I] Migrator: exec migration id: Rename table data_source to data_source_v1 - v1
2015/09/03 08:29:56 [I] Migrator: exec migration id: create data_source table v2
2015/09/03 08:29:56 [I] Migrator: exec migration id: create index IDX_data_source_org_id - v2
2015/09/03 08:29:56 [I] Migrator: exec migration id: create index UQE_data_source_org_id_name - v2
2015/09/03 08:29:56 [I] Migrator: exec migration id: copy data_source v1 to v2
2015/09/03 08:29:56 [I] Migrator: exec migration id: Drop old table data_source_v1 #2
2015/09/03 08:29:56 [I] Migrator: exec migration id: create api_key table
2015/09/03 08:29:56 [I] Migrator: exec migration id: add index api_key.account_id
2015/09/03 08:29:57 [I] Migrator: exec migration id: add index api_key.key
2015/09/03 08:29:57 [I] Migrator: exec migration id: add index api_key.account_id_name
2015/09/03 08:29:57 [I] Migrator: exec migration id: drop index IDX_api_key_account_id - v1
2015/09/03 08:29:57 [I] Migrator: exec migration id: drop index UQE_api_key_key - v1
2015/09/03 08:29:57 [I] Migrator: exec migration id: drop index UQE_api_key_account_id_name - v1
2015/09/03 08:29:57 [I] Migrator: exec migration id: Rename table api_key to api_key_v1 - v1
2015/09/03 08:29:57 [I] Migrator: exec migration id: create api_key table v2
2015/09/03 08:29:57 [I] Migrator: exec migration id: create index IDX_api_key_org_id - v2
2015/09/03 08:29:57 [I] Migrator: exec migration id: create index UQE_api_key_key - v2
2015/09/03 08:29:57 [I] Migrator: exec migration id: create index UQE_api_key_org_id_name - v2
2015/09/03 08:29:57 [I] Migrator: exec migration id: copy api_key v1 to v2
2015/09/03 08:29:57 [I] Migrator: exec migration id: Drop old table api_key_v1
2015/09/03 08:29:57 [I] Migrator: exec migration id: create dashboard_snapshot table v4
2015/09/03 08:29:57 [I] Migrator: exec migration id: drop table dashboard_snapshot_v4 #1
2015/09/03 08:29:57 [I] Migrator: exec migration id: create dashboard_snapshot table v5 #2
2015/09/03 08:29:57 [I] Migrator: exec migration id: create index UQE_dashboard_snapshot_key - v5
2015/09/03 08:29:57 [I] Migrator: exec migration id: create index UQE_dashboard_snapshot_delete_key - v5
2015/09/03 08:29:57 [I] Migrator: exec migration id: create index IDX_dashboard_snapshot_user_id - v5
2015/09/03 08:29:57 [I] Migrator: exec migration id: alter dashboard_snapshot to mediumtext v2
2015/09/03 08:29:58 [I] Created default admin user: admin
panic: Invalid DSN: Missing the slash separating the database name

goroutine 1 [running]:
github.com/grafana/grafana/pkg/middleware.Sessioner(0x1261720, 0x0, 0x0)
	/go/src/github.com/grafana/grafana/pkg/middleware/session.go:60 +0x15b
github.com/grafana/grafana/pkg/cmd.newMacaron(0x0)
	/go/src/github.com/grafana/grafana/pkg/cmd/web.go:49 +0x4bf
github.com/grafana/grafana/pkg/cmd.StartServer()
	/go/src/github.com/grafana/grafana/pkg/cmd/web.go:78 +0x3c
main.main()
	/go/src/github.com/grafana/grafana/main.go:67 +0x1f7

goroutine 6 [syscall]:
os/signal.loop()
	/usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/src/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 7 [select]:
main.listenToSystemSignels()
	/go/src/github.com/grafana/grafana/main.go:112 +0x4dd
created by main.main
	/go/src/github.com/grafana/grafana/main.go:47 +0xc5

goroutine 15 [chan receive]:
github.com/grafana/grafana/pkg/metrics.StartUsageReportLoop(0x0)
	/go/src/github.com/grafana/grafana/pkg/metrics/report_usage.go:22 +0x8c
created by main.main
	/go/src/github.com/grafana/grafana/main.go:64 +0x1f0

goroutine 10 [select]:
github.com/grafana/grafana/pkg/log.(*Logger).StartLogger(0xc20800b600)
	/go/src/github.com/grafana/grafana/pkg/log/log.go:227 +0x369
created by github.com/grafana/grafana/pkg/log.newLogger
	/go/src/github.com/grafana/grafana/pkg/log/log.go:157 +0x13a

goroutine 11 [select]:
github.com/grafana/grafana/pkg/log.(*Logger).StartLogger(0xc20800b6c0)
	/go/src/github.com/grafana/grafana/pkg/log/log.go:227 +0x369
created by github.com/grafana/grafana/pkg/log.newLogger
	/go/src/github.com/grafana/grafana/pkg/log/log.go:157 +0x13a

goroutine 12 [chan receive]:
database/sql.(*DB).connectionOpener(0xc208186f00)
	/usr/src/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
	/usr/src/go/src/database/sql/sql.go:452 +0x31c

goroutine 17 [chan receive]:
github.com/grafana/grafana/pkg/services/notifications.processMailQueue()
	/go/src/github.com/grafana/grafana/pkg/services/notifications/mailer.go:30 +0x69
created by github.com/grafana/grafana/pkg/services/notifications.initMailQueue
	/go/src/github.com/grafana/grafana/pkg/services/notifications/mailer.go:24 +0x5c

goroutine 51 [runnable]:
text/template/parse.lexText(0xc208046880, 0xddd978)
	/usr/src/go/src/text/template/parse/lex.go:228 +0x37b
text/template/parse.(*lexer).run(0xc208046880)
	/usr/src/go/src/text/template/parse/lex.go:198 +0x5d
created by text/template/parse.lex
	/usr/src/go/src/text/template/parse/lex.go:191 +0x1ac

goroutine 65 [runnable]:
database/sql.(*DB).connectionOpener(0xc208108000)
	/usr/src/go/src/database/sql/sql.go:588
created by database/sql.Open
	/usr/src/go/src/database/sql/sql.go:452 +0x31c
```
After second init start:

```bash
2015/09/03 08:30:30 [I] Starting Grafana
2015/09/03 08:30:30 [I] Version: 2.2.0-pre1, Commit: v2.1.2+183-gd56e778, Build date: 2015-09-02 09:32:49 +0000 UTC
2015/09/03 08:30:30 [I] Configuration Info
Config files:
  [0]: /usr/share/grafana/conf/defaults.ini
  [1]: /etc/grafana/grafana.ini
Paths:
  home: /usr/share/grafana
  data: /usr/share/grafana/data
  logs: /var/log/grafana

2015/09/03 08:30:30 [I] Database: mysql
2015/09/03 08:30:30 [I] Migrator: Starting DB migration
panic: Invalid DSN: Missing the slash separating the database name

goroutine 1 [running]:
github.com/grafana/grafana/pkg/middleware.Sessioner(0x1261720, 0x0, 0x0)
	/go/src/github.com/grafana/grafana/pkg/middleware/session.go:60 +0x15b
github.com/grafana/grafana/pkg/cmd.newMacaron(0x0)
	/go/src/github.com/grafana/grafana/pkg/cmd/web.go:49 +0x4bf
github.com/grafana/grafana/pkg/cmd.StartServer()
	/go/src/github.com/grafana/grafana/pkg/cmd/web.go:78 +0x3c
main.main()
	/go/src/github.com/grafana/grafana/main.go:67 +0x1f7

goroutine 6 [syscall]:
os/signal.loop()
	/usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/src/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 7 [select]:
main.listenToSystemSignels()
	/go/src/github.com/grafana/grafana/main.go:112 +0x4dd
created by main.main
	/go/src/github.com/grafana/grafana/main.go:47 +0xc5

goroutine 10 [select]:
github.com/grafana/grafana/pkg/log.(*Logger).StartLogger(0xc2081005c0)
	/go/src/github.com/grafana/grafana/pkg/log/log.go:227 +0x369
created by github.com/grafana/grafana/pkg/log.newLogger
	/go/src/github.com/grafana/grafana/pkg/log/log.go:157 +0x13a

goroutine 11 [select]:
github.com/grafana/grafana/pkg/log.(*Logger).StartLogger(0xc208100600)
	/go/src/github.com/grafana/grafana/pkg/log/log.go:227 +0x369
created by github.com/grafana/grafana/pkg/log.newLogger
	/go/src/github.com/grafana/grafana/pkg/log/log.go:157 +0x13a

goroutine 12 [chan receive]:
database/sql.(*DB).connectionOpener(0xc208181d60)
	/usr/src/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
	/usr/src/go/src/database/sql/sql.go:452 +0x31c

goroutine 13 [chan receive]:
github.com/grafana/grafana/pkg/services/notifications.processMailQueue()
	/go/src/github.com/grafana/grafana/pkg/services/notifications/mailer.go:30 +0x69
created by github.com/grafana/grafana/pkg/services/notifications.initMailQueue
	/go/src/github.com/grafana/grafana/pkg/services/notifications/mailer.go:24 +0x5c

goroutine 33 [chan receive]:
github.com/grafana/grafana/pkg/metrics.StartUsageReportLoop(0x0)
	/go/src/github.com/grafana/grafana/pkg/metrics/report_usage.go:22 +0x8c
created by main.main
	/go/src/github.com/grafana/grafana/main.go:64 +0x1f0

goroutine 36 [runnable]:
database/sql.(*DB).connectionOpener(0xc2080f6280)
	/usr/src/go/src/database/sql/sql.go:588
created by database/sql.Open
	/usr/src/go/src/database/sql/sql.go:452 +0x31c
```

**Comment by szibis** [comment]
My config file (passwords and domains removed):

```ini
##################### Grafana Configuration Defaults #####################
#
# Do not modify this file in grafana installs
#

app_mode = production

#################################### Paths ####################################
[paths]
# Path to where grafana can store temp files, sessions, and the sqlite3 db (if that is used)
#
data = data
#
# Directory where grafana can store logs
#
logs = /var/log/grafana

#################################### Server ####################################
[server]
# Protocol (http or https)
protocol = http

# The ip address to bind to, empty will bind to all interfaces
http_addr = 127.0.0.1

# The http port  to use
http_port = 3000

# The public facing domain name used to access grafana from a browser
domain = grafana.example.com

# Redirect to correct domain if host header does not match domain
# Prevents DNS rebinding attacks
enforce_domain = true

# The full public facing url
root_url = %(protocol)s://%(domain)s:%(http_port)s/

# Log web requests
router_logging = true

# the path relative working path
static_root_path = public

# enable gzip
enable_gzip = true

# https certs & key file
cert_file = 
cert_key = 

#################################### Database ####################################
[database]
# Either "mysql", "postgres" or "sqlite3", it's your choice
type = mysql
host = 10.1.3.1:3306
name = grafana
user = grafana
password = xxxxxxxxxx

# For "postgres" only, either "disable", "require" or "verify-full"
ssl_mode = disable

# For "sqlite3" only, path relative to data_path setting
# path = grafana.db

#################################### Session ####################################
[session]
# Either "memory", "file", "redis", "mysql", "postgresql", default is "file"
provider = mysql

# Provider config options
# memory: not have any config yet
# file: session dir path, is relative to grafana data_path
# redis: config like redis server e.g. `addr=127.0.0.1:6379,pool_size=100,db=grafana`
# postgres: user=a password=b host=localhost port=5432 dbname=c sslmode=disable
# mysql: go-sql-driver/mysql dsn config string, e.g. `user:password@tcp(127.0.0.1:3306)/database_name`

provider_config = sessions

# Session cookie name
cookie_name = grafana_sess

# If you use session in https only, default is false
cookie_secure = true

# Session life time, default is 86400
session_life_time = 86400

#################################### Analytics ####################################
[analytics]
# Server reporting, sends usage counters to stats.grafana.org every 24 hours.
# No ip addresses are being tracked, only simple counters to track
# running instances, dashboard and error counts. It is very helpful to us.
# Change this option to false to disable reporting.
reporting_enabled = true

# Google Analytics universal tracking code, only enabled if you specify an id here
google_analytics_ua_id =

# Google Tag Manager ID, only enabled if you specify an id here
google_tag_manager_id =

#################################### Security ####################################
[security]
# default admin user, created on startup
admin_user = admin

# default admin password, can be changed before first start of grafana,  or in profile settings
admin_password = xxxxxxxxxxxxx

# used for signing
secret_key = xxxxxxxxxxxx

# Auto-login remember days
login_remember_days = 7
cookie_username = grafana_user
cookie_remember_name = grafana_remember

# disable gravatar profile images
disable_gravatar = false

#################################### Users ####################################
[users]
# disable user signup / registration
allow_sign_up = true

# Allow non admin users to create organizations
allow_org_create = false

# Set to true to automatically assign new users to the default organization (id 1)
auto_assign_org = false

# Default role new users will be automatically assigned (if auto_assign_org above is set to true)
auto_assign_org_role = Viewer

# Require email validation before sign up completes
verify_email_enabled = false

#################################### Anonymous Auth ##########################
[auth.anonymous]
# enable anonymous access
enabled = false

# specify organization name that should be used for unauthenticated users
org_name = Main Org.

# specify role for unauthenticated users
org_role = Viewer

#################################### Github Auth ##########################
[auth.github]
enabled = false
allow_sign_up = false
client_id = some_id
client_secret = some_secret
scopes = user:email
auth_url = https://github.com/login/oauth/authorize
token_url = https://github.com/login/oauth/access_token
api_url = https://api.github.com/user
team_ids =
allowed_organizations =

#################################### Google Auth ##########################
[auth.google]
enabled = false
allow_sign_up = false
client_id = some_client_id
client_secret = some_client_secret
scopes = https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
auth_url = https://accounts.google.com/o/oauth2/auth
token_url = https://accounts.google.com/o/oauth2/token
api_url = https://www.googleapis.com/oauth2/v1/userinfo
allowed_domains = 

#################################### Basic Auth ##########################
[auth.basic]
enabled = true

#################################### Auth Proxy ##########################
[auth.proxy]
enabled = false
header_name = X-WEBAUTH-USER
header_property = username
auto_sign_up = true

#################################### Auth LDAP ##########################
[auth.ldap]
enabled = false
config_file = /etc/grafana/ldap.toml

#################################### SMTP / Emailing ##########################
[smtp]
enabled = false
host = localhost:25
user =
password =
cert_file =
key_file =
skip_verify = false
from_address = admin@grafana.localhost

[emails]
welcome_email_on_sign_up = false
templates_pattern = emails/*.html

#################################### Logging ##########################
[log]
# Either "console", "file", default is "console"
# Use comma to separate multiple modes, e.g. "console, file"
mode = console, file

# Buffer length of channel, keep it as it is if you don't know what it is.
buffer_len = 10000

# Either "Trace", "Debug", "Info", "Warn", "Error", "Critical", default is "Trace"
level = Trace

# For "console" mode only
[log.console]
level =

# For "file" mode only
[log.file]
level =
# This enables automated log rotate(switch of following options), default is true
log_rotate = true

# Max line number of single file, default is 1000000
max_lines = 1000000

# Max size shift of single file, default is 28 means 1 << 28, 256MB
max_lines_shift = 28

# Segment log daily, default is true
daily_rotate = true

# Expired days of log file(delete after max days), default is 7
max_days = 7

#################################### AMPQ Event Publisher ##########################
[event_publisher]
enabled = false
rabbitmq_url = amqp://localhost/
exchange = grafana_events

#################################### Dashboard JSON files ##########################
[dashboards.json]
enabled = false
path = /var/lib/grafana/dashboards
```
