### ISSUE TITLE
Enhancement request: Binary and docker image support for s390x

### ISSUE THREAD

**Issue by vitt-bagal** [grafana/grafana#24273]
**What would you like to be added**:
Binaries and docker images for `s390x` arch

**Why is this needed**:
To use Grafana on `s390x`

**Comment by james-crowley** [comment]
@aknuds1 I saw you comment over on #24104. I am definitely interested in seeing support for `s390x`. Grafana is such a major monitoring tool and to not have `s390x` support cripples projects who rely on Grafana. 

I am willing to provide any support the development team needs, hardware, software patches, etc. 

Is there a place where we could discuss this further? I saw Grafana has a slack channel and joined but wanted to double check if the development team utilizes it.

**Comment by aknuds1** [comment]
@james-crowley Thanks for chiming in, I will check with colleagues.

**Comment by james-crowley** [comment]
Just wanted to update the issues for others following this thread. Myself and @aknuds1 have been communication via email. Will update this issue with any important information.

**Comment by Nayana-ibm** [comment]
@james-crowley Do we have any new update on this?

**Comment by james-crowley** [comment]
@Nayana-ibm Myself and @aknuds1 were talking about `s390x` support but I think the conversation stalled. Happy to pick it back up again!

**Comment by maxwellemerson** [comment]
Really disappointed with the lack of s390x support. Grafana is a great toolset. We've had to use RedHat distributed and integrate s390x exporters - From a DR perspective, having everything on the same platform is ideal.

**Comment by kycfeel** [comment]
Hi there. I'm also looking for an update on this!

**Comment by vitt-bagal** [comment]
@james-crowley Do we have any new update on this?

**Comment by james-crowley** [comment]
@vitt-bagal Sorry no knew updates. I have not had the time to reach out to a developer at Grafana Labs.

**Comment by vmorris** [comment]
AFAIK it's not supported by Grafana Labs, but IBM does build and make available a docker image for grafana: https://epwt-www.mybluemix.net/software/support/trial/cst/programwebsite.wss?siteId=1261&h=null&p=null

**Comment by vitt-bagal** [comment]
@james-crowley @aknuds1 Do we have any new update on this?

**Comment by aknuds1** [comment]
@vitt-bagal sorry, I'm not aware of any updates.

**Comment by JavaPerformance** [comment]
I finally got it to work... it's a bit hacky but acts a a guide.

https://github.com/JavaPerformance/GrafanaS390xBuild

**Comment by rvdheij** [comment]
Very good! I thought I was getting close last night with the guidance to use yarn-4.0.0.rc.12 but couldn’t finish it.
Ideally we should have something including the section on architecture. Not sure where we can get a handle on that, but might end up in the pre-processing

**Comment by JavaPerformance** [comment]
Glad I could help, feel free to tidy up the docker file

**Comment by JavaPerformance** [comment]
Can SWC be dropped for the moment?

**Comment by rvdheij** [comment]
Thank you again. I ended up dotting my own Dockerfile with your ideas, and have the 9.0.2 working here.
What I understood from the PR, it's "just" about the build speed. I don't understand these things well enough, but I was wondering whether we couldn't have the front-end stuff as "noarch" bolted on to the container that brings the binaries. Not having to build the image is even faster...

**Comment by rvdheij** [comment]
It's easier when you can stand on the shoulders of giants like @JavaPerformance who helped me understand what I needed. I have it now in my Dockerfile to build the Grafana image. I found it easiest to install yarn on the side first:
```
ENV YARN=4.0.0-rc.12
RUN npm install -g yarn \
  && mkdir -p /root/yarn-setup \
  && cd /root/yarn-setup \
  && yarn set version ${YARN}
```
Next, I clone the Grafana source and replace the older version of yarn by my more recent copy.
```
RUN rm .yarn/releases/yarn*.cjs \
 && cp /root/yarn-setup/.yarn/releases/*.cjs .yarn/releases/ \
 && sed -i "s/\(^yarnPath:.*\/yarn-\).*\.cjs/\1${YARN}.cjs/" .yarnrc.yml
```
Finally, I remove the SWC references from the source tree. Since diff/patch would be time-consuming to make them work after each change in nearby other package levels, I used 'jq' to filter the package.json files. The nice thing is that this will continue to work even when that original PR is reverted.
```
#
# Strip all references to the experimental SWC package since there's no s390x version of that.
# The 'jq' utility is more suitable to change JSON files than the diff/patch approach. Since it
# lacks an in-place 
#
RUN sed -i "/@yarnpkg\/plugin-typescript/d; /@yarnpkg\/plugin-interactive-tools/d" .yarnrc.yml \
 && for f in `find . -type f -name "package.json" -exec grep -l "swc/" {} +` ; do \
      jq '.devDependencies|=with_entries(select(.key|test("^@swc/.*")|not))' < $f | sponge $f ; \
    done \
 && yarn set version ${YARN}
```
While I created the recipe for 9.0.2, I'm happy to say that I could build 9.0.6 as well as the 9.1.0-beta1 without further changes..

**Comment by eaibmz** [comment]
@rvdheij Thanks for posting your instructions, worked for me as well on my s390x LPAR!

I tried first to build the latest grafana but it failed in `parcel@watcher` package added in commit da5bc5bde7ff8515d7f07fb01a7a3eaa94f87381.

**Comment by rvdheij** [comment]
I just built grafana:9.1.0 without problems.

**Comment by dandotimujahid** [comment]
@james-crowley Do you have any update on binary and docker image support for s390x ?

**Comment by rvdheij** [comment]
And I'm happy to say that my recipe just built 9.2.1 properly as well. We've seen no issues with running Grafana on s390x. Just having the container images would likely be good enough, and avoid the hassle of building for different distributions.

**Comment by JackieManuja** [comment]
@rvdheij - I am getting following issue in 9.2.5, any input would be a great help.
<img width="1293" alt="Screenshot 2022-12-29 at 1 53 50 PM" src="https://user-images.githubusercontent.com/2322936/209924864-576509ee-f21e-4bb5-80ae-a23fb5f5be38.png">

**Comment by rvdheij** [comment]
@JackieManuja I do have the built images here: https://hub.docker.com/repository/docker/rvdheij/grafana

**Comment by JackieManuja** [comment]
@rvdheij - Thank you for the quick turnaround.
But I need to create a custom image from 9.2.5, so I have to rebuild after the changes.

**Comment by rvdheij** [comment]
I'm still using that snippet to upgrade to yarn-4 and peel off the SWC with that script in the Dockerfile. There's probably enough in these posts to make your build work.

**Comment by JackieManuja** [comment]
Can you share the docker file for s390x?

**Comment by JackieManuja** [comment]
@rvdheij - Did you get a chance to look at my comment?

**Comment by ksdeekshith** [comment]
Hi there, I'm also looking forward to this enhancement request. Is it being supported in the future? Any progress here?

**Comment by sachinjangle** [comment]
I am trying to create s390x build of Grafana (version 9.2.5). I am using Go alpine image (`golang:1.19.3-alpine3.17`) to build Grafana but its getting failed at step `make build-go` with error as -
```
make: /bin/sh: Operation not permitted
make: /bin/sh: Operation not permitted
make: *** [Makefile:76: build-go] Error 127
```

Please let me know if anyone has any suggestion to fix this issue.

**Comment by yasiribmcon** [comment]
@james-crowley Do we have any updates on binary and docker image support for s390x ?

**Comment by JavaPerformance** [comment]
> Hi @james-crowley, Do we have any updates on binary and docker image support for s390x ?

Hi, I was planning to create new build instructions shortly, would that help?

**Comment by eaibmz** [comment]
New problem with Grafana 11 :( 
`nx@npm` has no support for s390x.

```
# This file contains the result of Yarn building a package (nx@virtual:fa6eeaa7c9f4e1db0f350601993a6029e8bb72c06889f8cfb84b0d52baf2222c364ee2e33fef459cbbe21959a676ab0d1a5b88ec4e42655dd590db72a28ac7fe#npm:18.1.3)
# Script name: postinstall

/tmp/grafana/node_modules/nx/src/native/index.js:235
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
        ^

Error: Unsupported architecture on Linux: s390x
    at Object.<anonymous> (/tmp/grafana/node_modules/nx/src/native/index.js:235:15)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/tmp/grafana/node_modules/nx/src/hasher/node-task-hasher-impl.js:10:18)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)

Node.js v20.11.1
```

**Comment by rvdheij** [comment]
Guess I didn't look yet. Next week or so...

**Comment by sachinjangle** [comment]
Hi there! I am also using Grafana 11.3.0 on s390x and getting same error as above of Unsupported architecture for nx@npm. 

Please let me know if there is any workaround.

**Comment by rvdheij** [comment]
I believe Neale proposed the fix for nx, but don't know whether it was accepted. 
I have decided to avoid the issue and use the front-end from x64 with the server built for s390x. Saves a lot of time when building the image. Works fine.

**Comment by JavaPerformance** [comment]
##########

FROM alpine:edge as grafana-builder

LABEL grafana-builder=true



ARG http_proxy=ChangeMe

ARG https_proxy=ChangeMe

ARG no_proxy=ChangeMe

ARG node_heap=12228



ENV HTTP_PROXY $http_proxy

ENV HTTPS_PROXY $https_proxy

ENV http_proxy $http_proxy

ENV https_proxy $https_proxy

ENV NO_PROXY $no_proxy

ENV no_proxy $no_proxy

ENV YARN_HTTP_PROXY $http_proxy

ENV YARN_HTTPS_PROXY $https_proxy

ENV NODE_OPTIONS --max-old-space-size=${node_heap}



USER root



WORKDIR /root



RUN mkdir -p /usr/local/share/ca-certificates/ \

    && wget -O /usr/local/share/ca-certificates/ChangeMe.crt
http://yourcompany.com/ChangeMe.crt



RUN cat /usr/local/share/ca-certificates/ChangeMe.crt >>
/etc/ssl/certs/ca-certificates.crt



RUN apk update

RUN apk upgrade



RUN apk --no-cache add ca-certificates \

    && rm -rf /var/cache/apk/*



RUN update-ca-certificates



RUN apk update

RUN apk upgrade



RUN apk --no-cache add bash nodejs-current npm yarn git go python3 g++ vim
make patch curl \

    && rm -rf /var/cache/apk/*



RUN yarn config set proxy $http_proxy \

    && yarn config set https-proxy $https_proxy \

    && npm config set proxy $http_proxy \

    && npm config set https-proxy $https_proxy \

    && git config --global http.proxy $http_proxy \

    && git config --global https.proxy $https_proxy



RUN git clone https://github.com/grafana/grafana.git



WORKDIR /root/grafana



RUN git checkout v11.4.0



ENV NODE_ENV production



RUN rm yarn.lock



ENV NAPI_RS_FORCE_WASI 1

ENV NX_DAEMON false

ENV NX_DISABLE_DB true



RUN yarn add @swc/wasm



RUN yarn install --immutable



RUN yarn build



RUN bash -c ' \

FAIL_COUNT=0; \

MAX_FAIL=20; \

while true; do \

    if [ $((FAIL_COUNT % 2)) -eq 0 ]; then \

        echo "Attempting with GOPROXY=https://proxy.golang.org..."; \

        GOPROXY=https://proxy.golang.org go mod download; \

    else \

        echo "Attempting with GOPROXY=direct..."; \

        GOPROXY=direct go mod download; \

    fi; \

    if [ $? -eq 0 ]; then \

        echo "Successfully downloaded all modules"; \

        break; \

    else \

        echo "Download failed, retrying..."; \

        FAIL_COUNT=$((FAIL_COUNT + 1)); \

        if [ $FAIL_COUNT -ge $MAX_FAIL ]; then \

            echo "Hit the maximum failure threshold ($MAX_FAIL), exiting.";
\

            exit 1; \

        fi; \

    fi; \

done'



RUN make build-go



##########

FROM alpine:edge as grafana



ARG http_proxy=ChangeMe

ARG https_proxy=ChangeMe

ARG no_proxy=ChangeMe



ENV HTTP_PROXY $http_proxy

ENV HTTPS_PROXY $https_proxy

ENV http_proxy $http_proxy

ENV https_proxy $https_proxy

ENV NO_PROXY $no_proxy

ENV no_proxy $no_proxy



RUN mkdir -p /usr/local/share/ca-certificates/ \

    && wget -O /usr/local/share/ca-certificates/ChangeMe.crt
http://yourcompany.com/ChangeMe.crt



RUN cat /usr/local/share/ca-certificates/ChangeMe.crt >>
/etc/ssl/certs/ca-certificates.crt



RUN apk update

RUN apk upgrade



RUN apk --no-cache add ca-certificates \

    && rm -rf /var/cache/apk/*



RUN update-ca-certificates



RUN apk update

RUN apk upgrade



ARG GF_UID="472"

ARG GF_GID="0"



ENV PATH="/usr/share/grafana/bin:$PATH"

#ENV GF_PATHS_CONFIG="/etc/grafana/grafana.ini"

ENV GF_PATHS_CONFIG="/var/lib/grafana/grafana.ini"

ENV GF_PATHS_DATA="/var/lib/grafana"

ENV GF_PATHS_HOME="/usr/share/grafana"

ENV GF_PATHS_LOGS="/var/log/grafana"

ENV GF_PATHS_PLUGINS="/var/lib/grafana/plugins"

ENV GF_PATHS_PROVISIONING="/etc/grafana/provisioning"



WORKDIR /usr/share/grafana



RUN apk add --no-cache ca-certificates bash tzdata musl-utils

RUN apk add --no-cache openssl ncurses-libs ncurses-terminfo-base

RUN apk upgrade ncurses-libs ncurses-terminfo-base

RUN apk info -vv | sort



RUN if [ ! $(getent group "$GF_GID") ]; then \

  addgroup -S -g $GF_GID grafana; \

  fi



COPY --from=grafana-builder /root/grafana/conf /usr/share/grafana/conf

COPY --from=grafana-builder /root/grafana/bin/linux-s390x/grafana
/usr/share/grafana/bin/

COPY --from=grafana-builder /root/grafana/bin/linux-s390x/grafana-server
/usr/share/grafana/bin/

COPY --from=grafana-builder /root/grafana/bin/linux-s390x/grafana-cli
/usr/share/grafana/bin/

COPY --from=grafana-builder /root/grafana/public /usr/share/grafana/public

COPY --from=grafana-builder /root/grafana/tools /usr/share/grafana/tools

COPY --from=grafana-builder /root/grafana/packaging/docker/run.sh /run.sh



RUN export GF_GID_NAME=$(getent group $GF_GID | cut -d':' -f1) && \

  mkdir -p "$GF_PATHS_HOME/.aws" && \

  adduser -S -u $GF_UID -G "$GF_GID_NAME" grafana && \

  mkdir -p "$GF_PATHS_PROVISIONING/datasources" \

  "$GF_PATHS_PROVISIONING/dashboards" \

  "$GF_PATHS_PROVISIONING/notifiers" \

  "$GF_PATHS_PROVISIONING/plugins" \

  "$GF_PATHS_PROVISIONING/access-control" \

  "$GF_PATHS_LOGS" \

  "$GF_PATHS_PLUGINS" \

  "$GF_PATHS_DATA" && \

  cp "$GF_PATHS_HOME/conf/ldap.toml" /etc/grafana/ldap.toml && \

  chown -R "grafana:$GF_GID_NAME" "$GF_PATHS_DATA" "$GF_PATHS_HOME/.aws"
"$GF_PATHS_LOGS" "$GF_PATHS_PLUGINS" "$GF_PATHS_PROVISIONING" && \

  chmod -R 777 "$GF_PATHS_DATA" "$GF_PATHS_HOME/.aws" "$GF_PATHS_LOGS"
"$GF_PATHS_PLUGINS" "$GF_PATHS_PROVISIONING"



EXPOSE 3000



USER grafana

ENTRYPOINT [ "/run.sh" ]



Paul Anderson (external) | External Staff | Contractor | Group Functions IT
Swiss Re Management Ltd | Soodring 6, 8134 Adliswil, Switzerland
<https://www.google.com/maps/search/Soodring+6,+8134+Adliswil,+Switzerland?entry=gmail&source=g>
Direct: +41 43 285 56 59 Email: ***@***.***





This e-mail, including attachments, is intended for the person(s) or
company(s) named and may contain confidential and/or legally privileged
information. Unauthorized disclosure, copying or use of this information
may be unlawful and is prohibited. If you are not the intended recipient,
please delete this message and notify the sender. All incoming and outgoing
e-mail messages are stored in the Swiss Re Electronic Message Repository.
If you do not wish the retention of potentially private e-mails by Swiss
Re, we strongly advise you not to use the Swiss Re e-mail account for any
private, non-business related communications.

**Comment by v1gnesh** [comment]
https://github.com/nrwl/nx/issues/27104

**Comment by sachinjangle** [comment]
@rvdheij Thanks for your input.
I tried to create the Grafana front-end for the x64 architecture yesterday using the following configuration:
`FROM --platform=linux/amd64 node:20-alpine as js-builder`

But the build is failing with the error:
`ERROR: process "/bin/sh -c yarn build" did not complete successfully: cannot allocate memory`

This is occurring despite having sufficient memory available on my machine. Have you faced similar issue while building the Grafana front-end?
```
admin@host:~$ free -h
               total        used        free      shared  buff/cache   available
Mem:           7.8Gi       978Mi       5.6Gi        26Mi       1.2Gi       6.7Gi
Swap:          6.0Gi       999Mi       5.0Gi
```

**Comment by JavaPerformance** [comment]
@sachinjangle  you might want to try setting the environment variable: NODE_OPTIONS --max-old-space-size=${SizeInMB}

**Comment by JavaPerformance** [comment]
@rvdheij  @v1gnesh  @sachinjangle this dockerfile worked for me:

`##########
FROM alpine:edge as grafana-builder
LABEL grafana-builder=true

ARG http_proxy=ChangeMe
ARG https_proxy=ChangeMe
ARG no_proxy=ChangeMe
ARG node_heap=12228

ENV HTTP_PROXY $http_proxy
ENV HTTPS_PROXY $https_proxy
ENV http_proxy $http_proxy
ENV https_proxy $https_proxy
ENV NO_PROXY $no_proxy
ENV no_proxy $no_proxy
ENV YARN_HTTP_PROXY $http_proxy
ENV YARN_HTTPS_PROXY $https_proxy
ENV NODE_OPTIONS --max-old-space-size=${node_heap}

USER root

WORKDIR /root

RUN mkdir -p /usr/local/share/ca-certificates/ \
    && wget -O /usr/local/share/ca-certificates/ChangeMe.crt http://yourcompany.com/ChangeMe.crt

RUN cat /usr/local/share/ca-certificates/ChangeMe.crt >> /etc/ssl/certs/ca-certificates.crt

RUN apk update
RUN apk upgrade

RUN apk --no-cache add ca-certificates \
    && rm -rf /var/cache/apk/*

RUN update-ca-certificates

RUN apk update
RUN apk upgrade

RUN apk --no-cache add bash nodejs-current npm yarn git go python3 g++ vim make patch curl \
    && rm -rf /var/cache/apk/*

RUN yarn config set proxy $http_proxy \
    && yarn config set https-proxy $https_proxy \
    && npm config set proxy $http_proxy \
    && npm config set https-proxy $https_proxy \
    && git config --global http.proxy $http_proxy \
    && git config --global https.proxy $https_proxy

RUN git clone https://github.com/grafana/grafana.git

WORKDIR /root/grafana

RUN git checkout v11.4.0

ENV NODE_ENV production

RUN rm yarn.lock

ENV NAPI_RS_FORCE_WASI 1
ENV NX_DAEMON false
ENV NX_DISABLE_DB true

RUN yarn add @swc/wasm

RUN yarn install --immutable

RUN yarn build

RUN bash -c ' \
FAIL_COUNT=0; \
MAX_FAIL=20; \
while true; do \
    if [ $((FAIL_COUNT % 2)) -eq 0 ]; then \
        echo "Attempting with GOPROXY=https://proxy.golang.org..."; \
        GOPROXY=https://proxy.golang.org go mod download; \
    else \
        echo "Attempting with GOPROXY=direct..."; \
        GOPROXY=direct go mod download; \
    fi; \
    if [ $? -eq 0 ]; then \
        echo "Successfully downloaded all modules"; \
        break; \
    else \
        echo "Download failed, retrying..."; \
        FAIL_COUNT=$((FAIL_COUNT + 1)); \
        if [ $FAIL_COUNT -ge $MAX_FAIL ]; then \
            echo "Hit the maximum failure threshold ($MAX_FAIL), exiting."; \
            exit 1; \
        fi; \
    fi; \
done'

RUN make build-go

##########
FROM alpine:edge as grafana

ARG http_proxy=ChangeMe
ARG https_proxy=ChangeMe
ARG no_proxy=ChangeMe

ENV HTTP_PROXY $http_proxy
ENV HTTPS_PROXY $https_proxy
ENV http_proxy $http_proxy
ENV https_proxy $https_proxy
ENV NO_PROXY $no_proxy
ENV no_proxy $no_proxy

RUN mkdir -p /usr/local/share/ca-certificates/ \
    && wget -O /usr/local/share/ca-certificates/ChangeMe.crt http://yourcompany.com/ChangeMe.crt

RUN cat /usr/local/share/ca-certificates/ChangeMe.crt >> /etc/ssl/certs/ca-certificates.crt

RUN apk update
RUN apk upgrade

RUN apk --no-cache add ca-certificates \
    && rm -rf /var/cache/apk/*

RUN update-ca-certificates

RUN apk update
RUN apk upgrade

ARG GF_UID="472"
ARG GF_GID="0"

ENV PATH="/usr/share/grafana/bin:$PATH"
#ENV GF_PATHS_CONFIG="/etc/grafana/grafana.ini"
ENV GF_PATHS_CONFIG="/var/lib/grafana/grafana.ini"
ENV GF_PATHS_DATA="/var/lib/grafana"
ENV GF_PATHS_HOME="/usr/share/grafana"
ENV GF_PATHS_LOGS="/var/log/grafana"
ENV GF_PATHS_PLUGINS="/var/lib/grafana/plugins"
ENV GF_PATHS_PROVISIONING="/etc/grafana/provisioning"

WORKDIR /usr/share/grafana

RUN apk add --no-cache ca-certificates bash tzdata musl-utils
RUN apk add --no-cache openssl ncurses-libs ncurses-terminfo-base
RUN apk upgrade ncurses-libs ncurses-terminfo-base
RUN apk info -vv | sort

RUN if [ ! $(getent group "$GF_GID") ]; then \
  addgroup -S -g $GF_GID grafana; \
  fi

COPY --from=grafana-builder /root/grafana/conf /usr/share/grafana/conf
COPY --from=grafana-builder /root/grafana/bin/linux-s390x/grafana /usr/share/grafana/bin/
COPY --from=grafana-builder /root/grafana/bin/linux-s390x/grafana-server /usr/share/grafana/bin/
COPY --from=grafana-builder /root/grafana/bin/linux-s390x/grafana-cli /usr/share/grafana/bin/
COPY --from=grafana-builder /root/grafana/public /usr/share/grafana/public
COPY --from=grafana-builder /root/grafana/tools /usr/share/grafana/tools
COPY --from=grafana-builder /root/grafana/packaging/docker/run.sh /run.sh

RUN export GF_GID_NAME=$(getent group $GF_GID | cut -d':' -f1) && \
  mkdir -p "$GF_PATHS_HOME/.aws" && \
  adduser -S -u $GF_UID -G "$GF_GID_NAME" grafana && \
  mkdir -p "$GF_PATHS_PROVISIONING/datasources" \
  "$GF_PATHS_PROVISIONING/dashboards" \
  "$GF_PATHS_PROVISIONING/notifiers" \
  "$GF_PATHS_PROVISIONING/plugins" \
  "$GF_PATHS_PROVISIONING/access-control" \
  "$GF_PATHS_LOGS" \
  "$GF_PATHS_PLUGINS" \
  "$GF_PATHS_DATA" && \
  cp "$GF_PATHS_HOME/conf/ldap.toml" /etc/grafana/ldap.toml && \
  chown -R "grafana:$GF_GID_NAME" "$GF_PATHS_DATA" "$GF_PATHS_HOME/.aws" "$GF_PATHS_LOGS" "$GF_PATHS_PLUGINS" "$GF_PATHS_PROVISIONING" && \
  chmod -R 777 "$GF_PATHS_DATA" "$GF_PATHS_HOME/.aws" "$GF_PATHS_LOGS" "$GF_PATHS_PLUGINS" "$GF_PATHS_PROVISIONING"

EXPOSE 3000

USER grafana
ENTRYPOINT [ "/run.sh" ]
`

**Comment by rvdheij** [comment]
No, you're still trying to build the front-end. I take the easy route like this
```
FROM docker.io/s390x/golang:${GOLANG_VERSION} as builder

... # build the back-end stuff

# Get a copy of the x64 container to borrow the front-end as built
FROM --platform=linux/amd64 docker.io/grafana/grafana:${GRAFANA_VERSION} as js-built

# Create the runtime package from the two earlier ones
FROM --platform=linux/s390x docker.io/debian:stable
ARG BASE

EXPOSE 3000

ARG GF_UID="472"
ARG GF_GID="472"
 ...

COPY --from=js-built $GF_PATHS_HOME/public/            $GF_PATHS_HOME/public/

COPY --from=builder $BASE/conf/              $GF_PATHS_HOME/conf/
COPY --from=builder $BASE/conf/sample.ini    $GF_PATHS_CONFIG
COPY --from=builder $BASE/conf/ldap.toml     /etc/grafana/
COPY --from=builder $BASE/bin/linux-s390x/grafana         /usr/sbin/
COPY --from=builder $BASE/bin/linux-s390x/grafana-server /usr/sbin/
COPY --from=builder $BASE/bin/linux-s390x/grafana-cli    /usr/sbin/
```

**Comment by sachinjangle** [comment]
Theoretically, the multi-architecture build should have worked, but it failed for an unknown reason.

@JavaPerformance: I tried incorporating some of the changes from your Dockerfile but unfortunately it did not work for me. Thank you for taking time to provide your input.

@rvdheij: Thank you for your input. I am able to successfully create the build using your approach. As I customized Grafana to suit my requirements, I first created the x86 build, pushed it to the DTR and then proceeded to create the s390x build by referring  **public** folder from it.
