### ISSUE TITLE
Cloudwatch: Panic on query

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#24639]
Not sure what I did. Been clicking around the cheat sheet examples.
grafana-server ended with a panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4ef5189]

goroutine 1189 [running]:
github.com/grafana/grafana/pkg/tsdb/cloudwatch.generateGroupKey(0xc001177940, 0x2, 0x2, 0x15, 0xc0011d0188, 0x0)
	/Users/david/go/src/github.com/grafana/grafana/pkg/tsdb/cloudwatch/log_query.go:116 +0x29
github.com/grafana/grafana/pkg/tsdb/cloudwatch.groupResults(0xc0010da980, 0xc000da6180, 0x2, 0x2, 0x2, 0x2, 0x0, 0x0, 0xc0009ec2d0)
	/Users/david/go/src/github.com/grafana/grafana/pkg/tsdb/cloudwatch/log_query.go:95 +0x3f1
github.com/grafana/grafana/pkg/tsdb/cloudwatch.(*CloudWatchExecutor).executeLogActions.func1(0x1, 0x0)
	/Users/david/go/src/github.com/grafana/grafana/pkg/tsdb/cloudwatch/log_actions.go:43 +0x2d7
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000c5c780, 0xc000e37040)
	/Users/david/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	/Users/david/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:54 +0x66
```

**Comment by aknuds1** [comment]
Which Grafana version?

**Comment by davkal** [comment]
16297da298
