### ISSUE TITLE
Grafana ignoring GF_RENDERING_CALLBACK_URL settings

### ISSUE THREAD

**Issue by gkelekov** [grafana/grafana#25109]
**What happened**:
Grafana 7.0.x. config of GF_RENDERING_CALLBACK_URL is not checked when Grafana sends request to Grafana image renderer.
 
Grafana running with docker compose, with newly created Grafana image renderer. Grafana compose has in its environment:

>     - GF_RENDERING_SERVER_URL=http://10.50.x.x:8081/render
>     - GF_RENDERING_CALLBACK_URL=http://10.50.x.x:80/

Grafana image renderer is started on same host as Grafana, running containers in bridged network mode. Both containers run properly and are, individually, working as they should, and Grafana recognise external image renderer.
> 12:10:53.000 info t=2020-05-26T12:10:53+0200 lvl=info msg="Backend rendering via external http server" logger=rendering renderer=http

But rendering image is not working:
![image](https://user-images.githubusercontent.com/27995366/82901194-e7536a80-9f5d-11ea-9260-0a6dd344bc0b.png)

Grafana log:
```
12:42:23.000 info t=2020-05-26T12:42:23+0200 lvl=info msg=Rendering logger=rendering renderer=http path="d-solo/OKVuQVCmk/skela-upis-dbi-problemi?orgId=1&from=1590487941656&to=1590489741656&var-IzvorUplate=All&panelId=32&width=1000&height=500&tz=Europe%2FZagreb"
12:42:24.000 info t=2020-05-26T12:42:24+0200 lvl=dbug msg="calling remote rendering service" logger=rendering renderer=http url="http://10.50.xx.xx:8081/render?deviceScaleFactor=1.000000&domain=localhost&encoding=&height=500&renderKey=G2KDS05ZUDA5pWcGu3rpou2Jl0YAVSZ6&timeout=60&timezone=Europe%2FZagreb&url=http%3A%2F%2Flocalhost%3A3000%2Frender%2Fd-solo%2FOKVuQVCmk%2Fskela-upis-dbi-problemi%3ForgId%3D1%26from%3D1590487941656%26to%3D1590489741656%26var-IzvorUplate%3DAll%26panelId%3D32%26width%3D1000%26height%3D500%26tz%3DEurope%252FZagreb%26render%3D1&width=1000"
12:42:24.000 info t=2020-05-26T12:42:24+0200 lvl=eror msg="Remote rendering request failed" logger=rendering renderer=http error="500 Internal Server Error"
```

Grafana image renderer log:

```
12:42:24.000 s2 s2ops1 info {"url":"http://localhost:3000/render/d-solo/OKVuQVCmk/skela-upis-dbi-problemi?orgId=1&from=1590487941656&to=1590489741656&var-IzvorUplate=All&panelId=32&width=1000&height=500&tz=Europe%2FZagreb&render=1","level":"debug","message":"Render request received"}
12:42:24.000 s2 s2ops1 info {"url":"http://localhost:3000/render/d-solo/OKVuQVCmk/skela-upis-dbi-problemi?orgId=1&from=1590487941656&to=1590489741656&var-IzvorUplate=All&panelId=32&width=1000&height=500&tz=Europe%2FZagreb&render=1","method":"GET","level":"error","message":"Browser request failed"}
12:42:24.000 s2 s2ops1 info {"url":"/render?deviceScaleFactor=1.000000&domain=localhost&encoding=&height=500&renderKey=G2KDS05ZUDA5pWcGu3rpou2Jl0YAVSZ6&timeout=60&timezone=Europe%2FZagreb&url=http%3A%2F%2Flocalhost%3A3000%2Frender%2Fd-solo%2FOKVuQVCmk%2Fskela-upis-dbi-problemi%3ForgId%3D1%26from%3D1590487941656%26to%3D1590489741656%26var-IzvorUplate%3DAll%26panelId%3D32%26width%3D1000%26height%3D500%26tz%3DEurope%252FZagreb%26render%3D1&width=1000","stack":"Error: net::ERR_CONNECTION_REFUSED at http://localhost:3000/render/d-solo/OKVuQVCmk/skela-upis-dbi-problemi?orgId=1&from=1590487941656&to=1590489741656&var-IzvorUplate=All&panelId=32&width=1000&height=500&tz=Europe%2FZagreb&render=1\n    at navigate (/usr/src/app/node_modules/puppeteer/lib/FrameManager.js:120:37)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async FrameManager.navigateFrame (/usr/src/app/node_modules/puppeteer/lib/FrameManager.js:94:17)\n    at async Frame.goto (/usr/src/app/node_modules/puppeteer/lib/FrameManager.js:406:12)\n    at async Page.goto (/usr/src/app/node_modules/puppeteer/lib/Page.js:675:12)\n  -- ASYNC --\n    at Frame.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:111:15)\n    at Page.goto (/usr/src/app/node_modules/puppeteer/lib/Page.js:675:49)\n    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:112:23)\n    at Browser.<anonymous> (/usr/src/app/build/browser/browser.js:130:24)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/build/browser/browser.js:4:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","level":"error","message":"Request failed"}
12:42:24.000 s2 s2ops1 info {"url":"http://localhost:3000/render/d-solo/OKVuQVCmk/skela-upis-dbi-problemi?orgId=1&from=1590487941656&to=1590489741656&var-IzvorUplate=All&panelId=32&width=1000&height=500&tz=Europe%2FZagreb&render=1","level":"debug","message":"Connection closed"}
12:42:24.000 s2 s2ops1 info {"message":"::ffff:172.17.0.1 - - [26/May/2020:10:42:24 +0000] \"GET /render?deviceScaleFactor=1.000000&domain=localhost&encoding=&height=500&renderKey=G2KDS05ZUDA5pWcGu3rpou2Jl0YAVSZ6&timeout=60&timezone=Europe%2FZagreb&url=http%3A%2F%2Flocalhost%3A3000%2Frender%2Fd-solo%2FOKVuQVCmk%2Fskela-upis-dbi-problemi%3ForgId%3D1%26from%3D1590487941656%26to%3D1590489741656%26var-IzvorUplate%3DAll%26panelId%3D32%26width%3D1000%26height%3D500%26tz%3DEurope%252FZagreb%26render%3D1&width=1000 HTTP/1.1\" 500 96 \"-\" \"Grafana/7.0.1\"\n","level":"error"}
```
It seems to us that the problem is in Grafana, exacly, it does not read callback_url we have setup, but it is always set to http://localhost:3000 (as can be seen in image renderer log)

We tried also to edit Grafana defaults.ini within container 
```
[rendering]
server_url = http://10.50.xx.xx:8081/render
callback_url = http://10.50.xx.xx/
```
With no help. It seems that it always just checks http_addr and http_port defined withing config:
```
# The ip address to bind to, empty will bind to all interfaces 
http_addr =
# The http port  to use
http_port = 3000
#http_port = 80
```

**What you expected to happen**:
Image rendered when using Share > Direct link rendered image

**How to reproduce it (as minimally and precisely as possible)**:
Start Grafana with docker-compose with any port but 3000, exposed to host, and connect it to Grafana image renderer (using host IP addreses). Changing GF_RENDERING_CALLBACK_URL will be ignored and Grafana will always sent http://localhost:3000 as callback url to image renderer.

**Anything else we need to know?**:
I can confirm that there is no problem with networking, as I can curl or wget from Grafana container to image rendere container and vice versa.

**Environment**:
- Grafana version: 7.0.0. / 7.0.1.
- Data source type & version: Graphite
- OS Grafana is installed on: Ubuntu 16.04, Docker 18.03.1-ce
- User OS & Browser: MacOS, Opera, Firefox, Chrome
- Grafana plugins: grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel,grafana-piechart-panel
- Others:

**Comment by aknuds1** [comment]
@marefr Wondering what priority we ought to assign this, in case it's a bug introduced by v7?

**Comment by marefr** [comment]
@gkelekov csn you please include your full docker compose file and grafana server log (when it starts up) since it should show that you've overridden certain settings using environment variables. Thanks

**Comment by marefr** [comment]
FYI Using the example [here](https://github.com/grafana/grafana-image-renderer/blob/master/docs/remote_rendering_using_docker.md#docker-compose-example) `GF_RENDERING_CALLBACK_URL` is properly overridden and my rendering works.

```bash
> docker pull grafana/grafana:latest
> docker pull grafana/grafana-image-renderer:latest
> docker-compose logs grafana                                                                                                                                                                 
Attaching to simple_grafana_1                                                                                                                                                                 
grafana_1   | t=2020-05-26T22:41:42+0000 lvl=info msg="Starting Grafana" logger=server version=7.0.1 commit=ef5b586d7d branch=HEAD compiled=2020-05-26T08:05:56+0000                          
grafana_1   | t=2020-05-26T22:41:42+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini                                                          
grafana_1   | t=2020-05-26T22:41:42+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini                                                                      
grafana_1   | t=2020-05-26T22:41:42+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"                                         
grafana_1   | t=2020-05-26T22:41:42+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"                                         
grafana_1   | t=2020-05-26T22:41:42+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"                              
grafana_1   | t=2020-05-26T22:41:42+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"                        
grafana_1   | t=2020-05-26T22:41:42+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.log.mode=console"                                                    
grafana_1   | t=2020-05-26T22:41:42+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_DATA=/var/lib/grafana"                                      
grafana_1   | t=2020-05-26T22:41:42+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_LOGS=/var/log/grafana"                                      
grafana_1   | t=2020-05-26T22:41:42+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PLUGINS=/var/lib/grafana/plugins"                           
grafana_1   | t=2020-05-26T22:41:42+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PROVISIONING=/etc/grafana/provisioning"                     
grafana_1   | t=2020-05-26T22:41:42+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_LOG_FILTERS=rendering:debug"
grafana_1   | t=2020-05-26T22:41:42+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_RENDERING_SERVER_URL=http://renderer:8081/render"
grafana_1   | t=2020-05-26T22:41:42+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_RENDERING_CALLBACK_URL=http://grafana:3000/"

...

grafana_1   | t=2020-05-26T22:41:44+0000 lvl=info msg="Backend rendering via external http server" logger=rendering renderer=http
grafana_1   | t=2020-05-26T22:41:44+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
grafana_1   | t=2020-05-26T22:42:25+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=172.19.0.1 time_ms=0 size=29 referer=
grafana_1   | t=2020-05-26T22:42:30+0000 lvl=info msg="Successful Login" logger=http.server User=admin@localhost
grafana_1   | t=2020-05-26T22:42:49+0000 lvl=info msg=Rendering logger=rendering renderer=http path="d-solo/1pDPO5kMz/new-dashboard-copy?orgId=1&from=1590511368112&to=1590532968112&panelId=2&width=1000&height=500&tz=Europe%2FStockholm"
grafana_1   | t=2020-05-26T22:42:49+0000 lvl=dbug msg="calling remote rendering service" logger=rendering renderer=http url="http://renderer:8081/render?deviceScaleFactor=1.000000&domain=grafana&encoding=&height=500&renderKey=LJGprkxNyau2fZ2Xjvenp7gPEugtedny&timeout=60&timezone=Europe%2FStockholm&url=http%3A%2F%2Fgrafana%3A3000%2Fd-solo%2F1pDPO5kMz%2Fnew-dashboard-copy%3ForgId%3D1%26from%3D1590511368112%26to%3D1590532968112%26panelId%3D2%26width%3D1000%26height%3D500%26tz%3DEurope%252FStockholm%26render%3D1&width=1000"
```

**Comment by gkelekov** [comment]
This is very weird. 
After losing 2 days for this issue, today I restarted Grafana (v7.0.1.) and image renderer (it picked up latest version), with changed grafana ini file (to enable debug logs). We wanted to see if config if overwritten from env. It is and after stop-start, it started to send proper callback_url:
`13:27:34.000  info t=2020-05-27T13:27:34+0200 lvl=info msg=Rendering logger=rendering renderer=http path="d-solo/UQhNReaik/wall-supersport-local?orgId=1&refresh=10s&from=1590574933600&to=1590578533600&var-IzvorUplate=All&panelId=8&width=1000&height=500&tz=Europe%2FZagreb"`

`13:27:34.000  info {"url":"http://10.50.XX.XX/d-solo/UQhNReaik/wall-supersport-local?orgId=1&refresh=10s&from=1590574933600&to=1590578533600&var-IzvorUplate=All&panelId=8&width=1000&height=500&tz=Europe%2FZagreb&render=1","level":"debug","message":"Render request received"}`

I'll try to investigate further what happened on our system to cause such strange behaviour (maybe some docker layer not refreshing properly with update, or something in that direction)

Thank you for help.
You can close this issue.

**Comment by marefr** [comment]
Thanks for confirming
