### ISSUE TITLE
Failed to load plugin '@typescript-eslint' declared in '.eslintrc » @grafana/eslint-config#overrides[1] » ./config-ts.js': Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by edannenberg** [grafana/grafana#25145]
**What happened**:

Building grafana fails since v6.7.0 with:

```
ModuleError: Module Error (from ./node_modules/eslint-loader/dist/cjs.js):
  Failed to load plugin '@typescript-eslint' declared in '.eslintrc » @grafana/eslint-config#overrides[1] » ./config-ts.js': Cannot convert undefined or null to object
      at emitError (/var/tmp/portage/www-apps/grafana-7.0.1/work/grafana-7.0.1/src/github.com/grafana/grafana/node_modules/webpack/lib/NormalModule.js:173:6)
      at Linter.lint (/var/tmp/portage/www-apps/grafana-7.0.1/work/grafana-7.0.1/src/github.com/grafana/grafana/node_modules/eslint-loader/dist/Linter.js:55:29)
      at Object.loader (/var/tmp/portage/www-apps/grafana-7.0.1/work/grafana-7.0.1/src/github.com/grafana/grafana/node_modules/eslint-loader/dist/index.js:26:29)
      at LOADER_EXECUTION (/var/tmp/portage/www-apps/grafana-7.0.1/work/grafana-7.0.1/src/github.com/grafana/grafana/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
      at runSyncOrAsync (/var/tmp/portage/www-apps/grafana-7.0.1/work/grafana-7.0.1/src/github.com/grafana/grafana/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
      at iterateNormalLoaders (/var/tmp/portage/www-apps/grafana-7.0.1/work/grafana-7.0.1/src/github.com/grafana/grafana/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
      at Array.<anonymous> (/var/tmp/portage/www-apps/grafana-7.0.1/work/grafana-7.0.1/src/github.com/grafana/grafana/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
      at Storage.finished (/var/tmp/portage/www-apps/grafana-7.0.1/work/grafana-7.0.1/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
      at /var/tmp/portage/www-apps/grafana-7.0.1/work/grafana-7.0.1/src/github.com/grafana/grafana/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
      at /var/tmp/portage/www-apps/grafana-7.0.1/work/grafana-7.0.1/src/github.com/grafana/grafana/node_modules/graceful-fs/graceful-fs.js:123:16
      at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
  TypeError: Failed to load plugin '@typescript-eslint' declared in '.eslintrc » @grafana/eslint-config#overrides[1] » ./config-ts.js': Cannot convert undefined or null to object
      at Function.getOwnPropertyNames (<anonymous>)
      at /var/tmp/portage/www-apps/grafana-7.0.1/work/grafana-7.0.1/src/github.com/grafana/grafana/node_modules/@typescript-eslint/eslint-plugin/dist/rules/unbound-method.js:34:19
      at Array.map (<anonymous>)
      at Object.<anonymous> (/var/tmp/portage/www-apps/grafana-7.0.1/work/grafana-7.0.1/src/github.com/grafana/grafana/node_modules/@typescript-eslint/eslint-plugin/dist/rules/unbound-method.js:32:6)
      at Module._compile (/var/tmp/portage/www-apps/grafana-7.0.1/work/grafana-7.0.1/src/github.com/grafana/grafana/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
      at Module.load (internal/modules/cjs/loader.js:1002:32)
      at Function.Module._load (internal/modules/cjs/loader.js:901:14)
      at Module.require (internal/modules/cjs/loader.js:1044:19)
      at require (/var/tmp/portage/www-apps/grafana-7.0.1/work/grafana-7.0.1/src/github.com/grafana/grafana/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
      at Object.<anonymous> (/var/tmp/portage/www-apps/grafana-7.0.1/work/grafana-7.0.1/src/github.com/grafana/grafana/node_modules/@typescript-eslint/eslint-plugin/dist/rules/index.js:91:42)
      at Module._compile (/var/tmp/portage/www-apps/grafana-7.0.1/work/grafana-7.0.1/src/github.com/grafana/grafana/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
      at Module.load (internal/modules/cjs/loader.js:1002:32)
      at Function.Module._load (internal/modules/cjs/loader.js:901:14)
      at Module.require (internal/modules/cjs/loader.js:1044:19)
      at require (/var/tmp/portage/www-apps/grafana-7.0.1/work/grafana-7.0.1/src/github.com/grafana/grafana/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
      at Object.<anonymous> (/var/tmp/portage/www-apps/grafana-7.0.1/work/grafana-7.0.1/src/github.com/grafana/grafana/node_modules/@typescript-eslint/eslint-plugin/dist/index.js:5:33)
      at Module._compile (/var/tmp/portage/www-apps/grafana-7.0.1/work/grafana-7.0.1/src/github.com/grafana/grafana/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
      at Module.load (internal/modules/cjs/loader.js:1002:32)
      at Function.Module._load (internal/modules/cjs/loader.js:901:14)
      at Module.require (internal/modules/cjs/loader.js:1044:19)
      at require (/var/tmp/portage/www-apps/grafana-7.0.1/work/grafana-7.0.1/src/github.com/grafana/grafana/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
      at ConfigArrayFactory._loadPlugin (/var/tmp/portage/www-apps/grafana-7.0.1/work/grafana-7.0.1/src/github.com/grafana/grafana/node_modules/eslint/lib/cli-engine/config-array-factory.js:978:42)
      at /var/tmp/portage/www-apps/grafana-7.0.1/work/grafana-7.0.1/src/github.com/grafana/grafana/node_modules/eslint/lib/cli-engine/config-array-factory.js:848:33
      at Array.reduce (<anonymous>)
      at ConfigArrayFactory._loadPlugins (/var/tmp/portage/www-apps/grafana-7.0.1/work/grafana-7.0.1/src/github.com/grafana/grafana/node_modules/eslint/lib/cli-engine/config-array-factory.js:844:22)
      at ConfigArrayFactory._normalizeObjectConfigDataBody (/var/tmp/portage/www-apps/grafana-7.0.1/work/grafana-7.0.1/src/github.com/grafana/grafana/node_modules/eslint/lib/cli-engine/config-array-factory.js:667:32)
      at _normalizeObjectConfigDataBody.next (<anonymous>),
```

**What you expected to happen**:

Build succeeds.

**How to reproduce it (as minimally and precisely as possible)**:

```
yarn install --pure-lockfile
./node_modules/.bin/grunt build
```

**Anything else we need to know?**:

I maintain this package for years now for my custom docker image stack, last successful version I can build is `6.6.2`.

**Environment**:
- Grafana version: 6.7.0 - latest (7.0.1)
- User OS & Browser:
    Gentoo based Docker container with nodejs v12.16.3 / yarn 1.22.4

**Comment by aknuds1** [comment]
For reference, I just tried the same steps as you on Arch Linux, works for me:

```
yarn install --pure-lockfile
./node_modules/.bin/grunt build
```

**Comment by edannenberg** [comment]
Weird, I just tried again with the official Gentoo image, which I don't use normally, same issue. Steps for reproducing:

```
docker create -v /usr/portage --name myportagesnapshot gentoo/portage:latest /bin/true
docker run --interactive --tty --volumes-from myportagesnapshot gentoo/stage3-amd64-hardened-nomultilib:latest /bin/bash

echo '>=net-libs/nodejs-12.16.2' > /etc/portage/package.mask
echo 'sys-apps/yarn ~amd64' > /etc/portage/package.accept_keywords
emerge dev-vcs/git nodejs yarn
git clone https://github.com/grafana/grafana.git
cd grafana/
git checkout v6.7.0
yarn install --pure-lockfile
./node_modules/.bin/grunt build
```

You can then switch to the `v6.6.2` branch in the same image and the build works.

**Comment by torkelo** [comment]
Closing this, we do not provide help for building old branches 

Maybe you can get help on the community site https://community.grafana.com

**Comment by edannenberg** [comment]
I have the same issue with the current master, I only referenced the `6.7.0` branch as the earliest one with the issue.

**Comment by edannenberg** [comment]
Ran `git bisect` on the good/bad tags, f48169633ce9a9387d468081140b1b1a6e2c5ad6 is the bad commit. Which is sadly not very helpful. Is there a way to build the project without running eslint?

**Comment by aknuds1** [comment]
@edannenberg For troubleshooting, have you tried on another Linux distro, f.ex. Debian?

**Comment by edannenberg** [comment]
I don't have another Distro available so not really an option for me. However I could build the shipped `Dockerfile.ubuntu` ruling out any Docker host issues.

Finally caved in and debugged the stacktrace (not exactly a nodejs fan to say the least):

`at node_modules/@typescript-eslint/eslint-plugin/dist/rules/unbound-method.js:34:19`

```
const nativelyBoundMembers = [
    'Promise',
    'Number',
    'Object',
    'String',
    'RegExp',
    'Symbol',
    'Array',
    'Proxy',
    'Date',
    'Infinity',
    'Atomics',
    'Reflect',
    'console',
    'Math',
    'JSON',
    'Intl',
]
    .map(namespace => {
    const object = global[namespace];
    console.log(namespace);
    return Object.getOwnPropertyNames(object)
        .filter(name => !name.startsWith('_') &&
        typeof object[name] === 'function')
        .map(name => `${namespace}.${name}`);
})
    .reduce((arr, names) => arr.concat(names), []);
```

```
# ./node_modules/.bin/grunt build
...
Promise
Number
Object
String
RegExp
Symbol
Array
Proxy
Date
Infinity
Atomics
Reflect
console
Math
JSON
Intl
TypeError: Failed to load plugin '@typescript-eslint' declared in '.eslintrc » @grafana/eslint-config#overrides[1] » ./config-ts.js': Cannot convert undefined or null to object
    at Function.getOwnPropertyNames (<anonymous>)
    at node_modules/@typescript-eslint/eslint-plugin/dist/rules/unbound-method.js:35:19
```

Apparently `eslint` always expects `icu`, which is not the default on Gentoo. :facepalm: Build works now after enabling it.

**Comment by aknuds1** [comment]
Can we close this issue then?
