### ISSUE TITLE
Test failures on 32bit archs after v7.0.0

### ISSUE THREAD

**Issue by kaey** [grafana/grafana#25287]
**What happened**:

Running `go test ./...` in alpine linux on x86 and armv7 results in failures. Full build log available here:

armv7 - https://tpaste.us/7KaL
x86 - https://tpaste.us/1OzQ

These are regressions introduced in v7.0.0

**What you expected to happen**:

no failures

**How to reproduce it (as minimally and precisely as possible)**:

`go test ./...` on x86 host

**Anything else we need to know?**:

Commits that (likely) introduced failures - 56687a08f91, 51536738840

**Environment**:
- Grafana version: v7.0.1
- Data source type & version: n/a
- OS Grafana is installed on: Alpine linux edge
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others:

**Comment by kylebrandt** [comment]
A but more specifically I can trigger this in the SDK with the arrow Encode test:

```
# github.com/grafana/grafana-plugin-sdk-go/data
$ GOOS=linux GOARCH=386 go test ./... -run '^(TestEncode)$' -v
=== RUN   TestEncode
--- FAIL: TestEncode (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x804a16b]

goroutine 6 [running]:
testing.tRunner.func1.1(0x8401f60, 0x87a8838)
        /usr/local/go/src/testing/testing.go:940 +0x27c
testing.tRunner.func1(0xa16e140)
        /usr/local/go/src/testing/testing.go:943 +0x349
panic(0x8401f60, 0x87a8838)
        /usr/local/go/src/runtime/panic.go:969 +0x122
runtime/internal/atomic.Load64(0xa016a5c, 0x841de60, 0x0)
        /usr/local/go/src/runtime/internal/atomic/asm_386.s:194 +0xb
github.com/apache/arrow/go/arrow/array.(*Chunked).Release(0xa016a50)
        /home/kbrandt/go/pkg/mod/github.com/apache/arrow/go/arrow@v0.0.0-20200403134915-89ce1cadb678/array/table.go:141 +0x2e
panic(0x8401f60, 0x87a8838)
        /usr/local/go/src/runtime/panic.go:969 +0x122
runtime/internal/atomic.Xadd64(0xa016a5c, 0x1, 0x0, 0x1, 0x0)
        /usr/local/go/src/runtime/internal/atomic/asm_386.s:105 +0xc
github.com/apache/arrow/go/arrow/array.(*Chunked).Retain(...)
        /home/kbrandt/go/pkg/mod/github.com/apache/arrow/go/arrow@v0.0.0-20200403134915-89ce1cadb678/array/table.go:134
github.com/apache/arrow/go/arrow/array.NewColumn(0x8452d4a, 0xd, 0x84f70b0, 0x87bff58, 0x0, 0xa1843c0, 0x3, 0x3, 0xa1843e0, 0x3, ...)
        /home/kbrandt/go/pkg/mod/github.com/apache/arrow/go/arrow@v0.0.0-20200403134915-89ce1cadb678/array/table.go:56 +0x91
github.com/grafana/grafana-plugin-sdk-go/data.buildStringColumn(0x84f8370, 0x87bff58, 0x8452d4a, 0xd, 0x84f70b0, 0x87bff58, 0x0, 0xa1843c0, 0x3, 0x3, ...)
        /home/kbrandt/go/github.com/grafana/grafana-plugin-sdk-go/data/arrow_column_builders.go:20 +0x28a
github.com/grafana/grafana-plugin-sdk-go/data.buildArrowColumns(0xa02df60, 0xa174500, 0x1b, 0x1b, 0xa0168d0, 0x0, 0x0, 0x0, 0x7791f700)
        /home/kbrandt/go/github.com/grafana/grafana-plugin-sdk-go/data/arrow.go:159 +0x1318
github.com/grafana/grafana-plugin-sdk-go/data.(*Frame).MarshalArrow(0xa02df60, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/kbrandt/go/github.com/grafana/grafana-plugin-sdk-go/data/arrow.go:30 +0xe5
github.com/grafana/grafana-plugin-sdk-go/data_test.TestEncode(0xa16e140)
        /home/kbrandt/go/github.com/grafana/grafana-plugin-sdk-go/data/arrow_test.go:239 +0x23
testing.tRunner(0xa16e140, 0x846ec88)
        /usr/local/go/src/testing/testing.go:991 +0xb4
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1042 +0x2ad
FAIL    github.com/grafana/grafana-plugin-sdk-go/data   0.004s
testing: warning: no tests to run
PASS
ok      github.com/grafana/grafana-plugin-sdk-go/data/sqlutil   (cached) [no tests to run]
FAIL
```

will work to pin down more.

**Comment by kylebrandt** [comment]
Underlying our Dataframes in the backend is Apache Arrow. The Apache Arrow Go library's tests also fail on 32-bit for what looks to be the same reason from traces. Created an issue in their Jira tracker: https://issues.apache.org/jira/browse/ARROW-9174

**Comment by kylebrandt** [comment]
I think https://github.com/apache/arrow/pull/7483 might a fix / workaround for the problem in sync/atomic https://github.com/golang/go/issues/37262

**Comment by kylebrandt** [comment]
Setting for 7.1 assuming a fix lands in the arrow library by then. If not can be the next patch release.

**Comment by kaey** [comment]
@kylebrandt 
Thanks for working on this. Github being a very nice service didn't send me single email for this issue even though i'm subscribed.

Unfortunately 1 problem mentioned here remains unfixed, I filed another issue #26389
