### ISSUE TITLE
Remote rendering with dockerized container sometimes fails

### ISSUE THREAD

**Issue by languitar** [grafana/grafana#25716]
**What happened**:

We have Grafana 7 running on EKS with the dockerized remote rendering service deployed for rendering alert images. Sometimes, instead of the correct plot, only a default test image is posted to Slack and error messages are emitted by Grafana and the renderer.

**What you expected to happen**:

Images are always rendered correctly

**How to reproduce it (as minimally and precisely as possible)**:

Unfortunately, I couldn't find a way to reproduce this in a limited test case.

**Anything else we need to know?**:

The remote rendering container is deployed using the method I have described [in this issue comment](https://github.com/helm/charts/issues/21959#issuecomment-640653320). Thus, renderer and grafana share the same network namespace and can communicate directly using `localhost`. No caching involved.

When rendering fails, the remote renderer emits the following log messages:

```
{"message":"::ffff:127.0.0.1 - - [18/Jun/2020:01:04:34 +0000] \"GET /render?deviceScaleFactor=1.000000&domain=localhost&encoding=&height=500&renderKey=U8TxLVDSM1M7VcWHEQi9WyNcdH8YjAXN&timeout=15&timezone=&url=http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2F09cVU_9Wk%2Fdatabase-consistency-alerting%3ForgId%3D1%26panelId%3D10%26render%3D1&width=1000 HTTP/1.1\" - - \"-\" \"Grafana/7.0.3\"\n","level":"debug"}
{"url":"/render?deviceScaleFactor=1.000000&domain=localhost&encoding=&height=500&renderKey=U8TxLVDSM1M7VcWHEQi9WyNcdH8YjAXN&timeout=15&timezone=&url=http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2F09cVU_9Wk%2Fdatabase-consistency-alerting%3ForgId%3D1%26panelId%3D10%26render%3D1&width=1000","stack":"Error: Request aborted\n    at onaborted (/usr/src/app/node_modules/express/lib/response.js:1025:15)\n    at Immediate._onImmediate (/usr/src/app/node_modules/express/lib/response.js:1067:9)\n    at processImmediate (internal/timers.js:456:21)","level":"error","message":"Request failed"}
TypeError: Cannot read property 'statusCode' of undefined
    at /usr/src/app/build/service/http-server.js:92:46
    at Layer.handle_error (/usr/src/app/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:315:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:127:14)
    at /usr/src/app/build/service/http-server.js:51:21
    at /usr/src/app/node_modules/express/lib/response.js:434:22
    at onaborted (/usr/src/app/node_modules/express/lib/response.js:1027:5)
{"url":"http://localhost:3000/d-solo/QOfuckAZk/api-events?orgId=1&panelId=10&render=1","level":"debug","message":"Render request received"}
{"file":"/tmp/f13be133.png","level":"debug","message":"Deleting temporary file"}
```

And Grafana reports the following:

```
t=2020-06-18T11:45:28+0000 lvl=eror msg="Failed to send request to remote rendering service." logger=rendering renderer=http error="Get \"htt
p://localhost:8081/render?deviceScaleFactor=1.000000&domain=localhost&encoding=&height=500&renderKey=2HUHoZbj07yWyaZF1RMt9tqRCz5EbUWI&timeout
=15&timezone=&url=http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2FL4WNBvtZz%2Flog-alerting%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000\": cont
ext deadline exceeded"
t=2020-06-18T11:45:28+0000 lvl=eror msg="Failed to render and upload alert panel image." logger=alerting.notifier ruleId=21 error="Failed to 
send request to remote rendering service. Get \"http://localhost:8081/render?deviceScaleFactor=1.000000&domain=localhost&encoding=&height=500
&renderKey=2HUHoZbj07yWyaZF1RMt9tqRCz5EbUWI&timeout=15&timezone=&url=http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2FL4WNBvtZz%2Flog-alerting%3ForgI
d%3D1%26panelId%3D2%26render%3D1&width=1000\": context deadline exceeded"
t=2020-06-18T11:45:28+0000 lvl=info msg="Executing slack notification" logger=alerting.notifier.slack ruleId=21 notification=devs
t=2020-06-18T11:45:28+0000 lvl=eror msg="Failed to get render key from cache" logger=rendering renderer=http error="cache item not found"
t=2020-06-18T11:45:28+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/alerts/states-for-das
hboard status=401 remote_addr=127.0.0.1 time_ms=0 size=32 referer="http://localhost:3000/d-solo/L4WNBvtZz/log-alerting?orgId=1&panelId=2&rend
er=1"
```

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: Prometheus + Victoria metrics
- OS Grafana is installed on: Docker container running inside EKS
- User OS & Browser: not relevant for remote rendering
- Grafana plugins: 
![image](https://user-images.githubusercontent.com/1336287/85136652-38463e00-b240-11ea-8319-052eee87f26e.png)

- Others:

**Comment by torkelo** [comment]
Is it completely random? What graph are you trying to render? how long does the query take ?

**Comment by languitar** [comment]
I couldn't spot a pattern so far :/

**Comment by languitar** [comment]
Maybe this is of interest: we use Victoria Metrics as the backend. However, this was already the case when we were still on Grafana 6 and there rendering worked without any issues.

**Comment by languitar** [comment]
I just had a look at the reported error messages and can confirm that various plots on different dashboards are affected:
```
❯ cat ~/Downloads/log.err | sed 's/.*\(http.*\)/\1/' | cut -d "\\" -f 1 | sort
http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2F09cVU_9Wk%2Fdatabase-consistency-alerting%3ForgId%3D1%26panelId%3D10%26render%3D1&width=1000
http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2F09cVU_9Wk%2Fdatabase-consistency-alerting%3ForgId%3D1%26panelId%3D10%26render%3D1&width=1000
http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2F09cVU_9Wk%2Fdatabase-consistency-alerting%3ForgId%3D1%26panelId%3D10%26render%3D1&width=1000
http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2F09cVU_9Wk%2Fdatabase-consistency-alerting%3ForgId%3D1%26panelId%3D10%26render%3D1&width=1000
http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2F09cVU_9Wk%2Fdatabase-consistency-alerting%3ForgId%3D1%26panelId%3D11%26render%3D1&width=1000
http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2F09cVU_9Wk%2Fdatabase-consistency-alerting%3ForgId%3D1%26panelId%3D11%26render%3D1&width=1000
http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2F7bOegv2Zz%2Fairflow%3ForgId%3D1%26panelId%3D4%26render%3D1&width=1000
http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2F7bOegv2Zz%2Fairflow%3ForgId%3D1%26panelId%3D4%26render%3D1&width=1000
http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2FCkNLSPrZz%2Fgdprlog-service%3ForgId%3D1%26panelId%3D4%26render%3D1&width=1000
http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2FCkNLSPrZz%2Fgdprlog-service%3ForgId%3D1%26panelId%3D4%26render%3D1&width=1000
http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2FL4WNBvtZz%2Flog-alerting%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000
http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2FL4WNBvtZz%2Flog-alerting%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000
http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2FL4WNBvtZz%2Flog-alerting%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000
http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2FL4WNBvtZz%2Flog-alerting%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000
http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2FL4WNBvtZz%2Flog-alerting%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000
http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2FL4WNBvtZz%2Flog-alerting%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000
http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2FL4WNBvtZz%2Flog-alerting%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000
http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2FL4WNBvtZz%2Flog-alerting%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000
http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2FL4WNBvtZz%2Flog-alerting%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000
http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2FL4WNBvtZz%2Flog-alerting%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000
http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2FL4WNBvtZz%2Flog-alerting%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000
http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2FL4WNBvtZz%2Flog-alerting%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000
http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2FL4WNBvtZz%2Flog-alerting%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000
http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2FL4WNBvtZz%2Flog-alerting%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000
http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2FQOfuckAZk%2Fapi-events%3ForgId%3D1%26panelId%3D10%26render%3D1&width=1000
http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2FQOfuckAZk%2Fapi-events%3ForgId%3D1%26panelId%3D10%26render%3D1&width=1000
http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2FQOfuckAZk%2Fapi-events%3ForgId%3D1%26panelId%3D10%26render%3D1&width=1000
http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2FQOfuckAZk%2Fapi-events%3ForgId%3D1%26panelId%3D10%26render%3D1&width=1000
```

**Comment by arjunnayak** [comment]
We're getting a similar error with Grafana v7 and image-renderer:latest running as docker containers in a k8s pod. Hitting the image render url in the browser works, but fails via curl. 
Curl:
`curl --http2 -v -H "Authorization: Bearer <API_KEY>" --silent -o image.png https://grafana.my.url/render/d-solo/4Uf2RVgZzA/overview?orgId=1&refresh=30s&from=1593547285834&to=1593558085834&panelId=3&width=1000&height=500&tz=America%2FLos_Angeles`

Resulting logs from the containers:
`renderer {"url":"/render?deviceScaleFactor=1.000000&domain=localhost&encoding=&height=400&renderKey=7D19N8pAxkj0a7A5l9u2sxkjVlmR97Ge&timeout=60&timezone=&url=http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2F4Uf2RVgZzA%2Fapi-gateway-overview%3ForgId%3D1%26render%3D1&width=800","stack":"TimeoutError: waiting for function failed: timeout 60000ms exceeded\n    at new WaitTask (/usr/src/app/node_modules/puppeteer/lib/DOMWorld.js:549:28)\n    at DOMWorld.waitForFunction (/usr/src/app/node_modules/puppeteer/lib/DOMWorld.js:454:12)\n    at Frame.waitForFunction (/usr/src/app/node_modules/puppeteer/lib/FrameManager.js:657:28)\n    at Page.waitForFunction (/usr/src/app/node_modules/puppeteer/lib/Page.js:1144:29)\n    at Browser.<anonymous> (/usr/src/app/build/browser/browser.js:174:24)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/build/browser/browser.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","level":"error","message":"Requestfailed"}

grafana t=2020-07-01T00:08:39+0000 lvl=eror msg="Failed to send request to remote rendering service." logger=rendering renderer=http error="Get \"http://localhost:8081/render?deviceScaleFactor=1.000000&domain=localhost&encoding=&height=400&renderKey=bikU7J4IfyIJrPbHsPFDM4zUMKOLY637&timeout=60&timezone=&url=http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2F4Uf2RVgZzA%2Fapi-gateway-overview%3ForgId%3D1%26render%3D1&width=800\": context deadline exceeded"

grafana t=2020-07-01T00:08:39+0000 lvl=eror msg="Rendering failed." logger=context userId=0 orgId=1 uname= error="Failed to send request to remote rendering service. Get \"http://localhost:8081/render?deviceScaleFactor=1.000000&domain=localhost&encoding=&height=400&renderKey=bikU7J4IfyIJrPbHsPFDM4zUMKOLY637&timeout=60&timezone=&url=http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2F4Uf2RVgZzA%2Fapi-gateway-overview%3ForgId%3D1%26render%3D1&width=800\": context deadline exceeded"

grafana t=2020-07-01T00:08:39+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/render/d-solo/4Uf2RVgZzA/api-gateway-overview status=500 remote_addr=10.0.14.97 time_ms=62027 size=1723 referer=`
