### ISSUE TITLE
Nightly build titles panel seem to be broken

### ISSUE THREAD

**Issue by timgriffiths** [grafana/grafana#2733]
Interested in trying out a few of the new features in 2.5 so i pulled down the nightly build, but i noticing all the panel titles have gone astray 

![image](https://cloud.githubusercontent.com/assets/4284863/9839093/1d2d17a0-5ab2-11e5-9da0-257538e7d222.png)

![image](https://cloud.githubusercontent.com/assets/4284863/9839095/31e8400c-5ab2-11e5-80f0-949542301d8f.png)

Also see this error when looking in the chrome dev tools
```
Error: [$injector:unpr] Unknown provider: aProvider <- a <- interpolateTemplateVarsFilter
http://errors.angularjs.org/1.4.3/$injector/unpr?p0=aProvider%20%3C-%20a%20%3C-NaNnterpolateTemplateVarsFilter
    at http://grafana-hk.tibra.com/app/app.415e973a.js:9:5834
    at http://grafana-hk.tibra.com/app/app.415e973a.js:9:25174
    at Object.d [as get] (http://grafana-hk.tibra.com/app/app.415e973a.js:9:24344)
    at http://grafana-hk.tibra.com/app/app.415e973a.js:9:25271
    at d (http://grafana-hk.tibra.com/app/app.415e973a.js:9:24344)
    at Object.e [as invoke] (http://grafana-hk.tibra.com/app/app.415e973a.js:9:24681)
    at Object.$get (http://grafana-hk.tibra.com/app/app.415e973a.js:9:23151)
    at Object.e [as invoke] (http://grafana-hk.tibra.com/app/app.415e973a.js:9:24714)
    at http://grafana-hk.tibra.com/app/app.415e973a.js:9:25291
    at Object.d [as get] (http://grafana-hk.tibra.com/app/app.415e973a.js:9:24344)
```
Using  Version: 2.5.0-pre1, Commit: v2.1.2+321-g8174b9f, Build date: 2015-09-11 16:58:45 +1000 AEST

**Comment by zenixLR** [comment]
Same thing for me..
Tried to build a docker image with the 2.5-pre1 and got the same unparsed panels as timgriffiths.
