### ISSUE TITLE
Panel Title and Time is not shown

### ISSUE THREAD

**Issue by tegge** [grafana/grafana#2800]
Hello,

i installed version 2.5.0.pre1 and got a visual failure in displaying panel-template Vars for Panel-Title and Time.
Dev-Tools says:
{code}
Error: [$injector:unpr] Unknown provider: aProvider <- a <- interpolateTemplateVarsFilter
http://errors.angularjs.org/1.4.3/$injector/unpr?p0=aProvider%20%3C-%20a%20%3C-NaNnterpolateTemplateVarsFilter
    at http://grafana-test:3000/app/app.415e973a.js:9:5834
    at http://grafana-test:3000/app/app.415e973a.js:9:25174
    at Object.d [as get] (http://grafana-test:3000/app/app.415e973a.js:9:24344)
    at http://grafana-test:3000/app/app.415e973a.js:9:25271
    at d (http://grafana-test:3000/app/app.415e973a.js:9:24344)
    at Object.e [as invoke] (http://grafana-test:3000/app/app.415e973a.js:9:24681)
    at Object.$get (http://grafana-test:3000/app/app.415e973a.js:9:23151)
    at Object.e [as invoke] (http://grafana-test:3000/app/app.415e973a.js:9:24714)
    at http://grafana-test:3000/app/app.415e973a.js:9:25291
    at Object.d [as get] (http://grafana-test:3000/app/app.415e973a.js:9:24344)
{code}
![grafana-bug](https://cloud.githubusercontent.com/assets/4160790/10018543/fc352d44-6137-11e5-87db-6675661a778f.png)

**Comment by torkelo** [comment]
whats the build date / commit for the version you are running?

**Comment by tegge** [comment]
"latest" from Fr 11 Sep 2015 13:31:09 CEST amd64

**Comment by torkelo** [comment]
can you try a newer build?

**Comment by tegge** [comment]
Trayed the Build Grafana version: 2.5.0-pre1, commit: v2.1.2+420-gf632b3b, build date: 2015-09-22 14:29:41

No Problem anymore.
