### ISSUE TITLE
yarn dev fails using yarn version 2

### ISSUE THREAD

**Issue by a5hk** [grafana/grafana#28169]
**What happened**: 
I was trying to create a new plugin following [this](https://grafana.com/tutorials/build-a-panel-plugin/#3) tutorial and [this ](https://yarnpkg.com/getting-started/install) one to install yarn. But it throws an error when I enter `yarn dev`. 

**What you expected to happen**: 
To build the plugin without errors.

**How to reproduce it (as minimally and precisely as possible)**: 
Follow [panel plugin](https://grafana.com/tutorials/build-a-panel-plugin/#3) tutorial but before `yarn install` issue this command from yarn installation manual: `yarn set version berry` then continue with plugin tutorial. There is no errors if I don't use `yarn set version berry`, just some warning when executing `yarn install`.

**Anything else we need to know?**:
**yarn version 2 logs**:
`yarn dev` log:
```
⠋ Linting  Trace: Error: Failed to load config "prettier" to extend from.
  Referenced from: /home/ash/projects/grafana-plugins/my-plugin/.yarn/$$virtual/eslint-plugin-prettier-virtual-afd8534cb2/0/cache/eslint-plugin-prettier-npm-3.1.4-eba11cd45a-4e4df15579.zip/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js
      at configMissingError (/home/ash/projects/grafana-plugins/my-plugin/.yarn/cache/eslint-npm-7.4.0-3e08abf7a8-ef144e684c.zip/node_modules/eslint/lib/cli-engine/config-array-factory.js:282:9)
      at ConfigArrayFactory._loadExtendedShareableConfig (/home/ash/projects/grafana-plugins/my-plugin/.yarn/cache/eslint-npm-7.4.0-3e08abf7a8-ef144e684c.zip/node_modules/eslint/lib/cli-engine/config-array-factory.js:858:23)
      at ConfigArrayFactory._loadExtends (/home/ash/projects/grafana-plugins/my-plugin/.yarn/cache/eslint-npm-7.4.0-3e08abf7a8-ef144e684c.zip/node_modules/eslint/lib/cli-engine/config-array-factory.js:763:25)
      at ConfigArrayFactory._normalizeObjectConfigDataBody (/home/ash/projects/grafana-plugins/my-plugin/.yarn/cache/eslint-npm-7.4.0-3e08abf7a8-ef144e684c.zip/node_modules/eslint/lib/cli-engine/config-array-factory.js:702:25)
      at _normalizeObjectConfigDataBody.next (<anonymous>)
      at ConfigArrayFactory._normalizeObjectConfigData (/home/ash/projects/grafana-plugins/my-plugin/.yarn/cache/eslint-npm-7.4.0-3e08abf7a8-ef144e684c.zip/node_modules/eslint/lib/cli-engine/config-array-factory.js:647:20)
      at _normalizeObjectConfigData.next (<anonymous>)
      at ConfigArrayFactory._normalizeObjectConfigDataBody (/home/ash/projects/grafana-plugins/my-plugin/.yarn/cache/eslint-npm-7.4.0-3e08abf7a8-ef144e684c.zip/node_modules/eslint/lib/cli-engine/config-array-factory.js:702:25)
      at _normalizeObjectConfigDataBody.next (<anonymous>)
      at ConfigArrayFactory._normalizeObjectConfigData (/home/ash/projects/grafana-plugins/my-plugin/.yarn/cache/eslint-npm-7.4.0-3e08abf7a8-ef144e684c.zip/node_modules/eslint/lib/cli-engine/config-array-factory.js:647:20)
      at _normalizeObjectConfigData.next (<anonymous>)
      at ConfigArrayFactory._normalizeObjectConfigDataBody (/home/ash/projects/grafana-plugins/my-plugin/.yarn/cache/eslint-npm-7.4.0-3e08abf7a8-ef144e684c.zip/node_modules/eslint/lib/cli-engine/config-array-factory.js:702:25)
      at _normalizeObjectConfigDataBody.next (<anonymous>)
      at ConfigArrayFactory._normalizeObjectConfigData (/home/ash/projects/grafana-plugins/my-plugin/.yarn/cache/eslint-npm-7.4.0-3e08abf7a8-ef144e684c.zip/node_modules/eslint/lib/cli-engine/config-array-factory.js:647:20)
      at _normalizeObjectConfigData.next (<anonymous>)
      at ConfigArrayFactory.loadFile (/home/ash/projects/grafana-plugins/my-plugin/.yarn/cache/eslint-npm-7.4.0-3e08abf7a8-ef144e684c.zip/node_modules/eslint/lib/cli-engine/config-array-factory.js:459:16) {
    messageTemplate: 'extend-config-missing',
    messageData: {
      configName: 'prettier',
      importerName: '/home/ash/projects/grafana-plugins/my-plugin/.yarn/$$virtual/eslint-plugin-prettier-virtual-afd8534cb2/0/cache/eslint-plugin-prettier-npm-3.1.4-eba11cd45a-4e4df15579.zip/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js'
    }
  }
      at /home/ash/projects/grafana-plugins/my-plugin/.yarn/cache/@grafana-toolkit-npm-7.2.0-61cee481c8-0f4aa8f6bc.zip/node_modules/@grafana/toolkit/src/cli/utils/useSpinner.js:25:29
      at step (/home/ash/projects/grafana-plugins/my-plugin/.yarn/cache/tslib-npm-1.10.0-9261539b46-d03db5b8d2.zip/node_modules/tslib/tslib.js:136:27)
      at Object.throw (/home/ash/projects/grafana-plugins/my-plugin/.yarn/cache/tslib-npm-1.10.0-9261539b46-d03db5b8d2.zip/node_modules/tslib/tslib.js:117:57)
      at rejected (/home/ash/projects/grafana-plugins/my-plugin/.yarn/cache/tslib-npm-1.10.0-9261539b46-d03db5b8d2.zip/node_modules/tslib/tslib.js:108:69)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
✖ Failed to load config "prettier" to extend from.
Referenced from: /home/ash/projects/grafana-plugins/my-plugin/.yarn/$$virtual/eslint-plugin-prettier-virtual-afd8534cb2/0/cache/eslint-plugin-prettier-npm-3.1.4-eba11cd45a-4e4df15579.zip/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js
```

`yarn install` log:
```
➤ YN0000: ┌ Resolution step
➤ YN0061: │ @types/jest-diff@npm:24.3.0 is deprecated: This is a stub types definition. jest-diff provides its own type definitions, so you do not need this installed.
➤ YN0061: │ mkdirp@npm:0.5.1 is deprecated: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
➤ YN0061: │ chokidar@npm:2.1.8 is deprecated: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
➤ YN0061: │ request@npm:2.88.2 is deprecated: request has been deprecated, see https://github.com/request/request/issues/3142
➤ YN0061: │ request@npm:2.88.2 is deprecated: request has been deprecated, see https://github.com/request/request/issues/3142
➤ YN0061: │ memoize-one@npm:4.1.0 is deprecated: New custom equality api does not play well with all equality helpers. Please use v5.x
➤ YN0032: │ nan@npm:2.14.1: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ popper.js@npm:1.16.1 is deprecated: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
➤ YN0061: │ har-validator@npm:5.1.3 is deprecated: this library is no longer supported
➤ YN0061: │ fsevents@npm:1.2.13 is deprecated: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
➤ YN0061: │ fsevents@npm:1.2.13 is deprecated: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
➤ YN0032: │ fsevents@npm:2.1.3: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ core-js@npm:2.6.11 is deprecated: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
➤ YN0061: │ core-js@npm:1.2.7 is deprecated: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
➤ YN0032: │ fsevents@npm:2.1.3: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ urix@npm:0.1.0 is deprecated: Please see https://github.com/lydell/urix#deprecated
➤ YN0061: │ resolve-url@npm:0.2.1 is deprecated: https://github.com/lydell/resolve-url#deprecated
➤ YN0061: │ left-pad@npm:1.3.0 is deprecated: use String.prototype.padStart()
➤ YN0032: │ evp_bytestokey@npm:1.0.3: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ request-promise-native@npm:1.0.8 is deprecated: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
➤ YN0002: │ rc-trigger@npm:2.6.5 doesn't provide react-dom@^15.0.0 || ^16.0.0 requested by rc-animate@npm:2.11.1
➤ YN0002: │ rc-trigger@npm:2.6.5 doesn't provide react@^15.0.0 || ^16.0.0 requested by rc-animate@npm:2.11.1
➤ YN0002: │ @grafana/slate-react@npm:0.22.9-grafana [a192d] doesn't provide slate-react@>=0.22.0 requested by slate-react-placeholder@npm:0.2.9
➤ YN0002: │ rc-trigger@npm:4.4.3 doesn't provide react-dom@* requested by rc-align@npm:4.0.8
➤ YN0002: │ rc-trigger@npm:4.4.3 doesn't provide react@* requested by rc-align@npm:4.0.8
➤ YN0002: │ rc-trigger@npm:4.4.3 doesn't provide react-dom@^16.0.0 requested by rc-motion@npm:1.1.2
➤ YN0002: │ rc-trigger@npm:4.4.3 doesn't provide react@^16.0.0 requested by rc-motion@npm:1.1.2
➤ YN0002: │ react-dev-utils@npm:10.2.1 doesn't provide typescript@>= 2.7 requested by fork-ts-checker-webpack-plugin@npm:3.1.1
➤ YN0002: │ react-dev-utils@npm:10.2.1 doesn't provide webpack@>= 4 requested by fork-ts-checker-webpack-plugin@npm:3.1.1
➤ YN0060: │ @grafana/toolkit@npm:7.2.0 provides prettier@npm:1.19.1 with version 1.19.1 which doesn't satisfy ^2.0.5 requested by @grafana/eslint-config@npm:2.0.0
➤ YN0060: │ @grafana/toolkit@npm:7.2.0 provides typescript@patch:typescript@npm%3A3.9.3#builtin<compat/typescript>::version=3.9.3&hash=5bf698 with version 3.9.3 which doesn't satisfy ^3.9.6 requested by @grafana/eslint-config@npm:2.0.0
➤ YN0000: └ Completed in 2m 6s
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yargs@npm:13.3.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:15.3.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:3.10.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yauzl@npm:2.10.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yn@npm:3.1.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 27s 855ms
➤ YN0000: ┌ Link step
➤ YN0062: │ fsevents@patch:fsevents@npm%3A1.2.13#builtin<compat/fsevents>::version=1.2.13&hash=127e8e The platform linux is incompatible with this module, building skipped.
➤ YN0062: │ fsevents@patch:fsevents@npm%3A2.1.3#builtin<compat/fsevents>::version=2.1.3&hash=127e8e The platform linux is incompatible with this module, building skipped.
➤ YN0007: │ core-js@npm:2.6.11 must be built because it never did before or the last one failed
➤ YN0007: │ node-sass@npm:4.14.1 must be built because it never did before or the last one failed
➤ YN0007: │ puppeteer-core@npm:1.18.1 must be built because it never did before or the last one failed
➤ YN0000: └ Completed in 11s 618ms
➤ YN0000: Done with warnings in 2m 46s
```

**yarn version 1 logs**:
`yarn install` log:
```
yarn install v1.22.10
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning Pattern ["@grafana/data@next"] is trying to unpack in the same destination "/home/ash/.cache/yarn/v6/npm-@grafana-data-7.2.0-29ae47a1c8a331d12fa269ef900922ade829c0aa-integrity/node_modules/@grafana/data" as pattern ["@grafana/data@^7.0.0","@grafana/data@7.2.0"]. This could result in non-deterministic behavior, skipping.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "@grafana/toolkit > @grafana/eslint-config@2.0.0" has incorrect peer dependency "prettier@^2.0.5".
warning "@grafana/toolkit > @grafana/eslint-config@2.0.0" has incorrect peer dependency "typescript@^3.9.6".
warning "@grafana/toolkit > @grafana/ui > @grafana/slate-react > slate-react-placeholder@0.2.9" has unmet peer dependency "slate-react@>=0.22.0".
[5/5] Building fresh packages...
Done in 353.21s.
```

**Environment**:
* Grafana version: 7.2.1
* OS Grafana is installed on:  Ubuntu 20.04.1 LTS
* Others:
  - Nodejs: v12.19.0
  - yarn: 2.3.2

**Comment by aknuds1** [comment]
I don't think this is a bug since you're diverging from the instructions in the tutorial (by upgrading to yarn v2).

**Comment by a5hk** [comment]
Fair. But I think yarn version should also be mentioned in the tutorial like nodejs and grafana versions.

**Comment by aknuds1** [comment]
@a5hk I don't really agree, since you explicitly diverged from the tutorial instructions (yarn v2 requires you to enable it on the project, as you did).
