### ISSUE TITLE
ModuleNotFoundError: Module not found: Error: Can't resolve 'vendor/angular-other/angular-strap'

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#28163]
Running `make` on master https://github.com/grafana/grafana/commit/f393e66a5a6a3cba1b52ba1f85abb18ec1657ee4 gives:

```
  ModuleNotFoundError: Module not found: Error: Can't resolve 'vendor/angular-other/angular-strap' in '/Users/user/Work/grafana/public/app'
      at /Users/user/Work/grafana/node_modules/webpack/lib/Compilation.js:925:10
      at /Users/user/Work/grafana/node_modules/webpack/lib/NormalModuleFactory.js:401:22
      at /Users/user/Work/grafana/node_modules/webpack/lib/NormalModuleFactory.js:130:21
      at /Users/user/Work/grafana/node_modules/webpack/lib/NormalModuleFactory.js:224:22
      at /Users/user/Work/grafana/node_modules/neo-async/async.js:2830:7
      at /Users/user/Work/grafana/node_modules/neo-async/async.js:6877:13
      at /Users/user/Work/grafana/node_modules/webpack/lib/NormalModuleFactory.js:214:25
      at /Users/user/Work/grafana/node_modules/enhanced-resolve/lib/Resolver.js:213:14
      at /Users/user/Work/grafana/node_modules/enhanced-resolve/lib/Resolver.js:285:5
      at eval (eval at create (/Users/user/Work/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
      at /Users/user/Work/grafana/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
      at /Users/user/Work/grafana/node_modules/enhanced-resolve/lib/Resolver.js:285:5
      at eval (eval at create (/Users/user/Work/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
      at /Users/user/Work/grafana/node_modules/enhanced-resolve/lib/Resolver.js:285:5
      at eval (eval at create (/Users/user/Work/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
      at /Users/user/Work/grafana/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
      at /Users/user/Work/grafana/node_modules/enhanced-resolve/lib/Resolver.js:285:5
      at eval (eval at create (/Users/user/Work/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
      at /Users/user/Work/grafana/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:30:40
      at /Users/user/Work/grafana/node_modules/enhanced-resolve/lib/Resolver.js:285:5
      at eval (eval at create (/Users/user/Work/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
      at /Users/user/Work/grafana/node_modules/enhanced-resolve/lib/Resolver.js:285:5
      at eval (eval at create (/Users/user/Work/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
      at /Users/user/Work/grafana/node_modules/enhanced-resolve/lib/Resolver.js:285:5
      at eval (eval at create (/Users/user/Work/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
      at /Users/user/Work/grafana/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
      at /Users/user/Work/grafana/node_modules/enhanced-resolve/lib/Resolver.js:285:5
      at eval (eval at create (/Users/user/Work/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
      at /Users/user/Work/grafana/node_modules/enhanced-resolve/lib/Resolver.js:285:5
      at eval (eval at create (/Users/user/Work/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
      at /Users/user/Work/grafana/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
      at /Users/user/Work/grafana/node_modules/enhanced-resolve/lib/Resolver.js:285:5
      at eval (eval at create (/Users/user/Work/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
      at /Users/user/Work/grafana/node_modules/enhanced-resolve/lib/Resolver.js:285:5
      at eval (eval at create (/Users/user/Work/grafana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
      at /Users/user/Work/grafana/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
  resolve 'vendor/angular-other/angular-strap' in '/Users/user/Work/grafana/public/app'
    Parsed request is a module
    using description file: /Users/user/Work/grafana/package.json (relative path: ./public/app)
      Field 'browser' doesn't contain a valid alias configuration
      resolve as module
        /Users/user/Work/grafana/public/app/node_modules doesn't exist or is not a directory
        /Users/user/Work/grafana/public/node_modules doesn't exist or is not a directory
        /Users/user/Work/node_modules doesn't exist or is not a directory
        /Users/user/node_modules doesn't exist or is not a directory
        /Users/node_modules doesn't exist or is not a directory
        /node_modules doesn't exist or is not a directory
        looking for modules in /Users/user/Work/grafana/node_modules
          using description file: /Users/user/Work/grafana/package.json (relative path: ./node_modules)
            Field 'browser' doesn't contain a valid alias configuration
            using description file: /Users/user/Work/grafana/package.json (relative path: ./node_modules/vendor/angular-other/angular-strap)
              no extension
                Field 'browser' doesn't contain a valid alias configuration
                /Users/user/Work/grafana/node_modules/vendor/angular-other/angular-strap doesn't exist
              .ts
                Field 'browser' doesn't contain a valid alias configuration
                /Users/user/Work/grafana/node_modules/vendor/angular-other/angular-strap.ts doesn't exist
              .tsx
                Field 'browser' doesn't contain a valid alias configuration
                /Users/user/Work/grafana/node_modules/vendor/angular-other/angular-strap.tsx doesn't exist
              .es6
                Field 'browser' doesn't contain a valid alias configuration
                /Users/user/Work/grafana/node_modules/vendor/angular-other/angular-strap.es6 doesn't exist
              .js
                Field 'browser' doesn't contain a valid alias configuration
                /Users/user/Work/grafana/node_modules/vendor/angular-other/angular-strap.js doesn't exist
              .json
                Field 'browser' doesn't contain a valid alias configuration
                /Users/user/Work/grafana/node_modules/vendor/angular-other/angular-strap.json doesn't exist
              .svg
                Field 'browser' doesn't contain a valid alias configuration
                /Users/user/Work/grafana/node_modules/vendor/angular-other/angular-strap.svg doesn't exist
              as directory
                /Users/user/Work/grafana/node_modules/vendor/angular-other/angular-strap doesn't exist
        looking for modules in /Users/user/Work/grafana/public
          using description file: /Users/user/Work/grafana/package.json (relative path: ./public)
            Field 'browser' doesn't contain a valid alias configuration
            using description file: /Users/user/Work/grafana/package.json (relative path: ./public/vendor/angular-other/angular-strap)
              no extension
                Field 'browser' doesn't contain a valid alias configuration
                /Users/user/Work/grafana/public/vendor/angular-other/angular-strap doesn't exist
              .ts
                Field 'browser' doesn't contain a valid alias configuration
                /Users/user/Work/grafana/public/vendor/angular-other/angular-strap.ts doesn't exist
              .tsx
                Field 'browser' doesn't contain a valid alias configuration
                /Users/user/Work/grafana/public/vendor/angular-other/angular-strap.tsx doesn't exist
              .es6
                Field 'browser' doesn't contain a valid alias configuration
                /Users/user/Work/grafana/public/vendor/angular-other/angular-strap.es6 doesn't exist
              .js
                Field 'browser' doesn't contain a valid alias configuration
                /Users/user/Work/grafana/public/vendor/angular-other/angular-strap.js doesn't exist
              .json
                Field 'browser' doesn't contain a valid alias configuration
                /Users/user/Work/grafana/public/vendor/angular-other/angular-strap.json doesn't exist
              .svg
                Field 'browser' doesn't contain a valid alias configuration
                /Users/user/Work/grafana/public/vendor/angular-other/angular-strap.svg doesn't exist
              as directory
               >> Exited with code: 1.
```

any idea what might it be?

**Comment by simPod** [comment]
invalid

**Comment by ramondepieri** [comment]
I was facing the same issue, and worst. That looked like a random issue, because sometimes the build pass and others the build fail. I don´t understand the reason, but you need to have the "public/vendor" folder and all the files in your public folder. Sometimes this files are auto generated, others not. So I copied these files from some installation that I had, past in my repository, remove the "vendor" from .gitignore and commit all "public/vendor" files. This solved the problem
