### ISSUE TITLE
@grafanatoolkit sign error

### ISSUE THREAD

**Issue by algenty** [grafana/grafana#28940]
Hi @dprokop 
I have an error when i try to sign plugin flowcharting, an idea ?

arnaud@lubuntu:~/workspaces/grafana-flowcharting$ ./sign.sh 
  Building manifest...
  TypeError: fs_1.default.promises.opendir is not a function
      at /home/arnaud/.npm/_npx/7728/lib/node_modules/@grafana/toolkit/src/plugins/manifest.js:17:80
      at step (/home/arnaud/.npm/_npx/7728/lib/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:140:27)
      at Object.next (/home/arnaud/.npm/_npx/7728/lib/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:121:57)
      at resume (/home/arnaud/.npm/_npx/7728/lib/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:210:48)
      at /home/arnaud/.npm/_npx/7728/lib/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:

My script : 
arnaud@lubuntu:~/workspaces/grafana-flowcharting$ cat sign.sh
export GRAFANA_API_KEY="$(cat key.txt)"
npx @grafana/toolkit plugin:sign

My package.json : 
  "devDependencies": {
    "@angular/core": "^10.2.1",
    "@babel/plugin-proposal-class-properties": "^7.3.4",
    "@grafana/data": "7.3.1",
    "@grafana/eslint-config": "1.0.0-rc1",
    "@grafana/runtime": "7.3.1",
    "@grafana/toolkit": "7.3.1",
    "@grafana/ui": "7.3.1",
...

**Comment by papagian** [comment]
which operating system are you using?

**Comment by algenty** [comment]
linux : ubuntu 20 
I'll try on windows WSL Ubuntu

**Comment by algenty** [comment]
Seems to work after update yarn and clean node-module : 
rm -rf node_modules
sudo apt-get update && sudo apt-get install yarn
yarn install

![image](https://user-images.githubusercontent.com/47012725/98586306-d0fd5900-22c8-11eb-9060-4381c8c46111.png)

Thx a lot

**Comment by algenty** [comment]
Correction : 
Works on WSL 1
Same error on ubuntu 20

**Comment by algenty** [comment]
Fixed, need nodejs 12 or more.
yarn install on ubuntu install only version
for information, The solution for next issues : 
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install -y nodejs

BR
Arnaud

**Comment by dkozar** [comment]
I just got the same error on Windows.

Tried to rebuild the modules, but it didn't help.

Any idea why this happens?

**Comment by DonatoD** [comment]
Hi ,any news on how to fix it on windows? I'm having the same problem. Thanks
