### ISSUE TITLE
email notifications hanging when connection times out

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#2989]
In the raintank/grafana server i was trying to debug why the alerting executors seemed to hang occasionally and not process new jobs.
I think the problem is also in grafana/grafana.
I saw this message in logs
```
2015/10/20 20:46:41 ESC[1;31m[asm_amd64.s:2232 goexit()] [E] Async sent email 0 succeed, not send emails:  err: dial tcp 104.130.177.23:25: connection timed outESC[0m
2015/10/20 20:46:41 ESC[1;36m[T] Sending mails to: ESC[0m

```
i got suspicious that the timeout might be way too long, so i did a full goroutine dump at https://gist.github.com/Dieterbe/77a5b82aa97ea0ce2cc5

I found 10 cases of notifications.go sendEmailCommandHandler's addToMailQueue not able to send to mailQueue because it's blocked from taking in new entries

```
dieter@dieter-m6800 ~ grep -B 2 'notifications/mailer.go:47' dump.txt 
goroutine 68 [chan send, 10 minutes]:
github.com/grafana/grafana/pkg/services/notifications.func·001(0xc20d20f260)
	/go/src/github.com/grafana/grafana/pkg/services/notifications/mailer.go:47 +0x4a
--
goroutine 69 [chan send, 6 minutes]:
github.com/grafana/grafana/pkg/services/notifications.func·001(0xc20d20e9c0)
	/go/src/github.com/grafana/grafana/pkg/services/notifications/mailer.go:47 +0x4a
--
goroutine 70 [chan send, 10 minutes]:
github.com/grafana/grafana/pkg/services/notifications.func·001(0xc20d0a9620)
	/go/src/github.com/grafana/grafana/pkg/services/notifications/mailer.go:47 +0x4a
--
goroutine 71 [chan send, 2 minutes]:
github.com/grafana/grafana/pkg/services/notifications.func·001(0xc208165c80)
	/go/src/github.com/grafana/grafana/pkg/services/notifications/mailer.go:47 +0x4a
--
goroutine 72 [chan send, 10 minutes]:
github.com/grafana/grafana/pkg/services/notifications.func·001(0xc20d0a58c0)
	/go/src/github.com/grafana/grafana/pkg/services/notifications/mailer.go:47 +0x4a
--
goroutine 73 [chan send, 8 minutes]:
github.com/grafana/grafana/pkg/services/notifications.func·001(0xc20d0a4000)
	/go/src/github.com/grafana/grafana/pkg/services/notifications/mailer.go:47 +0x4a
--
goroutine 74 [chan send, 4 minutes]:
github.com/grafana/grafana/pkg/services/notifications.func·001(0xc208b5c060)
	/go/src/github.com/grafana/grafana/pkg/services/notifications/mailer.go:47 +0x4a
--
goroutine 75 [chan send, 10 minutes]:
github.com/grafana/grafana/pkg/services/notifications.func·001(0xc20d18b9e0)
	/go/src/github.com/grafana/grafana/pkg/services/notifications/mailer.go:47 +0x4a
--
goroutine 76 [chan send]:
github.com/grafana/grafana/pkg/services/notifications.func·001(0xc20d0a5c20)
	/go/src/github.com/grafana/grafana/pkg/services/notifications/mailer.go:47 +0x4a
--
goroutine 77 [chan send, 10 minutes]:
github.com/grafana/grafana/pkg/services/notifications.func·001(0xc20d047c20)
	/go/src/github.com/grafana/grafana/pkg/services/notifications/mailer.go:47 +0x4a
```

goroutine 78 is blocked on iowait for `conn, err := net.Dial("tcp", net.JoinHostPort(host, port))` for about 1 minute.
the mailQueue has a buffer of 10 but mails are only being processed sequentially so anything that hangs even for a bit will cause a backlog of email messages.

so we would need to do some concurrent email handling or at the very least cache the connection state. if we tried to connect for a minute not too long ago, it's most likely the connection will fail again. maybe use a background worker that tries re-establish connections

**Comment by torkelo** [comment]
added 10 second timeout to smpt dial

**Comment by Dieterbe** [comment]
And the rest is the same still ? Then it will still have same problem

**Comment by torkelo** [comment]
oh, thought you said it was due to too high timeout

**Comment by torkelo** [comment]
Anyway, afraid fixes here does not affect Worldping alerting anymore as the codebases are separate now
