### ISSUE TITLE
Image Render Does Not Work in docker-compose.yml

### ISSUE THREAD

**Issue by DennisFaucher** [grafana/grafana#30803]
**What happened**: Using docker-compose.yml for grafana and renderer, alert email was sent without image of dashboard. Errors on console are:

grafana_1   | t=2021-02-01T22:35:01+0000 lvl=info msg=Rendering logger=rendering renderer=http path="d-solo/3PHh-bLGk/test-dashboard?orgId=1&panelId=2"
grafana_1   | t=2021-02-01T22:35:01+0000 lvl=dbug msg="calling remote rendering service" logger=rendering renderer=http url="http://renderer:8081/render?deviceScaleFactor=1.000000&domain=grafana&encoding=&height=500&renderKey=AxD0pyoT0b1K4XGLlVIe1j2RbMY6sMP6&timeout=15&timezone=&url=http%3A%2F%2Fgrafana%3A3000%2Fd-solo%2F3PHh-bLGk%2Ftest-dashboard%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000"
grafana_1   | t=2021-02-01T22:35:16+0000 lvl=eror msg="Failed to send request to remote rendering service." logger=rendering renderer=http error="Get \"http://renderer:8081/render?deviceScaleFactor=1.000000&domain=grafana&encoding=&height=500&renderKey=AxD0pyoT0b1K4XGLlVIe1j2RbMY6sMP6&timeout=15&timezone=&url=http%3A%2F%2Fgrafana%3A3000%2Fd-solo%2F3PHh-bLGk%2Ftest-dashboard%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000\": context deadline exceeded"
grafana_1   | t=2021-02-01T22:35:16+0000 lvl=eror msg="Failed to render and upload alert panel image." logger=alerting.notifier ruleId=1 error="failed to send request to remote rendering service: Get \"http://renderer:8081/render?deviceScaleFactor=1.000000&domain=grafana&encoding=&height=500&renderKey=AxD0pyoT0b1K4XGLlVIe1j2RbMY6sMP6&timeout=15&timezone=&url=http%3A%2F%2Fgrafana%3A3000%2Fd-solo%2F3PHh-bLGk%2Ftest-dashboard%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000\": context deadline exceeded"
grafana_1   | t=2021-02-01T22:35:16+0000 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[dennis@faucher.net] singleEmail=false
grafana_1   | t=2021-02-01T22:35:22+0000 lvl=eror msg="Failed to get render key from cache" logger=rendering renderer=http error="cache item not found"
grafana_1   | t=2021-02-01T22:35:22+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/d-solo/3PHh-bLGk/test-dashboard status=401 remote_addr=172.20.0.2 time_ms=0 size=32 referer=
renderer_1  | {"msg":"Failed to load resource: the server responded with a status of 401 (Unauthorized)","url":"http://grafana:3000/d-solo/3PHh-bLGk/test-dashboard?orgId=1&panelId=2&render=1","level":"error","message":"Browser console error"}
renderer_1  | {"url":"/render?deviceScaleFactor=1.000000&domain=grafana&encoding=&height=500&renderKey=AxD0pyoT0b1K4XGLlVIe1j2RbMY6sMP6&timeout=15&timezone=&url=http%3A%2F%2Fgrafana%3A3000%2Fd-solo%2F3PHh-bLGk%2Ftest-dashboard%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000","stack":"TimeoutError: waiting for function failed: timeout 15000ms exceeded\n    at new WaitTask (/usr/src/app/node_modules/puppeteer/lib/DOMWorld.js:549:28)\n    at DOMWorld.waitForFunction (/usr/src/app/node_modules/puppeteer/lib/DOMWorld.js:454:12)\n    at Frame.waitForFunction (/usr/src/app/node_modules/puppeteer/lib/FrameManager.js:657:28)\n    at Page.waitForFunction (/usr/src/app/node_modules/puppeteer/lib/Page.js:1144:29)\n    at Browser.<anonymous> (/usr/src/app/build/browser/browser.js:174:24)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/build/browser/browser.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","level":"error","message":"Request failed"}

**What you expected to happen**: Using docker-compose.yml for grafana and renderer, image of dashboard panel should be sent with alter email

**How to reproduce it (as minimally and precisely as possible)**:
Use the sample docker-compose.yml with an added line for editable grafana.ini for smtp

version: '2'

services:
  grafana:
    image: grafana/grafana:master
    ports:
     - "3000:3000"
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    volumes:
     - /root/image-render/grafana.ini:/etc/grafana/grafana.ini
  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by DennisFaucher** [comment]
[Edit] I edited grafana.ini to uncomment server_url & callback_url and now images are working.

server_url = http://localhost:8081/render
#server_url = http://localhost:49154/render
callback_url = http://localhost:3000/
