### ISSUE TITLE
Error when hiding query using Elasticsearch datasource

### ISSUE THREAD

**Issue by hulu1522** [grafana/grafana#3300]
When trying to hide a query during some testing an error happens that cases the graph to fail until I enable it again.  I am new to Grafana so I might be missing something but it seems like a bug.  Thanks.

Error:
```
TypeError: Cannot read property 'then' of undefined
    at issueMetricQuery (http://10.129.21.200:3000/app/app.b4b243aa.js:34:8492)
    at n.a.refreshData (http://10.129.21.200:3000/app/app.b4b243aa.js:44:8044)
    at http://10.129.21.200:3000/app/app.b4b243aa.js:34:5867
    at i (http://10.129.21.200:3000/app/app.b4b243aa.js:13:3780)
    at http://10.129.21.200:3000/app/app.b4b243aa.js:13:3952
    at n.$eval (http://10.129.21.200:3000/app/app.b4b243aa.js:13:11572)
    at n.$digest (http://10.129.21.200:3000/app/app.b4b243aa.js:13:10003)
    at n.$apply (http://10.129.21.200:3000/app/app.b4b243aa.js:13:11839)
    at HTMLAnchorElement.<anonymous> (http://10.129.21.200:3000/app/app.b4b243aa.js:15:9885)
    at HTMLAnchorElement._.event.dispatch (http://10.129.21.200:3000/app/app.b4b243aa.js:7:2254)
```

Screenshot:
![grafana_-_logstash](https://cloud.githubusercontent.com/assets/8116850/11311798/4bd042c8-8f8f-11e5-9bd7-11f516b6204a.png)

**Comment by torkelo** [comment]
thanks for reporting this! fixed!
