### ISSUE TITLE
As code: Import/export with adding/removing default values causes errors

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#34509]
Please add any found issues here:

**Comment by axelavargas** [comment]
## **Trim/Apply feature toggle on Dashboard**

### **What happened:**

Importing a dashboard with `Export for sharing externally` and `Export with trimed dashboard json` enabled causes `unexpected Error` on the [testing](https://g80-beta.grafana.net/) environment 


### **What you expected to happen:**

A dashboard is imported correctly


### **How to reproduce it (as minimally and precisely as possible):**

#### In your local environment:

1.  In [feature_toggles] section in custom.ini, add enable = trimDefaults
2.  Go to a complex dashboard -> share -> export -> activate toggle “export with trimmed dashboard json”  and activate "Export for sharing externally" -> click on save to file.

#### On the [testing](https://g80-beta.grafana.net/) environment 

1. Click create -> import -> upload previous json file

**Note**
I also tested exporting without enabling the `Export with trimed dashboard json` and that one did not generate the error on the testing environment.

**Error Log**

```An unexpected error happened
DetailsTypeError: Cannot read property 'toString' of undefined

    at https://g80-beta.grafana.net/public/build/app.4f857895d25408eb0dd2.js:5669:3758
    at div
    at button
    at https://g80-beta.grafana.net/public/build/app.4f857895d25408eb0dd2.js:2027:331
    at i (https://g80-beta.grafana.net/public/build/app.4f857895d25408eb0dd2.js:5542:5562)
    at https://g80-beta.grafana.net/public/build/app.4f857895d25408eb0dd2.js:650:19506
    at div
    at https://g80-beta.grafana.net/public/build/app.4f857895d25408eb0dd2.js:2007:32119
    at b (https://g80-beta.grafana.net/public/build/app.4f857895d25408eb0dd2.js:5669:1831)
    at WithTheme(undefined)
    at o (https://g80-beta.grafana.net/public/build/app.4f857895d25408eb0dd2.js:5394:299)
    at l
    at div
    at h (https://g80-beta.grafana.net/public/build/app.4f857895d25408eb0dd2.js:5339:7252)
    at div
    at div
    at https://g80-beta.grafana.net/public/build/app.4f857895d25408eb0dd2.js:3223:1583
    at C (https://g80-beta.grafana.net/public/build/app.4f857895d25408eb0dd2.js:5017:506)
    at k (https://g80-beta.grafana.net/public/build/vendors~app.4f857895d25408eb0dd2.js:2:70367)
    at div
    at div
    at N (https://g80-beta.grafana.net/public/build/DashboardPage.4f857895d25408eb0dd2.js:450:655)
    at DashboardPage
    at k (https://g80-beta.grafana.net/public/build/vendors~app.4f857895d25408eb0dd2.js:2:70367)
    at n (https://g80-beta.grafana.net/public/build/vendors~app.4f857895d25408eb0dd2.js:2:461697)
    at K (https://g80-beta.grafana.net/public/build/app.4f857895d25408eb0dd2.js:719:3200)
    at t (https://g80-beta.grafana.net/public/build/vendors~app.4f857895d25408eb0dd2.js:2:1207127)
    at t (https://g80-beta.grafana.net/public/build/vendors~app.4f857895d25408eb0dd2.js:2:1209172)
    at div
    at t (https://g80-beta.grafana.net/public/build/vendors~app.4f857895d25408eb0dd2.js:2:1203732)
    at div
    at at (https://g80-beta.grafana.net/public/build/app.4f857895d25408eb0dd2.js:3223:1106)
    at h (https://g80-beta.grafana.net/public/build/app.4f857895d25408eb0dd2.js:5548:25681)
    at zi (https://g80-beta.grafana.net/public/build/app.4f857895d25408eb0dd2.js:3877:564)
    at Ii (https://g80-beta.grafana.net/public/build/app.4f857895d25408eb0dd2.js:3877:848)
    at l (https://g80-beta.grafana.net/public/build/vendors~app.4f857895d25408eb0dd2.js:2:68275)
    at be (https://g80-```

**Comment by ying-jeanne** [comment]
hi @axelavargas, could you share the dashboard JSON without trimmed,

**Comment by ying-jeanne** [comment]
the main branch seems working fine, the problem produced only on beta2.

**Comment by ying-jeanne** [comment]
the problem of trim/apply test comes from export trimmed dashboard, input it into a Grafana instance doesn't activate the trim defaults feature, then the import fails. we can consider it is as expected, since we don't apply the defaults when import in this case.
