### ISSUE TITLE
Errors starting Grafana after building for Mac OS X (el Capitan)

### ISSUE THREAD

**Issue by AlexIoannides** [grafana/grafana#3527]
Hello, 

I've followed the steps for building v2.6 from source, but when I try to execute the code I get the following errors:

```
AlexIoannidesMac:bin alexioannides$ ./grafana
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x41bbb2f]

goroutine 1 [running]:
github.com/grafana/grafana/pkg/setting.loadConfiguration(0xc20803ff80)
	/applications/grafana/src/github.com/grafana/grafana/pkg/setting/setting.go:312 +0x28f
github.com/grafana/grafana/pkg/setting.NewConfigContext(0xc20803ff80, 0x0, 0x0)
	/applications/grafana/src/github.com/grafana/grafana/pkg/setting/setting.go:394 +0x5f
main.initRuntime()
	/applications/grafana/src/github.com/grafana/grafana/main.go:86 +0x11e
main.main()
	/applications/grafana/src/github.com/grafana/grafana/main.go:61 +0x25a

goroutine 5 [select]:
github.com/grafana/grafana/pkg/log.(*Logger).StartLogger(0xc20803f9c0)
	/applications/grafana/src/github.com/grafana/grafana/pkg/log/log.go:227 +0x369
created by github.com/grafana/grafana/pkg/log.newLogger
	/applications/grafana/src/github.com/grafana/grafana/pkg/log/log.go:157 +0x13a

goroutine 6 [syscall]:
os/signal.loop()
	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:27 +0x35

goroutine 7 [select]:
main.listenToSystemSignels()
	/applications/grafana/src/github.com/grafana/grafana/main.go:126 +0x4dd
created by main.main
	/applications/grafana/src/github.com/grafana/grafana/main.go:57 +0x249
AlexIoannidesMac:bin alexioannides$ 
```

There were no errors in any of the build steps. I have no experience of Go, so no idea where to start.

Thanks,

Alex

**Comment by AlexIoannides** [comment]
My apologies - this errors only occurs when I try to run ./grafana from the $GOPATH/bin directory.

If I run from $GOPATH/src/grafana, then all is good.

If you have the time and inclination, I'm curious to know what's going on (but no worries if you don't).

**Comment by torkelo** [comment]
it is trying to find a config file <current working dir>/conf/defaults.ini , also the static content (public)
