### ISSUE TITLE
Table view crash using Azure datasource

### ISSUE THREAD

**Issue by gabrielmcf** [grafana/grafana#35999]
**What happened**:

Creating any Azure metric and switching the dashboard to "Table view" crashes Grafana. I have tested creating the metric first then switching the button and switching to table first and then creating the metric. Both ways the screen crashes as soon as the data is fetched.

**What you expected to happen**:

To show me the metrics in a table view.

**How to reproduce it (as minimally and precisely as possible)**:

- Create a new dashboard
- Choose an Azure datasource
- Create any metric and plot the chart
- Switch the "Table view" button on the top menu

**Anything else we need to know?**:

The logs printed on screen:

```
An unexpected error happened
DetailsTypeError: Cannot read property 'numeric' of undefined

    at wt (https://<REDACTED>/public/build/app.90f320b382a70cd0232d.js:3115:1756)
    at wn (https://<REDACTED>/public/build/app.90f320b382a70cd0232d.js:3285:18)
    at div
    at https://<REDACTED>/public/build/app.90f320b382a70cd0232d.js:3285:2656
    at div
    at div
    at t (https://<REDACTED>/public/build/vendors~app.90f320b382a70cd0232d.js:2:1875650)
    at div
    at div
    at div
    at t (https://<REDACTED>/public/build/vendors~app.90f320b382a70cd0232d.js:2:706836)
    at h (https://<REDACTED>/public/build/app.90f320b382a70cd0232d.js:5437:31539)
    at div
    at https://<REDACTED>/public/build/app.90f320b382a70cd0232d.js:3285:921
    at Vr (https://<REDACTED>/public/build/app.90f320b382a70cd0232d.js:2357:38225)
    at f (https://<REDACTED>/public/build/app.90f320b382a70cd0232d.js:1961:2262)
    at div
    at div
    at Da (https://<REDACTED>/public/build/app.90f320b382a70cd0232d.js:3376:133)
    at lr (https://<REDACTED>/public/build/DashboardPage.90f320b382a70cd0232d.js:354:715)
    at div
    at t (https://<REDACTED>/public/build/vendors~app.90f320b382a70cd0232d.js:2:1897376)
    at div
    at div
    at div
    at t (https://<REDACTED>/public/build/DashboardPage.90f320b382a70cd0232d.js:327:1554)
    at div
    at t (https://<REDACTED>/public/build/DashboardPage.90f320b382a70cd0232d.js:327:3507)
    at div
    at t (https://<REDACTED>/public/build/DashboardPage.90f320b382a70cd0232d.js:327:1554)
    at div
    at t (https://<REDACTED>/public/build/DashboardPage.90f320b382a70cd0232d.js:327:3507)
    at Vn (https://<REDACTED>/public/build/DashboardPage.90f320b382a70cd0232d.js:327:9018)
    at div
    at div
    at pr (https://<REDACTED>/public/build/DashboardPage.90f320b382a70cd0232d.js:354:2075)
    at k (https://<REDACTED>/public/build/vendors~app.90f320b382a70cd0232d.js:2:70367)
    at div
    at W (https://<REDACTED>/public/build/DashboardPage.90f320b382a70cd0232d.js:405:667)
    at DashboardPage
    at k (https://<REDACTED>/public/build/vendors~app.90f320b382a70cd0232d.js:2:70367)
    at n (https://<REDACTED>/public/build/vendors~app.90f320b382a70cd0232d.js:2:462197)
    at dr (https://<REDACTED>/public/build/app.90f320b382a70cd0232d.js:5612:3196)
    at t (https://<REDACTED>/public/build/vendors~app.90f320b382a70cd0232d.js:2:1206671)
    at t (https://<REDACTED>/public/build/vendors~app.90f320b382a70cd0232d.js:2:1208716)
    at div
    at t (https://<REDACTED>/public/build/vendors~app.90f320b382a70cd0232d.js:2:1203276)
    at div
    at at (https://<REDACTED>/public/build/app.90f320b382a70cd0232d.js:3076:1106)
    at h (https://<REDACTED>/public/build/app.90f320b382a70cd0232d.js:5435:19792)
    at Di (https://<REDACTED>/public/build/app.90f320b382a70cd0232d.js:3726:564)
    at Ei (https://<REDACTED>/public/build/app.90f320b382a70cd0232d.js:3726:848)
    at l (https://<REDACTED>/public/build/vendors~app.90f320b382a70cd0232d.js:2:68275)
    at Nr (https://<REDACTED>/public/build/app.90f320b382a70cd0232d.js:5625:300)
```

**Environment**:
Grafana version: 8.0.3
Data source type & version: Azure
OS Grafana is installed on: running on docker over Linux (centos 8.3.2011)
User OS & Browser: Fedora 33 & Google Chrome 91

**Comment by zuchka** [comment]
Hi @gabrielmcf,

Thanks for reporting this issue.

I can confirm this behavior on one of our [internal instances](https://g80-beta.grafana.net/d/MA8bC_g7z/azure-table-error-test?orgId=1). I can generate the error w/o table view or by clicking `table view`
