### ISSUE TITLE
Terraform deploy grafana resource: Error: rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by MinsonTFW** [grafana/grafana#36450]
**What happened**:
While deploy grafana dashboard via Terraform, got the Error: rpc error: code = Unavailable desc = transport is closing

**What you expected to happen**:
there should be no error message while deploy grafana resource via Terraform

**How to reproduce it (as minimally and precisely as possible)**:
deploy a new grafana dashboard with grafana provider later than 1.10.0
```
provider "grafana" {
  url  = data.aws_ssm_parameter.url.value
  auth = data.aws_ssm_parameter.key.value
}

data "aws_region" "current" {}

resource "grafana_alert_notification" "email_alert" {
  count      = 1
  name       = xxx
  type       = "email"
  is_default = false

  settings = {
    "addresses"   = "xxx"
    "uploadImage" = "true"
  }
}

data "http" "uid" {
  url = format("%sapi/alert-notifications/%s", data.aws_ssm_parameter.url.value, join(", ", grafana_alert_notification.email_alert[*].id))
  request_headers = {
    Authorization = format("Bearer %s", data.aws_ssm_parameter.key.value)
  }

  depends_on = [
    grafana_alert_notification.email_alert,
  ]

}

data "template_file" "dash_tpl" {
  count    = 1
  template = file("dash.tpl")
  vars = {
    region             = data.aws_region.current.name
    datasource         = "xxx"
    uid                = jsondecode(data.http.uid.body)["uid"]
  }
}

resource "grafana_dashboard" "metrics" {
  count       = 1
  config_json = data.template_file.dash_tpl[count.index].rendered
  lifecycle {
    ignore_changes = [
      config_json
    ]
  }
}
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 1.11.0, 1.12.0, 1.13.0(later than 1.10.0)
- Data source type & version: AWS CloudWatch (also not work for Azure)
- OS Grafana is installed on: Grafana v6.7.1 (ca6d08d5cb)
- User OS & Browser: WSL2 Ubuntu20.04
- Grafana plugins: CloudWatch Data Source - Native Plugin
- Others: 
   - Terraform v0.14.11
   - provider registry.terraform.io/grafana/grafana v1.13.0
   - provider registry.terraform.io/hashicorp/aws v3.48.0
   - provider registry.terraform.io/hashicorp/http v2.1.0
   - provider registry.terraform.io/hashicorp/local v2.1.0
   - provider registry.terraform.io/hashicorp/template v2.2.0
   - provider registry.terraform.io/hashicorp/tls v3.1.0

**Workaround**:
I can deploy the dashboard if I stick the grafana provider version to: version = "~> 1.10.0"

**What's more**:
Tried to reproduce the issue with Terraform 15 or higher version, and the error is different:
```
│ Error: Plugin did not respond
│
│   with grafana_dashboard.metrics[0],
│   on grafana.tf line 110, in resource "grafana_dashboard" "metrics":
│  110: resource "grafana_dashboard" "metrics" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).PlanResourceChange call. The plugin logs may
│ contain more details.
╵
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-grafana_v1.13.0 plugin:

panic: Attempted to unmarshal invalid JSON. This unexpectedly got past schema validation.

goroutine 97 [running]:
github.com/grafana/terraform-provider-grafana/grafana.unmarshalDashboardConfigJSON(0xdb72b1, 0x24, 0xc72060)
        github.com/grafana/terraform-provider-grafana/grafana/resource_dashboard.go:268 +0x106
github.com/grafana/terraform-provider-grafana/grafana.normalizeDashboardConfigJSON(0xc72060, 0xc000566730, 0xb, 0x0)
        github.com/grafana/terraform-provider-grafana/grafana/resource_dashboard.go:299 +0x145
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diffString(0xc0002beb10, 0xda1dd8, 0xb, 0xc0003b8dc0, 0xc0000bd508, 0xeaff38, 0xc000800200, 0x203000, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/schema.go:1375 +0x6e3
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diff(0xc0002beb10, 0xda1dd8, 0xb, 0xc0003b8dc0, 0xc0005722e0, 0xeaff38, 0xc000800200, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/schema.go:957 +0x4e8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0xc0002beb10, 0xeac438, 0xc000304180, 0xc00057e2a0, 0xc0004786f0, 0x0, 0xc49660, 0xc000481560, 0x1388300, 0xc72060, ...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/schema.go:522 +0x219
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0xc0001eab60, 0xeac438, 0xc000304180, 0xc00057e2a0, 0xc0004786f0, 0xc49660, 0xc000481560, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:506 +0xa5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).PlanResourceChange(0xc00019b2c0, 0xeac438, 0xc000304180, 0xc0004880a0, 0xc000304180, 0xd60d20, 0xc000478100)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/grpc_provider.go:693 +0x7c5
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).PlanResourceChange(0xc0003069e0, 0xeac4e0, 0xc000304180, 0xc00057e150, 0xc0003069e0, 0xc000478180, 0xc000592ba0)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:315 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler(0xd60d20, 0xc0003069e0, 0xeac4e0, 0xc000478180, 0xc0000564e0, 0x0, 0xeac4e0, 0xc000478180, 0xc00070c0c0, 0xb7)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:362 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002e0c40, 0xeb3c58, 0xc000102d80, 0xc00026a000, 0xc0000a67e0, 0x1348f28, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.38.0/server.go:1286 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0002e0c40, 0xeb3c58, 0xc000102d80, 0xc00026a000, 0x0)
        google.golang.org/grpc@v1.38.0/server.go:1609 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000038260, 0xc0002e0c40, 0xeb3c58, 0xc000102d80, 0xc00026a000)
        google.golang.org/grpc@v1.38.0/server.go:934 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.38.0/server.go:932 +0x1fd

Error: The terraform-provider-grafana_v1.13.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

Would real appreciated if anyone can help and have a check, thanks!

**Comment by MinsonTFW** [comment]
move the issue to grafana/terraform-provider-grafana
