### ISSUE TITLE
Error message when loading @grafana/ui Icon component using @testing-library/react

### ISSUE THREAD

**Issue by andresmgot** [grafana/grafana#37052]
**What happened**:

When any component that depends on the `Icon` component from `@grafana/ui` is rendered, I got the following error:

```
  ● Console

    console.error
      Error: Error parsing input
          at convertFromString (/home/andres/projects/src/github.com/grafana/redshift-datasource/node_modules/@grafana/ui/index.development.js:2385:19)
          at convert (/home/andres/projects/src/github.com/grafana/redshift-datasource/node_modules/@grafana/ui/index.development.js:2404:16)
          at InlineSVG.getNode (/home/andres/projects/src/github.com/grafana/redshift-datasource/node_modules/@grafana/ui/index.development.js:2751:24)
          at InlineSVG.call [as getElement] (/home/andres/projects/src/github.com/grafana/redshift-datasource/node_modules/@grafana/ui/index.development.js:2782:29)
          at callCallback (/home/andres/projects/src/github.com/grafana/redshift-datasource/node_modules/react-dom/cjs/react-dom.development.js:12318:12)
          at commitUpdateQueue (/home/andres/projects/src/github.com/grafana/redshift-datasource/node_modules/react-dom/cjs/react-dom.development.js:12339:9)
          at commitLifeCycles (/home/andres/projects/src/github.com/grafana/redshift-datasource/node_modules/react-dom/cjs/react-dom.development.js:20709:11)
          at apply (/home/andres/projects/src/github.com/grafana/redshift-datasource/node_modules/react-dom/cjs/react-dom.development.js:23426:7)
... more traces
```

The culprit seems to be `react-inlinesvg`, since it's the one failed to load. Note that this only happens for external packages (not in Grafana core). I assume it's something related to how Grafana package icons but I don't know how to get rid of that.

I have tried to mock the `Icon` component and the package `react-inlinesvg` with `jest` to avoid loading those icons with no luck.

**What you expected to happen**:

This simple test to work without errors:

```
import React from 'react';
import { render } from '@testing-library/react';
import { Alert } from '@grafana/ui';

describe('Alert', () => {
  it('should render an Alert', async () => {
    render(<Alert />);
  });
});
```

**How to reproduce it (as minimally and precisely as possible)**:

See the example above.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.6
- Data source type & version: N/A
- OS Grafana is installed on: Linux
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others:

**Comment by sscots** [comment]
I get this error when I try to include @grafana/ui into my own project and simple just use
`<IconButton name="search"/>`
I also included 'react-inlinesvg' but still got same error.
