### ISSUE TITLE
Cannot read Graphite metrics

### ISSUE THREAD

**Issue by PsychoSid** [grafana/grafana#3719]
Hello,

Having trouble reading Graphite (0.9.15) information into Grafana (2.6.0)

Panel data error: TypeError: Cannot read property 'length' of undefined
    at g.convertDataPointsToMs (http://10.34.2.99:3000/public/app/app.ca0ab6f9.js:44:22773)
    at i (http://10.34.2.99:3000/public/app/app.ca0ab6f9.js:13:5845)
    at http://10.34.2.99:3000/public/app/app.ca0ab6f9.js:13:6017
    at n.$eval (http://10.34.2.99:3000/public/app/app.ca0ab6f9.js:13:13637)
    at n.$digest (http://10.34.2.99:3000/public/app/app.ca0ab6f9.js:13:12068)
    at n.$apply (http://10.34.2.99:3000/public/app/app.ca0ab6f9.js:13:13904)
    at f (http://10.34.2.99:3000/public/app/app.ca0ab6f9.js:11:20602)
    at r (http://10.34.2.99:3000/public/app/app.ca0ab6f9.js:11:22399)
    at XMLHttpRequest.v.onload (http://10.34.2.99:3000/public/app/app.ca0ab6f9.js:11:22939)

Request headers:-
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.8
Connection:keep-alive
Content-Length:126
Content-Type:application/x-www-form-urlencoded
Host:<myhost.mydomain>
Origin:http://10.34.2.99:3000
Referer:http://10.34.2.99:3000/dashboard/db/netapp-dashboard-cluster-group
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36

Response Headers:-
Access-Control-Allow-Credentials:true
Access-Control-Allow-Headers:*
Access-Control-Allow-Methods:*
Access-Control-Allow-Origin:*
Connection:Keep-Alive
Content-Encoding:gzip
Content-Length:542
Content-Type:text/html; charset=utf-8
Date:Wed, 13 Jan 2016 13:05:08 GMT
Keep-Alive:timeout=5, max=98
Server:Apache/2.4.6 (Red Hat Enterprise Linux) mod_wsgi/3.4 Python/2.7.5
Vary:Accept-Encoding

Form Data:-
target:highestAverage(netapp.perf.*.*.node.*.vol_summary.read_latency, 5)
from:-6h
until:now
format:json
maxDataPoints:100

It's a 200 return code.

Scratching my head on this one if any ideas are available ?

Thanks
Paul

**Comment by torkelo** [comment]
whats the response data from graphite?

**Comment by PsychoSid** [comment]
Don't worry I was using the wrong URL had http://<thing>/graphite removing that worked. My bad.
