### ISSUE TITLE
Disabled query causes error in alerting editor 

### ISSUE THREAD

**Issue by a-mazed** [grafana/grafana#39000]
**What happened**:
After upgrading Grafana from v7.5.7 to v8.1.2 I got "An unexpected error happened" editing alert rules. After some investigation, I decided that it was caused by query previously disabled on the graph panel.

**What you expected to happen**:
Succesfully edited alert rule

**How to reproduce it (as minimally and precisely as possible)**:

1. create query in Grafana v7.5.7, disable it and make an alert with it
2. update Grafana to v8.1.2
3. enable option ngalert
4. open this alert rule in editor and press "Run queries"
5. face the error

```
An unexpected error happened
TypeError: Cannot read properties of undefined (reading 'series')

    at t (http://hostname:3000/public/build/vendors~app.f2e9788d35f3ceef8811.js:2:2266796)
    at Dr (http://hostname:3000/public/build/vendors~app.f2e9788d35f3ceef8811.js:2:2336807)
    at he (http://hostname:3000/public/build/AlertingRuleForm.f2e9788d35f3ceef8811.js:110:385)
    at div
    at Re (http://hostname:3000/public/build/AlertingRuleForm.f2e9788d35f3ceef8811.js:110:2786)
    at F (http://hostname:3000/public/build/vendors~app.f2e9788d35f3ceef8811.js:2:1136397)
    at div
    at div
    at f (http://hostname:3000/public/build/app.f2e9788d35f3ceef8811.js:1058:26)
    at fieldset
    at Xd (http://hostname:3000/public/build/app.f2e9788d35f3ceef8811.js:4763:1215)
    at div
    at div
    at b (http://hostname:3000/public/build/AlertingRuleForm.f2e9788d35f3ceef8811.js:1:230)
    at Pe (http://hostname:3000/public/build/AlertingRuleForm.f2e9788d35f3ceef8811.js:121:455)
    at div
    at div
    at div
    at t (http://hostname:3000/public/build/vendors~app.f2e9788d35f3ceef8811.js:2:852951)
    at h (http://hostname:3000/public/build/app.f2e9788d35f3ceef8811.js:6100:36473)
    at div
    at form
    at j (http://hostname:3000/public/build/vendors~app.f2e9788d35f3ceef8811.js:2:1134319)
    at $t (http://hostname:3000/public/build/AlertingRuleForm.f2e9788d35f3ceef8811.js:149:252)
    at Gt (http://hostname:3000/public/build/AlertingRuleForm.f2e9788d35f3ceef8811.js:170:79)
    at t.default.Object.style (http://hostname:3000/public/build/AlertingRuleForm.f2e9788d35f3ceef8811.js:172:53)
    at dl (http://hostname:3000/public/build/app.f2e9788d35f3ceef8811.js:4466:682)
    at ul (http://hostname:3000/public/build/app.f2e9788d35f3ceef8811.js:4466:972)
    at WithErrorBoundary
    at n (http://hostname:3000/public/build/vendors~app.f2e9788d35f3ceef8811.js:2:545060)
    at Q (http://hostname:3000/public/build/app.f2e9788d35f3ceef8811.js:654:3244)
    at t (http://hostname:3000/public/build/vendors~app.f2e9788d35f3ceef8811.js:2:1381705)
    at t (http://hostname:3000/public/build/vendors~app.f2e9788d35f3ceef8811.js:2:1383750)
    at main
    at t (http://hostname:3000/public/build/vendors~app.f2e9788d35f3ceef8811.js:2:1378310)
    at div
    at la (http://hostname:3000/public/build/app.f2e9788d35f3ceef8811.js:3789:1227)
    at h (http://hostname:3000/public/build/app.f2e9788d35f3ceef8811.js:6060:20211)
    at dl (http://hostname:3000/public/build/app.f2e9788d35f3ceef8811.js:4466:682)
    at ul (http://hostname:3000/public/build/app.f2e9788d35f3ceef8811.js:4466:972)
    at l (http://hostname:3000/public/build/vendors~app.f2e9788d35f3ceef8811.js:2:71604)
    at Oe (http://hostname:3000/public/build/app.f2e9788d35f3ceef8811.js:667:517)
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1.2
- Data source type & version: Prometheus
- OS Grafana is installed on: Centos 8
- User OS & Browser: Win10, Chrome 93.0.4577.63
- Grafana plugins:
- Others:

**Comment by papagian** [comment]
@a-mazed thank you for reporting this!
What do you mean that the query was disabled? Maybe that the specific alert was paused?
Could you also share, from your browser's developer tools network tab, the request and the response sent when you click on`"Run queries"`? thank you

**Comment by a-mazed** [comment]
Unfortunately, I don't have such alerts anymore. I have deleted all of them and created their copies
