### ISSUE TITLE
Toggle text edit mode without any text box?

### ISSUE THREAD

**Issue by jhagg** [grafana/grafana#39982]
(I'm new to Grafana!)

I just upgraded to 8.1.5 (from 5.4), and noticed that when I click on the toggle button and expected a text box, I got nothing, nowhere to type at all. Clicking again returned the button style config. So I downgraded to 7.5.10 and the text box reappeared again!
So, is this a bug or just a misconfiguration from my side?
See pictures below.

*(I tried several other subversions of 8, same result, no text box.)*

Same result when I tested an old panel that I setup in 5.4,
there is no text at all in version 8.

OS: Debian sid
grafana-enterprise: 8.1.5

---
I'm using Icinga2 & Graphite carbon as data source.

graphite-carbon: 1.1.7-1
icinga2: 2.13.1-1.bullseye
icingaweb2-module-grafana: 1.4.2

---
### Version 8.1.5, button style
![8 1 5](https://user-images.githubusercontent.com/5468152/135970351-22149a7a-b706-49d9-9cdf-e1985c96289a.png)

### Version 8.1.5, text box style
![8 1 5 2](https://user-images.githubusercontent.com/5468152/135970348-714a2f6f-51aa-45b1-b861-34b72d6ebc73.png)

### Version 7.5.10, button style
![7 5 10](https://user-images.githubusercontent.com/5468152/135970345-478e0d88-d24c-4ac0-8904-920f2389e8b2.png)

### Version 7.5.10, text box style
![7 5 10 2](https://user-images.githubusercontent.com/5468152/135970343-d2bbbe5d-12f3-4f12-bdd5-72a980b5e427.png)

**Comment by ivanahuckova** [comment]
fyi @ifrost

**Comment by ifrost** [comment]
@jhagg - thanks for reporting this. I wasn't able to reproduce it locally with standard Graphite installation (though I think it shouldn't matter and the problem shouldn't be related to your configuration). The editor should show a text input with a prompt like below:

<img width="1107" alt="Screen Shot 2021-10-05 at 09 50 52" src="https://user-images.githubusercontent.com/745532/135982484-c57d7203-6259-41a3-88fd-a9d3af63e34a.png">

Could you please let me know:
- what browser you're using?
- do you see any errors in dev console?
- does it work in Explore?
- does it work if you select something in "button style" visual editor and then switch to text box editor?
- do you experience any problems with other data sources?
- could you also give it a go with 8.2.0-beta2?

Thanks!

**Comment by jhagg** [comment]
### what browser you're using?

Sorry, I forgot the browsers.
My main browser is Firefox 88.0.1, but I've also tried Chromium 93.0.4577.82-1
and Chrome 81.0.4044.122-1.

---
### do you see any errors in dev console?

Yes, I see quite a lot of errors, see attached file.

At the bottom I get these two:

Firefox can’t establish a connection to the server at ws://example.com:3000/api/live/ws. centrifuge.js:544:13
Firefox can’t establish a connection to the server at ws://example.com:3000/api/live/ws. centrifuge.js:544:13
(domain redacted)

However, no error shows up when I toggle it.

---
### does it work in Explore?

Same problem in Explore.

---
### does it work if you select something in "button style" visual editor and then switch to text box editor?

When I setup a graph with the buttons I get a working graph, but
no text when I toggle to text mode.

---
### do you experience any problems with other data sources?

Sorry, I only have one data source, I'm not sure how I would do that.

---
### could you also give it a go with 8.2.0-beta2?

I can try 8.2.0 if it's packaged. I have not created a stage server (yet)
so I'm using the prod server and the packaged version of Grafana.

---
[Errors in console](https://github.com/grafana/grafana/files/7284072/err.txt)

---
[Debug info in console](https://github.com/grafana/grafana/files/7284079/debug.txt)

**Comment by ifrost** [comment]
Thanks! 8.2.0-beta2 is available for downloading, but this version also uses Slate text editor which seems to be causing problems so not sure if that would change anything. The issue seems to be similar to https://community.grafana.com/t/error-when-trying-to-add-new-link-to-panel/47583 (at least looking at console errors). In the case mentioned in community proxy was causing the issue. Do you use any proxy?

**Comment by jhagg** [comment]
### 8.2.0-beta2 is available for downloading 

I did try 8.2.0~beta2, but it didn't work somehow, it stopped answering
on port 3000. The grafana log seems to indicate some plugin issue:

"Failed to start renderer plugin: Unrecognized remote plugin message: 
This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol."

Grafana dies and systemd restarts it after a few seconds.


(See log files below)

Going back to 8.1.5 or 7.5.10 worked fine.

### Do you use any proxy?

Yes and no. I have a proxy setup to listen on port 3001 and icinga2
is configured to use that port.

But I've only used port 3000 directly (no ssl) when I configured Grafana.  
*(http_port = 3000, domain = localhost)*

[journal.log](https://github.com/grafana/grafana/files/7291383/journal.log)
[grafana.log](https://github.com/grafana/grafana/files/7291384/grafana.log)

**Comment by ifrost** [comment]
@jhagg many thanks for all the info! I'll try again reproduce it locally. There's one more thing it'd be great if you could check. If you go to [Grafana Play](https://play.grafana.org/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22grafana-misc-stats%22,%7B%22refId%22:%22A%22%7D%5D) and try to switch - does the input show up? Should look like below:


https://user-images.githubusercontent.com/745532/136215156-d99e729a-9ec6-4c66-a006-d508266ce40e.mov

**Comment by jhagg** [comment]
### Grafana Play
![play1](https://user-images.githubusercontent.com/5468152/136327385-b5dd260e-2b3c-4a71-a115-08096050b8c0.png)
![play2](https://user-images.githubusercontent.com/5468152/136327387-c3a2f4ed-3ffa-4dfa-9a64-674e97d96d41.png)
![play3](https://user-images.githubusercontent.com/5468152/136327388-e47202a6-838e-4e38-a1a6-d874ee36b3cf.png)

**Comment by jhagg** [comment]
I have found the problem, it was indeed the websockets.  I forgot that I was
accessing port 3000 through a local proxy due to working from home. :-(

*(privoxy does not support websockets.)*

I just upgraded to 8.1.7 and when I created a tunnel directly to the server,
edit worked just fine.

**I'm very sorry for all trouble I caused.**

Thanks for your support anyway!

/Jörgen
