### ISSUE TITLE
grafana-server is crashing with "fatal error: concurrent map writes"

### ISSUE THREAD

**Issue by drook** [grafana/grafana#4044]
````crashlog
2016/02/16 10:22:55 [I] Completed 192.168.0.99 test "POST /api/datasources/proxy/5 HTTP/1.1" 401 Unauthorized 26 bytes in 554us
2016/02/16 10:22:55 [I] Completed 192.168.0.99 test "POST /api/datasources/proxy/6 HTTP/1.1" 401 Unauthorized 26 bytes in 542us
2016/02/16 10:22:55 [I] Completed 192.168.0.99 test "POST /api/datasources/proxy/14 HTTP/1.1" 401 Unauthorized 26 bytes in 512us
2016/02/16 10:22:55 [I] Completed 192.168.0.99 test "POST /api/datasources/proxy/18 HTTP/1.1" 401 Unauthorized 26 bytes in 643us
fatal error: concurrent map writes

goroutine 6672 [running]:
runtime.throw(0x1160bd0, 0x15)
        /usr/local/go-1.6rc1/src/runtime/panic.go:530 +0x99 fp=0xc82079b9f8 sp=0xc82079b9e0
runtime.mapassign1(0xd80220, 0xc8201b0a80, 0xc82079bac0, 0xc82079bac8)
        /usr/local/go-1.6rc1/src/runtime/hashmap.go:445 +0xb1 fp=0xc82079baa0 sp=0xc82079b9f8
github.com/grafana/grafana/pkg/api.getDatasource(0x3, 0x1, 0x3, 0x0, 0x0)
        /usr/local/grafana/src/github.com/grafana/grafana/pkg/api/dataproxy.go:80 +0x143 fp=0xc82079bc00 sp=0xc82079baa0
github.com/grafana/grafana/pkg/api.ProxyDataSourceRequest(0xc8202f9290)                                                 
        /usr/local/grafana/src/github.com/grafana/grafana/pkg/api/dataproxy.go:85 +0x6b fp=0xc82079bd00 sp=0xc82079bc00
runtime.call32(0xc82027e580, 0x12ada28, 0xc820710158, 0x800000008)
        /usr/local/go-1.6rc1/src/runtime/asm_amd64.s:472 +0x3e fp=0xc82079bd28 sp=0xc82079bd00
reflect.Value.call(0xd8e9a0, 0x12ada28, 0x13, 0x10aa930, 0x4, 0xc820490d20, 0x1, 0x1, 0x0, 0x0, ...)
        /usr/local/go-1.6rc1/src/reflect/value.go:435 +0x120d fp=0xc82079c078 sp=0xc82079bd28
reflect.Value.Call(0xd8e9a0, 0x12ada28, 0x13, 0xc820490d20, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go-1.6rc1/src/reflect/value.go:303 +0xb1 fp=0xc82079c0d8 sp=0xc82079c078
github.com/Unknwon/macaron/inject.(*injector).Invoke(0xc820490b60, 0xd8e9a0, 0x12ada28, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/grafana/src/github.com/grafana/grafana/Godeps/_workspace/src/github.com/Unknwon/macaron/inject/inject.go:102 +0x442 fp=0xc82079c240 sp=0xc82079c0d8
github.com/Unknwon/macaron.(*Context).run(0xc82044c000)
        /usr/local/grafana/src/github.com/grafana/grafana/Godeps/_workspace/src/github.com/Unknwon/macaron/context.go:11
3 +0xa3 fp=0xc82079c350 sp=0xc82079c240                                                                                 
github.com/Unknwon/macaron.(*Context).Next(0xc82044c000)
        /usr/local/grafana/src/github.com/grafana/grafana/Godeps/_workspace/src/github.com/Unknwon/macaron/context.go:10
4 +0x2c fp=0xc82079c360 sp=0xc82079c350
github.com/grafana/grafana/pkg/middleware.Sessioner.func1(0xc8202f9290)
        /usr/local/grafana/src/github.com/grafana/grafana/pkg/middleware/session.go:70 +0x37 fp=0xc82079c3e8 sp=0xc82079
c360
````

**Comment by bergquist** [comment]
Never seen this before :) 
How many datasources do you have? What kinda of datasource are you using?

**Comment by tral** [comment]
we use 14 datasources and all of them - https://github.com/grafana/datasource-plugin-genericdatasource

**Comment by tral** [comment]
Do you think it could be caused by invalid data?

**Comment by drook** [comment]
Looks like a race condition to me. From [Core library](http://tip.golang.org/doc/go1.6#minor_library_changes) article:

> The runtime has added lightweight, best-effort detection of concurrent misuse of maps. As always, 
> if one goroutine is writing to a map, no other goroutine should be reading or writing the map 
> concurrently. If the runtime detects this condition, it prints a diagnosis and crashes the program. 
> The best way to find out more about the problem is to run the program under the race detector, 
> which will more reliably identify the race and give more detail. 

So, this kind of error is seen sometimes in go code, for example googling gives this: https://github.com/spf13/afero/commit/75b0bd216a4b4f527dae351073b259fef4f00f81 .

Guys in the link above are fixing this by adding mutexes and locking/unlocking them. Are datasources in grafana nneeding this ? I'm not much of the programmer myself.

**Comment by drook** [comment]
By the way, this is repeatable. we have like loads of these crashlogs.

**Comment by tral** [comment]
It continues crashing every single day.
Meanwhile, we use Go 1.6 RC (I read that Grafana should run with Go 1.5, was it tested with 1.6?)

**Comment by woodsaj** [comment]
looks like torkel added a basic caching layer (that is not thread safe) and then only partially removed it.

https://github.com/grafana/grafana/blame/master/pkg/api/dataproxy.go#L67-L82

commenting out line #80 should fix the problem.

**Comment by bergquist** [comment]
@woodsaj good catch!
