### ISSUE TITLE
PostgreSQL: missing "=" after "sessions" in connection info

### ISSUE THREAD

**Issue by wienczny** [grafana/grafana#4081]
Grafana does not start using postgresql database.
Installed on Debian using the repository. The version is 2.6.0.

```
Feb 19 15:39:14 grafana grafana-server[787]: 2016/02/19 15:39:14 [I] Database: postgres
Feb 19 15:39:14 grafana grafana-server[787]: 2016/02/19 15:39:14 [I] Migrator: Starting DB migration
Feb 19 15:39:14 grafana grafana-server[787]: panic: missing "=" after "sessions" in connection info string"
Feb 19 15:39:14 grafana grafana-server[787]: goroutine 1 [running]:
Feb 19 15:39:14 grafana grafana-server[787]: github.com/grafana/grafana/pkg/middleware.Sessioner(0x1662520, 0x0, 0x0)
Feb 19 15:39:14 grafana grafana-server[787]: /go/src/github.com/grafana/grafana/pkg/middleware/session.go:64 +0x161
Feb 19 15:39:14 grafana grafana-server[787]: github.com/grafana/grafana/pkg/cmd.newMacaron(0xc820348450)
Feb 19 15:39:14 grafana grafana-server[787]: /go/src/github.com/grafana/grafana/pkg/cmd/web.go:49 +0x4c1
Feb 19 15:39:14 grafana grafana-server[787]: github.com/grafana/grafana/pkg/cmd.StartServer()
Feb 19 15:39:14 grafana grafana-server[787]: /go/src/github.com/grafana/grafana/pkg/cmd/web.go:78 +0x45
Feb 19 15:39:14 grafana grafana-server[787]: main.main()
Feb 19 15:39:14 grafana grafana-server[787]: /go/src/github.com/grafana/grafana/main.go:77 +0x3d6
Feb 19 15:39:14 grafana grafana-server[787]: goroutine 17 [syscall, locked to thread]:
Feb 19 15:39:14 grafana grafana-server[787]: runtime.goexit()
Feb 19 15:39:14 grafana grafana-server[787]: /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
Feb 19 15:39:14 grafana grafana-server[787]: goroutine 5 [syscall]:
Feb 19 15:39:14 grafana grafana-server[787]: os/signal.loop()
Feb 19 15:39:14 grafana grafana-server[787]: /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
Feb 19 15:39:14 grafana grafana-server[787]: created by os/signal.init.1
Feb 19 15:39:14 grafana grafana-server[787]: /usr/local/go/src/os/signal/signal_unix.go:28 +0x37
Feb 19 15:39:14 grafana grafana-server[787]: goroutine 19 [chan receive]:
Feb 19 15:39:14 grafana grafana-server[787]: github.com/grafana/grafana/pkg/services/notifications.processMailQueue()
Feb 19 15:39:14 grafana grafana-server[787]: /go/src/github.com/grafana/grafana/pkg/services/notifications/mailer.go:30 +0x75
Feb 19 15:39:14 grafana grafana-server[787]: created by github.com/grafana/grafana/pkg/services/notifications.initMailQueue
Feb 19 15:39:14 grafana grafana-server[787]: /go/src/github.com/grafana/grafana/pkg/services/notifications/mailer.go:24 +0x59
Feb 19 15:39:14 grafana grafana-server[787]: goroutine 7 [select]:
Feb 19 15:39:14 grafana grafana-server[787]: main.listenToSystemSignels()
Feb 19 15:39:14 grafana grafana-server[787]: /go/src/github.com/grafana/grafana/main.go:126 +0x4ab
Feb 19 15:39:14 grafana grafana-server[787]: created by main.main
Feb 19 15:39:14 grafana grafana-server[787]: /go/src/github.com/grafana/grafana/main.go:57 +0x2a1
Feb 19 15:39:14 grafana grafana-server[787]: goroutine 18 [select, locked to thread]:
Feb 19 15:39:14 grafana grafana-server[787]: runtime.gopark(0x10ddcb8, 0xc820022728, 0xefa068, 0x6, 0x4c4718, 0x2)
Feb 19 15:39:14 grafana grafana-server[787]: /usr/local/go/src/runtime/proc.go:185 +0x163
Feb 19 15:39:14 grafana grafana-server[787]: runtime.selectgoImpl(0xc820022728, 0x0, 0x18)
Feb 19 15:39:14 grafana grafana-server[787]: /usr/local/go/src/runtime/select.go:392 +0xa64
Feb 19 15:39:14 grafana grafana-server[787]: runtime.selectgo(0xc820022728)
Feb 19 15:39:14 grafana grafana-server[787]: /usr/local/go/src/runtime/select.go:212 +0x12
Feb 19 15:39:14 grafana grafana-server[787]: runtime.ensureSigM.func1()
Feb 19 15:39:14 grafana grafana-server[787]: /usr/local/go/src/runtime/signal1_unix.go:227 +0x353
Feb 19 15:39:14 grafana grafana-server[787]: runtime.goexit()
Feb 19 15:39:14 grafana grafana-server[787]: /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
Feb 19 15:39:14 grafana grafana-server[787]: goroutine 13 [select]:
Feb 19 15:39:14 grafana grafana-server[787]: github.com/grafana/grafana/pkg/log.(*Logger).StartLogger(0xc82019e080)
Feb 19 15:39:14 grafana grafana-server[787]: /go/src/github.com/grafana/grafana/pkg/log/log.go:227 +0x3cf
Feb 19 15:39:14 grafana grafana-server[787]: created by github.com/grafana/grafana/pkg/log.newLogger
Feb 19 15:39:14 grafana grafana-server[787]: /go/src/github.com/grafana/grafana/pkg/log/log.go:157 +0x138
Feb 19 15:39:14 grafana grafana-server[787]: goroutine 14 [select]:
Feb 19 15:39:14 grafana grafana-server[787]: github.com/grafana/grafana/pkg/log.(*Logger).StartLogger(0xc82019e5c0)
Feb 19 15:39:14 grafana grafana-server[787]: /go/src/github.com/grafana/grafana/pkg/log/log.go:227 +0x3cf
Feb 19 15:39:14 grafana grafana-server[787]: created by github.com/grafana/grafana/pkg/log.newLogger
Feb 19 15:39:14 grafana grafana-server[787]: /go/src/github.com/grafana/grafana/pkg/log/log.go:157 +0x138
Feb 19 15:39:14 grafana grafana-server[787]: goroutine 15 [chan receive]:
Feb 19 15:39:14 grafana grafana-server[787]: database/sql.(*DB).connectionOpener(0xc8201a46e0)
Feb 19 15:39:14 grafana grafana-server[787]: /usr/local/go/src/database/sql/sql.go:634 +0x45
Feb 19 15:39:14 grafana grafana-server[787]: created by database/sql.Open
Feb 19 15:39:14 grafana grafana-server[787]: /usr/local/go/src/database/sql/sql.go:481 +0x336
Feb 19 15:39:14 grafana grafana-server[787]: goroutine 25 [chan receive]:
Feb 19 15:39:14 grafana grafana-server[787]: github.com/grafana/grafana/pkg/metrics.StartUsageReportLoop(0xa)
Feb 19 15:39:14 grafana grafana-server[787]: /go/src/github.com/grafana/grafana/pkg/metrics/report_usage.go:22 +0x85
Feb 19 15:39:14 grafana grafana-server[787]: created by main.main
Feb 19 15:39:14 grafana grafana-server[787]: /go/src/github.com/grafana/grafana/main.go:74 +0x3d1
Feb 19 15:39:14 grafana grafana-server[787]: goroutine 29 [chan receive]:
Feb 19 15:39:14 grafana grafana-server[787]: database/sql.(*DB).connectionOpener(0xc820184460)
Feb 19 15:39:14 grafana grafana-server[787]: /usr/local/go/src/database/sql/sql.go:634 +0x45
Feb 19 15:39:14 grafana grafana-server[787]: created by database/sql.Open
Feb 19 15:39:14 grafana grafana-server[787]: /usr/local/go/src/database/sql/sql.go:481 +0x336
```

**Comment by torkelo** [comment]
Please provide you config

**Comment by wienczny** [comment]
```
##################### Grafana Configuration Example #####################
#
# Everything has defaults so you only need to uncomment things you want to
# change

# possible values : production, development
; app_mode = production

#################################### Paths ####################################
[paths]
# Path to where grafana can store temp files, sessions, and the sqlite3 db (if that is used)
#
;data = /var/lib/grafana
#
# Directory where grafana can store logs
#
;logs = /var/log/grafana

#################################### Server ####################################
[server]
# Protocol (http or https)
;protocol = http

# The ip address to bind to, empty will bind to all interfaces
;http_addr =

# The http port  to use
;http_port = 3000

# The public facing domain name used to access grafana from a browser
;domain = localhost

# Redirect to correct domain if host header does not match domain
# Prevents DNS rebinding attacks
;enforce_domain = false

# The full public facing url
;root_url = %(protocol)s://%(domain)s:%(http_port)s/

# Log web requests
;router_logging = false

# the path relative working path
;static_root_path = public

# enable gzip
;enable_gzip = false

# https certs & key file
;cert_file =
;cert_key =

#################################### Database ####################################
[database]
# Either "mysql", "postgres" or "sqlite3", it's your choice
type = postgres
host = 127.0.0.1:5432
name = grafana
user = grafana
password = grafana

# For "postgres" only, either "disable", "require" or "verify-full"
ssl_mode = disable

# For "sqlite3" only, path relative to data_path setting
;path = grafana.db

#################################### Session ####################################
[session]
# Either "memory", "file", "redis", "mysql", "postgres", default is "file"
provider = postgres

# Provider config options
# memory: not have any config yet
# file: session dir path, is relative to grafana data_path
# redis: config like redis server e.g. `addr=127.0.0.1:6379,pool_size=100,db=grafana`
# mysql: go-sql-driver/mysql dsn config string, e.g. `user:password@tcp(127.0.0.1:3306)/database_name`
# postgres: user=a password=b host=localhost port=5432 dbname=c sslmode=disable
;provider_config = sessions

# Session cookie name
;cookie_name = grafana_sess

# If you use session in https only, default is false
;cookie_secure = false

# Session life time, default is 86400
;session_life_time = 86400

#################################### Analytics ####################################
[analytics]
# Server reporting, sends usage counters to stats.grafana.org every 24 hours.
# No ip addresses are being tracked, only simple counters to track
# running instances, dashboard and error counts. It is very helpful to us.
# Change this option to false to disable reporting.
;reporting_enabled = true

# Google Analytics universal tracking code, only enabled if you specify an id here
;google_analytics_ua_id =

#################################### Security ####################################
[security]
# default admin user, created on startup
;admin_user = admin

# default admin password, can be changed before first start of grafana,  or in profile settings
;admin_password = admin

# used for signing
;secret_key = SW2YcwTIb9zpOOhoPsMm

# Auto-login remember days
;login_remember_days = 7
;cookie_username = grafana_user
;cookie_remember_name = grafana_remember

# disable gravatar profile images
;disable_gravatar = false

# data source proxy whitelist (ip_or_domain:port seperated by spaces)
;data_source_proxy_whitelist =

#################################### Users ####################################
[users]
# disable user signup / registration
allow_sign_up = false

# Allow non admin users to create organizations
allow_org_create = false

# Set to true to automatically assign new users to the default organization (id 1)
;auto_assign_org = true

# Default role new users will be automatically assigned (if disabled above is set to true)
;auto_assign_org_role = Viewer

# Background text for the user field on the login page
;login_hint = email or username

#################################### Anonymous Auth ##########################
[auth.anonymous]
# enable anonymous access
;enabled = false

# specify organization name that should be used for unauthenticated users
;org_name = Main Org.

# specify role for unauthenticated users
;org_role = Viewer

#################################### Github Auth ##########################
[auth.github]
;enabled = false
;allow_sign_up = false
;client_id = some_id
;client_secret = some_secret
;scopes = user:email,read:org
;auth_url = https://github.com/login/oauth/authorize
;token_url = https://github.com/login/oauth/access_token
;api_url = https://api.github.com/user
;team_ids =
;allowed_organizations =

#################################### Google Auth ##########################
[auth.google]
;enabled = false
;allow_sign_up = false
;client_id = some_client_id
;client_secret = some_client_secret
;scopes = https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
;auth_url = https://accounts.google.com/o/oauth2/auth
;token_url = https://accounts.google.com/o/oauth2/token
;api_url = https://www.googleapis.com/oauth2/v1/userinfo
;allowed_domains =

#################################### Auth Proxy ##########################
[auth.proxy]
;enabled = false
;header_name = X-WEBAUTH-USER
;header_property = username
;auto_sign_up = true

#################################### Basic Auth ##########################
[auth.basic]
;enabled = true

#################################### Auth LDAP ##########################
[auth.ldap]
;enabled = false
;config_file = /etc/grafana/ldap.toml

#################################### SMTP / Emailing ##########################
[smtp]
;enabled = false
;host = localhost:25
;user =
;password =
;cert_file =
;key_file =
;skip_verify = false
;from_address = admin@grafana.localhost

[emails]
;welcome_email_on_sign_up = false

#################################### Logging ##########################
[log]
# Either "console", "file", default is "console"
# Use comma to separate multiple modes, e.g. "console, file"
;mode = console, file

# Buffer length of channel, keep it as it is if you don't know what it is.
;buffer_len = 10000

# Either "Trace", "Debug", "Info", "Warn", "Error", "Critical", default is "Trace"
;level = Info

# For "console" mode only
[log.console]
;level =

# For "file" mode only
[log.file]
;level =
# This enables automated log rotate(switch of following options), default is true
;log_rotate = true

# Max line number of single file, default is 1000000
;max_lines = 1000000

# Max size shift of single file, default is 28 means 1 << 28, 256MB
;max_lines_shift = 28

# Segment log daily, default is true
;daily_rotate = true

# Expired days of log file(delete after max days), default is 7
;max_days = 7

#################################### AMPQ Event Publisher ##########################
[event_publisher]
;enabled = false
;rabbitmq_url = amqp://localhost/
;exchange = grafana_events

;#################################### Dashboard JSON files ##########################
[dashboards.json]
;enabled = false
;path = /var/lib/grafana/dashboards
```

**Comment by vmw-andersonm** [comment]
Please, note that if you set "provider = postgres" for  sessions, then you have to first create the "session" table in postgres, as per http://docs.grafana.org/installation/configuration/#session, and then define the value for the provider_config option as following (of course, replacing with your values):
user=a password=b host=localhost port=5432 dbname=c sslmode=disable
