### ISSUE TITLE
Grafana v8.3.2 does not show all panels on smaller screens

### ISSUE THREAD

**Issue by Links2004** [grafana/grafana#43003]
**What happened**:

many dashboards are missing panels on smaller screens after updating to Grafana v8.3.2.

example:
![image](https://user-images.githubusercontent.com/974709/145676372-0203af0e-b987-4aa4-8fa9-ba75f422bb5f.png)

if you resize the window the panels will show them self and keep being there.
this holds true if you go back to the exact same size then on page load.

but this "workaround" is not practicable for smartphones and full screen kiosk mode displays.
which breaks many of our status overview displays currently.

![Peek 2021-12-11 13-34](https://user-images.githubusercontent.com/974709/145676670-7eecf45f-21d8-4da8-993c-3d92d84c5390.gif)

**What you expected to happen**:

side is loaded and all panels are shown, without the need to resize the window first.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.2
- Data source type & version: does not affect bug
- OS Grafana is installed on: rendering issue
- User OS & Browser: tested in chrome, chromium, android phone
- Grafana plugins:
- Others:

**Comment by kaydelaney** [comment]
Hi @Links2004, thanks for making this issue. I think this may have been fixed by https://github.com/grafana/grafana/pull/42834. Do you think you could check if you can reproduce the issue on `main`?

**Comment by Links2004** [comment]
is there a nightly docker build or something like that to use?
or do I need to build Grafana from scratch ?

**Comment by Links2004** [comment]
I tried to build it with `make build-docker-full` but no success there.

the build shows errors and later fails.
```
Step 13/48 : COPY emails emails
 ---> Using cache
 ---> f58be024ed01
Step 14/48 : ENV NODE_ENV production
 ---> Using cache
 ---> 77a3e16a5fda
Step 15/48 : RUN yarn build
 ---> Running in 9d1e5d6ab3a6
No locales defined!

Add 'locales' to your configuration. See https://lingui.js.org/ref/conf.html#locales
Compiling message catalogs…
Done!
[
  ModuleNotFoundError: Module not found: Error: Can't resolve '../../locales/en/messages' in '/grafana/public/app/core'
      at /grafana/.yarn/__virtual__/webpack-virtual-0eaea73f47/0/cache/webpack-npm-5.63.0-1a7a135265-8127be3d90.zip/node_modules/webpack/lib/Compilation.js:2011:28
      at /grafana/.yarn/__virtual__/webpack-virtual-0eaea73f47/0/cache/webpack-npm-5.63.0-1a7a135265-8127be3d90.zip/node_modules/webpack/lib/NormalModuleFactory.js:795:13
      at eval (eval at create (/grafana/.yarn/cache/tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
      at /grafana/.yarn/__virtual__/webpack-virtual-0eaea73f47/0/cache/webpack-npm-5.63.0-1a7a135265-8127be3d90.zip/node_modules/webpack/lib/NormalModuleFactory.js:275:22
      at eval (eval at create (/grafana/.yarn/cache/tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
      at /grafana/.yarn/__virtual__/webpack-virtual-0eaea73f47/0/cache/webpack-npm-5.63.0-1a7a135265-8127be3d90.zip/node_modules/webpack/lib/NormalModuleFactory.js:431:22
      at /grafana/.yarn/__virtual__/webpack-virtual-0eaea73f47/0/cache/webpack-npm-5.63.0-1a7a135265-8127be3d90.zip/node_modules/webpack/lib/NormalModuleFactory.js:124:11
      at /grafana/.yarn/__virtual__/webpack-virtual-0eaea73f47/0/cache/webpack-npm-5.63.0-1a7a135265-8127be3d90.zip/node_modules/webpack/lib/NormalModuleFactory.js:667:25
      at /grafana/.yarn/__virtual__/webpack-virtual-0eaea73f47/0/cache/webpack-npm-5.63.0-1a7a135265-8127be3d90.zip/node_modules/webpack/lib/NormalModuleFactory.js:852:8
      at /grafana/.yarn/__virtual__/webpack-virtual-0eaea73f47/0/cache/webpack-npm-5.63.0-1a7a135265-8127be3d90.zip/node_modules/webpack/lib/NormalModuleFactory.js:972:5
  resolve '../../locales/en/messages' in '/grafana/public/app/core'
    using description file: /grafana/package.json (relative path: ./public/app/core)
      Field 'browser' doesn't contain a valid alias configuration
      using description file: /grafana/package.json (relative path: ./public/locales/en/messages)
        no extension
          Field 'browser' doesn't contain a valid alias configuration
          /grafana/public/locales/en/messages doesn't exist
        .ts
          Field 'browser' doesn't contain a valid alias configuration
          /grafana/public/locales/en/messages.ts doesn't exist
        .tsx
          Field 'browser' doesn't contain a valid alias configuration
          /grafana/public/locales/en/messages.tsx doesn't exist
        .es6
          Field 'browser' doesn't contain a valid alias configuration
          /grafana/public/locales/en/messages.es6 doesn't exist
        .js
          Field 'browser' doesn't contain a valid alias configuration
          /grafana/public/locales/en/messages.js doesn't exist
        .json
          Field 'browser' doesn't contain a valid alias configuration
          /grafana/public/locales/en/messages.json doesn't exist
        .svg
          Field 'browser' doesn't contain a valid alias configuration
          /grafana/public/locales/en/messages.svg doesn't exist
        as directory
          /grafana/public/locales/en/messages doesn't exist
]
The command '/bin/sh -c yarn build' returned a non-zero code: 1
make: *** [Makefile:100: build-docker-full] Error 1
```

**Comment by lost-carrier** [comment]
+1

...but locates it to...
* 8.2.3 -> NOT affected
* 8.2.4 -> affected!

**Comment by Links2004** [comment]
retested with 8.3.3, which still shows the problem

**Comment by kaydelaney** [comment]
The fix linked earlier won't be part of a grafana release until 8.4.0.
If you'd like to test the fix to see if it fixes things for you, you can pull `docker pull grafana/grafana:main`

**Comment by Links2004** [comment]
imported one if the affected dashboards in to `grafana/grafana:main`, and the panels are shown as exacted.
is there a approximate timeline for 8.4.0?

**Comment by kaydelaney** [comment]
At this point we're aiming for mid-February, but that's subject to change

**Comment by bartekn** [comment]
I still experience it in latest mobile Chrome. I'm running latest Grafana (`v9.4.7 (4add91f03d)`).
