### ISSUE TITLE
Prometheus query builder: Error: Illegal value for token color: #fff

### ISSUE THREAD

**Issue by colega** [grafana/grafana#43052]
**What happened**:

I opened Grafana Explore with Prometheus datasource selected, and saw this error:

![image](https://user-images.githubusercontent.com/1511481/145856636-d5a3b262-0848-4f18-860d-6935e9027583.png)

<details><summary>Full trace</summary>

```
An unexpected error happened
Details
Error: Illegal value for token color: #fff

    at me (https://<redacted grafana ops>/grafana/public/build/react-monaco-editor.04d0c04337c9d010e53f.js:1:15966)
    at Ns (https://<redacted grafana ops>/grafana/public/build/3007.04d0c04337c9d010e53f.js:2162:3811)
    at div
    at Nt (https://<redacted grafana ops>/grafana/public/build/prom-query-field.04d0c04337c9d010e53f.js:1:55746)
    at Suspense
    at he
    at pe (https://<redacted grafana ops>/grafana/public/build/prometheusPlugin.04d0c04337c9d010e53f.js:57:10113)
    at div
    at div
    at o (https://<redacted grafana ops>/grafana/public/build/3007.04d0c04337c9d010e53f.js:4495:7027)
    at fe (https://<redacted grafana ops>/grafana/public/build/prometheusPlugin.04d0c04337c9d010e53f.js:57:10675)
    at Be (https://<redacted grafana ops>/grafana/public/build/prometheusPlugin.04d0c04337c9d010e53f.js:68:815)
    at Tl (https://<redacted grafana ops>/grafana/public/build/3007.04d0c04337c9d010e53f.js:2883:467)
    at Ol (https://<redacted grafana ops>/grafana/public/build/3007.04d0c04337c9d010e53f.js:2883:1023)
    at div
    at div
    at div
    at https://<redacted grafana ops>/grafana/public/build/8402.04d0c04337c9d010e53f.js:2:707713
    at f (https://<redacted grafana ops>/grafana/public/build/8402.04d0c04337c9d010e53f.js:2:621295)
    at Uo (https://<redacted grafana ops>/grafana/public/build/8402.04d0c04337c9d010e53f.js:2:709084)
    at Zo (https://<redacted grafana ops>/grafana/public/build/8402.04d0c04337c9d010e53f.js:2:709202)
    at c (https://<redacted grafana ops>/grafana/public/build/3007.04d0c04337c9d010e53f.js:4617:968)
    at div
    at C (https://<redacted grafana ops>/grafana/public/build/3007.04d0c04337c9d010e53f.js:6909:540)
    at div
    at https://<redacted grafana ops>/grafana/public/build/8402.04d0c04337c9d010e53f.js:2:711426
    at f (https://<redacted grafana ops>/grafana/public/build/8402.04d0c04337c9d010e53f.js:2:621295)
    at f (https://<redacted grafana ops>/grafana/public/build/8402.04d0c04337c9d010e53f.js:2:618950)
    at oo (https://<redacted grafana ops>/grafana/public/build/8402.04d0c04337c9d010e53f.js:2:694459)
    at t (https://<redacted grafana ops>/grafana/public/build/8402.04d0c04337c9d010e53f.js:2:627718)
    at io (https://<redacted grafana ops>/grafana/public/build/8402.04d0c04337c9d010e53f.js:2:698197)
    at d (https://<redacted grafana ops>/grafana/public/build/1666.04d0c04337c9d010e53f.js:82:806)
    at ze (https://<redacted grafana ops>/grafana/public/build/explore.04d0c04337c9d010e53f.js:208:1914)
    at div
    at div
    at div
    at div
    at t (https://<redacted grafana ops>/grafana/public/build/8402.04d0c04337c9d010e53f.js:2:779792)
    at u (https://<redacted grafana ops>/grafana/public/build/3007.04d0c04337c9d010e53f.js:290:1044)
    at Xs (https://<redacted grafana ops>/grafana/public/build/explore.04d0c04337c9d010e53f.js:476:630)
    at WithTheme(undefined)
    at y (https://<redacted grafana ops>/grafana/public/build/8402.04d0c04337c9d010e53f.js:2:1089994)
    at div
    at on (https://<redacted grafana ops>/grafana/public/build/explore.04d0c04337c9d010e53f.js:491:2693)
    at y (https://<redacted grafana ops>/grafana/public/build/8402.04d0c04337c9d010e53f.js:2:1089994)
    at Tl (https://<redacted grafana ops>/grafana/public/build/3007.04d0c04337c9d010e53f.js:2883:467)
    at Ol (https://<redacted grafana ops>/grafana/public/build/3007.04d0c04337c9d010e53f.js:2883:1023)
    at div
    at div
    at mn (https://<redacted grafana ops>/grafana/public/build/explore.04d0c04337c9d010e53f.js:491:4494)
    at y (https://<redacted grafana ops>/grafana/public/build/8402.04d0c04337c9d010e53f.js:2:1089994)
    at n (https://<redacted grafana ops>/grafana/public/build/8402.04d0c04337c9d010e53f.js:2:1059206)
    at Ce (https://<redacted grafana ops>/grafana/public/build/3007.04d0c04337c9d010e53f.js:4426:193)
    at t (https://<redacted grafana ops>/grafana/public/build/8402.04d0c04337c9d010e53f.js:2:1107992)
    at t (https://<redacted grafana ops>/grafana/public/build/8402.04d0c04337c9d010e53f.js:2:1110013)
    at main
    at t (https://<redacted grafana ops>/grafana/public/build/8402.04d0c04337c9d010e53f.js:2:1104610)
    at div
    at Gs (https://<redacted grafana ops>/grafana/public/build/3007.04d0c04337c9d010e53f.js:2171:1055)
    at d (https://<redacted grafana ops>/grafana/public/build/3007.04d0c04337c9d010e53f.js:4872:26330)
    at Tl (https://<redacted grafana ops>/grafana/public/build/3007.04d0c04337c9d010e53f.js:2883:467)
    at Ol (https://<redacted grafana ops>/grafana/public/build/3007.04d0c04337c9d010e53f.js:2883:1023)
    at l (https://<redacted grafana ops>/grafana/public/build/8402.04d0c04337c9d010e53f.js:2:1087512)
    at Ye (https://<redacted grafana ops>/grafana/public/build/3007.04d0c04337c9d010e53f.js:4439:436)
```
</details>

**What you expected to happen**:

I should see the query builder.

**How to reproduce it (as minimally and precisely as possible)**:

Open Explore mode.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4.0-45022pre [1db9b1e](https://github.com/grafana/grafana/commit/1db9b1e6a905978cace829925e436a594bf3fd23)
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome on Linux
- Grafana plugins: N/A
- Others: N/A

**Comment by Logiraptor** [comment]
Just adding more details: I'm seeing the same issue. For me it only occurs in light mode. Dark mode is working fine (presumably because the token color is different).

**Comment by Elfo404** [comment]
Changing https://github.com/grafana/grafana/blob/8fb4882a013f307576423ba7600b72a09ead75e9/packages/grafana-data/src/themes/palette.ts#L2 from`#FFF` to `#FFFFFF` seems to fix the issue, however there are more apparently:

![image](https://user-images.githubusercontent.com/1170767/146174782-0d126935-0eaf-46c0-a1b3-03f272f262e5.png)

cc. @gabor

**Comment by gabor** [comment]
fixed by https://github.com/grafana/grafana/pull/43153
