### ISSUE TITLE
Azure Monitor: Bug switching back to Query type variable

### ISSUE THREAD

**Issue by fridgepoet** [grafana/grafana#43523]
**What happened**:
Grafana crashes while switching back to query type variable

**How to reproduce it (as minimally and precisely as possible)**:
Steps:
1. Click on Dashboard settings -> variables
2. Add new variable. It should be Query type
3. Choose Azure Monitor data source
4. Change to Custom type
5. Change back to Query type

`grafanaTemplateVariableFns.ts:226 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading ‘defaultSubscriptionId’)`

![out](https://user-images.githubusercontent.com/4163034/147356989-9f686fac-0b27-49a1-a2fc-cb1e0b4cc8e2.gif)

**Environment**:
Grafana version: 8.4-pre

**Comment by andresmgot** [comment]
hey @fridgepoet I tried to reproduce this but I am not able to:

![Peek 2022-01-19 17-07](https://user-images.githubusercontent.com/4025665/150169346-1fedc529-0554-462c-ac67-2e8a674d176d.gif)

are you still able to reproduce it?

**Comment by fridgepoet** [comment]
Yes I still am. That's strange. Let me know if there's any other information I could provide to help understand why.
```
TypeError: datasource.getVariables is not a function

    at ResourceField (http://localhost:3000/public/build/app.js?927a3c73c9df68feea82:180327:3)
    at div
    at InlineFieldRow (http://localhost:3000/public/build/app.js?927a3c73c9df68feea82:67272:5)
    at div
    at LogsQueryEditor (http://localhost:3000/public/build/app.js?927a3c73c9df68feea82:180151:3)
    at VariableEditor (http://localhost:3000/public/build/azureMonitorPlugin.js:2473:76)
    at div
    at div
    at div
    at Layout (http://localhost:3000/public/build/app.js?927a3c73c9df68feea82:72384:5)
    at VerticalGroup (http://localhost:3000/public/build/app.js?927a3c73c9df68feea82:72431:3)
    at div
    at div
    at Layout (http://localhost:3000/public/build/app.js?927a3c73c9df68feea82:72384:5)
    at VerticalGroup (http://localhost:3000/public/build/app.js?927a3c73c9df68feea82:72431:3)
    at div
    at div
    at Layout (http://localhost:3000/public/build/app.js?927a3c73c9df68feea82:72384:5)
    at VerticalGroup (http://localhost:3000/public/build/app.js?927a3c73c9df68feea82:72431:3)
    at QueryVariableEditorUnConnected (http://localhost:3000/public/build/app.js?927a3c73c9df68feea82:168666:1)
    at ConnectFunction (http://localhost:3000/public/build/app.js?927a3c73c9df68feea82:283515:68)
    at div
    at div
    at Layout (http://localhost:3000/public/build/app.js?927a3c73c9df68feea82:72384:5)
    at VerticalGroup (http://localhost:3000/public/build/app.js?927a3c73c9df68feea82:72431:3)
    at form
    at div
    at VariableEditorEditorUnConnected (http://localhost:3000/public/build/app.js?927a3c73c9df68feea82:164942:1)
    at ConnectFunction (http://localhost:3000/public/build/app.js?927a3c73c9df68feea82:283515:68)
    at div
    at VariableEditorContainerUnconnected (http://localhost:3000/public/build/app.js?927a3c73c9df68feea82:164803:1)
    at ConnectFunction (http://localhost:3000/public/build/app.js?927a3c73c9df68feea82:283515:68)
    at div
    at div
    at div
    at div
    at div
    at Scrollbars (http://localhost:3000/public/build/app.js?927a3c73c9df68feea82:244531:9)
    at CustomScrollbar (http://localhost:3000/public/build/app.js?927a3c73c9df68feea82:59212:3)
    at div
    at DashboardSettings (http://localhost:3000/public/build/app.js?927a3c73c9df68feea82:132364:3)
    at div
    at UnthemedDashboardPage (http://localhost:3000/public/build/DashboardPage.js:20607:1)
    at DashboardPage
    at ConnectFunction (http://localhost:3000/public/build/app.js?927a3c73c9df68feea82:283515:68)
    at LoadableComponent (http://localhost:3000/public/build/app.js?927a3c73c9df68feea82:282675:7)
    at GrafanaRoute (http://localhost:3000/public/build/app.js?927a3c73c9df68feea82:116841:1)
    at Route (http://localhost:3000/public/build/app.js?927a3c73c9df68feea82:285675:29)
    at Switch (http://localhost:3000/public/build/app.js?927a3c73c9df68feea82:285877:29)
    at main
    at Router (http://localhost:3000/public/build/app.js?927a3c73c9df68feea82:285306:30)
    at div
    at ModalsProvider (http://localhost:3000/public/build/app.js?927a3c73c9df68feea82:76308:5)
    at ThemeProvider (http://localhost:3000/public/build/app.js?927a3c73c9df68feea82:120490:3)
    at ErrorBoundary (http://localhost:3000/public/build/app.js?927a3c73c9df68feea82:65580:1)
    at ErrorBoundaryAlert (http://localhost:3000/public/build/app.js?927a3c73c9df68feea82:65651:1)
    at I18nProvider (http://localhost:3000/public/build/app.js?927a3c73c9df68feea82:12203:19)
    at I18nProvider (http://localhost:3000/public/build/app.js?927a3c73c9df68feea82:116077:3)
    at Provider (http://localhost:3000/public/build/app.js?927a3c73c9df68feea82:283230:20)
    at AppWrapper (http://localhost:3000/public/build/app.js?927a3c73c9df68feea82:97005:5)
```
![Screen Shot 2022-01-21 at 10 16 39](https://user-images.githubusercontent.com/4163034/150500531-9c2107a3-8eb1-4be6-9f48-b34d10024eb4.png)

**Comment by andresmgot** [comment]
FTR, we were able to reproduce it. The error appears when changing from the Azure Monitor editor in the template variable to `-- Grafana --` (which is a testing data source). For some reason it tries to load the Azure Monitor editor but the `datasource` is the other one.

**Comment by fridgepoet** [comment]
I am no longer able to reproduce the issue on v8.5.0-beta1 nor on v9.0.0-pre (main branch), so some change seems to have resolved it in the meantime.

**Comment by sarahzinger** [comment]
I just tested 8.4.6 which was just released and see the issue, but don't see it on main, so it would be nice if we can figure out what might have fixed it and see if it's possible to backport. 

Interesting this doesn't seem to happen for me when I switch from azure to adx but it does happen when i switch from azure to timestream. I'm not sure what that tells us but it seems like a potential clue.

**Comment by sarahzinger** [comment]
I believe this has been resolved (accidentally) with the work done in https://github.com/grafana/grafana/pull/46215/files#diff-0d2a13013eaf591a6a299942188756a875af488ae4aa0e633fe64ba4f4312e15L50 in 8.5 which is scheduled to go out sometime next week (the beta is already available :))
