### ISSUE TITLE
Checking for changes in provisioned dashboards sometimes causes panic on Windows

### ISSUE THREAD

**Issue by mkyporter** [grafana/grafana#43542]
**What happened**: Grafana sometimes panics when checking for changes in provisioned dashboard files.

**What you expected to happen**: No panic.

**How to reproduce it (as minimally and precisely as possible)**: Not sure. We've been trying to figure out a way to make it fail for some time now.

**Anything else we need to know?**: We have several Orgs using the same dashboard json makes Grafana log warnings about duplicate dashboards since 8.x.x. I created a separate set of dashboards per org but the issue persisted, which made the warnings go away but, the application still failed.

**Environment**:
- Grafana version: 8.2.7
- OS Grafana is installed on: Windows Server 2016

Error logged to the console:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x22 pc=0x117b7a9]

goroutine 539 [running]:
context.(*valueCtx).Done(0xc000d20cc0)
	<autogenerated>:1 +0x29
database/sql.(*DB).conn(0xc00053fee0, {0x40eb730, 0xc000d20cc0}, 0x1)
	/usr/local/go/src/database/sql/sql.go:1268 +0xe5
database/sql.(*DB).query(0x0, {0x40eb730, 0xc000d20cc0}, {0xc000783180, 0xe6}, {0xc0010dff00, 0x2, 0x2}, 0x20)
	/usr/local/go/src/database/sql/sql.go:1695 +0x5d
database/sql.(*DB).QueryContext(0xc00119a820, {0x40eb730, 0xc000d20cc0}, {0xc000783180, 0xe6}, {0xc0010dff00, 0x2, 0x2})
	/usr/local/go/src/database/sql/sql.go:1674 +0xdf
xorm.io/core.(*DB).QueryContext(0xc0009fe9c0, {0x40eb730, 0xc000d20cc0}, {0xc000783180, 0x2}, {0xc0010dff00, 0x0, 0x40c28f0})
	/root/go/pkg/mod/xorm.io/core@v0.7.3/db.go:121 +0x45
xorm.io/xorm.(*Session).queryRows(0xc0015a9500, {0xc000783180, 0xe6}, {0xc0010dff00, 0xc00002f960, 0x34c22a0})
	/root/go/pkg/mod/xorm.io/xorm@v0.8.2/session_raw.go:74 +0x6ca
xorm.io/xorm.(*Session).nocacheGet(0x6f697461746f6e6e, 0x19, 0x200a0d2c22737472, {0x3895040, 0xc0004969c0}, {0xc000783180, 0xe6}, {0xc0010dff00, 0x2, 0x2})
	/root/go/pkg/mod/xorm.io/xorm@v0.8.2/session_get.go:103 +0xe5
xorm.io/xorm.(*Session).get(0xc0015a9500, {0x3895040, 0xc0004969c0})
	/root/go/pkg/mod/xorm.io/xorm@v0.8.2/session_get.go:90 +0x6e7
xorm.io/xorm.(*Session).Get(0x3a598a0, {0x3895040, 0xc0004969c0})
	/root/go/pkg/mod/xorm.io/xorm@v0.8.2/session_get.go:23 +0x78
github.com/grafana/grafana/pkg/services/sqlstore.GetDashboardCtx.func1(0xc0010dfe20)
	/drone/src/pkg/services/sqlstore/dashboard.go:247 +0x152
github.com/grafana/grafana/pkg/services/sqlstore.withDbSession({0x40eb730, 0xc000d20cc0}, 0xc00085a460, 0xc0012a3448)
	/drone/src/pkg/services/sqlstore/session.go:67 +0x128
github.com/grafana/grafana/pkg/services/sqlstore.GetDashboardCtx({0x40eb730, 0xc000d20cc0}, 0x10bef07)
	/drone/src/pkg/services/sqlstore/dashboard.go:241 +0x46
reflect.Value.call({0x35d34a0, 0x3ce62a8, 0x30}, {0x3af9416, 0x4}, {0xc000d20cf0, 0x2, 0x18})
	/usr/local/go/src/reflect/value.go:543 +0x814
reflect.Value.Call({0x35d34a0, 0x3ce62a8, 0x336e19a}, {0xc000d20cf0, 0x2, 0x2})
	/usr/local/go/src/reflect/value.go:339 +0xc5
github.com/grafana/grafana/pkg/bus.(*InProcBus).DispatchCtx(0xc00055c0c0, {0x40eb688, 0xc00140ad00}, {0x3432de0, 0xc0004c0180})
	/drone/src/pkg/bus/bus.go:119 +0x68d
github.com/grafana/grafana/pkg/bus.DispatchCtx(...)
	/drone/src/pkg/bus/bus.go:231
github.com/grafana/grafana/pkg/services/provisioning/dashboards.getOrCreateFolderID({0x40eb688, 0xc00140ad00}, 0xc0001a53b0, {0x40fe428, 0xc00144e450}, {0xc001307100, 0xc000d20c90})
	/drone/src/pkg/services/provisioning/dashboards/file_reader.go:300 +0x107
github.com/grafana/grafana/pkg/services/provisioning/dashboards.(*FileReader).storeDashboardsInFolder(0xc0007fd500, {0x40eb688, 0xc00140ad00}, 0xc000d5a5a0, 0xc000f4f600, 0xc0017b7640)
	/drone/src/pkg/services/provisioning/dashboards/file_reader.go:142 +0x7d
github.com/grafana/grafana/pkg/services/provisioning/dashboards.(*FileReader).walkDisk(0xc0007fd500, {0x40eb688, 0xc00140ad00})
	/drone/src/pkg/services/provisioning/dashboards/file_reader.go:112 +0x247
github.com/grafana/grafana/pkg/services/provisioning/dashboards.(*FileReader).pollChanges(0xc0007fd500, {0x40eb688, 0xc00140ad00})
	/drone/src/pkg/services/provisioning/dashboards/file_reader.go:77 +0xe7
created by github.com/grafana/grafana/pkg/services/provisioning/dashboards.(*Provisioner).PollChanges
	/drone/src/pkg/services/provisioning/dashboards/dashboard.go:96 +0x4c
```

**Comment by mkyporter** [comment]
We paniced again and we have a slightly different error.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x143b809]

goroutine 2142 [running]:
context.(*valueCtx).Done(0xc001236060)
	<autogenerated>:1 +0x29
context.parentCancelCtx({0x4656c70, 0xc001236060})
	/usr/local/go/src/context/context.go:298 +0x2b
context.removeChild({0x4656c70, 0xc001236060}, {0x4625a50, 0xc001074000})
	/usr/local/go/src/context/context.go:315 +0x31
context.(*cancelCtx).cancel(0xc001074000, 0x1, {0x4608e00, 0xc0001081e0})
	/usr/local/go/src/context/context.go:421 +0x25b
context.WithCancel.func1()
	/usr/local/go/src/context/context.go:238 +0x30
database/sql.(*Rows).close(0xc000328180, {0x0, 0x0})
	/usr/local/go/src/database/sql/sql.go:3286 +0x18a
database/sql.(*Rows).Close(...)
	/usr/local/go/src/database/sql/sql.go:3263
xorm.io/xorm.(*Session).nocacheGet(0xc00228f158, 0x19, 0x2000, {0x3d85b60, 0xc000b40000}, {0xc002210000, 0xe6}, {0xc0015f61a0, 0x2, 0x2})
	/root/go/pkg/mod/xorm.io/xorm@v0.8.2/session_get.go:244 +0x13af
xorm.io/xorm.(*Session).get(0xc000dee000, {0x3d85b60, 0xc000b40000})
	/root/go/pkg/mod/xorm.io/xorm@v0.8.2/session_get.go:90 +0x6e7
xorm.io/xorm.(*Session).Get(0x30005, {0x3d85b60, 0xc000b40000})
	/root/go/pkg/mod/xorm.io/xorm@v0.8.2/session_get.go:23 +0x78
github.com/grafana/grafana/pkg/services/sqlstore.GetDashboard.func1(0xc0015f6000)
	/drone/src/pkg/services/sqlstore/dashboard.go:241 +0x152
github.com/grafana/grafana/pkg/services/sqlstore.withDbSession({0x4656c70, 0xc001236060}, 0xc000211340, 0xc00228f438)
	/drone/src/pkg/services/sqlstore/session.go:67 +0x128
github.com/grafana/grafana/pkg/services/sqlstore.GetDashboard({0x4656c70, 0xc001236060}, 0x137ef27)
	/drone/src/pkg/services/sqlstore/dashboard.go:235 +0x46
reflect.Value.call({0x3aac6c0, 0x41f0198, 0x30}, {0x3ff99fa, 0x4}, {0xc001236090, 0x2, 0x18})
	/usr/local/go/src/reflect/value.go:543 +0x814
reflect.Value.Call({0x3aac6c0, 0x41f0198, 0x383825b}, {0xc001236090, 0x2, 0x2})
	/usr/local/go/src/reflect/value.go:339 +0xc5
github.com/grafana/grafana/pkg/bus.(*InProcBus).DispatchCtx(0xc000080200, {0x4656bc8, 0xc00104b2c0}, {0x39014a0, 0xc000df03c0})
	/drone/src/pkg/bus/bus.go:119 +0x68d
github.com/grafana/grafana/pkg/bus.DispatchCtx(...)
	/drone/src/pkg/bus/bus.go:231
github.com/grafana/grafana/pkg/services/provisioning/dashboards.getOrCreateFolderID({0x4656bc8, 0xc00104b2c0}, 0xc0004ce4d0, {0x466a5a8, 0xc00119f050}, {0xc001949440, 0x2030004})
	/drone/src/pkg/services/provisioning/dashboards/file_reader.go:300 +0x107
github.com/grafana/grafana/pkg/services/provisioning/dashboards.(*FileReader).storeDashboardsInFolder(0xc0014ec930, {0x4656bc8, 0xc00104b2c0}, 0xc0012259e0, 0xc0012305e0, 0xc0017e42f0)
	/drone/src/pkg/services/provisioning/dashboards/file_reader.go:142 +0x7d
github.com/grafana/grafana/pkg/services/provisioning/dashboards.(*FileReader).walkDisk(0xc0014ec930, {0x4656bc8, 0xc00104b2c0})
	/drone/src/pkg/services/provisioning/dashboards/file_reader.go:112 +0x247
github.com/grafana/grafana/pkg/services/provisioning/dashboards.(*FileReader).pollChanges(0xc0014ec930, {0x4656bc8, 0xc00104b2c0})
	/drone/src/pkg/services/provisioning/dashboards/file_reader.go:77 +0xe7
created by github.com/grafana/grafana/pkg/services/provisioning/dashboards.(*Provisioner).PollChanges
	/drone/src/pkg/services/provisioning/dashboards/dashboard.go:96 +0x4c
```

**Comment by gurpartb** [comment]
@zuchka Is there any chance CleanUpService is deleting pointer reference? Code below was updated on December 20th after Grafana 7.3.3 release on December 14th.
https://github.com/grafana/grafana/commit/ff3cf94b56577093aaa468e477a2c62300521e8a#diff-f08934382b78082a861379480cfc429f0e8cb87ad8dfea47c3e4191630407b78

**Comment by zuchka** [comment]
@mkyporter 

thanks for all this info.

> when checking for changes in provisioned dashboard files

can you elaborate on this? Are you performing a specific action inside/outside the UI?

**Comment by gurpartb** [comment]
I was able to produce a similar error in Gafana 8.3.3 by setting 20+ providers, all with updateIntervalSeconds=1, in dashboards_provisioning.yaml. It took about 24 hours for Grafana to crash.

Everything above the line
`/root/go/pkg/mod/xorm.io/xorm@v0.8.2/session_get.go:103 +0xe5`
is same as the original error mkyporter posted. Everything below the line is same as the second error mkyporter posted.

**Error**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x23 pc=0x11ab809]

goroutine 349 [running]:
context.(*valueCtx).Done(0xc00193b9b0)
	<autogenerated>:1 +0x29
database/sql.(*DB).conn(0xc0007ec1a0, {0x43c6c70, 0xc00193b9b0}, 0x1)
	/usr/local/go/src/database/sql/sql.go:1268 +0xe5
database/sql.(*DB).query(0x0, {0x43c6c70, 0xc00193b9b0}, {0xc00223e380, 0xe6}, {0xc000beb1a0, 0x2, 0x2}, 0x20)
	/usr/local/go/src/database/sql/sql.go:1695 +0x5d
database/sql.(*DB).QueryContext(0x0, {0x43c6c70, 0xc00193b9b0}, {0xc00223e380, 0xe6}, {0xc000beb1a0, 0x2, 0x2})
	/usr/local/go/src/database/sql/sql.go:1674 +0xdf
xorm.io/core.(*DB).QueryContext(0xc000a16140, {0x43c6c70, 0xc00193b9b0}, {0xc00223e380, 0x2}, {0xc000beb1a0, 0x0, 0x439abb8})
	/root/go/pkg/mod/xorm.io/core@v0.7.3/db.go:121 +0x45
xorm.io/xorm.(*Session).queryRows(0xc0010bc000, {0xc00223e380, 0xe6}, {0xc000beb1a0, 0xc002a3f0a0, 0x3707b60})
	/root/go/pkg/mod/xorm.io/xorm@v0.8.2/session_raw.go:74 +0x6ca
xorm.io/xorm.(*Session).nocacheGet(0xc000e6b158, 0x19, 0x2000, {0x3af5b60, 0xc0007fc000}, {0xc00223e380, 0xe6}, {0xc000beb1a0, 0x2, 0x2})
	/root/go/pkg/mod/xorm.io/xorm@v0.8.2/session_get.go:103 +0xe5
xorm.io/xorm.(*Session).get(0xc0010bc000, {0x3af5b60, 0xc0007fc000})
	/root/go/pkg/mod/xorm.io/xorm@v0.8.2/session_get.go:90 +0x6e7
xorm.io/xorm.(*Session).Get(0x30003, {0x3af5b60, 0xc0007fc000})
	/root/go/pkg/mod/xorm.io/xorm@v0.8.2/session_get.go:23 +0x78
github.com/grafana/grafana/pkg/services/sqlstore.GetDashboard.func1(0xc000c29320)
	/drone/src/pkg/services/sqlstore/dashboard.go:241 +0x152
github.com/grafana/grafana/pkg/services/sqlstore.withDbSession({0x43c6c70, 0xc00193b9b0}, 0xc0007fa000, 0xc000e6b438)
	/drone/src/pkg/services/sqlstore/session.go:67 +0x128
github.com/grafana/grafana/pkg/services/sqlstore.GetDashboard({0x43c6c70, 0xc00193b9b0}, 0x10eef27)
	/drone/src/pkg/services/sqlstore/dashboard.go:235 +0x46
reflect.Value.call({0x381c6c0, 0x3f60198, 0x30}, {0x3d699fa, 0x4}, {0xc00193b9e0, 0x2, 0x18})
	/usr/local/go/src/reflect/value.go:543 +0x814
reflect.Value.Call({0x381c6c0, 0x3f60198, 0x35a825b}, {0xc00193b9e0, 0x2, 0x2})
	/usr/local/go/src/reflect/value.go:339 +0xc5
github.com/grafana/grafana/pkg/bus.(*InProcBus).DispatchCtx(0xc000271d40, {0x43c6bc8, 0xc000becb40}, {0x36714a0, 0xc000c27440})
	/drone/src/pkg/bus/bus.go:119 +0x68d
github.com/grafana/grafana/pkg/bus.DispatchCtx(...)
	/drone/src/pkg/bus/bus.go:231
github.com/grafana/grafana/pkg/services/provisioning/dashboards.getOrCreateFolderID({0x43c6bc8, 0xc000becb40}, 0xc000a4bd50, {0x43da5a8, 0xc000c49470}, {0xc000c2cc68, 0x2030006})
	/drone/src/pkg/services/provisioning/dashboards/file_reader.go:300 +0x107
github.com/grafana/grafana/pkg/services/provisioning/dashboards.(*FileReader).storeDashboardsInFolder(0xc000a4c850, {0x43c6bc8, 0xc000becb40}, 0xc000beb0a0, 0xc0018b0a60, 0xc0010cd420)
	/drone/src/pkg/services/provisioning/dashboards/file_reader.go:142 +0x7d
github.com/grafana/grafana/pkg/services/provisioning/dashboards.(*FileReader).walkDisk(0xc000a4c850, {0x43c6bc8, 0xc000becb40})
	/drone/src/pkg/services/provisioning/dashboards/file_reader.go:112 +0x247
github.com/grafana/grafana/pkg/services/provisioning/dashboards.(*FileReader).pollChanges(0xc000a4c850, {0x43c6bc8, 0xc000becb40})
	/drone/src/pkg/services/provisioning/dashboards/file_reader.go:77 +0xe7
created by github.com/grafana/grafana/pkg/services/provisioning/dashboards.(*Provisioner).PollChanges
	/drone/src/pkg/services/provisioning/dashboards/dashboard.go:96 +0x4c
```

**Last Trace Event**
```
{"trace_id":"00000000000000005c1d27709c2043c8","span_id":"5c1d27709c2043c8","parent_span_id":"","name":"bus - GetDashboardQuery","attributes":{"msg":"GetDashboardQuery","sampler.param":true,"sampler.type":"const"},"end_time":1642039689594266000,"kind":"SPAN_KIND_UNSPECIFIED","status":{"message":"","code":"STATUS_CODE_UNSET"},"start_time":1642039689594266000}
```

**Comment by gurpartb** [comment]
@idafurjes I was able to reproduce this (Grafana crash < 1hr) by creating 1000 dashboard Providers in a single Org, running standalone Grafana 8.2.3 service on Windows. I'm attaching a python script that can help you create n number of provisioned Dashboards, Providers, and Orgs for any Grafana service. You'll have to configure the script with Grafana provisioning folder paths and a sample_dashboard.json
[provision_dashboards_crash_test_py_script.txt](https://github.com/grafana/grafana/files/7909085/provision_dashboards_crash_test_py_script.txt)
