### ISSUE TITLE
Issue while using "*".

### ISSUE THREAD

**Issue by Himanshu-pupneja** [grafana/grafana#4382]
Hi @torkelo,

can you please help to identifying the issue. i am getting the error while using "*" in metric field.
snapshot attached for the same. Without * graph is working fine but when i use * it gives the below error.

* What grafana version are you using?         2.6
* What datasource are you using?                Graphite
* What OS are you running grafana on?       RHEL6.5

Error: 
Graphite encountered an unexpected error while handling your request.
Please contact your site administrator if the problem persists.

Traceback (most recent call last):
  File "/opt/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 109, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 104, in renderView
    seriesList = evaluateTarget(requestContext, target)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 10, in evaluateTarget
    result = evaluateTokens(requestContext, tokens)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 21, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 28, in evaluateTokens
    args = [evaluateTokens(requestContext, arg) for arg in tokens.call.args]
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 21, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 24, in evaluateTokens
    return fetchData(requestContext, tokens.pathExpression)
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 224, in fetchData
    dbResults = dbFile.fetch( timestamp(startTime), timestamp(endTime) )
  File "/opt/graphite/webapp/graphite/storage.py", line 298, in fetch
    (timeInfo,values) = whisper.fetch(self.fs_path, startTime, endTime)
  File "/opt/python/lib/python2.7/site-packages/whisper.py", line 667, in fetch
![image](https://cloud.githubusercontent.com/assets/15123322/13809804/85b21e44-eb92-11e5-80c8-dc52382df6a2.png)

Thank you! For helping us make Grafana even better.

To help us respond to your issues faster, please make sure to add as much information as possible.

If this issue is about a plugin, please open the issue in that repository.

Start your issues title with [Feature Request] / [Bug] / [Question] or no tag if your unsure.

Ex
* What grafana version are you using?
* What datasource are you using?
* What OS are you running grafana on?

**Comment by bergquist** [comment]
This seems like an graphite issue rather then grafana issue.

Can the query be rendered within graphite?
How many options does * return? graphite can be very slow if the amounts of options for * is to many.

**Comment by Himanshu-pupneja** [comment]
Hi bergquist,

I guess i got the issue, * contains 3000 values and the memory can't be able to handle this much data at once.
Thanks for looking into this.

Thanks
-Himanshu
