### ISSUE TITLE
No locales defined!

### ISSUE THREAD

**Issue by symeonmattes** [grafana/grafana#43824]
**What happened**:
During the installation of Grafana in a docker an error occurred related to locales

```
No locales defined!

Add 'locales' to your configuration. See https://lingui.js.org/ref/conf.html#locales
Compiling message catalogs…
Done!
No locales defined!

Add 'locales' to your configuration. See https://lingui.js.org/ref/conf.html#locales
[
  ModuleNotFoundError: Module not found: Error: Can't resolve '../../locales/en/messages' in '/grafana/public/app/core'
      at /grafana/.yarn/__virtual__/webpack-virtual-2e8f7f9227/0/cache/webpack-npm-5.65.0-da658c1b49-221ab8ccd4.zip/node_modules/webpack/lib/Compilation.js:2011:28
      at /grafana/.yarn/__virtual__/webpack-virtual-2e8f7f9227/0/cache/webpack-npm-5.65.0-da658c1b49-221ab8ccd4.zip/node_modules/webpack/lib/NormalModuleFactory.js:795:13
      at eval (eval at create (/grafana/.yarn/cache/tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
      at /grafana/.yarn/__virtual__/webpack-virtual-2e8f7f9227/0/cache/webpack-npm-5.65.0-da658c1b49-221ab8ccd4.zip/node_modules/webpack/lib/NormalModuleFactory.js:275:22
      at eval (eval at create (/grafana/.yarn/cache/tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
      at /grafana/.yarn/__virtual__/webpack-virtual-2e8f7f9227/0/cache/webpack-npm-5.65.0-da658c1b49-221ab8ccd4.zip/node_modules/webpack/lib/NormalModuleFactory.js:431:22
      at /grafana/.yarn/__virtual__/webpack-virtual-2e8f7f9227/0/cache/webpack-npm-5.65.0-da658c1b49-221ab8ccd4.zip/node_modules/webpack/lib/NormalModuleFactory.js:124:11
      at /grafana/.yarn/__virtual__/webpack-virtual-2e8f7f9227/0/cache/webpack-npm-5.65.0-da658c1b49-221ab8ccd4.zip/node_modules/webpack/lib/NormalModuleFactory.js:667:25
      at /grafana/.yarn/__virtual__/webpack-virtual-2e8f7f9227/0/cache/webpack-npm-5.65.0-da658c1b49-221ab8ccd4.zip/node_modules/webpack/lib/NormalModuleFactory.js:852:8
      at /grafana/.yarn/__virtual__/webpack-virtual-2e8f7f9227/0/cache/webpack-npm-5.65.0-da658c1b49-221ab8ccd4.zip/node_modules/webpack/lib/NormalModuleFactory.js:972:5
  resolve '../../locales/en/messages' in '/grafana/public/app/core'
    using description file: /grafana/package.json (relative path: ./public/app/core)
      Field 'browser' doesn't contain a valid alias configuration
      using description file: /grafana/package.json (relative path: ./public/locales/en/messages)
        no extension
          Field 'browser' doesn't contain a valid alias configuration
          /grafana/public/locales/en/messages doesn't exist
        .ts
          Field 'browser' doesn't contain a valid alias configuration
          /grafana/public/locales/en/messages.ts doesn't exist
        .tsx
          Field 'browser' doesn't contain a valid alias configuration
          /grafana/public/locales/en/messages.tsx doesn't exist
        .es6
          Field 'browser' doesn't contain a valid alias configuration
          /grafana/public/locales/en/messages.es6 doesn't exist
        .js
          Field 'browser' doesn't contain a valid alias configuration
          /grafana/public/locales/en/messages.js doesn't exist
        .json
          Field 'browser' doesn't contain a valid alias configuration
          /grafana/public/locales/en/messages.json doesn't exist
        .svg
          Field 'browser' doesn't contain a valid alias configuration
          /grafana/public/locales/en/messages.svg doesn't exist
        as directory
          /grafana/public/locales/en/messages doesn't exist
]
The command '/bin/sh -c yarn build' returned a non-zero code: 1
```

**What you expected to happen**:

The installation of the grafana in a docker container

**How to reproduce it (as minimally and precisely as possible)**:

1. Download from https://github.com/grafana/grafana/releases/tag/v8.3.3
2. Run
```
docker build grafana
```

**Anything else we need to know?**:

**Environment**: 
- Grafana version: 8.3.3
- Data source type & version: [lsb_release -a](https://github.com/grafana/grafana/releases/tag/v8.3.3)
- OS Grafana is installed on: Docker 20.10.9
- User OS & Browser: Debian 10
- Grafana plugins: The default in the Dockerfile
- Others:

**Comment by symeonmattes** [comment]
It seems that it's on the current version of git and not the 8.3.3

**Comment by akkinalper** [comment]
I am facing same issue on version 8.3.3

Error Messages
`Removing intermediate container 03a7d11923e6
 ---> f66648a32fde
Step 9/48 : COPY tsconfig.json .eslintrc .editorconfig .browserslistrc .prettierrc.js babel.config.json ./
 ---> 7d06c9cebeec
Step 10/48 : COPY public public
 ---> 77d11de44986
Step 11/48 : COPY tools tools
 ---> bdf3c0327c18
Step 12/48 : COPY scripts scripts
 ---> eb4a00b5bb99
Step 13/48 : COPY emails emails
 ---> ce03859d9205
Step 14/48 : ENV NODE_ENV production
 ---> Running in 8ca1ea15e428
Removing intermediate container 8ca1ea15e428
 ---> 4ffea30b4a75
Step 15/48 : RUN yarn build
 ---> Running in f8831de84f60
No locales defined!

Add 'locales' to your configuration. See https://lingui.js.org/ref/conf.html#locales
Compiling message catalogs…
Done!
No locales defined!

Add 'locales' to your configuration. See https://lingui.js.org/ref/conf.html#locales
The command '/bin/sh -c yarn build' returned a non-zero code: 129`

My Enviornment:

* MacOs - Bigsur
* Docker version 19.03.12
* yarn version: 3.1.1
* Node version : v14.17.1
*

**Comment by akkinalper** [comment]
I found that Dockerfile doesn't include .linguirc
After adding this file to docker problem solved

**Comment by longruiran** [comment]
I am also facing same error on version 8.3.3
