### ISSUE TITLE
Grafana vs Elastisearch field data loading is forbidden error

### ISSUE THREAD

**Issue by cello86** [grafana/grafana#4385]
Hi All,
we're actually using these versions:
* Grafana 2.6.0
* Elasticsearch 2.2.1
* CentOS 6.5 x86_64

We installed grafana on our development enviroment to test a replacemente of Kibana 4.4.0 but we noticed some issue with the terms searches. In fact if we tried to implement some panels with the terms search we received a error "field data loading is forbidden.."

Did somone noticce this issue?

Thanks,
Marcello

**Comment by torkelo** [comment]
whats your elasticsearch query? and where do you see this error? From elasticsearch?

**Comment by cello86** [comment]
I tried to add a table panel with terms based on a specific field ordered by term value and the query 

clientip: *

I received the error from grafana side.
{"root_cause":[{"type":"exception","reason":"java.lang.IllegalStateException: Field data loading is forbidden on clientip"},{"type":"illegal_state_exception","reason":"Field data loading is forbidden on clientip"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"logstash-apache-es-2016.02.24","node":"aZHu4TEORJ6gLY-avVDrVQ","reason":{"type":"exception","reason":"java.lang.IllegalStateException: Field data loading is forbidden on clientip","caused_by":{"type":"unchecked_execution_exception","reason":"java.lang.IllegalStateException: Field data loading is forbidden on clientip","caused_by":{"type":"illegal_state_exception","reason":"Field data loading is forbidden on clientip"}}}},{"shard":0,"index":"logstash-apache-it-2016.01.25","node":"aZHu4TEORJ6gLY-avVDrVQ","reason":{"type":"illegal_state_exception","reason":"Field data loading is forbidden on clientip"}}]}

Marcello

**Comment by torkelo** [comment]
that is an elasticsearch error, something wrong with you data or how you query it

**Comment by cello86** [comment]
The error reported is:

[2016-03-16 15:18:35,861][DEBUG][action.search.type       ] [cw-stms-ebe01] [logstash-apache-it-2016.03.16][0], node[aZHu4TEORJ6gLY-avVDrVQ], [P], v[2], s[STARTED], a[id=ZMvdL6ToQcSJiTQHC4wcjQ]: Failed to execute [org.elasticsearch.action.search.SearchRequest@482439b7]
RemoteTransportException[[cw-stms-ebe01][10.175.241.191:9300][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: ElasticsearchException[java.lang.IllegalStateException: Field data loading is forbidden on response]; nested: UncheckedExecutionException[java.lang.IllegalStateException: Field data loading is forbidden on response]; nested: IllegalStateException[Field data loading is forbidden on response];
Caused by: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: ElasticsearchException[java.lang.IllegalStateException: Field data loading is forbidden on response]; nested: UncheckedExecutionException[java.lang.IllegalStateException: Field data loading is forbidden on response]; nested: IllegalStateException[Field data loading is forbidden on response];
        at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:409)
        at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:113)
        at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:364)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:376)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: ElasticsearchException[java.lang.IllegalStateException: Field data loading is forbidden on response]; nested: UncheckedExecutionException[java.lang.IllegalStateException: Field data loading is forbidden on response]; nested: IllegalStateException[Field data loading is forbidden on response];
        at org.elasticsearch.index.fielddata.plain.AbstractIndexFieldData.load(AbstractIndexFieldData.java:82)
        at org.elasticsearch.search.aggregations.support.ValuesSource$Bytes$FieldData.bytesValues(ValuesSource.java:195)
       at org.elasticsearch.search.aggregations.bucket.terms.StringTermsAggregator.getLeafCollector(StringTermsAggregator.java:73)
        at org.elasticsearch.search.aggregations.AggregatorBase.getLeafCollector(AggregatorBase.java:132)
        at org.elasticsearch.search.aggregations.AggregatorBase.getLeafCollector(AggregatorBase.java:38)
        at org.apache.lucene.search.MultiCollector.getLeafCollector(MultiCollector.java:121)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:812)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:535)
        at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:384)
        ... 10 more
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Field data loading is forbidden on response
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4739)
        at org.elasticsearch.indices.fielddata.cache.IndicesFieldDataCache$IndexFieldCache.load(IndicesFieldDataCache.java:156)
        at org.elasticsearch.index.fielddata.plain.AbstractIndexFieldData.load(AbstractIndexFieldData.java:76)
        ... 18 more
Caused by: java.lang.IllegalStateException: Field data loading is forbidden on response
        at org.elasticsearch.index.fielddata.plain.DisabledIndexFieldData.fail(DisabledIndexFieldData.java:68)
        at org.elasticsearch.index.fielddata.plain.DisabledIndexFieldData.loadDirect(DisabledIndexFieldData.java:54)
        at org.elasticsearch.indices.fielddata.cache.IndicesFieldDataCache$IndexFieldCache$1.call(IndicesFieldDataCache.java:163)
        at org.elasticsearch.indices.fielddata.cache.IndicesFieldDataCache$IndexFieldCache$1.call(IndicesFieldDataCache.java:156)
        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4742)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
        ... 22 more
[2016-03-16 15:18:35,861][DEBUG][action.search.type       ] [cw-stms-ebe01] All shards failed for phase: [query]
RemoteTransportException[[cw-stms-ebe01][10.175.241.191:9300][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: ElasticsearchException[java.lang.IllegalStateException: Field data loading is forbidden on response]; nested: UncheckedExecutionException[java.lang.IllegalStateException: Field data loading is forbidden on response]; nested: IllegalStateException[Field data loading is forbidden on response];
Caused by: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: ElasticsearchException[java.lang.IllegalStateException: Field data loading is forbidden on response]; nested: UncheckedExecutionException[java.lang.IllegalStateException: Field data loading is forbidden on response]; nested: IllegalStateException[Field data loading is forbidden on response];
        at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:409)
        at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:113)
        at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:364)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:376)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: ElasticsearchException[java.lang.IllegalStateException: Field data loading is forbidden on response]; nested: UncheckedExecutionException[java.lang.IllegalStateException: Field data loading is forbidden on response]; nested: IllegalStateException[Field data loading is forbidden on response];
        at org.elasticsearch.index.fielddata.plain.AbstractIndexFieldData.load(AbstractIndexFieldData.java:82)
        at org.elasticsearch.search.aggregations.support.ValuesSource$Bytes$FieldData.bytesValues(ValuesSource.java:195)
        at org.elasticsearch.search.aggregations.bucket.terms.StringTermsAggregator.getLeafCollector(StringTermsAggregator.java:73)
        at org.elasticsearch.search.aggregations.AggregatorBase.getLeafCollector(AggregatorBase.java:132)
        at org.elasticsearch.search.aggregations.AggregatorBase.getLeafCollector(AggregatorBase.java:38)
        at org.apache.lucene.search.MultiCollector.getLeafCollector(MultiCollector.java:121)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:812)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:535)
        at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:384)
        ... 10 more
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Field data loading is forbidden on response
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4739)
        at org.elasticsearch.indices.fielddata.cache.IndicesFieldDataCache$IndexFieldCache.load(IndicesFieldDataCache.java:156)
        at org.elasticsearch.index.fielddata.plain.AbstractIndexFieldData.load(AbstractIndexFieldData.java:76)
        ... 18 more
Caused by: java.lang.IllegalStateException: Field data loading is forbidden on response
        at org.elasticsearch.index.fielddata.plain.DisabledIndexFieldData.fail(DisabledIndexFieldData.java:68)
        at org.elasticsearch.index.fielddata.plain.DisabledIndexFieldData.loadDirect(DisabledIndexFieldData.java:54)
        at org.elasticsearch.indices.fielddata.cache.IndicesFieldDataCache$IndexFieldCache$1.call(IndicesFieldDataCache.java:163)
        at org.elasticsearch.indices.fielddata.cache.IndicesFieldDataCache$IndexFieldCache$1.call(IndicesFieldDataCache.java:156)
        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4742)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
        ... 22 more
[2016-03-16 15:18:35,861][DEBUG][action.search.type       ] [cw-stms-ebe01] All shards failed for phase: [query]
RemoteTransportException[[cw-stms-ebe01][10.175.241.191:9300][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: ElasticsearchException[java.lang.IllegalStateException: Field data loading is forbidden on response]; nested: UncheckedExecutionException[java.lang.IllegalStateException: Field data loading is forbidden on response]; nested: IllegalStateException[Field data loading is forbidden on response];
Caused by: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: ElasticsearchException[java.lang.IllegalStateException: Field data loading is forbidden on response]; nested: UncheckedExecutionException[java.lang.IllegalStateException: Field data loading is forbidden on response]; nested: IllegalStateException[Field data loading is forbidden on response];
        at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:409)
        at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:113)
        at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:364)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:376)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: ElasticsearchException[java.lang.IllegalStateException: Field data loading is forbidden on response]; nested: UncheckedExecutionException[java.lang.IllegalStateException: Field data loading is forbidden on response]; nested: IllegalStateException[Field data loading is forbidden on response];
        at org.elasticsearch.index.fielddata.plain.AbstractIndexFieldData.load(AbstractIndexFieldData.java:82)
        at org.elasticsearch.search.aggregations.support.ValuesSource$Bytes$FieldData.bytesValues(ValuesSource.java:195)
        at org.elasticsearch.search.aggregations.bucket.terms.StringTermsAggregator.getLeafCollector(StringTermsAggregator.java:73)
        at org.elasticsearch.search.aggregations.AggregatorBase.getLeafCollector(AggregatorBase.java:132)
        at org.elasticsearch.search.aggregations.AggregatorBase.getLeafCollector(AggregatorBase.java:38)
        at org.apache.lucene.search.MultiCollector.getLeafCollector(MultiCollector.java:121)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:812)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:535)
        at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:384)
        ... 10 more
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Field data loading is forbidden on response
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4739)
        at org.elasticsearch.indices.fielddata.cache.IndicesFieldDataCache$IndexFieldCache.load(IndicesFieldDataCache.java:156)
        at org.elasticsearch.index.fielddata.plain.AbstractIndexFieldData.load(AbstractIndexFieldData.java:76)
        ... 18 more
Caused by: java.lang.IllegalStateException: Field data loading is forbidden on response
        at org.elasticsearch.index.fielddata.plain.DisabledIndexFieldData.fail(DisabledIndexFieldData.java:68)
        at org.elasticsearch.index.fielddata.plain.DisabledIndexFieldData.loadDirect(DisabledIndexFieldData.java:54)
        at org.elasticsearch.indices.fielddata.cache.IndicesFieldDataCache$IndexFieldCache$1.call(IndicesFieldDataCache.java:163)
        at org.elasticsearch.indices.fielddata.cache.IndicesFieldDataCache$IndexFieldCache$1.call(IndicesFieldDataCache.java:156)
        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4742)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
        ... 22 more

**Comment by torkelo** [comment]
It's an Elsaticsearch error, dont know the cause, maybe ask in a elasticsearch forum

**Comment by cello86** [comment]
Hi All,
there isn't an error but a configuration of logstash to not analyze all the terms for performance improvements. Kibana permit to use the .raw version of the field, but on Grafana isn't present these selection of the same field.

**Comment by lavaalone** [comment]
Yes I'm also facing this issue. Grafana does not allow to use .raw on String field as Kibana does, so it's impossible to do the Term right now.

**Comment by emillion** [comment]
I think the reason can be found here : https://github.com/elastic/elasticsearch/issues/15267#issuecomment-163657397

**Comment by rlodge** [comment]
My understanding is that the new(er) elasticsearch setups don't allow this sort of query on analyzed fields, and the suggested solution is to use the ".raw" value instead.  But Grafana doesn't allow me to do that.  If I enter, say, "level.raw" for log level, it issues the query to elasticsearch correctly, and returns the correct results, but then Grafana gets a JS error:

```
boot.8ba215a1.js:36 TypeError: Cannot read property 'toString' of undefined
    at a.isMsResolutionNeeded (http://analytics-nonprod-graphite-01.cengage.info/grafana/public/app/boot.8ba215a1.js:19:17859)
    at h.seriesHandler (http://analytics-nonprod-graphite-01.cengage.info/grafana/public/app/boot.8ba215a1.js:17:18524)
    at Array.map (native)
    at h.onDataReceived (http://analytics-nonprod-graphite-01.cengage.info/grafana/public/app/boot.8ba215a1.js:17:17831)
    at e.emit (http://analytics-nonprod-graphite-01.cengage.info/grafana/public/app/boot.8ba215a1.js:39:20720)
    at a.emit (http://analytics-nonprod-graphite-01.cengage.info/grafana/public/app/boot.8ba215a1.js:39:22811)
    at h.f.handleQueryResult (http://analytics-nonprod-graphite-01.cengage.info/grafana/public/app/boot.8ba215a1.js:41:15445)
    at h (http://analytics-nonprod-graphite-01.cengage.info/grafana/public/app/boot.8ba215a1.js:36:18232)
    at http://analytics-nonprod-graphite-01.cengage.info/grafana/public/app/boot.8ba215a1.js:36:18404
    at n.$eval (http://analytics-nonprod-graphite-01.cengage.info/grafana/public/app/boot.8ba215a1.js:36:25921)
```
