### ISSUE TITLE
Building custom plugins error: PostCSS plugin postcss-discard-comments requires PostCSS 8.

### ISSUE THREAD

**Issue by pepjo** [grafana/grafana#44701]
**What happened**:
We are unable to build our custom datasource plugin. We get the following error:

```
✖ PostCSS plugin postcss-discard-comments requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
  Trace: Error: PostCSS plugin postcss-discard-comments requires PostCSS 8.
  Migration guide for end-users:
  https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
      at Processor.normalize (/home/peprf/projects/telemetry-grafana/plugins/oc-data/node_modules/postcss/lib/processor.js:167:15)
      at new Processor (/home/peprf/projects/telemetry-grafana/plugins/oc-data/node_modules/postcss/lib/processor.js:56:25)
      at postcss (/home/peprf/projects/telemetry-grafana/plugins/oc-data/node_modules/postcss/lib/postcss.js:55:10)
      at cssnanoPlugin (/home/peprf/projects/telemetry-grafana/plugins/oc-data/node_modules/cssnano/dist/index.js:158:31)
      at getDefaultProcessor (/home/peprf/projects/telemetry-grafana/plugins/oc-data/node_modules/optimize-css-assets-webpack-plugin/src/index.js:9:19)
      at new OptimizeCssAssetsWebpackPlugin (/home/peprf/projects/telemetry-grafana/plugins/oc-data/node_modules/optimize-css-assets-webpack-plugin/src/index.js:30:9)
      at /home/peprf/projects/telemetry-grafana/plugins/oc-data/node_modules/@grafana/toolkit/src/config/webpack.plugin.config.js:160:25
      at step (/home/peprf/projects/telemetry-grafana/plugins/oc-data/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:143:27)
      at Object.next (/home/peprf/projects/telemetry-grafana/plugins/oc-data/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:124:57)
      at /home/peprf/projects/telemetry-grafana/plugins/oc-data/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:117:75
      at new Promise (<anonymous>)
      at __awaiter (/home/peprf/projects/telemetry-grafana/plugins/oc-data/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:113:16)
      at getBaseWebpackConfig (/home/peprf/projects/telemetry-grafana/plugins/oc-data/node_modules/@grafana/toolkit/src/config/webpack.plugin.config.js:148:78)
      at /home/peprf/projects/telemetry-grafana/plugins/oc-data/node_modules/@grafana/toolkit/src/config/webpack.plugin.config.js:279:42
      at step (/home/peprf/projects/telemetry-grafana/plugins/oc-data/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:143:27)
      at Object.next (/home/peprf/projects/telemetry-grafana/plugins/oc-data/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:124:57)
      at /home/peprf/projects/telemetry-grafana/plugins/oc-data/node_modules/@grafana/toolkit/src/cli/utils/useSpinner.js:31:33
      at step (/home/peprf/projects/telemetry-grafana/plugins/oc-data/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:143:27)
      at Object.throw (/home/peprf/projects/telemetry-grafana/plugins/oc-data/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:124:57)
      at rejected (/home/peprf/projects/telemetry-grafana/plugins/oc-data/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:115:69)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

These are our package.json dependencies:
```json
"devDependencies": {
  "@grafana/data": "latest",
  "@grafana/toolkit": "latest",
  "@grafana/ui": "latest",
  "@types/lodash": "latest",
  "@testing-library/jest-dom": "5.4.0",
  "@testing-library/react": "^10.0.2"
},
"dependencies": {
  "@grafana/runtime": "^8.3.4"
}
```

**What you expected to happen**:
I would expect the build to work as expected.

**How to reproduce it (as minimally and precisely as possible)**:
Following the datasource plugin tutorial with the latest versions should result in this error.

**Environment**:
- Grafana version: 8.3.4
- Data source type & version: Custom datasource plugin
- User OS & Browser: Linux using docker
- Grafana plugins: Only the custom plugin

**Comment by pepjo** [comment]
I've noted that, even though grafana itself has an updated postcss version: https://github.com/grafana/grafana/blob/main/package.json#L200

the toolkit project does not: https://github.com/grafana/grafana/blob/main/packages/grafana-toolkit/package.json#L86

**Comment by pepjo** [comment]
I am closing this, after deleting the `node_modules` folder and installing again it works. I must have updated the dependencies incorrectly!

**Comment by adsazad** [comment]
deleting and reinstalling `node_modules` didn't work.
I ran `npm i postcss` and after that `npm run build` it worked.

**Comment by radiorz** [comment]
postcss and autoprefixer should be installed.
