### ISSUE TITLE
Connect Prometheus error.

### ISSUE THREAD

**Issue by kerwin** [grafana/grafana#4476]
I'm using grafana v2.6.0 production version to connect prometheus, but get this error.

```
Cannot read property 'message' of null

			TypeError: Cannot read property 'message' of null
    at http://*.*.*.*:9091/public/app/app.ca0ab6f9.js:27:22903
    at i (http://*.*.*.*:9091/public/app/app.ca0ab6f9.js:13:5845)
    at http://*.*.*.*:9091/public/app/app.ca0ab6f9.js:13:6017
    at n.$eval (http://*.*.*.*:9091/public/app/app.ca0ab6f9.js:13:13637)
    at n.$digest (http://*.*.*.*:9091/public/app/app.ca0ab6f9.js:13:12068)
    at n.$apply (http://*.*.*.*:9091/public/app/app.ca0ab6f9.js:13:13904)
    at f (http://*.*.*.*:9091/public/app/app.ca0ab6f9.js:11:20602)
    at r (http://*.*.*.*:9091/public/app/app.ca0ab6f9.js:11:22399)
    at XMLHttpRequest.w (http://*.*.*.*:9091/public/app/app.ca0ab6f9.js:11:22994)
```

**Comment by kerwin** [comment]
the prometheus version is 

revision	6e8d4e9
version	0.17.0

**Comment by kerwin** [comment]
It's worked!

**Comment by lamont** [comment]
I am having the same error, did you do anything to fix it or find any more information on the error?

**Comment by jcrombez** [comment]
@kerwin any info on how you fixed it ? I have the same problem with a fresh install.

**Comment by pedrualves** [comment]
Same issue
