### ISSUE TITLE
MongoDB Enterprise Plugin Bug 

### ISSUE THREAD

**Issue by BlakeFernandez1** [grafana/grafana#44936]
Issue with setting up the MongoDB plugin. I have a simple find query hard coded and a table panel that displays the right information, however when I add a textbox variable to the dashboard (and doesn't use it in the MongoDB query) the panel stops working and I receive a "panelqueryrunner error typeerror". Once I remove that textbox variable and refreshes the dashboard it works again.

FYI: The issue can be replicated in the demo environment, and is specific to adding a textbox variable to the dashboard.
Error Message:
```
PanelQueryRunner.ts:258 PanelQueryRunner Error TypeError: Cannot read properties of undefined (reading 'uid')
    at eval (mongoInterpolate.ts:10:42)
    at eval (mongoInterpolate.ts:24:55)
    at Array.filter (<anonymous>)
    at m (mongoInterpolate.ts:24:36)
    at t.applyTemplateVariables (MongoDatasource.ts:71:22)
    at DataSourceWithBackend.ts:133:17
    at Array.map (<anonymous>)
    at t.query (DataSourceWithBackend.ts:110:29)
    at t.query (MongoDatasource.ts:40:23)
    at runRequest.ts:180:73
```

**Comment by mdvictor** [comment]
Bug has been fixed in version 1.1.12 of the MongoDB DS
