### ISSUE TITLE
Grafana 8.4.0: Copy Invite for Pending User Doesn't Copy Invite Text

### ISSUE THREAD

**Issue by alvintownsend** [grafana/grafana#45617]
**What happened**:

When creating a new user, clicking on the "Copy Invite" button for a pending invite should copy the invite text to the clipboard. It didn't, instead I get a JavaScript error. Error follows:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')
    at ClipboardButton.tsx:35:8
    at Object.Ue (react-dom.production.min.js:52:317)
    at Ke (react-dom.production.min.js:52:471)
    at react-dom.production.min.js:53:35
    at kr (react-dom.production.min.js:100:68)
    at Er (react-dom.production.min.js:101:380)
    at react-dom.production.min.js:113:65
    at Ne (react-dom.production.min.js:292:189)
    at react-dom.production.min.js:50:57
    at Ar (react-dom.production.min.js:105:469)
(anonymous) @ ClipboardButton.tsx:35
Ue @ react-dom.production.min.js:52
Ke @ react-dom.production.min.js:52
(anonymous) @ react-dom.production.min.js:53
kr @ react-dom.production.min.js:100
Er @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
Ne @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Ar @ react-dom.production.min.js:105
Jt @ react-dom.production.min.js:75
Xt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ho @ react-dom.production.min.js:122
ze @ react-dom.production.min.js:292
$t @ react-dom.production.min.js:73
```

**What you expected to happen**:

The invite text should have been copied to the clipboard.

**How to reproduce it (as minimally and precisely as possible)**:

Click the ⚙️ for Configuration;
Click "Users";
Add a new user;
Click "Pending Invites";
Click "Copy Invite";
Paste from clipboard somewhere.

Note that the contents of the clipboard are whatever was in the clipboard before clicking "Copy Invite".

**Anything else we need to know?**:

Possibly:

* I've just completed a reconfiguration of Nginx and Grafana to get past cross-domain issues when running Grafana behind a reverse proxy;
* I have not configured Grafana to send emails for invites (or anything else).

**Environment**:
- Grafana version: 8.4.0 (Docker)
- Data source type & version: n/a
- OS Grafana is installed on: Docker on Debian 11
- User OS & Browser: Mac OS 11.6.2; Brave Version 1.35.103 Chromium: 98.0.4758.102 (Official Build) (x86_64)
- Grafana plugins: default only, none added
- Others: n/a

**Comment by bio** [comment]
Also the button doesn't work in Firefox:
```
Uncaught TypeError: navigator.clipboard is undefined
    o ClipboardButton.tsx:34
    React 11
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
ClipboardButton.tsx:34:4
```

**Comment by Kangaroux** [comment]
The clipboard API is unavailable on `http://` pages: https://stackoverflow.com/a/51823007/2896976

While fixing it for http would be great, I think it would be better to maybe include the link on the button itself so you can right click > copy url

**Comment by Kangaroux** [comment]
@bio If you use React dev tools you can inspect the invite button and you'll see the URL listed under the `invitee` props (you might need to inspect the button's parent(s))

Make sure to check the host on the URL since it might be `localhost:3000`

**Comment by alvintownsend** [comment]
> While fixing it for http would be great, I think it would be better to maybe include the link on the button itself so you can right click > copy url

This would be an entirely acceptable fix, possibly even preferable to using the Clipboard API in general.

**Comment by zuchka** [comment]
some initial research:

[code in question](https://github.com/grafana/grafana/blob/main/public/app/features/invites/InviteeRow.tsx#L27-L29)

note about `ClipboardEvent` [getting deprecated in next major release](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/ClipboardButton/ClipboardButton.tsx#L4-L10)

Looks like the the `ClipboardButton` component is used widely. The behavior appears the same for the few that I checked, like the copy button in `ViewJsonModal.tsx`. 

Below are all the mentions I could find in the codebase:

```
packages/grafana-ui/src/components/index.ts
13:export { ClipboardButton } from './ClipboardButton/ClipboardButton';

packages/grafana-ui/src/components/ClipboardButton/ClipboardButton.story.internal.tsx
4:import { ClipboardButton, Props } from './ClipboardButton';
6:import mdx from './ClipboardButton.mdx';
9:  title: 'Buttons/ClipboardButton',
10:  component: ClipboardButton,
33:        <ClipboardButton
40:        </ClipboardButton>

packages/grafana-ui/src/components/ClipboardButton/ClipboardButton.mdx
2:import { ClipboardButton } from './ClipboardButton';
4:<Meta title="MDX|ClipboardButton" component={ClipboardButton} />
6:# ClipboardButton
13:<ClipboardButton
19:</ClipboardButton>
22:<Props of={ClipboardButton} />

packages/grafana-ui/src/components/ClipboardButton/ClipboardButton.tsx
23:export function ClipboardButton({ onClipboardCopy, onClipboardError, children, getText, ...buttonProps }: Props) {

public/app/features/serviceaccounts/CreateTokenModal.tsx
6:  ClipboardButton,
106:                <ClipboardButton
107:                  className={styles.modalCopyToClipboardButton}
113:                </ClipboardButton>
118:            <ClipboardButton variant="primary" getText={() => token} onClipboardCopy={onCloseInternal}>
120:            </ClipboardButton>
142:    modalCopyToClipboardButton: css`

public/app/angular/angular_wrappers.ts
10:  ClipboardButton,
206:  react2AngularDirective('clipboardButton', ClipboardButton, [

public/app/features/invites/InviteeRow.tsx
5:import { Button, ClipboardButton } from '@grafana/ui';
27:          <ClipboardButton variant="secondary" size="sm" getText={() => invitee.url}>
29:          </ClipboardButton>

public/app/features/dashboard/components/ShareModal/ShareEmbed.tsx
2:import { ClipboardButton, Field, Modal, RadioButtonGroup, Switch, TextArea } from '@grafana/ui';
103:          <ClipboardButton variant="primary" getText={this.getIframeHtml} onClipboardCopy={this.onIframeHtmlCopy}>
105:          </ClipboardButton>

public/app/features/dashboard/components/ShareModal/ShareSnapshot.tsx
2:import { Button, ClipboardButton, Field, Icon, Input, LinkButton, Modal, Select, Spinner } from '@grafana/ui';
265:            <ClipboardButton variant="secondary" getText={this.getSnapshotUrl} onClipboardCopy={this.onSnapshotUrlCopy}>
267:            </ClipboardButton>

public/app/features/dashboard/components/ShareModal/ShareLink.tsx
3:import { Alert, ClipboardButton, Field, FieldSet, Icon, Input, RadioButtonGroup, Switch } from '@grafana/ui';
119:                <ClipboardButton variant="primary" getText={this.getShareUrl} onClipboardCopy={this.onShareUrlCopy}>
121:                </ClipboardButton>

public/app/features/dashboard/components/ShareModal/ViewJsonModal.tsx
2:import { ClipboardButton, CodeEditor, Modal } from '@grafana/ui';
25:        <ClipboardButton getText={getClipboardText} onClipboardCopy={onClipboardCopy}>
27:        </ClipboardButton>

public/app/features/dashboard/components/SaveDashboard/forms/SaveProvisionedDashboardForm.tsx
4:import { Button, ClipboardButton, Modal, stylesFactory, TextArea, useTheme } from '@grafana/ui';
64:          <ClipboardButton getText={() => dashboardJSON} onClipboardCopy={onCopyToClipboardSuccess}>
66:          </ClipboardButton>

public/app/features/inspector/QueryInspector.tsx
2:import { Button, ClipboardButton, JSONFormatter, LoadingPlaceholder } from '@grafana/ui';
297:            <ClipboardButton
305:            </ClipboardButton>

public/app/features/playlist/ShareModal.tsx
3:import { Checkbox, ClipboardButton, Field, FieldSet, Icon, Input, Modal, RadioButtonGroup } from '@grafana/ui';
59:              <ClipboardButton variant="primary" getText={() => shareUrl} onClipboardCopy={onShareUrlCopy}>
61:              </ClipboardButton>

public/app/features/alerting/TestRuleResult.tsx
2:import { LoadingPlaceholder, JSONFormatter, Icon, HorizontalGroup, ClipboardButton } from '@grafana/ui';
109:            <ClipboardButton getText={this.getTextForClipboard} onClipboardCopy={this.onClipboardSuccess} icon="copy">
111:            </ClipboardButton>

public/app/features/alerting/unified/components/rules/RuleDetailsActionButtons.tsx
7:import { Button, ConfirmModal, ClipboardButton, HorizontalGroup, LinkButton, useStyles2 } from '@grafana/ui';
190:        <ClipboardButton
203:        </ClipboardButton>
```
