### ISSUE TITLE
Grafana 8.4.1 - Windows Service won't start if log mode = syslog

### ISSUE THREAD

**Issue by UlrichThiess** [grafana/grafana#45729]
Grafana 8.4.1 installation on Windows Server 2019

### Service start failed ###

custom.ini
```
[log]
mode = syslog
```

grafana_service.log
```
panic: Handler is uninitialized for mode "syslog"

goroutine 1 [running]:
github.com/grafana/grafana/pkg/infra/log.ReadLoggingConfig({0xc000780f70, 0x1, 0xc000046a20}, {0xc00081f920, 0x2d}, 0xc000a69f10)
        /drone/src/pkg/infra/log/log.go:407 +0xff9
github.com/grafana/grafana/pkg/setting.(*Cfg).initLogging(0xc0008c2000, 0x4)
        /drone/src/pkg/setting/setting.go:1101 +0x13b
github.com/grafana/grafana/pkg/setting.(*Cfg).loadConfiguration(0xc0008c2000, {{0x0, 0x0}, {0x0, 0x0}, {0xc0000741e0, 0x0, 0x0}})
        /drone/src/pkg/setting/setting.go:771 +0x4ca
github.com/grafana/grafana/pkg/setting.(*Cfg).Load(0xc0008c2000, {{0x0, 0x0}, {0x0, 0x0}, {0xc0000741e0, 0x0, 0x0}})
        /drone/src/pkg/setting/setting.go:859 +0x23b
github.com/grafana/grafana/pkg/setting.NewCfgFromArgs({{0x0, 0x0}, {0x0, 0x0}, {0xc0000741e0, 0x0, 0x0}})
        /drone/src/pkg/setting/setting.go:829 +0x79
github.com/grafana/grafana/pkg/server.Initialize({{0x0, 0x0}, {0x0, 0x0}, {0xc0000741e0, 0x0, 0x0}}, {{0x0, 0x0}, {0x0, ...}, ...}, ...)
        /drone/src/pkg/server/wire_gen.go:119 +0xb6
github.com/grafana/grafana/pkg/cmd/grafana-server/commands.executeServer({0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x41636e4, 0x7}, 0x400, {{0x4710ef8, ...}, ...})
        /drone/src/pkg/cmd/grafana-server/commands/cli.go:170 +0x567
github.com/grafana/grafana/pkg/cmd/grafana-server/commands.RunServer({{0x4710ef8, 0x5}, {0x47127c0, 0xa}, {0x4710ef0, 0x4}, {0x47127b0, 0xa}})
        /drone/src/pkg/cmd/grafana-server/commands/cli.go:107 +0x785
main.main()
        /drone/src/pkg/cmd/grafana-server/main.go:16 +0xc5
```
  
### Service start succeed ###

custom.ini
```
[log]
mode = file
```

**Comment by zuchka** [comment]
possibly related to this larger discussion about the syslog regression:

https://github.com/grafana/grafana/issues/45752

**Comment by mellieA** [comment]
@UlrichThiess are you still seeing this issue with the fix implemented for syslog? https://github.com/grafana/grafana/pull/47209

I'll close it for now, but please reopen or create a new issue and reference this one if it is not resolved.

**Comment by kimboslice99** [comment]
This still appears to be an issue (v10.2.2, win x64)
