### ISSUE TITLE
[Bug] - Cannot read property 'toString' of undefined(...)

### ISSUE THREAD

**Issue by tk-hendrik** [grafana/grafana#4600]
Grafana: 3.0.0-beta21459801392
Ubuntu 14.04 LTS
Elasticsearch 1.4.5 and 2.2.1

```
boot.8698c185.js:36 TypeError: Cannot read property 'toString' of undefined
    at a.isMsResolutionNeeded (https://xxxxxxx/grafana/public/app/boot.8698c185.js:18:21971)
    at h.seriesHandler (https://xxxxxxx/grafana/public/app/boot.8698c185.js:17:3343)
    at Array.map (native)
    at h.onDataReceived (https://xxxxxxx/grafana/public/app/boot.8698c185.js:17:2656)
    at b.__tryOrUnsub (https://xxxxxxx/grafana/public/app/boot.8698c185.js:29:27817)
    at b.next (https://xxxxxxx/grafana/public/app/boot.8698c185.js:29:27163)
    at b._next (https://xxxxxxx/grafana/public/app/boot.8698c185.js:29:26533)
    at b.next (https://xxxxxxx/grafana/public/app/boot.8698c185.js:29:26196)
    at b._finalNext (https://xxxxxxx/grafana/public/app/boot.8698c185.js:30:4282)
    at b._next (https://xxxxxxx/grafana/public/app/boot.8698c185.js:30:4170)(anonymous function) @ boot.8698c185.js:36
boot.8698c185.js:31 Panel data error: TypeError: Cannot read property 'toString' of undefined(…)
```
I've just played around with chrome debugger and I'm not very familar with JS. So just a guess: datapoints[a][0] <<-- In my situation datapoints itself is an array but has no sub-array.

Regards,
Hendrik

**Comment by torkelo** [comment]
Could you describe where you get this? What is your elasticsearch query? What is the elasticsearch response? (Chrome dev tools network tab)

**Comment by tk-hendrik** [comment]
Add Panel -> Graph
Metrics: 
Query (empty)
Alias (empty)
Metric Count
Group by: Terms value: tags   (TOP10, Order by: Term value)

No other configuration for this panel.

Request: 
```
{
   "search_type":"count",
   "ignore_unavailable":true,
   "index":[
      "cif.observables-2016.04.07",
      "cif.observables-2016.04.08"
   ]
}{
   "size":0,
   "query":{
      "filtered":{
         "query":{
            "query_string":{
               "analyze_wildcard":true,
               "query":"*"
            }
         },
         "filter":{
            "bool":{
               "must":[
                  {
                     "range":{
                        "@timestamp":{
                           "gte":"1460072712600",
                           "lte":"1460094312600"
                        }
                     }
                  }
               ]
            }
         }
      }
   },
   "aggs":{
      "2":{
         "terms":{
            "field":"tags",
            "size":10,
            "order":{
               "_term":"desc"
            }
         },
         "aggs":{

         }
      }
   }
}
```

Response:
```
{
   "responses":[
      {
         "took":29,
         "timed_out":false,
         "_shards":{
            "total":10,
            "successful":10,
            "failed":0
         },
         "hits":{
            "total":222881,
            "max_score":0.0,
            "hits":[

            ]
         },
         "aggregations":{
            "2":{
               "doc_count_error_upper_bound":0,
               "sum_other_doc_count":283077,
               "buckets":[
                  {
                     "key":"zeus",
                     "doc_count":2380
                  },
                  {
                     "key":"whitelist",
                     "doc_count":9589
                  },
                  {
                     "key":"url",
                     "doc_count":16
                  },
                  {
                     "key":"uce",
                     "doc_count":42
                  },
                  {
                     "key":"torexitnode",
                     "doc_count":966
                  },
                  {
                     "key":"suspicious",
                     "doc_count":13355
                  },
                  {
                     "key":"spam",
                     "doc_count":1535
                  },
                  {
                     "key":"scanner",
                     "doc_count":19060
                  },
                  {
                     "key":"rdata",
                     "doc_count":149179
                  },
                  {
                     "key":"ransomwaretracker",
                     "doc_count":4609
                  }
               ]
            }
         }
      }
   ]
}

```

**Comment by torkelo** [comment]
You need to group by time as well when used with graph panel. It does not support non time based data (yet). Sorry for bad error message in this case. 

The table panel should support this type of query I think

**Comment by tk-hendrik** [comment]
Table panel works great, indeed.

Of course the questions:
Is it planned to support to  group by non time data?
Otherwise: Any suggestions how hard it would be to implement? Would work on a PR for that.

**Comment by torkelo** [comment]
Yes, support to graph non time based histograms would be great. And a PR woulfor be appreciated indeed :heart

**Comment by tk-hendrik** [comment]
$0.02 for a hint where to dive into and i'll give it a try.
