### ISSUE TITLE
Grafana on s390x - big-endian arch

### ISSUE THREAD

**Issue by eaibmz** [grafana/grafana#46269]
Hi,

i tried to build the official Grafana Docker image and got this error:

```
$ docker build --no-cache  -f Dockerfile -t grafana-tmp .
Sending build context to Docker daemon  53.22MB
Step 1/48 : FROM node:16-alpine3.15 as js-builder
 ---> 6dbfb9ef845e
Step 2/48 : ENV NODE_OPTIONS=--max_old_space_size=8000
 ---> Running in fbfc572d509f
Removing intermediate container fbfc572d509f
 ---> 84e0cd1bfdfb
Step 3/48 : WORKDIR /grafana
 ---> Running in bed7f248b293
Removing intermediate container bed7f248b293
 ---> 1770e7176b99
Step 4/48 : COPY package.json yarn.lock .yarnrc.yml ./
 ---> 9e666a4189cd
Step 5/48 : COPY .yarn .yarn
 ---> 296cd1eabfef
Step 6/48 : COPY packages packages
 ---> 584a24773fd9
Step 7/48 : COPY plugins-bundled plugins-bundled
 ---> eaf50c723eb6
Step 8/48 : RUN yarn install
 ---> Running in dc5e4b267659
Internal Error: Execution failed with a non-error rejection (rejected value: "Runtime error: expected the system to be little-endian!")
    at oo.error (/grafana/.yarn/releases/yarn-3.1.0.cjs:377:305)
    at r (/grafana/.yarn/releases/yarn-3.1.0.cjs:448:10660)
The command '/bin/sh -c yarn install' returned a non-zero code: 1
```

**Environment**:
- Grafana version: 8.4.3

Version 8.4.3 doesn't work but version 8.2.7 still works.

Regards
Alex

**Comment by eaibmz** [comment]
https://github.com/yarnpkg/berry/issues/2745
