### ISSUE TITLE
The test for the package "./pkg/services/ngalert/schedule” and "./pkg/expr" fails on linux/arm64.

### ISSUE THREAD

**Issue by zhangfannie** [grafana/grafana#46395]
**What happened**:
Use "go test" to test “./pkg/services/ngalert/schedule” and "./pkg/expr" packages, both of them are failed.

**What you expected to happen**:
pass

**How to reproduce it (as minimally and precisely as possible)**:
1. download grafana source code: git clone https://github.com/grafana/grafana.git
2. download golang source code: git clone https://github.com/golang/go.git
3. build a master go: cd src && ./make.bash
4. test "./pkg/services/ngalert/schedule” and "./pkg/expr" packages.
  4.1. cd grafana/pkg/services/ngalert/schedule && go test 
  It reports the following errors.
```
unexpected fault address 0x8000101
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8000101 pc=0x41e188]

goroutine 414 [running]:
runtime.throw({0x176aeeb?, 0x200000050?})
        /home/fanzha02/work/go_project/gotest/src/runtime/panic.go:992 +0x50 fp=0x4000d92f00 sp=0x4000d92ed0 pc=0x4471a0
runtime.sigpanic()
        /home/fanzha02/work/go_project/gotest/src/runtime/signal_unix.go:825 +0x1a4 fp=0x4000d92f30 sp=0x4000d92f00 pc=0x45e894
runtime.mapiternext(0x4000f47c10)
        /home/fanzha02/work/go_project/gotest/src/runtime/map.go:913 +0x1a8 fp=0x4000d92fb0 sp=0x4000d92f40 pc=0x41e188
runtime.mapiterinit(0xffff8a42e108?, 0x30?, 0x4000800400?)
        /home/fanzha02/work/go_project/gotest/src/runtime/map.go:861 +0x2f4 fp=0x4000d92fe0 sp=0x4000d92fb0 pc=0x41dfa4
reflect.mapiterinit(0x4000d93048?, 0x102059c?, 0x4000d93048?)
        /home/fanzha02/work/go_project/gotest/src/runtime/map.go:1373 +0x20 fp=0x4000d93010 sp=0x4000d92fe0 pc=0x474320
gonum.org/v1/gonum/graph/iterator.(*mapIter).next(0x4000f47c20)
    /home/fanzha02/go/pkg/mod/gonum.org/v1/gonum@v0.9.3/graph/iterator/map.go:97 +0x5c fp=0x4000d93030 sp=0x4000d93010 pc=0xd510ec
gonum.org/v1/gonum/graph/iterator.(*Nodes).Next(0x4000f63c20)  
/home/fanzha02/go/pkg/mod/gonum.org/v1/gonum@v0.9.3/graph/iterator/nodes_map.go:40 +0x3c fp=0x4000d93050 sp=0x4000d93030 pc=0xd511ac
github.com/grafana/grafana/pkg/expr.buildGraphEdges(0x40003d88c0, 0x4000f638f0?)
        /home/fanzha02/sharefolder/asanprojecttest/grafana/pkg/expr/graph.go:174 +0x160 fp=0x4000d93170 sp=0x4000d93050 pc=0x1020600
github.com/grafana/grafana/pkg/expr.(*Service).buildDependencyGraph(0x4000d931b8?, 0x10234b4?)
        /home/fanzha02/sharefolder/asanprojecttest/grafana/pkg/expr/graph.go:87 +0x38 fp=0x4000d931a0 sp=0x4000d93170 pc=0x101fcd8
github.com/grafana/grafana/pkg/expr.(*Service).buildPipeline(0x0?, 0xe7791b0b1?)
        /home/fanzha02/sharefolder/asanprojecttest/grafana/pkg/expr/graph.go:65 +0x20 fp=0x4000d931c0 sp=0x4000d931a0 pc=0x101fc20
...
```
  4.2. cd grafana/pkg/expr && go test
  It reports the following errors.
```
unexpected fault address 0x7000103
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7000103 pc=0x41e188]

goroutine 302 [running]:
runtime.throw({0x1190eae?, 0x418a0c?})
        /home/fanzha02/work/go_project/gotest/src/runtime/panic.go:992 +0x50 fp=0x40002d0bd0 sp=0x40002d0ba0 pc=0x4471a0
runtime.sigpanic()
        /home/fanzha02/work/go_project/gotest/src/runtime/signal_unix.go:825 +0x1a4 fp=0x40002d0c00 sp=0x40002d0bd0 pc=0x45e844
runtime.mapiternext(0x400045d850)
        /home/fanzha02/work/go_project/gotest/src/runtime/map.go:913 +0x1a8 fp=0x40002d0c80 sp=0x40002d0c10 pc=0x41e188
runtime.mapiterinit(0xffffbb120108?, 0x30?, 0x1b3bc20?)
        /home/fanzha02/work/go_project/gotest/src/runtime/map.go:861 +0x2f4 fp=0x40002d0cb0 sp=0x40002d0c80 pc=0x41dfa4
reflect.mapiterinit(0x40002d0d18?, 0xe9c13c?, 0x40002d0d18?)
        /home/fanzha02/work/go_project/gotest/src/runtime/map.go:1373 +0x20 fp=0x40002d0ce0 sp=0x40002d0cb0 pc=0x4742d0
gonum.org/v1/gonum/graph/iterator.(*mapIter).next(0x400045d860)
        /home/fanzha02/go/pkg/mod/gonum.org/v1/gonum@v0.9.3/graph/iterator/map.go:97 +0x5c fp=0x40002d0d00 sp=0x40002d0ce0 pc=0x70aefc
gonum.org/v1/gonum/graph/iterator.(*Nodes).Next(0x400034f650)
        /home/fanzha02/go/pkg/mod/gonum.org/v1/gonum@v0.9.3/graph/iterator/nodes_map.go:40 +0x3c fp=0x40002d0d20 sp=0x40002d0d00 pc=0x70afbc
github.com/grafana/grafana/pkg/expr.buildGraphEdges(0x40003da840, 0x400034f2c0?)
        /home/fanzha02/sharefolder/asanprojecttest/grafana/pkg/expr/graph.go:174 +0x160 fp=0x40002d0e40 sp=0x40002d0d20 pc=0xe9c1a0
github.com/grafana/grafana/pkg/expr.(*Service).buildDependencyGraph(0x521817?, 0x18bb888?)
        /home/fanzha02/sharefolder/asanprojecttest/grafana/pkg/expr/graph.go:87 +0x38 fp=0x40002d0e70 sp=0x40002d0e40 pc=0xe9b878
github.com/grafana/grafana/pkg/expr.(*Service).buildPipeline(0x15c5883?, 0x3c?)
        /home/fanzha02/sharefolder/asanprojecttest/grafana/pkg/expr/graph.go:65 +0x20 fp=0x40002d0e90 sp=0x40002d0e70 pc=0xe9b7c0
...
```

**Comment by Elfo404** [comment]
looping in both @grafana/backend-platform and @grafana/alerting-squad-backend

**Comment by wbrowne** [comment]
@zhangfannie did you follow [Grafana's developer guide](https://github.com/grafana/grafana/blob/main/contribute/developer-guide.md) to setup Grafana? If not I recommend you do so as that is the expected way to develop with Grafana

**Comment by zhangfannie** [comment]
@wbrowne I did not setup Grafana and I am not a user of Grafana. I just use `go` command to test the correctness of the *_test.go cases. Thank you.

**Comment by wbrowne** [comment]
@zhangfannie  Could you please provide the follow missing information from the Grafana bug report template;

```
**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:
```

**Comment by kylebrandt** [comment]
I can replicate this with `main` and `gotip` (See below). That being said, building Grafana with development / unreleased versions of Go is not supported. So closing this unless there is a released version of Go that this is happening with (For now I am assuming not). The supported version of go would be the version in the `go.mod` file for main.

Should this still happen with a actual Go release (or if it is, in which case please reopen) then once we update or `go.mod` file these tests would fail, so we wouldn't be doing that until the problem is resolved. So it will resurface again if it is an issue that survives to a Go release.

```
# kbrandt @ kbrandt-ws in ~/go/github.com/grafana/grafana/pkg/expr on git:main o [11:49:03] 
$ gotip version
go version devel go1.18-c5c1955 Thu Dec 2 18:02:46 2021 +0000 linux/amd64

# kbrandt @ kbrandt-ws in ~/go/github.com/grafana/grafana/pkg/expr on git:main o [11:49:07] 
$ git log | head -n1 
commit 5a5def6de7a9638e9a204ece32db1bd69e26d86c
# kbrandt @ kbrandt-ws in ~/go/github.com/grafana/grafana/pkg/expr on git:main o [11:49:29] 
$ gotip test
unexpected fault address 0x2000100
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2000100 pc=0x418a0a]

goroutine 33 [running]:
runtime.throw({0x12b2fe7?, 0x4135f5?})
        /home/kbrandt/sdk/gotip/src/runtime/panic.go:992 +0x71 fp=0xc000086bf8 sp=0xc000086bc8 pc=0x440e11
runtime.sigpanic()
        /home/kbrandt/sdk/gotip/src/runtime/signal_unix.go:804 +0x305 fp=0xc000086c48 sp=0xc000086bf8 pc=0x457245
runtime.mapiternext(0xc0002d67f0)
        /home/kbrandt/sdk/gotip/src/runtime/map.go:913 +0x18a fp=0xc000086cb8 sp=0xc000086c48 pc=0x418a0a
runtime.mapiterinit(0x7f77acbf05b8?, 0x30?, 0x1d42a00?)
        /home/kbrandt/sdk/gotip/src/runtime/map.go:861 +0x228 fp=0xc000086cd8 sp=0xc000086cb8 pc=0x418828
reflect.mapiterinit(0x120?, 0xc000086d30?, 0xc000086d30?)
        /home/kbrandt/sdk/gotip/src/runtime/map.go:1373 +0x19 fp=0xc000086d00 sp=0xc000086cd8 pc=0x46da99
gonum.org/v1/gonum/graph/iterator.(*mapIter).next(0xc0002d6800)
        /home/kbrandt/go/pkg/mod/gonum.org/v1/gonum@v0.9.3/graph/iterator/map.go:89 +0x5e fp=0xc000086d20 sp=0xc000086d00 pc=0x7392fe
gonum.org/v1/gonum/graph/iterator.(*Nodes).Next(0xc0002deb10)
        /home/kbrandt/go/pkg/mod/gonum.org/v1/gonum@v0.9.3/graph/iterator/nodes_map.go:40 +0x36 fp=0xc000086d40 sp=0xc000086d20 pc=0x7393d6
github.com/grafana/grafana/pkg/expr.buildGraphEdges(0xc00030e060, 0xc0002de780?)
        /home/kbrandt/go/github.com/grafana/grafana/pkg/expr/graph.go:174 +0x16b fp=0xc000086e58 sp=0xc000086d40 pc=0xfb28ab
github.com/grafana/grafana/pkg/expr.(*Service).buildDependencyGraph(0xc00030c808?, 0x522073?)
        /home/kbrandt/go/github.com/grafana/grafana/pkg/expr/graph.go:87 +0x35 fp=0xc000086e80 sp=0xc000086e58 pc=0xfb1ed5
github.com/grafana/grafana/pkg/expr.(*Service).buildPipeline(0xf?, 0x17b0f57?)
        /home/kbrandt/go/github.com/grafana/grafana/pkg/expr/graph.go:65 +0x19 fp=0xc000086ea0 sp=0xc000086e80 pc=0xfb1e39
github.com/grafana/grafana/pkg/expr.TestServicebuildPipeLine.func1(0x40ed19?)
        /home/kbrandt/go/github.com/grafana/grafana/pkg/expr/graph_test.go:232 +0x4a fp=0xc000086f70 sp=0xc000086ea0 pc=0xfb83ca
testing.tRunner(0xc0002781a0, 0xc000308408)
        /home/kbrandt/sdk/gotip/src/testing/testing.go:1410 +0x102 fp=0xc000086fc0 sp=0xc000086f70 pc=0x522142
testing.(*T).Run.func1()
        /home/kbrandt/sdk/gotip/src/testing/testing.go:1457 +0x2a fp=0xc000086fe0 sp=0xc000086fc0 pc=0x522fea
runtime.goexit()
        /home/kbrandt/sdk/gotip/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000086fe8 sp=0xc000086fe0 pc=0x4741a1
created by testing.(*T).Run
        /home/kbrandt/sdk/gotip/src/testing/testing.go:1457 +0x35f

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0003269c0, {0x12ccdb4?, 0x521b25?}, 0x1326c08)
        /home/kbrandt/sdk/gotip/src/testing/testing.go:1458 +0x37a
testing.runTests.func1(0xc0003269c0?)
        /home/kbrandt/sdk/gotip/src/testing/testing.go:1810 +0x6e
testing.tRunner(0xc0003269c0, 0xc00073fcd8)
        /home/kbrandt/sdk/gotip/src/testing/testing.go:1410 +0x102
testing.runTests(0xc0000be000?, {0x1cdd040, 0x5, 0x5}, {0x7f77acbf05b8?, 0x40?, 0x1d41ee0?})
        /home/kbrandt/sdk/gotip/src/testing/testing.go:1808 +0x457
testing.(*M).Run(0xc0000be000)
        /home/kbrandt/sdk/gotip/src/testing/testing.go:1690 +0x5d9
main.main()
        _testmain.go:55 +0x1aa

goroutine 56 [select]:
go.opentelemetry.io/otel/sdk/trace.(*batchSpanProcessor).processQueue(0xc000391a40)
        /home/kbrandt/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.0.0/trace/batch_span_processor.go:243 +0x12c
go.opentelemetry.io/otel/sdk/trace.NewBatchSpanProcessor.func1()
        /home/kbrandt/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.0.0/trace/batch_span_processor.go:111 +0x65
created by go.opentelemetry.io/otel/sdk/trace.NewBatchSpanProcessor
        /home/kbrandt/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.0.0/trace/batch_span_processor.go:109 +0x245

goroutine 32 [chan receive]:
testing.(*T).Run(0xc000327d40, {0x12c80dd?, 0x67?}, 0xc000308408)
        /home/kbrandt/sdk/gotip/src/testing/testing.go:1458 +0x37a
github.com/grafana/grafana/pkg/expr.TestServicebuildPipeLine(0x40ed19?)
        /home/kbrandt/go/github.com/grafana/grafana/pkg/expr/graph_test.go:231 +0x183c
testing.tRunner(0xc000327d40, 0x1326c08)
        /home/kbrandt/sdk/gotip/src/testing/testing.go:1410 +0x102
created by testing.(*T).Run
        /home/kbrandt/sdk/gotip/src/testing/testing.go:1457 +0x35f
exit status 2
FAIL    github.com/grafana/grafana/pkg/expr     0.013s
```

**Comment by zhangfannie** [comment]
@kylebrandt The go1.18rc has added `-asan` option, which can detect memory access errors. 

<1>. For the package `pkg/services/ngalert/schedule`, when we use `go1.18rc -asan test`,  `-asan` option can provide more useful information.
```
==126245==ERROR: AddressSanitizer: use-after-poison on address 0x20400062b9c8 at pc 0x00000116d7cc bp 0x000000000000 sp 0x2040006c2a70
READ of size 16 at 0x20400062b9c8 thread T8
    #0 0x116d7cb in gonum.org/v1/gonum/graph/iterator.(*mapIter).node /home/fanzha02/go/pkg/mod/gonum.org/v1/gonum@v0.9.3/graph/iterator/map.go:89
    #1 0xffffb1941c47  (/usr/lib/aarch64-linux-gnu/libasan.so.4+0xdac47)
    #2 0x484a6f in asancall /home/fanzha02/go_release/go/src/runtime/asan_arm64.s:66

Address 0x20400062b9c8 is a wild pointer.
SUMMARY: AddressSanitizer: use-after-poison /home/fanzha02/go/pkg/mod/gonum.org/v1/gonum@v0.9.3/graph/iterator/map.go:89 in gonum.org/v1/gonum/graph/iterator.(*mapIter).node
Shadow bytes around the buggy address:
  0x0418000c56e0: 00 00 f7 f7 00 00 f7 f7 00 00 f7 f7 00 00 f7 f7
  0x0418000c56f0: 00 00 f7 f7 00 00 f7 f7 00 00 f7 f7 00 00 f7 f7
  0x0418000c5700: 00 00 f7 f7 00 00 f7 f7 00 00 f7 f7 00 00 f7 f7
  0x0418000c5710: 00 00 f7 f7 00 00 f7 f7 00 00 f7 f7 00 00 f7 f7
  0x0418000c5720: 00 00 f7 f7 00 00 f7 f7 00 00 f7 f7 00 00 f7 f7
=>0x0418000c5730: 00 00 f7 f7 00 00 f7 f7 00[00]f7 f7 00 00 00 00
  0x0418000c5740: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0418000c5750: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0418000c5760: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0418000c5770: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0418000c5780: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
```

<2>. For the package pkg/expr, -asan option reports the information as below. Because the compiler will set -d=checkptr=1 implicitly when -asan is enabled.
```
fatal error: checkptr: converted pointer straddles multiple allocations

goroutine 292 [running]:
runtime.throw({0x17acaef?, 0x86729c?})
        /home/fanzha02/go_release/go/src/runtime/panic.go:992 +0x50 fp=0x20400054fc70 sp=0x20400054fc40 pc=0x453d80
runtime.checkptrAlignment(0x20400054fcc8?, 0x8675f4?, 0x2040009ed2c8?)
        /home/fanzha02/go_release/go/src/runtime/checkptr.go:26 +0x80 fp=0x20400054fc90 sp=0x20400054fc70 pc=0x422520
gonum.org/v1/gonum/graph/iterator.(*mapIter).node(0x2040005470c0)
        /home/fanzha02/go/pkg/mod/gonum.org/v1/gonum@v0.9.3/graph/iterator/map.go:89 +0x8c fp=0x20400054fcd0 sp=0x20400054fc90 pc=0x8672bc
gonum.org/v1/gonum/graph/iterator.(*Nodes).Next(0x2040009ed2c0)
        /home/fanzha02/go/pkg/mod/gonum.org/v1/gonum@v0.9.3/graph/iterator/nodes_map.go:43 +0xd0 fp=0x20400054fd30 sp=0x20400054fcd0 pc=0x867600
github.com/grafana/grafana/pkg/expr.buildNodeRegistry(0x204000982de0)
        /home/fanzha02/sharefolder/asanprojecttest/grafana/pkg/expr/graph.go:115 +0x26c fp=0x20400054fde0 sp=0x20400054fd30 pc=0x133174c
github.com/grafana/grafana/pkg/expr.(*Service).buildDependencyGraph(0x2040002cce30?, 0x133a150?)
        /home/fanzha02/sharefolder/asanprojecttest/grafana/pkg/expr/graph.go:85 +0x2c fp=0x20400054fe10 sp=0x20400054fde0 pc=0x13312fc
github.com/grafana/grafana/pkg/expr.(*Service).buildPipeline(0x56e0e7?, 0x2701508?)
        /home/fanzha02/sharefolder/asanprojecttest/grafana/pkg/expr/graph.go:65 +0x20 fp=0x20400054fe30 sp=0x20400054fe10 pc=0x1331250
github.com/grafana/grafana/pkg/expr.TestServicebuildPipeLine.func1(0x2040002e8a00?)
        /home/fanzha02/sharefolder/asanprojecttest/grafana/pkg/expr/graph_test.go:232 +0x50 fp=0x20400054ff20 sp=0x20400054fe30 pc=0x133a160
```

It makes sense to close this issue because of go1.18rc is not a stable release. Hopefully the `-asan` option will provide useful information if the stable go1.18 release reproduces the issue. Thank you.

**Comment by kylebrandt** [comment]
Thanks for the additional information. Guessing it is in our gonum dependency https://github.com/gonum/gonum/issues/1775
