### ISSUE TITLE
Server start failure after 8.5.0 upgrade - RaspberryPi

### ISSUE THREAD

**Issue by chphe** [grafana/grafana#48263]
**What happened**:
Version 8.5.0 won't start on a RaspberryPi. The logging isn't clear on how to resolve the problem.

*** Logging ***

```
unexpected fault address 0x434d5d8,
fatal error: fault,
[signal SIGSEGV: segmentation violation code=0x2 addr=0x434d5d8 pc=0x434d5d8],
,
goroutine 1 [running, locked to thread]:,
runtime.throw({0x27fa6d9, 0x5}),
	/usr/local/go/src/runtime/panic.go:1198 +0x5c fp=0x681bc30 sp=0x681bc1c pc=0x4c44c,
runtime.sigpanic(),
	/usr/local/go/src/runtime/signal_unix.go:742 +0x1d0 fp=0x681bc48 sp=0x681bc30 pc=0x65b1c,
github.com/grafana/grafana/pkg/services/alerting/notifiers.init.10(),
	/drone/src/pkg/services/alerting/notifiers/pushover.go:97 +0x2c fp=0x681bc74 sp=0x681bc4c pc=0x2083e64,
runtime: unexpected return pc for runtime.(*mcache).refill called from 0x0,
stack: frame={sp:0x681bc74, fp:0x681bca4} stack=[0x67fc000,0x681c000),
0x0681bbf4:  0x00000001  0x00000000  0x00000000  0x0004c658 <runtime.fatalthrow+0x00000044> ,
0x0681bc04:  0x0004c44c <runtime.throw+0x0000005c>  0x0681bc0c  0x0004c670 <runtime.fatalthrow.func1+0x00000000>  0x060000f0 ,
0x0681bc14:  0x0004c44c <runtime.throw+0x0000005c>  0x0681bc1c  0x00065b1c <runtime.sigpanic+0x000001d0>  0x0681bc24 ,
0x0681bc24:  0x0004c464 <runtime.throw.func1+0x00000000>  0x027fa6d9  0x00000005  0x02083e64 <github.com/grafana/grafana/pkg/services/alerting/notifiers.init.10+0x0000002c> ,
0x0681bc34:  0x027fa6d9  0x00000005  0x061f37c0  0x0434d5d8 ,
0x0681bc44:  0x060000f0  0x02083e64 <github.com/grafana/grafana/pkg/services/alerting/notifiers.init.10+0x0000002c>  0x00026f28 <runtime.(*mcache).refill+0x00000154>  0x06053dac ,
0x0681bc54:  0x0000002f  0x00000030  0x00000001  0x00000030 ,
0x0681bc64:  0x00555555 <google.golang.org/protobuf/internal/impl.aberrantAppendField+0x0000063d>  0x0612404f  0x00000018  0x00000000 ,
0x0681bc74: <0x00000000  0x00000018  0x00000016  0x0000000b ,
0x0681bc84:  0x00000002  0x0000000e  0x0000001a  0x00000066 ,
0x0681bc94:  0x00000008  0x00000018  0x0001cdd8 <runtime.mallocgc+0x000005e8>  0xb6ed4e68 ,
0x0681bca4: >0x00000000  0x00000000  0x00000000  0x00000000 ,
0x0681bcb4:  0x00000000  0x00000000  0x00000000  0x00000000 ,
0x0681bcc4:  0x00000000  0x00000000  0x00000000  0x00000000 ,
0x0681bcd4:  0x0262d300  0x01000138 <google.golang.org/api/storage/v1.(*DefaultObjectAccessControlsPatchCall).Do+0x00000020>  0x00500100 <google.golang.org/protobuf/internal/filedesc.(*File).unmarshalSeed+0x000001b8>  0xb6ed4e68 ,
0x0681bce4:  0x0000004c  0x00000050  0xb6ec7538  0x00000050 ,
0x0681bcf4:  0x0459a600  0x06124000  0x00067310 <runtime.growslice+0x000004f8>  0x0001d39c <runtime.newobject+0x0000002c> ,
0x0681bd04:  0x0007fd90 <os.runtime_args+0x00000054>  0x00024080 <runtime.typedslicecopy+0x000000c0>  0x06124000  0x0007fdd8 <os.runtime_args+0x0000009c> ,
0x0681bd14:  0x06124000  0x06042000  0x00000048  0x00000000 ,
runtime.(*mcache).refill(0x0, 0x0),
	/usr/local/go/src/runtime/mcache.go:185 +0x154 fp=0x681bca4 sp=0x681bc74 pc=0x26f28,
,
goroutine 134 [chan receive]:,
github.com/golang/glog.(*loggingT).flushDaemon(0x4599698),
	/opt/drone/gomodcache/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x70,
created by github.com/golang/glog.init.0,
	/opt/drone/gomodcache/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:410 +0x214,
,
goroutine 121 [select]:,
go.opentelemetry.io/otel/sdk/trace.(*batchSpanProcessor).processQueue(0x6256840),
	/opt/drone/gomodcache/go.opentelemetry.io/otel/sdk@v1.0.0/trace/batch_span_processor.go:243 +0xf4,
go.opentelemetry.io/otel/sdk/trace.NewBatchSpanProcessor.func1(0x6256840),
	/opt/drone/gomodcache/go.opentelemetry.io/otel/sdk@v1.0.0/trace/batch_span_processor.go:111 +0x4c,
created by go.opentelemetry.io/otel/sdk/trace.NewBatchSpanProcessor,
	/opt/drone/gomodcache/go.opentelemetry.io/otel/sdk@v1.0.0/trace/batch_span_processor.go:109 +0x1e8,
,
goroutine 85 [select]:,
go.opencensus.io/stats/view.(*worker).start(0x62578c0),
	/opt/drone/gomodcache/go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0xa0,
created by go.opencensus.io/stats/view.init.0,
	/opt/drone/gomodcache/go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0x64
```

**What you expected to happen**:
Have Grafana starting without problems.

**How to reproduce it (as minimally and precisely as possible)**:
I experience the problem with the official Docker image ([grafana/grafana:latest](https://hub.docker.com/r/grafana/grafana)). Version 8.4.7 runs fine.
It both happens on a migration from an earlier version, as on a new container without a volume.

**Anything else we need to know?**:

The problem also seems to be on a bare-metal installation. This according to the thread in the community forum: https://community.grafana.com/t/server-start-failure-after-8-5-0-upgrade/64437

I'm following the instructions on:
- https://grafana.com/docs/grafana/latest/installation/docker/
- https://grafana.com/docs/grafana/latest/installation/upgrading/#docker

**Environment**:
- Grafana version: 8.5.0
- OS Grafana is installed on: 
`> hostnamectl`
```
 Operating System: Raspbian GNU/Linux 10 (buster)
 Kernel: Linux 5.10.103-v7l+
 Architecture: arm
```
RaspberryPi 4
- Docker: 
```
Client: Docker Engine - Community
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 24 01:48:21 2022
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 01:46:07 2022
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by chphe** [comment]
This issue is definitely a duplicate of https://github.com/grafana/grafana/issues/48130.
Closing this one.
