### ISSUE TITLE
cannot add annotations on influxdb, does not list datasources

### ISSUE THREAD

**Issue by niv** [grafana/grafana#4857]
* What grafana version are you using?
3.0.0 beta 6, installed via .deb package

* What datasource are you using?
InfluxDB, tested with 0.11 and 0.12.

* What OS are you running grafana on?
Ubuntu 14.04, 64 bit.

The Datasources dropdown for annotations is empty when attempting to add some from influxdb. Opening the annotations edit view emits this error:

```
boot.b99a7b8c.js:35 TypeError: Cannot read property 'name' of undefined
    at n.d.reset (<mydomain>/public/app/boot.b99a7b8c.js:10:20003)
    at n.d.init (<mydomain>/public/app/boot.b99a7b8c.js:10:19569)
    at fn (eval at <anonymous> (<mydomain>/public/app/boot.b99a7b8c.js:37:9107), <anonymous>:4:203)
    at n.$eval (<mydomain>/public/app/boot.b99a7b8c.js:35:25719)
    at pre (<mydomain>/public/app/boot.b99a7b8c.js:37:30302)
    at oa (<mydomain>/public/app/boot.b99a7b8c.js:34:24257)
    at o (<mydomain>/public/app/boot.b99a7b8c.js:34:16475)
    at h (<mydomain>/public/app/boot.b99a7b8c.js:34:12855)
    at <mydomain>/public/app/boot.b99a7b8c.js:34:12386
    at link (<mydomain>/public/app/boot.b99a7b8c.js:37:30225) <div ng-controller="AnnotationsEditorCtrl" ng-init="init()" class="ng-scope">
```

**Comment by torkelo** [comment]
thanks for reporting this! fixed in mater, will try to release beta7 soon.

**Comment by niv** [comment]
Thank you!
