### ISSUE TITLE
Grafana toolkit - signing a plugin error

### ISSUE THREAD

**Issue by CurlyDev1** [grafana/grafana#48903]
**What happened**: Unable to sign plugin running the command 
`$ npm run sign

> aquis-aquis-mac-bulk-uploader@1.0.0 sign /home/usera/plugin
> grafana-toolkit plugin:sign

  Building manifest...
  Signing manifest...
  Error: Error signing manifest: Request failed with status code 502
      at /home/usera/plugins/node_modules/@grafana/toolkit/src/plugins/manifest.js:100:19
      at Generator.throw (<anonymous>)
      at rejected (/home/usera/plugins/node_modules/tslib/tslib.js:115:69)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
`

**What you expected to happen**: I expected the plugin to successfully be signed

**How to reproduce it (as minimally and precisely as possible)**: 

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.3.2
- Grafana toolkit version: v8.5.2
- OS Grafana is installed on: Rocky 8
- Node version: v14.19.1
- npm version: 6.14.16

**Comment by CurlyDev1** [comment]
Cheers I upgraded to node v16.15.0 but still get the same error, I discovered its to with handling requests via proxies and the axios library that the toolkit uses when making the call to the grafana api does not handle proxy requests well.
I've switched to a different environment in the meantime
