### ISSUE TITLE
[Bug] Template Variables Not Working if Field Type is a Number

### ISSUE THREAD

**Issue by forewarned** [grafana/grafana#5144]
The template doesn't work when the field of a variable is a number. When writing a query in a template, I use a field that is a number data type. When putting it in the query of a graph, an error appears on the graph saying "a.replace is not a function" and the graph is empty. When the template query term is replaced with a field string data type, no error appears and the graph shows the data.

Chrome displays the following error information in the console when using a number data type:
boot.js:35 TypeError: a.replace is not a function
    at c (http://localhost/public/app/boot.js:10:29987)
    at http://localhost/public/app/boot.js:10:30695
    at Function._a (http://localhost/public/app/boot.js:40:28129)
    at formatValue (http://localhost/public/app/boot.js:10:30667)
    at http://localhost/public/app/boot.js:10:31863
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at replace (http://localhost/public/app/boot.js:10:31586)
    at h.query (http://localhost/public/app/boot.js:13:13849)
    at h.f.issueQueries **(http://localhost/public/app/boot.js:40:15069)**

Grafana v 3.0.2
Datasource: Elasticsearch
OS: Windows

![brokentemplate](https://cloud.githubusercontent.com/assets/14337073/15480932/0053cfc4-20f6-11e6-9e01-be341bae0ea0.jpg)

**Comment by torkelo** [comment]
this is fixed in 3.0.3
