### ISSUE TITLE
[Bug] Unexpected token when loading custom Home dashboard

### ISSUE THREAD

**Issue by grobie** [grafana/grafana#5167]
Since our upgrade to 3.0.3 we can't use a custom Home dashboard anymore. The page won't load and only show "Unexpected error" notification error. I just upgraded to current master 41deea9, but the problem persists. Workaround is to change the Org home dashboard setting back to "default"

```
SyntaxError: Unexpected token { in JSON at position 25              boot.4c6dcc80.js:35
    at Object.parse (native)
    at X (http://grafana.int.s-cloud.net/public/app/boot.4c6dcc80.js:33:22873)
    at zb (http://grafana.int.s-cloud.net/public/app/boot.4c6dcc80.js:34:31663)
    at http://grafana.int.s-cloud.net/public/app/boot.4c6dcc80.js:35:120
    at f (http://grafana.int.s-cloud.net/public/app/boot.4c6dcc80.js:33:17607)
    at Db (http://grafana.int.s-cloud.net/public/app/boot.4c6dcc80.js:35:102)
    at g (http://grafana.int.s-cloud.net/public/app/boot.4c6dcc80.js:35:829)
    at h (http://grafana.int.s-cloud.net/public/app/boot.4c6dcc80.js:35:19893)
    at http://grafana.int.s-cloud.net/public/app/boot.4c6dcc80.js:35:20065
    at n.$eval (http://grafana.int.s-cloud.net/public/app/boot.4c6dcc80.js:35:27582)
```

**Comment by bergquist** [comment]
Thank you for reporting this.

**Comment by bergquist** [comment]
Fixed by https://github.com/grafana/grafana/commit/8c2b6b532dc97b56639c5e268532793950767177 3.0.4 will contain this fix and be released today.

**Comment by grobie** [comment]
Thank you.
