### ISSUE TITLE
[Bug/Feat] Warn user when sharing unsaved panel or unsaved dashboard

### ISSUE THREAD

**Issue by fg2it** [grafana/grafana#5182]
On grafana v3.0.4 (but it is true for the previous releases too), using influxdb (or --grafana-- test data), on raspberry pi, the following steps lead to a "page not found 404" png being rendered : 
- create a new dashboard
- add a new panel/graph, configure the panel and go back too dashboard
- without saving the dashboard, render the panel (share/Direct link rendered image).

I would expect to see at least the same behavior than I can see when try to render a newly added panel from an already saved dashboard, without saving the dashboard with the newly added panel : a png with "panel not found".

Probably in both cases, skipping the rendering and detecting that the user is trying to share/render an unsaved panel would be cleaner. A uniform way to do so might be to simply prevent sharing in these cases.

The "404" png comes with the following addition in log : 

```
2016/05/25 21:21:54 [I] PhantomRenderer::renderToPng url http://localhost:3000/dashboard-solo/new?panelId=1&from=1464189646190&to=1464211246190&width=1000&height=500
Error: undefined is not an object (evaluating 'b.$$route.pageClass')
        at http://localhost:3000/public/app/boot.16792590.js:28:3862
        at $broadcast (http://localhost:3000/public/app/boot.16792590.js:35:72515)
        at http://localhost:3000/public/app/boot.16792590.js:8:110768
        at h (http://localhost:3000/public/app/boot.16792590.js:35:38008)
        at http://localhost:3000/public/app/boot.16792590.js:35:38180
        at $eval (http://localhost:3000/public/app/boot.16792590.js:35:71124)
        at $digest (http://localhost:3000/public/app/boot.16792590.js:35:69637)
        at $apply (http://localhost:3000/public/app/boot.16792590.js:35:71414)
        at http://localhost:3000/public/app/boot.16792590.js:33:64434
        at g (http://localhost:3000/public/app/boot.16792590.js:34:11271)
        at h (http://localhost:3000/public/app/boot.16792590.js:33:40414)
        at ha (http://localhost:3000/public/app/boot.16792590.js:33:40693)
        at http://localhost:3000/public/app/boot.16792590.js:10:36170
        at O (http://localhost:3000/public/app/boot.16792590.js:6:1544)
        at K (http://localhost:3000/public/app/boot.16792590.js:6:1173)
        at when (http://localhost:3000/public/app/boot.16792590.js:6:4847)
        at run (http://localhost:3000/public/app/boot.16792590.js:6:3886)
        at _drain (http://localhost:3000/public/app/boot.16792590.js:5:106378)
        at drain (http://localhost:3000/public/app/boot.16792590.js:5:78699)

  http://localhost:3000/public/app/boot.16792590.js:35
```

On the contrary, the "panel not found" png comes with :

```
2016/05/25 21:29:04 [I] PhantomRenderer::renderToPng url http://localhost:3000/dashboard-solo/db/new-dashboard?panelId=2&from=1464190075140&to=1464211675140&width=1000&height=500
2016/05/25 21:29:10 [I] Completed 192.168.1.225 - "GET /render/dashboard-solo/db/new-dashboard HTTP/1.1" 302 Found 29 bytes in 2059us
```

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
