### ISSUE TITLE
Tempo traces not viewable in Grafana 9.0.2

### ISSUE THREAD

**Issue by bilbof** [grafana/grafana#51955]
**What happened**:

When viewing a Tempo trace in Grafana v9.0.2:

```
An unexpected error happened
Details
TypeError: Cannot read properties of undefined (reading 'datasourceName')

    at Ce (https://t-grafana/public/build/4027.8dfc68b1a209650f62f9.js:4720:58)
    at WithTheme(UnthemedSpanBarRow)
    at div
    at div
    at div
    at div
    at g (https://t-grafana/public/build/4027.8dfc68b1a209650f62f9.js:4299:2473)
    at dt (https://t-grafana/public/build/4027.8dfc68b1a209650f62f9.js:4925:594)
    at WithTheme(undefined)
```

![image](https://user-images.githubusercontent.com/8124374/177949971-f27c0907-a097-4286-941c-b41736d47034.png)

**What you expected to happen**:

Be able to view traces - viewable in Grafana 8.5

**How to reproduce it (as minimally and precisely as possible)**:

Not sure - no traces are currently viewable

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.0.5
- Data source type & version: Tempo created through the UI
- OS Grafana is installed on: Kubernetes
- User OS & Browser: Windows and Linux, Chrome
- Grafana plugins: None
- Others: None

**Comment by bilbof** [comment]
Recreating the Tempo data source through the UI resolves the issue
