### ISSUE TITLE
panic: unexpected handler type: func(*models.ReqContext) bool

### ISSUE THREAD

**Issue by simondeziel** [grafana/grafana#53793]
**What happened**:

Upgraded grafana deb package from 9.0.7 -> 9.1.0 and grafana-server started crashing. Here's the journalctl output:

```
Aug 16 16:57:04 metrics grafana-server[131]: logger=server t=2022-08-16T16:57:04.236103198Z level=info msg="Shutdown started" reason="System signal: terminated"
Aug 16 16:57:04 metrics grafana-server[131]: logger=tracing t=2022-08-16T16:57:04.236426916Z level=info msg="Closing tracing"
Aug 16 16:57:04 metrics systemd[1]: Stopping Grafana instance...
Aug 16 16:57:04 metrics grafana-server[131]: logger=ngalert t=2022-08-16T16:57:04.238577636Z level=error msg="unable to fetch orgIds" msg="context canceled"
Aug 16 16:57:04 metrics systemd[1]: grafana-server.service: Deactivated successfully.
Aug 16 16:57:04 metrics systemd[1]: Stopped Grafana instance.
Aug 16 16:57:04 metrics systemd[1]: grafana-server.service: Consumed 55.412s CPU time.
Aug 16 16:57:04 metrics systemd[1]: Started Grafana instance.
Aug 16 16:57:04 metrics grafana-server[2229]: logger=settings t=2022-08-16T16:57:04.705705209Z level=info msg="Starting Grafana" version=9.1.0 commit=82e32447b4 branch=HEAD compiled=2022-08-16T09:30:13Z
Aug 16 16:57:04 metrics grafana-server[2229]: logger=settings t=2022-08-16T16:57:04.706730991Z level=info msg="Config loaded from" file=/usr/share/grafana/conf/defaults.ini
Aug 16 16:57:04 metrics grafana-server[2229]: logger=settings t=2022-08-16T16:57:04.706775193Z level=info msg="Config loaded from" file=/etc/grafana/grafana.ini
Aug 16 16:57:04 metrics grafana-server[2229]: logger=settings t=2022-08-16T16:57:04.706805644Z level=info msg="Config overridden from command line" arg="default.paths.data=/var/lib/grafana"
Aug 16 16:57:04 metrics grafana-server[2229]: logger=settings t=2022-08-16T16:57:04.706868657Z level=info msg="Config overridden from command line" arg="default.paths.logs=/var/log/grafana"
Aug 16 16:57:04 metrics grafana-server[2229]: logger=settings t=2022-08-16T16:57:04.706898913Z level=info msg="Config overridden from command line" arg="default.paths.plugins=/var/lib/grafana/plugins"
Aug 16 16:57:04 metrics grafana-server[2229]: logger=settings t=2022-08-16T16:57:04.706928023Z level=info msg="Config overridden from command line" arg="default.paths.provisioning=/etc/grafana/provisioning"
Aug 16 16:57:04 metrics grafana-server[2229]: logger=settings t=2022-08-16T16:57:04.706972521Z level=info msg="Path Home" path=/usr/share/grafana
Aug 16 16:57:04 metrics grafana-server[2229]: logger=settings t=2022-08-16T16:57:04.707010839Z level=info msg="Path Data" path=/var/lib/grafana
Aug 16 16:57:04 metrics grafana-server[2229]: logger=settings t=2022-08-16T16:57:04.707061485Z level=info msg="Path Logs" path=/var/log/grafana
Aug 16 16:57:04 metrics grafana-server[2229]: logger=settings t=2022-08-16T16:57:04.707090996Z level=info msg="Path Plugins" path=/var/lib/grafana/plugins
Aug 16 16:57:04 metrics grafana-server[2229]: logger=settings t=2022-08-16T16:57:04.707120171Z level=info msg="Path Provisioning" path=/etc/grafana/provisioning
Aug 16 16:57:04 metrics grafana-server[2229]: logger=settings t=2022-08-16T16:57:04.707149918Z level=info msg="App mode production"
Aug 16 16:57:04 metrics grafana-server[2229]: logger=sqlstore t=2022-08-16T16:57:04.707889677Z level=info msg="Connecting to DB" dbtype=sqlite3
Aug 16 16:57:04 metrics grafana-server[2229]: logger=migrator t=2022-08-16T16:57:04.747652201Z level=info msg="Starting DB migrations"
Aug 16 16:57:04 metrics grafana-server[2229]: logger=migrator t=2022-08-16T16:57:04.762133054Z level=info msg="Executing migration" id="Add last_used_at to api_key table"
Aug 16 16:57:04 metrics grafana-server[2229]: logger=migrator t=2022-08-16T16:57:04.87902168Z level=info msg="Executing migration" id="add rule_group_idx column to alert_rule"
Aug 16 16:57:04 metrics grafana-server[2229]: logger=migrator t=2022-08-16T16:57:04.883355874Z level=info msg="Executing migration" id="add rule_group_idx column to alert_rule_version"
Aug 16 16:57:04 metrics grafana-server[2229]: logger=migrator t=2022-08-16T16:57:04.892263798Z level=info msg="Executing migration" id="create correlation table v1"
Aug 16 16:57:04 metrics grafana-server[2229]: logger=migrator t=2022-08-16T16:57:04.895584215Z level=info msg="Executing migration" id="drop index UQE_dashboard_public_config_uid - v1"
Aug 16 16:57:04 metrics grafana-server[2229]: logger=migrator t=2022-08-16T16:57:04.903463587Z level=info msg="Executing migration" id="drop index IDX_dashboard_public_config_org_id_dashboard_uid - v1"
Aug 16 16:57:04 metrics grafana-server[2229]: logger=migrator t=2022-08-16T16:57:04.906504878Z level=info msg="Executing migration" id="Drop old dashboard public config table"
Aug 16 16:57:04 metrics grafana-server[2229]: logger=migrator t=2022-08-16T16:57:04.909479697Z level=info msg="Executing migration" id="recreate dashboard public config v1"
Aug 16 16:57:04 metrics grafana-server[2229]: logger=migrator t=2022-08-16T16:57:04.912532625Z level=info msg="Executing migration" id="drop index UQE_dashboard_public_config_uid - v2"
Aug 16 16:57:04 metrics grafana-server[2229]: logger=migrator t=2022-08-16T16:57:04.912739021Z level=warn msg="Skipping migration: Already executed, but not recorded in migration log" id="drop index UQE_dashboard_public_config_uid - v2"
Aug 16 16:57:04 metrics grafana-server[2229]: logger=migrator t=2022-08-16T16:57:04.915228518Z level=info msg="Executing migration" id="drop index IDX_dashboard_public_config_org_id_dashboard_uid - v2"
Aug 16 16:57:04 metrics grafana-server[2229]: logger=migrator t=2022-08-16T16:57:04.915577473Z level=warn msg="Skipping migration: Already executed, but not recorded in migration log" id="drop index IDX_dashboard_public_config_org_id_dashboard_uid - v2"
Aug 16 16:57:04 metrics grafana-server[2229]: logger=migrator t=2022-08-16T16:57:04.917929318Z level=info msg="Executing migration" id="Drop public config table"
Aug 16 16:57:04 metrics grafana-server[2229]: logger=migrator t=2022-08-16T16:57:04.923455947Z level=info msg="Executing migration" id="Recreate dashboard public config v2"
Aug 16 16:57:04 metrics grafana-server[2229]: logger=migrator t=2022-08-16T16:57:04.926380141Z level=info msg="Executing migration" id="create index UQE_dashboard_public_config_uid - v2"
Aug 16 16:57:04 metrics grafana-server[2229]: logger=migrator t=2022-08-16T16:57:04.933913867Z level=info msg="Executing migration" id="create index IDX_dashboard_public_config_org_id_dashboard_uid - v2"
Aug 16 16:57:04 metrics grafana-server[2229]: logger=migrator t=2022-08-16T16:57:04.937134465Z level=info msg="Executing migration" id="create index UQE_dashboard_public_config_access_token - v2"
Aug 16 16:57:04 metrics grafana-server[2229]: logger=migrator t=2022-08-16T16:57:04.944988103Z level=info msg="Executing migration" id="Rename table dashboard_public_config to dashboard_public - v2"
Aug 16 16:57:04 metrics grafana-server[2229]: logger=migrator t=2022-08-16T16:57:04.954152278Z level=info msg="Executing migration" id="update group index for alert rules"
Aug 16 16:57:04 metrics grafana-server[2229]: logger=migrator t=2022-08-16T16:57:04.956928996Z level=info msg="migrations completed" performed=17 skipped=425 duration=195.288899ms
Aug 16 16:57:05 metrics grafana-server[2229]: logger=plugin.manager t=2022-08-16T16:57:05.025791561Z level=info msg="Plugin registered" pluginId=input
Aug 16 16:57:05 metrics grafana-server[2229]: logger=plugin.finder t=2022-08-16T16:57:05.02590714Z level=warn msg="Skipping finding plugins as directory does not exist" path=/var/lib/grafana/plugins
Aug 16 16:57:05 metrics grafana-server[2229]: logger=secrets t=2022-08-16T16:57:05.026449094Z level=info msg="Envelope encryption state" enabled=true currentprovider=secretKey.v1
Aug 16 16:57:05 metrics grafana-server[2229]: logger=query_data t=2022-08-16T16:57:05.031682419Z level=info msg="Query Service initialization"
Aug 16 16:57:05 metrics grafana-server[2229]: logger=live.push_http t=2022-08-16T16:57:05.048411427Z level=info msg="Live Push Gateway initialization"
Aug 16 16:57:05 metrics grafana-server[2229]: logger=ticker t=2022-08-16T16:57:05.068159067Z level=info msg=starting first_tick=2022-08-16T16:57:10Z
Aug 16 16:57:05 metrics grafana-server[2229]: logger=infra.usagestats.collector t=2022-08-16T16:57:05.209696003Z level=info msg="registering usage stat providers" usageStatsProvidersLen=2
Aug 16 16:57:05 metrics grafana-server[2229]: logger=server t=2022-08-16T16:57:05.210133362Z level=info msg="Writing PID file" path=/run/grafana/grafana-server.pid pid=2229
Aug 16 16:57:05 metrics grafana-server[2229]: logger=provisioning.alerting t=2022-08-16T16:57:05.256997706Z level=info msg="starting to provision alerting"
Aug 16 16:57:05 metrics grafana-server[2229]: logger=provisioning.alerting t=2022-08-16T16:57:05.25712278Z level=info msg="finished to provision alerting"
Aug 16 16:57:05 metrics grafana-server[2229]: panic: unexpected handler type: func(*models.ReqContext) bool
Aug 16 16:57:05 metrics grafana-server[2229]: goroutine 351 [running]:
Aug 16 16:57:05 metrics grafana-server[2229]: github.com/grafana/grafana/pkg/api/response.wrap_handler({0x2df48c0, 0x37b50b8})
Aug 16 16:57:05 metrics grafana-server[2229]:         /drone/src/pkg/api/response/web_hack.go:55 +0x27d
Aug 16 16:57:05 metrics grafana-server[2229]: github.com/grafana/grafana/pkg/web.validateAndWrapHandler(...)
Aug 16 16:57:05 metrics grafana-server[2229]:         /drone/src/pkg/web/macaron.go:60
Aug 16 16:57:05 metrics grafana-server[2229]: github.com/grafana/grafana/pkg/web.validateAndWrapHandlers({0xc000766340, 0x4, 0x2f721c0})
Aug 16 16:57:05 metrics grafana-server[2229]:         /drone/src/pkg/web/macaron.go:68 +0x7e
Aug 16 16:57:05 metrics grafana-server[2229]: github.com/grafana/grafana/pkg/web.(*Router).Handle(0xc0019d83c0, {0x35ae874, 0x4}, {0xc0007365a0, 0x13}, {0xc000766340, 0x3, 0x3})
Aug 16 16:57:05 metrics grafana-server[2229]:         /drone/src/pkg/web/router.go:149 +0xec
Aug 16 16:57:05 metrics grafana-server[2229]: github.com/grafana/grafana/pkg/api/routing.(*RouteRegisterImpl).Register(0xc000eaf260, {0x3d2a2a0, 0xc0019d6d20}, {0x0, 0xc001a45cc8, 0x0})
Aug 16 16:57:05 metrics grafana-server[2229]:         /drone/src/pkg/api/routing/route_register.go:133 +0x226
Aug 16 16:57:05 metrics grafana-server[2229]: github.com/grafana/grafana/pkg/api/routing.(*RouteRegisterImpl).Register(0xc00050f180, {0x3d2a2a0, 0xc0019d6d20}, {0x0, 0x8, 0x0})
Aug 16 16:57:05 metrics grafana-server[2229]:         /drone/src/pkg/api/routing/route_register.go:138 +0x9f
Aug 16 16:57:05 metrics grafana-server[2229]: github.com/grafana/grafana/pkg/api.(*HTTPServer).applyRoutes(0xc000ee0500)
Aug 16 16:57:05 metrics grafana-server[2229]:         /drone/src/pkg/api/http_server.go:509 +0x58
Aug 16 16:57:05 metrics grafana-server[2229]: github.com/grafana/grafana/pkg/api.(*HTTPServer).Run(0xc000ee0500, {0x3d60148, 0xc0019eb600})
Aug 16 16:57:05 metrics grafana-server[2229]:         /drone/src/pkg/api/http_server.go:328 +0x67
Aug 16 16:57:05 metrics grafana-server[2229]: github.com/grafana/grafana/pkg/server.(*Server).Run.func1()
Aug 16 16:57:05 metrics grafana-server[2229]:         /drone/src/pkg/server/server.go:168 +0x123
Aug 16 16:57:05 metrics grafana-server[2229]: golang.org/x/sync/errgroup.(*Group).Go.func1()
Aug 16 16:57:05 metrics grafana-server[2229]:         /opt/drone/gomodcache/golang.org/x/sync@v0.0.0-20220601150217-0de741cfad7f/errgroup/errgroup.go:75 +0x64
Aug 16 16:57:05 metrics grafana-server[2229]: created by golang.org/x/sync/errgroup.(*Group).Go
Aug 16 16:57:05 metrics grafana-server[2229]:         /opt/drone/gomodcache/golang.org/x/sync@v0.0.0-20220601150217-0de741cfad7f/errgroup/errgroup.go:72 +0xa9
Aug 16 16:57:05 metrics systemd[1]: grafana-server.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 16 16:57:05 metrics systemd[1]: grafana-server.service: Failed with result 'exit-code'.
Aug 16 16:57:05 metrics systemd[1]: grafana-server.service: Scheduled restart job, restart counter is at 1.
Aug 16 16:57:05 metrics systemd[1]: Stopped Grafana instance.
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1.0
- Data source type & version: Prometheus 2.37.0
- OS Grafana is installed on: Ubuntu 22.04.1 amd64
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others: inside a LXD unprivileged container

**Comment by dginhoux** [comment]
Hi, 

Get the same thing.
I use pgsql and running on docker.

**Comment by usmangt** [comment]
Hi all,

Thanks for the opening this issue.

@dginhoux  On docker, did you encounter while doing an upgrade from 9.0.x to 9.1.0 OR some other way ?

**Comment by usmangt** [comment]
> Hi all,
> 
> Thanks for the opening this issue.
> 
> @dginhoux On docker, did you encounter while doing an upgrade from 9.0.x to 9.1.0 OR some other way ?

I just tried to reproduce this via docker-compose, my steps in summary were;

1- install a fresh grafana ver 9.0.7
2- added a test dashboard and saved it 
3- docker-compose down
4- updated docker.compose.yml and set grafana ver. to 9.0.1
6- docker-compose up -d --force-recreate
7- seems to be working fine.

Incase, if I missed something please let me know.

**Comment by dginhoux** [comment]
Hi, 

Coming from 9.0.7, i'm upgrading to 9.1.0.
In my grafana.ini, i set this option "force_migration = true", is it a great idea ?

**Comment by simondeziel** [comment]
Here is the content of my `grafana.ini` config, very little was modified from the base config shipped by grafana 9.0.7:

```
root@metrics:~# grep -Ev '^(;|#|$)' /etc/grafana/grafana.ini
[paths]
[server]
[database]
[datasources]
[remote_cache]
[dataproxy]
[analytics]
reporting_enabled = false
check_for_updates = false
check_for_plugin_updates = false
[security]
disable_initial_admin_creation = true
disable_gravatar = true
[security.encryption]
[snapshots]
[dashboards]
[users]
allow_sign_up = false
allow_org_create = false
[auth]
[auth.anonymous]
[auth.github]
[auth.gitlab]
[auth.google]
[auth.grafana_com]
[auth.azuread]
[auth.okta]
[auth.generic_oauth]
[auth.basic]
[auth.proxy]
[auth.jwt]
enabled = false
[auth.ldap]
[aws]
[azure]
[rbac]
enabled = false
[smtp]
[emails]
[log]
[log.console]
[log.file]
[log.syslog]
[log.frontend]
[quota]
[unified_alerting]
[alerting]
[annotations]
[annotations.dashboard]
[annotations.api]
[explore]
[help]
[profile]
[query_history]
[metrics]
[metrics.environment_info]
[metrics.graphite]
[grafana_com]
[tracing.jaeger]
[tracing.opentelemetry.jaeger]
[tracing.opentelemetry.otlp]
[external_image_storage]
[external_image_storage.s3]
[external_image_storage.webdav]
[external_image_storage.gcs]
[external_image_storage.azure_blob]
[external_image_storage.local]
[rendering]
[panels]
[plugins]
[live]
[plugin.grafana-image-renderer]
[enterprise]
[feature_toggles]
[date_formats]
[expressions]
[geomap]
```

**Comment by usmangt** [comment]
Hi @simondeziel, Can you please tell us which Debian version you used to reproduce this error?

**Comment by simondeziel** [comment]
@usmangt the LXD container is running Ubuntu 22.04.1 amd64.

**Comment by dginhoux** [comment]
My grafana stack doesn't contains any confidential informations, i can easily provide content like : 
- a ZIP of everything
- grafana ini 
- pgsql dump

I quickly duplicate it to don't destroy my main instance.

For informations, i'm using grafana on swarm cluster since v7 and i'v already upgraded to all theses versions : 
7.3.5, 7.3.7, 7.4.0, 7.4.1, 7.4.2, 7.4.3, 7.4.5, 7.5.0, 7.5.1, 7.5.2, 7.5.3, 7.5.4, 7.5.5, 7.5.6, 7.5.7
8.0.2, 8.0.3, 8.0.4, 8.0.5, 8.0.6
8.1.0, 8.1.1, 8.1.2, 8.1.3, 8.1.4, 8.1.5, 8.1.6, 8.1.7
8.2.0, 8.2.1, 8.2.2, 8.2.3, 8.2.5
8.3.0, 8.3.1, 8.3.2, 8.3.3, 8.3.4, 8.3.6
8.4.1, 8.4.2, 8.4.3, 8.4.4, 8.4.5, 8.4.6, 8.4.7
8.5.0, 8.5.1, 8.5.2, 8.5.3, 8.5.5, 8.5.6
9.0.0, 9.0.1, 9.0.2, 9.0.3, 9.0.4, 9.0.5, 9.0.6, 9.0.7


I don't remember exactly, when on v8.5, i've recreate my old grafana.ini (since v5) from scratch to be sure to have all newly options.

**Comment by dginhoux** [comment]
Hi, 

Same issue from 9.0.7 to 9.1.1

**Comment by dginhoux** [comment]
I'm trying to deploy an new empty stack (grafana 9.1.1 and pgsql 14 with my ini file)... and still the same issue.

**Comment by dginhoux** [comment]
YEAAHH ! !!

I've just find a solution : 
In my ini file i've this : 
```
#################################### Role-based Access Control ###########
[rbac]
enabled = false
# If enabled, cache permissions in a in memory cache (Enterprise only)
;permission_cache = true
```

i comment everything and it work now ! it work on my old instance, and my brand new for tests.

**Comment by kalleep** [comment]
Seems like the authorize fallback handlers in https://github.com/grafana/grafana/blob/main/pkg/services/correlations/api.go#L21-L30 is miss configured. I can make a fix for that tomorrow
