### ISSUE TITLE
Creating dashboard from query in Explorer page results invalid query in panel in Grafana v.9.0.5

### ISSUE THREAD

**Issue by akorosi** [grafana/grafana#53927]
**What happened**: I created a query in Explorer page using a Cortex datasource then I clicked on the "Add to dashboard button". I selected "New dashboard" and clicked on "Open dashboard". Then I selected the panel and clicked on the "Edit" button. The graph shows the correct data, but the query is not visible, but instead of the query I see an Exception and there is no way to see or edit the query. Exception:
`An unexpected error happened`
```
TypeError: Cannot read properties of undefined (reading 'label')

    at https://grafana.dtcisb.technology/public/build/prometheusPlugin.d59378aa50e00a3aeb1f.js:82:20200
    at div
    at A (https://grafana.dtcisb.technology/public/build/9809.fda1ab8a7d47805687a6.js:2:12810)
    at t.EditorRows (https://grafana.dtcisb.technology/public/build/9809.fda1ab8a7d47805687a6.js:2:69270)
    at https://grafana.dtcisb.technology/public/build/prometheusPlugin.d59378aa50e00a3aeb1f.js:86:58
    at pt (https://grafana.dtcisb.technology/public/build/prometheusPlugin.d59378aa50e00a3aeb1f.js:86:3335)
    at Bl (https://grafana.dtcisb.technology/public/build/4027.75004167a6da62afedb9.js:3120:467)
    at zl (https://grafana.dtcisb.technology/public/build/4027.75004167a6da62afedb9.js:3120:1023)
    at div
    at div
    at div
    at https://grafana.dtcisb.technology/public/build/9809.fda1ab8a7d47805687a6.js:2:705846
    at g (https://grafana.dtcisb.technology/public/build/9809.fda1ab8a7d47805687a6.js:2:1096373)
    at So (https://grafana.dtcisb.technology/public/build/9809.fda1ab8a7d47805687a6.js:2:707161)
    at Oo (https://grafana.dtcisb.technology/public/build/9809.fda1ab8a7d47805687a6.js:2:707279)
    at h (https://grafana.dtcisb.technology/public/build/4027.75004167a6da62afedb9.js:5600:72)
    at div
    at I (https://grafana.dtcisb.technology/public/build/4027.75004167a6da62afedb9.js:7398:955)
    at div
    at https://grafana.dtcisb.technology/public/build/9809.fda1ab8a7d47805687a6.js:2:709520
    at g (https://grafana.dtcisb.technology/public/build/9809.fda1ab8a7d47805687a6.js:2:1096373)
    at l (https://grafana.dtcisb.technology/public/build/9809.fda1ab8a7d47805687a6.js:2:1094418)
    at zr (https://grafana.dtcisb.technology/public/build/9809.fda1ab8a7d47805687a6.js:2:692869)
    at t (https://grafana.dtcisb.technology/public/build/9809.fda1ab8a7d47805687a6.js:2:626298)
    at Hr (https://grafana.dtcisb.technology/public/build/9809.fda1ab8a7d47805687a6.js:2:696409)
    at d (https://grafana.dtcisb.technology/public/build/6549.f792862f9957ffda6109.js:68:268)
    at div
    at div
    at div
    at div
    at div
    at t (https://grafana.dtcisb.technology/public/build/9809.fda1ab8a7d47805687a6.js:2:777259)
    at c (https://grafana.dtcisb.technology/public/build/4027.75004167a6da62afedb9.js:314:168)
    at H (https://grafana.dtcisb.technology/public/build/3833.5a9567f878ccf1d29313.js:5:185)
    at Nr (https://grafana.dtcisb.technology/public/build/DashboardPage.443afb1d60705186c20f.js:392:229)
    at div
    at Qi (https://grafana.dtcisb.technology/public/build/4027.75004167a6da62afedb9.js:2714:31)
    at div
    at https://grafana.dtcisb.technology/public/build/DashboardPage.443afb1d60705186c20f.js:392:1584
    at div
    at div
    at n (https://grafana.dtcisb.technology/public/build/DashboardPage.443afb1d60705186c20f.js:70:8187)
    at div
    at n (https://grafana.dtcisb.technology/public/build/DashboardPage.443afb1d60705186c20f.js:70:10136)
    at div
    at n (https://grafana.dtcisb.technology/public/build/DashboardPage.443afb1d60705186c20f.js:70:8187)
    at div
    at n (https://grafana.dtcisb.technology/public/build/DashboardPage.443afb1d60705186c20f.js:70:10136)
    at Ke (https://grafana.dtcisb.technology/public/build/DashboardPage.443afb1d60705186c20f.js:70:15723)
    at div
    at div
    at Zr (https://grafana.dtcisb.technology/public/build/DashboardPage.443afb1d60705186c20f.js:409:1512)
    at g (https://grafana.dtcisb.technology/public/build/9809.fda1ab8a7d47805687a6.js:2:1096373)
    at WithTheme(Connect(Zr))
    at div
    at ri (https://grafana.dtcisb.technology/public/build/DashboardPage.443afb1d60705186c20f.js:532:7234)
    at DashboardPage
    at g (https://grafana.dtcisb.technology/public/build/9809.fda1ab8a7d47805687a6.js:2:1096373)
    at n (https://grafana.dtcisb.technology/public/build/9809.fda1ab8a7d47805687a6.js:2:1042703)
    at Po (https://grafana.dtcisb.technology/public/build/4027.75004167a6da62afedb9.js:8273:23633)
    at t (https://grafana.dtcisb.technology/public/build/9809.fda1ab8a7d47805687a6.js:2:1111691)
    at t (https://grafana.dtcisb.technology/public/build/9809.fda1ab8a7d47805687a6.js:2:1113712)
    at main
    at t (https://grafana.dtcisb.technology/public/build/9809.fda1ab8a7d47805687a6.js:2:1108309)
    at div
    at us (https://grafana.dtcisb.technology/public/build/4027.75004167a6da62afedb9.js:2573:1029)
    at t.KBarProvider (https://grafana.dtcisb.technology/public/build/9809.fda1ab8a7d47805687a6.js:2:358763)
    at c (https://grafana.dtcisb.technology/public/build/4027.75004167a6da62afedb9.js:5862:27780)
    at Bl (https://grafana.dtcisb.technology/public/build/4027.75004167a6da62afedb9.js:3120:467)
    at zl (https://grafana.dtcisb.technology/public/build/4027.75004167a6da62afedb9.js:3120:1023)
    at y (https://grafana.dtcisb.technology/public/build/9809.fda1ab8a7d47805687a6.js:2:141237)
    at Oo (https://grafana.dtcisb.technology/public/build/4027.75004167a6da62afedb9.js:8273:23162)
    at l (https://grafana.dtcisb.technology/public/build/9809.fda1ab8a7d47805687a6.js:2:1094418)
    at nl (https://grafana.dtcisb.technology/public/build/4027.75004167a6da62afedb9.js:8286:115)
```

**What you expected to happen**: I would like to see the same query as I created in the Explorer page

**How to reproduce it (as minimally and precisely as possible)**: Steps are documented in the first section

**Anything else we need to know?**:

**Environment**: AWS EKS, Terraform, Kubernetes, cortex_helm_version  = "0.6.0"
- Grafana version: Grafana v.9.0.5 (I cannot see the issue with v.8.5.10)
- Data source type & version: Cortex,  cortex_helm_version  = "0.6.0"
- OS Grafana is installed on: Alpine
- User OS & Browser: Chrome, Mac
- Grafana plugins: Cortex
- Others:

**Comment by Elfo404** [comment]
@grafana/observability-metrics i think this has already been reported before and it's because the prometheus query editor assuming the shape of the query model is different in dashboards. can you check?

**Comment by bohandley** [comment]
We are working on reproducing this issue currently, thank you!

**Comment by obetomuniz** [comment]
Hot update: I was able to reproduce the issue locally. Now I'll be digging into the issue and fix investigation. 

Also, thanks @Elfo404, for suggesting the potential problem source. I'll be checking this in deep too.

**Comment by daniellee** [comment]
The hands-on module "Module: Creating dashboard panels directly from Explore" in Grafana University for the "Add to dashboard" feature suffers from the same bug: https://university.grafana.com/learn/course/84/module-creating-dashboard-panels-directly-from-explore;lp=22

So might want to follow up with them to upgrade the Grafana version used in the tutorial sandbox once the bug is fixed.

cc @matthewhelmke

**Comment by matthewhelmke** [comment]
> The hands-on module "Module: Creating dashboard panels directly from Explore" in Grafana University for the "Add to dashboard" feature suffers from the same bug: https://university.grafana.com/learn/course/84/module-creating-dashboard-panels-directly-from-explore;lp=22
> 
> So might want to follow up with them to upgrade the Grafana version used in the tutorial sandbox once the bug is fixed.
> 
> cc @matthewhelmke

Thanks for the tag! I'm tagging @rodrigofernandz since he will be doing the work for the upgrade when it's time.
