### ISSUE TITLE
Unified Alerting - Editing an alert locks my browser on 9.1.1 

### ISSUE THREAD

**Issue by reyjrar** [grafana/grafana#54169]
**What happened**:

Testing the upgrade to 9.1.1, I was able to successfully create alerts via the API. When I go to edit those alerts by interacting with any form element on the page, the tab becomes unresponsive, even browser controls like Reload/Stop/Force Reload do nothing. I can scroll and view the whole page, but none of the elements on the page allow interaction.

If I load the edit alert page, I *can* interact with "Cancel / Delete / Save / Save and exit", but if I click into a text box or click on any other element in the page, the browser locks.  This happens on Safari, Brave (Chromium-based), and Firefox.

On Brave I was able to get this message out the console:

```
list:1 The keyword 'inner-spin-button' specified to an 'appearance' property is not standardized. It will be removed in the future.
list:1 The keyword 'inner-spin-button' specified to an 'appearance' property is not standardized. It will be removed in the future.
list:1 The keyword 'inner-spin-button' specified to an 'appearance' property is not standardized. It will be removed in the future.
react-dom.production.min.js:216 Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at lu (react-dom.production.min.js:237:48)
    at Ca (react-dom.production.min.js:170:408)
    at context.tsx:78:9
    at Du (react-dom.production.min.js:262:359)
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Uo (react-dom.production.min.js:122:325)
    at Ru (react-dom.production.min.js:261:308)
    at vu (react-dom.production.min.js:243:50)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
as @ react-dom.production.min.js:216
i.componentDidCatch.n.callback @ react-dom.production.min.js:217
fi @ react-dom.production.min.js:131
ps @ react-dom.production.min.js:220
Au @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Uo @ react-dom.production.min.js:122
Tu @ react-dom.production.min.js:252
vu @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Uo @ react-dom.production.min.js:122
Vo @ react-dom.production.min.js:123
Wo @ react-dom.production.min.js:122
lu @ react-dom.production.min.js:237
Ca @ react-dom.production.min.js:170
(anonymous) @ context.tsx:41
(anonymous) @ store.ts:196
await in (anonymous) (async)
(anonymous) @ context.tsx:49
Du @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
Uo @ react-dom.production.min.js:122
Ru @ react-dom.production.min.js:261
vu @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Uo @ react-dom.production.min.js:122
Vo @ react-dom.production.min.js:123
Wo @ react-dom.production.min.js:122
(anonymous) @ react-dom.production.min.js:244
De @ react-dom.production.min.js:292
Fe @ react-dom.production.min.js:49
(anonymous) @ react-dom.production.min.js:50
Rr @ react-dom.production.min.js:105
Jt @ react-dom.production.min.js:75
Xt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Uo @ react-dom.production.min.js:122
Ne @ react-dom.production.min.js:292
$t @ react-dom.production.min.js:73
react-dom.production.min.js:237 Uncaught (in promise) Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at lu (react-dom.production.min.js:237:48)
    at Ca (react-dom.production.min.js:170:408)
    at Object.refresh (context.tsx:101:11)
    at V (helpers.ts:168:11)
    at G (store.ts:75:5)
    at store.ts:195:19
    at context.tsx:56:9
    at Du (react-dom.production.min.js:262:359)
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Uo (react-dom.production.min.js:122:325)
lu @ react-dom.production.min.js:237
Ca @ react-dom.production.min.js:170
refresh @ context.tsx:101
V @ helpers.ts:168
G @ store.ts:75
(anonymous) @ store.ts:195
(anonymous) @ context.tsx:56
Du @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
Uo @ react-dom.production.min.js:122
Ru @ react-dom.production.min.js:261
vu @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Uo @ react-dom.production.min.js:122
Vo @ react-dom.production.min.js:123
Wo @ react-dom.production.min.js:122
(anonymous) @ react-dom.production.min.js:244
De @ react-dom.production.min.js:292
Fe @ react-dom.production.min.js:49
(anonymous) @ react-dom.production.min.js:50
Rr @ react-dom.production.min.js:105
Jt @ react-dom.production.min.js:75
Xt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Uo @ react-dom.production.min.js:122
Ne @ react-dom.production.min.js:292
$t @ react-dom.production.min.js:73
await in $t (async)
(anonymous) @ context.tsx:56
Du @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
Uo @ react-dom.production.min.js:122
Ru @ react-dom.production.min.js:261
vu @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Uo @ react-dom.production.min.js:122
Vo @ react-dom.production.min.js:123
Wo @ react-dom.production.min.js:122
(anonymous) @ react-dom.production.min.js:244
De @ react-dom.production.min.js:292
Fe @ react-dom.production.min.js:49
(anonymous) @ react-dom.production.min.js:50
Rr @ react-dom.production.min.js:105
Jt @ react-dom.production.min.js:75
Xt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Uo @ react-dom.production.min.js:122
Ne @ react-dom.production.min.js:292
$t @ react-dom.production.min.js:73
```

**What you expected to happen**:

My browser tab to remain operable.

**How to reproduce it (as minimally and precisely as possible)**:

Here's an example rule that I can't edit without the browser locking up:

Datasource is Graphite web 

```json
{
  "annotations": {
    "current": "{{ $values.B }}",
    "graph_url": "https://graphite.example.com/render?format=png&from=-900s&target={{ $labels.name }}",
    "message": "LoadAvgNorm over 0.4 (currently {{ $values.B }})"
  },
  "condition": "C",
  "data": [
    {
      "datasourceUid": "000000001",
      "model": {
        "intervalMs": 1000,
        "maxDataPoints": 100,
        "metricColumn": "none",
        "refId": "A",
        "target": "keepLastValue(lm.*.*.*.LoadAvgNorm,1)",
        "timeColumn": "time"
      },
      "queryType": "",
      "refId": "A",
      "relativeTimeRange": {
        "from": 900,
        "to": 0
      }
    },
    {
      "datasourceUid": "-100",
      "model": {
        "expression": "A",
        "hide": false,
        "intervalMs": 1000,
        "maxDataPoints": 100,
        "reducer": "mean",
        "refId": "B",
        "type": "reduce"
      },
      "queryType": "",
      "refId": "B",
      "relativeTimeRange": {
        "from": 0,
        "to": 0
      }
    },
    {
      "datasourceUid": "-100",
      "model": {
        "expression": "$B > 0.4",
        "hide": false,
        "intervalMs": 1000,
        "maxDataPoints": 100,
        "refId": "C",
        "type": "math"
      },
      "queryType": "",
      "refId": "C",
      "relativeTimeRange": {
        "from": 0,
        "to": 0
      }
    }
  ],
  "execErrState": "Alerting",
  "folderUID": "IvYMuYJWk",
  "for": "5m",
  "id": 144,
  "labels": {
    "build": "{{ reReplaceAll \"^lm\\\\.[^.]+\\\\.([^.]+).*\" \"$1\" $labels.name  }}",
    "host": "{{ reReplaceAll \"^lm\\\\.[^.]+\\\\.[^.]+\\\\.([^.]+).*\" \"$1\" $labels.name  }}",
    "location": "{{ reReplaceAll \"^lm\\\\.([^.]+).*\" \"$1\" $labels.name  }}",
    "metric": "LoadAvgNorm"
  },
  "noDataState": "NoData",
  "orgID": 1,
  "ruleGroup": "LoadAvgNorm over 0.4",
  "title": "LoadAvgNorm over 0.4",
  "uid": "r3zFzDWVz",
  "updated": "2022-08-23T21:18:47Z"
}
```

**Anything else we need to know?**:

Running behind an Apache 2.4 Reverse Proxy:

```
<VirtualHost "_default_:443">
    ServerName "grafana.example.com"
    ErrorLog "/var/log/httpd/grafana_ssl_error.log"
    TransferLog "/var/log/httpd/grafana_ssl_access.log"

    # Enable SSL and Load Certificates/Keys
    Include "snippets.d/ssl_grafana.conf"

    # Enable Proxying
    ProxyPreserveHost On
    ProxyPass / http://127.0.0.1:3000/
    ProxyPassReverse / http://127.0.0.1:3000/
    ProxyRequests Off
</VirtualHost>
```

I love Grafana. I am grateful for the project. I have no idea how I functioned in the before times. Keep up the great work :)

**Environment**:
- Grafana version: 9.1.1
- Data source type & version: Graphite Web 1.1.8
- OS Grafana is installed on: CentOS 7
- User OS & Browser: macOS, Safari, Brave, and Firefox
- Grafana plugins: N/A
- Others:  Apache 2.4

**Comment by reyjrar** [comment]
The error is a [React Recursion Error](https://reactjs.org/docs/error-decoder.html/?invariant=185).

It happens on 8.5.2 and 8.5.10 as well, but doesn't lock on the browser:
![ScreenShot of 8.5.10](https://user-images.githubusercontent.com/99365/186790409-18024929-9e8e-409e-a31c-2eb60b588755.png)

**Comment by reyjrar** [comment]
The rules this happens on were created via the `/api/ruler/grafana/api/v1/rules/<namespace>` API. I'm looking at the provisioning APIs now to cut over my scripts. I'm hoping that solves the problem? I don't know. Here are the API endpoints I found to create rules:

* `/api/ruler/grafana/api/v1/rules/<namespace>`
* `/api/v1/provisioning/alert-rules`

I think there was one in the `/api/alertmanager/` space too. Anyways, I think the issue is the unsupported endpoints still accept data and something with their format breaks things.

**Comment by konrad147** [comment]
I was able to reproduce the problem. It seems the query model is not valid. Probably there are some fields missing. I think you should try to use Provisioning API for what you are trying to achieve.

I'll try to clarify the APIs confusion

- `/api/ruler/grafana/api/v1/rules` and similar - this is our internal API. It's not intended for public use (although it's doable) as we may change it at any point without a notice
- `/api/v1/provisioning/` - this is the Provisioning API we added in Grafana 9.1. If you want to access the rules programmatically you should use that API. There is [Provisioning API docs](https://grafana.com/docs/grafana/latest/developers/http_api/alerting_provisioning/). This is our extension point for external services. It provides a better validation and more fine-grained access to the alerting objects

**Comment by reyjrar** [comment]
The Provisioning API is missing a "GET" for a list of rules in a namespace.
