### ISSUE TITLE
Some graphs showing up blank with error in browser console

### ISSUE THREAD

**Issue by mbentley** [grafana/grafana#55520]
**What happened**:

I'm seeing a few of my graphs show up with blank consoles.  I am not sure what would have changed as I did not change any configurations recently.  I do notice that when toggling off/on specific queries that dashboards then populate.  I also put the exact same queries into the explore functionality and I don't see any errors so I am not sure what is going on.  This started in Grafana 9.1.5 and can't be reproduced in 9.1.4.

![screenshot 2022-09-20 at 3 44 21 PM](https://user-images.githubusercontent.com/414445/191351027-06bf2823-6711-4aa2-a4af-a519b2e3138f.png)

```
Uncaught TypeError: Failed to execute 'createLinearGradient' on 'CanvasRenderingContext2D': The provided double value is non-finite.
    at ko (gradientFills.ts:157:17)
    at n (UPlotThresholds.ts:71:15)
    at UPlotThresholds.ts:123:9
    at uPlot.esm.js:5257:8
    at Array.forEach (<anonymous>)
    at ro (uPlot.esm.js:5256:18)
    at xr (uPlot.esm.js:4274:4)
```

**What you expected to happen**:

Graphs displayed as normal.

**How to reproduce it (as minimally and precisely as possible)**:

It's somewhat random so I am not sure how to reproduce unfortunately.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1.6 (also saw this on 9.1.5)
- Data source type & version: InfluxDB v2.4.0
- OS Grafana is installed on: `grafana/grafana:9.1.5` Docker image (Based on Alpine 3.15.6)
- User OS & Browser: macOS Google Chrome
- Grafana plugins: n/a
- Others:

**Comment by codeincarnate** [comment]
Seems like this could be a fill or threshold not getting one of its colors. Have there been any changes to data or thresholds? If that's not the case there could be a gradient color not being set and getting this error as a result.

**Comment by mbentley** [comment]
Ah - so I was going through and attempting to re-create the issue.  The problem seems to come up when I set the `Decimals` to `0` .  If `Decimals` is unset or non-zero, it seems to be fine:

![decimals](https://user-images.githubusercontent.com/414445/192325819-c7bb7bab-4596-4280-a84f-6f42589d0a2d.gif)

**Comment by leeoniya** [comment]
hmm, could have been this?

https://github.com/grafana/grafana/pull/54679/files#diff-ced08131b2d307084ef219c3ed371edeed8be74ec6b1cdb93c47097b9806501aR109-R112

**Comment by leeoniya** [comment]
repro. the threshold rendering is a red herring. even without them the y scale looks broken when decimals=0.

<details><summary>log-y-zero-dec</summary>

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 351,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "testdata",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "log": 2,
              "type": "log"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "area"
            }
          },
          "decimals": 0,
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "transparent",
                "value": null
              },
              {
                "color": "red",
                "value": 30
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "A",
          "scenarioId": "csv_metric_values",
          "stringInput": ".25,60"
        }
      ],
      "title": "Panel Title",
      "type": "timeseries"
    }
  ],
  "schemaVersion": 37,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "log-zero-dec",
  "uid": "k1Cn6Z4Vk",
  "version": 2,
  "weekStart": ""
}
```
</details>
