### ISSUE TITLE
Grafana UI Error: "thresholds" not found

### ISSUE THREAD

**Issue by xiyu95** [grafana/grafana#56125]
**What happened**:
When visiting [Grafana UI](https://developers.grafana.com/ui/latest/index.html?path=/story/visualizations-table--bar-gauge-cell), and looking at the Table Component, there exists an error on the page with error message shown below:
```
Error: "thresholds" not found in: 
    at e.value (https://developers.grafana.com/ui/latest/48.522604d8.iframe.bundle.js:2:97377)
    at c (https://developers.grafana.com/ui/latest/48.522604d8.iframe.bundle.js:2:33381)
    at u (https://developers.grafana.com/ui/latest/48.522604d8.iframe.bundle.js:2:37349)
    at h (https://developers.grafana.com/ui/latest/48.522604d8.iframe.bundle.js:2:28063)
    at https://developers.grafana.com/ui/latest/48.522604d8.iframe.bundle.js:2:548371
    at Array.map (<anonymous>)
    at data (https://developers.grafana.com/ui/latest/48.522604d8.iframe.bundle.js:2:547273)
    at ne (https://developers.grafana.com/ui/latest/48.522604d8.iframe.bundle.js:2:548593)
    at le (https://developers.grafana.com/ui/latest/48.522604d8.iframe.bundle.js:2:550699)
    at ce (https://developers.grafana.com/ui/latest/48.522604d8.iframe.bundle.js:2:550990)
```

Screenshot as followed:
![Screen Shot 2022-09-30 at 9 57 53 AM](https://user-images.githubusercontent.com/112968312/193320145-e717835a-3e86-41af-bf98-b89f44129600.png)

**What you expected to happen**:
A normal page with sample Table component on it

**How to reproduce it (as minimally and precisely as possible)**:
[Link here](https://developers.grafana.com/ui/latest/index.html?path=/story/visualizations-table--bar-gauge-cell)

**Comment by allansson** [comment]
This also happens with `BigValue` and `BarGauge`.

**Comment by zuchka** [comment]
Hi @allansson & @xiyu95 

thanks for reporting this. All three of those stories are loading on my end. Perhaps this is already fixed? If you could double check if this works on your end that would be very helpful. Thank you!

**Comment by xiyu95** [comment]
> thanks for reporting this. All three of those stories are loading on my end. Perhaps this is already fixed? If you could double check if this works on your end that would be very helpful. Thank you!

I just checked and it seems like it loaded out fine for me now.

@allansson Could you please double check this on your side once more, and then we can close the ticket.

**Comment by allansson** [comment]
Yes, it's working now. We can close the ticket.
