### ISSUE TITLE
Invalid interval String error when changing Evaluate every field value

### ISSUE THREAD

**Issue by milinpatel13298** [grafana/grafana#56141]
**What happened**:
An error is displayed when attempting to change the "Evaluate every" field by deleting the numeric part "only", i.e.; if you attempt to just change the interval from, say 5m to 1m, by placing your cursor before m and hit backspace; leaving the field value as "m", then the error is displayed before you get to typing 1 (to change the field value to 1m)

**What you expected to happen**:
The UI should give enough time to change the "Evaluate every" value in the textbox and "decide" whether the interval is valid only after the focus is taken off that field/or not at least not immediately like it is currently doing.

**How to reproduce it (as minimally and precisely as possible)**:
Change the interval from, say 5m to 1m, by placing your cursor before m and hit backspace; leaving the field value as "m"

**Anything else we need to know?**:
Error details
An unexpected error happened
Details
Error: Invalid interval string, has to be either unit-less or end with one of the following units: "y, M, w, d, h, m, s, ms"

    at Re (https://graphs.tools.support/public/build/AlertingRuleForm.65d68808f5c3c22f3566.js:74:1118)
    at div
    at div
    at div
    at t (https://graphs.tools.support/public/build/2449.def35241a3dcae812382.js:2:710633)
    at c (https://graphs.tools.support/public/build/6151.962c8f241d27d9b5b744.js:83:2765)
    at div
    at form
    at R (https://graphs.tools.support/public/build/2449.def35241a3dcae812382.js:2:926701)
    at li (https://graphs.tools.support/public/build/AlertingRuleForm.65d68808f5c3c22f3566.js:152:1395)
    at Si.style (https://graphs.tools.support/public/build/AlertingRuleForm.65d68808f5c3c22f3566.js:175:49)
    at nu (https://graphs.tools.support/public/build/6151.962c8f241d27d9b5b744.js:3232:467)
    at au (https://graphs.tools.support/public/build/6151.962c8f241d27d9b5b744.js:3232:1023)
    at WithErrorBoundary
    at n (https://graphs.tools.support/public/build/2449.def35241a3dcae812382.js:2:979539)
    at jl (https://graphs.tools.support/public/build/6151.962c8f241d27d9b5b744.js:8234:11732)
    at t (https://graphs.tools.support/public/build/2449.def35241a3dcae812382.js:2:1048527)
    at t (https://graphs.tools.support/public/build/2449.def35241a3dcae812382.js:2:1050548)
    at main
    at wo (https://graphs.tools.support/public/build/6151.962c8f241d27d9b5b744.js:8194:22407)
    at t (https://graphs.tools.support/public/build/2449.def35241a3dcae812382.js:2:1045145)
    at div
    at Fi (https://graphs.tools.support/public/build/6151.962c8f241d27d9b5b744.js:2479:1027)
    at t.KBarProvider (https://graphs.tools.support/public/build/2449.def35241a3dcae812382.js:2:290785)
    at l (https://graphs.tools.support/public/build/6151.962c8f241d27d9b5b744.js:5960:28425)
    at nu (https://graphs.tools.support/public/build/6151.962c8f241d27d9b5b744.js:3232:467)
    at au (https://graphs.tools.support/public/build/6151.962c8f241d27d9b5b744.js:3232:1023)
    at y (https://graphs.tools.support/public/build/2449.def35241a3dcae812382.js:2:2903758)
    at bl (https://graphs.tools.support/public/build/6151.962c8f241d27d9b5b744.js:8234:10879)
    at l (https://graphs.tools.support/public/build/2449.def35241a3dcae812382.js:2:1031254)
    at Jl (https://graphs.tools.support/public/build/6151.962c8f241d27d9b5b744.js:8247:115)

**Environment**:
- Grafana version: v9.1.5
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by grobinson-grafana** [comment]
Hi! :wave: I think this issue is similar to https://github.com/grafana/grafana/issues/55357, which will be fixed in Grafana 9.2.

**Comment by milinpatel13298** [comment]
Hi! Thank you for your reply. That sounds good!

**Comment by grobinson-grafana** [comment]
You're welcome! I will close this issue as a duplicate. However, if its not fixed in 9.2 please feel free to re-open it!
