### ISSUE TITLE
Deleted graphite metrics still queried

### ISSUE THREAD

**Issue by roycec** [grafana/grafana#5635]
Hello,

I'm not sure, if my problem is related to Grafana or to Graphite. Some days ago I deleted some no longer used Graphite data files (wsp). Now I see exeptions on the Graphite (webapp) exception.log, e.g.

Fri Jul 22 10:20:02 2016 :: Failed CarbonLink query 'tst.servxxxx.load.load.shortterm'
Traceback (most recent call last):
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 385, in fetchData
    cachedResults = CarbonLink.query(dbFile.real_metric)
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 146, in query
    results = self.send_request(request)
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 207, in send_request
    conn = self.get_connection(host)
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 134, in get_connection
    connection.connect( (server, port) )
  File "<string>", line 1, in connect
error: [Errno 111] Connection refused

This metric file does not longer exist. Where might this information regarding the former metric file still be stored? Does one have to do further steps when removing outdated graphite metric files except from removing the files itselves? I apologize if this is the wrong place for my question.

Grafana 3.0.4
Graphite 0.9.15
RHEL 6.6

Regards
Christian

**Comment by torkelo** [comment]
not sure, for me it usually works by just removing the wsp files, try restarting carbon-cache.

If that does work open question in mailing list
