### ISSUE TITLE
Notify user when metric query fails due to too many series

### ISSUE THREAD

**Issue by obfuscurity** [grafana/grafana#5778]
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
  - v3.1.1 (commit: a4d2708)
- What datasource are you using?
  - Graphite (metrictank)
- What OS are you running grafana on?
  - "Linux 2.6 / 3.x / 4.x (64-bit)" (metrictank running in Docker Toolbox)
- What did you do?
  - Attempted to add a metric query inside of a new graph panel.
- What was the expected result?
  - The leaf node would populate with the available choices.
- What happened instead?
  - The query editor showed me an empty field. In the background (dev console), graphite-api returned a 500 due to too many series.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/graphite_api/app.py", line 144, in metrics_find
    key=lambda node: node.name
  File "/usr/local/lib/python2.7/dist-packages/graphite_api/storage.py", line 21, in find
    for node in finder.find_nodes(query):
  File "/usr/local/lib/python2.7/dist-packages/graphite_metrictank.py", line 114, in find_nodes
    matches = self.search_series(query)
  File "/usr/local/lib/python2.7/dist-packages/graphite_metrictank.py", line 212, in search_series
    raise Exception("Too many series. Refine your search or ask your admin to increase max_docs")
Exception: Too many series. Refine your search or ask your admin to increase max_docs
```

It would be very useful to catch this raised exception and present a warning to the user in the UI.

/cc @Dieterbe

**Comment by Dieterbe** [comment]
basically if a datasource is returning http 500's (it doesn't have to be graphite-api returning http 500 too many series, it could be anything), grafana needs to present the error to the user.
