### ISSUE TITLE
Regression in 9.2.3 in TimeSeries breaks with fill below option

### ISSUE THREAD

**Issue by lstrojny** [grafana/grafana#57977]
**What happened**:
Timeseries graph crashes with this error:

```
TypeError: Cannot read properties of undefined (reading 'state')
    at r (fieldState.ts:40:31)
    at utils.ts:404:35
    at Object.prepConfig (TimeSeries.tsx:25:12)
    at b.prepState (GraphNG.tsx:133:24)
    at new b (GraphNG.tsx:104:22)
    at gi (react-dom.production.min.js:135:172)
    at qa (react-dom.production.min.js:181:146)
    at Zs (react-dom.production.min.js:269:427)
    at Ou (react-dom.production.min.js:250:347)
    at ku (react-dom.production.min.js:250:278)
```

Looking at the diff between 9.2.2 and 9.2.3, I would guess https://github.com/grafana/grafana/pull/57728 triggered the regression.

**What you expected to happen**:
Timeseries graph renders normally

**How to reproduce it (as minimally and precisely as possible)**:
This is the graph that crashes

<details>

```
{
  "id": 4,
  "gridPos": {
    "h": 8,
    "w": 23,
    "x": 0,
    "y": 14
  },
  "type": "timeseries",
  "title": "Load",
  "datasource": {
    "uid": "i3od78gRz",
    "type": "prometheus"
  },
  "fieldConfig": {
    "defaults": {
      "custom": {
        "drawStyle": "line",
        "lineInterpolation": "smooth",
        "barAlignment": 0,
        "lineWidth": 2,
        "fillOpacity": 0,
        "gradientMode": "none",
        "spanNulls": false,
        "showPoints": "auto",
        "pointSize": 5,
        "stacking": {
          "mode": "none",
          "group": "A"
        },
        "axisPlacement": "auto",
        "axisLabel": "",
        "axisColorMode": "text",
        "scaleDistribution": {
          "type": "linear"
        },
        "axisCenteredZero": false,
        "hideFrom": {
          "tooltip": false,
          "viz": false,
          "legend": false
        },
        "thresholdsStyle": {
          "mode": "off"
        },
        "axisSoftMin": 0
      },
      "color": {
        "mode": "palette-classic"
      },
      "mappings": [],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          }
        ]
      },
      "min": 0,
      "unit": "none"
    },
    "overrides": [
      {
        "matcher": {
          "id": "byFrameRefID",
          "options": "B"
        },
        "properties": [
          {
            "id": "custom.lineWidth",
            "value": 0
          },
          {
            "id": "custom.hideFrom",
            "value": {
              "legend": true,
              "tooltip": false,
              "viz": false
            }
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "Detail dodecaphonism"
        },
        "properties": [
          {
            "id": "custom.fillBelowTo",
            "value": "dodecaphonism"
          },
          {
            "id": "color",
            "value": {
              "fixedColor": "light-green",
              "mode": "fixed"
            }
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "Detail most"
        },
        "properties": [
          {
            "id": "custom.fillBelowTo",
            "value": "most"
          },
          {
            "id": "color",
            "value": {
              "fixedColor": "light-yellow",
              "mode": "fixed"
            }
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "Detail polyphony"
        },
        "properties": [
          {
            "id": "custom.fillBelowTo",
            "value": "polyphony"
          },
          {
            "id": "color",
            "value": {
              "fixedColor": "light-blue",
              "mode": "fixed"
            }
          }
        ]
      }
    ]
  },
  "options": {
    "tooltip": {
      "mode": "single",
      "sort": "none"
    },
    "legend": {
      "showLegend": true,
      "displayMode": "list",
      "placement": "bottom",
      "calcs": [
        "lastNotNull"
      ]
    }
  },
  "targets": [
    {
      "datasource": {
        "type": "prometheus",
        "uid": "i3od78gRz"
      },
      "editorMode": "code",
      "expr": "rate(node_load15[$__rate_interval])",
      "interval": "5m",
      "legendFormat": "{{instance}}",
      "range": true,
      "refId": "A"
    },
    {
      "datasource": {
        "type": "prometheus",
        "uid": "i3od78gRz"
      },
      "editorMode": "code",
      "expr": "rate(node_load1[$__rate_interval])",
      "hide": false,
      "legendFormat": "Detail {{instance}}",
      "range": true,
      "refId": "B"
    }
  ]
}
```

</details>

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.3
- Data source type & version: prometheus 2.27.0
- OS Grafana is installed on: Debian Linux
- User OS & Browser: Chrome 106.0.5249.119

**Comment by mdvictor** [comment]
Hey @lstrojny. I'll be looking over this.

**Comment by mdvictor** [comment]
Can you please share with me a data sample from the query inspector? I'm having a hard time reproducing it

**Comment by lstrojny** [comment]
[debug-Memory usage-2022-11-02 20_40_11.json.txt](https://github.com/grafana/grafana/files/9923656/debug-Memory.usage-2022-11-02.20_40_11.json.txt)

Sure. Hope this is what you meant

**Comment by sensej-j** [comment]
Hello, 
I also get the same error message when I add "Graph styles -> Fill below to" to Overrides

**Comment by JJ-JT-git** [comment]
Hi, My dashboard is broken too, when will the fix be deployed for the hosted Grafana?

**Comment by leeoniya** [comment]
we have a 9.2.4 release scheduled for Tue next week, so by then for sure (it may take another day or two to hit any hosted instances). if you're self-hosted you can roll back to 9.2.2 or revert https://github.com/grafana/grafana/pull/57728 and make a custom build. otherwise you can open an escalation to roll back your instance, if that's a channel available to you (sorry i'm not too familiar with this process)

unfortunately the proper fix is not immediately obvious. but we'll need to make a call before Tue about how to proceed:

- #58030 is one option, though it's not yet clear if this is a future-proof solution
- find a fix that addresses both this issue and the one that was originally fixed by https://github.com/grafana/grafana/pull/57728. this may involve changes to how [FillBelowToEditor](https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/timeseries/FillBelowToEditor.tsx) gets and saves field names.
- roll back #57728 as a last resort

hope that's somewhat helpful :crossed_fingers:

**Comment by lstrojny** [comment]
I can confirm that the issue is gone in yesterday’s release 9.2.4. Thank you!
