### ISSUE TITLE
Dashboards: Starring a dashboard where uid = `home` will throw error for many urls

### ISSUE THREAD

**Issue by Vonng** [grafana/grafana#59764]
**What happened**:

I have a dashboard named Home with uid `home`, when I upgrade to grafana 9.3.0 and Grafana 9.3.1. When I log in as the admin user, the default home dashboard shows the following error msg and fails to load: 

It seems like a recursive call on the function `addCrumbs`.

```javascript
An unexpected error happened

RangeError: Maximum call stack size exceeded

    at b (http://g.pigsty/public/build/2352.d7c14cbd3dbda648a17f.js:5801:1143)
    at Dr (http://g.pigsty/public/build/DashboardPage.8a1350f57b9b7c0796ec.js:504:7204)
    at DashboardPage
    at g (http://g.pigsty/public/build/2754.c9252327f51106ea3a6d.js:2:1042231)
    at Suspense
    at c (http://g.pigsty/public/build/2352.d7c14cbd3dbda648a17f.js:1207:301)
    at _c (http://g.pigsty/public/build/2352.d7c14cbd3dbda648a17f.js:8832:350)
    at t (http://g.pigsty/public/build/2754.c9252327f51106ea3a6d.js:2:1060624)
    at t (http://g.pigsty/public/build/2754.c9252327f51106ea3a6d.js:2:1062645)
    at main
    at Cd (http://g.pigsty/public/build/2352.d7c14cbd3dbda648a17f.js:8793:6820)
    at t (http://g.pigsty/public/build/2754.c9252327f51106ea3a6d.js:2:1057242)
    at div
    at o (http://g.pigsty/public/build/2352.d7c14cbd3dbda648a17f.js:1996:4308)
    at t.KBarProvider (http://g.pigsty/public/build/2754.c9252327f51106ea3a6d.js:2:271053)
    at l (http://g.pigsty/public/build/2352.d7c14cbd3dbda648a17f.js:6145:19538)
    at c (http://g.pigsty/public/build/2352.d7c14cbd3dbda648a17f.js:1207:301)
    at u (http://g.pigsty/public/build/2352.d7c14cbd3dbda648a17f.js:1207:855)
    at l (http://g.pigsty/public/build/2754.c9252327f51106ea3a6d.js:2:1040276)
    at bu (http://g.pigsty/public/build/2352.d7c14cbd3dbda648a17f.js:8845:115)
```

```js
  function addCrumbs(node: NavModelItem) {
    // construct the URL to match
    // we want to ignore query params except for the editview query param
    const urlSearchParams = new URLSearchParams(node.url?.split('?')[1]);
    let urlToMatch = `${node.url?.split('?')[0]}`;
    if (urlSearchParams.has('editview')) {
      urlToMatch += `?editview=${urlSearchParams.get('editview')}`;
    }
    if (!foundHome && !node.hideFromBreadcrumbs) {
      if (homeNav && urlToMatch === homeNav.url) {
        crumbs.unshift({ text: getNavTitle(homeNav.id) ?? homeNav.text, href: node.url ?? '' });
        foundHome = true;
      } else {
        crumbs.unshift({ text: getNavTitle(node.id) ?? node.text, href: node.url ?? '' });
      }
    }

    if (node.parentItem) {
      addCrumbs(node.parentItem);
    }
  }
```

**What you expected to happen**:

work as older grafana version

**How to reproduce it (as minimally and precisely as possible)**:

Import dashboard [`home.json`](https://github.com/Vonng/pigsty/blob/v2.0.0-a1/roles/grafana/files/dashboards/home.json) , star the dashboard and refresh the browser

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.3.0 and 9.3.1
- Data source type & version: default
- OS Grafana is installed on: CentOS 7.9 / Rocky 8.6 / Rocky 9.0
- User OS & Browser: Chrome 107.0.5304.121 / Safari 16.0
- Grafana plugins:  [ volkovlabs-echarts-panel, marcusolsson-treemap-panel]
- Others:

**Comment by zuchka** [comment]
Thanks for creating this issue, @Vonng 

I was able to reproduce this on main. WARNING: do not try to reproduce in prod. You need to remove the dashboard from the DB in order to revert the error.

Here are steps using a local developer environment:

1. make a backup of your local db (just in case)

```
cp data/grafana.db data/grafana-backup.db
```

2. now import this JSON where UID = home. Or create a scratch dashboard and manually change the UID. Dont use an existing one:

```
{
  "__inputs": [],
  "__elements": {},
  "__requires": [
    {
      "type": "grafana",
      "id": "grafana",
      "name": "Grafana",
      "version": "9.4.0-pre"
    },
    {
      "type": "panel",
      "id": "timeseries",
      "name": "Time series",
      "version": ""
    }
  ],
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": null,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "datasource",
        "uid": "grafana"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "title": "Panel Title",
      "type": "timeseries"
    }
  ],
  "schemaVersion": 37,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "break-my-grafana",
  "uid": "home",
  "version": 2,
  "weekStart": ""
}
```
3. Star the dashboard. I don't know how or why but this is crucial. 
4. Now either log out of grafana and log back in or use `COMMAND + SHIFT + R` / whatever to do a hard refresh in the browser. You will get the error described above. It will break every dashboard-related url.

5. undo the damage. shell into db:

```
sqlite3 data/grafana.db
```

6. delete dashboard with UID = "home":

```
DELETE FROM dashboard WHERE uid = "home";
```

7. type `.quit` to exit shell and then refresh browser. you're back to normal.

In my developer tools I saw some references to i18n files so I added the i18n tag as well.
