### ISSUE TITLE
Explore: Prom after split screen: `TypeError: Cannot read properties of undefined (reading 'fields')`

### ISSUE THREAD

**Issue by samjewell** [grafana/grafana#60060]
**What happened**:
See video: https://www.loom.com/share/c7ad8e30fb344742b132736fd2bdd33a

- Run a Prom Query
- Split the screen
- Edit the query in the left-hand pane
- Shift-Enter to execute the query (but right pane executes - see #60059)
- Now click the mouse to execute the left-pane query
- Some kind of error message appears.

Error is as follows:

<details><summary>Error text Output</summary>
 
An unexpected error happened
Details
TypeError: Cannot read properties of undefined (reading 'fields')

    at d (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/2423.843a2f33e1396b03bd24.js:3282:2513)
    at b (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/2423.843a2f33e1396b03bd24.js:1685:2794)
    at T (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/2423.843a2f33e1396b03bd24.js:3025:966)
    at TimeSeries
    at G.c.setPanelChangeHandler.fieldConfig (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/2423.843a2f33e1396b03bd24.js:9392:890)
    at r (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/2423.843a2f33e1396b03bd24.js:2:542)
    at c (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/2423.843a2f33e1396b03bd24.js:1241:301)
    at u (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/2423.843a2f33e1396b03bd24.js:1241:855)
    at x (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/2423.843a2f33e1396b03bd24.js:8681:12065)
    at kt (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/explore.0d7766659a724c1a5602.js:57:487)
    at div
    at div
    at div
    at h (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/2423.843a2f33e1396b03bd24.js:251:321)
    at Mt (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/explore.0d7766659a724c1a5602.js:70:461)
    at c (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/2423.843a2f33e1396b03bd24.js:1241:301)
    at u (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/2423.843a2f33e1396b03bd24.js:1241:855)
    at c (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/2423.843a2f33e1396b03bd24.js:1241:301)
    at u (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/2423.843a2f33e1396b03bd24.js:1241:855)
    at main
    at div
    at t (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/6022.c8ceedd02d7b6b36a321.js:2:1216170)
    at div
    at div
    at div
    at t (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/6022.c8ceedd02d7b6b36a321.js:2:719634)
    at p (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/2423.843a2f33e1396b03bd24.js:435:3279)
    at ao (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/explore.0d7766659a724c1a5602.js:488:3564)
    at g (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/6022.c8ceedd02d7b6b36a321.js:2:1050277)
    at WithTheme(Connect(ao))
    at div
    at uo (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/explore.0d7766659a724c1a5602.js:511:3047)
    at g (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/6022.c8ceedd02d7b6b36a321.js:2:1050277)
    at WithTheme(Connect(uo))
    at c (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/2423.843a2f33e1396b03bd24.js:1241:301)
    at u (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/2423.843a2f33e1396b03bd24.js:1241:855)
    at div
    at o (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/7303.6c0c803ec301459098af.js:1:2322)
    at div
    at o (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/7303.6c0c803ec301459098af.js:1:4236)
    at F (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/7303.6c0c803ec301459098af.js:1:9705)
    at div
    at div
    at bo (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/explore.0d7766659a724c1a5602.js:527:351)
    at Suspense
    at c (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/2423.843a2f33e1396b03bd24.js:1241:301)
    at ts (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/2423.843a2f33e1396b03bd24.js:5620:348)
    at t (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/6022.c8ceedd02d7b6b36a321.js:2:1068670)
    at t (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/6022.c8ceedd02d7b6b36a321.js:2:1070691)
    at main
    at Pt (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/2423.843a2f33e1396b03bd24.js:5581:6999)
    at t (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/6022.c8ceedd02d7b6b36a321.js:2:1065288)
    at div
    at o (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/2423.843a2f33e1396b03bd24.js:2091:4677)
    at t.KBarProvider (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/6022.c8ceedd02d7b6b36a321.js:2:279862)
    at l (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/2423.843a2f33e1396b03bd24.js:6341:20330)
    at c (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/2423.843a2f33e1396b03bd24.js:1241:301)
    at u (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/2423.843a2f33e1396b03bd24.js:1241:855)
    at l (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/6022.c8ceedd02d7b6b36a321.js:2:1048322)
    at Vs (https://grafana-assets.grafana.net/grafana/9.4.0-45061pre/public/build/2423.843a2f33e1396b03bd24.js:5633:167)

</details>

**What you expected to happen**:
Work the first time around too, not just the second time around

**How to reproduce it (as minimally and precisely as possible)**:
See video

**Anything else we need to know?**:
No

**Environment**:

I used "Explore to Dashboard" and then "Panel Help" to quickly get the environment data - here it is:

| Key | Value |
|--|--|
| Panel | timeseries @ 9.4.0-45061pre (29d2f86955) |
| Grafana | 9.4.0-45061pre (29d2f86955) // Enterprise |
<details><summary>Panel debug snapshot dashboard</summary>

```json
{
  "panels": [
    {
      "id": 2,
      "gridPos": {
        "h": 13,
        "w": 15,
        "x": 0,
        "y": 0
      },
      "type": "timeseries",
      "title": "Reproduced with embedded data",
      "datasource": {
        "type": "grafana",
        "uid": "grafana"
      },
      "targets": [
        {
          "refId": "A",
          "datasource": {
            "type": "grafana",
            "uid": "grafana"
          },
          "queryType": "snapshot",
          "snapshot": [
            {
              "schema": {
                "refId": "A",
                "meta": {
                  "type": "timeseries-multi",
                  "custom": {
                    "resultType": "vector"
                  },
                  "executedQueryString": "Expr: count(grafanacloud_instance_active_series)\nStep: 15s",
                  "preferredVisualisationType": "graph"
                },
                "name": "count(grafanacloud_instance_active_series)",
                "fields": [
                  {
                    "name": "Time",
                    "type": "time",
                    "typeInfo": {
                      "frame": "time.Time"
                    },
                    "config": {
                      "interval": 15000
                    }
                  },
                  {
                    "name": "Value",
                    "type": "number",
                    "typeInfo": {
                      "frame": "float64"
                    },
                    "labels": {},
                    "config": {
                      "displayNameFromDS": "count(grafanacloud_instance_active_series)"
                    }
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    1670535180000
                  ],
                  [
                    3
                  ]
                ]
              }
            },
            {
              "schema": {
                "refId": "A",
                "meta": {
                  "type": "timeseries-multi",
                  "custom": {
                    "resultType": "matrix"
                  },
                  "executedQueryString": "Expr: count(grafanacloud_instance_active_series)\nStep: 15s",
                  "preferredVisualisationType": "graph"
                },
                "name": "count(grafanacloud_instance_active_series)",
                "fields": [
                  {
                    "name": "Time",
                    "type": "time",
                    "typeInfo": {
                      "frame": "time.Time"
                    },
                    "config": {
                      "interval": 15000
                    }
                  },
                  {
                    "name": "Value",
                    "type": "number",
                    "typeInfo": {
                      "frame": "float64"
                    },
                    "labels": {},
                    "config": {
                      "displayNameFromDS": "count(grafanacloud_instance_active_series)"
                    }
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    1670534880000,
                    1670534895000,
                    1670534910000,
                    1670534925000,
                    1670534940000,
                    1670534955000,
                    1670534970000,
                    1670534985000,
                    1670535000000,
                    1670535015000,
                    1670535030000,
                    1670535045000,
                    1670535060000,
                    1670535075000,
                    1670535090000,
                    1670535105000,
                    1670535120000,
                    1670535135000,
                    1670535150000,
                    1670535165000,
                    1670535180000
                  ],
                  [
                    3,
                    3,
                    3,
                    3,
                    3,
                    3,
                    3,
                    3,
                    3,
                    3,
                    3,
                    3,
                    3,
                    3,
                    3,
                    3,
                    3,
                    3,
                    3,
                    3,
                    3
                  ]
                ]
              }
            }
          ]
        }
      ],
      "options": {
        "tooltip": {
          "mode": "single",
          "sort": "none"
        },
        "legend": {
          "showLegend": true,
          "displayMode": "list",
          "placement": "bottom",
          "calcs": []
        }
      },
      "fieldConfig": {
        "defaults": {
          "custom": {
            "drawStyle": "line",
            "lineInterpolation": "linear",
            "barAlignment": 0,
            "lineWidth": 1,
            "fillOpacity": 0,
            "gradientMode": "none",
            "spanNulls": false,
            "showPoints": "auto",
            "pointSize": 5,
            "stacking": {
              "mode": "none",
              "group": "A"
            },
            "axisPlacement": "auto",
            "axisLabel": "",
            "axisColorMode": "text",
            "scaleDistribution": {
              "type": "linear"
            },
            "axisCenteredZero": false,
            "hideFrom": {
              "tooltip": false,
              "viz": false,
              "legend": false
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "color": {
            "mode": "palette-classic"
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "value": null,
                "color": "green"
              },
              {
                "value": 80,
                "color": "red"
              }
            ]
          }
        },
        "overrides": []
      }
    },
    {
      "gridPos": {
        "h": 7,
        "w": 9,
        "x": 15,
        "y": 0
      },
      "id": 5,
      "options": {
        "content": "<table width=\"100%\">\n    <tr>\n      <th width=\"2%\">Panel</th>\n      <td >timeseries @ 9.4.0-45061pre (29d2f86955)</td>\n    </tr>\n    <tr>\n      <th>Queries</th>\n      <td>A[prometheus]</td>\n    </tr>\n    \n    <tr><th>Data</th><td> 2 frames, 4 fields, 22 rows </td></tr>\n    \n    <tr>\n      <th>Grafana</th>\n      <td>9.4.0-45061pre (29d2f86955) // Enterprise</td>\n    </tr>\n  </table>",
        "mode": "html"
      },
      "title": "Debug info",
      "type": "text"
    },
    {
      "id": 6,
      "title": "Original Panel JSON",
      "type": "text",
      "gridPos": {
        "h": 13,
        "w": 9,
        "x": 15,
        "y": 7
      },
      "options": {
        "content": "{\n  \"id\": 1,\n  \"gridPos\": {\n    \"x\": 0,\n    \"y\": 0,\n    \"w\": 12,\n    \"h\": 8\n  },\n  \"type\": \"timeseries\",\n  \"title\": \"New Panel\",\n  \"datasource\": {\n    \"type\": \"prometheus\",\n    \"uid\": \"grafanacloud-usage\"\n  },\n  \"targets\": [\n    {\n      \"refId\": \"A\",\n      \"datasource\": {\n        \"type\": \"prometheus\",\n        \"uid\": \"grafanacloud-usage\"\n      },\n      \"editorMode\": \"code\",\n      \"expr\": \"count(grafanacloud_instance_active_series)\",\n      \"legendFormat\": \"__auto\",\n      \"range\": true,\n      \"instant\": true,\n      \"key\": \"Q-a66e5c10-92a0-44ce-bb68-c8e740703c9a-0\"\n    }\n  ],\n  \"options\": {\n    \"tooltip\": {\n      \"mode\": \"single\",\n      \"sort\": \"none\"\n    },\n    \"legend\": {\n      \"showLegend\": true,\n      \"displayMode\": \"list\",\n      \"placement\": \"bottom\",\n      \"calcs\": []\n    }\n  },\n  \"fieldConfig\": {\n    \"defaults\": {\n      \"custom\": {\n        \"drawStyle\": \"line\",\n        \"lineInterpolation\": \"linear\",\n        \"barAlignment\": 0,\n        \"lineWidth\": 1,\n        \"fillOpacity\": 0,\n        \"gradientMode\": \"none\",\n        \"spanNulls\": false,\n        \"showPoints\": \"auto\",\n        \"pointSize\": 5,\n        \"stacking\": {\n          \"mode\": \"none\",\n          \"group\": \"A\"\n        },\n        \"axisPlacement\": \"auto\",\n        \"axisLabel\": \"\",\n        \"axisColorMode\": \"text\",\n        \"scaleDistribution\": {\n          \"type\": \"linear\"\n        },\n        \"axisCenteredZero\": false,\n        \"hideFrom\": {\n          \"tooltip\": false,\n          \"viz\": false,\n          \"legend\": false\n        },\n        \"thresholdsStyle\": {\n          \"mode\": \"off\"\n        }\n      },\n      \"color\": {\n        \"mode\": \"palette-classic\"\n      },\n      \"mappings\": [],\n      \"thresholds\": {\n        \"mode\": \"absolute\",\n        \"steps\": [\n          {\n            \"value\": null,\n            \"color\": \"green\"\n          },\n          {\n            \"value\": 80,\n            \"color\": \"red\"\n          }\n        ]\n      }\n    },\n    \"overrides\": []\n  }\n}",
        "mode": "code",
        "code": {
          "language": "json",
          "showLineNumbers": true,
          "showMiniMap": true
        }
      }
    },
    {
      "id": 3,
      "title": "Data from panel above",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 15,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": true,
          "refId": "A"
        }
      ]
    }
  ],
  "schemaVersion": 37,
  "title": "Debug: New Panel // 2022-12-08 21:33:12",
  "tags": [
    "debug",
    "debug-timeseries"
  ],
  "time": {
    "from": "2022-12-08T21:28:12.323Z",
    "to": "2022-12-08T21:33:12.324Z"
  }
}
```
</details>

**Comment by samjewell** [comment]
I think this is an issue on Grafana Ops. I don't think it's related to splitting the screen. I've hit this error again today on Ops, without using split-screen at all.

**Comment by samjewell** [comment]
**EDIT:**
I've reproduced on my own personal GrafanaCloud instance, **without splitting the screen**. It's not related to splitting the screen at all, this error.

It's present on:

`Grafana | 9.4.0-45130pre (a589929c92) // Enterprise`

**Comment by ifrost** [comment]
Possibly duplicated of #60138

**Comment by gtk-grafana** [comment]
Yeah @samjewell I just merged in a fix for this on main for https://github.com/grafana/grafana/issues/60138, please let me know if you are still running into trouble with this!
