### ISSUE TITLE
From "View rule" -> View in Explore -> `this.input.chunk` is not a function

### ISSUE THREAD

**Issue by samjewell** [grafana/grafana#60526]
**What happened**:

https://www.loom.com/share/d61f73fccdc64688994ed1eb708c8a2c

I don't have much time today, and I'm not personally an active user of this feature. So all I've done is record the video above - see for yourself the repro steps.

Looks like it's because the datasource is `-- Grafana --` when the explore is rendered:

![image](https://user-images.githubusercontent.com/2903904/208448455-d4f225c5-e048-45b6-adf1-553f5e4797b7.png)

```
An unexpected error happened
Details
TypeError: this.input.chunk is not a function

    at https://grafana-assets.grafana.net/grafana/9.4.0-46208pre/public/build/8629.5d292932509a84e48d84.js:57:9428
    at div
    at de (https://grafana-assets.grafana.net/grafana/9.4.0-46208pre/public/build/3382.8d96b5b616d92385ac15.js:2:92536)
    at t.EditorRows (https://grafana-assets.grafana.net/grafana/9.4.0-46208pre/public/build/3382.8d96b5b616d92385ac15.js:2:96943)
    at https://grafana-assets.grafana.net/grafana/9.4.0-46208pre/public/build/8629.5d292932509a84e48d84.js:85:284
    at pa (https://grafana-assets.grafana.net/grafana/9.4.0-46208pre/public/build/8629.5d292932509a84e48d84.js:85:3359)
    at s (https://grafana-assets.grafana.net/grafana/9.4.0-46208pre/public/build/1018.eeedcc387e82d150e222.js:2:183)
    at d (https://grafana-assets.grafana.net/grafana/9.4.0-
```

**Environment**:
 Via a new Panel created from the Explore that showed the error:

From Panel-Help:

| Key | Value |
|--|--|
| Panel | table @ 9.4.0-46208pre |
| Grafana | 9.4.0-46208pre (4346a91dee) // Enterprise |
<details><summary>Panel debug snapshot dashboard</summary>

```json
{
  "panels": [
    {
      "gridPos": {
        "h": 13,
        "w": 15,
        "x": 0,
        "y": 0
      },
      "type": "table",
      "title": "Reproduced with embedded data",
      "datasource": {
        "type": "grafana",
        "uid": "grafana"
      },
      "targets": [
        {
          "refId": "A",
          "datasource": {
            "type": "grafana",
            "uid": "grafana"
          },
          "queryType": "snapshot",
          "snapshot": [
            {
              "schema": {
                "refId": "A",
                "fields": [
                  {
                    "name": "time",
                    "type": "time",
                    "typeInfo": {
                      "frame": "time.Time",
                      "nullable": true
                    },
                    "config": {
                      "interval": 60000
                    }
                  },
                  {
                    "name": "A-series",
                    "type": "number",
                    "typeInfo": {
                      "frame": "float64",
                      "nullable": true
                    },
                    "labels": {},
                    "config": {}
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    1671438619483,
                    1671438679483,
                    1671438739483,
                    1671438799483,
                    1671438859483,
                    1671438919483,
                    1671438979483,
                    1671439039483,
                    1671439099483,
                    1671439159483,
                    1671439219483,
                    1671439279483,
                    1671439339483,
                    1671439399483,
                    1671439459483,
                    1671439519483,
                    1671439579483,
                    1671439639483,
                    1671439699483,
                    1671439759483,
                    1671439819483,
                    1671439879483,
                    1671439939483,
                    1671439999483,
                    1671440059483,
                    1671440119483,
                    1671440179483,
                    1671440239483,
                    1671440299483,
                    1671440359483,
                    1671440419483,
                    1671440479483,
                    1671440539483,
                    1671440599483,
                    1671440659483,
                    1671440719483,
                    1671440779483,
                    1671440839483,
                    1671440899483,
                    1671440959483,
                    1671441019483,
                    1671441079483,
                    1671441139483,
                    1671441199483,
                    1671441259483,
                    1671441319483,
                    1671441379483,
                    1671441439483,
                    1671441499483,
                    1671441559483,
                    1671441619483,
                    1671441679483,
                    1671441739483,
                    1671441799483,
                    1671441859483,
                    1671441919483,
                    1671441979483,
                    1671442039483,
                    1671442099483,
                    1671442159483,
                    1671442219483,
                    1671442279483,
                    1671442339483,
                    1671442399483,
                    1671442459483,
                    1671442519483,
                    1671442579483,
                    1671442639483,
                    1671442699483,
                    1671442759483,
                    1671442819483,
                    1671442879483,
                    1671442939483,
                    1671442999483,
                    1671443059483,
                    1671443119483,
                    1671443179483,
                    1671443239483,
                    1671443299483,
                    1671443359483,
                    1671443419483,
                    1671443479483,
                    1671443539483,
                    1671443599483,
                    1671443659483,
                    1671443719483,
                    1671443779483,
                    1671443839483,
                    1671443899483,
                    1671443959483,
                    1671444019483,
                    1671444079483,
                    1671444139483,
                    1671444199483,
                    1671444259483,
                    1671444319483,
                    1671444379483,
                    1671444439483,
                    1671444499483,
                    1671444559483,
                    1671444619483,
                    1671444679483,
                    1671444739483,
                    1671444799483,
                    1671444859483,
                    1671444919483,
                    1671444979483,
                    1671445039483,
                    1671445099483,
                    1671445159483,
                    1671445219483,
                    1671445279483,
                    1671445339483,
                    1671445399483,
                    1671445459483,
                    1671445519483,
                    1671445579483,
                    1671445639483,
                    1671445699483,
                    1671445759483,
                    1671445819483,
                    1671445879483,
                    1671445939483,
                    1671445999483,
                    1671446059483,
                    1671446119483,
                    1671446179483,
                    1671446239483,
                    1671446299483,
                    1671446359483,
                    1671446419483,
                    1671446479483,
                    1671446539483,
                    1671446599483,
                    1671446659483,
                    1671446719483,
                    1671446779483,
                    1671446839483,
                    1671446899483,
                    1671446959483,
                    1671447019483,
                    1671447079483,
                    1671447139483,
                    1671447199483,
                    1671447259483,
                    1671447319483,
                    1671447379483,
                    1671447439483,
                    1671447499483,
                    1671447559483,
                    1671447619483,
                    1671447679483,
                    1671447739483,
                    1671447799483,
                    1671447859483,
                    1671447919483,
                    1671447979483,
                    1671448039483,
                    1671448099483,
                    1671448159483,
                    1671448219483,
                    1671448279483,
                    1671448339483,
                    1671448399483,
                    1671448459483,
                    1671448519483,
                    1671448579483,
                    1671448639483,
                    1671448699483,
                    1671448759483,
                    1671448819483,
                    1671448879483,
                    1671448939483,
                    1671448999483,
                    1671449059483,
                    1671449119483,
                    1671449179483,
                    1671449239483,
                    1671449299483,
                    1671449359483,
                    1671449419483,
                    1671449479483,
                    1671449539483,
                    1671449599483,
                    1671449659483,
                    1671449719483,
                    1671449779483,
                    1671449839483,
                    1671449899483,
                    1671449959483,
                    1671450019483,
                    1671450079483,
                    1671450139483,
                    1671450199483,
                    1671450259483,
                    1671450319483,
                    1671450379483,
                    1671450439483,
                    1671450499483,
                    1671450559483,
                    1671450619483,
                    1671450679483,
                    1671450739483,
                    1671450799483,
                    1671450859483,
                    1671450919483,
                    1671450979483,
                    1671451039483,
                    1671451099483,
                    1671451159483,
                    1671451219483,
                    1671451279483,
                    1671451339483,
                    1671451399483,
                    1671451459483,
                    1671451519483,
                    1671451579483,
                    1671451639483,
                    1671451699483,
                    1671451759483,
                    1671451819483,
                    1671451879483,
                    1671451939483,
                    1671451999483,
                    1671452059483,
                    1671452119483,
                    1671452179483,
                    1671452239483,
                    1671452299483,
                    1671452359483,
                    1671452419483,
                    1671452479483,
                    1671452539483,
                    1671452599483,
                    1671452659483,
                    1671452719483,
                    1671452779483,
                    1671452839483,
                    1671452899483,
                    1671452959483,
                    1671453019483,
                    1671453079483,
                    1671453139483,
                    1671453199483,
                    1671453259483,
                    1671453319483,
                    1671453379483,
                    1671453439483,
                    1671453499483,
                    1671453559483,
                    1671453619483,
                    1671453679483,
                    1671453739483,
                    1671453799483,
                    1671453859483,
                    1671453919483,
                    1671453979483,
                    1671454039483,
                    1671454099483,
                    1671454159483,
                    1671454219483,
                    1671454279483,
                    1671454339483,
                    1671454399483,
                    1671454459483,
                    1671454519483,
                    1671454579483,
                    1671454639483,
                    1671454699483,
                    1671454759483,
                    1671454819483,
                    1671454879483,
                    1671454939483,
                    1671454999483,
                    1671455059483,
                    1671455119483,
                    1671455179483,
                    1671455239483,
                    1671455299483,
                    1671455359483,
                    1671455419483,
                    1671455479483,
                    1671455539483,
                    1671455599483,
                    1671455659483,
                    1671455719483,
                    1671455779483,
                    1671455839483,
                    1671455899483,
                    1671455959483,
                    1671456019483,
                    1671456079483,
                    1671456139483,
                    1671456199483,
                    1671456259483,
                    1671456319483,
                    1671456379483,
                    1671456439483,
                    1671456499483,
                    1671456559483,
                    1671456619483,
                    1671456679483,
                    1671456739483,
                    1671456799483,
                    1671456859483,
                    1671456919483,
                    1671456979483,
                    1671457039483,
                    1671457099483,
                    1671457159483,
                    1671457219483,
                    1671457279483,
                    1671457339483,
                    1671457399483,
                    1671457459483,
                    1671457519483,
                    1671457579483,
                    1671457639483,
                    1671457699483,
                    1671457759483,
                    1671457819483,
                    1671457879483,
                    1671457939483,
                    1671457999483,
                    1671458059483,
                    1671458119483,
                    1671458179483,
                    1671458239483,
                    1671458299483,
                    1671458359483,
                    1671458419483,
                    1671458479483,
                    1671458539483,
                    1671458599483,
                    1671458659483,
                    1671458719483,
                    1671458779483,
                    1671458839483,
                    1671458899483,
                    1671458959483,
                    1671459019483,
                    1671459079483,
                    1671459139483,
                    1671459199483,
                    1671459259483,
                    1671459319483,
                    1671459379483,
                    1671459439483,
                    1671459499483,
                    1671459559483,
                    1671459619483,
                    1671459679483,
                    1671459739483,
                    1671459799483,
                    1671459859483,
                    1671459919483,
                    1671459979483,
                    1671460039483,
                    1671460099483,
                    1671460159483
                  ],
                  [
                    4.724668373906806,
                    4.390464313732553,
                    4.2571411605675245,
                    3.877557012671102,
                    4.092920461250382,
                    4.221482773230322,
                    4.612024493575393,
                    4.966625605483195,
                    4.879618367446182,
                    4.684084154659936,
                    5.15845041679784,
                    5.621235488007387,
                    5.889603216135988,
                    6.094732145076135,
                    6.496114240235732,
                    6.190662796865336,
                    6.632770340176543,
                    7.0614742146042975,
                    6.906584206623267,
                    6.537019051368745,
                    6.3935041016607945,
                    6.010132357682808,
                    5.830696328111099,
                    5.453093443529172,
                    5.207309029320967,
                    5.129896869669888,
                    5.289840029909876,
                    5.256051819665134,
                    4.938746336456178,
                    5.3275573060203545,
                    5.078040476385466,
                    5.421027835103538,
                    5.161104638439097,
                    4.997374193019666,
                    4.8805937840172975,
                    4.433975074990126,
                    4.851951514057276,
                    5.079781246636573,
                    4.629264468976911,
                    4.604744517289695,
                    4.495602523620938,
                    4.988664663886369,
                    5.084004926598596,
                    4.757589073989317,
                    4.480295357534583,
                    4.686729775751785,
                    4.440896699388384,
                    4.849796371082133,
                    5.03558917755032,
                    5.313459944554029,
                    5.053597192785438,
                    4.5644328761883655,
                    4.219740005892225,
                    3.8333824765903035,
                    3.4650113895429686,
                    3.471671620889381,
                    3.204873294992806,
                    3.180100624929376,
                    2.9265030701490597,
                    3.3066859558062354,
                    3.636314424193082,
                    4.054423493907721,
                    3.650516326753979,
                    3.4162275681633605,
                    3.6965536818193443,
                    3.2600847163112476,
                    3.402620206524454,
                    3.5283521917296667,
                    3.6741824740955833,
                    3.491099759521592,
                    3.675093661656524,
                    3.533257229388461,
                    3.538594477307038,
                    3.130431912812816,
                    2.8694201587137513,
                    2.9257680670432418,
                    3.010667917944349,
                    3.29937732834986,
                    3.214544836795046,
                    2.716485341260885,
                    2.5710919295489854,
                    2.8959720276816716,
                    2.7323574657110132,
                    2.3591236564971085,
                    2.416708332709738,
                    2.2920779837644085,
                    2.0932556703387974,
                    1.8579307701211685,
                    1.4833873644597655,
                    1.0565637088045952,
                    0.8846655218941923,
                    0.3861278041694432,
                    0.03465172394328914,
                    0.06694289485776245,
                    0.13428650227495492,
                    0.587222370560335,
                    0.22879600465510974,
                    0.6357931751888176,
                    0.6285434847094646,
                    0.16291535731269724,
                    0.5166815792071714,
                    0.21184739905178301,
                    0.09771317481222391,
                    0.42279816545915744,
                    0.6045929458021233,
                    0.9005889859963191,
                    1.0957613974687015,
                    1.1952712190299013,
                    1.1781449797545616,
                    1.3021799213164722,
                    1.782642386428308,
                    1.3817992588825367,
                    1.2806865890991583,
                    0.9301127761724133,
                    1.0798794237850755,
                    1.080221382896882,
                    0.86973608498364,
                    0.7974819944948492,
                    0.8839972076473587,
                    0.6815352986433696,
                    0.7065822750613475,
                    0.6546262409674393,
                    0.2515977912261902,
                    0.5524407457978484,
                    0.763740976006941,
                    1.0421240079049512,
                    0.9337299870526052,
                    1.1072482509364692,
                    0.7344274217568528,
                    0.27372395773532954,
                    0.0036176066683772934,
                    0.06338600058565036,
                    0.09690894763365598,
                    0.08921040034689204,
                    -0.22659706977779143,
                    0.14371410163296366,
                    0.1426969020466749,
                    0.47350451868841964,
                    0.006828410078895064,
                    -0.316170413117897,
                    -0.2435033929098282,
                    -0.7216361460434843,
                    -0.7982632982265104,
                    -0.8183230872932002,
                    -0.4811670440981263,
                    -0.5371678474244114,
                    -0.5942489420303645,
                    -0.272810719786992,
                    -0.7567521050186504,
                    -0.889694963250806,
                    -0.7111442422404857,
                    -0.9528603633031161,
                    -0.8002246120195833,
                    -1.1984352083470893,
                    -1.2487438554197192,
                    -1.1248955403251266,
                    -0.7967723091119245,
                    -0.44946691304492636,
                    -0.679959645352261,
                    -0.7222345016024174,
                    -1.1036897326354784,
                    -0.9845899316993468,
                    -1.4099582226196152,
                    -1.5017469270657258,
                    -1.232313659513581,
                    -1.5476823559855277,
                    -2.001230894716312,
                    -2.176828862716922,
                    -2.333739022709046,
                    -2.7420151578857217,
                    -3.020133959612438,
                    -2.9069158936182418,
                    -2.949550745751349,
                    -2.645232527060837,
                    -3.142281835557446,
                    -2.6877599672343235,
                    -2.545596854441349,
                    -2.8703827031925835,
                    -2.874946200423451,
                    -2.439419436033864,
                    -2.1673489103909622,
                    -2.194279239770972,
                    -1.8145966439248151,
                    -1.483141525383056,
                    -1.7427120829790164,
                    -1.404566551403588,
                    -0.928809628951567,
                    -0.5709494283619552,
                    -0.8625015816027854,
                    -0.46431991541049744,
                    -0.6360311688347698,
                    -0.3348714780879868,
                    -0.027436722095274813,
                    -0.15284142566572811,
                    -0.29836921465582267,
                    -0.6399463670387265,
                    -0.4887497734749281,
                    -0.8941923493188424,
                    -0.6843892116006033,
                    -0.48305768744363564,
                    -0.6576897922550797,
                    -0.8223639822498046,
                    -0.4166409999744486,
                    -0.09816642088061334,
                    -0.26691705987584097,
                    -0.211949191544113,
                    -0.14954611166693138,
                    -0.11209814021933545,
                    -0.055232170759070776,
                    0.31477196706774596,
                    0.41411625989364137,
                    0.2160427739240935,
                    0.27706825735705715,
                    -0.15549043893267794,
                    0.24727940938082954,
                    -0.23521427861236532,
                    0.23085002097559437,
                    -0.08948683262400176,
                    -0.2179471985684855,
                    -0.65366707464684,
                    -0.42882849669462175,
                    -0.27239412610415425,
                    -0.05392134177717489,
                    0.16216488499341608,
                    0.11196221190689609,
                    -0.09610305492504206,
                    0.16445081476856743,
                    -0.027629376968411945,
                    0.38923845998271933,
                    0.34281317284451696,
                    0.5847801430340075,
                    0.09650014727892109,
                    -0.3125756269636508,
                    -0.646953451400591,
                    -1.0334129366001692,
                    -1.3173244395506396,
                    -1.765851178972818,
                    -1.6125268822484777,
                    -2.0270387171551154,
                    -1.7614087729179415,
                    -2.161151582329068,
                    -2.6181724606358125,
                    -2.2526557168266623,
                    -1.9062153368259085,
                    -1.6912640086083535,
                    -1.2371277320160132,
                    -0.7930937904894545,
                    -1.1969076056978005,
                    -1.3765920382286214,
                    -1.1213451715907876,
                    -0.686763504107711,
                    -0.7012439527364422,
                    -0.4601908422843597,
                    -0.049876175967644154,
                    0.40815288479875944,
                    0.5066147727898246,
                    0.7229155462750162,
                    0.6788184074756773,
                    1.1453697839195982,
                    1.0208299133523109,
                    0.9191751993833706,
                    0.8492194440631338,
                    0.620817487388271,
                    0.32528041176513367,
                    0.3152774626488608,
                    -0.08792482795553491,
                    -0.07567517423838466,
                    0.1253170686630728,
                    0.47290310782975997,
                    0.4387743502788126,
                    0.5332898322094636,
                    0.48159558463138774,
                    0.4719485531190146,
                    0.14712097650630596,
                    0.08021896864066885,
                    -0.012223908268755357,
                    -0.5085725570864315,
                    -0.44138584265776315,
                    0.04062640079711066,
                    0.2564169481083596,
                    0.7252706389395596,
                    0.5386345090459843,
                    0.9479738563679366,
                    1.0878083082651124,
                    0.7709162934836079,
                    1.0661628989279723,
                    1.128639472182749,
                    1.563744656385445,
                    1.0989113247122693,
                    1.2386995506427212,
                    0.9877859015419896,
                    0.6611658533753345,
                    0.933958417748371,
                    0.9628229086244225,
                    0.8633973711662284,
                    1.3537128024657168,
                    1.5452929869674272,
                    1.6874408211832077,
                    1.4334087639019248,
                    1.446678832754123,
                    1.4102505013817637,
                    1.2070900672493738,
                    1.6859557710724595,
                    1.5340014454122417,
                    1.6431512981111454,
                    1.6732415177541093,
                    1.3328967858685474,
                    1.046443929189031,
                    1.4214427614253804,
                    1.3611024852180318,
                    1.6423503506346515,
                    1.3238116605849104,
                    1.466648428046358,
                    1.092534376565502,
                    1.341565594903006,
                    0.9920623863631712,
                    1.466964646663088,
                    1.3049012739395405,
                    1.712469634136236,
                    1.4354416616778285,
                    1.4586062247340363,
                    0.9797123887259995,
                    0.734203530187107,
                    0.9619898287012142,
                    1.0190522562960416,
                    1.0242678527626543,
                    1.1808706517803784,
                    1.093495634189347,
                    1.3896909465360159,
                    1.0329285913782196,
                    1.1698933231039468,
                    1.252959510490545,
                    1.7192681531946516,
                    1.8751910414721986,
                    1.489377144626017,
                    1.0514138373985666,
                    1.1757579841439016,
                    0.8515621232742672,
                    0.7748026153519841,
                    0.6759888910266849,
                    1.0913252886103821,
                    1.2894884538390075,
                    0.9529037431151097,
                    1.0914251739800926,
                    0.7043699433420463,
                    0.688296918858426,
                    0.723065036618265,
                    0.7296237361877149,
                    1.1180793618330955,
                    1.311472462490684,
                    1.8034605098487508,
                    2.012583175367265,
                    2.1073970025644218,
                    2.0556198648488753,
                    2.288053059074992,
                    2.5727692892650227,
                    2.1002957351491216,
                    2.049558207494802,
                    1.9818693931217621,
                    1.8373343498637018
                  ]
                ]
              }
            }
          ]
        }
      ],
      "options": {
        "showHeader": true,
        "footer": {
          "show": false,
          "reducer": [
            "sum"
          ],
          "countRows": false,
          "fields": ""
        }
      },
      "fieldConfig": {
        "defaults": {
          "custom": {
            "align": "auto",
            "displayMode": "auto",
            "inspect": false
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "value": null,
                "color": "green"
              },
              {
                "value": 80,
                "color": "red"
              }
            ]
          }
        },
        "overrides": []
      },
      "id": 2,
      "pluginVersion": "9.4.0-46208pre"
    },
    {
      "gridPos": {
        "h": 7,
        "w": 9,
        "x": 15,
        "y": 0
      },
      "id": 5,
      "options": {
        "content": "<table width=\"100%\">\n    <tr>\n      <th width=\"2%\">Panel</th>\n      <td >table @ 9.4.0-46208pre</td>\n    </tr>\n    <tr>\n      <th>Queries</th>\n      <td>A[datasource]</td>\n    </tr>\n    \n    <tr><th>Data</th><td> 1 frames, 2 fields, 360 rows </td></tr>\n    \n    <tr>\n      <th>Grafana</th>\n      <td>9.4.0-46208pre (4346a91dee) // Enterprise</td>\n    </tr>\n  </table>",
        "mode": "html"
      },
      "title": "Debug info",
      "type": "text"
    },
    {
      "id": 6,
      "title": "Original Panel JSON",
      "type": "text",
      "gridPos": {
        "h": 13,
        "w": 9,
        "x": 15,
        "y": 7
      },
      "options": {
        "content": "{\n  \"gridPos\": {\n    \"x\": 0,\n    \"y\": 0,\n    \"w\": 12,\n    \"h\": 8\n  },\n  \"type\": \"table\",\n  \"title\": \"New Panel\",\n  \"datasource\": {\n    \"type\": \"datasource\",\n    \"uid\": \"grafana\"\n  },\n  \"targets\": [\n    {\n      \"refId\": \"A\",\n      \"key\": \"Q-eed9e248-06a9-422e-af9f-62fbf04e9f40-0\",\n      \"datasource\": {\n        \"type\": \"datasource\",\n        \"uid\": \"grafana\"\n      }\n    }\n  ],\n  \"options\": {\n    \"showHeader\": true,\n    \"footer\": {\n      \"show\": false,\n      \"reducer\": [\n        \"sum\"\n      ],\n      \"countRows\": false,\n      \"fields\": \"\"\n    }\n  },\n  \"fieldConfig\": {\n    \"defaults\": {\n      \"custom\": {\n        \"align\": \"auto\",\n        \"displayMode\": \"auto\",\n        \"inspect\": false\n      },\n      \"mappings\": [],\n      \"thresholds\": {\n        \"mode\": \"absolute\",\n        \"steps\": [\n          {\n            \"value\": null,\n            \"color\": \"green\"\n          },\n          {\n            \"value\": 80,\n            \"color\": \"red\"\n          }\n        ]\n      }\n    },\n    \"overrides\": []\n  },\n  \"id\": 1,\n  \"pluginVersion\": \"9.4.0-46208pre\"\n}",
        "mode": "code",
        "code": {
          "language": "json",
          "showLineNumbers": true,
          "showMiniMap": true
        }
      }
    },
    {
      "id": 3,
      "title": "Data from panel above",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 15,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": true,
          "refId": "A"
        }
      ]
    }
  ],
  "schemaVersion": 37,
  "title": "Debug: New Panel // 2022-12-19 14:30:26",
  "tags": [
    "debug",
    "debug-table"
  ],
  "time": {
    "from": "2022-12-19T08:30:26.902Z",
    "to": "2022-12-19T14:30:26.902Z"
  }
}
```
</details>

**Comment by svennergr** [comment]
Hi there,

I took a quick look. Clicking the `View in Explore` button will generate a link like this:
http://localhost:3000/explore?left=%7B%22datasource%22:%22IaiEY2e7z%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%22Loki%22,%22expr%22:%7B%22editorMode%22:%22builder%22,%22expr%22:%22sum%28count_over_time%28%7Bsource%3D%5C%22data%5C%22%7D%20%7C%3D%20%60%60%20%5B$__interval%5D%29%29%22,%22hide%22:false,%22intervalMs%22:1000,%22maxDataPoints%22:43200,%22queryType%22:%22range%22,%22datasource%22:%22Loki%22%7D%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D&orgId=1

That link is generated here https://github.com/grafana/grafana/blob/main/public/app/features/alerting/unified/components/rule-viewer/RuleViewerVisualization.tsx#L141. The `expr` property should be a `string`, but here it is created as an object.

Thus I am passing this to @grafana/observability-experience-squad as they seemed to change it in https://github.com/grafana/grafana/pull/59686.

**Comment by samjewell** [comment]
I'm hyped that this is fixed, thank you @gelicia
