### ISSUE TITLE
unable to initialize the notification log component of alerting: proto: wrong wireType = 2 for field Idx

### ISSUE THREAD

**Issue by cg-nz** [grafana/grafana#61645]
**What happened**:

Hi There.  Firstly thanks for everyone's time and effort on this project.

Our team were adding some additional unified alerting rules, and grafana is SIGSEGV'ing with the following error.
To get around this for now, I have disabled unified_alerting in the config.

`unable to initialize the notification log component of alerting: proto: wrong wireType = 2 for field Idx`

Full Log:

```
logger=settings t=2023-01-17T19:56:55.274707855Z level=info msg="Starting Grafana" version=9.3.2 commit=21c1d14e91 branch=HEAD compiled=2022-12-14T10:40:18Z
logger=settings t=2023-01-17T19:56:55.274933097Z level=info msg="Config loaded from" file=/usr/share/grafana/conf/defaults.ini
logger=settings t=2023-01-17T19:56:55.274945603Z level=info msg="Config loaded from" file=/etc/grafana/grafana.ini
logger=settings t=2023-01-17T19:56:55.274951342Z level=info msg="Config overridden from command line" arg="default.paths.data=/var/lib/grafana"
logger=settings t=2023-01-17T19:56:55.274956973Z level=info msg="Config overridden from command line" arg="default.paths.logs=/var/log/grafana"
logger=settings t=2023-01-17T19:56:55.274962164Z level=info msg="Config overridden from command line" arg="default.paths.plugins=/var/lib/grafana/plugins"
logger=settings t=2023-01-17T19:56:55.27496855Z level=info msg="Config overridden from command line" arg="default.paths.provisioning=/etc/grafana/provisioning"
logger=settings t=2023-01-17T19:56:55.274973583Z level=info msg="Config overridden from command line" arg="default.log.mode=console"
logger=settings t=2023-01-17T19:56:55.274978982Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_DATA=/var/lib/grafana"
logger=settings t=2023-01-17T19:56:55.274984449Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_LOGS=/var/log/grafana"
logger=settings t=2023-01-17T19:56:55.274989564Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_PLUGINS=/var/lib/grafana/plugins"
logger=settings t=2023-01-17T19:56:55.274994503Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_PROVISIONING=/etc/grafana/provisioning"
logger=settings t=2023-01-17T19:56:55.274999513Z level=info msg="Path Home" path=/usr/share/grafana
logger=settings t=2023-01-17T19:56:55.275004393Z level=info msg="Path Data" path=/var/lib/grafana
logger=settings t=2023-01-17T19:56:55.275009073Z level=info msg="Path Logs" path=/var/log/grafana
logger=settings t=2023-01-17T19:56:55.275014421Z level=info msg="Path Plugins" path=/var/lib/grafana/plugins
logger=settings t=2023-01-17T19:56:55.275019339Z level=info msg="Path Provisioning" path=/etc/grafana/provisioning
logger=settings t=2023-01-17T19:56:55.275024255Z level=info msg="App mode production"
logger=sqlstore t=2023-01-17T19:56:55.275083061Z level=info msg="Connecting to DB" dbtype=sqlite3
logger=migrator t=2023-01-17T19:56:55.296178457Z level=info msg="Starting DB migrations"
logger=migrator t=2023-01-17T19:56:55.306020528Z level=info msg="migrations completed" performed=0 skipped=464 duration=762.793µs
logger=plugin.loader t=2023-01-17T19:56:55.388385196Z level=info msg="Plugin registered" pluginID=input
logger=plugin.loader t=2023-01-17T19:56:55.389044602Z level=warn msg="Skipping loading plugin due to problem with signature" pluginID=sumo-logic-metrics-datasource status=unsigned
logger=secrets t=2023-01-17T19:56:55.389367157Z level=info msg="Envelope encryption state" enabled=true currentprovider=secretKey.v1
logger=query_data t=2023-01-17T19:56:55.392461818Z level=info msg="Query Service initialization"
logger=live.push_http t=2023-01-17T19:56:55.397116187Z level=info msg="Live Push Gateway initialization"
logger=ngalert.multiorg.alertmanager t=2023-01-17T19:56:55.399117138Z level=error msg="unable to create Alertmanager for org" org=1 error="unable to initialize the notification log component of alerting: proto: wrong wireType = 2 for field Idx"
logger=cli t=2023-01-17T19:56:55.400619548Z level=error msg="Critical error" reason="runtime error: invalid memory address or nil pointer dereference" stackTrace="goroutine 1 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/grafana/grafana/pkg/cmd/grafana-server/commands.executeServer.func2()\n\t/drone/src/pkg/cmd/grafana-server/commands/cli.go:143 +0x94\npanic({0x30e3340, 0x5c7d690})\n\t/usr/local/go/src/runtime/panic.go:884 +0x212\ngithub.com/grafana/grafana/pkg/services/ngalert/notifier.(*Alertmanager).ApplyConfig(0x0, 0xc000856510?)\n\t/drone/src/pkg/services/ngalert/notifier/alertmanager.go:318 +0xae\ngithub.com/grafana/grafana/pkg/services/ngalert/notifier.(*MultiOrgAlertmanager).SyncAlertmanagersForOrgs(0xc001270c00, {0x3f3bb60, 0xc000124000}, {0xc0017426d0, 0x1, 0x3f3d220?})\n\t/drone/src/pkg/services/ngalert/notifier/multiorg_alertmanager.go:208 +0x772\ngithub.com/grafana/grafana/pkg/services/ngalert/notifier.(*MultiOrgAlertmanager).LoadAndSyncAlertmanagersForOrgs(0xc001270c00, {0x3f3bb60, 0xc000124000})\n\t/drone/src/pkg/services/ngalert/notifier/multiorg_alertmanager.go:140 +0xd8\ngithub.com/grafana/grafana/pkg/services/ngalert.(*AlertNG).init(0xc00138c780)\n\t/drone/src/pkg/services/ngalert/ngalert.go:163 +0x405\ngithub.com/grafana/grafana/pkg/services/ngalert.ProvideService(0xc000bd3000, {0x3f16980?, 0xc000c0d220}, {_, _}, {_, _}, {_, _}, {0x3f4ca20, ...}, ...)\n\t/drone/src/pkg/services/ngalert/ngalert.go:94 +0x529\ngithub.com/grafana/grafana/pkg/server.Initialize({{0x7ffc32fbcd29, 0x18}, {0x7ffc32fbcd0d, 0x12}, {0xc000122040, 0x5, 0x5}}, {{0x0, 0x0}, {0x0, ...}, ...}, ...)\n\t/drone/src/pkg/server/wire_gen.go:397 +0x4165\ngithub.com/grafana/grafana/pkg/cmd/grafana-server/commands.executeServer({0x7ffc32fbcd29, 0x18}, {0x7ffc32fbcd0d, 0x12}, {0x0, 0x0}, {0x7ffc32fbcd4e, 0x6}, 0x203000?, {{0x3f02764, ...}, ...})\n\t/drone/src/pkg/cmd/grafana-server/commands/cli.go:188 +0x7a5\ngithub.com/grafana/grafana/pkg/cmd/grafana-server/commands.RunServer({{0x3f02764, 0x5}, {0x3f03980, 0xa}, {0x3f0275c, 0x4}, {0x3f03970, 0xa}})\n\t/drone/src/pkg/cmd/grafana-server/commands/cli.go:111 +0x758\nmain.main()\n\t/drone/src/pkg/cmd/grafana-server/main.go:16 +0xb7\n"
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x217d18e]

goroutine 1 [running]:
github.com/grafana/grafana/pkg/cmd/grafana-server/commands.executeServer.func2()
	/drone/src/pkg/cmd/grafana-server/commands/cli.go:144 +0x175
panic({0x30e3340, 0x5c7d690})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/grafana/grafana/pkg/services/ngalert/notifier.(*Alertmanager).ApplyConfig(0x0, 0xc000856510?)
	/drone/src/pkg/services/ngalert/notifier/alertmanager.go:318 +0xae
github.com/grafana/grafana/pkg/services/ngalert/notifier.(*MultiOrgAlertmanager).SyncAlertmanagersForOrgs(0xc001270c00, {0x3f3bb60, 0xc000124000}, {0xc0017426d0, 0x1, 0x3f3d220?})
	/drone/src/pkg/services/ngalert/notifier/multiorg_alertmanager.go:208 +0x772
github.com/grafana/grafana/pkg/services/ngalert/notifier.(*MultiOrgAlertmanager).LoadAndSyncAlertmanagersForOrgs(0xc001270c00, {0x3f3bb60, 0xc000124000})
	/drone/src/pkg/services/ngalert/notifier/multiorg_alertmanager.go:140 +0xd8
github.com/grafana/grafana/pkg/services/ngalert.(*AlertNG).init(0xc00138c780)
	/drone/src/pkg/services/ngalert/ngalert.go:163 +0x405
github.com/grafana/grafana/pkg/services/ngalert.ProvideService(0xc000bd3000, {0x3f16980?, 0xc000c0d220}, {_, _}, {_, _}, {_, _}, {0x3f4ca20, ...}, ...)
	/drone/src/pkg/services/ngalert/ngalert.go:94 +0x529
github.com/grafana/grafana/pkg/server.Initialize({{0x7ffc32fbcd29, 0x18}, {0x7ffc32fbcd0d, 0x12}, {0xc000122040, 0x5, 0x5}}, {{0x0, 0x0}, {0x0, ...}, ...}, ...)
	/drone/src/pkg/server/wire_gen.go:397 +0x4165
github.com/grafana/grafana/pkg/cmd/grafana-server/commands.executeServer({0x7ffc32fbcd29, 0x18}, {0x7ffc32fbcd0d, 0x12}, {0x0, 0x0}, {0x7ffc32fbcd4e, 0x6}, 0x203000?, {{0x3f02764, ...}, ...})
	/drone/src/pkg/cmd/grafana-server/commands/cli.go:188 +0x7a5
github.com/grafana/grafana/pkg/cmd/grafana-server/commands.RunServer({{0x3f02764, 0x5}, {0x3f03980, 0xa}, {0x3f0275c, 0x4}, {0x3f03970, 0xa}})
	/drone/src/pkg/cmd/grafana-server/commands/cli.go:111 +0x758
main.main()
	/drone/src/pkg/cmd/grafana-server/main.go:16 +0xb7
```

**What you expected to happen**:

No SIGSEGV.

**How to reproduce it (as minimally and precisely as possible)**:

Additional rules were added

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.3.2. Podman container grafana/grafana-oss:9.3.2
- Data source type & version: Prometheus, Telegraf
- OS Grafana is installed on: RHEL 8.4
- User OS & Browser: Chrome/Mac
- Grafana plugins: Bundled
- Others:

**Comment by cg-nz** [comment]
This was fixed by changing permissions (0700, to 0755) on the host mounted Docker folder for the data directory, still owned by the grafana container user / group. Perplexing, but it's working now.

**Comment by Patrick-Remy** [comment]
After some hours of trying to recover grafana (also latest main branch did not fix it), my fix was to remove stored silences and notifications in the database:

> WARNING: this will effectively remove configured silences! 

- Stop grafana
- Backup `/var/lib/grafana/grafana.db`
- Open sqlite database `/var/lib/grafana/grafana.db` (or /var/lib/docker/volumes/<your-volume>/_data/grafana.db), and list entries of `kv_store`
   ```sh
   sqlite3 grafana.db
   sqlite> SELECT * FROM kv_store WHERE namespace = "alertmanager";
   1|1|alertmanager|notifications|<some-base64>|2022-05-04 09:29:59|2023-01-22 23:27:18.384984943+01:00
   2|1|alertmanager|silences|<some-base64>|2022-05-04 09:29:59|2023-01-22 23:27:18.374074211+01:00
   ....
   ```
- Clear values for alertmanager 
  ```sh
  sqlite> UPDATE kv_store SET value = "" WHERE namespace = "alertmanager";
  ```
- Remove (cached?) alerting data (probably `/var/lib/docker/volumes/`....)
   ```sh
   rm -rf /var/lib/grafana/alerting
   ```

**Comment by goaround** [comment]
@Patrick-Remy thank you!
