### ISSUE TITLE
can't show the configured notifications on alert configuration page

### ISSUE THREAD

**Issue by qingweiqm** [grafana/grafana#6233]
* **I'm submitting a Bug report **
- [ ] Bug report

Please include this information:
- What Grafana version are you using?
the newest
- What datasource are you using?
influxdb
- What OS are you running grafana on?
centos 7
- What did you do?
setting notification on alert configuration
- What was the expected result?
should show the configured notifications.
- What happened instead?
can't see the configured notifications lists.

![2016-10-11 5 43 06](https://cloud.githubusercontent.com/assets/20061689/19266002/34590296-8fda-11e6-8987-76281beca992.png)
![2016-10-11 5 42 58](https://cloud.githubusercontent.com/assets/20061689/19266003/348d256c-8fda-11e6-9715-1316a182c53a.png)
#
**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
any errors in the chrome dev console?

**Comment by torkelo** [comment]
do you have any notifications marked as "send for all alerts"  ?

**Comment by logicall** [comment]
I have the same problem.
This is what is written in the console
This error appears when I turn in "Alert"
`boot.a4fc6d3d.js:37 TypeError: Cannot read property 'length' of null
    at a.initModel (boot.a4fc6d3d.js:47)
    at boot.a4fc6d3d.js:47
    at g (boot.a4fc6d3d.js:38)
    at boot.a4fc6d3d.js:38
    at o.$eval (boot.a4fc6d3d.js:38)
    at o.$digest (boot.a4fc6d3d.js:38)
    at o.$apply (boot.a4fc6d3d.js:38)
    at boot.a4fc6d3d.js:38
    at f (boot.a4fc6d3d.js:36)
    at boot.a4fc6d3d.js:36`

This error appears when I turn in "Notifications" and press "+" in "Send to"
`TypeError: Cannot read property 'map' of null
    at a.getNotifications (http://192.168.20.15:8050/public/app/boot.a4fc6d3d.js:47:24983)
    at fn (eval at compile (http://192.168.20.15:8050/public/app/boot.a4fc6d3d.js:39:27313), <anonymous>:4:249)
    at o.e.(anonymous function) [as getOptions] (http://192.168.20.15:8050/public/app/boot.a4fc6d3d.js:37:8985)
    at http://192.168.20.15:8050/public/app/boot.a4fc6d3d.js:21:12120
    at o.$eval (http://192.168.20.15:8050/public/app/boot.a4fc6d3d.js:38:10041)
    at o.$apply (http://192.168.20.15:8050/public/app/boot.a4fc6d3d.js:38:10274)
    at b.h.source (http://192.168.20.15:8050/public/app/boot.a4fc6d3d.js:21:12100)
    at b.p.lookup (http://192.168.20.15:8050/public/app/boot.a4fc6d3d.js:21:12835)
    at HTMLAnchorElement.<anonymous> (http://192.168.20.15:8050/public/app/boot.a4fc6d3d.js:21:13122)
    at HTMLAnchorElement.dispatch (http://192.168.20.15:8050/public/app/boot.a4fc6d3d.js:34:25088)`

installed version on CentOS7
`rpm -qa | fgrep grafana
grafana-4.0.0-1476202643pre1.x86_64`

**Comment by logicall** [comment]
I have just been updated to version "grafana-4.0.0-1476251942pre1.x86_64"
Problem still exists

**Comment by bergquist** [comment]
Thank you for reporting this!
