### ISSUE TITLE
[Bug] grafana-cli plugins install and segmentation violation

### ISSUE THREAD

**Issue by pavleec** [grafana/grafana#6256]
Hi,

There is something wrong with the  **grafana-cli plugins install** command (Grafana build 4.0.0-1476271887pre1). I've tried to install grafana-clock-panel and got the following error message : 

```
>grafana-cli plugins install grafana-clock-panel

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x487a05]

goroutine 1 [running]:
panic(0x6e3520, 0xc420010100)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/grafana/grafana/pkg/cmd/grafana-cli/services.createRequest(0xc4200db800, 0x1f, 0xc4200e8690, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/grafana/grafana/pkg/cmd/grafana-cli/services/services.go:153 +0x365
github.com/grafana/grafana/pkg/cmd/grafana-cli/services.GetPlugin(0x7fffce01f308, 0x13, 0xc4200db800, 0x1f, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/grafana/grafana/pkg/cmd/grafana-cli/services/services.go:115 +0xdf
github.com/grafana/grafana/pkg/cmd/grafana-cli/commands.InstallPlugin(0x7fffce01f308, 0x13, 0x0, 0x0, 0x88dac0, 0xc420030048, 0x8, 0x727680)
        /go/src/github.com/grafana/grafana/pkg/cmd/grafana-cli/commands/install_command.go:61 +0x89
github.com/grafana/grafana/pkg/cmd/grafana-cli/commands.installCommand(0x88dac0, 0xc420030048, 0x733b65, 0x5)
        /go/src/github.com/grafana/grafana/pkg/cmd/grafana-cli/commands/install_command.go:57 +0x10e
github.com/grafana/grafana/pkg/cmd/grafana-cli/commands.runCommand.func1(0xc4200918c0)
        /go/src/github.com/grafana/grafana/pkg/cmd/grafana-cli/commands/commands.go:15 +0x87
github.com/grafana/grafana/vendor/github.com/codegangsta/cli.Command.Run(0x7343be, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x741716, 0x2f, 0x0, ...)
        /go/src/github.com/grafana/grafana/vendor/github.com/codegangsta/cli/command.go:137 +0xa8b
github.com/grafana/grafana/vendor/github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc420091680, 0xc420091560, 0x0, 0x0)
        /go/src/github.com/grafana/grafana/vendor/github.com/codegangsta/cli/app.go:283 +0x8c7
github.com/grafana/grafana/vendor/github.com/codegangsta/cli.Command.startApp(0x73440b, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x73ab48, 0x1a, 0x0, ...)
        /go/src/github.com/grafana/grafana/vendor/github.com/codegangsta/cli/command.go:215 +0x6e6
github.com/grafana/grafana/vendor/github.com/codegangsta/cli.Command.Run(0x73440b, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x73ab48, 0x1a, 0x0, ...)
        /go/src/github.com/grafana/grafana/vendor/github.com/codegangsta/cli/command.go:59 +0x13ca
github.com/grafana/grafana/vendor/github.com/codegangsta/cli.(*App).Run(0xc420091440, 0xc42000c180, 0x4, 0x4, 0x0, 0x0)
        /go/src/github.com/grafana/grafana/vendor/github.com/codegangsta/cli/app.go:176 +0x919
main.main()
        /go/src/github.com/grafana/grafana/pkg/cmd

**Comment by bergquist** [comment]
Seems like the response from grafana.net was empty. Ive improved the error message. Thank you!

**Comment by theluke55** [comment]
hey guys has this been solved, i'm getting the same error
