### ISSUE TITLE
Cloud Monitoring Time Series Query Nil Logger

### ISSUE THREAD

**Issue by rhbuf** [grafana/grafana#62901]
**What happened**:

I configured an invalid GCP Cloud Monitoring query so that a bad request is returned to Grafana, which then panics because a logger has not been initialised. I initially ran in Grafana Cloud but decided to reproduce locally so I could see the logs.
```
goroutine 627 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x64
github.com/grafana/grafana/pkg/services/ngalert/eval.(*conditionEvaluator).EvaluateRaw.func1()
	/drone/src/pkg/services/ngalert/eval/eval.go:57 +0x70
panic({0x2d99fc0, 0x5705670})
	/usr/local/go/src/runtime/panic.go:884 +0x20c
github.com/grafana/grafana/pkg/tsdb/cloudmonitoring.unmarshalResponse({0x0, 0x0}, 0x4002606fc0)
	/drone/src/pkg/tsdb/cloudmonitoring/cloudmonitoring.go:652 +0x1ec
github.com/grafana/grafana/pkg/tsdb/cloudmonitoring.doRequestQueryPage({0x0, 0x0}, 0x400251bef8?, 0x4001e0eb00, {0x3, {0x0, 0xedb6f1f26, 0x58eee20}, {0x0, 0x0}, ...})
	/drone/src/pkg/tsdb/cloudmonitoring/time_series_query.go:50 +0x194
github.com/grafana/grafana/pkg/tsdb/cloudmonitoring.(*cloudMonitoringTimeSeriesQuery).run(_, {_,_}, _, _, {0x3, {0x0, 0xedb6f1f26, 0x58eee20}, {0x0, ...}, ...}, ...)
	/drone/src/pkg/tsdb/cloudmonitoring/time_series_query.go:96 +0xa9c
github.com/grafana/grafana/pkg/tsdb/cloudmonitoring.(*Service).executeTimeSeriesQuery(0x400072d2c0, {0x3bef578, 0x4001b8c7e0}, 0x463f20?, {0x3, {0x0, 0xedb6f1f26, 0x58eee20}, {0x0, 0x0}, ...}, ...)
	/drone/src/pkg/tsdb/cloudmonitoring/cloudmonitoring.go:282 +0x11c
github.com/grafana/grafana/pkg/tsdb/cloudmonitoring.(*Service).QueryData(0x2fa3c00?, {0x3bef578, 0x4001b8c7e0}, 0x4001a63220)
	/drone/src/pkg/tsdb/cloudmonitoring/cloudmonitoring.go:274 +0x1cc
github.com/grafana/grafana/pkg/plugins/backendplugin/coreplugin.(*corePlugin).QueryData(0x2d927c0?, {0x3bef578?, 0x4001b8c7e0?}, 0x2722b70?)
	/drone/src/pkg/plugins/backendplugin/coreplugin/core_plugin.go:81 +0x38
github.com/grafana/grafana/pkg/plugins.(*Plugin).QueryData(0x42045f0cdb2?, {0x3bef578, 0x4001b8c7e0}, 0xc0ef686700de181f?)
	/drone/src/pkg/plugins/plugins.go:259 +0x68
github.com/grafana/grafana/pkg/plugins/manager/client.(*Service).QueryData.func1()
	/drone/src/pkg/plugins/manager/client/client.go:39 +0x34
github.com/grafana/grafana/pkg/plugins/backendplugin/instrumentation.instrumentPluginRequest({0x3bef578, 0x4001b8c7e0}, 0x40014b6aa0, 0x4001a63220, {0x340b801, 0x9}, 0x400251cd90)
	/drone/src/pkg/plugins/backendplugin/instrumentation/instrumentation.go:41 +0x70
github.com/grafana/grafana/pkg/plugins/backendplugin/instrumentation.InstrumentQueryDataRequest(...)
	/drone/src/pkg/plugins/backendplugin/instrumentation/instrumentation.go:97
github.com/grafana/grafana/pkg/plugins/manager/client.(*Service).QueryData(0x40005923f0?, {0x3bef578?, 0x4001b8c7e0?}, 0x4001a63220?)
	/drone/src/pkg/plugins/manager/client/client.go:38 +0x1cc
github.com/grafana/grafana/pkg/expr.(*DSNode).Execute(0x40025da6e0, {0x3bef578, 0x4001b8c7e0}, {0x40d03c?, 0xffff8b22ca68?, 0x58eee20?}, 0x4000078c00?, 0x400173bef0)
	/drone/src/pkg/expr/nodes.go:239 +0x424
github.com/grafana/grafana/pkg/expr.(*DataPipeline).execute(0x400251d608, {0x3bef578, 0x4001b8c7e0}, {0x30?, 0x400251d598?, 0x58eee20?}, 0x6fc239cb3?)
	/drone/src/pkg/expr/graph.go:53 +0xc4
github.com/grafana/grafana/pkg/expr.(*Service).ExecutePipeline(0x3bef5b0?, {0x3bef578, 0x4001b8c7e0}, {0x4001ae5c80?, 0x0?, 0x58eee20?}, {0x4001ae5c80, 0x3, 0x3})
	/drone/src/pkg/expr/service.go:68 +0xac
github.com/grafana/grafana/pkg/services/ngalert/eval.(*conditionEvaluator).EvaluateRaw(0x4001b8c780?, {0x3bef5b0?, 0x4001b7cf00?}, {0x1ede124?, 0x4002534798?, 0x58eee20?})
	/drone/src/pkg/services/ngalert/eval/eval.go:73 +0xf8
github.com/grafana/grafana/pkg/services/ngalert/eval.(*conditionEvaluator).Evaluate(0x4001b8c780, {0x3bef5b0?, 0x4001b7cf00?}, {0x4001ed67e0?, 0x57ae218?, 0x58eee20?})
	/drone/src/pkg/services/ngalert/eval/eval.go:78 +0x40
github.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRoutine.func2({0x3bef5b0, 0x4001b7cf00}, 0x4002534bc8?, 0x4000b2e688)
	/drone/src/pkg/services/ngalert/schedule/schedule.go:346 +0x4d0
github.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRoutine.func4.2(0x48?)
	/drone/src/pkg/services/ngalert/schedule/schedule.go:434 +0x1e0
github.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRoutine.func3(0x4001a62fa0)
	/drone/src/pkg/services/ngalert/schedule/schedule.go:381 +0x70
github.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRoutine.func4(0x4002534ed0?, 0x4002534dcc?, {0x1?, {0x4001b92d10?, 0x0?}}, 0x4000b2e688, 0x4002534e70, 0x400160dd08, {0x3c00280?, 0x4001b7cf30}, ...)
	/drone/src/pkg/services/ngalert/schedule/schedule.go:424 +0x18c
github.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRoutine(0x400061ca80, {0x3bf0e30, 0x4001b7ce70}, {0x0?, {0x4001b92d10?, 0x4000077f01?}}, 0x400147b2c0, 0x400147b320)
	/drone/src/pkg/services/ngalert/schedule/schedule.go:440 +0x560
github.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).processTick.func1()
	/drone/src/pkg/services/ngalert/schedule/schedule.go:237 +0x40
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/opt/drone/gomodcache/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x5c
created by golang.org/x/sync/errgroup.(*Group).Go
	/opt/drone/gomodcache/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa4
```

**What you expected to happen**:

The error should be shown in the UI and a panic should not be thrown. The logger should not be nil and needs to be added here (relative to v9.3.6):
```patch
diff --git a/pkg/tsdb/cloudmonitoring/cloudmonitoring.go b/pkg/tsdb/cloudmonitoring/cloudmonitoring.go
index a690c78dc4..6defdf2d73 100644
--- a/pkg/tsdb/cloudmonitoring/cloudmonitoring.go
+++ b/pkg/tsdb/cloudmonitoring/cloudmonitoring.go
@@ -338,6 +338,7 @@ func (s *Service) buildQueryExecutors(logger log.Logger, req *backend.QueryDataR
                                        AliasBy:     q.MetricQuery.AliasBy,
                                        timeRange:   req.Queries[0].TimeRange,
                                        GraphPeriod: q.MetricQuery.GraphPeriod,
+                                       logger:      logger,
                                }
                        } else {
                                cmtsf.AliasBy = q.MetricQuery.AliasBy
```

**How to reproduce it (as minimally and precisely as possible)**:

Write a test that returns a 400 from a mock and observe it panic as the logger is not added to the query executor and will be called in `unmarshalResponse`.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.3.6
- Data source type & version: 
- OS Grafana is installed on:
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by alyssabull** [comment]
Hello @rhbuf! I have managed to reproduce this error on Grafana main. Unfortunately, v9.3.6 is no longer supported for bug fixes. I will work on a fix for the next release of Grafana and can keep you posted on when that fix is merged.
