### ISSUE TITLE
[Timeseries] Infinite loop with logarithmic axis

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#63256]
**What happened**:

Timeseries panel with logarithmic axis and this dataset

```csv
"Time","DEN"
2023-02-10 13:55:00,
2023-02-10 14:00:00,134 ms
2023-02-10 14:05:00,132 ms
2023-02-10 14:10:00,133 ms
2023-02-10 14:15:00,138 ms
2023-02-10 14:20:00,138 ms
2023-02-10 14:25:00,133 ms
2023-02-10 14:30:00,138 ms
2023-02-10 14:35:00,129 ms
2023-02-10 14:40:00,126 ms
2023-02-10 14:45:00,137 ms
2023-02-10 14:50:00,127 ms
```

crashes on

```
es.array.push.js:34 Uncaught RangeError: Invalid array length
    at Array.push (es.array.push.js:34:1)
    at Object.logAxisSplits [as splits] (uPlot.esm.js:1358:1)
    at uPlot.esm.js:4085:1
    at Array.forEach (<anonymous>)
    at axesCalc (uPlot.esm.js:4050:1)
    at convergeSize (uPlot.esm.js:3129:1)
    at _commit (uPlot.esm.js:4340:1)
```

This is the commit that caused it, without it, it does not happen

https://github.com/grafana/grafana/pull/60768

It infinitely loops through this do statement 

https://github.com/leeoniya/uPlot/blob/1e4ea5427100f81750a93c1ab9f5b78d3c0bf116/dist/uPlot.esm.js#L1357-L1367

**Environment**:
- Grafana version: 0bd326d846bba158be115cb2de8992d9e037409c

**Comment by leeoniya** [comment]
plz provide more detailed info.

what min/max settings are you using?

this doesnt crash for me: (with min/max not set)

![image](https://user-images.githubusercontent.com/43234/218132754-e2598806-11c0-4901-aee3-c04a5575f229.png)

```
"Time","DEN"
2023-02-10T13:55:00Z,
2023-02-10T14:00:00Z,134
2023-02-10T14:05:00Z,132
2023-02-10T14:10:00Z,133
2023-02-10T14:15:00Z,138
2023-02-10T14:20:00Z,138
2023-02-10T14:25:00Z,133
2023-02-10T14:30:00Z,138
2023-02-10T14:35:00Z,129
2023-02-10T14:40:00Z,126
2023-02-10T14:45:00Z,137
2023-02-10T14:50:00Z,127
```

**Comment by simPod** [comment]
I have this definition:

```json
{
  "datasource": {
    "uid": "-- Mixed --",
    "type": "datasource"
  },
  "fieldConfig": {
    "defaults": {
      "custom": {
        "drawStyle": "line",
        "lineInterpolation": "stepBefore",
        "barAlignment": 0,
        "lineWidth": 1,
        "fillOpacity": 70,
        "gradientMode": "none",
        "spanNulls": false,
        "showPoints": "auto",
        "pointSize": 5,
        "stacking": {
          "mode": "none",
          "group": false
        },
        "axisPlacement": "auto",
        "axisLabel": "",
        "axisColorMode": "text",
        "scaleDistribution": {
          "type": "linear"
        },
        "axisCenteredZero": false,
        "hideFrom": {
          "tooltip": false,
          "viz": false,
          "legend": false
        },
        "thresholdsStyle": {
          "mode": "line"
        },
        "axisSoftMin": 0
      },
      "color": {
        "mode": "palette-classic"
      },
      "mappings": [],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "transparent",
            "value": null
          },
          {
            "color": "#ffffff",
            "value": 0
          }
        ]
      },
      "unit": "ms"
    },
    "overrides": [
      {
        "matcher": {
          "id": "byRegexp",
          "options": "/[A-Z]{3}/"
        },
        "properties": [
          {
            "id": "custom.fillOpacity",
            "value": 0
          },
          {
            "id": "min",
            "value": 0
          },
          {
            "id": "custom.scaleDistribution",
            "value": {
              "log": 2,
              "type": "log"
            }
          },
          {
            "id": "unit",
            "value": "ms"
          }
        ]
      }
    ]
  },
  "gridPos": {
    "h": 8,
    "w": 24,
    "x": 0,
    "y": 40
  },
  "id": 6,
  "links": [],
  "options": {
    "tooltip": {
      "mode": "multi",
      "sort": "none"
    },
    "legend": {
      "showLegend": true,
      "displayMode": "table",
      "placement": "right",
      "calcs": [
        "max",
        "last",
        "pctl95"
      ]
    }
  },
  "targets": [
    {
      "datasource": {
        "uid": "000000002",
        "type": "simpod-json-datasource"
      },
      "alias": "",
      "payload": "{}",
      "refId": "A",
      "target": "something",
      "editorMode": "code"
    }
  ],
  "title": "hi",
  "transformations": [],
  "transparent": true,
  "type": "timeseries",
  "minSpan": null,
  "repeat": null,
  "repeatDirection": null
}
```

**Comment by leeoniya** [comment]
we should fix this so it doesn't crash.

however, but Logarithmic axes cannot mathematically reach zero (or be negatove), so the fix would be simply to ignore your settings. Symlog should be able to support 0 and negatives, but that doesnt seem to work currently.

**Comment by simPod** [comment]
Yup, sth like a warning to tell user what to do or sth like that idk. But not infinite loop I guess. 👌🏾

**Comment by leeoniya** [comment]
pretty sure this will fix it: https://github.com/grafana/grafana/pull/59758
