### ISSUE TITLE
Selecting "Raw Document" metric breaks graph permanently

### ISSUE THREAD

**Issue by jacobweber** [grafana/grafana#6367]
- **I'm submitting a ...**
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 3.1.1
- What datasource are you using? Elasticsearch
- What OS are you running grafana on? CentOS 6.8
- What did you do? Select Metric = "Raw Document", then change Metric back to something else, like "Max".
- What was the expected result? Sub-fields appear for editing selected metric, e.g. selecting "Max" shows another field next to it, to enter the name of the field to use in the metric.
- What happened instead? Panel stops working. If you save it in this state, it becomes permanently broken. The next time you open the editor, the Metrics panel shows "{{ctrl.target.refId}} ({{ctrl.target.datasource}}" instead of the metrics fields.

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

When you select "Raw Document", it performs a query, which returns valid results. In the JS console, an error appears:

```
TypeError: Cannot read property 'toString' of undefined
    at a.isMsResolutionNeeded (https://grafana.dev.scivantage.com/public/app/boot.1649cbaa.js:19:17889)
    at h.seriesHandler (https://grafana.dev.scivantage.com/public/app/boot.1649cbaa.js:17:18589)
    at Array.map (native)
    at h.onDataReceived (https://grafana.dev.scivantage.com/public/app/boot.1649cbaa.js:17:17896)
    at e.emit (https://grafana.dev.scivantage.com/public/app/boot.1649cbaa.js:39:22558)
    at a.emit (https://grafana.dev.scivantage.com/public/app/boot.1649cbaa.js:39:24649)
    at h.f.handleQueryResult (https://grafana.dev.scivantage.com/public/app/boot.1649cbaa.js:41:18076)
    at h (https://grafana.dev.scivantage.com/public/app/boot.1649cbaa.js:36:20031)
    at https://grafana.dev.scivantage.com/public/app/boot.1649cbaa.js:36:20203
    at n.$eval (https://grafana.dev.scivantage.com/public/app/boot.1649cbaa.js:36:27720)
Panel data error: TypeError: Cannot read property 'toString' of undefined(…)
```

Then when you select a different metric type, like "Sum", another error appears:

```
Object {message: "Invalid query"}
```

**Comment by torkelo** [comment]
You cannot use Sum with Raw Document you need a bucket aggregation (Terms or date histogram). 

The graph panel does not support Raw Document queries currently, only table panel. 

But the "Invalid Query" error that breaks the query editor is a bug that should be fixed.

**Comment by jacobweber** [comment]
Just to clarify, I wasn't try to use both Sum and Raw Document; I was trying to switch between them. And when I selected Raw Document, all the "group by" fields disappeared, so I couldn't do a bucket aggregation.

Same behavior on the Table panel.

**Comment by widgetpl** [comment]
I have the same problem but with Prometheus datasource. Not sure why this error appeared ( maybe because of templated datasource and switching between them ).

Message:
```
Cannot read property 'replace' of undefined
```

Stack trace:
```
TypeError: Cannot read property 'replace' of undefined
    at k (http://172.16.239.3:3000/public/app/plugins/datasource/prometheus/datasource.js?bust=1488531981383:4:156)
    at l (http://172.16.239.3:3000/public/app/boot.6d63bd8b.js:52:14654)
    at Function.Sg [as map] (http://172.16.239.3:3000/public/app/boot.6d63bd8b.js:53:15348)
    at interpolateQueryExpr (http://172.16.239.3:3000/public/app/plugins/datasource/prometheus/datasource.js?bust=1488531981383:4:809)
    at Object.formatValue (http://172.16.239.3:3000/public/app/boot.6d63bd8b.js:10:25506)
    at http://172.16.239.3:3000/public/app/boot.6d63bd8b.js:10:26856
    at RegExp.[Symbol.replace] (<anonymous>)
    at String.replace (native)
    at Object.replace (http://172.16.239.3:3000/public/app/boot.6d63bd8b.js:10:26579)
    at eval (http://172.16.239.3:3000/public/app/plugins/datasource/prometheus/datasource.js?bust=1488531981383:4:1153)
```

**Comment by RalfJung** [comment]
Same problem here with a 4.1.2 Debian package.

**Comment by pathikmehta** [comment]
I am facing the same problem with version 5.3.2 as well.

**Comment by volter** [comment]
Can somebody correct the typo in "Documnent" in the title?

**Comment by marefr** [comment]
Let us know if anyone interested in contributing a fix for this? We'll be available with guidance and helping out reviewing etc.
