### ISSUE TITLE
Bug: Alerting InfluxDB Source: Runtime Error

### ISSUE THREAD

**Issue by berglh** [grafana/grafana#6531]
- [x] Bug report

- What Grafana version are you using?
I am running `Grafana v4.0.0-beta1 (commit: 6a81389)` inside the Docker container [https://hub.docker.com/r/grafana/grafana/](https://hub.docker.com/r/grafana/grafana/)
- What datasource are you using?
`Influxdb v0.13.0`
- What OS are you running grafana on?
 `Oracle Enterprise Linux 7`
- What did you do?
Running Grafana behind a nginx reverse proxy.
I create an alert and attempt to test it. I'm using a single series source. I've tried a variety of different conditions relevant to my alert type. The series was a redis queue size. The series name was in the format "hostname.redis.queue".
![5769400](https://cloud.githubusercontent.com/assets/12455338/20166491/f2c66898-a760-11e6-9101-2f709386f78d.png)
- What was the expected result?
It test successfully against InfluxDB datasource.
- What happened instead?
After posting the request to test, I receive a 502 bad gateway and Grafana crashes with the following log entries:
```
Nov 10 15:53:06 REDACTED docker[56367]: master: Pulling from grafana/grafana
Nov 10 15:53:06 REDACTED docker[56367]: 386a066cd84a: Already exists
Nov 10 15:53:06 REDACTED docker[56367]: a3ed95caeb02: Already exists
Nov 10 15:53:06 REDACTED docker[56367]: 03856a03d6d2: Already exists
Nov 10 15:53:06 REDACTED docker[56367]: a3ed95caeb02: Already exists
Nov 10 15:53:06 REDACTED docker[56367]: a3ed95caeb02: Already exists
Nov 10 15:53:06 REDACTED docker[56367]: 970a2c610b94: Already exists
Nov 10 15:53:06 REDACTED docker[56367]: a3ed95caeb02: Already exists
Nov 10 15:53:06 REDACTED docker[56367]: Digest: sha256:a236ac9e7131d101fbf29df072200a5eb7615d8286e48f035a4096bdf42741b2
Nov 10 15:53:06 REDACTED docker[56367]: Status: Image is up to date for grafana/grafana:master
Nov 10 15:53:06 REDACTED docker[56566]: t=2016-11-10T05:53:06+0000 lvl=info msg="Starting Grafana" logger=main version=4.0.0-beta1 commit=6a81389 compiled=2016-11-09T13:48:51+0000
Nov 10 15:53:06 REDACTED docker[56566]: t=2016-11-10T05:53:06+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
Nov 10 15:53:06 REDACTED docker[56566]: t=2016-11-10T05:53:06+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
Nov 10 15:53:06 REDACTED docker[56566]: t=2016-11-10T05:53:06+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.data=/data"
Nov 10 15:53:06 REDACTED docker[56566]: t=2016-11-10T05:53:06+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
Nov 10 15:53:06 REDACTED docker[56566]: t=2016-11-10T05:53:06+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
Nov 10 15:53:06 REDACTED docker[56566]: t=2016-11-10T05:53:06+0000 lvl=info msg="Config overriden from Environment variable" logger=settings var="GF_PATHS_DATA=/data"
Nov 10 15:53:06 REDACTED docker[56566]: t=2016-11-10T05:53:06+0000 lvl=info msg="Config overriden from Environment variable" logger=settings var="GF_SECURITY_ADMIN_PASSWORD=REDACTED"
Nov 10 15:53:06 REDACTED docker[56566]: t=2016-11-10T05:53:06+0000 lvl=info msg="Config overriden from Environment variable" logger=settings var="GF_AUTH_ANONYMOUS_ENABLED=true"
Nov 10 15:53:06 REDACTED docker[56566]: t=2016-11-10T05:53:06+0000 lvl=info msg="Config overriden from Environment variable" logger=settings var="GF_AUTH_ANONYMOUS_ORG_NAME=REDACTED"
Nov 10 15:53:06 REDACTED docker[56566]: t=2016-11-10T05:53:06+0000 lvl=info msg="Config overriden from Environment variable" logger=settings var="GF_AUTH_ANONYMOUS_ORG_ROLE=Editor"
Nov 10 15:53:06 REDACTED docker[56566]: t=2016-11-10T05:53:06+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
Nov 10 15:53:06 REDACTED docker[56566]: t=2016-11-10T05:53:06+0000 lvl=info msg="Path Data" logger=settings path=/data
Nov 10 15:53:06 REDACTED docker[56566]: t=2016-11-10T05:53:06+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
Nov 10 15:53:06 REDACTED docker[56566]: t=2016-11-10T05:53:06+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
Nov 10 15:53:06 REDACTED docker[56566]: t=2016-11-10T05:53:06+0000 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3
Nov 10 15:53:06 REDACTED docker[56566]: t=2016-11-10T05:53:06+0000 lvl=info msg="Starting DB migration" logger=migrator
Nov 10 15:53:06 REDACTED docker[56566]: t=2016-11-10T05:53:06+0000 lvl=info msg="Starting plugin search" logger=plugins
Nov 10 15:53:06 REDACTED docker[56566]: t=2016-11-10T05:53:06+0000 lvl=info msg="Initializing Alerting" logger=alerting.engine
Nov 10 15:53:06 REDACTED docker[56566]: t=2016-11-10T05:53:06+0000 lvl=info msg="Initializing CleanUpService" logger=cleanup
Nov 10 15:53:06 REDACTED docker[56566]: t=2016-11-10T05:53:06+0000 lvl=info msg="Initializing HTTP Server" logger=server address=0.0.0.0:3000 protocol=http subUrl=
Nov 10 16:01:18 REDACTED docker[56566]: panic: runtime error: invalid memory address or nil pointer dereference
Nov 10 16:01:18 REDACTED docker[56566]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x506456]
Nov 10 16:01:18 REDACTED docker[56566]: goroutine 499 [running]:
Nov 10 16:01:18 REDACTED docker[56566]: panic(0xd21720, 0xc420016050)
Nov 10 16:01:18 REDACTED docker[56566]: /usr/local/go/src/runtime/panic.go:500 +0x1a1
Nov 10 16:01:18 REDACTED docker[56566]: github.com/grafana/grafana/pkg/tsdb/influxdb.(*InfluxdbQueryParser).Parse(0x16f2e70, 0xc4200d3b70, 0xc4204d7cc0, 0x20, 0xd85ba0, 0xda4701)
Nov 10 16:01:18 REDACTED docker[56566]: /go/src/github.com/grafana/grafana/pkg/tsdb/influxdb/model_parser.go:40 +0x526
Nov 10 16:01:18 REDACTED docker[56566]: github.com/grafana/grafana/pkg/tsdb/influxdb.(*InfluxDBExecutor).getQuery(0xc420619080, 0xc42033ca08, 0x1, 0x1, 0xc4208292c0, 0x7f1509bc44b0, 0x0, 0x2, 0x41708c)
Nov 10 16:01:18 REDACTED docker[56566]: /go/src/github.com/grafana/grafana/pkg/tsdb/influxdb/influxdb.go:91 +0x5a
Nov 10 16:01:18 REDACTED docker[56566]: github.com/grafana/grafana/pkg/tsdb/influxdb.(*InfluxDBExecutor).Execute(0xc420619080, 0x1539e20, 0xc420016300, 0xc42033ca08, 0x1, 0x1, 0xc4208292c0, 0x0)
Nov 10 16:01:18 REDACTED docker[56566]: /go/src/github.com/grafana/grafana/pkg/tsdb/influxdb/influxdb.go:49 +0xc5
Nov 10 16:01:18 REDACTED docker[56566]: github.com/grafana/grafana/pkg/tsdb.(*Batch).process(0xc4208fc9c0, 0x1539e20, 0xc420016300, 0xc4208292c0)
Nov 10 16:01:18 REDACTED docker[56566]: /go/src/github.com/grafana/grafana/pkg/tsdb/batch.go:42 +0x408
Nov 10 16:01:18 REDACTED docker[56566]: created by github.com/grafana/grafana/pkg/tsdb.HandleRequest
Nov 10 16:01:18 REDACTED docker[56566]: /go/src/github.com/grafana/grafana/pkg/tsdb/request.go:21 +0x243
```

**Comment by bergquist** [comment]
Thank you for reporting this! This should be fixed in master and will be available for download shortly at http://grafana.org/builds or grafana:latest container.

**Comment by berglh** [comment]
Thanks @bergquist, appreciate the fast response, looking forward to experimenting further.

**Comment by berglh** [comment]
@bergquist - this issue is no longer present in the current master container build :+1:
