### ISSUE TITLE
Github issue metrics collection workflow failing on forks

### ISSUE THREAD

**Issue by kousikmitra** [grafana/grafana#66206]
**What happened**:

The `Github issue metrics collection` workflow is scheduled to run at `*/10 * * * *` interval. The workflow is continuously failing for below reason.

```
Run ./actions/metrics-collector
/home/runner/work/grafana/grafana/actions/node_modules/@actions/core/lib/core.js:106
        throw new Error(`Input required and not supplied: ${name}`);
        ^

Error: Input required and not supplied: token
    at Object.getInput (/home/runner/work/grafana/grafana/actions/node_modules/@actions/core/lib/core.js:106:15)
    at getRequiredInput (/home/runner/work/grafana/grafana/actions/common/utils.js:[4](https://github.com/kousikmitra/grafana/actions/runs/4654256904/jobs/8235833351#step:4:5)0:41)
    at new ActionBase (/home/runner/work/grafana/grafana/actions/common/Action.js:16:[5](https://github.com/kousikmitra/grafana/actions/runs/4654256904/jobs/8235833351#step:4:6)1)
    at new Action (/home/runner/work/grafana/grafana/actions/common/Action.js:103:9)
    at new MetricsCollector (/home/runner/work/grafana/grafana/actions/metrics-collector/index.js:8:9)
    at Object.<anonymous> (/home/runner/work/grafana/grafana/actions/metrics-collector/index.js:5[6](https://github.com/kousikmitra/grafana/actions/runs/4654256904/jobs/8235833351#step:4:7):1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:9[8](https://github.com/kousikmitra/grafana/actions/runs/4654256904/jobs/8235833351#step:4:9)1:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:[12](https://github.com/kousikmitra/grafana/actions/runs/4654256904/jobs/8235833351#step:4:13))
```

**What you expected to happen**:
Not sure what is the expected behaviour here, but I think it should not run on forked repos.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by khushijain21** [comment]
I have the same issue

**Comment by tonypowa** [comment]
hi @kousikmitra 
thank you for creating this issue

what endpoint are you calling?
also, please could you share the docs you followed?

**Comment by kousikmitra** [comment]
This is not about grafana but the github workflow `metrics-collector`

https://github.com/grafana/grafana/blob/5df33c0dc1a673e1a9ed6128b7cf4b4649371e5f/.github/workflows/metrics-collector.yml

The workflow started failing on my fork for the before mentioned reason which is valid. Am not sure why the workflow is running on my forked repo.

**Comment by tonypowa** [comment]
thank you for holding on @kousikmitra 

there is no expectation that github actions will work on forked repos 

in any case, this wouldn't be something we have the resources to investigate at the moment
