### ISSUE TITLE
[Bug] Singlestat throws error with sparklines and empty height

### ISSUE THREAD

**Issue by milesich** [grafana/grafana#6785]
- What Grafana version are you using?
v4.0.0-1480439068
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
CentOS Linux release 7.2.1511 (Core)

When you enable sparklines on a singlestat panel that has no height set it will not load and show this error:

`Invalid dimensions for plot, width = 115, height = 0`

```
Error: Invalid dimensions for plot, width = 115, height = 0
    at b.resize (https://.../grafana/public/app/boot.fdf40765.js:20:1803)
    at new b (https://.../grafana/public/app/boot.fdf40765.js:19:3267)
    at t (https://.../grafana/public/app/boot.fdf40765.js:19:10096)
    at new c (https://.../grafana/public/app/boot.fdf40765.js:20:1512)
    at Function.a.plot (https://.../grafana/public/app/boot.fdf40765.js:20:4447)
    at n (https://.../grafana/public/app/boot.fdf40765.js:20:21367)
    at o (https://.../grafana/public/app/boot.fdf40765.js:20:21809)
    at e.<anonymous> (https://.../grafana/public/app/boot.fdf40765.js:20:22638)
    at e.emit (https://.../grafana/public/app/boot.fdf40765.js:48:17770)
    at a.emit (https://.../grafana/public/app/boot.fdf40765.js:48:19428)

```

**Comment by torkelo** [comment]
could you describe what you did to get this? added a singlestat panel and set height to 0? or what do you mean empty? if the panel height is empty it will use the row height

**Comment by milesich** [comment]
Empty height as I left the field empty.
![screen shot 2016-12-01 at 21 18 44](https://cloud.githubusercontent.com/assets/1993963/20811112/b6b7fefe-b80c-11e6-943a-3441bc192d57.png)

Found the issue. The row height was set to 25px. When I changed it to 50px there were no more errors.
