### ISSUE TITLE
[Feature request] Mattermost notification

### ISSUE THREAD

**Issue by towolf** [grafana/grafana#6818]
Mattermost theoretically is compatible with Slack webhooks. Tried it out and got this traceback:

```
platform[14605]: 2016/12/04 16:18:31 interface conversion: interface is float64, not string
platform[14605]: goroutine 1621 [running]:
platform[14605]: runtime/debug.Stack(0x85ef5c, 0xc4200780f0, 0x2)
platform[14605]:         /usr/local/go/src/runtime/debug/stack.go:24 +0x79
platform[14605]: runtime/debug.PrintStack()
platform[14605]:         /usr/local/go/src/runtime/debug/stack.go:16 +0x22
platform[14605]: github.com/mattermost/platform/vendor/github.com/gorilla/handlers.recoveryHandler.log(0x104d700, 0xc420f861c0, 0x0, 0xc4208cc101, 0xbf1b00, 0xc422243580)
platform[14605]:         /var/lib/jenkins/jobs/msr/jobs/enterprise-release/workspace/src/github.com/mattermost/platform/vendor/github.com/gorilla/handlers/recovery.go:84 +0x9b
platform[14605]: github.com/mattermost/platform/vendor/github.com/gorilla/handlers.recoveryHandler.ServeHTTP.func1(0x1055380, 0xc420bc21a0, 0x104d700, 0xc420f861c0, 0x0, 0x96b001)
platform[14605]:         /var/lib/jenkins/jobs/msr/jobs/enterprise-release/workspace/src/github.com/mattermost/platform/vendor/github.com/gorilla/handlers/recovery.go:69 +0xae
platform[14605]: panic(0xbf1b00, 0xc422243580)
platform[14605]:         /usr/local/go/src/runtime/panic.go:458 +0x243
platform[14605]: github.com/mattermost/platform/model.expandAnnouncements(0xc422a34150)
platform[14605]:         /var/lib/jenkins/jobs/msr/jobs/enterprise-release/workspace/src/github.com/mattermost/platform/model/incoming_webhook.go:236 +0x3f0
platform[14605]: github.com/mattermost/platform/model.IncomingWebhookRequestFromJson(0x7f81412e7458, 0xc422242dc0, 0xc4206c98c0)
platform[14605]:         /var/lib/jenkins/jobs/msr/jobs/enterprise-release/workspace/src/github.com/mattermost/platform/model/incoming_webhook.go:259 +0xe4
platform[14605]: github.com/mattermost/platform/api.incomingWebhook(0xc4204e8240, 0x1055380, 0xc420bc21a0, 0xc421d44000)
platform[14605]:         /var/lib/jenkins/jobs/msr/jobs/enterprise-release/workspace/src/github.com/mattermost/platform/api/webhook.go:380 +0x1ee
platform[14605]: github.com/mattermost/platform/api.handler.ServeHTTP(0xd39738, 0x10000, 0x1055380, 0xc420bc21a0, 0xc421d44000)
platform[14605]:         /var/lib/jenkins/jobs/msr/jobs/enterprise-release/workspace/src/github.com/mattermost/platform/api/context.go:213 +0xa12
platform[14605]: github.com/mattermost/platform/api.(*handler).ServeHTTP(0xc420db8f20, 0x1055380, 0xc420bc21a0, 0xc421d44000)
platform[14605]:         <autogenerated>:1 +0x70
platform[14605]: github.com/mattermost/platform/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420dfb540, 0x1055380, 0xc420bc21a0, 0xc421d44000)
platform[14605]:         /var/lib/jenkins/jobs/msr/jobs/enterprise-release/workspace/src/github.com/mattermost/platform/vendor/github.com/gorilla/mux/mux.go:103 +0x255
platform[14605]: github.com/mattermost/platform/api.(*CorsWrapper).ServeHTTP(0xc420f861c0, 0x1055380, 0xc420bc21a0, 0xc421d44000)
platform[14605]:         /var/lib/jenkins/jobs/msr/jobs/enterprise-release/workspace/src/github.com/mattermost/platform/api/context.go:263 +0x164
platform[14605]: github.com/mattermost/platform/vendor/github.com/gorilla/handlers.recoveryHandler.ServeHTTP(0x104d700, 0xc420f861c0, 0x0, 0xaf0000c420d03e01, 0x1055380, 0xc420bc21a0, 0xc421d44000)
platform[14605]:         /var/lib/jenkins/jobs/msr/jobs/enterprise-release/workspace/src/github.com/mattermost/platform/vendor/github.com/gorilla/handlers/recovery.go:73 +0xae
platform[14605]: github.com/mattermost/platform/vendor/github.com/gorilla/handlers.(*recoveryHandler).ServeHTTP(0xc420d7b800, 0x1055380, 0xc420bc21a0, 0xc421d44000)
platform[14605]:         <autogenerated>:52 +0x8a
platform[14605]: net/http.serverHandler.ServeHTTP(0xc420bbcf00, 0x1055380, 0xc420bc21a0, 0xc421d44000)
platform[14605]:         /usr/local/go/src/net/http/server.go:2202 +0x7d
platform[14605]: net/http.(*conn).serve(0xc420df8300, 0x1055e40, 0xc422242d80)
platform[14605]:         /usr/local/go/src/net/http/server.go:1579 +0x4b7
platform[14605]: created by net/http.(*Server).Serve
platform[14605]:         /usr/local/go/src/net/http/server.go:2293 +0x44d
```

I *know* this would be a Mattermost bug. But OTOH Mattermost allows *richer* alerts due to Markdown support, so this is asking for special tailored Mattermost alerting.

**Comment by towolf** [comment]
The Mattermost bug is https://github.com/mattermost/platform/issues/4444, and it was already fixed. 

But the fact remains, that a slightly modified Slack notification can provide an enriched experience in Mattermost.

**Comment by towolf** [comment]
![image](https://cloud.githubusercontent.com/assets/345210/20868418/8de7b874-ba5b-11e6-9e3a-117d8a233660.png)

Here's an example, where actual markdown is used: for a table, and for a larger embedded image.

Here's the code:

```json
{
  "attachments": [
    {
      "color": "#D63232",
      "image_url": "",
      "text": " ![](https://grafana-img.example.net/pubsub.png)\n
\n
| channels | patterns |\n
|---------:|---------:|\n
|      8.6 |      0.0 |\n",
      "title": "[Alerting] Redis pubsub alert",
      "title_link": "https://grafana.example.net/dashboard/db/overview?fullscreen&edit&tab=alert&panelId=54"
    }
  ],
  "parse": "full"
}
```

It’s basically the same as Slack with more formatting possibilities.

**Comment by PsychoSid** [comment]
Hi,

For the record with MMv3.5.1 and Grafana 4.0 the Slack alerting kind of worked - it only sent OK's - Alerts produced a 500 in MM.

@towolf +1 for the markdown suggestion

Cheers
Paul

**Comment by jensbaitingerbosch** [comment]
The bug mattermost/platform#4444 is fixed, but its not in the MM 3.5.1 release.

**Comment by bergquist** [comment]
At this point, we won't be adding more alert notifiers to Grafana Core. We are working on supporting backend plugins so people can add any notifiers they need without us having to learn all the contracts. 

https://github.com/grafana/grafana/issues/6841

I'm closing this issue to avoid confusion about mattermost getting into core.

**Comment by towolf** [comment]
That's ok, the slack plug-in mostly works for mattermost also.

**Comment by madsystem** [comment]
Slack plugin works for me as well. Just dont put in any other info than the incoming webhook url.
