### ISSUE TITLE
AlertNG init 30 Second,but org over 5000，Causing Grafana to fail to start

### ISSUE THREAD

**Issue by w2009211777** [grafana/grafana#69080]
### 
# What went wrong?

**What happened**:

  - ngalert.go initCtx, cancelFunc := context.WithTimeout(context.Background(), 30*time.Second)
  - bug org over 5000,so Initialization time exceeds 30 seconds，error info is :
  - `logger=infra.kvstore.sql t=2023-05-25T13:52:04.294781402Z level=debug msg="kvstore value not found" orgId=27163 namespace=alertmanager key=silences
logger=alertmanager org=27461 t=2023-05-25T13:52:04.295114265Z level=debug msg="notification log snapshot file doesn't exist" err="open /var/lib/grafana/alerting/27163/notifications: no such file or directory"
logger=ngalert.multiorg.alertmanager t=2023-05-25T13:52:04.322007724Z level=error msg="failed to apply Alertmanager config for org" org=27163 id=1814 error="unable to apply configuration: context deadline exceeded"
logger=infra.kvstore.sql t=2023-05-25T13:52:04.322196466Z level=debug msg="error getting kvstore value" orgId=20541 namespace=alertmanager key=notifications err="context deadline exceeded"`

**What did you expect to happen**:

  - 

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana and do X 

**Step 2**:

- Now click button Y

**Step 3**:

- Wait for the browser to crash. Error message says: "Error..."

### 
# What Grafana version are you using?

9.4.3

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Kubernetes

### Is this a Regression?

None

**Comment by w2009211777** [comment]
The following information is relatively complete：
`logger=infra.kvstore.sql t=2023-05-25T11:19:30.997574564Z level=debug msg="kvstore value not found" orgId=20977 namespace=alertmanager key=notifications
logger=infra.kvstore.sql t=2023-05-25T11:19:31.005704834Z level=debug msg="kvstore value not found" orgId=20977 namespace=alertmanager key=silences
logger=alertmanager org=27461 t=2023-05-25T11:19:31.005977374Z level=debug msg="notification log snapshot file doesn't exist" err="open /var/lib/grafana/alerting/20977/notifications: no such file or directory"
logger=infra.kvstore.sql t=2023-05-25T11:19:31.030708037Z level=debug msg="kvstore value not found" orgId=28732 namespace=alertmanager key=notifications
logger=infra.kvstore.sql t=2023-05-25T11:19:31.038795683Z level=debug msg="kvstore value not found" orgId=28732 namespace=alertmanager key=silences
logger=alertmanager org=27461 t=2023-05-25T11:19:31.039070946Z level=debug msg="notification log snapshot file doesn't exist" err="open /var/lib/grafana/alerting/28732/notifications: no such file or directory"
logger=infra.kvstore.sql t=2023-05-25T11:19:31.064960051Z level=debug msg="kvstore value not found" orgId=28729 namespace=alertmanager key=notifications
logger=infra.kvstore.sql t=2023-05-25T11:19:31.073127707Z level=debug msg="kvstore value not found" orgId=28729 namespace=alertmanager key=silences
logger=alertmanager org=27461 t=2023-05-25T11:19:31.073418589Z level=debug msg="notification log snapshot file doesn't exist" err="open /var/lib/grafana/alerting/28729/notifications: no such file or directory"
logger=infra.kvstore.sql t=2023-05-25T11:19:31.09280216Z level=debug msg="kvstore value not found" orgId=28728 namespace=alertmanager key=notifications
logger=infra.kvstore.sql t=2023-05-25T11:19:31.094975843Z level=debug msg="error getting kvstore value" orgId=28728 namespace=alertmanager key=silences err="context deadline exceeded"
logger=ngalert.multiorg.alertmanager t=2023-05-25T11:19:31.095008252Z level=error msg="unable to create Alertmanager for org" org=28728 error="error reading file 'silences' from database: context deadline exceeded"
logger=cli t=2023-05-25T11:19:31.095333555Z level=error msg="Critical error" reason="runtime error: invalid memory address or nil pointer dereference" stackTrace="goroutine 1 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/grafana/grafana/pkg/cmd/grafana-server/commands.RunServer.func3()\n\t/drone/src/pkg/cmd/grafana-server/commands/cli.go:181 +0x9c\npanic({0x3d9ae00, 0x732bb70})\n\t/usr/local/go/src/runtime/panic.go:890 +0x263\ngithub.com/grafana/grafana/pkg/services/ngalert/notifier.(*Alertmanager).ApplyConfig(0x0, 0xc00252ee40?)\n\t/drone/src/pkg/services/ngalert/notifier/alertmanager.go:232 +0xf5\ngithub.com/grafana/grafana/pkg/services/ngalert/notifier.(*MultiOrgAlertmanager).SyncAlertmanagersForOrgs(0xc001894300, {0x4e597a8, 0xc0018c2840}, {0xc001980000, 0x1300, 0x4e5aea0?})\n\t/drone/src/pkg/services/ngalert/notifier/multiorg_alertmanager.go:208 +0x772\ngithub.com/grafana/grafana/pkg/services/ngalert/notifier.(*MultiOrgAlertmanager).LoadAndSyncAlertmanagersForOrgs(0xc001894300, {0x4e597a8, 0xc0018c2840})\n\t/drone/src/pkg/services/ngalert/notifier/multiorg_alertmanager.go:140 +0xd8\ngithub.com/grafana/grafana/pkg/services/ngalert.(*AlertNG).init(0xc00018d6c0)\n\t/drone/src/pkg/services/ngalert/ngalert.go:176 +0x466\ngithub.com/grafana/grafana/pkg/services/ngalert.ProvideService(_, {_, _}, {_, _}, {_, _}, {_, _}, {0x4e708c8, ...}, ...)\n\t/drone/src/pkg/services/ngalert/ngalert.go:101 +0x5a9\ngithub.com/grafana/grafana/pkg/server.Initialize({{0x7ffc2d745c5a, 0x18}, {0x7ffc2d745c3e, 0x12}, {0xc000ca1da0, 0x6, 0x6}}, {{0x0, 0x0}, {0x0, ...}, ...}, ...)\n\t/drone/src/pkg/server/wire_gen.go:431 +0x4a45\ngithub.com/grafana/grafana/pkg/cmd/grafana-server/commands.RunServer({{0x4e1138c, 0x5}, {0x4e12630, 0xa}, {0x4e11384, 0x4}, {0x4e12620, 0xa}, 0xc000c3ecc0})\n\t/drone/src/pkg/cmd/grafana-server/commands/cli.go:228 +0xfea\ngithub.com/grafana/grafana/pkg/cmd/grafana-server/commands.ServerCommand.func1(0xc00143fb00?)\n\t/drone/src/pkg/cmd/grafana-server/commands/cli.go:97 +0xc5\ngithub.com/urfave/cli/v2.(*Command).Run(0xc0014b4480, 0xc000c3e8c0)\n\t/opt/drone/gomodcache/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x5c8\ngithub.com/urfave/cli/v2.(*App).RunContext(0xc000993ba0, {0x4e59770?, 0xc000082018}, {0xc0000740a0, 0xa, 0xa})\n\t/opt/drone/gomodcache/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0xb36\ngithub.com/urfave/cli/v2.(*App).Run(...)\n\t/opt/drone/gomodcache/github.com/urfave/cli/v2@v2.3.0/app.go:224\nmain.main()\n\t/drone/src/pkg/cmd/grafana/main.go:39 +0x27d\n"
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2283ab5]

goroutine 1 [running]:
github.com/grafana/grafana/pkg/cmd/grafana-server/commands.RunServer.func3()
	/drone/src/pkg/cmd/grafana-server/commands/cli.go:182 +0x17e
panic({0x3d9ae00, 0x732bb70})
	/usr/local/go/src/runtime/panic.go:890 +0x263
github.com/grafana/grafana/pkg/services/ngalert/notifier.(*Alertmanager).ApplyConfig(0x0, 0xc00252ee40?)
	/drone/src/pkg/services/ngalert/notifier/alertmanager.go:232 +0xf5
github.com/grafana/grafana/pkg/services/ngalert/notifier.(*MultiOrgAlertmanager).SyncAlertmanagersForOrgs(0xc001894300, {0x4e597a8, 0xc0018c2840}, {0xc001980000, 0x1300, 0x4e5aea0?})
	/drone/src/pkg/services/ngalert/notifier/multiorg_alertmanager.go:208 +0x772
github.com/grafana/grafana/pkg/services/ngalert/notifier.(*MultiOrgAlertmanager).LoadAndSyncAlertmanagersForOrgs(0xc001894300, {0x4e597a8, 0xc0018c2840})
	/drone/src/pkg/services/ngalert/notifier/multiorg_alertmanager.go:140 +0xd8
github.com/grafana/grafana/pkg/services/ngalert.(*AlertNG).init(0xc00018d6c0)
	/drone/src/pkg/services/ngalert/ngalert.go:176 +0x466
github.com/grafana/grafana/pkg/services/ngalert.ProvideService(_, {_, _}, {_, _}, {_, _}, {_, _}, {0x4e708c8, ...}, ...)
	/drone/src/pkg/services/ngalert/ngalert.go:101 +0x5a9
github.com/grafana/grafana/pkg/server.Initialize({{0x7ffc2d745c5a, 0x18}, {0x7ffc2d745c3e, 0x12}, {0xc000ca1da0, 0x6, 0x6}}, {{0x0, 0x0}, {0x0, ...}, ...}, ...)
	/drone/src/pkg/server/wire_gen.go:431 +0x4a45
github.com/grafana/grafana/pkg/cmd/grafana-server/commands.RunServer({{0x4e1138c, 0x5}, {0x4e12630, 0xa}, {0x4e11384, 0x4}, {0x4e12620, 0xa}, 0xc000c3ecc0})
	/drone/src/pkg/cmd/grafana-server/commands/cli.go:228 +0xfea
github.com/grafana/grafana/pkg/cmd/grafana-server/commands.ServerCommand.func1(0xc00143fb00?)
	/drone/src/pkg/cmd/grafana-server/commands/cli.go:97 +0xc5
github.com/urfave/cli/v2.(*Command).Run(0xc0014b4480, 0xc000c3e8c0)
	/opt/drone/gomodcache/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x5c8
github.com/urfave/cli/v2.(*App).RunContext(0xc000993ba0, {0x4e59770?, 0xc000082018}, {0xc0000740a0, 0xa, 0xa})
	/opt/drone/gomodcache/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0xb36
github.com/urfave/cli/v2.(*App).Run(...)
	/opt/drone/gomodcache/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
	/drone/src/pkg/cmd/grafana/main.go:39 +0x27d`

**Comment by JohnnyQQQQ** [comment]
Can you please tell us what the exact steps are to reproduce? What do you mean by "but org over 5000", that it only happens if the org ID is over 5000?

**Comment by iXingo** [comment]
org > 120, same issue

**Comment by iXingo** [comment]
Hi @w2009211777 how did you fix the issue
