### ISSUE TITLE
Alerting: Test flake in pkg/services/ngalert/schedule

### ISSUE THREAD

**Issue by zerok** [grafana/grafana#69444]
Looks like there is a flaky test in pkg/services/ngalert/schedule ([example](https://drone.grafana.net/grafana/grafana/119442/3/7)).

```
ok  	github.com/grafana/grafana/pkg/services/ngalert/provisioning	1.012s	coverage: 69.4% of statements
panic: runtime error: index out of range [-1]

goroutine 293 [running]:
math/rand.(*rngSource).Uint64(...)
	/usr/local/go/src/math/rand/rng.go:249
math/rand.(*rngSource).Int63(0x0?)
	/usr/local/go/src/math/rand/rng.go:234 +0x92
math/rand.(*Rand).Int63(...)
	/usr/local/go/src/math/rand/rand.go:95
math/rand.(*Rand).Int31(...)
	/usr/local/go/src/math/rand/rand.go:109
math/rand.(*Rand).Int31n(0xc00026cae0, 0x6)
	/usr/local/go/src/math/rand/rand.go:144 +0x59
math/rand.(*Rand).Intn(0x924b6cc9cdb2b38c?, 0xc001517c8c?)
	/usr/local/go/src/math/rand/rand.go:182 +0x2e
github.com/grafana/grafana/pkg/util.GenerateShortUID()
	/drone/src/pkg/util/shortid_generator.go:42 +0xd5
github.com/grafana/grafana/pkg/services/ngalert/models.GenerateAlertLabels(0x3, {0x1a42617, 0x4})
	/drone/src/pkg/services/ngalert/models/testing.go:185 +0x73
github.com/grafana/grafana/pkg/services/ngalert/models.AlertRuleGen.func1()
	/drone/src/pkg/services/ngalert/models/testing.go:45 +0xe5
github.com/grafana/grafana/pkg/services/ngalert/schedule.TestSchedule_alertRuleInfo.func3.2()
	/drone/src/pkg/services/ngalert/schedule/registry_test.go:221 +0xc2
created by github.com/grafana/grafana/pkg/services/ngalert/schedule.TestSchedule_alertRuleInfo.func3
	/drone/src/pkg/services/ngalert/schedule/registry_test.go:209 +0x185
FAIL	github.com/grafana/grafana/pkg/services/ngalert/schedule	0.261s
```

Could you please take a look? Thanks 🙂

**Comment by JohnnyQQQQ** [comment]
This seems to be a problem with `github.com/grafana/grafana/pkg/util.GenerateShortUID()` and is not directly related to alerting.

**Comment by JohnnyQQQQ** [comment]
I could reproduce it, and a fix is on its way.
