### ISSUE TITLE
grafana-server: crash on fatal error: concurrent map write

### ISSUE THREAD

**Issue by buptpzw** [grafana/grafana#69636]
### 
# What went wrong?

Grafana restart frequently on kubernetes. full log:

2023-06-06T09:34:00.418073359Z fatal error: concurrent map writes
2023-06-06T09:34:00.418299352Z fatal error: concurrent map writes
2023-06-06T09:34:00.426018958Z 
2023-06-06T09:34:00.432490636Z goroutine 165825 [running]:
2023-06-06T09:34:00.432530947Z net/textproto.MIMEHeader.Del(...)
2023-06-06T09:34:00.432659652Z 	/usr/local/go/src/net/textproto/header.go:55
2023-06-06T09:34:00.432670227Z net/http.Header.Del(...)
2023-06-06T09:34:00.432678468Z 	/usr/local/go/src/net/http/header.go:81
2023-06-06T09:34:00.432843205Z github.com/grafana/grafana/pkg/util/proxyutil.ClearCookieHeader(0xc0064f5a00, {0x0, 0x0, 0xc003e20068?}, {0xc002f9ee80, 0x1, 0xa?})
2023-06-06T09:34:00.432861737Z 	/drone/src/pkg/util/proxyutil/proxyutil.go:45 +0x16a
2023-06-06T09:34:00.432872489Z github.com/grafana/grafana/pkg/services/query.(*Service).handleQuerySingleDatasource(0xc0010027e0, {0x3f3ed68, 0xc001efa0c0}, 0xc009a97b20, 0xc001d57220)
2023-06-06T09:34:00.432880557Z 	/drone/src/pkg/services/query/query.go:228 +0x9b3
2023-06-06T09:34:00.432890065Z github.com/grafana/grafana/pkg/services/query.(*Service).QueryData(0xc0010027e0, {0x3f3ed68, 0xc001efa0c0}, 0xc009a97b20, 0x0, {{0xc0036e93a0, 0xd}, {0xc0036e93b0, 0xd}, {0xc002868330, ...}, ...})
2023-06-06T09:34:00.432909129Z 	/drone/src/pkg/services/query/query.go:91 +0x35b
2023-06-06T09:34:00.432918425Z github.com/grafana/grafana/pkg/services/query.(*Service).QueryData.func1()
2023-06-06T09:34:00.432926505Z 	/drone/src/pkg/services/query/query.go:108 +0x125
2023-06-06T09:34:00.432934125Z golang.org/x/sync/errgroup.(*Group).Go.func1()
2023-06-06T09:34:00.432942275Z 	/opt/drone/gomodcache/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
2023-06-06T09:34:00.432950229Z created by golang.org/x/sync/errgroup.(*Group).Go
2023-06-06T09:34:00.432957989Z 	/opt/drone/gomodcache/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
2023-06-06T09:34:00.432965888Z 
2023-06-06T09:34:00.432971601Z goroutine 1 [semacquire, 3 minutes]:
2023-06-06T09:34:00.432978954Z sync.runtime_Semacquire(0x4?)
2023-06-06T09:34:00.432987318Z 	/usr/local/go/src/runtime/sema.go:62 +0x25
2023-06-06T09:34:00.432995401Z sync.(*WaitGroup).Wait(0xc001a77170?)
2023-06-06T09:34:00.433002884Z 	/usr/local/go/src/sync/waitgroup.go:139 +0x52
2023-06-06T09:34:00.433009447Z golang.org/x/sync/errgroup.(*Group).Wait(0xc001a73e80)
2023-06-06T09:34:00.433017661Z 	/opt/drone/gomodcache/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:53 +0x27
2023-06-06T09:34:00.433074615Z github.com/grafana/grafana/pkg/server.(*Server).Run(0xc001c6ac00)
2023-06-06T09:34:00.433083964Z 	/drone/src/pkg/server/server.go:181 +0x138
2023-06-06T09:34:00.433092389Z github.com/grafana/grafana/pkg/cmd/grafana-server/commands.executeServer({0x7ffdaeb90134, 0x18}, {0x7ffdaeb90118, 0x12}, {0x0, 0x0}, {0x7ffdaeb90159, 0x6}, 0xc00007c580?, {{0x3f05944, ...}, ...})

### 
# How do we reproduce it?

I don't know the specific steps to reproduce, but it happens frequently

### 
# What Grafana version are you using?

v9.3.6

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Kubernetes

### User's OS?

Alpine Linux v3.15

### Is this a Regression?

None

**Comment by tonypowa** [comment]
hi @buptpzw 

thank you for creating this issue

in addition to the logs you provided, could you increase [the verbosity of the Grafana server logs](https://grafana.com/docs/grafana/latest/administration/configuration/#level) to debug and note any errors? 

More info on troubleshooting Grafana issues here https://grafana.com/docs/grafana/v9.0/troubleshooting/

**Comment by tonypowa** [comment]
also could you please try to update to the latest version available of Grafana and see if that helps?

**Comment by buptpzw** [comment]
hi @tonypowa 

thank you for reply.

I opened the debug log. See full log below:
<img width="1383" alt="截屏2023-06-08 下午5 06 59" src="https://github.com/grafana/grafana/assets/18019066/1aa2cdf1-ff35-44f6-9a7f-e5b79b9ff260">

**Comment by tonypowa** [comment]
Thank you for the logs @buptpzw 

Here is a similar issue. If you believe it is related, I'd advise to add a comment in there and monitor progress from there.
https://github.com/grafana/grafana/issues/44509

Closing this one. Please reopen if the above does not apply in your case.
