### ISSUE TITLE
Transform: "Group by" fails entire panel for missing values in subset of series

### ISSUE THREAD

**Issue by Strandfelt** [grafana/grafana#70902]
### 
# What went wrong?

**What happened**:

  - Following upgrade from Grafana docker image version 9.4.12 to 10.0.1, transform "group by" crashes the panel if there are empty series

**What did you expect to happen**:
  - That the dashboard transformations that worked in the previous version, also work in the new version

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana, create a dashboard with a time series panel
- Add a query that returns a time series with missing values
- Add a query that returns a time series with values

**Step 2**:
- On the dashboard, create a transform "Group by" 
- For field "Time" select "Group by"
- For a the series, select "Calculate" and select "Total" in the Stats-field

**Step 3**:
- The panel stops rendering. The browser console contains the error message: 
```
reportUnhandledError.js:10 
 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at P (processDataFrame.ts:263:36)
    at m (groupBy.ts:183:14)
    at groupBy.ts:143:39
    at map.js:7:37
    at E._next (OperatorSubscriber.js:15:21)
    at M.next (Subscriber.js:34:18)
    at b._subscribe (innerFrom.js:51:24)
    at b._trySubscribe (Observable.js:38:25)
    at Observable.js:32:31
    at u (errorContext.js:19:9)
```

### 
# What Grafana version are you using?

v10.0.1

### 
### Is the bug inside a Dashboard Panel?

| Key | Value |
|--|--|
| Panel | timeseries @ 9.3.6 |
| Grafana | 10.0.1 (5a30620b85) // Open Source |
<details><summary>Panel debug snapshot dashboard</summary>

```json
{
  "panels": [
    {
      "datasource": {
        "type": "grafana",
        "uid": "grafana"
      },
      "fieldConfig": {
        "defaults": {
          "custom": {
            "drawStyle": "line",
            "lineInterpolation": "linear",
            "barAlignment": 0,
            "lineWidth": 1,
            "fillOpacity": 10,
            "gradientMode": "opacity",
            "spanNulls": false,
            "showPoints": "auto",
            "pointSize": 5,
            "stacking": {
              "mode": "none",
              "group": "A"
            },
            "axisPlacement": "auto",
            "axisLabel": "",
            "axisColorMode": "text",
            "scaleDistribution": {
              "type": "linear"
            },
            "axisCenteredZero": true,
            "hideFrom": {
              "tooltip": false,
              "viz": false,
              "legend": false
            },
            "thresholdsStyle": {
              "mode": "off"
            },
            "lineStyle": {
              "fill": "solid"
            }
          },
          "color": {
            "mode": "palette-classic"
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          },
          "unit": "locale"
        },
        "overrides": []
      },
      "gridPos": {
        "h": 13,
        "w": 15,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "tooltip": {
          "mode": "multi",
          "sort": "none"
        },
        "legend": {
          "showLegend": true,
          "displayMode": "list",
          "placement": "bottom",
          "calcs": []
        }
      },
      "pluginVersion": "9.3.6",
      "targets": [
        {
          "refId": "A",
          "datasource": {
            "type": "grafana",
            "uid": "grafana"
          },
          "queryType": "snapshot",
          "snapshot": [
            {
              "schema": {
                "name": "Series0",
                "fields": [
                  {
                    "name": "Time",
                    "type": "time",
                    "config": {}
                  },
                  {
                    "name": "Value",
                    "type": "number",
                    "config": {}
                  }
                ]
              },
              "data": {
                "values": [
                  [],
                  []
                ]
              }
            },
            {
              "schema": {
                "name": "Series1",
                "fields": [
                  {
                    "name": "Time",
                    "type": "time",
                    "config": {}
                  },
                  {
                    "name": "Value",
                    "type": "number",
                    "config": {}
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    1688040000000,
                    1688040900000,
                    1688041800000,
                    1688042700000,
                  ],
                  [
                    1,
                    2,
                    3,
                    4,
                  ]
                ]
              }
            },
            {
              "schema": {
                "name": "Series2",
                "fields": [
                  {
                    "name": "Time",
                    "type": "time",
                    "config": {}
                  },
                  {
                    "name": "Value",
                    "type": "number",
                    "config": {}
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    1688040000000,
                    1688040900000,
                    1688041800000,
                    1688042700000,
                  ],
                  [
                    5,
                    6,
                    7,
                    8,
                  ]
                ]
              }
            }
          ]
        }
      ],
      "transformations": [
        {
          "id": "groupBy",
          "options": {
            "fields": {
              "Time": {
                "aggregations": [],
                "operation": "groupby"
              },
              "Series0": {
                "aggregations": [
                  "sum"
                ],
                "operation": "aggregate"
              },
              "Series1": {
                "aggregations": [
                  "sum"
                ],
                "operation": "aggregate"
              },
              "Series2": {
                "aggregations": [
                  "sum"
                ],
                "operation": "aggregate"
              }
            }
          }
        }
      ],
      "type": "timeseries",
      "description": "",
      "title": "Reproduced with embedded data"
    },
    {
      "gridPos": {
        "h": 7,
        "w": 9,
        "x": 15,
        "y": 0
      },
      "id": 5,
      "options": {
        "content": "<table width=\"100%\">\n    <tr>\n      <th width=\"2%\">Panel</th>\n      <td >timeseries @ 9.3.6</td>\n    </tr>\n    <tr>\n      <th>Queries</th>\n      <td>A[grafana-simple-json-datasource], B[grafana-simple-json-datasource], C[grafana-simple-json-datasource]</td>\n    </tr>\n    <tr>\n      <th>Transform</th>\n      <td>renameByRegex, groupBy</td>\n  </tr>\n    <tr><th>Data</th><td> 12 frames, 24 fields, 3420 rows </td></tr>\n    \n    <tr>\n      <th>Grafana</th>\n      <td>10.0.1 (5a30620b85) // Open Source</td>\n    </tr>\n  </table>",
        "mode": "html"
      },
      "title": "Debug info",
      "type": "text"
    },
    {
      "id": 3,
      "title": "Data from panel above (after transformations)",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 15,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": true,
          "refId": "A"
        }
      ]
    },
    {
      "id": 100,
      "title": "Data (before transformations)",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 24,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": false,
          "refId": "A"
        }
      ]
    }
  ],
  "schemaVersion": 37,
  "title": "Debug: undefined // 2023-06-29 15:21:18",
  "tags": [
    "debug",
    "debug-timeseries"
  ],
  "time": {
    "from": "2023-06-28T22:00:00.000Z",
    "to": "2023-06-29T21:59:59.999Z"
  }
}
```
</details>

### Grafana Platform?

Docker

### User's OS?

Windows 11

### User's Browser?

Chrome Version 114.0.5735.199 (Official Build) (64-bit), Microsoft Edge Version 114.0.1823.58 (Official build) (64-bit)

### Is this a Regression?

Yes

### Are Datasources involved?

SimpleJson 1.4.2

**Comment by tonypowa** [comment]
hi @Strandfelt 

thank you for creating this issue

the dashboard JSON cannot get imported, could you please copy it again? thank you

**Comment by Strandfelt** [comment]
@tonypowa I had to redact some values. I simplified the data. Maybe this is better?
| Key | Value |
|--|--|
| Panel | timeseries @ 10.0.1 |
| Grafana | 10.0.1 (5a30620b85) // Open Source |
<details><summary>Panel debug snapshot dashboard</summary>

```json
{
  "panels": [
    {
      "datasource": {
        "type": "grafana",
        "uid": "grafana"
      },
      "fieldConfig": {
        "defaults": {
          "custom": {
            "drawStyle": "line",
            "lineInterpolation": "linear",
            "barAlignment": 0,
            "lineWidth": 1,
            "fillOpacity": 0,
            "gradientMode": "none",
            "spanNulls": false,
            "showPoints": "auto",
            "pointSize": 5,
            "stacking": {
              "mode": "none",
              "group": "A"
            },
            "axisPlacement": "auto",
            "axisLabel": "",
            "axisColorMode": "text",
            "scaleDistribution": {
              "type": "linear"
            },
            "axisCenteredZero": false,
            "hideFrom": {
              "tooltip": false,
              "viz": false,
              "legend": false
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "color": {
            "mode": "palette-classic"
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 13,
        "w": 15,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "tooltip": {
          "mode": "single",
          "sort": "none"
        },
        "legend": {
          "showLegend": true,
          "displayMode": "list",
          "placement": "bottom",
          "calcs": []
        }
      },
      "pluginVersion": "10.0.1",
      "targets": [
        {
          "refId": "A",
          "datasource": {
            "type": "grafana",
            "uid": "grafana"
          },
          "queryType": "snapshot",
          "snapshot": [
            {
              "schema": {
                "name": "Series1",
                "fields": [
                  {
                    "name": "Time",
                    "type": "time",
                    "config": {}
                  },
                  {
                    "name": "Value",
                    "type": "number",
                    "config": {}
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    1688470200000,
                    1688471100000,
                    1688470200000,
                    1688471100000
                  ],
                  [
                    1,
                    2,
                    3,
                    4
                  ]
                ]
              }
            },
            {
              "schema": {
                "name": "Series2",
                "fields": [
                  {
                    "name": "Time",
                    "type": "time",
                    "config": {}
                  },
                  {
                    "name": "Value",
                    "type": "number",
                    "config": {}
                  }
                ]
              },
              "data": {
                "values": [
                  [],
                  []
                ]
              }
            }
          ]
        }
      ],
      "title": "Reproduced with embedded data",
      "transformations": [
        {
          "id": "groupBy",
          "options": {
            "fields": {
              "Series1": {
                "aggregations": [
                  "sum"
                ],
                "operation": "aggregate"
              },
              "Series2": {
                "aggregations": [
                  "sum"
                ],
                "operation": "aggregate"
              },
              "Time": {
                "aggregations": [],
                "operation": "groupby"
              },
              "Value": {
                "aggregations": [
                  "sum"
                ],
                "operation": "aggregate"
              }
            }
          }
        }
      ],
      "type": "timeseries"
    },
    {
      "gridPos": {
        "h": 7,
        "w": 9,
        "x": 15,
        "y": 0
      },
      "id": 5,
      "options": {
        "content": "<table width=\"100%\">\n    <tr>\n      <th width=\"2%\">Panel</th>\n      <td >timeseries @ 10.0.1</td>\n    </tr>\n    <tr>\n      <th>Queries</th>\n      <td>A[grafana-simple-json-datasource], B[grafana-simple-json-datasource]</td>\n    </tr>\n    <tr>\n      <th>Transform</th>\n      <td>groupBy</td>\n  </tr>\n    <tr><th>Data</th><td> 2 frames, 4 fields, 4 rows </td></tr>\n    \n    <tr>\n      <th>Grafana</th>\n      <td>10.0.1 (5a30620b85) // Open Source</td>\n    </tr>\n  </table>",
        "mode": "html"
      },
      "title": "Debug info",
      "type": "text"
    },
    {
      "id": 6,
      "title": "Original Panel JSON",
      "type": "text",
      "gridPos": {
        "h": 13,
        "w": 9,
        "x": 15,
        "y": 7
      },
      "options": {
        "content": "{\n  \"datasource\": {\n    \"type\": \"grafana-simple-json-datasource\",\n    \"uid\": \"Y-vk8wkVk\"\n  },\n  \"fieldConfig\": {\n    \"defaults\": {\n      \"custom\": {\n        \"drawStyle\": \"line\",\n        \"lineInterpolation\": \"linear\",\n        \"barAlignment\": 0,\n        \"lineWidth\": 1,\n        \"fillOpacity\": 0,\n        \"gradientMode\": \"none\",\n        \"spanNulls\": false,\n        \"showPoints\": \"auto\",\n        \"pointSize\": 5,\n        \"stacking\": {\n          \"mode\": \"none\",\n          \"group\": \"A\"\n        },\n        \"axisPlacement\": \"auto\",\n        \"axisLabel\": \"\",\n        \"axisColorMode\": \"text\",\n        \"scaleDistribution\": {\n          \"type\": \"linear\"\n        },\n        \"axisCenteredZero\": false,\n        \"hideFrom\": {\n          \"tooltip\": false,\n          \"viz\": false,\n          \"legend\": false\n        },\n        \"thresholdsStyle\": {\n          \"mode\": \"off\"\n        }\n      },\n      \"color\": {\n        \"mode\": \"palette-classic\"\n      },\n      \"mappings\": [],\n      \"thresholds\": {\n        \"mode\": \"absolute\",\n        \"steps\": [\n          {\n            \"color\": \"green\",\n            \"value\": null\n          },\n          {\n            \"color\": \"red\",\n            \"value\": 80\n          }\n        ]\n      }\n    },\n    \"overrides\": []\n  },\n  \"gridPos\": {\n    \"h\": 9,\n    \"w\": 24,\n    \"x\": 0,\n    \"y\": 0\n  },\n  \"id\": 1,\n  \"options\": {\n    \"tooltip\": {\n      \"mode\": \"single\",\n      \"sort\": \"none\"\n    },\n    \"legend\": {\n      \"showLegend\": true,\n      \"displayMode\": \"list\",\n      \"placement\": \"bottom\",\n      \"calcs\": []\n    }\n  },\n  \"pluginVersion\": \"10.0.1\",\n  \"targets\": [\n    {\n      \"datasource\": {\n        \"type\": \"grafana-simple-json-datasource\",\n        \"uid\": \"Y-vk8wkVk\"\n      },\n      \"refId\": \"A\",\n      \"target\": \"columns=FromUtc,PnLDKK/filter=Country='AT'#Series1\",\n      \"type\": \"timeserie\"\n    },\n    {\n      \"datasource\": {\n        \"type\": \"grafana-simple-json-datasource\",\n        \"uid\": \"Y-vk8wkVk\"\n      },\n      \"hide\": false,\n      \"refId\": \"B\",\n      \"target\": \"columns=FromUtc,PnLDKK/filter=Country='SE'#Series2\",\n      \"type\": \"timeserie\"\n    }\n  ],\n  \"title\": \"Panel Title\",\n  \"transformations\": [\n    {\n      \"id\": \"groupBy\",\n      \"options\": {\n        \"fields\": {\n          \"Series1\": {\n            \"aggregations\": [\n              \"sum\"\n            ],\n            \"operation\": \"aggregate\"\n          },\n          \"Series2\": {\n            \"aggregations\": [\n              \"sum\"\n            ],\n            \"operation\": \"aggregate\"\n          },\n          \"Time\": {\n            \"aggregations\": [],\n            \"operation\": \"groupby\"\n          },\n          \"Value\": {\n            \"aggregations\": [\n              \"sum\"\n            ],\n            \"operation\": \"aggregate\"\n          }\n        }\n      }\n    }\n  ],\n  \"type\": \"timeseries\"\n}",
        "mode": "code",
        "code": {
          "language": "json",
          "showLineNumbers": true,
          "showMiniMap": true
        }
      }
    },
    {
      "id": 3,
      "title": "Data from panel above (after transformations)",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 15,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": true,
          "refId": "A"
        }
      ]
    },
    {
      "id": 100,
      "title": "Data (before transformations)",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 24,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": false,
          "refId": "A"
        }
      ]
    }
  ],
  "schemaVersion": 37,
  "title": "Debug: Panel Title // 2023-07-04 14:24:23",
  "tags": [
    "debug",
    "debug-timeseries"
  ],
  "time": {
    "from": "2023-07-04T11:24:23.967Z",
    "to": "2023-07-04T12:24:23.967Z"
  }
}
```
</details>

**Comment by tonypowa** [comment]
thanks @Strandfelt  

I just sent the issue to the dashboard squad for further review

**Comment by Strandfelt** [comment]
Hi. This is still present in Grafana v10.1.0. Any updates?

**Comment by Strandfelt** [comment]
The stack trace source line references have changed a bit though:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at v (processDataFrame.ts:262:36)
    at m (groupBy.ts:183:14)
    at groupBy.ts:143:39
    at map.js:7:37
    at E._next (OperatorSubscriber.js:15:21)
    at K.next (Subscriber.js:34:18)
    at b._subscribe (innerFrom.js:51:24)
    at b._trySubscribe (Observable.js:38:25)
    at Observable.js:32:31
    at u (errorContext.js:19:9)
```
