### ISSUE TITLE
Pyroscope datasource: Crash when entering query

### ISSUE THREAD

**Issue by iainlane** [grafana/grafana#72187]
### What happened?

I am running a build from main (commit `b08271da32`). When I enter any query in the Pyroscope datasource I get a crash like this:

```
panic: interface conversion: interface {} is int64, not data.EnumItemIndex                                              
                                                                                                                        
goroutine 38019 [running]:                                                                                              
github.com/grafana/grafana-plugin-sdk-go/data.(*enumVector).Append(0x52e1340?, {0x4fbede0?, 0x9db76f8?})                
»·······/opt/drone/gomodcache/github.com/grafana/grafana-plugin-sdk-go@v0.171.0/data/field_type_enum.go:32 +0xb7        
github.com/grafana/grafana-plugin-sdk-go/data.(*Field).Append(...)                                                      
»·······/opt/drone/gomodcache/github.com/grafana/grafana-plugin-sdk-go@v0.171.0/data/field.go:160                       
github.com/grafana/grafana/pkg/tsdb/grafana-pyroscope-datasource.(*EnumField).Append(0xc008cc9d48, {0xc005bcbbc0, 0x5}) 
»·······/drone/src/pkg/tsdb/grafana-pyroscope-datasource/query.go:328 +0x82                                             
github.com/grafana/grafana/pkg/tsdb/grafana-pyroscope-datasource.treeToNestedSetDataFrame.func1(0xc003d2c7d0)           
»·······/drone/src/pkg/tsdb/grafana-pyroscope-datasource/query.go:305 +0xea                                             
github.com/grafana/grafana/pkg/tsdb/grafana-pyroscope-datasource.walkTree(0xc002c822d0, 0xc008cc9d60)                   
»·······/drone/src/pkg/tsdb/grafana-pyroscope-datasource/query.go:362 +0x6e                                             
github.com/grafana/grafana/pkg/tsdb/grafana-pyroscope-datasource.treeToNestedSetDataFrame(0xc002c822d0, {0x5e37f32, 0x2})
»·······/drone/src/pkg/tsdb/grafana-pyroscope-datasource/query.go:301 +0x3aa                                            
github.com/grafana/grafana/pkg/tsdb/grafana-pyroscope-datasource.responseToDataFrames(0xc003077d58)                     
»·······/drone/src/pkg/tsdb/grafana-pyroscope-datasource/query.go:126 +0x4d                                             
github.com/grafana/grafana/pkg/tsdb/grafana-pyroscope-datasource.(*PhlareDatasource).query.func2()                      
»·······/drone/src/pkg/tsdb/grafana-pyroscope-datasource/query.go:94 +0x2c7                                             
golang.org/x/sync/errgroup.(*Group).Go.func1()                                                                          
»·······/opt/drone/gomodcache/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x64                                    
created by golang.org/x/sync/errgroup.(*Group).Go                                                                       
»·······/opt/drone/gomodcache/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0xa5                                    
```

### What did you expect to happen?

Query works properly and results are returned

### Did this work before?

I've got another deployment alongside the CD one running `v10.0.2` and that one works fine

### How do we reproduce it?

1. Run main, have a Pyroscope datasource configured
2. Visit Explore and issue a query against the datasource, e.g. `{cluster="mycluster", job="myjob"}

### Environment (with versions)?

Grafana: b08271da32
OS: Linux
Browser: Chrome linux 114.0.5735.198 (Official Build) unknown (64-bit) 

### Grafana platform?

Kubernetes

### Datasource(s)?

pyroscope

**Comment by usmangt** [comment]
Hi @iainlane,

Thanks for opening this issue.

What is your Kubernetes version?

Also, anything in the grafana + pyroscope container logs which might be related to the above stack-trace?

**Comment by aocenas** [comment]
Fixed by https://github.com/grafana/grafana/pull/72188
