### ISSUE TITLE
[Bug] Cannot run Grafana on Bash for Windows 10 subsystem.

### ISSUE THREAD

**Issue by thinkingmedia** [grafana/grafana#7241]
Please include this information:

### What Grafana version are you using?
4.1.1-1484211277_amd64

### What datasource are you using?
not applicable

### What OS are you running grafana on?
Ubuntu 14.0.4 on Windows 10 subsystem.

### What did you do?
I've tried installing the deb package, and also using the APT repository. Grafana will not run after installation.

### What was the expected result?

Grafana should be runnable after installation.

### What happened instead?

After installation both the `grafana-server` and `grafana-cli` report the same segmentation fault error. The app never gets into configuring or any other start up code. Appears to die trying to load dependencies.

As far as I can tell. Go is throwing a segmentation fault when loading `inconshreveable/log15`, but I don't know why. It's not failing at a specific line number. It appears to fail during importing. Most of the line numbers shown in the stack trace are at the bottom of the files. 

Here is a trace of installing for the first time on Ubuntu for Windows 10.

```
➜  ~ sudo apt-get install -y adduser libfontconfig
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libfontconfig1' instead of 'libfontconfig'
adduser is already the newest version.
libfontconfig1 is already the newest version.
libfontconfig1 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
➜  ~ wget https://grafanarel.s3.amazonaws.com/builds/grafana_4.1.1-1484211277_amd64.deb
--2017-01-12 13:26:49--  https://grafanarel.s3.amazonaws.com/builds/grafana_4.1.1-1484211277_amd64.deb
Resolving grafanarel.s3.amazonaws.com (grafanarel.s3.amazonaws.com)... 52.216.0.216
Connecting to grafanarel.s3.amazonaws.com (grafanarel.s3.amazonaws.com)|52.216.0.216|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 45204028 (43M) [application/x-debian-package]
Saving to: ‘grafana_4.1.1-1484211277_amd64.deb’

100%[===========================================================================================================================================================================>] 45,204,028  5.35MB/s   in 8.4s

2017-01-12 13:26:58 (5.16 MB/s) - ‘grafana_4.1.1-1484211277_amd64.deb’ saved [45204028/45204028]

➜  ~ sudo dpkg -i grafana_4.1.1-1484211277_amd64.deb
Selecting previously unselected package grafana.
(Reading database ... 55072 files and directories currently installed.)
Preparing to unpack grafana_4.1.1-1484211277_amd64.deb ...
Unpacking grafana (4.1.1-1484211277) ...
Setting up grafana (4.1.1-1484211277) ...
Adding system user `grafana' (UID 107) ...
Adding new user `grafana' (UID 107) with group `grafana' ...
Not creating home directory `/usr/share/grafana'.
### NOT starting grafana-server by default on bootup, please execute
 sudo update-rc.d grafana-server defaults 95 10
### In order to start grafana-server, execute
 sudo service grafana-server start
Processing triggers for ureadahead (0.100.0-16) ...
➜  ~ sudo grafana-cli
unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x84c3e3]

goroutine 1 [running, locked to thread]:
runtime.throw(0xa1c504, 0x5)
        /usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc420123ce0 sp=0xc420123cc0
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:27 +0x288 fp=0xc420123d38 sp=0xc420123ce0
github.com/grafana/grafana/vendor/github.com/go-stack/stack.findSigpanic.func1(0x0, 0xc420123d78, 0x0)
        /go/src/github.com/grafana/grafana/vendor/github.com/go-stack/stack/stack.go:228 +0x53 fp=0xc420123d60 sp=0xc420123d38
github.com/grafana/grafana/vendor/github.com/go-stack/stack.findSigpanic(0xa2d9b9)
        /go/src/github.com/grafana/grafana/vendor/github.com/go-stack/stack/stack.go:229 +0x3d fp=0xc420123d90 sp=0xc420123d60
github.com/grafana/grafana/vendor/github.com/go-stack/stack.init()
        /go/src/github.com/grafana/grafana/vendor/github.com/go-stack/stack/stack.go:233 +0xa2 fp=0xc420123dc0 sp=0xc420123d90
github.com/grafana/grafana/vendor/github.com/inconshreveable/log15.init()
        /go/src/github.com/grafana/grafana/vendor/github.com/inconshreveable/log15/syslog.go:56 +0x80 fp=0xc420123e00 sp=0xc420123dc0
github.com/grafana/grafana/pkg/log.init()
        /go/src/github.com/grafana/grafana/pkg/log/syslog.go:105 +0x6c fp=0xc420123e40 sp=0xc420123e00
github.com/grafana/grafana/pkg/setting.init()
        /go/src/github.com/grafana/grafana/pkg/setting/setting_smtp.go:32 +0x65 fp=0xc420123e48 sp=0xc420123e40
github.com/grafana/grafana/pkg/components/securejsondata.init()
        /go/src/github.com/grafana/grafana/pkg/components/securejsondata/securejsondata.go:25 +0x2e fp=0xc420123e50 sp=0xc420123e48
github.com/grafana/grafana/pkg/models.init()
        /go/src/github.com/grafana/grafana/pkg/models/user.go:178 +0x62 fp=0xc420123ea0 sp=0xc420123e50
github.com/grafana/grafana/pkg/services/sqlstore.init()
        /go/src/github.com/grafana/grafana/pkg/services/sqlstore/user.go:402 +0x67 fp=0xc420123ee8 sp=0xc420123ea0
github.com/grafana/grafana/pkg/cmd/grafana-cli/commands.init()
        /go/src/github.com/grafana/grafana/pkg/cmd/grafana-cli/commands/upgrade_command.go:33 +0x62 fp=0xc420123f30 sp=0xc420123ee8
main.init()
        /go/src/github.com/grafana/grafana/pkg/cmd/grafana-cli/main.go:73 +0x42 fp=0xc420123f38 sp=0xc420123f30
runtime.main()
        /usr/local/go/src/runtime/proc.go:172 +0x1bf fp=0xc420123f90 sp=0xc420123f38
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420123f98 sp=0xc420123f90

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1
➜  ~
```

**Comment by torkelo** [comment]
looks like Windows 10 linux support is not 100%. 

Not sure what we can do here. We do have a windows builds available and have no reported issues on linux. And can't see what is causing the segmentation violation.
