### ISSUE TITLE
Alerting: Edit Contact Point mimir-alertmanager - Webhook with Basic Auth: fails with TypeError: Cannot read properties of undefined (reading 'credentials')

### ISSUE THREAD

**Issue by hoexter** [grafana/grafana#72972]
### What happened?

Trying to edit a Webhook Contact Point with HTTP basic auth for the mimir-alertmanager ends in an error:

```
An unexpected error happened
Details
TypeError: Cannot read properties of undefined (reading 'credentials')

    at pt (https://grafana.mycorp/public/build/NotificationsListPage.fb1c2bae6997bab62fc0.js:358:579)
    at ft (https://grafana.mycorp/public/build/NotificationsListPage.fb1c2bae6997bab62fc0.js:366:124)
    at ga (https://grafana.mycorp/public/build/NotificationsListPage.fb1c2bae6997bab62fc0.js:373:1463)
    at Ke (https://grafana.mycorp/public/build/5226.48dbd59a341e1b9072d3.js:206:23585)
    at Ke (https://grafana.mycorp/public/build/5226.48dbd59a341e1b9072d3.js:206:25781)
    at r (https://grafana.mycorp/public/build/2077.434d3383b7b57dc17e44.js:4684:701)
    at div
    at div
    at div
    at div
    at V (https://grafana.mycorp/public/build/5226.48dbd59a341e1b9072d3.js:140:13278)
    at o (https://grafana.mycorp/public/build/2077.434d3383b7b57dc17e44.js:518:3183)
    at div
    at x (https://grafana.mycorp/public/build/2077.434d3383b7b57dc17e44.js:4684:2948)
    at Ki (https://grafana.mycorp/public/build/5524.9aa52fdd2ea883bd4d8a.js:22:21654)
    at fe (https://grafana.mycorp/public/build/5524.9aa52fdd2ea883bd4d8a.js:1:249)
    at Za (https://grafana.mycorp/public/build/NotificationsListPage.fb1c2bae6997bab62fc0.js:388:9891)
    at f (https://grafana.mycorp/public/build/2077.434d3383b7b57dc17e44.js:1320:180)
    at u (https://grafana.mycorp/public/build/2077.434d3383b7b57dc17e44.js:1320:754)
    at WithErrorBoundary
    at Suspense
    at f (https://grafana.mycorp/public/build/2077.434d3383b7b57dc17e44.js:1320:180)
    at Km (https://grafana.mycorp/public/build/2077.434d3383b7b57dc17e44.js:9259:330)
    at Ke (https://grafana.mycorp/public/build/5226.48dbd59a341e1b9072d3.js:206:23585)
    at Ci (https://grafana.mycorp/public/build/5226.48dbd59a341e1b9072d3.js:197:4727)
    at An (https://grafana.mycorp/public/build/5226.48dbd59a341e1b9072d3.js:197:10217)
    at Do (https://grafana.mycorp/public/build/5226.48dbd59a341e1b9072d3.js:206:11746)
    at Ke (https://grafana.mycorp/public/build/5226.48dbd59a341e1b9072d3.js:206:25781)
    at div
    at div
    at div
    at main
    at Hc (https://grafana.mycorp/public/build/2077.434d3383b7b57dc17e44.js:9256:2429)
    at Ci (https://grafana.mycorp/public/build/5226.48dbd59a341e1b9072d3.js:197:4727)
    at An (https://grafana.mycorp/public/build/5226.48dbd59a341e1b9072d3.js:197:10217)
    at Tn (https://grafana.mycorp/public/build/5226.48dbd59a341e1b9072d3.js:197:9607)
    at es (https://grafana.mycorp/public/build/5226.48dbd59a341e1b9072d3.js:206:12045)
    at Ke (https://grafana.mycorp/public/build/5226.48dbd59a341e1b9072d3.js:206:19753)
    at div
    at c (https://grafana.mycorp/public/build/2077.434d3383b7b57dc17e44.js:2337:3973)
    at g (https://grafana.mycorp/public/build/5226.48dbd59a341e1b9072d3.js:46:13846)
    at i (https://grafana.mycorp/public/build/2077.434d3383b7b57dc17e44.js:4996:18170)
    at f (https://grafana.mycorp/public/build/2077.434d3383b7b57dc17e44.js:1320:180)
    at u (https://grafana.mycorp/public/build/2077.434d3383b7b57dc17e44.js:1320:754)
    at E (https://grafana.mycorp/public/build/5226.48dbd59a341e1b9072d3.js:175:118397)
    at cl (https://grafana.mycorp/public/build/2077.434d3383b7b57dc17e44.js:9270:122)
```

### What did you expect to happen?

Editing a contact point should just work. :)

### Did this work before?

Not sure, first setup we've with the mimir-alertmanager. It works for the Grafana Alertmanager.

### How do we reproduce it?

Alerting -> Contact Points -> select "alertmanager" (here mimir-alertmanager) as the alertmanager -> Add contact point ->
Integration: Webhook
URL: http://my-crazy-domain-for-a-webhook.com/api/foobar

Optional Webhook settings -> HTTP Config -> Basic auth ->
Username: foo
Password: bar

-> Save contact point -> Click on the pen symbol next to the "test123 Webhook"

### Environment (with versions)?

Grafana: Grafana v10.0.2 (b2bbe10fbc)
Browser: Vivaldi 6.1.3035.257

### Grafana platform?

Kubernetes

**Comment by hoexter** [comment]
Apparently I missed the release of 10.0.3 where this issue got fixed.
