### ISSUE TITLE
Grafana 9.5.9 / alert rule panic runtime error: index out of range [0] with length 0 - occurs when no data is returned by the query

### ISSUE THREAD

**Issue by Daryes** [grafana/grafana#74974]
### What happened?

I've just upgraded from grafana 9.3.8 to 9.5.9 and I got suddenly multiple grafana rules causing this error in the log.
```
logger=ngalert.eval rule_uid=pABl7yFVz org_id=1 t=2023-09-17T16:05:01.116794133+02:00 level=error msg="alert rule panic" error="runtime error: index out of range [0] with length 0" stack="goroutine 673 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x5e
github.com/grafana/grafana/pkg/services/ngalert/eval.(*conditionEvaluator).EvaluateRaw.func1()
	github.com/grafana/grafana/pkg/services/ngalert/eval/eval.go:58 +0x7d
panic({0xb2e480?, 0xc0024485a0?})
	runtime/panic.go:914 +0x21f
github.com/grafana/grafana/pkg/expr.(*DSNode).Execute(0xc0022682c0, {0x1633840, 0xc0033251f0}, {0xc0025a8f68?, 0x33a51a5?, 0x61579e0?}, 0x7feea5b7cb10?, 0xc000f8c8a0)
	github.com/grafana/grafana/pkg/expr/nodes.go:317 +0x171b
```

Or from the alerting => rules editor 
```
logger=ngalert.eval t=2023-09-17T19:14:52.256796788+02:00 level=error msg="alert rule panic" error="runtime error: index out of range [0] with length 0" stack="goroutine 45929 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x5e
github.com/grafana/grafana/pkg/services/ngalert/eval.(*conditionEvaluator).EvaluateRaw.func1()
	github.com/grafana/grafana/pkg/services/ngalert/eval/eval.go:58 +0x7d
panic({0xb2e480?, 0xc00313c3c0?})
	runtime/panic.go:914 +0x21f
github.com/grafana/grafana/pkg/expr.(*DSNode).Execute(0xc002390bb0, {0x1633840, 0xc00258df80}, {0xc0017a7a88?, 0x33a51a5?, 0x61579e0?}, 0x7f6d14e347a0?, 0xc000fe0cc0)
	github.com/grafana/grafana/pkg/expr/nodes.go:317 +0x171b
github.com/grafana/grafana/pkg/expr.(*DataPipeline).execute(0xc0017a7c10, {0x1633840, 0xc00258df80}, {0x34bb150?, 0xc00258df80?, 0x61579e0?}, 0x61579e0?)
	github.com/grafana/grafana/pkg/expr/graph.go:53 +0xfe
github.com/grafana/grafana/pkg/expr.(*Service).ExecutePipeline(0x1633798?, {0x1633840, 0xc00258df80}, {0xc002d1a300?, 0xc003c630e0?, 0x61579e0?}, {0xc002d1a2d0, 0x3, 0x3})
	github.com/grafana/grafana/pkg/expr/service.go:68 +0xcf
github.com/grafana/grafana/pkg/services/ngalert/eval.(*conditionEvaluator).EvaluateRaw(0xc001ff0840?, {0x1633798?, 0xc002193bc0?}, {0xc001a64f00?, 0xc002477760?, 0x61579e0?})
	github.com/grafana/grafana/pkg/services/ngalert/eval/eval.go:74 +0x139
github.com/grafana/grafana/pkg/services/ngalert/api.TestingApiSrv.RouteEvalQueries({0xc000b7bd70, {0x161a9c0, 0xc000fe05a0}, {0x1644750, 0xc000db70e0}, {0x162ade8, 0xc001034540}, {0x161c450, 0xc000db6e40}, 0xc0002b3368, ...}, ...)
	github.com/grafana/grafana/pkg/services/ngalert/api/api_testing.go:142 +0x555
github.com/grafana/grafana/pkg/services/ngalert/api.(*TestingApiHandler).handleRouteEvalQueries(...)
	github.com/grafana/grafana/pkg/services/ngalert/api/testing_api.go:29
```

### What did you expect to happen?

No error

### Did this work before?

No problem up to grafana 9.3.8, upgrading directly to 9.5.9 caused this error

### How do we reproduce it?

With an influxdb datasource, create a rule with a working query
Edit your query to add a condition to return an empty result, ex : SELECT metric FROM measurement WHERE ... `AND "mytag"= 'this will crash' ` ...
Click on preview
Grafana goes on error immediately. 

Given the error message `index out of range [0] with length 0`, it seems Grafana expects before anything that the query will always return some data

This can be confirmed on an existing rule where from time to time there's no data (like with on-demand services, or similar).
When the crash occurs due to the absence of data, just increase the time range to `now-12h to now` and it will start working correctly, because the range is enough to have some data.

### Is the bug inside a dashboard panel?

Related to Grafana alerting rules

### Environment (with versions)?

Grafana: 9.5.9
OS: Ubuntu 22.04
Browser: Firefox ESR 115.2

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

Influxdb 1.9

**Comment by usmangt** [comment]
Hi @Daryes,

Thanks for opening this issue.


Please review the submission template and include more details:

* What operating system are you using?
* Are you running Grafana in Docker, Kubernetes or any other environment?
* Can you please copy/paste the configuration file `/etc/grafana/grafana.ini`?

Optional 
* What happens, if you try to update from 9.3.8 to the current stable version i.e. 10.1.1?

**Comment by tobhv** [comment]
Hi. i have the same issue and am running on version 9.5.9.
OS: debian bookworm.
grafana runs on docker.
my datasource is postgresql though. log messages:
```
 logger=ngalert.eval rule_uid=b09bef3a-4e53-4447-8be8-b49ccb0db632 org_id=2 t=2023-09-19T07:55:09.321200261Z level=error msg="alert rule panic" error="runtime error: index out of range [0] with length 0" stack="goroutine 1874 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\ngithub.com/grafana/grafana/pkg/services/ngalert/eval.(*conditionEvaluator).EvaluateRaw.func1()\n\tgithub.com/grafana/grafana/pkg/services/ngalert/eval/eval.go:58 +0x7d\npanic({0xb2e480?, 0xc004800d68?})\n\truntime/panic.go:914 +0x21f\ngithub.com/grafana/grafana/pkg/expr.(*DSNode).Execute(0xc003e0ebb0, {0x1633840, 0xc003889a40}, {0xc0024cef68?, 0x33a51a5?, 0x61579e0?}, 0x7f773a0e8008?, 0xc0008b5770)\n\tgithub.com/grafana/grafana/pkg/expr/nodes.go:317 +0x171b\ngithub.com/grafana/grafana/pkg/expr.(*DataPipeline).execute(0xc0024cf0f0, {0x1633840, 0xc003889a40}, {0x34bb150?, 0xc003889a40?, 0x61579e0?}, 0x61579e0?)\n\tgithub.com/grafana/grafana/pkg/expr/graph.go:53 +0xfe\ngithub.com/grafana/grafana/pkg/expr.(*Service).ExecutePipeline(0x1633798?, {0x1633840, 0xc003889a40}, {0x60?, 0x58?, 0x61579e0?}, {0xc003051120, 0x2, 0x2})\n\tgithub.com/grafana/grafana/pkg/expr/service.go:68 +0xcf\ngithub.com/grafana/grafana/pkg/services/ngalert/eval.(*conditionEvaluator).EvaluateRaw(0xc00394ef00?, {0x1633798?, 0xc003637f20?}, {0x0?, 0x2?, 0x61579e0?})\n\tgithub.com/grafana/grafana/pkg/services/ngalert/eval/eval.go:74 +0x139\ngithub.com/grafana/grafana/pkg/services/ngalert/eval.(*conditionEvaluator).Evaluate(0xc00394ef00, {0x1633798?, 0xc003637f20?}, {0xc003035000?, 0x5f8c8e8?, 0x61579e0?})\n\tgithub.com/grafana/grafana/pkg/services/ngalert/eval/eval.go:79 +0x51\ngithub.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRoutine.func3({0x1633798, 0xc003637f20}, 0x4090c20328dd53cc?, 0x0?, 0xc003137188, {0x1644700, 0xc0038d99c0})\n\tgithub.com/grafana/grafana/pkg/services/ngalert/schedule/schedule.go:386 +0x643\ngithub.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRoutine.func5.2(0x48?)\n\tgithub.com/grafana/grafana/pkg/services/ngalert/schedule/schedule.go:519 +0xa8b\ngithub.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRoutine.func4(0xc0034171d0)\n\tgithub.com/grafana/grafana/pkg/services/ngalert/schedule/schedule.go:446 +0x59\ngithub.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRoutine.func5(0x0?, 0xc000f0e8f0, {0xc1380f711c05e652?, {0xc0024be840?, 0x61579e0?}}, 0xc003137188, 0xc0032a3e70, 0xc002016418, {0x1644750, 0xc0030e2ea0}, ...)\n\tgithub.com/grafana/grafana/pkg/services/ngalert/schedule/schedule.go:487 +0x1a6\ngithub.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRoutine(0xc000f0e8f0, {0x1633fb0, 0xc00307bbc0}, {0xc001948240?, {0xc0024be840?, 0x0?}}, 0xc000d57f80, 0xc0024dc000)\n\tgithub.com/grafana/grafana/pkg/services/ngalert/schedule/schedule.go:525 +0x7f6\ngithub.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).processTick.func1()\n\tgithub.com/grafana/grafana/pkg/services/ngalert/schedule/schedule.go:261 +0x36\ngolang.org/x/sync/errgroup.(*Group).Go.func1()\n\tgolang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x56\ncreated by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1843\n\tgolang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0x96\n"
grafana_1  | logger=ngalert.scheduler rule_uid=b09bef3a-4e53-4447-8be8-b49ccb0db632 org_id=2 version=30 fingerprint=4090c20328dd53cc attempt=0 now=2023-09-19T07:55:00Z t=2023-09-19T07:55:09.321243101Z level=error msg="Failed to evaluate rule" error="alert rule panic; please check the logs for the full stack" duration=33.918845ms
```
grafana.ini
```
[server]
domain = www.**REMOVED***.com
root_url = https://www.**REMOVED***.com

[users]
default_theme = light


[auth]
oauth_allow_insecure_email_lookup = true
oauth_auto_login = true
signout_redirect_url = https://**REMOVED***/realms/**REMOVED***/protocol/openid-connect/logout
login_cookie_name = __Host-grafana_session

[live]
max_connections = 0

[auth.generic_oauth]
skip_org_role_sync = true
enabled = true
name = OAuth
allow_sign_up = true
client_id = grafana
client_secret = **REMOVED***
scopes = openid profile email
empty_scopes = false
auth_url = https://**REMOVED***/realms/**REMOVED***/protocol/openid-connect/auth
token_url = https://**REMOVED***/realms/apps/protocol/openid-connect/token
api_url = https://**REMOVED***/realms/apps/protocol/openid-connect/userinfo
[plugin.marcusolsson-csv-datasource]
allow_local_mode = true
#workaround to disable password changes in grafana
#see also here https://community.grafana.com/t/workaround-to-disable-changing-pwd-when-using-generic-oauth/938
[auth.proxy]
enabled = true
[smtp]
enabled = true
host = host.docker.internal:25
from_address = noreply@**REMOVED***.com
from_name = **REMOVED***
skip_verify = true
[emails]
welcome_email_on_signup = false
[snapshots]
enabled = false
external_enabled = false
[database]
type = mysql
host = db:3306
name = grafanadb
user = **REMOVED***
password = **REMOVED***
[help]
enabled = false
[profile]
enabled = true
[security]
cookie_secure = true
cookie_samesite = strict
content_security_policy = true
```
if i run the query in datasource explore mode it runs without errors. behavior of the query is:
1) returns no data in case no threshold is hit.
2) returns columns in case a threshold is hit.
I see the issue only happening in case of 1) 

@usmangt 9.5.9 (or at time of writing 9.5.10) is supported and is as such a stable, supported version ?

**Comment by tobhv** [comment]
updated to 9.5.10 and behavior remains the same as described above.

**Comment by Daryes** [comment]
> Hi @Daryes,
> 
> Thanks for opening this issue.
> 
> Please review the submission template and include more details:
> 
>     * What operating system are you using?
> 
>     * Are you running Grafana in Docker, Kubernetes or any other environment?
> 
>     * Can you please copy/paste the configuration file `/etc/grafana/grafana.ini`?
> 
> 
> Optional
> 
>     * What happens, if you try to update from 9.3.8 to the current stable version i.e. 10.1.1?

Hello
The informations were already available at the end of the first message.
Aside the grafana.ini which is here :
```
[paths]
data = /server/grafana/data
plugins = /server/grafana/data/plugins
[server]
http_addr = 127.0.0.1
http_port = 3000
domain = grafana.***** masked for security
root_url = https://grafana.***** masked for security
enable_gzip = true
[database]
log_queries = false
[datasources]
[remote_cache]
[dataproxy]
[analytics]
reporting_enabled = false
check_for_updates = false
check_for_plugin_updates = false
feedback_links_enabled = false
[security]
disable_gravatar = true
[security.encryption]
[snapshots]
[dashboards]
versions_to_keep = 10
min_refresh_interval = 30s
[users]
allow_sign_up = false
editors_can_admin = true
[auth]
[auth.anonymous]
enabled = false
hide_version = true
[auth.github]
[auth.gitlab]
[auth.google]
[auth.grafana_com]
[auth.azuread]
[auth.okta]
[auth.generic_oauth]
enabled = true
name = Keycloak
allow_sign_up = true
client_id = ***** masked for security
client_secret = ***** masked for security
scopes = openid email username_alt
auth_url = https://sso.***** masked for security
token_url = https://sso.***** masked for security
api_url = https://sso.***** masked for security
[auth.basic]
[auth.proxy]
[auth.jwt]
[auth.ldap]
[aws]
[azure]
[rbac]
[smtp]
[emails]
[log]
mode = file
level = warn
[log.console]
[log.file]
[log.syslog]
[log.frontend]
[quota]
[unified_alerting]
enabled = true
execute_alerts = true
evaluation_timeout = 5m
[unified_alerting.reserved_labels]
[alerting]
enabled = false
max_annotation_age = 3M
[annotations]
[annotations.dashboard]
max_age = 3M
[annotations.api]
max_age = 3M
[explore]
[help]
[profile]
[query_history]
[metrics]
enabled = false
basic_auth_username =
basic_auth_password =
[metrics.environment_info]
[metrics.graphite]
[grafana_com]
[tracing.jaeger]
[tracing.opentelemetry]
[tracing.opentelemetry.jaeger]
[tracing.opentelemetry.otlp]
[external_image_storage]
[external_image_storage.s3]
[external_image_storage.webdav]
[external_image_storage.gcs]
[external_image_storage.azure_blob]
[external_image_storage.local]
[rendering]
[panels]
[plugins]
[live]
[plugin.grafana-image-renderer]
[enterprise]
[feature_toggles]
swaggerUi = false
[date_formats]
[expressions]
[geomap]
[navigation.app_sections]
[navigation.app_standalone_pages]
```

**Comment by RoyBoerner** [comment]
Same story for my installation. Issue occurred with 9.5.9 + 9.5.10. Rolled back to 9.5.8 and all is fine.

**Comment by vincent-olivert-riera** [comment]
> Grafana 9.5.11 should be released on October 3rd, this will fix the issue.

@armandgrillet , it seems that 9.5.11 was skipped and 9.5.12 was released instead.
Does 9.5.12 include the fix for this issue?

**Comment by toerkl** [comment]
Hi, any idea what version this fix will be available in? As stated above, it seems 9.5.11 was never released.

**Comment by te-online** [comment]
I just updated to 9.5.12 and when I preview the alert rule with now-12h, it still panics. Not sure if this is the exact same issue as @Daryes reported, but it did work before 9.5.9 (even if not enough data was available in the last 12 hours)

**Comment by tobhv** [comment]
Hi, from my end I can confirm that the issue still persists. @armandgrillet could you perhaps share some update ?

**Comment by jbkc85** [comment]
I just updated to v9.5.12 and ran into this issue too.  I have not been able to find a work around just yet.

**Comment by psyfox** [comment]
Same problem here. The solution was a roll back to 9.5.8 since 9.5.12 still have the issue.

**Comment by vincent-olivert-riera** [comment]
9.5.13 has been released and I think it does not include the fix either. This is very confusing because I would have expected to see 9.5.13 as a continuation of 9.5.12, however that does not seem to be the case:
![image](https://github.com/grafana/grafana/assets/6151586/4dc44a98-a3b1-44d6-8cc6-0d9a94abe772)
I don't know which logic Grafana follows for managing their branches, tags, or cutting their releases, but to me it looks a little bit chaotic (and worrying).

**Comment by Daryes** [comment]
The fix seems to be in 9.5.13, but I didn't check it yet.

It is related to this [fix](https://github.com/grafana/grafana/pull/74866), which has the following [backport](https://github.com/grafana/grafana/pull/74874) into 9.5.x  
Said backport is from the previous month, so you need to look for it in the commit history. You'll find it for the 9.5.13 release in at the sept 13, 2023, first one : `[v9.5.x] SSE: Fix DSNode to not panic when response has empty response`

**Comment by tobhv** [comment]
thx @Daryes ! for me the issue is resolved.

**Comment by tobhv** [comment]
hmm. not entirely it seems. the issue around empty results is solved. however if / when the alert returns data i get this error:
![image](https://github.com/grafana/grafana/assets/118474835/20a574a3-e24c-4742-82fb-8ea213d6baa7)

**Comment by tobhv** [comment]
found out cause of mentioned error. it was because i parsed values as strings. this used to work fine in 9.5.12 and earlier. (sorry: forgot why i chose that). so looks like some other behavior changed as a result of the fix but after adjusting to use value type for a value it looks fine to me. thanks again.

**Comment by te-online** [comment]
For what it's worth: Upgrading to 10.1.5 seems to have fixed this issue for me.
