### ISSUE TITLE
CRITICAL BUG: TypeError: e._d.getTime is not a function | results in crash when saving Grafana Cloud dashboard

### ISSUE THREAD

**Issue by MatinF** [grafana/grafana#76448]
### UPDATE
As per my latest post below, this is not related to Athena or any other specific data source. It appears to be a general issue related to saving dashboards with specific time periods specified - even applying to empty dashboards.

This is a critical bug because users will loose any progress they've made when they attempt to save their changes.

-----------

### What happened?

We are creating an Amazon Athena dashboard in Grafana Cloud. The dashboard template is attached below:

[athena-dashboard.json](https://github.com/grafana/grafana/files/12882429/athena-dashboard.json)

When I work with the dashboard, everything works as expected. I can also save my dashboard updates when I select 'All' in my `signal` dropdown. However, if I select specific signals in the drop down the dashboard crashes upon saving. I am also able to reproduce this if I select 'All' in `signal` and in `aggregation`. I do not know what causes this issue.

The video below shows the behavior and I've pasted both the error output from the browser window and console:

**Video**

https://github.com/grafana/grafana/assets/26184427/a29fc9bd-b34c-4a0e-86d2-ac5b0c11459e

**Browser window error**
```
An unexpected error happened
Details
TypeError: e._d.getTime is not a function

    at Qe (https://grafana-assets.grafana.net/grafana/10.2.0-61719/public/build/1470.848c23aba69169162826.js:2507:4383)
    at div
    at div
    at div
    at Z (https://grafana-assets.grafana.net/grafana/10.2.0-61719/public/build/7894.18f6b3bac734822c76f9.js:120:79442)
    at s (https://grafana-assets.grafana.net/grafana/10.2.0-61719/public/build/1470.848c23aba69169162826.js:204:30031)
    at div
    at h (https://grafana-assets.grafana.net/grafana/10.2.0-61719/public/build/7894.18f6b3bac734822c76f9.js:642:78922)
    at div
    at O (https://grafana-assets.grafana.net/grafana/10.2.0-61719/public/build/7894.18f6b3bac734822c76f9.js:39:38163)
    at div
    at ke (https://grafana-assets.grafana.net/grafana/10.2.0-61719/public/build/7894.18f6b3bac734822c76f9.js:39:48888)
    at https://grafana-assets.grafana.net/grafana/10.2.0-61719/public/build/7894.18f6b3bac734822c76f9.js:39:49199
    at div
    at R (https://grafana-assets.grafana.net/grafana/10.2.0-61719/public/build/7894.18f6b3bac734822c76f9.js:39:39160)
    at https://grafana-assets.grafana.net/grafana/10.2.0-61719/public/build/7894.18f6b3bac734822c76f9.js:26:296
    at P (https://grafana-assets.grafana.net/grafana/10.2.0-61719/public/build/7894.18f6b3bac734822c76f9.js:39:42581)
    at u (https://grafana-assets.grafana.net/grafana/10.2.0-61719/public/build/1470.848c23aba69169162826.js:204:112169)
    at at (https://grafana-assets.grafana.net/grafana/10.2.0-61719/public/build/1470.848c23aba69169162826.js:2518:21)
    at r
    at l (https://grafana-assets.grafana.net/grafana/10.2.0-61719/public/build/1470.848c23aba69169162826.js:224:13290)
    at v (https://grafana-assets.grafana.net/grafana/10.2.0-61719/public/build/7894.18f6b3bac734822c76f9.js:37:13808)
    at d (https://grafana-assets.grafana.net/grafana/10.2.0-61719/public/build/7894.18f6b3bac734822c76f9.js:642:177319)
    at c (https://grafana-assets.grafana.net/grafana/10.2.0-61719/public/build/1470.848c23aba69169162826.js:1076:20362)
    at o (https://grafana-assets.grafana.net/grafana/10.2.0-61719/public/build/1470.848c23aba69169162826.js:204:119127)
    at m (https://grafana-assets.grafana.net/grafana/10.2.0-61719/public/build/1470.848c23aba69169162826.js:204:119636)
    at y (https://grafana-assets.grafana.net/grafana/10.2.0-61719/public/build/7894.18f6b3bac734822c76f9.js:181:94044)
    at ni (https://grafana-assets.grafana.net/grafana/10.2.0-61719/public/build/1470.848c23aba69169162826.js:384:127)
```

I am using Chrome and my console output is below:

```
module.js?_cache=0.6.7:452 TypeError: e._d.getTime is not a function
    at new ve (moment.js:262:58)
    at sa (moment.js:2968:20)
    at dn (moment.js:2943:44)
    at na (moment.js:3037:16)
    at A (moment.js:3041:16)
    at a (moment.js:16:29)
    at g (moment_wrapper.ts:117:10)
    at U.hasTimeChanged (DashboardModel.ts:1095:38)
    at SaveDashboardForm.tsx:39:50
    at Object.useMemo (react-dom.production.min.js:184:189)

```

### What did you expect to happen?

The dashboard should save as expected without crashing

### Did this work before?

I do not know

### How do we reproduce it?

I am unable to provide a directly reproducible example

### Environment (with versions)?

Grafana: Grafana v10.2.0-61719 (165b4c3f66) | Cloud

OS: Windows 10 64 bit
Browser: Chrome

### Grafana platform?

None

**Comment by MatinF** [comment]
I tried re-creating my dashboard from scratch. This initially seemed to work, allowing me to save between adding each variable again. But after setting up the final part of the dashboard, my panel, the error started coming again. When I then try to 'scrape down' the dashboard to go back to what worked before, the error persists - even though I believe I ended up in a version that previously worked. 

It persists even down to creating just a single variable drop down with `SHOW TABLES`, until I then remove the regex as well from that drop down - after which I can save. But just before, when I was remaking the dashboard from scratch, that same variable with that same regex worked without issues.

**Comment by MatinF** [comment]
Note also that I am happy to provide our Athena datasource credentials for this test setup in a direct message.

**Comment by MatinF** [comment]
I have now isolated this further:

1) The crash issue does not happen if I use any of the 'relative' time periods (i.e. available from the time drop down), such as last 6 hours, last 2 years etc. This does not crash any version of the dashboard.

2) However, if I select a specific time period the dashboard can be saved (if no further action is taken first after selecting the time period), but then trying to save again will cause the crash.

This has been tested across various versions of my dashboard. 


Further, I have verified that this is unrelated to variable drop downs. The most simplistic example can be used to recreate this:

**Create a clean dashboard with a single panel as below**

![image](https://github.com/grafana/grafana/assets/26184427/36874750-0670-4684-9457-02ed1dfa2496)

**Save the dashboard after creating and refreshing the panel**
Verify that everything works as long as relative time periods are used, see below:
![image](https://github.com/grafana/grafana/assets/26184427/c29d720a-33f7-45e1-9742-b010edfbf77f)


**Change to a specific time period as below**
![image](https://github.com/grafana/grafana/assets/26184427/fcf80072-1456-4f6d-bae9-72c73646aaa6)

**Save the dashboard to trigger the crash**
![image](https://github.com/grafana/grafana/assets/26184427/f5bdb579-22e6-4825-acf6-2fd5388410e0)

Note that if the above does not trigger the crash, try changing the time period by e.g. 1 minute and save again.

We really hope this can be resolved quickly.

**Comment by MatinF** [comment]
**UPDATE**

This is **not related to Athena specifically** - this can be replicated with e.g. a Grafana random walk - or **with no data source at all** (i.e. an empty newly created dashboard). It seems to be a 100% general problem that would be critical to resolve asap.

**Comment by dprokop** [comment]
Introduced in https://github.com/grafana/grafana/pull/76116 by deep freezing time Moment objects that became corrupted after that. WIll be soon fixed with https://github.com/grafana/grafana/pull/76506 merged.
