### ISSUE TITLE
Invalid dimensions for plot, width = 1173.2119140625, height = 0

### ISSUE THREAD

**Issue by 756445638** [grafana/grafana#7655]
Stack trace:
Error: Invalid dimensions for plot, width = 1173.2119140625, height = 0
    at b.resize (http://localhost:3000/public/app/boot.js:20:9749)
    at new b (http://localhost:3000/public/app/boot.js:19:11211)
    at t (http://localhost:3000/public/app/boot.js:19:18040)
    at new c (http://localhost:3000/public/app/boot.js:20:9458)
    at Function.a.plot (http://localhost:3000/public/app/boot.js:20:12393)
    at a (http://localhost:3000/public/app/boot.js:18:7420)
    at q (http://localhost:3000/public/app/boot.js:18:8835)
    at f.<anonymous> (http://localhost:3000/public/app/boot.js:18:11799)
    at f.emit (http://localhost:3000/public/app/boot.js:52:3361)
    at a.emit (http://localhost:3000/public/app/boot.js:52:5256)

**Comment by torkelo** [comment]
This should not result in any noticeable issues

**Comment by 756445638** [comment]
What I have to do to solve this problem??

**Comment by torkelo** [comment]
Can you describe your problem?  The stack trace is when trying to render panels with no width. But you never described the problem, only a stack trace. 

Maybe you have  panel with span zero?

**Comment by 756445638** [comment]
thank godness,this problem has disappeared,I think it it my data have some problem,thank you !!

**Comment by 756445638** [comment]
I add 8 hours when insert data into influxdb!!
here is my code:
     now := utils.UnixMs(time.Now().Add(8 * time.Hour))
