### ISSUE TITLE
Add configurable starting timeout

### ISSUE THREAD

**Issue by BloberSh** [grafana/grafana#76809]
**Why is this needed**:

If Grafana takes more than 30s to start (due to network latency or whatever your want), the context deadline is exceeded and the start stop and fail with error : 
`logger=ngalert.multiorg.alertmanager t=2023-10-19T13:47:20.856219513+02:00 level=error msg="unable to create Alertmanager for org" org=7774 error="error
 reading file 'silences' from database: context deadline exceeded"
logger=cli t=2023-10-19T13:47:20.856558118+02:00 level=error msg="Critical error" reason="runtime error: invalid memory address or nil pointer dereference" stackTrace="goroutine 1 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/grafana/grafana/pkg/cmd/grafana-server/commands.RunServer.func3()\n\tgithub.com/grafana/grafana/pkg/cmd/grafana-server/commands/cli.go:181 +0x9c\npanic({0x98e5e0, 0x9621f80})\n\truntime/panic.go:890 +0x263\ngithub.com/grafana/grafana/pkg/services/ngalert/notifier.(*Alertmanager).ApplyConfig(0x0, {0x1f0f808, 0xc0018300c0}, 0xc0006497c0)\n\tgithub.com/grafana/grafana/pkg/services/ngalert/notifier/alertmanager.go:233 +0x11b\ngithub.com/grafana/grafana/pkg/services/ngalert/notifier.(*MultiOrgAlertmanager).SyncAlertmanagersForOrgs(0xc00096ab40, {0x1f0f808, 0xc0018300c0}, {0xc001e52000, 0x2c9, 0xc001c44240?})\n\tgithub.com/grafana/grafana/pkg/services/ngalert/notifier/multiorg_alertmanager.go:239 +0x77f\ngithub.com/grafana/grafana/pkg/services/ngalert/notifier.(*MultiOrgAlertmanager).LoadAndSyncAlertmanagersForOrgs(0xc00096ab40, {0x1f0f808, 0xc0018300c0})\n\tgithub.com/grafana/grafana/pkg/services/ngalert/notifier/multiorg_alertmanager.go:171 +0xd8\ngithub.com/grafana/grafana/pkg/services/ngalert.(*AlertNG).init(0xc0018241a0)\n\tgithub.com/grafana/grafana/pkg/services/ngalert/ngalert.go:170 +0x305\ngithub.com/grafana/grafana/pkg/services/ngalert.ProvideService(_, {_, _}, {_, _}, {_, _}, {_, _}, {0x1f326a0, ...}, ...)\n\tgithub.com/grafana/grafana/pkg/services/ngalert/ngalert.go:103 +0x5c9\ngithub.com/grafana/grafana/pkg/server.Initialize({{0x7ffc9cd90b91, 0x1f}, {0x0, 0x0}, {0xc000522280, 0x5, 0x5}}, {{0x0, 0x0}, {0x7ffc9cd90bbb, ...}, ...}, ...)\n\tgithub.com/grafana/grafana/pkg/server/wire_gen.go:481 +0x4e4e\ngithub.com/grafana/grafana/pkg/cmd/grafana-server/commands.RunServer({{0x1eb3db0, 0x6}, {0x1eb51d8, 0xa}, {0x1eb3da8, 0x4}, {0x1eb51c8, 0xa}, 0xc0009654c0})\n\tgithub.com/grafana/grafana/pkg/cmd/grafana-server/commands/cli.go:228 +0xfea\ngithub.com/grafana/grafana/pkg/cmd/grafana-server/commands.ServerCommand.func1(0xc0011c7b10?)\n\tgithub.com/grafana/grafana/pkg/cmd/grafana-server/commands/cli.go:97 +0xc5\ngithub.com/urfave/cli/v2.(*Command).Run(0xc001146160, 0xc0009654c0, {0xc0008e4200, 0x8, 0x8})\n\tgithub.com/urfave/cli/v2@v2.25.0/command.go:273 +0x9eb\ngithub.com/urfave/cli/v2.(*Command).Run(0xc001146420, 0xc000965380, {0xc000074090, 0x9, 0x9})\n\tgithub.com/urfave/cli/v2@v2.25.0/command.go:266 +0xc4d\ngithub.com/urfave/cli/v2.(*App).RunContext(0xc0005f30e0, {0x1f0f7d0?, 0xc000076040}, {0xc000074090, 0x9, 0x9})\n\tgithub.com/urfave/cli/v2@v2.25.0/app.go:332 +0x616\ngithub.com/urfave/cli/v2.(*App).Run(...)\n\tgithub.com/urfave/cli/v2@v2.25.0/app.go:309\nmain.main()\n\tgithub.com/grafana/grafana/pkg/cmd/grafana/main.go:39 +0x285\n"`

This specific error is from `pkg/services/ngalert/ngalert.go` line 151 (for grafana 10.1.5)
`// AlertNG should be initialized before the cancellation deadline of initCtx
	initCtx, cancelFunc := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancelFunc()`

**What would you like to be added**:

Add a configurable starting timeout with by default 30s in the configuration file.

**Who is this feature for?**

We are using it at company level with more than 700 orgs.

**Comment by iXingo** [comment]
same here

**Comment by BloberSh** [comment]
Hello @iXingo , no solution atm.
