### ISSUE TITLE
Core: Go panic/SIGSEGV

### ISSUE THREAD

**Issue by PythonCoderAS** [grafana/grafana#77050]
### What happened?

```
logger=ngalert.multiorg.alertmanager t=2023-10-24T13:40:41.924703616Z level=error msg="unable to create Alertmanager for org" org=1 error="error writing file notifications: open /var/lib/grafana/alerting/1/notifications: permission denied"
logger=cli t=2023-10-24T13:40:41.931976009Z level=error msg="Critical error" reason="runtime error: invalid memory address or nil pointer dereference" stackTrace="goroutine 1 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/grafana/grafana/pkg/cmd/grafana-server/commands.RunServer.func3()\n\tgithub.com/grafana/grafana/pkg/cmd/grafana-server/commands/cli.go:181 +0x9c\npanic({0x98e5e0, 0x9621f80})\n\truntime/panic.go:890 +0x263\ngithub.com/grafana/grafana/pkg/services/ngalert/notifier.(*Alertmanager).ApplyConfig(0x0, {0x1f0f808, 0xc0015c4120}, 0xc000a0e910)\n\tgithub.com/grafana/grafana/pkg/services/ngalert/notifier/alertmanager.go:233 +0x11b\ngithub.com/grafana/grafana/pkg/services/ngalert/notifier.(*MultiOrgAlertmanager).SyncAlertmanagersForOrgs(0xc0013cef00, {0x1f0f808, 0xc0015c4120}, {0xc001438868, 0x1, 0x1f170c0?})\n\tgithub.com/grafana/grafana/pkg/services/ngalert/notifier/multiorg_alertmanager.go:239 +0x77f\ngithub.com/grafana/grafana/pkg/services/ngalert/notifier.(*MultiOrgAlertmanager).LoadAndSyncAlertmanagersForOrgs(0xc0013cef00, {0x1f0f808, 0xc0015c4120})\n\tgithub.com/grafana/grafana/pkg/services/ngalert/notifier/multiorg_alertmanager.go:171 +0xd8\ngithub.com/grafana/grafana/pkg/services/ngalert.(*AlertNG).init(0xc0015b1040)\n\tgithub.com/grafana/grafana/pkg/services/ngalert/ngalert.go:170 +0x305\ngithub.com/grafana/grafana/pkg/services/ngalert.ProvideService(_, {_, _}, {_, _}, {_, _}, {_, _}, {0x1f326a0, ...}, ...)\n\tgithub.com/grafana/grafana/pkg/services/ngalert/ngalert.go:103 +0x5c9\ngithub.com/grafana/grafana/pkg/server.Initialize({{0x7fff0966ad4c, 0x18}, {0x7fff0966ad30, 0x12}, {0xc00117e180, 0x6, 0x6}}, {{0x0, 0x0}, {0x0, ...}, ...}, ...)\n\tgithub.com/grafana/grafana/pkg/server/wire_gen.go:481 +0x4e4e\ngithub.com/grafana/grafana/pkg/cmd/grafana-server/commands.RunServer({{0x1eb3db0, 0x6}, {0x1eb51d8, 0xa}, {0x1eb3da8, 0x4}, {0x1eb51c8, 0xa}, 0xc0006d8300})\n\tgithub.com/grafana/grafana/pkg/cmd/grafana-server/commands/cli.go:228 +0xfea\ngithub.com/grafana/grafana/pkg/cmd/grafana-server/commands.ServerCommand.func1(0xc0010bfb10?)\n\tgithub.com/grafana/grafana/pkg/cmd/grafana-server/commands/cli.go:97 +0xc5\ngithub.com/urfave/cli/v2.(*Command).Run(0xc0010dd8c0, 0xc0006d8300, {0xc000740e10, 0x9, 0x9})\n\tgithub.com/urfave/cli/v2@v2.25.0/command.go:273 +0x9eb\ngithub.com/urfave/cli/v2.(*Command).Run(0xc0010ddb80, 0xc0006d80c0, {0xc0001a6000, 0xa, 0xa})\n\tgithub.com/urfave/cli/v2@v2.25.0/command.go:266 +0xc4d\ngithub.com/urfave/cli/v2.(*App).RunContext(0xc0009f9860, {0x1f0f7d0?, 0xc0001a8000}, {0xc0001a6000, 0xa, 0xa})\n\tgithub.com/urfave/cli/v2@v2.25.0/app.go:332 +0x616\ngithub.com/urfave/cli/v2.(*App).Run(...)\n\tgithub.com/urfave/cli/v2@v2.25.0/app.go:309\nmain.main()\n\tgithub.com/grafana/grafana/pkg/cmd/grafana/main.go:39 +0x285\n"
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x71d12db]

goroutine 1 [running]:
github.com/grafana/grafana/pkg/cmd/grafana-server/commands.RunServer.func3()
	github.com/grafana/grafana/pkg/cmd/grafana-server/commands/cli.go:182 +0x17e
panic({0x98e5e0, 0x9621f80})
	runtime/panic.go:890 +0x263
github.com/grafana/grafana/pkg/services/ngalert/notifier.(*Alertmanager).ApplyConfig(0x0, {0x1f0f808, 0xc0015c4120}, 0xc000a0e910)
	github.com/grafana/grafana/pkg/services/ngalert/notifier/alertmanager.go:233 +0x11b
github.com/grafana/grafana/pkg/services/ngalert/notifier.(*MultiOrgAlertmanager).SyncAlertmanagersForOrgs(0xc0013cef00, {0x1f0f808, 0xc0015c4120}, {0xc001438868, 0x1, 0x1f170c0?})
	github.com/grafana/grafana/pkg/services/ngalert/notifier/multiorg_alertmanager.go:239 +0x77f
github.com/grafana/grafana/pkg/services/ngalert/notifier.(*MultiOrgAlertmanager).LoadAndSyncAlertmanagersForOrgs(0xc0013cef00, {0x1f0f808, 0xc0015c4120})
	github.com/grafana/grafana/pkg/services/ngalert/notifier/multiorg_alertmanager.go:171 +0xd8
github.com/grafana/grafana/pkg/services/ngalert.(*AlertNG).init(0xc0015b1040)
	github.com/grafana/grafana/pkg/services/ngalert/ngalert.go:170 +0x305
github.com/grafana/grafana/pkg/services/ngalert.ProvideService(_, {_, _}, {_, _}, {_, _}, {_, _}, {0x1f326a0, ...}, ...)
	github.com/grafana/grafana/pkg/services/ngalert/ngalert.go:103 +0x5c9
github.com/grafana/grafana/pkg/server.Initialize({{0x7fff0966ad4c, 0x18}, {0x7fff0966ad30, 0x12}, {0xc00117e180, 0x6, 0x6}}, {{0x0, 0x0}, {0x0, ...}, ...}, ...)
	github.com/grafana/grafana/pkg/server/wire_gen.go:481 +0x4e4e
github.com/grafana/grafana/pkg/cmd/grafana-server/commands.RunServer({{0x1eb3db0, 0x6}, {0x1eb51d8, 0xa}, {0x1eb3da8, 0x4}, {0x1eb51c8, 0xa}, 0xc0006d8300})
	github.com/grafana/grafana/pkg/cmd/grafana-server/commands/cli.go:228 +0xfea
github.com/grafana/grafana/pkg/cmd/grafana-server/commands.ServerCommand.func1(0xc0010bfb10?)
	github.com/grafana/grafana/pkg/cmd/grafana-server/commands/cli.go:97 +0xc5
github.com/urfave/cli/v2.(*Command).Run(0xc0010dd8c0, 0xc0006d8300, {0xc000740e10, 0x9, 0x9})
	github.com/urfave/cli/v2@v2.25.0/command.go:273 +0x9eb
github.com/urfave/cli/v2.(*Command).Run(0xc0010ddb80, 0xc0006d80c0, {0xc0001a6000, 0xa, 0xa})
	github.com/urfave/cli/v2@v2.25.0/command.go:266 +0xc4d
github.com/urfave/cli/v2.(*App).RunContext(0xc0009f9860, {0x1f0f7d0?, 0xc0001a8000}, {0xc0001a6000, 0xa, 0xa})
	github.com/urfave/cli/v2@v2.25.0/app.go:332 +0x616
github.com/urfave/cli/v2.(*App).Run(...)
	github.com/urfave/cli/v2@v2.25.0/app.go:309
main.main()
	github.com/grafana/grafana/pkg/cmd/grafana/main.go:39 +0x285
```

### What did you expect to happen?

Grafana should launch

### Did this work before?

This worked until I moved Docker volumes.

### How do we reproduce it?

1. Make a new volume for grafana data
2. Make temp container with any OS (such as alpine) with both old and new volumes mounted
3. `cp -r /src/* /dest`
4. Use new container with grafana

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.2.0
OS: Ubuntu 22/04
Browser: N/A

### Grafana platform?

Docker

### Datasource(s)?

Prometheus

**Comment by tonypowa** [comment]
hi @PythonCoderAS 

thank you for creating this issue

>logger=ngalert.multiorg.alertmanager t=2023-10-24T13:40:41.924703616Z level=error msg="unable to create Alertmanager for org" org=1 error="error writing file notifications: open /var/lib/grafana/alerting/1/notifications: permission denied"

could you check if the new destination directory that you are copying your files to have same access rights as the original?

**Comment by PythonCoderAS** [comment]
I realized the backup had user root. I must have seen the root group and assumed the backup was correct.

**Comment by tonypowa** [comment]
Thank you @PythonCoderAS for sharing your findings. 
Let us know if you still need help regarding this issue or if it can be closed.

**Comment by PythonCoderAS** [comment]
Hello, sorry for not seeing this, I have fixed it for now but maybe grafana should print an obvious error about permission mismatch and hard exit instead of crash

**Comment by tonypowa** [comment]
> print an obvious error about permission mismatch and hard exit instead of crash

@grafana/backend-platform Hi Squad. is this something that you would consider implementing?

**Comment by armandgrillet** [comment]
Closing in favor of https://github.com/grafana/grafana/issues/77050, this is a known bug.
