### ISSUE TITLE
Query History: Flaky test in queryHistory.test.tsx

### ISSUE THREAD

**Issue by harisrozajac** [grafana/grafana#78236]
There's a flaky query history test in this [build](https://drone.grafana.net/grafana/grafana/146485/1/5). 

Here are the details: 

```
● Explore: Query History › add comments to query history

    thrown: "Exceeded timeout of 30000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      192 |   });
      193 |
    > 194 |   it('add comments to query history', async () => {
          |   ^
      195 |     const urlParams = {
      196 |       left: serializeStateToUrlParam({
      197 |         datasource: 'loki',

      at public/app/features/explore/spec/queryHistory.test.tsx:194:3
      at Object.<anonymous> (public/app/features/explore/spec/queryHistory.test.tsx:81:1)
```

**Comment by ifrost** [comment]
Related issues #70158, #59116, #47635.
