### ISSUE TITLE
[Bug]: Cannot read property 'from' of undefined

### ISSUE THREAD

**Issue by Fox32** [grafana/grafana#7849]
I just updated to the latest Grafana version from the master branch an get the following error:

Please include this information:
- What Grafana version are you using?
Grafana v4.3.0-pre1 (commit: 32f89f6)
- What datasource are you using?
Graphite
- What OS are you running grafana on?
via Docker
- What did you do?
I have existing Graph panels using Graphite that have alerts attached.
- What was the expected result?
 All existing alert panels should also work with the latest version.
- What happened instead?
All alert panels show this error:
```
TypeError: Cannot read property 'from' of undefined
    at a.getPanelAnnotations (http://192.168.1.95/public/app/boot.cd9f39d3.js:10:23643)
    at a.getAnnotations (http://192.168.1.95/public/app/boot.cd9f39d3.js:10:23213)
    at b.issueQueries (http://192.168.1.95/public/app/boot.cd9f39d3.js:19:7172)
    at i (http://192.168.1.95/public/app/boot.cd9f39d3.js:42:16547)
    at http://192.168.1.95/public/app/boot.cd9f39d3.js:42:16969
    at o.$eval (http://192.168.1.95/public/app/boot.cd9f39d3.js:42:24124)
    at o.$digest (http://192.168.1.95/public/app/boot.cd9f39d3.js:42:22597)
    at http://192.168.1.95/public/app/boot.cd9f39d3.js:42:24211
    at f (http://192.168.1.95/public/app/boot.cd9f39d3.js:41:2677)
    at http://192.168.1.95/public/app/boot.cd9f39d3.js:41:4138
```

This is the source of the Dashboard:

```{
  "alert": {
    "conditions": [
      {
        "evaluator": {
          "params": [
            1
          ],
          "type": "lt"
        },
        "query": {
          "datasourceId": 2,
          "model": {
            "datasource": "Graphite",
            "refId": "A",
            "target": "this.is.secret"
          },
          "params": [
            "A",
            "5h",
            "now"
          ]
        },
        "reducer": {
          "params": [],
          "type": "max"
        },
        "type": "query"
      }
    ],
    "executionErrorState": "keep_state",
    "frequency": "60s",
    "handler": 1,
    "name": "Blub",
    "noDataState": "keep_state",
    "notifications": [
      {
        "id": 4
      }
    ]
  },
  "aliasColors": {},
  "bars": false,
  "datasource": "-- Mixed --",
  "editable": true,
  "error": false,
  "fill": 1,
  "id": 4,
  "legend": {
    "avg": false,
    "current": false,
    "max": false,
    "min": false,
    "show": true,
    "total": false,
    "values": false
  },
  "lines": true,
  "linewidth": 2,
  "links": [],
  "nullPointMode": "connected",
  "percentage": false,
  "pointradius": 5,
  "points": false,
  "renderer": "flot",
  "seriesOverrides": [],
  "span": 3,
  "stack": false,
  "steppedLine": false,
  "targets": [
    {
      "datasource": "Graphite",
      "refId": "A",
      "target": "this.is.secret"
    }
  ],
  "thresholds": [
    {
      "colorMode": "critical",
      "fill": true,
      "line": true,
      "op": "lt",
      "value": 1
    }
  ],
  "timeFrom": null,
  "timeShift": null,
  "title": "Blud",
  "tooltip": {
    "msResolution": false,
    "shared": true,
    "sort": 0,
    "value_type": "cumulative"
  },
  "type": "graph",
  "xaxis": {
    "mode": "time",
    "name": null,
    "show": true,
    "values": []
  },
  "yaxes": [
    {
      "format": "short",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": "0",
      "show": true
    },
    {
      "format": "short",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    }
  ]
}
```

**Comment by torkelo** [comment]
sorry, introduced in a change this morning, will fix asap
