### ISSUE TITLE
GitHub Actions: `metrics-collector-yml` has bad credentials (and shows it as notification to the reporter)

### ISSUE THREAD

**Issue by debuglevel** [grafana/grafana#80122]
### What happened?

Whenever somebody opens an issue,  `./actions/metrics-collector.yml` will run and fail: https://github.com/grafana/grafana/actions/runs/7444653699

Unfortunately, this sends a notification to the reporter, who cannot do anything about it:
![image](https://github.com/grafana/grafana/assets/2401265/cdf24ece-6a7a-4a73-85fb-0628810801f6)

```
Run ./actions/metrics-collector
  with:
    metricsWriteAPIKey: ***
    token: ***
    configPath: metrics-collector
running  MetricsCollector with context {
  payload: {
    issue: 80118,
    label: undefined,
    repository: 'https://github.com/grafana/grafana',
    sender: 'debuglevel',
    action: 'opened',
    contextIssue: { owner: 'grafana', repo: 'grafana', number: 80118 }
  },
  eventName: 'issues',
  sha: '9cdd519e5357f09b8487147b7700df0d877c0ae8',
  ref: 'refs/heads/main',
  workflow: 'Github issue metrics collection',
  action: '__self',
  actor: 'debuglevel'
}
Constructor OctoKit init
Constructor OctoKit end
trackMetric issue.opened_count 1
tracking metrics: { name: 'octokit_request_count', value: 0 }
trackMetric octokit_request_count 0
/home/runner/work/grafana/grafana/actions/node_modules/@octokit/request/dist-node/index.js:86
      const error = new requestError.RequestError(toErrorMessage(data), status, {
                    ^

RequestError [HttpError]: Bad credentials
    at /home/runner/work/grafana/grafana/actions/node_modules/@octokit/request/dist-node/index.js:86:[2](https://github.com/grafana/grafana/actions/runs/7444547336/job/20251141039#step:4:2)1
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getRateLimit (/home/runner/work/grafana/grafana/actions/common/utils.js:82:24)
    at async MetricsCollector.run (/home/runner/work/grafana/grafana/actions/common/Action.js:66:2[3](https://github.com/grafana/grafana/actions/runs/7444547336/job/20251141039#step:4:3)) {
  status: [4](https://github.com/grafana/grafana/actions/runs/7444547336/job/20251141039#step:4:4)01,
  response: {
    url: 'https://api.github.com/rate_limit',
    status: 401,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      connection: 'close',
      'content-length': '80',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Mon, 08 Jan 2024 07:48:29 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31[5](https://github.com/grafana/grafana/actions/runs/7444547336/job/20251141039#step:4:5)3[6](https://github.com/grafana/grafana/actions/runs/7444547336/job/20251141039#step:4:7)000; includeSubdomains; preload',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': 'F5[7](https://github.com/grafana/grafana/actions/runs/7444547336/job/20251141039#step:4:8)D:5AA6:149A071[8](https://github.com/grafana/grafana/actions/runs/7444547336/job/20251141039#step:4:9):2AD[9](https://github.com/grafana/grafana/actions/runs/7444547336/job/20251141039#step:4:10)A73D:659BA8CD',
      'x-ratelimit-limit': '60',
      'x-ratelimit-remaining': '59',
      'x-ratelimit-reset': '1704703709',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '1',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Bad credentials',
      documentation_url: 'https://docs.github.com/rest'
    }
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/rate_limit',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit.js/[16](https://github.com/grafana/grafana/actions/runs/7444547336/job/20251141039#step:4:17).43.2 Node.js/16.[20](https://github.com/grafana/grafana/actions/runs/7444547336/job/20251141039#step:4:21).2 (Linux 6.2; x[64](https://github.com/grafana/grafana/actions/runs/7444547336/job/20251141039#step:4:65))',
      authorization: 'token [REDACTED]'
    },
    request: { hook: [Function: bound bound register], validate: {} }
  }
}
```

### What did you expect to happen?

No error.

### Did this work before?

I guess.

### How do we reproduce it?

1. Open an issue.

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by marefr** [comment]
Thanks. I think this was fixed by #80795 so going to close it. If not let us know and we'll reopen. 

@ashharrison90 FYI
