### ISSUE TITLE
Session logout: Can't logout user from session

### ISSUE THREAD

**Issue by manuel-hiller-ebm** [grafana/grafana#80125]
### What happened?

If I try to logout from an user session, I get the following error inside my browser window:
![MicrosoftTeams-image](https://github.com/grafana/grafana/assets/129267118/deb23fda-4121-4919-821a-806af32ce724)

Grafana-Log below

### What did you expect to happen?

I expect, that the user session will be closed successfully without any errors.

### Did this work before?

Yes, I tried this on my dev instance with Grafana version 10.1.6 and this worked as expected.

### How do we reproduce it?

1. Login to Grafana instance
2. Try to logout from Grafana instance

### Is the bug inside a dashboard panel?

No, but here is the log from the Grafana server itself, which will be printed outed, if I try to log out:
```
Jan 08 09:43:21 Hostname grafana[1095]:         net/http/server.go:3086 +0x5cb
Jan 08 09:43:21 Hostname grafana[1095]: created by net/http.(*Server).Serve in goroutine 889
Jan 08 09:43:21 Hostname grafana[1095]:         net/http/server.go:2009 +0x5f4
Jan 08 09:43:21 Hostname grafana[1095]: net/http.(*conn).serve(0xc0023f2c60, {0x2161a88, 0xc003268450})
Jan 08 09:43:21 Hostname grafana[1095]:         net/http/server.go:2938 +0x8e
Jan 08 09:43:21 Hostname grafana[1095]: net/http.serverHandler.ServeHTTP({0xc001a9ef30?}, {0x2147830?, 0xc001aa4e00?}, 0x6?)
Jan 08 09:43:21 Hostname grafana[1095]:         github.com/grafana/grafana/pkg/web/macaron.go:163 +0xdd
Jan 08 09:43:21 Hostname grafana[1095]: github.com/grafana/grafana/pkg/web.(*Macaron).ServeHTTP(0xc003036000?, {0x2147830?, 0xc001aa4e00?}, 0xc0020fbf00?)
Jan 08 09:43:21 Hostname grafana[1095]:         github.com/grafana/grafana/pkg/web/router.go:211 +0x1b5
Jan 08 09:43:21 Hostname grafana[1095]: github.com/grafana/grafana/pkg/web.(*Router).ServeHTTP(0xc00301b640, {0x2147830, 0xc001aa4e00}, 0xc0020fbf00)
Jan 08 09:43:21 Hostname grafana[1095]:         github.com/grafana/grafana/pkg/web/router.go:155 +0x14e
Jan 08 09:43:21 Hostname grafana[1095]: github.com/grafana/grafana/pkg/web.(*Router).Handle.func1({0x2147830, 0xc001aa4e00}, 0x14a9a46?, 0xc0022ac4b4?)
Jan 08 09:43:21 Hostname grafana[1095]:         github.com/grafana/grafana/pkg/web/context.go:52 +0xf7
Jan 08 09:43:21 Hostname grafana[1095]: github.com/grafana/grafana/pkg/web.(*Context).run(0xc002873c00)
Jan 08 09:43:21 Hostname grafana[1095]:         net/http/server.go:2136 +0x29
Jan 08 09:43:21 Hostname grafana[1095]: net/http.HandlerFunc.ServeHTTP(0x2113e20?, {0x2148c70?, 0xc00213af50?}, 0xc002ba7920?)
Jan 08 09:43:21 Hostname grafana[1095]:         github.com/grafana/grafana/pkg/middleware/requestmeta/request_metadata.go:66 +0x176
Jan 08 09:43:21 Hostname grafana[1095]: github.com/grafana/grafana/pkg/api.(*HTTPServer).addMiddlewaresAndStaticRoutes.SetupRequestMetadata.func1.1({0x2148c70, 0xc00213a>
Jan 08 09:43:21 Hostname grafana[1095]:         net/http/server.go:2136 +0x29
Jan 08 09:43:21 Hostname grafana[1095]: net/http.HandlerFunc.ServeHTTP(0xc0016ec200?, {0x2148c70?, 0xc00213af50?}, 0x7?)
Jan 08 09:43:21 Hostname grafana[1095]:         github.com/grafana/grafana/pkg/middleware/request_tracing.go:88 +0x416
Jan 08 09:43:21 Hostname grafana[1095]: github.com/grafana/grafana/pkg/api.(*HTTPServer).addMiddlewaresAndStaticRoutes.RequestTracing.func2.1({0x2148c70, 0xc00213af50}, >
Jan 08 09:43:21 Hostname grafana[1095]:         net/http/server.go:2136 +0x29
Jan 08 09:43:21 Hostname grafana[1095]: net/http.HandlerFunc.ServeHTTP(0xc0016ec200?, {0x2148c70?, 0xc00213af50?}, 0xc002d674a0?)
Jan 08 09:43:21 Hostname grafana[1095]:         github.com/grafana/grafana/pkg/middleware/request_metrics.go:83 +0x256
Jan 08 09:43:21 Hostname grafana[1095]: github.com/grafana/grafana/pkg/middleware.RequestMetrics.func1.1({0x2148c70?, 0xc00213af50}, 0xc0016ec700)
Jan 08 09:43:21 Hostname grafana[1095]:         net/http/server.go:2136 +0x29
Jan 08 09:43:21 Hostname grafana[1095]: net/http.HandlerFunc.ServeHTTP(0x0?, {0x2148c70?, 0xc00213af50?}, 0x0?)
Jan 08 09:43:21 Hostname grafana[1095]:         github.com/grafana/grafana/pkg/middleware/loggermw/logger.go:72 +0x5b7
Jan 08 09:43:21 Hostname grafana[1095]: github.com/grafana/grafana/pkg/middleware/loggermw.(*loggerImpl).Middleware.func1.1({0x2148c70?, 0xc00213af50}, 0xc0016ec700)
Jan 08 09:43:21 Hostname grafana[1095]:         net/http/server.go:2136 +0x29
Jan 08 09:43:21 Hostname grafana[1095]: net/http.HandlerFunc.ServeHTTP(0x2161a88?, {0x2148c70?, 0xc00213af50?}, 0x14e7511?)
Jan 08 09:43:21 Hostname grafana[1095]:         github.com/grafana/grafana/pkg/middleware/recovery.go:179 +0xb6
Jan 08 09:43:21 Hostname grafana[1095]: github.com/grafana/grafana/pkg/api.(*HTTPServer).addMiddlewaresAndStaticRoutes.Recovery.func4.1({0x2148c70, 0xc00213af50}, 0xc002>
Jan 08 09:43:21 Hostname grafana[1095]:         net/http/server.go:2136 +0x29
Jan 08 09:43:21 Hostname grafana[1095]: net/http.HandlerFunc.ServeHTTP(0x2161a88?, {0x2148c70?, 0xc00213af50?}, 0x100?)
Jan 08 09:43:21 Hostname grafana[1095]:         github.com/grafana/grafana/pkg/middleware/csrf/csrf.go:66 +0x1fb
Jan 08 09:43:21 Hostname grafana[1095]: github.com/grafana/grafana/pkg/middleware/csrf.(*CSRF).Middleware.func1.1({0x2148c70, 0xc00213af50}, 0xa0f4e40?)
Jan 08 09:43:21 Hostname grafana[1095]:         net/http/server.go:2136 +0x29
Jan 08 09:43:21 Hostname grafana[1095]: net/http.HandlerFunc.ServeHTTP(0xc002d771a0?, {0x2148c70?, 0xc00213af50?}, 0x54343a8?)
Jan 08 09:43:21 Hostname grafana[1095]:         github.com/grafana/grafana/pkg/web/macaron.go:137 +0x1d3
Jan 08 09:43:21 Hostname grafana[1095]: github.com/grafana/grafana/pkg/web.mwFromHandler.func1.1({0x2148c70?, 0xc00213af50?}, 0xc0016ec900)
Jan 08 09:43:21 Hostname grafana[1095]:         net/http/server.go:2136 +0x29
Jan 08 09:43:21 Hostname grafana[1095]: net/http.HandlerFunc.ServeHTTP(0x7fd3a273f108?, {0x2148c70?, 0xc00213af50?}, 0x14b2dbf?)
Jan 08 09:43:21 Hostname grafana[1095]:         github.com/grafana/grafana/pkg/web/macaron.go:137 +0x1d3
Jan 08 09:43:21 Hostname grafana[1095]: github.com/grafana/grafana/pkg/web.mwFromHandler.func1.1({0x2148c70?, 0xc00213af50?}, 0xc0016ec900)
Jan 08 09:43:21 Hostname grafana[1095]:         net/http/server.go:2136 +0x29
Jan 08 09:43:21 Hostname grafana[1095]: net/http.HandlerFunc.ServeHTTP(0x2119260?, {0x2148c70?, 0xc00213af50?}, 0x5545825?)
Jan 08 09:43:21 Hostname grafana[1095]:         github.com/grafana/grafana/pkg/web/macaron.go:137 +0x1d3
Jan 08 09:43:21 Hostname grafana[1095]: github.com/grafana/grafana/pkg/web.mwFromHandler.func1.1({0x2148c70?, 0xc00213af50?}, 0xc0016ec900)
Jan 08 09:43:21 Hostname grafana[1095]:         net/http/server.go:2136 +0x29
Jan 08 09:43:21 Hostname grafana[1095]: net/http.HandlerFunc.ServeHTTP(0x2119260?, {0x2148c70?, 0xc00213af50?}, 0x5545825?)
Jan 08 09:43:21 Hostname grafana[1095]:         github.com/grafana/grafana/pkg/web/macaron.go:137 +0x1d3
Jan 08 09:43:21 Hostname grafana[1095]: github.com/grafana/grafana/pkg/web.mwFromHandler.func1.1({0x2148c70?, 0xc00213af50?}, 0xc0016ec900)
Jan 08 09:43:21 Hostname grafana[1095]:         net/http/server.go:2136 +0x29
Jan 08 09:43:21 Hostname grafana[1095]: net/http.HandlerFunc.ServeHTTP(0x2119260?, {0x2148c70?, 0xc00213af50?}, 0x5545825?)
Jan 08 09:43:21 Hostname grafana[1095]:         github.com/grafana/grafana/pkg/web/render.go:44 +0x21e
Jan 08 09:43:21 Hostname grafana[1095]: github.com/grafana/grafana/pkg/web.Renderer.func1.1({0x2148c70, 0xc00213af50}, 0xc0016ec900)
Jan 08 09:43:21 Hostname grafana[1095]:         net/http/server.go:2136 +0x29
Jan 08 09:43:21 Hostname grafana[1095]: net/http.HandlerFunc.ServeHTTP(0x5422626?, {0x2148c70?, 0xc00213af50?}, 0x20?)
Jan 08 09:43:21 Hostname grafana[1095]:         github.com/grafana/grafana/pkg/web/macaron.go:137 +0x1d3
Jan 08 09:43:21 Hostname grafana[1095]: github.com/grafana/grafana/pkg/web.mwFromHandler.func1.1({0x2148c70?, 0xc00213af50?}, 0xc0016ec900)
Jan 08 09:43:21 Hostname grafana[1095]:         net/http/server.go:2136 +0x29
Jan 08 09:43:21 Hostname grafana[1095]: net/http.HandlerFunc.ServeHTTP(0xc001f44400?, {0x2148c70?, 0xc00213af50?}, 0x5545825?)
Jan 08 09:43:21 Hostname grafana[1095]:         github.com/grafana/grafana/pkg/web/macaron.go:137 +0x1d3
Jan 08 09:43:21 Hostname grafana[1095]: github.com/grafana/grafana/pkg/web.mwFromHandler.func1.1({0x2148c70?, 0xc00213af50?}, 0xc0016ec900)
Jan 08 09:43:21 Hostname grafana[1095]:         net/http/server.go:2136 +0x29
Jan 08 09:43:21 Hostname grafana[1095]: net/http.HandlerFunc.ServeHTTP(0x2148c70?, {0x2148c70?, 0xc00213af50?}, 0x5545825?)
Jan 08 09:43:21 Hostname grafana[1095]:         github.com/grafana/grafana/pkg/web/macaron.go:137 +0x1d3
Jan 08 09:43:21 Hostname grafana[1095]: github.com/grafana/grafana/pkg/web.mwFromHandler.func1.1({0x2148c70?, 0xc00213af50?}, 0xc0016ec900)
Jan 08 09:43:21 Hostname grafana[1095]:         net/http/server.go:2136 +0x29
Jan 08 09:43:21 Hostname grafana[1095]: net/http.HandlerFunc.ServeHTTP(0x2148c70?, {0x2148c70?, 0xc00213af50?}, 0x5545825?)
Jan 08 09:43:21 Hostname grafana[1095]:         github.com/grafana/grafana/pkg/web/macaron.go:137 +0x1d3
Jan 08 09:43:21 Hostname grafana[1095]: github.com/grafana/grafana/pkg/web.mwFromHandler.func1.1({0x2148c70?, 0xc00213af50?}, 0xc0016ec900)
Jan 08 09:43:21 Hostname grafana[1095]:         net/http/server.go:2136 +0x29
Jan 08 09:43:21 Hostname grafana[1095]: net/http.HandlerFunc.ServeHTTP(0x2148c70?, {0x2148c70?, 0xc00213af50?}, 0x5545825?)
Jan 08 09:43:21 Hostname grafana[1095]:         github.com/grafana/grafana/pkg/web/macaron.go:137 +0x1d3
Jan 08 09:43:21 Hostname grafana[1095]: github.com/grafana/grafana/pkg/web.mwFromHandler.func1.1({0x2148c70?, 0xc00213af50?}, 0xc0016ec900)
Jan 08 09:43:21 Hostname grafana[1095]:         net/http/server.go:2136 +0x29
Jan 08 09:43:21 Hostname grafana[1095]: net/http.HandlerFunc.ServeHTTP(0x2148c70?, {0x2148c70?, 0xc00213af50?}, 0x5545825?)
Jan 08 09:43:21 Hostname grafana[1095]:         github.com/grafana/grafana/pkg/services/contexthandler/contexthandler.go:145 +0xbdc
Jan 08 09:43:21 Hostname grafana[1095]: github.com/grafana/grafana/pkg/services/contexthandler.(*ContextHandler).Middleware-fm.(*ContextHandler).Middleware.func1({0x2148>
Jan 08 09:43:21 Hostname grafana[1095]:         net/http/server.go:2136 +0x29
Jan 08 09:43:21 Hostname grafana[1095]: net/http.HandlerFunc.ServeHTTP(0xc001c06900?, {0x2148c70?, 0xc00213af50?}, 0x6?)
Jan 08 09:43:21 Hostname grafana[1095]:         github.com/grafana/grafana/pkg/web/macaron.go:137 +0x1d3
Jan 08 09:43:21 Hostname grafana[1095]: github.com/grafana/grafana/pkg/web.mwFromHandler.func1.1({0x2148c70?, 0xc00213af50?}, 0xc0016ec900)
Jan 08 09:43:21 Hostname grafana[1095]:         net/http/server.go:2136 +0x29
Jan 08 09:43:21 Hostname grafana[1095]: net/http.HandlerFunc.ServeHTTP(0x18?, {0x2148c70?, 0xc00213af50?}, 0xc00107a4f0?)
Jan 08 09:43:21 Hostname grafana[1095]:         github.com/grafana/grafana/pkg/web/macaron.go:137 +0x1d3
Jan 08 09:43:21 Hostname grafana[1095]: github.com/grafana/grafana/pkg/web.mwFromHandler.func1.1({0x2148c70?, 0xc00213af50?}, 0xc0016ec900)
Jan 08 09:43:21 Hostname grafana[1095]:         net/http/server.go:2136 +0x29
Jan 08 09:43:21 Hostname grafana[1095]: net/http.HandlerFunc.ServeHTTP(0x54343a8?, {0x2148c70?, 0xc00213af50?}, 0x5545825?)
Jan 08 09:43:21 Hostname grafana[1095]:         github.com/grafana/grafana/pkg/web/macaron.go:137 +0x1d3
Jan 08 09:43:21 Hostname grafana[1095]: github.com/grafana/grafana/pkg/web.mwFromHandler.func1.1({0x2148c70?, 0xc00213af50?}, 0xc0016ec900)
Jan 08 09:43:21 Hostname grafana[1095]:         net/http/server.go:2136 +0x29
Jan 08 09:43:21 Hostname grafana[1095]: net/http.HandlerFunc.ServeHTTP(0xc001a9ef60?, {0x2148c70?, 0xc00213af50?}, 0x5545825?)
Jan 08 09:43:21 Hostname grafana[1095]:         github.com/grafana/grafana/pkg/extensions/ratelimiting/ratelimiting.go:54 +0x22d
Jan 08 09:43:21 Hostname grafana[1095]: github.com/grafana/grafana/pkg/extensions/ratelimiting.(*HTTPRateLimiting).init.(*HTTPRateLimiting).rateLimitingMiddleware.func1.>
Jan 08 09:43:21 Hostname grafana[1095]:         net/http/server.go:2136 +0x29
Jan 08 09:43:21 Hostname grafana[1095]: net/http.HandlerFunc.ServeHTTP(0xc001a9f860?, {0x2148c70?, 0xc00213af50?}, 0x5d2360?)
Jan 08 09:43:21 Hostname grafana[1095]:         github.com/grafana/grafana/pkg/web/macaron.go:131 +0x12f
Jan 08 09:43:21 Hostname grafana[1095]: github.com/grafana/grafana/pkg/web.mwFromHandler.func1.1({0x2148c70?, 0xc00213af50?}, 0xc0016ecd00)
Jan 08 09:43:21 Hostname grafana[1095]:         net/http/server.go:2136 +0x29
Jan 08 09:43:21 Hostname grafana[1095]: net/http.HandlerFunc.ServeHTTP(0xc003346238?, {0x2148c70?, 0xc00213af50?}, 0x100?)
Jan 08 09:43:21 Hostname grafana[1095]:         github.com/grafana/grafana/pkg/api/response/web_hack.go:40 +0x30
Jan 08 09:43:21 Hostname grafana[1095]: github.com/grafana/grafana/pkg/api/response.wrap_handler.func3({0x2148c70?, 0xc00213af50?}, 0x1005a80?)
Jan 08 09:43:21 Hostname grafana[1095]:         github.com/grafana/grafana/pkg/api/login.go:263 +0x2c2
Jan 08 09:43:21 Hostname grafana[1095]: github.com/grafana/grafana/pkg/api.(*HTTPServer).Logout(0xc001efb800, 0xc001b3c680)
Jan 08 09:43:21 Hostname grafana[1095]:         runtime/panic.go:914 +0x21f
Jan 08 09:43:21 Hostname grafana[1095]: panic({0x9b4be0?, 0xa021670?})
Jan 08 09:43:21 Hostname grafana[1095]:         github.com/grafana/grafana/pkg/middleware/recovery.go:174 +0x668
Jan 08 09:43:21 Hostname grafana[1095]: github.com/grafana/grafana/pkg/api.(*HTTPServer).addMiddlewaresAndStaticRoutes.Recovery.func4.1.1()
Jan 08 09:43:21 Hostname grafana[1095]:         github.com/grafana/grafana/pkg/web/context.go:112 +0x248
Jan 08 09:43:21 Hostname grafana[1095]: github.com/grafana/grafana/pkg/web.(*Context).HTML(0xc002873c00, 0x14d0161?, {0x14ac838, 0x5}, {0x10898a0, 0xc002ee85a0})
Jan 08 09:43:21 Hostname grafana[1095]:         runtime/panic.go:920 +0x270
Jan 08 09:43:21 Hostname grafana[1095]: panic({0x5d2360?, 0xc00107b400?})
Jan 08 09:43:21 Hostname grafana[1095]:         net/http/server.go:1868 +0xb9
Jan 08 09:43:21 Hostname grafana[1095]: net/http.(*conn).serve.func1()
Jan 08 09:43:21 Hostname grafana[1095]: goroutine 55653 [running]:
Jan 08 09:43:21 Hostname grafana[1095]:  template: error:16:35: executing "error" at <.ContentDeliveryURL>: can't evaluate field ContentDeliveryURL in type struct { Titl>
Jan 08 09:43:21 Hostname grafana[1095]: server.go:3214: http: panic serving 10.100.71.113:33114: Context.HTML - Error rendering template: error. You may need to build fr>
Jan 08 09:43:21 Hostname grafana[1095]: logger=context userId=3 orgId=5 uname=Username@domain.local t=2024-01-08T09:43:21.140627614+01:00 level=error msg="Request e>
```

### Environment (with versions)?

Grafana: Grafana-Enterprise 10.2.3
OS: RedHat 9.3
Browser: Microsoft Edge Version 120.0.2210.91

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by weehal** [comment]
the same annoying error

Logout does not work for LDAP users - works perfectly well for local users

```log
logger=context userId=0 orgId=0 uname= t=2024-01-16T20:50:10.079930598Z level=info msg="Request Completed" method=GET path=/ status=302 remote_addr=172.27.xxx.yyy time_ms=0 duration=83.804µs size=29 referer= handler=/
logger=http.server t=2024-01-16T20:50:10.08757151Z level=error msg="Failed to parse user ID" error="identifier is not initialized"
```

**Comment by weehal** [comment]
Seems to be duplicate of #79839

**Comment by usmangt** [comment]
Closing as duplicate of above mentioned issue
