### ISSUE TITLE
Bug: grafana 3.1.1 Error: Invalid dimensions for plot

### ISSUE THREAD

**Issue by eighteen14k** [grafana/grafana#8115]
Please include this information:
> What Grafana version are you using? 3.1.1
> What datasource are you using? InfluxDB 1.2.2
> What OS are you running grafana on? CentOS 6
> What did you do? Changed the selected variable
> What was the expected result? New variable value used
> What happened instead? jserror

                       Error: Invalid dimensions for plot, width = 0, height = 196
   at b.prototype.resize (http://127.0.0.1:3001/public/app/boot.1649cbaa.js:18:24777)
   at b (http://127.0.0.1:3001/public/app/boot.1649cbaa.js:17:26158)
   at t (http://127.0.0.1:3001/public/app/boot.1649cbaa.js:18:1076)
   at c (http://127.0.0.1:3001/public/app/boot.1649cbaa.js:18:24492)
   at a.plot (http://127.0.0.1:3001/public/app/boot.1649cbaa.js:18:27406)
   at m (http://127.0.0.1:3001/public/app/boot.1649cbaa.js:19:11296)
   at o (http://127.0.0.1:3001/public/app/boot.1649cbaa.js:19:12444)
   at Anonymous function (http://127.0.0.1:3001/public/app/boot.1649cbaa.js:19:13240)
   at e.prototype.emit (http://127.0.0.1:3001/public/app/boot.1649cbaa.js:39:22546)
   at a.prototype.emit (http://127.0.0.1:3001/public/app/boot.1649cbaa.js:39:24636)

Now obviously "width = 0" is a problem! But ... *I* never set the width to 0.

If I open up the 'General', "Span" is null, "Min Span" is also null. These are defaults.

If I get in there and set the "Span" & "Min Span", the problem goes away.

So I started out with a single Gauge for one instance.
Then I created a variable (using templating) for the instance to do multi-value.
When I selected the second variable, it all collapsed.
Maybe there are some problems calculating widths for gauges when the number of gauges being presented is determined by "Repeat" in either "General" or "Row Editor"?

**Comment by torkelo** [comment]
this is fixed in later versions of Grafana please upgrade :)
