### ISSUE TITLE
Parca: Potentially flaky test

### ISSUE THREAD

**Issue by fabrizio-grafana** [grafana/grafana#81504]
[In this PR](https://drone.grafana.net/grafana/grafana/157420/1/6), a test in `public/app/plugins/datasource/parca/QueryEditor/QueryEditor.test.tsx` failed. Is it related to the Parca plugin itself and thus something we can address, or is it a general issue with some of the shared code we use?

```
      14 |     setup();
      15 |
    > 16 |     expect(screen.findByText('process_cpu:cpu')).toBeDefined();
         |                   ^
      17 |   });
      18 |
      19 |   it('should render options', async () => {

      at waitForWrapper (node_modules/@testing-library/dom/dist/wait-for.js:163:27)
      at node_modules/@testing-library/dom/dist/query-helpers.js:86:33
      at public/app/plugins/datasource/parca/QueryEditor/QueryEditor.test.tsx:16:19
      at node_modules/tslib/tslib.js:169:75
      at Object.__awaiter (node_modules/tslib/tslib.js:165:16)
      at Object.<anonymous> (public/app/plugins/datasource/parca/QueryEditor/QueryEditor.test.tsx:13:48)
```

**Comment by fabrizio-grafana** [comment]
Today the test was reported again to be flaky, so we should investigate it.
