### ISSUE TITLE
[Bug] Build failure: 

### ISSUE THREAD

**Issue by y-usuzumi** [grafana/grafana#8154]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please prefix your title with [Bug] or [Feature request]. 

Please include this information:
- What Grafana version are you using?
v4.2.0
- What datasource are you using?
N/A
- What OS are you running grafana on?
Gentoo Linux
- What did you do?
Build
- What was the expected result?
Build is successful.
- What happened instead?
```
(bpc)  kj@DCHORUS-OFFICE  ~/Lab/Netis/sources/bpc-x/bpc/appmall/grafana   feature/bohr-4715  npm run build

> grafana@4.2.0 build /home/kj/Lab/Netis/sources/bpc-x/bpc/appmall/grafana
> ./node_modules/grunt-cli/bin/grunt

Version 4.2.0
Running "jscs:src" (jscs) task
Fatal error: The config file ".jscs.json" was not found

npm ERR! Linux 4.10.1-gentoo
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grafana@4.2.0 build: `./node_modules/grunt-cli/bin/grunt`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grafana@4.2.0 build script './node_modules/grunt-cli/bin/grunt'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the grafana package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./node_modules/grunt-cli/bin/grunt
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs grafana
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls grafana
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/kj/.npm/_logs/2017-04-18T07_47_35_391Z-debug.log
```

In 2017-04-18T07_47_35_391Z-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@4.2.0
3 info using node@v7.9.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle grafana@4.2.0~prebuild: grafana@4.2.0
6 silly lifecycle grafana@4.2.0~prebuild: no script for prebuild, continuing
7 info lifecycle grafana@4.2.0~build: grafana@4.2.0
8 verbose lifecycle grafana@4.2.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle grafana@4.2.0~build: PATH: /usr/lib64/node_modules/npm/bin/node-gyp-bin:/home/kj/Lab/Netis/sources/bpc-x/bpc/appmall/grafana/node_modules/.bin:/home/kj/.virtualenvs/bpc/bin:/home/kj/.yarn/bin:/home/kj/.cargo/bin:/home/kj/.local/bin:/home/kj/.cabal/bin:/home/kj/.cargo/bin:/home/kj/.local/bin:/home/kj/.cabal/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/5.4.0:/usr/lib/llvm/4/bin
10 verbose lifecycle grafana@4.2.0~build: CWD: /home/kj/Lab/Netis/sources/bpc-x/bpc/appmall/grafana
11 silly lifecycle grafana@4.2.0~build: Args: [ '-c', './node_modules/grunt-cli/bin/grunt' ]
12 silly lifecycle grafana@4.2.0~build: Returned: code: 1  signal: null
13 info lifecycle grafana@4.2.0~build: Failed to exec build script
14 verbose stack Error: grafana@4.2.0 build: `./node_modules/grunt-cli/bin/grunt`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib64/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib64/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid grafana@4.2.0
16 verbose cwd /home/kj/Lab/Netis/sources/bpc-x/bpc/appmall/grafana
17 error Linux 4.10.1-gentoo
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
19 error node v7.9.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error grafana@4.2.0 build: `./node_modules/grunt-cli/bin/grunt`
23 error Exit status 1
24 error Failed at the grafana@4.2.0 build script './node_modules/grunt-cli/bin/grunt'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the grafana package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     ./node_modules/grunt-cli/bin/grunt
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs grafana
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls grafana
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

Exactly the same result as #6646 (which was closed)

- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by y-usuzumi** [comment]
Sorry, I copied the source code from somewhere else, and missed all dotfiles.
