### ISSUE TITLE
Cannot read property 'length' of null

### ISSUE THREAD

**Issue by guojun1992** [grafana/grafana#8175]
i use grafana and open-falcon

Stack trace:
TypeError: Cannot read property 'length' of null
    at OpenfalconDatasource.translateTime (http://xxxx:3000/public/plugins/fastweb-openfalcon-datasource/datasource.js?bust=1492653522114:151:45)
    at OpenfalconDatasource.query (http://xxxx:3000/public/plugins/fastweb-openfalcon-datasource/datasource.js?bust=1492653522114:25:28)
    at b.issueQueries (http://xxx:3000/public/app/boot.5ee7468a.js:46:17534)
    at b.issueQueries (http://xxxx:3000/public/app/boot.5ee7468a.js:19:6248)
    at i (http://xxx:3000/public/app/boot.5ee7468a.js:42:21962)
    at http://xxxx:3000/public/app/boot.5ee7468a.js:42:22384
    at o.$eval (http://xxx:3000/public/app/boot.5ee7468a.js:42:29539)
    at o.$digest (http://xxxx:3000/public/app/boot.5ee7468a.js:42:28012)
    at b.$apply (http://xxxx:3000/public/app/boot.5ee7468a.js:42:29822)
    at HTMLAnchorElement.<anonymous> (http://xxxx:3000/public/app/boot.5ee7468a.js:45:4868)

**Comment by torkelo** [comment]
please contact the plugin authors

**Comment by lwgarmstrong** [comment]
open-falcon的grafana plugin最新版已经修复了这个bug

**Comment by cnm4ak** [comment]
哪里修复的？。。。。

**Comment by yochji520** [comment]
哪里修复的？

**Comment by cypctlinux** [comment]
啥时候修复的

**Comment by lizhongyi2008** [comment]
https://github.com/open-falcon/grafana-openfalcon-datasource.git

使用open-falcon 的插件
