### ISSUE TITLE
Bug: Elasticsearch Metric queries using Template vars that return no values cause parse exceptions in ES

### ISSUE THREAD

**Issue by gbourke** [grafana/grafana#8179]
- What Grafana version are you using? 
**Grafana v4.2.0 (commit: 349f3eb93)**

- What datasource are you using?
**Elasticsearch (ES v5.2.0)**

- What OS are you running grafana on?
**Windows 7 Professional (SP1)**
	
- What did you do?

Added Elastic Search Datasource + various dashboards, panels (Graphs, Singestats, RAW JSON docs, etc.) All working as expected

On several dashboards, defined template variables such as
Template: Name: "environments" - Query {"find": "terms", "field": "event.report.environment.keyword"}, Refresh: "On Dashboard load"

In the Panel -> Graph->  Metrics, defined Query such as the following (referencing two template variables in this case):

Query: event.report.environment.keyword: $environments AND event.report.app.name.keyword: $applications

- What was the expected result?
The above all works fine when the template variables (backend ES query return values), an _msearch query is executed and the templated query executes correctly and the "Repeat Panel" option generates multiple graphs per template variable value

- What happened instead?
If a time period is selected, where either of the template variables return no values, Grafana appears to generate an ES query syntax which causes the backend ES to generate an exception per shard (in this case ~180 shards) - so the ES console throws 180 stack traces, exceptions

The issues appears to be the following:

POST 
http://localhost:4200/api/datasources/proxy/1/_msearch [HTTP/1.1 200 OK 419ms]
{"search_type":"query_then_fetch","ignore_unavailable":true,"index":"dev"}\n{"size":0,"query":{"bool":{"filter":[{"range":{"event.report.timestamp":{"gte":"1492673157304","lte":"1492694757304","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"event.report.environment.keyword: () AND event.report.app.name.keyword: (\\"Value1\\" OR \\"Value2\\")"}}]}},"aggs":{"3":{"terms":{"field":"event.report.app.name.keyword","size":10,"order":{"_term":"asc"},"min_doc_count":0},"aggs":{"2":{"date_histogram":{"interval":"1h","field":"event.report.timestamp","min_doc_count":0,"extended_bounds":{"min":"1492673157304","max":"1492694757304"},"format":"epoch_millis"},"aggs":{}}}}}}\n

The empty brackets after the first field name (event.report.environment.keyword) cause parse exception(s) in ES:

**"query" : "event.report.environment.keyword: () AND event.report.app.name.keyword: (\"Value1\" OR \"Value2\")",**

When both template vars have valid values, the queries execute fine.

This results in the following console error (in Firefox)

Panel data error: Object { data: "{
    "root_cause": [
        {
            "type": "parse_exception",
            "reason": "parse_exception: Encountered \" \")\" \") \"\" at line 1, column 35.\r\nWas expecting one of:\r\n    <NOT> ...\r\n    \"+\" ...\r\n    \"-\" ...\r\n    <BAREOPER> ...\r\n    \"(\" ...\r\n    \"*\" ...\r\n    <QUOTED> ...\r\n    <TERM> ...\r\n    <PREFIXTERM> ...\r\n    <WILDTERM> ...\r\n    <REGEXPTERM> ...\r\n    \"[\" ...\r\n    \"{\" ...\r\n    <NUMBER> ...\r\n    <TERM> ...\r\n    "
        },
        {
            "type": "query_shard_exception",
            "reason": "Failed to parse query [event.report.environment.keyword: () AND event.report.app.name.keyword: (\"Value1\" OR \"Value2\")]",
            "index_uuid": "BuryXuKjS1CqgDiJzTOcYQ",
            "index": "dev-2017-01-02"
        },
        {
            "type": "query_shard_exception",
            "reason": "Failed to parse query [event.report.environment.keyword: () AND event.report.app.name.keyword: (\"Valu"[…], message: "parse_exception: Encountered " ")" …", config: Object }  
boot.js:46:15299

====

The corresponding backend ES exceptions are as follows:			
			
[2017-04-20T14:26:44,392][DEBUG][o.e.a.s.TransportSearchAction] [node1] [dev-2017-01-12][1], node[vT2GiSnUmdQ8t1w],
PAhSRWyad56mvPa-Q]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[dev], indicesOptions=IndicesOptions[id=39, ig
w_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_alisases_to_multiple_indices=true, forbid_closed_indices=tr
l', preference='null', requestCache=null, scroll=null, source={
  "size" : 0,
  "query" : {
    "bool" : {
      "filter" : [
        {
          "range" : {
            "event.report.timestamp" : {
              "from" : "1492673157304",
              "to" : "1492694757304",
              "include_lower" : true,
              "include_upper" : true,
              "format" : "epoch_millis",
              "boost" : 1.0
            }
          }
        },
        {
          "query_string" : {
            "query" : "event.report.environment.keyword: () AND event.report.app.name.keyword: (\"Value1\" OR \"Value2\")",
            "fields" : [ ],
            "use_dis_max" : true,
            "tie_breaker" : 0.0,
            "default_operator" : "or",
            "auto_generate_phrase_queries" : false,
            "max_determined_states" : 10000,
            "enable_position_increment" : true,
            "fuzziness" : "AUTO",
            "fuzzy_prefix_length" : 0,
            "fuzzy_max_expansions" : 50,
            "phrase_slop" : 0,
            "analyze_wildcard" : true,
            "escape" : false,
            "split_on_whitespace" : true,
            "boost" : 1.0
          }
        }
      ],
      "disable_coord" : false,
      "adjust_pure_negative" : true,
      "boost" : 1.0
    }
	
org.elasticsearch.transport.RemoteTransportException: [DUB8538W7DT-jbeckett][10.32.0.89:5348][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.index.query.QueryShardException: Failed to parse query [event.report.environment.keyword: () AND event.report.app.name.keyword: ("Value1" OR "Value2")]
        at org.elasticsearch.index.query.QueryStringQueryBuilder.doToQuery(QueryStringQueryBuilder.java:1034) ~[elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:97) ~[elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toFilter(AbstractQueryBuilder.java:119) ~[elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:446) ~[elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:419) ~[elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:97) ~[elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$1(QueryShardContext.java:312) ~[elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:329) ~[elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:311) ~[elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:671) ~[elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:540) ~[elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:516) ~[elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:251) ~[elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:298) ~[elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:295) ~[elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1488) ~[elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:596) ~[elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.2.0.jar:5.2.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_121]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper: parse_exception: Cannot parse 'event.report.environment.keyword: () AND event.report.app.name.keyword: ("Value1" OR "Value2")': Encountered " ")" ") "" at line 1, column 35.
Was expecting one of:
    <NOT> ...
    "+" ...
    "-" ...
    <BAREOPER> ...
    "(" ...
    "*" ...
    <QUOTED> ...
    <TERM> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    <REGEXPTERM> ...
    "[" ...
    "{" ...
    <NUMBER> ...
    <TERM> ...

**Comment by torkelo** [comment]
event.report.environment.keyword: $environments AND event.report.app.name.keyword: $applications

This is not going to be a valid query if $environments has no values, not much Grafana can do here.

**Comment by torkelo** [comment]
or do you have have an idea for how those variables should be interpolated to generate a valid lucene query when there is no values?
