### ISSUE TITLE
Docker Build: Cannot run `make build-docker-full` on ubuntu

### ISSUE THREAD

**Issue by Umaaz** [grafana/grafana#83222]
### What happened?

With a fresh checkout if I try to build the docker image, the build fails on the step `yarn install --immutable`. Running this outside of docker it works fine.

I added `--inline-builds` to the command in the docker image to get the errors from the build. Below is the logs. It looks like python is needed for the build.

```
82.08 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! find Python 
82.09 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! find Python Python is not set from command line or npm configuration
82.09 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! find Python Python is not set from environment variable PYTHON
82.09 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! find Python checking if "python3" can be used
82.09 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! find Python - "python3" is not in PATH or produced an error
82.09 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! find Python checking if "python" can be used
82.09 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! find Python - "python" is not in PATH or produced an error
82.09 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! find Python 
82.09 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! find Python **********************************************************
82.10 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! find Python You need to install the latest version of Python.
82.10 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
82.10 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! find Python you can try one of the following options:
82.10 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
82.10 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! find Python   (accepted by both node-gyp and npm)
82.10 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! find Python - Set the environment variable PYTHON
82.10 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! find Python - Set the npm configuration variable python:
82.10 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
82.10 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! find Python For more information consult the documentation at:
82.10 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
82.10 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! find Python **********************************************************
82.10 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! find Python 
82.10 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! configure error 
82.10 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! stack Error: Could not find any Python installation to use
82.10 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! stack     at PythonFinder.fail (/tmp/grafana/node_modules/node-gyp/lib/find-python.js:330:47)
82.10 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! stack     at PythonFinder.runChecks (/tmp/grafana/node_modules/node-gyp/lib/find-python.js:159:21)
82.10 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! stack     at PythonFinder.<anonymous> (/tmp/grafana/node_modules/node-gyp/lib/find-python.js:202:16)
82.10 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! stack     at PythonFinder.execFileCallback (/tmp/grafana/node_modules/node-gyp/lib/find-python.js:294:16)
82.10 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! stack     at exithandler (node:child_process:430:5)
82.10 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:442:5)
82.10 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! stack     at ChildProcess.emit (node:events:518:28)
82.10 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
82.10 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! stack     at onErrorNT (node:internal/child_process:484:16)
82.10 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
82.10 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! System Linux 6.5.0-18-generic
82.10 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! command "/usr/local/bin/node" "/tmp/grafana/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/tmp/grafana/node_modules/@esfx/equatable/dist/node/Release/node-v115-linux-x64/hashCodeNative.node" "--module_name=hashCodeNative" "--module_path=/tmp/grafana/node_modules/@esfx/equatable/dist/node/Release/node-v115-linux-x64" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v115"
82.10 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! cwd /tmp/grafana/node_modules/@esfx/equatable
82.10 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! node -v v20.11.1
82.10 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! node-gyp -v v8.3.0
82.10 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! not ok 
82.11 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR node-pre-gyp ERR! build error 
82.11 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /tmp/grafana/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/tmp/grafana/node_modules/@esfx/equatable/dist/node/Release/node-v115-linux-x64/hashCodeNative.node --module_name=hashCodeNative --module_path=/tmp/grafana/node_modules/@esfx/equatable/dist/node/Release/node-v115-linux-x64 --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115' (1)
82.11 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/tmp/grafana/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
82.11 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:518:28)
82.11 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
82.11 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
82.11 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR node-pre-gyp ERR! System Linux 6.5.0-18-generic
82.11 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR node-pre-gyp ERR! command "/usr/local/bin/node" "/tmp/grafana/node_modules/@mapbox/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
82.11 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR node-pre-gyp ERR! cwd /tmp/grafana/node_modules/@esfx/equatable
82.11 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR node-pre-gyp ERR! node -v v20.11.1
82.11 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR node-pre-gyp ERR! node-pre-gyp -v v1.0.11
82.11 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR node-pre-gyp ERR! not ok 
```

### What did you expect to happen?

A usage docker image to be built.

### Did this work before?

Yes, in an earlier version of Grafana I have built this image. (some where around the release of Grafana 10)

### How do we reproduce it?

1. run `make build-docker-full` or `make build-docker-full-ubuntu`

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: main
OS: ubuntu

### Grafana platform?

Docker

**Comment by Umaaz** [comment]
I tried changing the image used for the build to `nikolaik/python-nodejs:python3.12-nodejs20-alpine` and this results in `not found: make`

```
 @esfx/equatable@npm:1.0.2 STDERR gyp ERR! build error 
110.2 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! stack Error: not found: make
110.2 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! stack     at getNotFoundError (/tmp/grafana/node_modules/which/which.js:10:17)
110.2 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! stack     at /tmp/grafana/node_modules/which/which.js:57:18
110.2 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! stack     at new Promise (<anonymous>)
110.2 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! stack     at step (/tmp/grafana/node_modules/which/which.js:54:21)
110.2 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! stack     at /tmp/grafana/node_modules/which/which.js:71:22
110.2 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! stack     at new Promise (<anonymous>)
110.2 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! stack     at subStep (/tmp/grafana/node_modules/which/which.js:69:33)
110.2 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! stack     at /tmp/grafana/node_modules/which/which.js:80:22
110.2 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! stack     at /tmp/grafana/node_modules/isexe/index.js:42:5
110.2 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! stack     at /tmp/grafana/node_modules/isexe/mode.js:8:5
110.2 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! System Linux 6.5.0-18-generic
```

**Comment by Umaaz** [comment]
After a number of attempts, it seems that `@esfx/equatable` needs make, python and gcc to build. I added these with apk to the JS build image.

`RUN apk add --no-cache make build-base python3`

This seems to fix the build for me.
