### ISSUE TITLE
NodeGraph: Flaky transient dependency

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#83318]
As part of this https://github.com/grafana/grafana/pull/78957 a new [library](https://github.com/microsoft/msagljs) was added which depends on `@esfx/equatable` which needs to be built from source because of:

```
YN0000: │ @esfx/equatable@npm:1.0.2 STDERR node-pre-gyp ERR! install response status 404 Not Found on https://github.com/esfx/esfx/releases/download/v1.0.2/hashCodeNative-v1.0.2-node-v115-linux-x64.tar.gz 

➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR node-pre-gyp WARN Pre-built binaries not installable for @esfx/equatable@1.0.2 and node@20.9.0 (node-v115 ABI, musl) (falling back to source compile with node-gyp) 
``` 

The build then requires some `https://unofficial-builds.nodejs.org/download/release/v20.9.0/node-v20.9.0-headers.tar.gz` which for one seems to be a bit less stable and sometimes fails and second, it's not great to depend on something like that for our build in case the whole `unofficial-builds.nodejs.org` goes away at some point.
```
➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! stack FetchError: request to https://unofficial-builds.nodejs.org/download/release/v20.9.0/node-v20.9.0-headers.tar.gz failed, reason: connect ECONNREFUSED 45.55.98.129:443
```

The `@esfx/equatable` seems to be used just for comparing objects and efficiency reasons so maybe we could remove it either by trying to contribute or forking the library.

**Comment by aocenas** [comment]
Recently there is also issue with building the dependency:
```
YN0000: │ @esfx/equatable@npm:1.0.2 STDOUT make: Entering directory '/drone/src/node_modules/@esfx/equatable/build'
➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDOUT   CXX(target) Release/obj.target/hashCodeNative/lib/hashCodeNative.o
➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR In file included from ../lib/hashCodeNative.h:5,
➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR                  from ../lib/hashCodeNative.cpp:1:
➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR /root/.cache/node-gyp/20.9.0/include/node/node.h:1170:7: warning: cast between incompatible function types from 'void (*)(v8::Local<v8::Object>)' to 'node::addon_register_func' {aka 'void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)'} [-Wcast-function-type]
➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR  1170 |       (node::addon_register_func) (regfunc),                          \
➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR       |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR /root/.cache/node-gyp/20.9.0/include/node/node.h:1204:3: note: in expansion of macro 'NODE_MODULE_X'
➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR  1204 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR       |   ^~~~~~~~~~~~~
➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR ../lib/hashCodeNative.cpp:99:1: note: in expansion of macro 'NODE_MODULE'
➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR    99 | NODE_MODULE(NODE_GYP_MODULE_NAME, Init)
➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR       | ^~~~~~~~~~~
➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDOUT   SOLINK_MODULE(target) Release/obj.target/hashCodeNative.node
➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDOUT   COPY Release/hashCodeNative.node
➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDOUT   COPY /drone/src/node_modules/@esfx/equatable/dist/node/Release/node-v115-linux-x64/hashCodeNative.node
➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDOUT   TOUCH Release/obj.target/action_after_build.stamp
➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDOUT make: Leaving directory '/drone/src/node_modules/@esfx/equatable/build'
```

**Comment by hiepqdinh** [comment]
Will this fix (removing msagl) be back-ported to `v10.4.x`? We started seeing this same error today when building grafana for v10.4.1

**Comment by levnach** [comment]
I started removing the dependency on esfx. It was just convenient to use for faster porting from C#.

**Comment by hiepqdinh** [comment]
> Will this fix (removing msagl) be back-ported to `v10.4.x`? We started seeing this same error today when building grafana for v10.4.1

So I compared the success build (before 1pm PT 05/22/2024) and the failed build (after 1pm PT 05/22/2024), and found out that the `node:20-alpine` docker image was changed earlier on the day from alpine-3.18 to alpine-3.20 https://github.com/nodejs/docker-node/commits/1810f76d762c8b080ab6aec585d66fb0f7f1d4a9/20/alpine3.20/Dockerfile 

My log OTOH shows that it was using alpine-3.19 though ¯\\\_(ツ)_/¯

So My local fix is to change [this line](https://github.com/grafana/grafana/blob/0ffc4c441b46756fb887ac8f08a6601cc9ebc4d8/Dockerfile#L4) in the `Dockerfile` from

```
ARG JS_IMAGE=node:20-alpine
```
to
```
ARG JS_IMAGE=node:20-alpine3.19
```

and my build (of 10.4.1) went through successfully!

**Comment by aocenas** [comment]
@levnach 
So there are few options that are a bit hard to estimate cost-vise:
1. try to make the CI less flaky. We could cache the build, use our own registry, or somehow vendor everything. This has some long term maintenance costs though and I would like to prevent adding more complexity to the CI. Not sure about vendoring if a native module is involved tbh.
2. Try to remove the esfx dependency from msagl either in the main repo or as our fork. Again having a separate fork has some long term costs I would like to avoid if possible.
3. Try to pick another library for this but that is surprisingly problematic. The algorithm used for layered layout in Graphviz seems to have the best results, problem is Graphviz itself has a license we cannot easily use and seems like there aren't many libraries that would try to reimplement it. Lot of JS libraries that claim so just use a Graphviz compiled to JS which poses the same licensing problems.

**Comment by aocenas** [comment]
> I started removing the dependency on esfx. It was just convenient to use for faster porting from C#.

So yeah this would be amazing, for us at least this would be the best case scenario.

**Comment by aocenas** [comment]
@hiepqdinh honestly no idea why it does not work in `node:20-alpine` all of a sudden. Again I would say all the build problems are fixable, but having something that is this sensitive to any change in the CI is itself problematic, more so as there are different teams maintaining the CI vs front end team maintaining the visualization using this which creates additional cost to fixing such issues.

**Comment by hiepqdinh** [comment]
> @hiepqdinh honestly no idea why it does not work in `node:20-alpine` all of a sudden. Again I would say all the build problems are fixable, but having something that is this sensitive to any change in the CI is itself problematic, more so as there are different teams maintaining the CI vs front end team maintaining the visualization using this which creates additional cost to fixing such issues.

@aocenas : The newer image of `node:20-alpine` switched to `alpine-3.20` like I mentioned in my previous post, it uses `python3.12.3-r1` which explicitly removes`distutils` [py3.12.3 changelog](https://docs.python.org/3/whatsnew/changelog.html#python-3-12-3-final) that causes compilation failure when building esfx from source (see below).`alpine-3.19` uses `py3.11.9-r0` according what I saw in my success build.

Here is the failure complaining about missing `distutils` FWIW.

```
#22 46.41 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR Traceback (most recent call last):
#22 46.41 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR   File "/tmp/grafana/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
#22 46.41 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR     import gyp  # noqa: E402
#22 46.41 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR     ^^^^^^^^^^
#22 46.41 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR   File "/tmp/grafana/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
#22 46.41 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR     import gyp.input
#22 46.41 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR   File "/tmp/grafana/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
#22 46.41 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR     from distutils.version import StrictVersion
#22 46.41 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR ModuleNotFoundError: No module named 'distutils'
#22 46.42 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! configure error 
#22 46.42 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! stack Error: `gyp` failed with exit code: 1
#22 46.42 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! stack     at ChildProcess.onCpExit (/tmp/grafana/node_modules/node-gyp/lib/configure.js:261:16)
#22 46.42 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! stack     at ChildProcess.emit (node:events:519:28)
#22 46.42 ➤ YN0000: │ @esfx/equatable@npm:1.0.2 STDERR gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
```

@levnach would you mind linking the PR that removed esfx? Is it back ported to previous versions (10.4.x)?

**Comment by levnach** [comment]
There is no PR. There is a bunch of commits: the last one is https://github.com/microsoft/msagljs/commit/06263c9ff87d3d818381267d940e9b172039f221.
I published @msagl/core@1.1.19 a couple of days ago that does not depend on esfx.
