### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'toLowerCase')

### ISSUE THREAD

**Issue by DeepakDonde-GWL** [grafana/grafana#83515]
### What happened?

I tried to add query using `Home->Explore` and faced below issue:
`TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at c (http://localhost:3000/public/build/1727.281a1e1cd15ef0881fa6.js:2:13549)
    at div
    at http://localhost:3000/public/build/8378.36d9cd16557e09d3c339.js:211:49620
    at div
    at B (http://localhost:3000/public/build/1727.281a1e1cd15ef0881fa6.js:2:13178)
    at http://localhost:3000/public/build/1697.ba74e2de8c65e37f1de4.js:87:11436
    at ia (http://localhost:3000/public/build/1697.ba74e2de8c65e37f1de4.js:87:13279)
    at div
    at m (http://localhost:3000/public/build/9733.976a8afd1c8ec137399a.js:26:25711)
    at u (http://localhost:3000/public/build/9733.976a8afd1c8ec137399a.js:26:23378)
    at http://localhost:3000/public/build/1697.ba74e2de8c65e37f1de4.js:98:4683
    at Ta (http://localhost:3000/public/build/1697.ba74e2de8c65e37f1de4.js:98:6910)
    at i (http://localhost:3000/public/build/8378.36d9cd16557e09d3c339.js:1:172)
    at o (http://localhost:3000/public/build/8378.36d9cd16557e09d3c339.js:192:118841)
    at g (http://localhost:3000/public/build/8378.36d9cd16557e09d3c339.js:192:119350)
    at div
    at div
    at div
    at fs (http://localhost:3000/public/build/9733.976a8afd1c8ec137399a.js:124:25127)
    at It (http://localhost:3000/public/build/9733.976a8afd1c8ec137399a.js:187:4993)
    at za (http://localhost:3000/public/build/9733.976a8afd1c8ec137399a.js:124:29667)
    at Rs (http://localhost:3000/public/build/9733.976a8afd1c8ec137399a.js:124:29797)
    at E (http://localhost:3000/public/build/8378.36d9cd16557e09d3c339.js:425:68)
    at div
    at K (http://localhost:3000/public/build/8378.36d9cd16557e09d3c339.js:4108:820)
    at div
    at mu (http://localhost:3000/public/build/9733.976a8afd1c8ec137399a.js:124:30083)
    at It (http://localhost:3000/public/build/9733.976a8afd1c8ec137399a.js:187:4993)
    at y (http://localhost:3000/public/build/9733.976a8afd1c8ec137399a.js:187:2689)
    at Xo (http://localhost:3000/public/build/9733.976a8afd1c8ec137399a.js:124:12772)
    at ft (http://localhost:3000/public/build/9733.976a8afd1c8ec137399a.js:66:950)`

### What did you expect to happen?

I expect to query should get added successfully

### Did this work before?

I am trying grafana for the first time

### How do we reproduce it?

1. Navigate to Home-> Explore
2.Click on Add Query
3.Select Metric

### Environment (with versions)?

Grafana:10.3
OS:Ubuntu
Browser:Chrome

### Grafana platform?

Docker

### Datasource(s)?

Prometheus

**Comment by itsmylife** [comment]
Hi @DeepakDonde-GWL Thanks for reporting the issue. The issue might be related to https://github.com/prometheus/prometheus/pull/13633 
If you are using Prometheus `v2.50.0`, could you please upgrade it to `v2.50.1` and clear the browser cache and try again? 

Related issue: https://github.com/grafana/grafana/issues/80185

**Comment by DeepakDonde-GWL** [comment]
@itsmylife I have updated prometheus. Below are the details:
```
prometheus, version 2.50.1 (branch: HEAD, revision: 8c9b0285360a0b6288d76214a75ce3025bce4050)
  build user:       root@6213bb3ee580
  build date:       20240226-11:36:26
  go version:       go1.21.7
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

But still having the same issue on grafana.
![image](https://github.com/grafana/grafana/assets/144044671/328e2528-f6b0-4436-85b3-5550942a156c)

Should I restart grafana container?

**Comment by deepak-donde** [comment]
update: I restarted grafana but still same error

**Comment by amatochristopher** [comment]
@deepak-donde - After updating Prometheus you will need to clear the cache in your browser. Doing this fixed the issue for me.

**Comment by itsmylife** [comment]
@deepak-donde What do you get when you request the metadata from Prometheus? 

https://prometheus.io/docs/prometheus/latest/querying/api/#querying-metric-metadata

```
$ curl -G http://localhost:9090/api/v1/metadata?limit=5
```

**Comment by PixiBixi** [comment]
Hi! Have the same issues as statued earlier.

There's the output of the API call. 

```
{"status":"success","data":{"kube_statefulset_replicas":[{"type":"gauge","unit":"","help":"[STABLE] Number of desired pods for a StatefulSet."}],"mysql_global_status_innodb_system_rows_read":[{"type":"unknown","unit":"","help":"Generic metric from SHOW GLOBAL STATUS."}],"node_time_clocksource_available_info":[{"type":"gauge","unit":"","help":"Available clocksources read from '/sys/devices/system/clocksource'."}],"prometheus_rule_group_last_evaluation_samples":[{"type":"gauge","unit":"","help":"The number of samples returned during the last rule group evaluation."}],"redis_migrate_cached_sockets_total":[{"type":"gauge","unit":"","help":"migrate_cached_sockets_total metric"}]}}
```

* Prometheus upgraded to 2.50.1
* Grafana upgraded to 10.3.1

**Comment by deepak-donde** [comment]
@itsmylife I no longer facing this issue. Checked this after 5 days.

PFB Prometheus metadata:

`{
  "status": "success",
  "data": {
    "node_hwmon_in_min_volts": [
      {
        "type": "gauge",
        "unit": "",
        "help": "Hardware monitor for voltage (min)"
      }
    ],
    "node_memory_VmallocChunk_bytes": [
      {
        "type": "gauge",
        "unit": "",
        "help": "Memory information field VmallocChunk_bytes."
      }
    ],
    "node_network_dormant": [
      {
        "type": "gauge",
        "unit": "",
        "help": "Network device property: dormant"
      }
    ],
    "prometheus_tsdb_exemplar_last_exemplars_timestamp_seconds": [
      {
        "type": "gauge",
        "unit": "",
        "help": "The timestamp of the oldest exemplar stored in circular storage. Useful to check for what timerange the current exemplar buffer limit allows. This usually means the last timestampfor all exemplars for a typical setup. This is not true though if one of the series timestamp is in future compared to rest series."
      }
    ],
    "prometheus_tsdb_wal_segment_current": [
      {
        "type": "gauge",
        "unit": "",
        "help": "Write log segment index that TSDB is currently writing to."
      }
    ]
  }
}`
