### ISSUE TITLE
Cannot visualize Geomap Markers from redis data

### ISSUE THREAD

**Issue by antonrv** [grafana/grafana#85049]
### What happened?

I'm trying to visualize geographical points (latitude and longitude) fetched from a redis data source using Geomap.

In the table view I can see that it successfully fetches the data (three colums, first a Timestamp typed 'time', then two columns 'Latitude' and 'Longitude' typed 'number', which can then be correctly visualized with Time series.

Also the dynamic time range works fine, only showing the data when the date range encompass such data.

However, when trying to plot these geo coordinates in Geomap, there is a bug:

Geomap -> Map layers -> Add layer -> click on Markers -> nothing happens
upon inspection of browse console: 

"
location.ts:33 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at Object.latitude (location.ts:33:32)
    at d (location.ts:130:32)
    at h (location.ts:172:18)
    at nn.update (frameVectorSource.ts:18:18)
    at Object.update (markersLayer.tsx:138:18)
    at tr (layers.ts:29:13)
    at Kn (layers.ts:152:3)
"

Of course no data is being visualized either, despite data exists in the table view.

### What did you expect to happen?

To actually show the Markers options and eventually something to be visualized with such markers configuration.

### Did this work before?

no

### How do we reproduce it?

1. load redis time series with two time series with key "Latitude" and "Longitude", with timestamps in milliseconds
2. In grafana, fetch data with two queries (RedisTimeSeries with command TS.RANGE on key Latitude and on key Longitude), then transformed with "Join by field", mode Outer (Time series) Field: time.
3. Geomap -> Map layers -> Add layer -> click on Markers -> see nothing happens, and an error in the browser console is reported

### Environment (with versions)?

Grafana: 10.4.1
OS: ubuntu 20.04
Browser: both chrome  122.0.6261.94 and firefox 124.0

### Grafana platform?

Docker

### Datasource(s)?

redis-datasource

**Comment by adela-almasan** [comment]
Hi @antonrv - thank you for submitting this issue! It would be super helpful if you could [provide a debug panel dashboard](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/).
