### ISSUE TITLE
Flaky test: `public/app/features/explore/spec/queryHistory.test.tsx`

### ISSUE THREAD

**Issue by fabrizio-grafana** [grafana/grafana#86287]
```
FAIL public/app/features/explore/spec/queryHistory.test.tsx (45.87 s)
  ● Explore: Query History › adds recently added query if the query history panel is already open

    Expected test not to call console.error().

    If the error is expected, test for it explicitly by mocking it out using jest.spyOn(console, 'error').mockImplementation() and test that the warning occurs.

    Error: Uncaught [TypeError: Cannot read properties of undefined (reading 'get')]

      41 |         }
      42 |
    > 43 |         return getDataSourceSrv().get(pane.datasource);
         |                                  ^
      44 |       })
      45 |     )
      46 |       .then((results) => results.filter(isFulfilled).map((result) => result.value))

      at reportException (node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:353:9)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:286:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:233:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:104:17)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:241:34)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:4213:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:4277:31)
      at reportUncaughtErrorInDEV (node_modules/react-dom/cjs/react-dom.development.js:22838:5)
      at captureCommitPhaseError (node_modules/react-dom/cjs/react-dom.development.js:27126:5)
      at commitPassiveMountEffects_complete (node_modules/react-dom/cjs/react-dom.development.js:24893:9)
      at commitPassiveMountEffects_begin (node_modules/react-dom/cjs/react-dom.development.js:24878:7)
      at commitPassiveMountEffects (node_modules/react-dom/cjs/react-dom.development.js:24866:3)
      at flushPassiveEffectsImpl (node_modules/react-dom/cjs/react-dom.development.js:27039:3)
      at flushPassiveEffects (node_modules/react-dom/cjs/react-dom.development.js:26984:14)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:26076:3)
      at flushSyncCallbacks (node_modules/react-dom/cjs/react-dom.development.js:12042:22)
      at flushSync (node_modules/react-dom/cjs/react-dom.development.js:26201:7)
      at ReactDOMRoot.Object.<anonymous>.ReactDOMHydrationRoot.unmount.ReactDOMRoot.unmount [as unmount] (node_modules/react-dom/cjs/react-dom.development.js:29336:5)
      at Object.unmount (node_modules/@testing-library/react/dist/pure.js:155:12)
      at node_modules/@testing-library/react/dist/pure.js:286:12
      at node_modules/@testing-library/react/dist/act-compat.js:48:24
      at act (node_modules/react/cjs/react.development.js:2512:16)
      at node_modules/@testing-library/react/dist/act-compat.js:47:25
      at node_modules/@testing-library/react/dist/pure.js:285:28
          at Array.forEach (<anonymous>)
      at cleanup (node_modules/@testing-library/react/dist/pure.js:281:22)
      at Object.<anonymous> (node_modules/@testing-library/react/dist/index.js:28:25)
        detail: TypeError: Cannot read properties of undefined (reading 'get')
      at public/app/features/explore/hooks/useExplorePageTitle.ts:43:34
            at Array.map (<anonymous>)
      at public/app/features/explore/hooks/useExplorePageTitle.ts:32:34
      at commitHookEffectListMount (node_modules/react-dom/cjs/react-dom.development.js:23150:26)
      at commitPassiveMountOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24931:11)
      at commitPassiveMountEffects_complete (node_modules/react-dom/cjs/react-dom.development.js:24891:9)
      at commitPassiveMountEffects_begin (node_modules/react-dom/cjs/react-dom.development.js:24878:7)
      at commitPassiveMountEffects (node_modules/react-dom/cjs/react-dom.development.js:24866:3)
      at flushPassiveEffectsImpl (node_modules/react-dom/cjs/react-dom.development.js:27039:3)
      at flushPassiveEffects (node_modules/react-dom/cjs/react-dom.development.js:26984:14)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:26076:3)
      at flushSyncCallbacks (node_modules/react-dom/cjs/react-dom.development.js:12042:22)
      at flushSync (node_modules/react-dom/cjs/react-dom.development.js:26201:7)
      at ReactDOMRoot.Object.<anonymous>.ReactDOMHydrationRoot.unmount.ReactDOMRoot.unmount [as unmount] (node_modules/react-dom/cjs/react-dom.development.js:29336:5)
      at Object.unmount (node_modules/@testing-library/react/dist/pure.js:155:12)
      at node_modules/@testing-library/react/dist/pure.js:286:12
      at node_modules/@testing-library/react/dist/act-compat.js:48:24
      at act (node_modules/react/cjs/react.development.js:2512:16)
      at node_modules/@testing-library/react/dist/act-compat.js:47:25
      at node_modules/@testing-library/react/dist/pure.js:285:28
            at Array.forEach (<anonymous>)
      at cleanup (node_modules/@testing-library/react/dist/pure.js:281:22)
      at Object.<anonymous> (node_modules/@testing-library/react/dist/index.js:28:25)
        type: 'unhandled exception'
      }
          at console.captureMessage [as error] (/drone/src/node_modules/jest-fail-on-console/index.js:78:25)
          at VirtualConsole.<anonymous> (/drone/src/node_modules/jest-environment-jsdom/build/index.js:63:23)
          at VirtualConsole.emit (node:events:514:28)
          at reportException (/drone/src/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:70:28)
          at innerInvokeEventListeners (/drone/src/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:353:9)
          at invokeEventListeners (/drone/src/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:286:3)
          at HTMLUnknownElementImpl._dispatch (/drone/src/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:233:9)
          at HTMLUnknownElementImpl.dispatchEvent (/drone/src/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:104:17)
          at HTMLUnknownElement.dispatchEvent (/drone/src/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:241:34)
          at Object.invokeGuardedCallbackDev (/drone/src/node_modules/react-dom/cjs/react-dom.development.js:4213:16)
          at invokeGuardedCallback (/drone/src/node_modules/react-dom/cjs/react-dom.development.js:4277:31)
          at reportUncaughtErrorInDEV (/drone/src/node_modules/react-dom/cjs/react-dom.development.js:22838:5)
          at captureCommitPhaseError (/drone/src/node_modules/react-dom/cjs/react-dom.development.js:27126:5)
          at commitPassiveMountEffects_complete (/drone/src/node_modules/react-dom/cjs/react-dom.development.js:24893:9)
          at commitPassiveMountEffects_begin (/drone/src/node_modules/react-dom/cjs/react-dom.development.js:24878:7)
          at commitPassiveMountEffects (/drone/src/node_modules/react-dom/cjs/react-dom.development.js:24866:3)
          at flushPassiveEffectsImpl (/drone/src/node_modules/react-dom/cjs/react-dom.development.js:27039:3)
          at flushPassiveEffects (/drone/src/node_modules/react-dom/cjs/react-dom.development.js:26984:14)
          at performSyncWorkOnRoot (/drone/src/node_modules/react-dom/cjs/react-dom.development.js:26076:3)
          at flushSyncCallbacks (/drone/src/node_modules/react-dom/cjs/react-dom.development.js:12042:22)
          at flushSync (/drone/src/node_modules/react-dom/cjs/react-dom.development.js:26201:7)
          at ReactDOMRoot.Object.<anonymous>.ReactDOMHydrationRoot.unmount.ReactDOMRoot.unmount [as unmount] (/drone/src/node_modules/react-dom/cjs/react-dom.development.js:29336:5)
          at Object.unmount (/drone/src/node_modules/@testing-library/react/dist/pure.js:155:12)
          at /drone/src/node_modules/@testing-library/react/dist/pure.js:286:12
          at /drone/src/node_modules/@testing-library/react/dist/act-compat.js:48:24
          at act (/drone/src/node_modules/react/cjs/react.development.js:2512:16)
          at /drone/src/node_modules/@testing-library/react/dist/act-compat.js:47:25
          at /drone/src/node_modules/@testing-library/react/dist/pure.js:285:28
          at Array.forEach (<anonymous>)
          at cleanup (/drone/src/node_modules/@testing-library/react/dist/pure.js:281:22)
          at Object.<anonymous> (/drone/src/node_modules/@testing-library/react/dist/index.js:28:25)
          at Promise.then.completed (/drone/src/node_modules/jest-circus/build/utils.js:298:28)
          at new Promise (<anonymous>)
          at callAsyncCircusFn (/drone/src/node_modules/jest-circus/build/utils.js:231:10)
          at _callCircusHook (/drone/src/node_modules/jest-circus/build/run.js:281:40)
          at runNextTicks (node:internal/process/task_queues:60:5)
          at listOnTimeout (node:internal/timers:540:9)
          at processTimers (node:internal/timers:514:7)
          at _runTest (/drone/src/node_modules/jest-circus/build/run.js:254:5)
          at _runTestsForDescribeBlock (/drone/src/node_modules/jest-circus/build/run.js:126:9)
          at _runTestsForDescribeBlock (/drone/src/node_modules/jest-circus/build/run.js:121:9)
          at run (/drone/src/node_modules/jest-circus/build/run.js:71:3)
          at runAndTransformResultsToJestFormat (/drone/src/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
          at jestAdapter (/drone/src/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
          at runTestInternal (/drone/src/node_modules/jest-runner/build/runTest.js:367:16)
          at runTest (/drone/src/node_modules/jest-runner/build/runTest.js:444:34)
          at Object.worker (/drone/src/node_modules/jest-runner/build/testWorker.js:106:12)
      at flushUnexpectedConsoleCalls (node_modules/jest-fail-on-console/index.js:47:13)
      at Object.<anonymous> (node_modules/jest-fail-on-console/index.js:134:7)
```

Failed build: https://drone.grafana.net/grafana/grafana/172753/1/6. Restarting the build made the test pass.

**Comment by fabrizio-grafana** [comment]
FYI @grafana/explore-squad, since according to `CODEOWNERS` you should be owner of this test.

**Comment by ifrost** [comment]
Happened as well in https://drone.grafana.net/grafana/grafana/172781/1/6 which was based off the latest main. I'll skip the test to check it again.
