### ISSUE TITLE
ubuntu 22.04 yarn install --immuable passed, but yarn start failed, pls help,thanks!Product Area: Short description of bug

### ISSUE THREAD

**Issue by andersling** [grafana/grafana#87533]
### What happened?

yarn install --immutable --inline-builds
➤ YN0000: · Yarn 4.2.1
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0s 695ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0060: │ @grafana/data is listed by your project with version 11.1.0-pre, which doesn't satisfy what @grafana/experimental (p09961) and other dependencies request (but they have non-overlapping ranges!).
➤ YN0060: │ @grafana/data is listed by your project with version 11.1.0-pre, which doesn't satisfy what @grafana/experimental (p9c164) and other dependencies request (^10.0.0).
➤ YN0060: │ @grafana/e2e-selectors is listed by your project with version 11.1.0-pre, which doesn't satisfy what @grafana/experimental (p69e2d) and other dependencies request (^10.0.0).
➤ YN0060: │ @grafana/runtime is listed by your project with version 11.1.0-pre, which doesn't satisfy what @grafana/experimental (p19c88) requests (^10.0.0).
➤ YN0060: │ @grafana/runtime is listed by your project with version 11.1.0-pre, which doesn't satisfy what @grafana/experimental (p68c57) and other dependencies request (but they have non-overlapping ranges!).
➤ YN0060: │ @grafana/schema is listed by your project with version 11.1.0-pre, which doesn't satisfy what @grafana/scenes (pb8930) requests (^10.4.1).
➤ YN0060: │ @grafana/ui is listed by your project with version 11.1.0-pre, which doesn't satisfy what @grafana/experimental (p3b8f5) and other dependencies request (^10.0.0).
➤ YN0060: │ @grafana/ui is listed by your project with version 11.1.0-pre, which doesn't satisfy what @grafana/experimental (pd722e) and other dependencies request (but they have non-overlapping ranges!).
➤ YN0060: │ @testing-library/dom is listed by your project with version 10.0.0, which doesn't satisfy what testing-library-selector (p708b4) requests (^9.3.3).
➤ YN0060: │ @types/react is listed by your project with version 18.2.79, which doesn't satisfy what @testing-library/react-hooks (p89aa2) and other dependencies request (^16.9.0 || ^17.0.0).
➤ YN0060: │ marked is listed by your project with version 12.0.2, which doesn't satisfy what @glideapps/glide-data-grid (pceac5) requests (^4.0.10).
➤ YN0060: │ monaco-editor is listed by your project with version 0.34.1, which doesn't satisfy what @grafana/monaco-logql (p03d88) and other dependencies request (but they have non-overlapping ranges!).
➤ YN0060: │ react is listed by your project with version 18.2.0, which doesn't satisfy what react-beautiful-dnd (p1eae0) and other dependencies request (but they have non-overlapping ranges!).
➤ YN0060: │ react-dom is listed by your project with version 18.2.0, which doesn't satisfy what @grafana/experimental (p5dcbe) and other dependencies request (but they have non-overlapping ranges!).
➤ YN0060: │ react-test-renderer is listed by your project with version 18.2.0, which doesn't satisfy what @testing-library/react-hooks (pdf88f) requests (^16.9.0 || ^17.0.0).
➤ YN0060: │ rollup is listed by your project with version 2.79.1, which doesn't satisfy what rollup-plugin-dts (p94e70) and other dependencies request (^3.29.4).
➤ YN0060: │ rxjs is listed by your project with version 7.8.1, which doesn't satisfy what @grafana/experimental (p41c44) and other dependencies request (7.8.0).
➤ YN0002: │ @grafana-plugins/grafana-postgresql-datasource@workspace:public/app/plugins/datasource/grafana-postgresql-datasource doesn't provide @testing-library/dom (p012e7), requested by @testing-library/user-event.
➤ YN0002: │ @grafana-plugins/grafana-postgresql-datasource@workspace:public/app/plugins/datasource/grafana-postgresql-datasource doesn't provide react-dom (p7074a), requested by @testing-library/react.
➤ YN0002: │ @grafana-plugins/grafana-postgresql-datasource@workspace:public/app/plugins/datasource/grafana-postgresql-datasource doesn't provide react-dom (p9ce1c), requested by @grafana/experimental.
➤ YN0002: │ @grafana-plugins/grafana-postgresql-datasource@workspace:public/app/plugins/datasource/grafana-postgresql-datasource doesn't provide react-select (pf9b71), requested by @grafana/experimental.
➤ YN0002: │ @grafana-plugins/mysql@workspace:public/app/plugins/datasource/mysql doesn't provide @testing-library/dom (pc1d93), requested by @testing-library/user-event.
➤ YN0002: │ @grafana-plugins/mysql@workspace:public/app/plugins/datasource/mysql doesn't provide react-dom (p1c427), requested by @testing-library/react.
➤ YN0002: │ @grafana-plugins/mysql@workspace:public/app/plugins/datasource/mysql doesn't provide react-dom (p88d9c), requested by @grafana/experimental.
➤ YN0002: │ @grafana-plugins/mysql@workspace:public/app/plugins/datasource/mysql doesn't provide react-select (p354fa), requested by @grafana/experimental.
➤ YN0086: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 846ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 1s 83ms
➤ YN0000: · Done with warnings in 3s 117ms

yarn start
Internal Error: spawn ETXTBSY
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at Object.spawn (node:child_process:761:9)
    at zY (/media/whatsminner/Kernel_T7/WisdomcomCloud/grafana/.yarn/releases/yarn-4.2.1.cjs:9:51924)
    at LE.implementation (/media/whatsminner/Kernel_T7/WisdomcomCloud/grafana/.yarn/releases/yarn-4.2.1.cjs:159:1348)
    at LE.exec (/media/whatsminner/Kernel_T7/WisdomcomCloud/grafana/.yarn/releases/yarn-4.2.1.cjs:165:1414)
    at LE.run (/media/whatsminner/Kernel_T7/WisdomcomCloud/grafana/.yarn/releases/yarn-4.2.1.cjs:165:1585)
    at oce (/media/whatsminner/Kernel_T7/WisdomcomCloud/grafana/.yarn/releases/yarn-4.2.1.cjs:165:7428)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Eot (/media/whatsminner/Kernel_T7/WisdomcomCloud/grafana/.yarn/releases/yarn-4.2.1.cjs:167:16)
    at async u (/media/whatsminner/Kernel_T7/WisdomcomCloud/grafana/.yarn/releases/yarn-4.2.1.cjs:167:147)

### What did you expect to happen?

yarn start
Internal Error: spawn ETXTBSY
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at Object.spawn (node:child_process:761:9)
    at zY (/media/whatsminner/Kernel_T7/WisdomcomCloud/grafana/.yarn/releases/yarn-4.2.1.cjs:9:51924)
    at LE.implementation (/media/whatsminner/Kernel_T7/WisdomcomCloud/grafana/.yarn/releases/yarn-4.2.1.cjs:159:1348)
    at LE.exec (/media/whatsminner/Kernel_T7/WisdomcomCloud/grafana/.yarn/releases/yarn-4.2.1.cjs:165:1414)
    at LE.run (/media/whatsminner/Kernel_T7/WisdomcomCloud/grafana/.yarn/releases/yarn-4.2.1.cjs:165:1585)
    at oce (/media/whatsminner/Kernel_T7/WisdomcomCloud/grafana/.yarn/releases/yarn-4.2.1.cjs:165:7428)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Eot (/media/whatsminner/Kernel_T7/WisdomcomCloud/grafana/.yarn/releases/yarn-4.2.1.cjs:167:16)
    at async u (/media/whatsminner/Kernel_T7/WisdomcomCloud/grafana/.yarn/releases/yarn-4.2.1.cjs:167:147)

### Did this work before?

yarn start
Internal Error: spawn ETXTBSY
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at Object.spawn (node:child_process:761:9)
    at zY (/media/whatsminner/Kernel_T7/WisdomcomCloud/grafana/.yarn/releases/yarn-4.2.1.cjs:9:51924)
    at LE.implementation (/media/whatsminner/Kernel_T7/WisdomcomCloud/grafana/.yarn/releases/yarn-4.2.1.cjs:159:1348)
    at LE.exec (/media/whatsminner/Kernel_T7/WisdomcomCloud/grafana/.yarn/releases/yarn-4.2.1.cjs:165:1414)
    at LE.run (/media/whatsminner/Kernel_T7/WisdomcomCloud/grafana/.yarn/releases/yarn-4.2.1.cjs:165:1585)
    at oce (/media/whatsminner/Kernel_T7/WisdomcomCloud/grafana/.yarn/releases/yarn-4.2.1.cjs:165:7428)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Eot (/media/whatsminner/Kernel_T7/WisdomcomCloud/grafana/.yarn/releases/yarn-4.2.1.cjs:167:16)
    at async u (/media/whatsminner/Kernel_T7/WisdomcomCloud/grafana/.yarn/releases/yarn-4.2.1.cjs:167:147)

### How do we reproduce it?

yarn start
Internal Error: spawn ETXTBSY
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at Object.spawn (node:child_process:761:9)
    at zY (/media/whatsminner/Kernel_T7/WisdomcomCloud/grafana/.yarn/releases/yarn-4.2.1.cjs:9:51924)
    at LE.implementation (/media/whatsminner/Kernel_T7/WisdomcomCloud/grafana/.yarn/releases/yarn-4.2.1.cjs:159:1348)
    at LE.exec (/media/whatsminner/Kernel_T7/WisdomcomCloud/grafana/.yarn/releases/yarn-4.2.1.cjs:165:1414)
    at LE.run (/media/whatsminner/Kernel_T7/WisdomcomCloud/grafana/.yarn/releases/yarn-4.2.1.cjs:165:1585)
    at oce (/media/whatsminner/Kernel_T7/WisdomcomCloud/grafana/.yarn/releases/yarn-4.2.1.cjs:165:7428)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Eot (/media/whatsminner/Kernel_T7/WisdomcomCloud/grafana/.yarn/releases/yarn-4.2.1.cjs:167:16)
    at async u (/media/whatsminner/Kernel_T7/WisdomcomCloud/grafana/.yarn/releases/yarn-4.2.1.cjs:167:147)

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by andersling** [comment]
After struggle a lot time to this problem, I finally find that  it is caused by the NodeJS version , WE HAVE TO USE THE ver 18.x , ver 20 or ver 21 will cuase this. Hope this can help someone who meet with it .

**Comment by chenyina1999** [comment]
I have the same problem as you, but the node version required by the grafana source code I downloaded is "engines": {
"node": ">= 22"}, so do you have any other solutions? thanks !
