### ISSUE TITLE
Dashboards: Cannot read properties of undefined (reading 'length') on Dashboard Refresh

### ISSUE THREAD

**Issue by MakinoharaShoko** [grafana/grafana#88280]
### What happened?

I am developing a Grafana plugin that supports streaming data and involves a backend. The streaming data works fine when I first land on it, but when I click on "Refresh Dashboard", the streaming breaks and the console shows the error:

Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at PanelQueryRunner.ts:157:55
    at Array.map (<anonymous>)
    at PanelQueryRunner.ts:155:49
    at map.js:7:37
    at E._next (OperatorSubscriber.js:15:21)
    at Q.next (Subscriber.js:34:18)
    at y._subscribe (innerFrom.js:51:24)
    at y._trySubscribe (Observable.js:38:25)
    at Observable.js:32:31
    at u (errorContext.js:19:9)

### What did you expect to happen?

Data flow executes normally after refresh

### Did this work before?

No

### How do we reproduce it?

1. Set up a data source that supports streaming data.
2. Use `getGrafanaLiveSrv().getDataStream` to get a data stream from the backend.
3. Refresh the dashboard while the data stream is running.

### Environment (with versions)?

Grafana: v10.3.3 (252761264e)
OS: Linux Ubuntu 20.04
Browser: Chrome 125.0.6422.61

### Grafana platform?

None

**Comment by tolzhabayev** [comment]
Hey @MakinoharaShoko,
could you please share a repository / branch that we could take a look at? 

As an alternative, please take a look at our examples repository https://github.com/grafana/grafana-plugin-examples/tree/main/examples/datasource-streaming-backend-websocket to see if it helps you figure out the difference in behaviour. 

And as usual recommendation - try latest grafana version to see if it fixes the issue.

**Comment by MakinoharaShoko** [comment]
OK. You can see https://github.com/dolphindb/grafana-datasource-next/blob/f13a0dbe4c2541d06421155955acbfdb0743bca4/src/datasource.ts#L20

I have to return a new Observable and manually subscribe the events of each streaming query.

But when I use merge to simply merge the streaming and non-streaming query like the code below, and start a streaming query, then get some data, and refresh the panel, the error occurs.

![image](https://github.com/grafana/grafana/assets/30483415/56fd064c-3c7a-43c6-982b-20a192d32bdb)


```typescript
  query(request: DataQueryRequest<DdbDataQuery>): Observable<DataQueryResponse> {
    const { range: { from, to }, scopedVars } = request

    const commonQueriesTargets = request.targets.filter(query => !query.is_streaming).map(query => {
      const code = query.queryText ?? '';
      const tplsrv = getTemplateSrv();
      (from as any)._isUTC = false;
      (to as any)._isUTC = false;
      const code_ = tplsrv
        .replace(
          code //@ts-ignore
            .replaceAll(
              /\$(__)?timeFilter\b/g,
              () =>
                'pair(' +
                from.format('YYYY.MM.DD HH:mm:ss.SSS') +
                ', ' +
                to.format('YYYY.MM.DD HH:mm:ss.SSS') +
                ')'
            ).replaceAll(
              /\$__interval\b/g,
              () =>
                tplsrv.replace('$__interval', scopedVars).replace(/h$/, 'H')
            ),
          scopedVars,
          var_formatter
        )
      return {
        ...query, queryText: code_
      }
    });
    const streamingQueries = request.targets.filter(query => query.is_streaming);

      /**
       * non-streaming
       */
      const commonRequest = { ...request, targets: commonQueriesTargets };
      const result = super.query(commonRequest);
      // streaming
      const observables = streamingQueries.map((query) => {
        return getGrafanaLiveSrv().getDataStream({
          addr: {
            scope: LiveChannelScope.DataSource,
            namespace: this.uid,
            path: `ws/streaming-${query.refId}-${query.streaming?.table ?? ''}`,
            data: {
              ...query,
            },
          },
        });
      });

      return merge(result,...observables)
  }
```

If I do not use merge but mannual use Observer to handle each event ,it works fine.

**Comment by MakinoharaShoko** [comment]
Thank you for your reply!
Just now I tested the data source in the repository you provided on v10.4.0 (03f502a94d), but the error still occurred.
I created a query like this:
![image](https://github.com/user-attachments/assets/fa0b24cc-41a1-4cb3-95da-0498990430cf)
During the first query, everything ran normally, but when I pressed refresh, an error occurred.
![image](https://github.com/user-attachments/assets/3be06a61-e737-4af4-a02d-03733ed716b0)
Follow is an image that shows the version and the error message side by side.
![image](https://github.com/user-attachments/assets/2b427886-caae-4ad9-b50f-1dae64357eb5)

**Comment by MakinoharaShoko** [comment]
I also tested in the latest version and the issue still occurs. You can also try changing the time range while streaming, and you will also encounter such an error message.
![image](https://github.com/user-attachments/assets/b0d4eb9b-9741-4b2b-8954-51e475bdd813)

**Comment by ryantxu** [comment]
@MakinoharaShoko you have waded into the most complex bits here!  It looks like your error is hitting this line:
https://github.com/grafana/grafana/blob/main/public/app/features/query/state/PanelQueryRunner.ts#L163

If you can find a fix in the panel query runner, we are all ears -- but I assume the easier fix is in the data source.  It looks like the data source is likely sending a packet that is missing the series property.  Can you verify that that exists?

**Comment by ryantxu** [comment]
If you can find a way to reproduce with the testdata source, we can help debugging/fixing better

**Comment by MakinoharaShoko** [comment]
Okay, I am happy to provide a reproduction method. @ryantxu 
You can use this branch, https://github.com/oshirohugo/xx-110724-datasource/tree/combine-stream-and-query, which was mentioned in the previous discussion, to reproduce the issue.
Create a dashboard using this data source and then create a panel. Subscribe to a stream data. Wait for a few seconds after the stream data has started to run (after a few data points have appeared). Then, click the refresh button located in the upper right corner of the chart. The error message will appear.

**Comment by hugohaggmark** [comment]
@MakinoharaShoko tried this with Grafana v12.1.0 and it works as expected using `merge` operator, can you please confirm so that we can close this issue? Thank you 🙏

**Comment by MakinoharaShoko** [comment]
I just tested this issue, and it's been resolved in v12.1.0. Thank you for your work!

**Comment by hugohaggmark** [comment]
Thanks for quick feedback 🙌
