### ISSUE TITLE
Alerting: Recovery Threshold with value `null` causes panic runtime error

### ISSUE THREAD

**Issue by dmakeienko** [grafana/grafana#88415]
### What happened?

I'm using [terraform-provider-grafana](https://github.com/grafana/terraform-provider-grafana) for managing alerts. When I tried to make a [recovery threshold](https://grafana.com/docs/grafana/latest/alerting/fundamentals/alert-rules/queries-conditions/#recovery-threshold), I've provided null to unloadEvaluator param:
```              
        unloadEvaluator = {
                params = [
                  null
                ]
              }
```
After apply and changes took effect, my grafana instance started to crash periodically with the following errors:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x6f04aa5]

goroutine 1445 [running]:
github.com/grafana/grafana/pkg/expr.UnmarshalThresholdCommand(0xc0049dcf50, {0x21fb130, 0xc002a7c000})
	github.com/grafana/grafana/pkg/expr/threshold.go:87 +0x265
github.com/grafana/grafana/pkg/expr.buildCMDNode(0xc0049dcf50, {0x21fb130, 0xc002a7c000})
	github.com/grafana/grafana/pkg/expr/nodes.go:124 +0x24b
github.com/grafana/grafana/pkg/expr.(*Service).buildGraph(0xc002e0ec00, 0xc004fb1900)
	github.com/grafana/grafana/pkg/expr/graph.go:228 +0x587
github.com/grafana/grafana/pkg/expr.(*Service).buildDependencyGraph(0x240?, 0x3b9aca00?)
	github.com/grafana/grafana/pkg/expr/graph.go:146 +0x13
github.com/grafana/grafana/pkg/expr.(*Service).buildPipeline(0x263a?, 0xc003130f80?)
	github.com/grafana/grafana/pkg/expr/graph.go:131 +0x6b
github.com/grafana/grafana/pkg/expr.(*Service).BuildPipeline(...)
	github.com/grafana/grafana/pkg/expr/service.go:97
github.com/grafana/grafana/pkg/services/ngalert/eval.(*evaluatorImpl).create(0xc0019c83c0, {{0xa294450, 0x1}, {0xc00239e900, 0x2, 0x2}}, 0xc004dc03a8?)
	github.com/grafana/grafana/pkg/services/ngalert/eval/eval.go:813 +0x59
github.com/grafana/grafana/pkg/services/ngalert/eval.(*evaluatorImpl).Create(0xc0019c83c0, {{0x22169a0, 0xc00395ad20}, {0x225dc58, 0xc0047d4fc0}, {0x21ce7a0, 0xc004dc03a8}}, {{0xa294450, 0x1}, {0xc00239e900, ...}})
	github.com/grafana/grafana/pkg/services/ngalert/eval/eval.go:809 +0x12d
github.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRoutine.func3({0x22169a0?, 0xc00395ad20?}, 0xc003415a70?, 0x14ef779?, 0xc0054fa948, {0x2245560, 0xc004f58a50}, 0x0)
	github.com/grafana/grafana/pkg/services/ngalert/schedule/schedule.go:385 +0x6d5
github.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRoutine.func4(0x0?, 0xc001d717a0, {0x17c?, {0xc003130df0?, 0x0?}}, 0xc0054fa948, 0xc0049ddc60, {0x222c570, 0xc003415aa0}, 0xc0049dde28, ...)
	github.com/grafana/grafana/pkg/services/ngalert/schedule/schedule.go:545 +0xb1a
github.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRoutine(0xc001d717a0, {0x2216f50, 0xc00359fbc0}, {0x1?, {0xc003130df0?, 0x0?}}, 0xc003599ec0, 0xc003599f20)
	github.com/grafana/grafana/pkg/services/ngalert/schedule/schedule.go:562 +0x725
github.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).processTick.func1()
	github.com/grafana/grafana/pkg/services/ngalert/schedule/schedule.go:259 +0x36
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.6.0/errgroup/errgroup.go:78 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1112
	golang.org/x/sync@v0.6.0/errgroup/errgroup.go:75 +0x96

``` 

### What did you expect to happen?

Either Grafana should response with an error when `null` is provided or custom recovery threshold should not be created.

### Did this work before?

No

### How do we reproduce it?

Create terraform config
```hcl
resource "grafana_rule_group" "alert" {
  name             = "Memory Status"
  folder_uid       = var.folder_uid
  interval_seconds = 30

  rule {
      name           =  "High RAM Usage on instance(s)"
      for            = "1m"
      condition      = "B"
      no_data_state  = "OK
      exec_err_state = "Error"

      is_paused = false
      data {
        ref_id     = "A"
        query_type = ""

        relative_time_range {
          from = 60
          to   = 0
        }
        datasource_uid = var.datasource_uid
        model = jsonencode({
          datasource = {
            type = var.datasource_type
            uid  = var.datasource_uid
          }
          editorMode = "code"
          expr       = "(100 - ((node_memory_MemAvailable_bytes{job=\"node-exporter\",instance=~\".+\"} * 100) / node_memory_MemTotal_bytes{job=\"node-exporter\",instance=~\".+\"})) * on(instance) group_left (nodename) node_uname_info{instance=~\".+\"}"
          instant    = true
          range      = false
          refId      = "A"
          hide       = false
        })
      }

      data {
        ref_id = "B"
        relative_time_range {
          from = 0
          to   = 0
        }
        datasource_uid = "__expr__"
        model = jsonencode({
          conditions = [
            {
              evaluator = {
                params = [
                  95
                ]
                type = "gt"
              }
              operator = {
                type = "and"
              }
              query = {
                params = [
                  "B"
                ]
              }
              reducer = {
                params = []
                type   = "last"
              }
              type = "query"
              unloadEvaluator = {
                params = [
                  null
                ]
              }
            },
          ]
          datasource = {
            name = "Expression"
            type = "__expr__"
            uid  = "__expr__"
          }
          expression = "A"
          refId      = "B"
          type       = "reduce"
          type       = "threshold"
        })
      }
  }
}
``` 

### Environment (with versions)?

Grafana: OSS 10.4.1
Helm: 7.3.7 
OS: Linux
Browser: Google Chrome 125.0.6422.112
Terraform Provider: 2.19.0
Terraform 1.5.5

### Grafana platform?

Kubernetes

### Datasource(s)?

Prometheus

**Comment by yuri-tceretian** [comment]
It's been fixed in https://github.com/grafana/grafana/pull/88521
