### ISSUE TITLE
[Bug] Selecting InfluxDB math function on Heatmap panel causes Javascript error

### ISSUE THREAD

**Issue by Fusl** [grafana/grafana#8870]
v4.4.1 - InfluxDB - Debian Jessie

```
TypeError: Cannot read property 'def' of undefined
    at a.i [as addStrategy] (https://grafana.fvz.io/public/app/boot.74ebeed4.js:17:5720)
    at a.addSelectPart (https://grafana.fvz.io/public/app/boot.74ebeed4.js:17:2963)
    at b.addSelectPart (https://grafana.fvz.io/public/app/boot.74ebeed4.js:17:13772)
    at fn (eval at compile (https://grafana.fvz.io/public/app/boot.74ebeed4.js:54:9786), <anonymous>:4:422)
    at o.e.(anonymous function) [as dropdownTypeaheadOnSelect] (https://grafana.fvz.io/public/app/boot.74ebeed4.js:51:22866)
    at b.f.menuItemSelected (https://grafana.fvz.io/public/app/boot.74ebeed4.js:33:12430)
    at fn (eval at compile (https://grafana.fvz.io/public/app/boot.74ebeed4.js:1:1), <anonymous>:4:184)
    at e (https://grafana.fvz.io/public/app/boot.74ebeed4.js:54:29976)
    at b.$eval (https://grafana.fvz.io/public/app/boot.74ebeed4.js:52:22865)
    at b.$apply (https://grafana.fvz.io/public/app/boot.74ebeed4.js:52:23098)
```

I verified that the math function itself works fine when using a graph and siglestat panels, haven't tested others though.

**Comment by daniellee** [comment]
I cannot recreate this. It seems to work fine for me. Can you provide more details - what does your query look like?

**Comment by Fusl** [comment]
Steps to reproduce this:

- Add a new panel `Heatmap`
- Select an InfluxDB data source
- Add `math` function -> works
- Remove `math` function
- Remove the default `GROUP BY` function `time($__interval)`, it will also remove the default `fill(null)` and `mean()` functions
- Try to add `math` function -> fails

**Comment by torkelo** [comment]
So you have only math added and not group by time? Strongly encourage to have group by time as otherwise InfluxDB can return millions of data points and hang your browser

**Comment by Fusl** [comment]
I'm well aware how much datapoints InfluxDB returns without a group by time, but doing group by time would distort and falsify the resulting heatmap. The heatmap itself is only drawn by the render API anyway, no browser will display this graph.

Yet, `math` shouldn't silently fail when there is no group by time.

**Comment by torkelo** [comment]
Or course not, 

Render api? Grafana render api is using a browser under the hoods (phantomjs) to generate the PNG, if you do not use group by time just be careful having to long a time range :)

**Comment by Fusl** [comment]
> just be careful

Everything's fine as can be seen [here](http://share.grafana.fvz.io/mtr.sh.html) :)

**Comment by daniellee** [comment]
Confirmed as a bug. There is an out of bounds error as the add math function expects there to be at least two parts in the query. Fix coming up.

**Comment by daniellee** [comment]
Fixed in master.
