### ISSUE TITLE
searching for "true" in Home/Administration/plugins

### ISSUE THREAD

**Issue by PrevosHD** [grafana/grafana#88959]
### What happened?

Yeah... i was looking for some new panels to show some data, specificly something that's easy to read for true/false (yeah, i could use color, dont need to mention it)
So i searched for "true" after pressing the last letter "e" grafana crashes.
(https://sub.example.com/plugins?filterBy=all&filterByType=all&q=true)

`An unexpected error happened`

```
    at ee (https://sub.example.com/public/build/PluginListPage.ad3f5686993ad0f34bb1.js:66:525)
    at Suspense
    at f (https://sub.example.com/public/build/8628.0b45d34f00c1a7531927.js:1278:180)
    at Bl (https://sub.example.com/public/build/8628.0b45d34f00c1a7531927.js:4678:333)
    at Ye (https://sub.example.com/public/build/7490.cf2da2a42f577bdb1843.js:178:24528)
    at Ye (https://sub.example.com/public/build/7490.cf2da2a42f577bdb1843.js:178:26724)
    at div
    at main
    at Zs (https://sub.example.com/public/build/8628.0b45d34f00c1a7531927.js:4675:1865)
    at Ye (https://sub.example.com/public/build/7490.cf2da2a42f577bdb1843.js:178:20823)
    at div
    at l (https://sub.example.com/public/build/8628.0b45d34f00c1a7531927.js:2567:3974)
    at v (https://sub.example.com/public/build/7490.cf2da2a42f577bdb1843.js:49:51342)
    at i (https://sub.example.com/public/build/8628.0b45d34f00c1a7531927.js:5411:18831)
    at f (https://sub.example.com/public/build/8628.0b45d34f00c1a7531927.js:1278:180)
    at c (https://sub.example.com/public/build/8628.0b45d34f00c1a7531927.js:1278:754)
    at S (https://sub.example.com/public/build/7490.cf2da2a42f577bdb1843.js:174:124661)
    at Zi (https://sub.example.com/public/build/8628.0b45d34f00c1a7531927.js:4691:127)
```

### What did you expect to happen?

Find some cool looking panels

### Did this work before?

First time.

### How do we reproduce it?

1. Login your Grafana
2. Open Home/Administration/Plugins
3. Search for "true"

### Environment (with versions)?

Grafana: Grafana v9.5.2 (cfcea75916)
OS: Ubuntu 22.04.4 LTS
Browser: Chrome Version 125.0.6422.142

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

MySQL

**Comment by PrevosHD** [comment]
should update next time.
