### ISSUE TITLE
Dashboard scenes: The get help screen feature does not properly populate when accessed through panel edit.

### ISSUE THREAD

**Issue by oscarkilhed** [grafana/grafana#89095]
When using scenes dashboards. Clicking the get help menu option on a panel from the dashboard view properly populates the debug dashboard, but if the menu item is clicked from inside the edit panel view the debug dashboard is not populated with data.

Context: https://raintank-corp.slack.com/archives/C03KVDHTWAH/p1718135082061829

**Comment by dprokop** [comment]
Stack trace:

```ts
Uncaught (in promise) Error: DashboardGridItem body expected to be VizPanel
    at gridItemToPanel (transformSceneToSaveModel.ts:195:11)
    at getDebugDashboard (utils.ts:75:32)
    at SupportSnapshotService.buildDebugDashboard (SupportSnapshotService.ts:72:45)
    at HelpWizard.tsx:55:13
    at commitHookEffectListMount (react-dom.development.js:23150:1)
    at commitPassiveMountOnFiber (react-dom.development.js:24926:1)
    at commitPassiveMountEffects_complete (react-dom.development.js:24891:1)
    at commitPassiveMountEffects_begin (react-dom.development.js:24878:1)
    at commitPassiveMountEffects (react-dom.development.js:24866:1)
    at flushPassiveEffectsImpl (react-dom.development.js:27039:1)
```
