### ISSUE TITLE
Build frontend assets fails with node 6.10.3 an npm 3.10.10

### ISSUE THREAD

**Issue by ogarcia** [grafana/grafana#8911]
When I try to build frontend assets with **node 6.10.3** an **npm 3.10.10** I give a segfault error.

```
Running "sass:src" (sass) task
Segmentation fault (core dumped)

npm ERR! Linux 4.11.9-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! grafana@4.4.1 build: `./node_modules/grunt-cli/bin/grunt`
npm ERR! Exit status 139
npm ERR! 
npm ERR! Failed at the grafana@4.4.1 build script './node_modules/grunt-cli/bin/grunt'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the grafana package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./node_modules/grunt-cli/bin/grunt
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs grafana
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls grafana
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/build/grafana-4.4.1/npm-debug.log
```
The `npm-debug.log` contains the following.

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle grafana@4.4.1~prebuild: grafana@4.4.1
6 silly lifecycle grafana@4.4.1~prebuild: no script for prebuild, continuing
7 info lifecycle grafana@4.4.1~build: grafana@4.4.1
8 verbose lifecycle grafana@4.4.1~build: unsafe-perm in lifecycle true
9 verbose lifecycle grafana@4.4.1~build: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/tmp/build/grafana-4.4.1/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle grafana@4.4.1~build: CWD: /tmp/build/grafana-4.4.1
11 silly lifecycle grafana@4.4.1~build: Args: [ '-c', './node_modules/grunt-cli/bin/grunt' ]
12 silly lifecycle grafana@4.4.1~build: Returned: code: 139  signal: null
13 info lifecycle grafana@4.4.1~build: Failed to exec build script
14 verbose stack Error: grafana@4.4.1 build: `./node_modules/grunt-cli/bin/grunt`
14 verbose stack Exit status 139
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid grafana@4.4.1
16 verbose cwd /tmp/build/grafana-4.4.1
17 error Linux 4.11.9-1-ARCH
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
19 error node v6.10.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error grafana@4.4.1 build: `./node_modules/grunt-cli/bin/grunt`
22 error Exit status 139
23 error Failed at the grafana@4.4.1 build script './node_modules/grunt-cli/bin/grunt'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the grafana package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ./node_modules/grunt-cli/bin/grunt
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs grafana
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls grafana
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by daniellee** [comment]
This sounds exactly like this: #8807 so might be fixed in master (none of us on the Grafana team has experienced this problem).

The standard advice for any npm problems for any project is to delete the node modules directory and try the yarn install again. Also, you could trying upgrading your npm.

**Comment by ogarcia** [comment]
@daniellee Yes, I think that is the same bug, because I'm using Alpine Linux too. I'll try with master and tell you the result.

**Comment by ogarcia** [comment]
Ok. Tested with master and works perfect. I think that this issue can be closed in next release. :wink:
