### ISSUE TITLE
Google Cloud Monitoring: Multiple broken functionality

### ISSUE THREAD

**Issue by BadLiveware** [grafana/grafana#89685]
### What happened?

Builder is broken in mutiple ways, selecting project doesnt work until reload, `filter` button seems to do nothing, `group` by doesnt update after selecting until reload, same with `group by function`

https://github.com/grafana/grafana/assets/10245011/5fb7bc7d-6187-4e13-b669-27dbcbc0ad55

Changing query type, e.g. to MQL/PromQL doesnt work until selecting type and then reloading page, which will get a react error before working on the second reload

https://github.com/grafana/grafana/assets/10245011/56e4ecae-5c16-4f85-87c5-5f05448d91b0

```
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

    at button
    at https://grafana-v2.tradera.cloud/public/build/5017.7907d834ca1fb6d153e1.js:286:69673
    at https://grafana-v2.tradera.cloud/public/build/5017.7907d834ca1fb6d153e1.js:286:77053
    at div
    at https://grafana-v2.tradera.cloud/public/build/5017.7907d834ca1fb6d153e1.js:190:7648
    at Ps (https://grafana-v2.tradera.cloud/public/build/5950.30ec6aaa9dcece6c3b3c.js:385:23567)
    at o (https://grafana-v2.tradera.cloud/public/build/5017.7907d834ca1fb6d153e1.js:313:31285)
    at d
    at Ps (https://grafana-v2.tradera.cloud/public/build/5950.30ec6aaa9dcece6c3b3c.js:385:23567)
    at div
    at div
    at https://grafana-v2.tradera.cloud/public/build/5017.7907d834ca1fb6d153e1.js:286:73026
    at nav
    at https://grafana-v2.tradera.cloud/public/build/5017.7907d834ca1fb6d153e1.js:214:20765
    at div
    at Os (https://grafana-v2.tradera.cloud/public/build/explore.476912733278e2a99729.js:11:9517)
    at xo (https://grafana-v2.tradera.cloud/public/build/explore.476912733278e2a99729.js:1:9935)
    at Ps (https://grafana-v2.tradera.cloud/public/build/5950.30ec6aaa9dcece6c3b3c.js:385:23567)
    at Ps (https://grafana-v2.tradera.cloud/public/build/5950.30ec6aaa9dcece6c3b3c.js:385:23567)
    at WithTheme(Connect(di))
    at div
    at div
    at div
    at fe (https://grafana-v2.tradera.cloud/public/build/5950.30ec6aaa9dcece6c3b3c.js:299:4634)
    at u (https://grafana-v2.tradera.cloud/public/build/5017.7907d834ca1fb6d153e1.js:194:29826)
    at fi (https://grafana-v2.tradera.cloud/public/build/explore.476912733278e2a99729.js:402:21751)
    at Ps (https://grafana-v2.tradera.cloud/public/build/5950.30ec6aaa9dcece6c3b3c.js:385:23567)
    at Ps (https://grafana-v2.tradera.cloud/public/build/5950.30ec6aaa9dcece6c3b3c.js:385:23567)
    at Ps (https://grafana-v2.tradera.cloud/public/build/5950.30ec6aaa9dcece6c3b3c.js:385:23567)
    at div
    at o (https://grafana-v2.tradera.cloud/public/build/660.838743295c2108f3492d.js:1:2299)
    at div
    at o (https://grafana-v2.tradera.cloud/public/build/660.838743295c2108f3492d.js:1:4287)
    at Ps (https://grafana-v2.tradera.cloud/public/build/5950.30ec6aaa9dcece6c3b3c.js:385:23567)
    at div
    at Ri (https://grafana-v2.tradera.cloud/public/build/explore.476912733278e2a99729.js:402:24290)
    at Suspense
    at Ps (https://grafana-v2.tradera.cloud/public/build/5950.30ec6aaa9dcece6c3b3c.js:385:23567)
    at lg (https://grafana-v2.tradera.cloud/public/build/5017.7907d834ca1fb6d153e1.js:5707:9531)
    at Ps (https://grafana-v2.tradera.cloud/public/build/5950.30ec6aaa9dcece6c3b3c.js:385:23567)
    at di (https://grafana-v2.tradera.cloud/public/build/5950.30ec6aaa9dcece6c3b3c.js:435:4456)
    at ni (https://grafana-v2.tradera.cloud/public/build/5950.30ec6aaa9dcece6c3b3c.js:435:12006)
    at ht (https://grafana-v2.tradera.cloud/public/build/5950.30ec6aaa9dcece6c3b3c.js:444:17389)
    at Ps (https://grafana-v2.tradera.cloud/public/build/5950.30ec6aaa9dcece6c3b3c.js:385:23567)
    at div
    at div
    at main
    at div
    at Qf (https://grafana-v2.tradera.cloud/public/build/5017.7907d834ca1fb6d153e1.js:5707:2396)
    at di (https://grafana-v2.tradera.cloud/public/build/5950.30ec6aaa9dcece6c3b3c.js:435:4456)
    at ni (https://grafana-v2.tradera.cloud/public/build/5950.30ec6aaa9dcece6c3b3c.js:435:12006)
    at cr (https://grafana-v2.tradera.cloud/public/build/5950.30ec6aaa9dcece6c3b3c.js:435:11342)
    at Hn (https://grafana-v2.tradera.cloud/public/build/5950.30ec6aaa9dcece6c3b3c.js:444:17688)
    at Ps (https://grafana-v2.tradera.cloud/public/build/5950.30ec6aaa9dcece6c3b3c.js:385:23567)
    at div
    at Ps (https://grafana-v2.tradera.cloud/public/build/5950.30ec6aaa9dcece6c3b3c.js:385:23567)
    at Ps (https://grafana-v2.tradera.cloud/public/build/5950.30ec6aaa9dcece6c3b3c.js:385:23567)
    at f (https://grafana-v2.tradera.cloud/public/build/5950.30ec6aaa9dcece6c3b3c.js:773:96569)
    at c (https://grafana-v2.tradera.cloud/public/build/5017.7907d834ca1fb6d153e1.js:499:21164)
    at Ps (https://grafana-v2.tradera.cloud/public/build/5950.30ec6aaa9dcece6c3b3c.js:385:23567)
    at Ps (https://grafana-v2.tradera.cloud/public/build/5950.30ec6aaa9dcece6c3b3c.js:385:23567)
    at it (https://grafana-v2.tradera.cloud/public/build/5950.30ec6aaa9dcece6c3b3c.js:416:529)
    at Ps (https://grafana-v2.tradera.cloud/public/build/5950.30ec6aaa9dcece6c3b3c.js:385:23567)
 ```

### What did you expect to happen?

It not to break in as many ways as it does :)

### Did this work before?

It works in 8.5

### How do we reproduce it?

1. Use the `Google Cloud Monitoring` datasource in v11
2. Try to do almost anything

### Environment (with versions)?

Auth: Workload Identity
Kubernetes: GKE 1.29
Grafana: v11
OS: Container optmized OS
Browser: Chrome 126

### Grafana platform?

Kubernetes

### Datasource(s)?

Google Cloud Monitoring

**Comment by BadLiveware** [comment]
🤦 I forgot that I downgraded to 10.4.3 after testing v11 in order to migrate things. It does seem to work just fine in v11.0.0
