### ISSUE TITLE
Rendering: invalid domain given to grafana-image-renderer if http_addr is an IPv6 address

### ISSUE THREAD

**Issue by Ma27** [grafana/grafana#90712]
### What happened?

Consider the following configuration file (shortened):

```ini
[server]
http_addr=2001:db8::1  # I would use a hostname here, but that's not possible since v11

[rendering]
callback_url=http://[2001:db8::1]:3000
```

When requesting a rendered image of a panel (Share > Direct link rendered image for an arbitrary panel), I only get a white image without any rendered panel and the following message in the logs:

```
 {"err":"ProtocolError: Protocol error (Network.setCookies): Invalid cookie fields\n    at <instance_members_initializer> (/nix/store/9b6hpc65z0bph3bghw5lzraq7sx97wcg-renderer-3.11.1/libexec/grafana-image-renderer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:49:14)\n    at new Callback (/nix/store/9b6hpc65z0bph3bghw5lzraq7sx97wcg-renderer-3.11.1/libexec/grafana-image-renderer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:53:16)\n    at CallbackRegistry.create (/nix/store/9b6hpc65z0bph3bghw5lzraq7sx97wcg-renderer-3.11.1/libexec/grafana-image-renderer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:93:26)\n    at Connection._rawSend (/nix/store/9b6hpc65z0bph3bghw5lzraq7sx97wcg-renderer-3.11.1/libexec/grafana-image-renderer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:207:26)\n    at CDPSessionImpl.send (/nix/store/9b6hpc65z0bph3bghw5lzraq7sx97wcg-renderer-3.11.1/libexec/grafana-image-renderer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:433:33)\n    at CDPPage.setCookie (/nix/store/9b6hpc65z0bph3bghw5lzraq7sx97wcg-renderer-3.11.1/libexec/grafana-image-renderer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:481:32)\n    at async Browser.preparePage (/nix/store/9b6hpc65z0bph3bghw5lzraq7sx97wcg-renderer-3.11.1/libexec/grafana-image-renderer/build/browser/browser.js:165:13)\n    at async /nix/store/9b6hpc65z0bph3bghw5lzraq7sx97wcg-renderer-3.11.1/libexec/grafana-image-renderer/build/browser/browser.js:257:17\n    at async Browser.takeScreenshot (/nix/store/9b6hpc65z0bph3bghw5lzraq7sx97wcg-renderer-3.11.1/libexec/grafana-image-renderer/build/browser/browser.js:252:13)\n    at async Browser.render (/nix/store/9b6hpc65z0bph3bghw5lzraq7sx97wcg-renderer-3.11.1/libexec/grafana-image-renderer/build/browser/browser.js:238:20)","level":"error","message":"Error while trying to prepare page for screenshot","url":"http://[2001:db8::1]:3000/d-solo/bdp5o8ik6xbswe/php-fpm?orgId=1&from=1721475710331&to=1721476610331&panelId=25&width=1000&height=500&scale=1&tz=Europe%2FBerlin&render=1"}
```

The `Invalid cookie fields` from Chromium seems to be the culprit.
With debug logging enabled, I also get

```
{"level":"debug","message":"::1 - - [20/Jul/2024:11:56:52 +0000] \"GET /render?deviceScaleFactor=1.000000&domain=fd42%3Ababe%3A%3A1&encoding=png&height=500&renderKey=EDEEOhxSlvDnfUhjJnrmWtI4sr9m5vOj&timeout=60&timezone=Europe%2FBerlin&url=http%3A%2F%2F%5B2001%3Adb8%3A%3A1%5D%3A3000%2Fd-solo%2Fbdp5o8ik6xbswe%2Fphp-fpm%3ForgId%3D1%26from%3D1721475710331%26to%3D1721476610331%26panelId%3D25%26width%3D1000%26height%3D500%26scale%3D1%26tz%3DEurope%252FBerlin%26render%3D1&width=1000 HTTP/1.1\" 200 2679 \"-\" \"Grafana/11.1.0\"\n"}
```

I think this happens because the raw IP is extracted in https://github.com/grafana/grafana/blob/ee90cd3031b0b0d916c595b9c0efad560a6963bb/pkg/services/rendering/rendering.go#L92 and the domain is then used to set cookies in https://github.com/grafana/grafana-image-renderer/blob/355e24a790158675260bd5f31e7338154619f8e9/src/browser/browser.ts#L161-L165.

The call trace from the renderer seems to confirm that.

### What did you expect to happen?

I'd expect the renderer to provide images containing panels and not a white image.

### Did this work before?

Yes. With Grafana <11.

### How do we reproduce it?

With the configuration parameters used above.

### Environment (with versions)?

Grafana: 11.1.0
Grafana Image Renderer: 3.11.1 (also tested with 3.11.0)
OS: NixOS 24.05
Browser: Firefox 127.0.2 (Client)
Tested with the following Chromium versions for grafana-image-renderer:
* Chromium 120.0.6099.129
* Chromium 126.0.6478.126

### Grafana platform?

None

**Comment by PhilippWendler** [comment]
Same here: broken with `http_addr=::1`, works with `http_addr=127.0.0.1`. Error message:
```
logger=plugin.grafana-image-renderer
t=2024-11-12T09:00:13.201068312+01:00
level=error
msg="Error while trying to prepare page for screenshot"
url="http://::1:3000/d-solo/V2fSBzzmz?from=2024-10-29T07:50:15.850Z&to=2024-11-12T07:51:00.850Z&timezone=browser&viewPanel=panel-3&panelId=panel-3&__feature.dashboardSceneSolo&width=1000&height=500&tz=Europe%2FBerlin&render=1"
err="ProtocolError: Protocol error (Network.setCookies): Invalid cookie fields
    at <instance_members_initializer> (/snapshot/src/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:93:14)
    at new Callback (/snapshot/src/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:97:16)
    at CallbackRegistry.create (/snapshot/src/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:22:26)
    at Connection._rawSend (/snapshot/src/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:89:26)
    at CdpCDPSession.send (/snapshot/src/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:66:33)
    at CdpPage.setCookie (/snapshot/src/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Page.js:490:45)
    at async Browser.preparePage (/snapshot/src/build/browser/browser.js:166:13)
    at async /snapshot/src/build/browser/browser.js:279:17
    at async Browser.takeScreenshot (/snapshot/src/build/browser/browser.js:274:13)
    at async Browser.render (/snapshot/src/build/browser/browser.js:260:20)"
```
Grafana 11.3.0 and grafana-image-renderer 3.11.6 on Ubuntu 22.04.

**Comment by Ma27** [comment]
https://nostalebots.xyz/

**Comment by macabu** [comment]
Hi @Ma27 , sorry for the delay, we were not actively monitoring image-renderer issues in this repo (rather in the image-renderer repo itself), but we're reorganizing a few things to have better track of the issues in the Grafana repo.

That said, I merged https://github.com/grafana/grafana-image-renderer/pull/907 and will tag a release Friday or Monday that will address this.
