### ISSUE TITLE
Grafana 11.1.3 can't be built on FreeBSD

### ISSUE THREAD

**Issue by eriksejr** [grafana/grafana#91368]
### What happened?

```
➤ YN0000: ┌ Link step
➤ YN0007: │ cypress@npm:13.10.0 must be built because it never has been before or the last one failed
➤ YN0009: │ cypress@npm:13.10.0 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-fd1ea6af/build.log)
➤ YN0000: └ Completed in 3s 755ms
➤ YN0000: · Failed with errors in 8s 949ms
gmake: *** [Makefile:43: node_modules] Error 1

 cat /tmp/xfs-fd1ea6af/build.log
# This file contains the result of Yarn building a package (cypress@npm:13.10.0)
# Script name: postinstall

Platform: "freebsd" is not supported.
```

A "gmake build-go" does complete and build the binaries, but I can't build the frontend stuff/templates. I tried the workaround in #89055 

```
yarn run themes-generate
yarn run generate-icons
yarn workspaces foreach --include="@grafana-plugins/*" --parallel -A run build NODE_ENV=production yarn exec webpack --config scripts/webpack/webpack.prod.js --progress
```

The first command completes, the 2nd complains about a missing NPX, and the 3rd generates the errors below:

```
[@grafana-plugins/grafana-azure-monitor-datasource]: [webpack-cli] Failed to load '/tmp/grafana-11.1.3/public/app/plugins/datasource/azuremonitor/scripts/webpack/webpack.prod.js' config
[@grafana-plugins/grafana-azure-monitor-datasource]: [webpack-cli] Error: Cannot find module '/tmp/grafana-11.1.3/public/app/plugins/datasource/azuremonitor/scripts/webpack/webpack.prod.js'
[@grafana-plugins/grafana-azure-monitor-datasource]: Require stack:
[@grafana-plugins/grafana-azure-monitor-datasource]: - /tmp/grafana-11.1.3/node_modules/webpack-cli/lib/webpack-cli.js
[@grafana-plugins/grafana-azure-monitor-datasource]: - /tmp/grafana-11.1.3/node_modules/webpack-cli/lib/bootstrap.js
[@grafana-plugins/grafana-azure-monitor-datasource]: - /tmp/grafana-11.1.3/node_modules/webpack-cli/bin/cli.js
[@grafana-plugins/grafana-azure-monitor-datasource]: - /tmp/grafana-11.1.3/node_modules/webpack/bin/webpack.js
[@grafana-plugins/grafana-azure-monitor-datasource]:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
[@grafana-plugins/grafana-azure-monitor-datasource]:     at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/tmp/grafana-11.1.3/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
[@grafana-plugins/grafana-azure-monitor-datasource]:     at Function.Module._load (node:internal/modules/cjs/loader:986:27)
[@grafana-plugins/grafana-azure-monitor-datasource]:     at Module.require (node:internal/modules/cjs/loader:1233:19)
[@grafana-plugins/grafana-azure-monitor-datasource]:     at require (node:internal/modules/helpers:179:18)
[@grafana-plugins/grafana-azure-monitor-datasource]:     at WebpackCLI.tryRequireThenImport (/tmp/grafana-11.1.3/node_modules/webpack-cli/lib/webpack-cli.js:223:30)
[@grafana-plugins/grafana-azure-monitor-datasource]:     at loadConfigByPath (/tmp/grafana-11.1.3/node_modules/webpack-cli/lib/webpack-cli.js:1406:38)
[@grafana-plugins/grafana-azure-monitor-datasource]:     at /tmp/grafana-11.1.3/node_modules/webpack-cli/lib/webpack-cli.js:1460:88
[@grafana-plugins/grafana-azure-monitor-datasource]:     at Array.map (<anonymous>)
[@grafana-plugins/grafana-azure-monitor-datasource]:     at WebpackCLI.loadConfig (/tmp/grafana-11.1.3/node_modules/webpack-cli/lib/webpack-cli.js:1460:68) {
[@grafana-plugins/grafana-azure-monitor-datasource]:   code: 'MODULE_NOT_FOUND',
[@grafana-plugins/grafana-azure-monitor-datasource]:   requireStack: [
[@grafana-plugins/grafana-azure-monitor-datasource]:     '/tmp/grafana-11.1.3/node_modules/webpack-cli/lib/webpack-cli.js',
[@grafana-plugins/grafana-azure-monitor-datasource]:     '/tmp/grafana-11.1.3/node_modules/webpack-cli/lib/bootstrap.js',
[@grafana-plugins/grafana-azure-monitor-datasource]:     '/tmp/grafana-11.1.3/node_modules/webpack-cli/bin/cli.js',
[@grafana-plugins/grafana-azure-monitor-datasource]:     '/tmp/grafana-11.1.3/node_modules/webpack/bin/webpack.js'
[@grafana-plugins/grafana-azure-monitor-datasource]:   ]
[@grafana-plugins/grafana-azure-monitor-datasource]: }
[@grafana-plugins/grafana-azure-monitor-datasource]: Process exited (exit code 2), completed in 4s 535ms
```
One instance of these errors per plugin

### What did you expect to happen?

I expected grafana to be buildable.

### Did this work before?

No

### How do we reproduce it?

1. pkg install go122 yarn gmake go-wire
2. cd <grafana source dir>
3. gmake

(might also need to symlink /usr/local/go122/bin/go -> /usr/local/bin/go) as FreeBSD 14 is still primarily on go 1.21 as the system Go version

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 11.1.3
OS: FreeBSD 14.1-RELEASE (amd64)
Browser: N/A

### Grafana platform?

Other

**Comment by eriksejr** [comment]
I switched to Linux for this, it seems FreeBSD is not well supported.
