### ISSUE TITLE
[Error]Cannot read property 'type' of null

### ISSUE THREAD

**Issue by hykych** [grafana/grafana#9254]
I'm using grafana 4.5.0-8805beta1 and the plugin simple-json-datasource.
```
Here's the error message:
TypeError: Cannot read property 'type' of null
    at a.getAutoDetectXAxisMode (https://logs.open-staging.cloud.mi.com/public/app/boot.0f46d340.js:20:1655)
    at a.getSeriesList (https://logs.open-staging.cloud.mi.com/public/app/boot.0f46d340.js:20:1297)
    at b.onDataReceived (https://logs.open-staging.cloud.mi.com/public/app/boot.0f46d340.js:20:8837)
    at f.emit (https://logs.open-staging.cloud.mi.com/public/app/boot.0f46d340.js:74:14956)
    at a.emit (https://logs.open-staging.cloud.mi.com/public/app/boot.0f46d340.js:74:17274)
    at b.handleQueryResult (https://logs.open-staging.cloud.mi.com/public/app/boot.0f46d340.js:74:6921)
    at i (https://logs.open-staging.cloud.mi.com/public/app/boot.0f46d340.js:61:17634)
    at https://logs.open-staging.cloud.mi.com/public/app/boot.0f46d340.js:61:18056
    at o.$eval (https://logs.open-staging.cloud.mi.com/public/app/boot.0f46d340.js:61:25211)
    at o.$digest (https://logs.open-staging.cloud.mi.com/public/app/boot.0f46d340.js:61:23684)
```
I wanted to find out if it's because the backend datapoints response, so I used chrome to inspect the page, but when i inspected the page, the error disappeared.

**Comment by torkelo** [comment]
What does your data source return? Make sure you return data in the specified format (see readme for simple data source plugin)
