### ISSUE TITLE
XY PAnel chart does not allow Time as a field when upgrading beyond 10.4.7

### ISSUE THREAD

**Issue by allomorphy** [grafana/grafana#93069]
### What happened?

Hi @leeoniya , others

Our XY Charts which map a value over Time break when upgrading to for example [11.0.4] or current [oss]. 
To get this panel to work again, we need to downgrade back to [10.4.7](https://hub.docker.com/layers/grafana/grafana/10.4.7/images/sha256-232a8fa350015933d54ac5effe67620c8b417d037dbd73e5e97bb94645a9eeec?context=explore)

Besides the fact that this is not ideal, this previous version breaks our gauge dials, which rely on more recent version.
These findings seem quite clear. The gauge panel repeats in a template variable `$analyte`.

Here is what I see when Refreshing browser with the panel graphs.

![Image](https://github.com/user-attachments/assets/228af3a6-7306-4006-b900-d29f352887bc)
```
actions.ts:1028 TypeError: oe.replace is not a function
    at X._replaceWithVariableRegex (template_srv.ts:356:17)
    at X.replace (template_srv.ts:276:17)
    at ar.applyVariables (datasource.ts:273:31)
    at ar.applyTemplateVariables (datasource.ts:185:20)
    at DataSourceWithBackend.ts:181:49
    at Array.map (<anonymous>)
    at ar.query (DataSourceWithBackend.ts:144:29)
    at ar.metricFindQuery (datasource.ts:356:15)
    at oE.runRequest (queryRunners.ts:88:28)
    at uE.onNewRequest (VariableQueryRunner.ts:119:10)
```

and FWIW, here is one of the Exceptions triggered in "actions.ts" line 1028:
```js
    try {
      if (!hasOngoingTransaction(rootStateKey, getState())) {
        // we might have cancelled a batch so then variable state is removed
        return;
      }

      const variableInState = getVariable(identifier, getState());
      dispatch(toKeyedAction(rootStateKey, variableStateFetching(toVariablePayload(variableInState))));
      await dispatch(upgradeLegacyQueries(toKeyedVariableIdentifier(variableInState)));
      await variableAdapters.get(variableInState.type).updateOptions(variableInState);
      dispatch(completeVariableLoading(identifier));
    } catch (error) {
      dispatch(toKeyedAction(rootStateKey, variableStateFailed(toVariablePayload(identifier, { error }))));

      if (!rethrow) {
        console.error(error);
        dispatch(notifyApp(createVariableErrorNotification('Error updating options:', error, identifier)));
      }

      if (rethrow) {
        throw error;
      }
    }
  };
```

(Just in case, we need and love the XY and not Timeseries for certain cases)

### What did you expect to happen?

The Time field to be available
Here it is in the [10.4.7](https://hub.docker.com/layers/grafana/grafana/10.4.7/images/sha256-232a8fa350015933d54ac5effe67620c8b417d037dbd73e5e97bb94645a9eeec?context=explore)

![Image](https://github.com/user-attachments/assets/af53708d-e8f6-4f9f-a289-8a13a86fed18)

### Did this work before?

Yes

### How do we reproduce it?

1. Upgrade and try to sue Time as a field in XY Panel

### Is the bug inside a dashboard panel?

yes

### Environment (with versions)?

Grafana: various
OS: linux
Browser: chrome

### Grafana platform?

Docker

### Datasource(s)?

Influxdb version 1

**Comment by allomorphy** [comment]
- [x] please make sure you have autoMigrateXYChartPanel feature toggle enabled.

**Comment by leeoniya** [comment]
can you share a bit more why you need to use an XYChart here instead of TimeSeries?

**Comment by allomorphy** [comment]
Dear @leeoniya 

Thank you for  picking up this issue.

I have found the Grafana Fu of changing the $timeInterval per Panel a great time sink.
So in the TimeSeries, I have over the years often been given hope that I can robustly and elegantly set **per panel** the viewport or time range.  (I tried today again and just ended up with a 🤕 ).

So the first answer to your question is in this crucial context of taking proper control of the X-Axis with time. The XY Graph *just works*.  It always shows the scale well on X as Time and always encompasses the returned data set well (*almost* entirely well). 

It has some bonuses as well, with setting for size of the data point based on value, color too. See the KRAFT AGE graph above.

In the context of taking control of the X-axis for non-Time is another obvious reason.

I love it.

Right now it crashes when I try to edit it.
I have not said goodbye so reduced it to a little bar below the replacement TimeSeries panel (have not copied over the Overrides in json yet).

Have I convinced you? If not you are super welcoem to login to the instance and feel for your self, the difference in functionality between GF versions 10 and 11 ;-)
Or feel free to see more context in this post made today: 
https://community.grafana.com/t/explicit-time-range-set-per-panel/131598/4

Thanks for your great work here and please elt me know how I could help.

My very best
E

**Comment by leeoniya** [comment]
> I have over the years often been given hope that I can robustly and elegantly set per panel the viewport or time range. (I tried today again and just ended up with a 🤕 ).

the new Scenes architecture supports this, but it's not part of the current dashboarding experience, and is only usable when building Grafana plugins and apps. but this will be possible in the future :)

> Have I convinced you? If not you are super welcoem to login to the instance and feel for your self, the difference in functionality between GF versions 10 and 11 ;-)

i guess i am not completely understanding your use case. it sounds like you have queries that do not include a time range, but instead include something like an id, and the response contains timestamps which you would like to the x axis to scale to? would it be sufficient to instead add an option to TimeSeries (and other time=x panels) that allows it behave in a way that scales x to the available data rather than always following the dashboard time range?

the code to support x=time in xychart is not difficult to add. what i want to point out, however, is that it is _not_ a good replacement for TimeSeries for numerous reasons:

1. the cursor interaction is very different - there is no way to issue new queries during zooming (we do not support changing the dashboard time range via xy selection), so you would have to rely on the time picker for this, which is ergonomically not great.
2. the hover behavior is per-point, so if you have multiple series there is no way to get the TimeSeries hover and tooltip behavior that shows multiple points across series at a specific timestamp.
3. there are much fewer styling options, including lack of area fill, or fill-between, etc.
4. there is no support for stacking
5. the performance for line charts in XY is worse for large datasets, since it cannot have optimizations that assume ordered + unique-x data.
6. etc...

so the problem is, if we add back x=time display in xy, what ends up happening is that people _think_ they can use it for timeseries data and end up opening issues for all the above things that we _do not_ want to add into xy. we have this situation to some extent in BarChart, which supports rendering x=time, but has very different behavior, capabilities, and data frame format from TimeSeries + bars styling.

i do think there is a good use-case for supporting time in XY - when you have a single series with multiple points for the same timestamp. but using xy as a timeseries simply because its x axis is currently tied to the dashboard range feels more like something we can fix in TimeSeries.

what do you think?

**Comment by leeoniya** [comment]
> It has some bonuses as well, with setting for size of the data point based on value, color too. See the KRAFT AGE graph above.

can you attach a screenshot with more data that shows how you use different sized points here?

**Comment by allomorphy** [comment]
Dear @leeoniya 

Thank you for taking this time to explain to me, the users.

I think it might be useful to bring some of us users into the planning.
<rant>When I hit a problem, I tend to spend way too much time trying to recover as I tend to put the blame on my work for far too long. (Like why did that option for Time just vanish - arghhh). </rant>

> the x axis in TimeSeries is currently tied to the dashboard range feels more like something we can fix in TimeSeries.
> what do you think?
 
Oh that would be happy days. Please let us know your timelines for this ;-) 
Meanwhile, if you could please bring me back my Time option for X-Axis. 
(BTW I cannot see in GH any evidence of this change in code).

I would absolutely love the functionality of Scenes and I get why it is a good thing, but
personally, I an just not up to diving into js in this way right now :-( 

I get each of your points 1. to 6. to n.
Right now the styling and overrides are fine for me in your XY and in one respect even better that the TS, see this.
(To answer your confusion, the query does return time and not an other field like is, its super simple), see here:

![Image](https://github.com/user-attachments/assets/deff8ca4-0a8d-432f-a18f-764800fa602b)

Is it not possible to add some of the other features into TimeSeries, like then it will be `ArbitrarySeries` or are there other complexities in implementing the XYChart  capabilities?

As requested, here is the sizing per datapoint which we like to have: 
![Image](https://github.com/user-attachments/assets/89f3b7ad-a750-4539-b84d-ac70ef053ba8)

Meanwhile, I had to reimplement this chart in TimeSeries but without the advantages mentioned in my last message and without this sizing of datapoint either.
![Image](https://github.com/user-attachments/assets/2b1d31d0-578a-489b-b4bf-401586cc1572)

Please let me know if anything is till unclear. Happy to help.

Thank you to you and to all who make Grafana, I love it despite the time it takes when things go wrong :-) 

E

**Comment by allomorphy** [comment]
@leeoniya 
It is not clear to us if there is any scheduling of TimeSeries panel to support the dashboard range to follow the x axis range.
Supporting this will open up a whole bunch of use cases for example with discrete or periodic as opposed to continuous data.

I would be super happy to DM to you access to our dashboard to show the current pain in "**Zoom to data**" as a workaround.

Thanks for your support and response. Much appreciated.

E

**Comment by allomorphy** [comment]
Have we added back Time as a X or has this a ghost?
