### ISSUE TITLE
Grafana: panic: duplicate metrics collector registration attempted

### ISSUE THREAD

**Issue by iXingo** [grafana/grafana#93732]
### What happened?

Grafana HA in k8s keeps restarting after upgrading to 11.2.0

```logger=context userId=0 orgId=0 uname= t=2024-09-25T11:16:46.443291207Z level=info msg="Request Completed" method=GET path=/api/live/ws status=401 remote_addr=10.20.23.164 time_ms=57 duration=57.477184ms size=105 referer= handler=/api/live/ws status_source=server
logger=context userId=0 orgId=0 uname= t=2024-09-25T11:16:46.508649987Z level=info msg="Request Completed" method=GET path=/api/live/ws status=401 remote_addr=10.2.183.95 time_ms=115 duration=115.096985ms size=105 referer= handler=/api/live/ws status_source=server
logger=context userId=0 orgId=0 uname= t=2024-09-25T11:16:46.687381454Z level=info msg="Request Completed" method=GET path=/api/live/ws status=401 remote_addr=10.2.185.72 time_ms=57 duration=57.384203ms size=105 referer= handler=/api/live/ws status_source=server
logger=context userId=0 orgId=0 uname= t=2024-09-25T11:16:47.013982503Z level=info msg="Request Completed" method=GET path=/api/live/ws status=401 remote_addr=10.40.203.235 time_ms=57 duration=57.358175ms size=105 referer= handler=/api/live/ws status_source=server
logger=context userId=0 orgId=0 uname= t=2024-09-25T11:16:47.084198974Z level=info msg="Request Completed" method=GET path=/api/live/ws status=401 remote_addr=10.128.39.243 time_ms=57 duration=57.078356ms size=105 referer= handler=/api/live/ws status_source=server
logger=context userId=0 orgId=0 uname= t=2024-09-25T11:16:47.119125553Z level=info msg="Request Completed" method=GET path=/api/live/ws status=401 remote_addr=10.25.74.50 time_ms=116 duration=116.400854ms size=105 referer= handler=/api/live/ws status_source=server
panic: duplicate metrics collector registration attempted

goroutine 1980 [running]:
github.com/prometheus/client_golang/prometheus.(*wrappingRegisterer).MustRegister(0xc00a9ea120, {0xc0050fe160?, 0x0?, 0x0?})
	github.com/prometheus/client_golang@v1.19.1/prometheus/wrap.go:104 +0x12b
github.com/prometheus/alertmanager/api/metrics.NewAlerts({0x2743d00, 0xc00a9ea120})
	github.com/prometheus/alertmanager@v0.27.0/api/metrics/metrics.go:39 +0x4c9
github.com/grafana/grafana/pkg/services/ngalert/metrics.NewAlertmanagerMetrics({0x2742880, 0xc00282bc70})
	github.com/grafana/grafana/pkg/services/ngalert/metrics/alertmanager.go:21 +0xe5
github.com/grafana/grafana/pkg/services/ngalert/notifier.NewMultiOrgAlertmanager.func1({0x27649c0, 0xc005d900a0}, 0x27)
	github.com/grafana/grafana/pkg/services/ngalert/notifier/multiorg_alertmanager.go:156 +0x85
github.com/grafana/grafana/pkg/services/ngalert/notifier.(*MultiOrgAlertmanager).SyncAlertmanagersForOrgs(0xc0016ca460, {0x27649c0, 0xc005d900a0}, {0xc007f21800, 0x91, 0x1?})
	github.com/grafana/grafana/pkg/services/ngalert/notifier/multiorg_alertmanager.go:304 +0x322
github.com/grafana/grafana/pkg/services/ngalert/notifier.(*MultiOrgAlertmanager).LoadAndSyncAlertmanagersForOrgs(0xc0016ca460, {0x27649c0, 0xc005d900a0})
	github.com/grafana/grafana/pkg/services/ngalert/notifier/multiorg_alertmanager.go:260 +0xce
github.com/grafana/grafana/pkg/services/ngalert/notifier.(*MultiOrgAlertmanager).Run(0xc0016ca460, {0x27649c0, 0xc005d900a0})
	github.com/grafana/grafana/pkg/services/ngalert/notifier/multiorg_alertmanager.go:243 +0xeb
github.com/grafana/grafana/pkg/services/ngalert.(*AlertNG).Run.func1()
	github.com/grafana/grafana/pkg/services/ngalert/ngalert.go:510 +0x26
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.8.0/errgroup/errgroup.go:78 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 7636
	golang.org/x/sync@v0.8.0/errgroup/errgroup.go:75 +0x96
```

### What did you expect to happen?

Grafana runs normal

### Did this work before?

Yes
It works on our dev instance which has less than 10 organizations, but failed on prod with more than 100 organizations

### How do we reproduce it?

1. Upgrade to 11.2.0
2. Create more than 100 orgs
3. running in k8s with 3 replicas

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 11.2.0
OS: Docker/K8s
Browser: chrome

### Grafana platform?

Kubernetes

**Comment by iXingo** [comment]
it's urgent, can anyone have a look?

**Comment by yincongcyincong** [comment]
i think this issue is fixed. just compile newest version  grafana.

**Comment by yincongcyincong** [comment]
> Is there any tag/version ? I see a fix in issue [#92707](https://github.com/grafana/grafana/issues/92707) but the milestone is 11.3.x which is not release yet.

i think you should use lastest main branch to compile.

**Comment by iXingo** [comment]
I still see the similar error on main branch:

```
goroutine 11746 [running]:

github.com/prometheus/client_golang/prometheus.(*wrappingRegisterer).MustRegister(0xc0106720f0, {0xc01062ccc0?, 0x0?, 0x0?})

github.com/prometheus/client_golang@v1.20.3/prometheus/wrap.go:104 +0x12b

github.com/prometheus/alertmanager/api/metrics.NewAlerts({0x24c43a0, 0xc0106720f0})

github.com/prometheus/alertmanager@v0.27.0/api/metrics/metrics.go:39 +0x4bd

github.com/grafana/grafana/pkg/services/ngalert/metrics.NewAlertmanagerMetrics({0x24c2fc0, 0xc0064fe140}, {0x2506430, 0xc002618420})

github.com/grafana/grafana/pkg/services/ngalert/metrics/alertmanager.go:23 +0xe5

github.com/grafana/grafana/pkg/services/ngalert/notifier.NewMultiOrgAlertmanager.func1({0x24e52e0, 0xc007f900a0}, 0x48)

github.com/grafana/grafana/pkg/services/ngalert/notifier/multiorg_alertmanager.go:161 +0xa7

github.com/grafana/grafana/pkg/services/ngalert/notifier.(*MultiOrgAlertmanager).SyncAlertmanagersForOrgs(0xc0001ae870, {0x24e52e0, 0xc007f900a0}, {0xc00ec91800, 0x92, 0xc007e14000?})

github.com/grafana/grafana/pkg/services/ngalert/notifier/multiorg_alertmanager.go:308 +0x322

github.com/grafana/grafana/pkg/services/ngalert/notifier.(*MultiOrgAlertmanager).LoadAndSyncAlertmanagersForOrgs(0xc0001ae870, {0x24e52e0, 0xc007f900a0})

github.com/grafana/grafana/pkg/services/ngalert/notifier/multiorg_alertmanager.go:264 +0xce

github.com/grafana/grafana/pkg/services/ngalert/notifier.(*MultiOrgAlertmanager).Run(0xc0001ae870, {0x24e52e0, 0xc007f900a0})

github.com/grafana/grafana/pkg/services/ngalert/notifier/multiorg_alertmanager.go:247 +0xeb

github.com/grafana/grafana/pkg/services/ngalert.(*AlertNG).Run.func1()

github.com/grafana/grafana/pkg/services/ngalert/ngalert.go:536 +0x26

golang.org/x/sync/errgroup.(*Group).Go.func1()

golang.org/x/sync@v0.8.0/errgroup/errgroup.go:78 +0x50

created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 11471

golang.org/x/sync@v0.8.0/errgroup/errgroup.go:75 +0x96
```

**Comment by iXingo** [comment]
#76809

**Comment by yincongcyincong** [comment]
@iXingo bro. please use my fixed branch to compile. i'm not sure the bug is fixed or not.
https://github.com/grafana/grafana/pull/93951

**Comment by santihernandezc** [comment]
Hi @iXingo , thanks for creating this bug report.
I confirmed that the issue persists. I've reopened https://github.com/grafana/grafana/issues/92707, so I'm closing this issue in favor of the older one.
