### ISSUE TITLE
After upgrading to 11.3.0, "direct link rended image" generate an error and a tiemout before handling the image

### ISSUE THREAD

**Issue by meepmeep** [grafana/grafana#95268]
### What happened?

After upgrading to 11.3.0 (debian stable package), the **Direct link rendered image** generate an error and need more than 1min to generate the image 
(with an error generating a timeout of 60sec "Error while waiting for the panels to load" url="http://10.0.0.103:3000/xyz")

Error log : 
`2024-10-23T16:52:33.070198+02:00 firefly grafana[3868329]: logger=plugin.grafana-image-renderer t=2024-10-23T16:52:33.069751781+02:00 level=error msg="Error while waiting for the panels to load" url="http://10.0.0.103:3000/d-solo/dcb32b6d-c08f-40ae-a0c6-651cb3191d21/irc?orgId=1&theme=dark&panelId=3&width=1000&height=500&tz=Europe%2FParis&render=1" err="TimeoutError: waiting for function failed: timeout 60000ms exceeded\n    at new WaitTask (/snapshot/src/node_modules/puppeteer/lib/cjs/puppeteer/common/IsolatedWorld.js:445:34)\n    at IsolatedWorld.waitForFunction (/snapshot/src/node_modules/puppeteer/lib/cjs/puppeteer/common/IsolatedWorld.js:349:26)\n    at Frame.waitForFunction (/snapshot/src/node_modules/puppeteer/lib/cjs/puppeteer/common/Frame.js:479:59)\n    at Page.waitForFunction (/snapshot/src/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2446:33)\n    at /snapshot/src/build/browser/browser.js:289:29\n    at Browser.withTimingMetrics (/snapshot/src/build/browser/browser.js:417:20)\n    at Browser.takeScreenshot (/snapshot/src/build/browser/browser.js:285:24)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async Browser.render (/snapshot/src/build/browser/browser.js:235:20)\n    at async PluginGRPCServer.render (/snapshot/src/build/plugin/v2/grpc_plugin.js:116:13)"`

### What did you expect to happen?

With previous version (11.2.2-01), generating the image took between 3 and 4 sec.

### Did this work before?

Yes. I rolled back to v11.2.2-01, and no error showed up in the logs while generating the image in 3sec.

### How do we reproduce it?

1. upgrade to 11.3.0
2. use a direct link rended image like this "http://10.0.0.103:3000/render/d-solo/dcb32b6d-c08f-40ae-a0c6-651cb3191d21?from=now-24h&to=now&timezone=Europe%2FParis&theme=dark&panelId=panel-4&__feature.dashboardSceneSolo&width=1000&height=500&tz=Europe%2FParis" 
3. wait for the timeout and error message in the log.

### Environment (with versions)?

Grafana: 11.3.0
OS: debian12
Browser: chrome, firefox, wget request. 

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

mysql

**Comment by meepmeep** [comment]
Solved. Rendering service must been update in the same time ;)
`grafana-cli plugins install grafana-image-renderer`

`✔ Downloaded and extracted grafana-image-renderer v3.11.6 zip successfully to /var/lib/grafana/plugins/grafana-image-renderer`

Since that, render is done in few seconds.
