### ISSUE TITLE
Transformations: Group to nested table - Short description of bug

### ISSUE THREAD

**Issue by igor-raits** [grafana/grafana#95747]
### What happened?

I use group to nested table transformation, and when the table is empty, using calculate "all unique values" (or any other calculation) fails with the error:

```
Error transforming data: Cannot read properties of undefined (reading 'length')
```

The full trace that I see in the browser's console:

```
zone.js:163 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at P (processDataFrame.ts:258:36)
    at y (groupToNestedTable.ts:196:14)
    at groupToNestedTable.ts:120:39
    at map.js:7:37
    at C.L._next (OperatorSubscriber.js:15:21)
    at ne.next (Subscriber.js:34:18)
    at U._subscribe (innerFrom.js:51:24)
    at U._trySubscribe (Observable.js:38:25)
    at Observable.js:32:31
    at p (errorContext.js:19:9)
```

I don't know if it is helpful but those lines are

```
--> aggregationField.type = detectFieldType(aggregation, field, aggregationField);
----> return guessFieldTypeForField(targetField) ?? FieldType.string;
------>  // 2. Check the first non-null value
------>  for (let i = 0; i < field.values.length; i++) {
```

1. Actual data table after few transformations (i.e. empty)
![Image](https://github.com/user-attachments/assets/9ca0dda5-6358-4670-a2ca-870ff2efe53a)
2. Enabling group by on one of the fields (no errors)
![Image](https://github.com/user-attachments/assets/86e1950e-e5c3-44a7-9e91-689aa09790f3)
3. Setting up "Calculate all unique values"
![Image](https://github.com/user-attachments/assets/49a51e70-6cf8-4635-8433-ffc07cf4afa4)

### What did you expect to happen?

I expect table to be rendered without error and simply show No Data.

### Did this work before?

I don't think so but it is not something I have been using for months. IOW, no.

### How do we reproduce it?

1. Get empty table
2. Group to nested tables
3. Use group by + calculate all values

### Environment (with versions)?

Grafana: v11.3.0 (d9455ff7db)
OS: Fedora 41
Browser: `google-chrome-stable-130.0.6723.91-1.x86_64`

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by ignatenkobrain** [comment]
If it helps with anything, I've tried to add couple of breakpoints to get more info about data structures:
![Image](https://github.com/user-attachments/assets/4bc87119-ccaa-4f21-aa85-fe16150ce056)
