### ISSUE TITLE
[Bug] 4.6 Single Stat Cannot read property 'length' of null

### ISSUE THREAD

**Issue by jveldboom** [grafana/grafana#9717]
Version: v4.6.0 (commit: c47f670)
Datasource: CloudWatch
OS: Docker

I'm using the single stat panel to return a CloudWatch custom metric. The query and panel worked great on v4.5 but after upgrading to 4.6, it no longer works for queries that do not return any metrics for date range.

Previously I would just add a Value Mappings for `null -> 0` which worked great. But with 4.6, I'm seeing the red exclamation with the error`Cannot read property 'length' of null` - clicking into shows the following error:

```
TypeError: Cannot read property 'length' of null
    at t.isMsResolutionNeeded (http://example.com:3000/public/build/0.bf07efaa01feb8a3f70b.js:1:8586)
    at new t (http://example.com:3000/public/build/0.bf07efaa01feb8a3f70b.js:1:5491)
    at e.seriesHandler (http://example.com:3000/public/build/0.bf07efaa01feb8a3f70b.js:7:274818)
    at Array.map (<anonymous>)
    at e.onDataReceived (http://example.com:3000/public/build/0.bf07efaa01feb8a3f70b.js:7:274694)
    at o.emit (http://example.com:3000/public/build/vendor.2305a8e1d478628b1297.js:15:520749)
    at t.emit (http://example.com:3000/public/build/app.3534da5bfa35355f5abb.js:1:29207)
    at e.handleQueryResult (http://example.com:3000/public/build/0.bf07efaa01feb8a3f70b.js:7:19860)
    at u (http://example.com:3000/public/build/vendor.2305a8e1d478628b1297.js:43:68722)
    at http://example.com:3000/public/build/vendor.2305a8e1d478628b1297.js:43:69127
```

![image](https://user-images.githubusercontent.com/303202/32149434-d0aba01c-bcda-11e7-934e-30e27bd53334.png)

I also have the thresholds set to `10,30` along with the Value Mapping of `null -> 0", but the error prevents that from working. The panel just shows black with zero. If I remove the Value Mapping, the panel will show "no value".

The issue is very reproducible, so please let me know if you need any more information from me.

**Comment by mcripster** [comment]
I am seeing a similar error as well.
```
TypeError: Cannot read property 'length' of null
    at t.updateRowSpan (row_model.ts:46)
    at new t (row_model.ts:32)
    at new t (model.ts:81)
    at t.create (dashboard_srv.ts:25)
    at t.setupDashboardInternal (dashboard_ctrl.ts:44)
    at t.setupDashboard (dashboard_ctrl.ts:35)
    at t.init (dashboard_ctrl.ts:137)
    at t.initDashboard (grafana_app.ts:38)
    at app.8849fc3d424a44caa6fc.js:18753
    at u (angular.js:17051) true
```

**Comment by cburn-r7** [comment]
This is also happening with me on Grafana 4.6: I am using the new Postgres plugin and trying to query my DB with the Pie Chart plugin. I am formatting the data as Table, not Time Series. The query is working in my pgadmin database IDE, and I was wondering whether I was making a mistake, or whether this is a bug.

`TypeError: Cannot read property 'length' of undefined
    at t.isMsResolutionNeeded (http://ec2-x-x-x-x.compute-1.amazonaws.com:xxxx/public/build/xxx.js:1:8586)
    at new t (http://ec2-x-x-x-x.compute-1.amazonaws.com:xxxx/public/build/xxx.js:1:5491)
    at PieChartCtrl.seriesHandler (http://ec2-x-x-x-x.compute-1.amazonaws.com:xxxx/public/plugins/grafana-piechart-panel/piechart_ctrl.js:169:26)
    at Array.map (<anonymous>)
    at PieChartCtrl.onDataReceived (http://ec2-x-x-x-x.compute-1.amazonaws.com:xxxx/public/plugins/grafana-piechart-panel/piechart_ctrl.js:162:36)
    at o.emit (http://ec2-x-x-x-x.compute-1.amazonaws.com:xxxx/public/build/vendor.xxx.js:15:521182)
    at t.emit (http://ec2-x-x-x-x.compute-1.amazonaws.com:xxxx/public/build/app.xxxx.js:1:29207)
    at PieChartCtrl.e.handleQueryResult (http://ec2-x-x-x-x.compute-1.amazonaws.com:xxxx/public/build/xxx.js:7:19860)
    at u (http://ec2-x-x-x-x.compute-1.amazonaws.com:xxxx/public/build/vendor.xxx.js:43:68722)`

**Comment by torkelo** [comment]
not sure the pie chart panel supports table data, think it only supports time series

**Comment by bergquist** [comment]
Should be fixed by https://github.com/grafana/grafana/pull/9856
