### ISSUE TITLE
Alerting: `Unexpected error` in alert details page when `ruleGroup` is not specified in rule provisioning API

### ISSUE THREAD

**Issue by j-svensmark** [grafana/grafana#97475]
### What happened?

After clicking the `view` button to access the details of an Alert, a page with `An unexpected error happened` appears.
![Image](https://github.com/user-attachments/assets/518c22ae-4d97-462c-af6d-e037e176d4d7)
![Image](https://github.com/user-attachments/assets/1d655112-ac5c-49c5-b394-0d7cab0de8cd)

<details>

<summary>Error text</summary>

```
TypeError: Cannot read properties of undefined (reading 'filter')

    at p (http://localhost:3000/public/build/3729.ffff83737929c19134ef.js:337:47124)
    at g (http://localhost:3000/public/build/3729.ffff83737929c19134ef.js:63:134080)
    at a (http://localhost:3000/public/build/3729.ffff83737929c19134ef.js:63:134589)
    at WithErrorBoundary
    at Suspense
    at g (http://localhost:3000/public/build/3729.ffff83737929c19134ef.js:63:134080)
    at mu (http://localhost:3000/public/build/3729.ffff83737929c19134ef.js:4418:11814)
    at I (http://localhost:3000/public/build/3855.c53eb219979d7cb3b2d4.js:997:29132)
    at wo (http://localhost:3000/public/build/3855.c53eb219979d7cb3b2d4.js:988:4451)
    at ms (http://localhost:3000/public/build/3855.c53eb219979d7cb3b2d4.js:988:12000)
    at Vt (http://localhost:3000/public/build/3855.c53eb219979d7cb3b2d4.js:997:17388)
    at I (http://localhost:3000/public/build/3855.c53eb219979d7cb3b2d4.js:997:31288)
    at div
    at http://localhost:3000/public/build/3729.ffff83737929c19134ef.js:82:52960
    at main
    at div
    at div
    at div
    at Pg (http://localhost:3000/public/build/3729.ffff83737929c19134ef.js:4418:2373)
    at div
    at Hc (http://localhost:3000/public/build/3729.ffff83737929c19134ef.js:4418:7141)
    at wo (http://localhost:3000/public/build/3855.c53eb219979d7cb3b2d4.js:988:4451)
    at ms (http://localhost:3000/public/build/3855.c53eb219979d7cb3b2d4.js:988:12000)
    at _s (http://localhost:3000/public/build/3855.c53eb219979d7cb3b2d4.js:988:11336)
    at Sr (http://localhost:3000/public/build/3855.c53eb219979d7cb3b2d4.js:997:17687)
    at y (http://localhost:3000/public/build/3729.ffff83737929c19134ef.js:5:284076)
    at I (http://localhost:3000/public/build/3855.c53eb219979d7cb3b2d4.js:997:25385)
    at v (http://localhost:3000/public/build/3855.c53eb219979d7cb3b2d4.js:164:9002)
    at E (http://localhost:3000/public/build/3855.c53eb219979d7cb3b2d4.js:1427:112967)
    at o (http://localhost:3000/public/build/3729.ffff83737929c19134ef.js:335:27877)
    at g (http://localhost:3000/public/build/3729.ffff83737929c19134ef.js:63:134080)
    at a (http://localhost:3000/public/build/3729.ffff83737929c19134ef.js:63:134589)
    at ht (http://localhost:3000/public/build/3855.c53eb219979d7cb3b2d4.js:1431:508)
    at bu (http://localhost:3000/public/build/3729.ffff83737929c19134ef.js:4418:13861)
```
</details>

### What did you expect to happen?

The alert details page shows up with no errors.

Alternatively, if `ruleGroup` is a required value of the `provisioning/alert-rules` API, omitting it should return an error.

### Did this work before?

Yes, it worked in Grafana 11.0.9, but stopped working since 11.1.0

### How do we reproduce it?

1. Launch Grafana (here using Docker as an example)
```sh
docker run -e GF_AUTH_ANONYMOUS_ENABLED=true -e GF_AUTH_ANONYMOUS_ORG_ROLE=Admin -p 3000:3000 --name=grafana grafana/grafana:11.2.0
```
2. Create folder and get its UID (here using `jq`, can also be extracted manually from the response)
```
FOLDER_UID=$(curl -X POST -H 'Content-Type: application/json' -d '{"title": "test_folder"}' http://localhost:3000/api/folders | jq '.uid')
```
3. Create an alert, calling without the `ruleGroup` value
```sh
curl -X POST -H 'Content-Type: application/json' -d '
{
  "title": "TEST-API_3",
  "folderUID": '$FOLDER_UID',
  "noDataState": "OK",
  "execErrState": "OK",
  "for": "5m",
  "orgId": 1,
  "uid": "",
  "condition": "A",
  "data": [
    {
      "refId": "A",
      "queryType": "",
      "relativeTimeRange": {
        "from": 600,
        "to": 0
      },
      "datasourceUid": "XXXXXXXXX-XXXXXXXXX-XXXXXXXXXX",
      "model": {
        "expr": "up",
        "hide": false,
        "intervalMs": 1000,
        "maxDataPoints": 43200,
        "refId": "A"
      }
    }
  ]
}
' http://0.0.0.0:3000/api/v1/provisioning/alert-rules
```
4. Access the Grafana instance at http://0.0.0.0:3000, go to `Alert rules`, expand the alert folder and click the `view` button.

### Environment (with versions)?

Grafana: 11.1.0+
OS: Grafana default docker OS
Browser: Chrome

### Grafana platform?

None

**Comment by alexander-akhmetov** [comment]
Thanks for reporting this! It is indeed a bug, rule groups are not optional in the provisioning API.
