### ISSUE TITLE
Dashboards: Dashboard Crashes with Javascript exceptions when working with NULL variable values

### ISSUE THREAD

**Issue by tamirfren** [grafana/grafana#97684]
### What happened?

When a dashboard variable has NULL as one of it's possible values (For example as one of the results from an SQL query), It's very easy when interacting with the variable picker to encounter issues that cause a complete crash of the dashboard from a Javascript exception - As shown in this image
![Image](https://github.com/user-attachments/assets/3fe34d47-64a2-4ddc-a307-397737fa367a)
Actions that cause this crash include:

1. Clicking checkbox to select all variables (As opposed to the "All" option)
2. Entering various letters in the text filter field, including but possibly not limited to - "n","e","u","i","f". These only cause the crash if they are the first letters in the text box
3. Selecting the NULL option if variable is multi-select

The specific error varies based on whichever of these I do, though they seem to be pretty similar. The text for the first crash is
`TypeError: Cannot read properties of null (reading 'value')

    at G (https://****/public/build/3719.c065b2e146c4c8347d51.js:1:147070)
    at ne
    at ue (https://****/public/build/9636.b941a14f2c41910ad58c.js:39:177215)
    at Wd.Component (https://****/public/build/9636.b941a14f2c41910ad58c.js:39:292851)
    at Jt (https://****/public/build/9636.b941a14f2c41910ad58c.js:39:138768)
    at div
    at om (https://****/public/build/9636.b941a14f2c41910ad58c.js:39:333577)
    at h0 (https://****/public/build/9636.b941a14f2c41910ad58c.js:39:333382)
    at Jt (https://****/public/build/9636.b941a14f2c41910ad58c.js:39:138768)
    at div
    at https://****/public/build/3719.c065b2e146c4c8347d51.js:1:135436
    at div
    at m (https://****/public/build/322.5df7dbfcd22d85fc7794.js:278:26159)
    at Jt (https://****/public/build/9636.b941a14f2c41910ad58c.js:39:138768)
    at div
    at div
    at st (https://****/public/build/322.5df7dbfcd22d85fc7794.js:275:243793)
    at div
    at div
    at Qe (https://****/public/build/322.5df7dbfcd22d85fc7794.js:275:242733)
    at Jt (https://****/public/build/9636.b941a14f2c41910ad58c.js:39:138768)
    at div
    at X (https://****/public/build/322.5df7dbfcd22d85fc7794.js:194:22907)
    at es (https://****/public/build/322.5df7dbfcd22d85fc7794.js:278:51414)
    at Jt (https://****/public/build/9636.b941a14f2c41910ad58c.js:39:138768)
    at W0 (https://****/public/build/9636.b941a14f2c41910ad58c.js:39:352435)
    at In (https://****/public/build/8779.3554bbccc2f934cb55f3.js:1:2522)
    at Xo (https://****/public/build/8779.3554bbccc2f934cb55f3.js:51:32923)
    at Suspense
    at g (https://****/public/build/322.5df7dbfcd22d85fc7794.js:12:133441)
    at th (https://****/public/build/322.5df7dbfcd22d85fc7794.js:2378:39173)
    at tt (https://****/public/build/9636.b941a14f2c41910ad58c.js:295:25340)
    at Re (https://****/public/build/9636.b941a14f2c41910ad58c.js:295:4574)
    at ot (https://****/public/build/9636.b941a14f2c41910ad58c.js:295:12212)
    at zt (https://****/public/build/9636.b941a14f2c41910ad58c.js:286:18055)
    at tt (https://****/public/build/9636.b941a14f2c41910ad58c.js:295:27534)
    at div
    at https://****/public/build/3719.c065b2e146c4c8347d51.js:1:135436
    at main
    at div
    at div
    at div
    at Pf (https://****/public/build/322.5df7dbfcd22d85fc7794.js:2380:4677)
    at Af (https://****/public/build/322.5df7dbfcd22d85fc7794.js:2380:9995)
    at Re (https://****/public/build/9636.b941a14f2c41910ad58c.js:295:4574)
    at ot (https://****/public/build/9636.b941a14f2c41910ad58c.js:295:12212)
    at Ke (https://****/public/build/9636.b941a14f2c41910ad58c.js:295:11545)
    at un (https://****/public/build/9636.b941a14f2c41910ad58c.js:286:18357)
    at v (https://****/public/build/322.5df7dbfcd22d85fc7794.js:5:188553)
    at tt (https://****/public/build/9636.b941a14f2c41910ad58c.js:295:21503)
    at Kc (https://****/public/build/322.5df7dbfcd22d85fc7794.js:2380:11398)
    at div
    at Xl (https://****/public/build/322.5df7dbfcd22d85fc7794.js:2378:18744)
    at y (https://****/public/build/9636.b941a14f2c41910ad58c.js:151:9173)
    at C (https://****/public/build/4239.c2eca2b0222ddf40980b.js:183:17550)
    at d (https://****/public/build/3719.c065b2e146c4c8347d51.js:24:12171)
    at g (https://****/public/build/322.5df7dbfcd22d85fc7794.js:12:133441)
    at i (https://****/public/build/322.5df7dbfcd22d85fc7794.js:12:133950)
    at pn (https://****/public/build/4239.c2eca2b0222ddf40980b.js:187:507)
    at jf (https://****/public/build/322.5df7dbfcd22d85fc7794.js:2380:13056)`
This issue clears on Refresh (They all happen before the variable is actually chosen so the URL stays the same)

### What did you expect to happen?

I expect mostly for the dashboard to not crash from these values. If the null values still have weird behaviors or are filtered out that's okay, but I expect the dashboards to mostly work in one way or another for places we haven't yet excluded those null values manually from the options.

### Did this work before?

I recently upgraded from version 10.3.5, and we haven't had any issues with the exact same dashboards and queries before the upgrade.

### How do we reproduce it?

1.Create a variable in a dashboard with "Query" data source, with at least one of the selected values being null (Including just doing a UNION with `Select NULL`)
2.In the dashboard view, click on the variable pick box and attempt any of the actions mentioned above

### Environment (with versions)?

Grafana: 11.3.1
Browser: Chrome

### Grafana platform?

Docker

**Comment by mkoglinhne** [comment]
Similar behavior with Grafana 11.4.0. Handling of null-values still failing.

**Comment by gelicia** [comment]
Hello, this should have been fixed as of 12.1 by this PR https://github.com/grafana/grafana/pull/106094

Can someone verify and let me know?
