### ISSUE TITLE
Dashboard: crash entering data into search field

### ISSUE THREAD

**Issue by ghaushe-ampere** [grafana/grafana#97983]
### What happened?

When entering data into a mysql populated search field, grafana immediately crashes.
This happens only for the characters: d,e,f,i,n.u

I get the following trace:
```
An unexpected error happened
Details
TypeError: Cannot read properties of undefined (reading 'match')

    at j (https://mydomain.com/grafana/public/build/1518.a3f1f690c084a37f01c7.js:39:176078)
    at lp.Component (https://mydomain.com/grafana/public/build/1518.a3f1f690c084a37f01c7.js:39:309116)
    at Jt (https://mydomain.com/grafana/public/build/1518.a3f1f690c084a37f01c7.js:39:138757)
    at div
    at Bm (https://mydomain.com/grafana/public/build/1518.a3f1f690c084a37f01c7.js:39:350510)
    at SS (https://mydomain.com/grafana/public/build/1518.a3f1f690c084a37f01c7.js:39:350315)
    at Jt (https://mydomain.com/grafana/public/build/1518.a3f1f690c084a37f01c7.js:39:138757)
    at div
    at https://mydomain.com/grafana/public/build/3719.c065b2e146c4c8347d51.js:1:135436
    at div
    at m (https://mydomain.com/grafana/public/build/322.177b4bb01c5d74f9b28f.js:278:26159)
    at Jt (https://mydomain.com/grafana/public/build/1518.a3f1f690c084a37f01c7.js:39:138757)
    at div
    at div
    at n (https://mydomain.com/grafana/public/build/322.177b4bb01c5d74f9b28f.js:159:37441)
    at div
    at X (https://mydomain.com/grafana/public/build/322.177b4bb01c5d74f9b28f.js:194:22907)
    at es (https://mydomain.com/grafana/public/build/322.177b4bb01c5d74f9b28f.js:278:51414)
    at Jt (https://mydomain.com/grafana/public/build/1518.a3f1f690c084a37f01c7.js:39:138757)
    at VS (https://mydomain.com/grafana/public/build/1518.a3f1f690c084a37f01c7.js:39:368708)
    at In (https://mydomain.com/grafana/public/build/8779.e255d939a1787b5617b6.js:1:2522)
    at Xo (https://mydomain.com/grafana/public/build/8779.e255d939a1787b5617b6.js:51:32923)
    at Suspense
    at g (https://mydomain.com/grafana/public/build/322.177b4bb01c5d74f9b28f.js:12:133441)
    at th (https://mydomain.com/grafana/public/build/322.177b4bb01c5d74f9b28f.js:2378:39173)
    at tt (https://mydomain.com/grafana/public/build/1518.a3f1f690c084a37f01c7.js:295:25390)
    at Re (https://mydomain.com/grafana/public/build/1518.a3f1f690c084a37f01c7.js:295:4581)
    at ot (https://mydomain.com/grafana/public/build/1518.a3f1f690c084a37f01c7.js:295:12260)
    at zt (https://mydomain.com/grafana/public/build/1518.a3f1f690c084a37f01c7.js:286:18058)
    at tt (https://mydomain.com/grafana/public/build/1518.a3f1f690c084a37f01c7.js:295:27584)
    at div
    at https://mydomain.com/grafana/public/build/3719.c065b2e146c4c8347d51.js:1:135436
    at main
    at div
    at div
    at div
    at Pf (https://mydomain.com/grafana/public/build/322.177b4bb01c5d74f9b28f.js:2380:4677)
    at Af (https://mydomain.com/grafana/public/build/322.177b4bb01c5d74f9b28f.js:2380:9995)
    at Re (https://mydomain.com/grafana/public/build/1518.a3f1f690c084a37f01c7.js:295:4581)
    at ot (https://mydomain.com/grafana/public/build/1518.a3f1f690c084a37f01c7.js:295:12260)
    at Ke (https://mydomain.com/grafana/public/build/1518.a3f1f690c084a37f01c7.js:295:11590)
    at un (https://mydomain.com/grafana/public/build/1518.a3f1f690c084a37f01c7.js:286:18360)
    at v (https://mydomain.com/grafana/public/build/322.177b4bb01c5d74f9b28f.js:5:188553)
    at tt (https://mydomain.com/grafana/public/build/1518.a3f1f690c084a37f01c7.js:295:21551)
    at Kc (https://mydomain.com/grafana/public/build/322.177b4bb01c5d74f9b28f.js:2380:11398)
    at div
    at Xl (https://mydomain.com/grafana/public/build/322.177b4bb01c5d74f9b28f.js:2378:18744)
    at y (https://mydomain.com/grafana/public/build/1518.a3f1f690c084a37f01c7.js:151:9173)
    at C (https://mydomain.com/grafana/public/build/4239.c2eca2b0222ddf40980b.js:183:17550)
    at d (https://mydomain.com/grafana/public/build/3719.c065b2e146c4c8347d51.js:24:12171)
    at g (https://mydomain.com/grafana/public/build/322.177b4bb01c5d74f9b28f.js:12:133441)
    at i (https://mydomain.com/grafana/public/build/322.177b4bb01c5d74f9b28f.js:12:133950)
    at pn (https://mydomain.com/grafana/public/build/4239.c2eca2b0222ddf40980b.js:187:507)
    at jf (https://mydomain.com/grafana/public/build/322.177b4bb01c5d74f9b28f.js:2380:13056)
```

### What did you expect to happen?

filtering of variable values

### Did this work before?

unkown

### How do we reproduce it?

dashboard with a variable defined as a mysql source, which produces ~600 entries.  'Sort Disabled', 'On dashboard load' selected.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 11.04
OS: docker
Browser: chrome (any)

### Grafana platform?

Docker

### Datasource(s)?

Mysql

**Comment by ghaushe-ampere** [comment]
We root caused this to having a null value in the mysql results.  eliminating that resolved the issue, but i still don't think grafana should stack-trace
